fix: Skip adding url parameter template if already present
vaadin/flow pull request #10001
Opened 2021-02-09 15:34 UTC by mshabarov

Fixes https://github.com/vaadin/flow/issues/9973

2021-02-10 10:23 UTC, denis-anisimov requested changes

2021-02-10 10:23 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/router/internal/HasUrlParameterFormat.java
> +        if (hasUrlParameter(navigationTarget) && !hasUrlTemplate(urlBase)) {
Why would I call `getTemplate`  method at all for `urlBase` with PARAMETER ?

It looks like the fix should be done in a different place: `urlBase` should not contain unexpected strings at all and there should be a check for that (or assertion).

And the caller should just not call the `getTemplate` method at all (under some conditions).
So the fix should be done in the caller (not sure which level) and not here.

2021-02-10 13:34 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/router/internal/HasUrlParameterFormat.java
> +        if (hasUrlParameter(navigationTarget) && !hasUrlTemplate(urlBase)) {
Now the client (caller) code verifies, that the given navigation target is a `HasUrlParameter` instance and the path does not contain the template, and only then call `getTemplate`.

`getTemplate` now throws if the unexpected path comes, or the passed navigation target is not a `HasUrlParameter`.

2021-02-10 14:05 UTC, denis-anisimov requested changes

2021-02-10 14:05 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +            path = HasUrlParameterFormat.getTemplate(path, navigationTarget);
This just transfers the check from the final place to the intermediate place.

The main question which I would like to understand and get fixed: _why_ the path which is passed as a parameter here may contain PARAMETER at all?
The _here_ means the first call in the stack trace of this method call: I will transfer this question along with traveling this  check to the caller.

I think the bug is: `path`  which is passed at the beginning of the call (may be somewhere in the route registry code) is wrong. It should never contains already PARAMETER.
Most likely the route is registered being registered once (may be being deregistered) and the second registration causes incorrect behavior.

This PR in its initial state and now just hides the symptoms but doesn't fix the original issue.

2021-02-10 14:36 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +            path = HasUrlParameterFormat.getTemplate(path, navigationTarget);
> Most likely the route is registered being registered once (may be being deregistered) and the second registration causes incorrect behavior.

This is very close to true I believe. The initial route registration causes no errors. Every path, which has a url parameter, is being extended with a pattern, as expected.

The issue occurs when the `RoutesChangedEvent` is fired as a result of routes update (next step after setting a new routes), and then the existing routes are copied to a OSGi route configuration.

That means the path is being copied too, and those paths with url parameters are passing through the `setRoute` method, which tries to add (again!) a template to them.

Well, I can explicitly add the `getTemplate` method call to the points, where I know in advance that the route (path) is created from navigation target class (i.e. a brand new route), and skip templates when the routes are being copied or removed.
This has a drawback though - this mutation points will be distributed along the code in several point and this is error-prone solution IMO, but technically more correct.
Will do it this way.

2021-02-10 17:41 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +            path = HasUrlParameterFormat.getTemplate(path, navigationTarget);
>That means the path is being copied too, and those paths with url parameters are passing through the setRoute method, which tries to add (again!) a template to them.

Looks like this is the place which should be fixed.
There should be either API which returns the path without template or the path should be converted back (somehow) so that it becomes the same as it was in the very first registration.
As I understand the API is weak at the moment: it always return the modified path and doesn't return the original path.
That should be just fixed.

2021-02-11 14:38 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +            path = HasUrlParameterFormat.getTemplate(path, navigationTarget);
I've reverted the previous source code changes and changed only the part where the routes updates are being fired to another route registry.
So, basically, from a high level point of view, those changes impacts only the part which is in `2.4`, but not in `6.0+`.

I found nothing better than just to trim the urls from the original registry, to having no param template there -> and then this template is added via normal `setRoute` functionality.

This has a drawback that if someone will want to get the route from registry and add it again in another registry, then he will have to do the same hack. But this scenario is not that possible IMO.

Please give your opinion about the approach I've pushed. If it's fine, I would add the rest of the tests and javadoc.

2021-02-12 06:27 UTC, denis-anisimov requested changes
This can go with that solution.

I still don't like the solution since it makes assumptions: it assumes that the navigation route being added into registry contains a PARAMETER which may be safely removed.
These are quite fragile assumptions.

At the moment this is localized to OSGi which has quite hacky implementation from the very beginning so we may keep this working this way.

BUT OSGi case reveals this as a common problem: one may not use the registry to remove a route from there and add the same route either in the same registry or another.
I may imaging that I want to register Routes via `@Route`  annotation, then modify routes at runtime so that some routes are removed and then at some point I want to restore the routes back. And this is no such way to do it properly.
I have to know about some "template" (which is very internal concept) and I have to know that I have to modify it to restore the correct route and I have to know the method which should be used. All of these things are magic.

The resume is : the API is weak.
It should be amended  with the method which returns the original navigation target path without any PARAMETER.
Please make a ticket about this.

2021-02-12 06:27 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/router/internal/HasUrlParameterFormat.java
> +    public static String excludeTemplate(String urlTemplate,
The method pretends to be an API but has no javadocs.

2021-02-15 11:12 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/router/internal/HasUrlParameterFormat.java
> +    public static String excludeTemplate(String urlTemplate,
Added

2021-02-15 11:13 UTC, mshabarov commented
I've added a separate ticket https://github.com/vaadin/flow/issues/10033.

2021-02-15 11:51 UTC, denis-anisimov approved these changes

2021-02-15 12:11 UTC, merged