feat: Backport first part of improved theming support
vaadin/flow pull request #10048
Opened 2021-02-17 06:27 UTC by caalador

Backport of initial parts of the improved theming support.

2021-02-22 14:29 UTC, taefi requested changes

2021-02-22 14:29 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
> +    @Theme(value =FakeLumoTheme.class)
```suggestion
    @Theme(value = FakeLumoTheme.class)
```

2021-02-22 14:29 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerTestComponents.java
> +    @Theme(value =Theme1.class, variant = Theme0.DARK)
```suggestion
    @Theme(value = Theme1.class, variant = Theme0.DARK)
```

2021-02-22 14:29 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerTestComponents.java
> +    @Theme(value =Theme1.class, variant = Theme0.DARK)
```suggestion
    @Theme(value = Theme1.class, variant = Theme0.DARK)
```

2021-02-22 14:29 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerTestComponents.java
> +    @Theme(value =Theme4.class)
```suggestion
    @Theme(value = Theme4.class)
```

2021-02-22 14:29 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerTestComponents.java
> +    @Theme(value =Theme2.class, variant = Theme2.FOO)
```suggestion
    @Theme(value = Theme2.class, variant = Theme2.FOO)
```

2021-02-22 14:29 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerTestComponents.java
> +    @Theme(value =Theme2.class)
```suggestion
    @Theme(value = Theme2.class)
```

2021-02-22 14:29 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/RouteLayoutComponent.java
> +@Theme(value =CustomTheme.class)
```suggestion
@Theme(value = CustomTheme.class)
```

2021-02-22 14:29 UTC, taefi commented on flow-tests/test-themes/frontend/theme/app-theme/global.css
> +}
Just to make sure:
This file misses the following lines from #9349 
```
body {
    background-image: url('theme/app-theme/img/bg.jpg');
}
```

2021-02-22 18:27 UTC, caalador reviewed
As I'm out the whole week you can fix the formatting problems, also check the backport ticket for the Theme annotation requirements.

2021-02-22 18:27 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
> +                    .isAssignableFrom(getFinder().loadClass(themeClass)))) {
It's part of the 14 requirements and is added content

2021-02-22 18:27 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
> +                            invokeAnnotationMethodAsString(theme, "themeFolder")))
It's 14 requirement as 14 doesn't use themeClass but value. Also themeFolder is value in 19

2021-02-22 18:27 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/theme/Theme.java
> + * value} property.
This is the requirement for 14 backport.

2021-02-22 18:27 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/theme/ThemeDefinition.java
> +        this(themeAnnotation.value(), themeAnnotation.variant(), themeAnnotation.themeFolder());
14 backport requirement for the annotation values

2021-02-22 18:27 UTC, caalador commented on flow-tests/test-themes/frontend/theme/app-theme/global.css
> +}
This is the correct version at this point in time see 9451

2021-02-26 08:45 UTC, taefi requested changes

2021-02-26 08:45 UTC, taefi commented on flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/TestComponents.java
> +    @Theme(value =Lumo.class, variant = Lumo.DARK)
```suggestion
    @Theme(value = Lumo.class, variant = Lumo.DARK)
```

2021-02-26 08:51 UTC, taefi submitted a review, later dismissed

2021-02-26 14:33 UTC, taefi approved these changes

2021-03-01 10:15 UTC, merged