fix: remember original state after LOADING
vaadin/flow pull request #10099
Opened 2021-02-19 13:56 UTC by joheriks

When transitioning back from LOADING, don't assume CONNECTED.

2021-02-22 11:20 UTC, Haprog requested changes
The logic seems slightly flawed to me and seems like it can still cause unexpected state in some cases. See my suggestion below.

2021-02-22 11:20 UTC, Haprog commented on flow-client/src/test/frontend/ConnectionStateTests.ts
> +      ConnectionState.LOADING, ConnectionState.CONNECTION_LOST))
Now here the logic changed so that the last state is `CONNECTION_LOST` instead of `CONNECTED`. This doesn't make sense to me.

Seems like the `store.loadingFinished();` call does not currently know or care if the loading was successful or not which in my opinion would be necessary information for these kind of tests and to be able to get the right behaviour.

See here https://github.com/vaadin/flow/blob/dd372e4d3c85352287151eaa3e05d09bb7448b59/flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts#L374-L387
where `loadingFinished()` is called the same way in both cases if the call succeeds or fails. The only difference is that in the failure case the state is set to `CONNECTION_LOST` after calling `loadingFinished()`. So in this case I think the issue used to be that `loadingFinished()` was previously setting the state to `CONNECTED` and then it was immediately set to `CONNECTION_LOST` (in case the call failed).

So it looks like two different parts of the code are trying to both determine what should happen here but this state change should only be handled in one place imo.

If a call finishes successfully (meaning we got a result from the server without network failure) it should mean that the connection is not lost and if a call fails (with network error) it should mean that the connection is lost.

I think the result of the most recently finished call should determine do we transition to `CONNECTION_LOST` or `CONNECTED`. Not what the state was before starting to load something (that seems irrelevant to me). Think about if you had connection lost, then started to load something, and it finishes successfully. It means you have a working connection so it should not return to connection lost state.

Imo instead of `stateBeforeLoading` we should have something like `latestCallSuccessful` (true or false). This could be set in `Connect.ts` before calling `loadingFinished()` or it could be a parameter to `loadingFinished()` so that it knows if it finished without network errors or not. Or alternatively split it to two methods `loadingSucceeded()` and `loadingFailed()`.

2021-02-22 11:20 UTC, Haprog commented on flow-client/src/test/frontend/ConnectionStateTests.ts
> +      ConnectionState.LOADING, ConnectionState.CONNECTION_LOST))
Imo we don't need to store `stateBeforeLoading` unless we would somehow support cancelling a call that has not finished yet.

Idea outside the scope of this issue: I think it might be useful to have another connection state that would only have 2 states (connected and connection lost, so without the loading states). This could be useful for users when they only care about is the current state considered to be connected or not without caring about possible ongoing/loading fetch calls.

2021-02-23 07:38 UTC, joheriks commented on flow-client/src/test/frontend/ConnectionStateTests.ts
> +      ConnectionState.LOADING, ConnectionState.CONNECTION_LOST))
Good points. Added a method `loadingFailed` transitioning to `CONNECTION_LOST` when the counter reaches zero. So the connection state will remain in `LOADING` while there are ongoing backend calls, and the result of the last call (succeeed or failed) will determine the final state (`LOADING`/`CONNECTION_LOST`). So `ConnectionStateStore` will represent the result of the last server interaction.

(Also removed the extra complication of `Connect` calling methods `loadingStarted` and `loadingFinished` in Flow instead of directly accessing `ConnectionStateStore`, as the only thing this accomplished in addition was setting the `isActive` flag for TestBench which was not stacked anyway and hence meaningless).

2021-02-23 10:23 UTC, Haprog submitted a review, later dismissed
Looks good. Consider removing commented line of code.

2021-02-23 11:15 UTC, joheriks commented on flow-client/src/test/frontend/ConnectTests.ts
> +        // expect((window as any).Vaadin.connectionState.state).to.equal(ConnectionState.CONNECTION_LOST);
Done. The assertion would still be valid but not necessary since the connection state is checked via the listener.

2021-02-23 11:18 UTC, Haprog approved these changes

2021-02-24 11:50 UTC, merged