chore: Fix initalizing to devServers
vaadin/flow pull request #10098
Opened 2021-02-19 13:07 UTC by caalador

Don't start third devServer in middle.

Fixes #10018

2021-02-19 14:03 UTC, denis-anisimov requested changes

2021-02-19 14:03 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
> -        // since the timeout is quite big the server port still should be
This comment should not be removed I guess.

2021-02-20 08:19 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
> -        // since the timeout is quite big the server port still should be
Comment returned.

2021-02-20 08:55 UTC, denis-anisimov approved these changes

2021-02-22 06:15 UTC, merged