chore: enable PWA in OSGi
vaadin/flow pull request #10100
Opened 2021-02-19 13:56 UTC by denis-anisimov

fixes vaadin/osgi#44

2021-02-22 12:00 UTC, mshabarov requested changes

2021-02-22 12:59 UTC, mshabarov requested changes

2021-02-22 12:59 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/AppShellPredicate.java
> + * Copyright 2000-2020 Vaadin Ltd.
Change to 2021

2021-02-22 12:59 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
>      public boolean isShell(Class<?> clz) {
This method is still used in `VaadinAppShellInitializer`, is possible to use `AppShellPredicate` there instead (get lookup from context, then get the app shell predicate from via lookup)?

2021-02-22 13:14 UTC, mshabarov commented
I couldn't find the test, which checks that the default `isShell` method (in default `AppShellPredicate` and in deprecated `AppShellRegistry::isShell`) returns `true` if the given class is an instance of `AppShellConfigurator`. But most probably it is being checked implicitly within another more 'high-level' test, is it the case?

2021-02-23 06:09 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/AppShellPredicate.java
> +public interface AppShellPredicate {
Can be but doesn't have to.
Done.

2021-02-23 06:10 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/di/LookupInitializer.java
> +        public AppShellPridicateImpl() {
Done

2021-02-23 06:13 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/di/LookupInitializer.java
> +        public AppShellPridicateImpl() {
Any default CTOR javadocs are totally useless.
Doesn't matter which way the instance is created.
The only reason why this absolutely dumb comment is here: SQ complains about javadocs absence.

The class is an internal implementation class and is not supposed to be used as API so no need so explain obvious things.

2021-02-23 06:15 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/di/LookupInitializer.java
> +    protected <T> void ensureService(
Done.

2021-02-23 06:20 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
> +     * @deprecated use {@link AppShellPredicate} to test whether the class is an
This class is not API.
I deprecated this method just because it's here for a while: starting from the time when `AppShellRegistry` has been added .
Otherwise I would silently remove the method: there is no even reason to have it here.
The implementation of this method contains exactly what you are requesting : it's pretty clear. Don't see reasons to repeat the same in deprecation message.

2021-02-23 06:21 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/AppShellPredicate.java
> + * Copyright 2000-2020 Vaadin Ltd.
Done

2021-02-23 06:24 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
>      public boolean isShell(Class<?> clz) {
It's possible of course.
And the only reason why `AppShellRegistry` is not removed: this usage.
Theoretically there can be someone why override this method and this overridden method is used in the `VaadinAppShellInitializer`.
If I use the correct impl inside `VaadinAppShellInitializer`  directly then the code which this someone relies in will be broken.

2021-02-23 06:32 UTC, denis-anisimov commented
> I couldn't find the test, which checks that the default `isShell` method (in default `AppShellPredicate` and in deprecated `AppShellRegistry::isShell`) returns `true` if the given class is an instance of `AppShellConfigurator`. But most probably it is being checked implicitly within another more 'high-level' test, is it the case?
> 
> Another question is that would the OSGi side implementation of app shell predicate be tested in OSGi project, or in flow (within felix-jetty config)?

I also couldn't find a test  which checks `AppShellRegistry::isShell` returns `true`.
Most likely it doesn't exist.
That's why I've not added this test: it should have been existed before I made refactoring.

OSGi functionality is in its own repo. All the questions about OSGi should be asked there.

2021-02-23 07:11 UTC, mshabarov approved these changes

2021-02-23 07:29 UTC, merged