chore: security helper with list of should-be-public urls
vaadin/flow pull request #10134
Opened 2021-02-26 10:43 UTC by joheriks

Related to vaadin/spring#678

2021-02-26 10:56 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/internal/SecurityHelper.java
> +            "/" + Constants.VAADIN_MAPPING + "/**",
Is it a problem that /VAADIN/dynamic is public? What does it contain?

2021-02-26 11:18 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/internal/SecurityHelper.java
> +            "/" + Constants.VAADIN_MAPPING + "/**",
In the spring pr is 

```java
                .filter(pattern -> !pattern.equals("/VAADIN/**"))
```

to remove the constant again. Not sure if that's the best way.

2021-02-26 12:54 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/internal/SecurityHelper.java
> +            "/" + Constants.VAADIN_MAPPING + "/**",
Removed `/VAADIN/**` from `PUBLIC_VAADIN_URLS`.

2021-03-01 11:16 UTC, haijian-vaadin requested changes
The code looks good to me, the sonar issues are reasonable, could be fixed.

2021-03-01 15:20 UTC, joheriks commented
> The code looks good to me, the sonar issues are reasonable, could be fixed.

Sonar issues fixed and validation build now passed.

2021-03-02 06:49 UTC, haijian-vaadin approved these changes

2021-03-02 06:50 UTC, merged