Only use the export chunk for exported web components if it is found
vaadin/flow pull request #10144
Opened 2021-02-27 12:45 UTC by Artur-

Makes it possible to reconfigure webpack to put exported wcs elsewhere

2021-03-02 14:21 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
> +                    .anyMatch(s -> EXPORT_CHUNK.equals(s));
Or use `chunks.hasKey(EXPORT_CHUNK)`?

2021-03-02 14:43 UTC, joheriks submitted a review, later dismissed

2021-03-03 08:41 UTC, joheriks submitted a review, later dismissed

2021-03-04 10:09 UTC, haijian-vaadin requested changes
Let's add some unit tests for this change before we merge it. The fusion team can make the tests.

2021-03-17 13:08 UTC, joheriks commented
Rebased and added unit test.

2021-03-17 21:38 UTC, haijian-vaadin requested changes

2021-03-17 21:38 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
> +    public void writeBootstrapPage_noExportChunk()
Should we also have a test like `writeBootstrapPage_withExportChunk`?

2021-03-18 07:55 UTC, joheriks commented on flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
> +    public void writeBootstrapPage_noExportChunk()
Good idea, done.

2021-03-18 07:58 UTC, haijian-vaadin approved these changes

2021-03-18 09:04 UTC, merged