cache stats.json and asset chunks
vaadin/flow pull request #10146
Opened 2021-02-28 09:39 UTC by knoobie

fixes #10116

2021-03-03 13:48 UTC, mshabarov requested changes
Thank you @knoobie for a contribution!
Your solution with caching looks good. I would propose refactor the code a bit in order to store the cached objects in a proper place.

2021-03-03 13:48 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    private static String cachedStatsJson = null;
I'm not sure the util class (`FrontendUtils`) is a proper place to store the cached data.
There is already a solution for external stats.json caching here https://github.com/vaadin/flow/blob/eacee0f42b8b6b111d2858c0fe6998f9f996a755/flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java#L463

What if we merge these two cases and store stats.json in context for both cases (external or classpath)?

2021-03-03 13:48 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    private static String cachedAssetChunks = null;
Same goes for cached asset chunks. What if you add one more field to `Stats` container to store there a result of `getStatsAssetsByChunkName`?

2021-03-03 13:48 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    private static String cachedStatsJson = null;
There is one more place stated in the original ticket stack trace https://github.com/vaadin/flow/issues/10116, where the exception is thrown:

https://github.com/vaadin/flow/blob/eacee0f42b8b6b111d2858c0fe6998f9f996a755/flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java#L892

I believe we should add a caching there as well. Context and configuration are available in this method, so we can check agains production mode and already cached object.

2021-03-03 15:42 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    private static String cachedStatsJson = null;
Thanks @mshabarov! I didn't know that class :) Gonna refactor the code (not sure if today or in the next days) but it sounds totally reasonable to store it in a proper class/storage.

2021-03-03 15:45 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    private static String cachedStatsJson = null;
I think this is already covered because `appendNpmBundle`:

https://github.com/vaadin/flow/blob/eacee0f42b8b6b111d2858c0fe6998f9f996a755/flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java#L907-L910

already calls the cached chunk in the first line :)

2021-03-03 19:36 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    private static String cachedStatsJson = null;
Okay.. I did some brainstorming and code digging. The biggest problem is `getStatsFromExternalUrl` because it populates the current cache / `Stats` within the context. Funny thing.. this is only done if the header `last-modified` of the `HttpConnection` has a value and it's older than the current stored value. 

I was thinking about removing the cache code from `getStatsFromExternalUrl` because it doesn't really make sense with the name but I couldn't satisfy the `Stats` constructor because of the missing `lastModified` information later on. (`getStatsFromExternalUrl` only returns an `InputStream`) .

Additionally.. do I have to check for the `lastModified` before I return the cache? with what value do I check it? Do I really have to create a `HttpConnection` everytime to check? That doesn't really sounds reasonable. This should only be done if `isExternalStatsFile=true` - meaning `lastModified` gets optional?

How about `assetChunks`? Does it inherit the `lastModified` from the `statsJson` or is can this be ignored? 

If you don't mind I would propose the following: 
 - Combined method to create and access the cache for `assetChunks` and `statsJson`. 
 - This method is only called in productionMode and returns the requested string 
 - If `isExternalStatsFile=true` I ALWAYS open a connection to get a `lastModified` timestamp to update the cache before return? or should I create a `LocalFileCache` and leave the old implementation alone? That would make a lot of things easier..

2021-03-04 08:39 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    private static String cachedStatsJson = null;
Sorry, I don't see how it's covered.
`appendNpmBundle` calls `getStatsAssetsByChunkName` in which the `stats.json` is being fetched either from local file or from external source.  
In case of a local file, the `stats.json` is never cached currently.

The only place where it is cached is here, for external source:
https://github.com/vaadin/flow/blob/eacee0f42b8b6b111d2858c0fe6998f9f996a755/flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java#L463

I wanted to emphasise that improving the performance by caching the `stats.json`, when loading from a file, should be done for both cases: during initial bootstrap in `BootstrapHandler` and in other cases when `stats.json` is needed and `FrontendUtils::getStatsContent` is being invoked.

2021-03-04 09:22 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    private static String cachedStatsJson = null;
In my current implementation is no call to `stats.json` if `productionMode = true && cachedAssetChunks` - yes that's faulty in other ways. See the comment from above with the wall of text / looking for ways around the whole external file cache situation.

2021-03-04 10:27 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    private static String cachedStatsJson = null;
> this is only done if the header last-modified of the HttpConnection has a value and it's older than the current stored value.

Why older? The current code looks fine: it updates the cached value if the object is not cached yet, or the source object has been modified (cached last modified timestamp is before the one obtained from external source). Another thing I have a doubts is that why is the timestamp is recalculated in getter method:
```java
        public LocalDateTime getLastModified() {
            return ZonedDateTime
                    .parse(lastModified, DateTimeFormatter.RFC_1123_DATE_TIME)
                    .toLocalDateTime();
        }
```
Why not store the `LocalDateTime` instead of `String`, but this is an another question.

> I was thinking about removing the cache code from getStatsFromExternalUrl because it doesn't really make sense with the name but I couldn't satisfy the Stats constructor because of the missing lastModified information later on. (getStatsFromExternalUrl only returns an InputStream) .

`getStatsFromExternalUrl` is a `private` methods, so we can change the return type so as to include the `lastModified` value there and extract the caching logic to a separate method and leave only the code related to fetching data via `HttpConnection`. The caching logic then will 'wrap' the actual fetch (from classpath or from external source) and populate the context if needed.

> Additionally.. do I have to check for the lastModified before I return the cache? with what value do I check it? Do I really have to create a HttpConnection everytime to check? That doesn't really sounds reasonable. This should only be done if isExternalStatsFile=true - meaning lastModified gets optional?

It's a good question! I would say, normally the `stats.json` should not be changed (?) if stored in classpath (in current WAR or another WAR on same server). But what happens if some hot redeploy mechanism is used (OSGi for instance), could it be changed then? Not sure about that. And even worse thing that if the `stats.json` is in another bundle, and it hasn't been loaded yet at the point when it's requested. Theoretically, it's possible. But that's would be an issues of a client code/environment. Not sure we should handle such a cases in the Flow. Long story short, I would ignore the `lastModified` for loading from classpath.

> How about assetChunks? Does it inherit the lastModified from the statsJson or is can this be ignored?

I believe it's just inherit the lastModified from stat.json. So if the stats.json is up-to-date, then no need to update the cached assetChunks.

> Combined method to create and access the cache for assetChunks and statsJson.
This method is only called in productionMode and returns the requested string
If isExternalStatsFile=true I ALWAYS open a connection to get a lastModified timestamp to update the cache before return? or should I create a LocalFileCache and leave the old implementation alone? That would make a lot of things easier..

Looks good, but I'm against to use `LocalFileCache` in Flow, as it would bring a new dependency, which may cause a serious unexpected conflicts/bug on the client project side.

2021-03-04 10:48 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    private static String cachedStatsJson = null;
Your suggestions sound reasonable and align to my understanding. Gonna try to refactor the implementation (wanted to get approval for deeper digging/changes). 

About `LocalFileCache` - that was just a name ;) I wanted to create a inner private class `LocalFileCache` that works like `Stats` just for the internal files to reduce the gazillion creations of `InputStream` and file access for cacheable ressources (asset chunks and json) without touching the current `Stats` class for `external` calls - this would only be called if `productionMode = true && externalStatsFile == false`.

2021-03-04 11:47 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    private static String cachedStatsJson = null;
> About LocalFileCache - that was just a name ;) I wanted to create a inner private class LocalFileCache that works like Stats just for the internal files to reduce the gazillion creations of InputStream and file access for cacheable ressources (asset chunks and json) without touching the current Stats class for external calls - this would only be called if productionMode = true && externalStatsFile == false.

Sorry for confusing :) Okay, sounds good then.

> Edit: About getStatsFromExternalUrl - it gave me a headache because the Stats cache is only called and populated if the connection has a lastModified header.

Well, I don't see any contradictions - if the header hasn't been obtained, then no conclusions about cached resource 'version' can be made, thus, the code simply fetches it from connection. What if you use the cached resource timestamp, if not header obtained?

2021-03-04 11:52 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    private static String cachedStatsJson = null;
Thanks for the clarification and your input! Gonna rework on this in the weekend by creating a separate `LocalFileCache` and if that seems good enough, we can try to integrate the whole `Stats` logic for external files there as well. Step by step.

2021-03-04 11:53 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    private static String cachedStatsJson = null;
Ah, sorry! You're right! Indeed, `getStatsAssetsByChunkName` contains changes. Ignore this comment then.

2021-03-06 07:35 UTC, knoobie commented
This is a complete rework based on the discussion with @mshabarov. The old `FrontendUtilsTest` are passing. Gonna see what the flow pipeline says to this change and create unit tests afterwards.

2021-03-06 15:55 UTC, knoobie commented
@mshabarov now it's ready to review. I've implemented the cache for `local stats.json` and `external stats.json` when `productionMode = true` otherwise there is no cache - removing the old `Stats` and cache for `external stats.json`. This change could result in a little overhead in development mode if somebody uses `external stats.json` and disables webpack.. (who does said? Nobody I think)

Additionally this implementation guards against your described problem with OSGI because it returns `StatsCache.NOT_CACHEABLE` (null) if the `stats.json` could not be found - resulting in retrying on the next execution. :) 

Open question: Now, I know why the `LocalDateTime` wasn't stored in the `Stats` - sonarqube complains. Do you want me to change it to `String` or add `transient`? I would go with `transient` because there isn't much information lost. The cache is gonna recreate itself when there is no `lastModified` and `externalStats=true`. 

And sorry for the unrelated code changes in the file.. I used `mvn formatter:format` in the end to comply with your rules and some older methods weren't aligned.

2021-03-08 14:29 UTC, mshabarov requested changes

2021-03-08 14:29 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    static StatsCache createCacheFromHttpURLConnection(StatsCache currentCache,
This method is used only inside another `private` method.
If it was a public API, it would be fine to test it separately. But, as its effectively `private`, It looks a bit weird to test it like this.
I'd expect it is tested as a part of some public API test.

2021-03-08 15:52 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    static StatsCache createCacheFromHttpURLConnection(StatsCache currentCache,
Sadly the other private method (caller) wasn't tested before and it seemed more straight forward to explicit test this part because of the additional logic. External stats were not tested at all (execution of `HttpUrlConnection` and so on) - testing this new logic seemed more important because the old logic didn't change.

2021-03-08 16:03 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    private static StatsCache getOrCreateStatsCache(VaadinContext context,
I can try to create a version that only modifies `getStatsFromClassPath` to reduce the impact of the change. I would propose to do this in another branch, I don't want to lose all this with a force push. ;)

2021-03-08 16:09 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +            // This isn't cached because production mode isn't enabled
This would be resolved by reducing the change to `getStatsFromClassPath` as well.

2021-03-09 06:29 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    private static StatsCache getOrCreateStatsCache(VaadinContext context,
Yes, let's proceed this way.

2021-03-09 06:30 UTC, knoobie commented
Closes this and create a new pr with less changes in the next 1-2 days.

2021-03-09 06:30 UTC, closed without merging