fix: Execute error handling as a last action in message handler
vaadin/flow pull request #10142
Opened 2021-02-26 16:09 UTC by mshabarov

Makes error handling the last action in the message handling queue, and ensures that the error message won't be shown if the page redirect has been requested on server side.

Fixes https://github.com/vaadin/flow/issues/9647

2021-03-02 11:28 UTC, denis-anisimov commented
The solution looks good for me.
But I would like to know whether it's possible to write a GWT unit test for this ?

We have some such tests in `GwtMessageHandlerTest`  . Please check whether this functionality can be unit tested.

The ITs are not reliable for this scenario.

2021-03-02 11:35 UTC, mshabarov commented
> But I would like to know whether it's possible to write a GWT unit test for this ?

Sure! I will check it.

2021-03-02 11:40 UTC, taefi requested changes

2021-03-02 11:40 UTC, taefi commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LogoutView.java
> +                                final CustomizedSystemMessages systemMessages = new CustomizedSystemMessages();
```suggestion
                                final CustomizedSystemMessages systemMessages = 
                                                new CustomizedSystemMessages();
```

2021-03-02 11:40 UTC, taefi commented on flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
> +                        && uiState != UIState.TERMINATED) {
Not sure if applicable, but what happens if `meta.containsKey("appError")` resolves to true and also `uiState == UIState.TERMINATED` returns true?

2021-03-02 11:58 UTC, mshabarov commented on flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
> +                        && uiState != UIState.TERMINATED) {
If `uiState == UIState.TERMINATED` is `true`, then it means that the redirect has been occurred and `stopApplication` method has been invoked. In that case, it is pointless to show the message, because the page has been redirected, and this error message is only relevant to old page.

2021-03-02 12:20 UTC, taefi approved these changes

2021-03-02 13:17 UTC, taefi commented
Do not merge until a decision made for adding GWT tests to this PR.

2021-03-05 06:14 UTC, denis-anisimov requested changes

2021-03-05 06:14 UTC, denis-anisimov commented on flow-client/src/test-gwt/java/com/vaadin/client/GwtMessageHandlerTest.java
> +        redirectCommand.set(0,
This looks overcomplicated and not a unit tests but rather IT.

The code should be unit tested: so there is no need to emulate various causes then application is terminated.
`this.stopApplication();` terminates the application.
You just need terminated application: terminate it directly via `UILifecycle::setState` .

2021-03-05 06:14 UTC, denis-anisimov commented on flow-client/src/test-gwt/java/com/vaadin/client/GwtMessageHandlerTest.java
> +        redirectCommand.set(0,
Same here `UILifecycle::setState `.

2021-03-05 06:53 UTC, mshabarov commented on flow-client/src/test-gwt/java/com/vaadin/client/GwtMessageHandlerTest.java
> +        redirectCommand.set(0,
Agree. Done

2021-03-05 06:53 UTC, mshabarov commented on flow-client/src/test-gwt/java/com/vaadin/client/GwtMessageHandlerTest.java
> +        redirectCommand.set(0,
Done

2021-03-05 07:06 UTC, denis-anisimov requested changes

2021-03-05 07:06 UTC, denis-anisimov commented on flow-client/src/test-gwt/java/com/vaadin/client/GwtMessageHandlerTest.java
> +        getUILifecycle().setState(UILifecycle.UIState.RUNNING);
Is this needed ?

2021-03-05 07:06 UTC, denis-anisimov commented on flow-client/src/test-gwt/java/com/vaadin/client/GwtMessageHandlerTest.java
> +        getUILifecycle().setState(UILifecycle.UIState.RUNNING);
Is this needed ?

2021-03-05 07:06 UTC, denis-anisimov commented on flow-client/src/test-gwt/java/com/vaadin/client/GwtMessageHandlerTest.java
> +    public void testHandleJSON_sessionExpiredAndUIRunning_sessionExpiredMessageShown() {
the name of the test is confusing since it mentioned "session expires" is extra here.

2021-03-05 07:06 UTC, denis-anisimov commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LogoutView.java
> +                    VaadinService.getCurrent().setSystemMessagesProvider(
Is this needed ?

2021-03-05 07:09 UTC, mshabarov commented on flow-client/src/test-gwt/java/com/vaadin/client/GwtMessageHandlerTest.java
> +        getUILifecycle().setState(UILifecycle.UIState.RUNNING);
Yes, `UIState` check that the transition goes smoothly from initial state to terminated. It throws in case any jump init -> terminated.

2021-03-05 07:16 UTC, mshabarov commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LogoutView.java
> +                    VaadinService.getCurrent().setSystemMessagesProvider(
Yes, it sets session notification message to be shown (it's not shown by default). Then, it actually should not be shown because of `Page::setLocation`. That is exactly I try to test: even if `setSessionExpiredNotificationEnabled(true)`, the page is being redirected with no blinking message.

2021-03-05 07:18 UTC, mshabarov commented on flow-client/src/test-gwt/java/com/vaadin/client/GwtMessageHandlerTest.java
> +    public void testHandleJSON_sessionExpiredAndUIRunning_sessionExpiredMessageShown() {
Why "session expires" is extra? I want this test to go through the code block which handles "session expire" flag and shown the corresponding message. It covers "session expire" case, so this wording is in the test name.

2021-03-05 07:26 UTC, denis-anisimov commented on flow-client/src/test-gwt/java/com/vaadin/client/GwtMessageHandlerTest.java
> +    public void testHandleJSON_sessionExpiredAndUIRunning_sessionExpiredMessageShown() {
Right, my bad.

2021-03-05 07:34 UTC, denis-anisimov requested changes

2021-03-05 07:34 UTC, denis-anisimov commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LogoutView.java
> +                    VaadinService.getCurrent().setSystemMessagesProvider(
This action relies on the behavior: the system message provider and the expired notification are handled and set on the client side BEFORE the actions below are executed.

The is expected behavior indeed. But if there a bug on the client side and the commands are handled AFTER then this test will be false positive (in fact it's exactly the same as the previous one).
To avoid such fragile behavior the message provider and session expired settings has to executed before without any assumptions. It should not be one action which relies on the Java order of execution.

2021-03-05 08:52 UTC, mshabarov commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LogoutView.java
> +                    VaadinService.getCurrent().setSystemMessagesProvider(
Thanks, it's fragile indeed! What if I call `setSessionExpiredNotificationEnabled(true)` separately by another button click, so that it will happens before page redirect and session expiration on the client side?
Moreover, this flag should be reverted at the end of test, so as to not impact another test.

2021-03-05 10:41 UTC, denis-anisimov commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LogoutView.java
> +                    VaadinService.getCurrent().setSystemMessagesProvider(
Another button click : yes.

Reverting is almost impossible.
You may use `tearDown` in the test of course but the problem is : this needs to be implemented via UI actions which may fail. And as a result revert won't be done.
Moreover failing inside `tearDown`  prevents screenshots being generated. 
That is  already known from Portlets tests.

If there are such "permanent effects" which may influence another tests then it's better to create another servlet with a dedicated URL mapping so that any changes in any configuration will affects only this servlet and don't touch others.
That allows to make a sandbox via the dedicated servlet.

2021-03-05 13:38 UTC, mshabarov commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LogoutView.java
> +                    VaadinService.getCurrent().setSystemMessagesProvider(
Alright, I've cut off the existing notification enabled part to the dedicated servlet, so now it should solve the problems with the ordering of configuration change and JS command execution, as well as configuration change impact on other tests.

2021-03-08 05:59 UTC, denis-anisimov approved these changes

2021-03-08 06:00 UTC, merged