Only inject scripts not already loaded when using an exported wc
vaadin/flow pull request #10145
Opened 2021-02-27 12:45 UTC by Artur-

This ensures that the same bundle is not loaded twice if injecting on a page where the app itself is already running

2021-03-01 08:48 UTC, fluorumlabs requested changes

2021-03-01 08:48 UTC, fluorumlabs commented on flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
> +                    writer.append("if (!hasScript('" + conditionalFilename
Use `"` (double quote) character for JavaScript string: single quote (`'`) is a valid character for URL.

2021-03-01 08:48 UTC, fluorumlabs commented on flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
> +                    + "  return !!scriptTags.find(script => script.src.endsWith(src))\n"
You probably wanted `return scriptTags.some(script => script.src.endsWith(src))`

2021-03-02 15:50 UTC, platosha reviewed
Good idea. There should be tests for this feature though.

2021-03-04 10:10 UTC, haijian-vaadin requested changes
Let's add some unit tests for this change before we merge it. The fusion team can make the tests.

2021-03-17 14:27 UTC, joheriks commented
Rebased and added unit test.

2021-03-17 21:31 UTC, haijian-vaadin requested changes

2021-03-17 21:31 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
> +        int guardIndex = result.indexOf("if (!hasScript(\"/VAADIN/build/vaadin-export-2222.cache.js\")) {");
I think it would be better to check if the `hasScript` function is defined. Otherwise, if I remove the code for defining the function, the test still passes.

2021-03-18 07:38 UTC, joheriks commented on flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
> +        int guardIndex = result.indexOf("if (!hasScript(\"/VAADIN/build/vaadin-export-2222.cache.js\")) {");
Done.

2021-03-18 07:57 UTC, haijian-vaadin approved these changes

2021-03-18 08:40 UTC, fluorumlabs requested changes
Couple of general questions:
1. What about (global) stylesheets? Loading the same stylesheet again will change the order how styles are overriding each other.
2. If we a planning to backport this to 14.x, we should verify that it works in compatibility mode as well (a bit contradictory here; `PATH_PATTERN` in the beginning implies that `WebComponentBootstrapHandler` can also serve `.html`, but content-type set at line 242 suggests otherwise).

2021-03-18 08:40 UTC, fluorumlabs commented on flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
> +            writer.write("var hasScript = function(src) {\n"
Just noticed that bootstrap script runs in the global scope, which means, that `hasScript` (and `headElem`) end up in `window`. It might create a headache if some of user-supplied scripts rely on this. IIFE should solve this.

2021-03-19 09:34 UTC, fluorumlabs approved these changes

2021-03-19 21:51 UTC, haijian-vaadin approved these changes

2021-03-19 21:51 UTC, merged