10109 remove only added routes
vaadin/flow pull request #10162
Opened 2021-03-02 06:45 UTC by denis-anisimov

2021-03-02 11:38 UTC, caalador requested changes

2021-03-02 11:38 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
>                  routeConfiguration.setAnnotatedRoute(navigationTarget);
Here the cache/stored list could be populated after setting a route as the data can be gotten with `routeConfiguration.getTemplate(navigationTarget)`

2021-03-02 11:38 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
> +    private static class StaticRoutesApplicationRouteRegistry
The class name indicates something that should always say the same, but it is used for removing some set of previously registered routes that excludes dynamic additions.
`PreviousRoutes` or `PreviousRouteInitialization` also it could be either a `List<String>` or `Set<String>` as only the template string is used.

2021-03-02 11:38 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
> +        }
Could also instead check 
```
Assert.assertTrue(registry.getTemplate(BaseRouteTarget.class).isPresent());
Assert.assertTrue(registry.getNavigationTarget(PathUtil.getPath("manual-route", Collections.emptyList())).isPresent());
```
or
```
RouteConfiguration configuration = RouteConfiguration.forRegistry(registry);
Assert.assertTrue(configuration.isRouteRegistered(BaseRouteTarget.class));
Assert.assertTrue(configuration.isPathAvailable("manual-route"));
```

2021-03-03 06:11 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/ClassLoaderAwareServletContainerInitializer.java
> +     *            being started and in which the classes contained in <tt>c</tt>
reverted back the whole class since there is no need in these changes anymore.

2021-03-03 06:18 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
> +    private static class StaticRoutesApplicationRouteRegistry
I don't like the class name as well.
But you are suggesting also quite bad name: your  name is based on the usage. It's quite weird to name class based on the single usage: doesn't matter how the class is used. It matters what the class represents: the same class can be used differently by many many pieces of code (even though this is quite specific case since the class is initially done private and intended to be used only in one place).

This class (ignoring its usage) contains static routes (unmutable). Comparing to the `ApplicationRouteRegistry` which is dynamic registry.
That was the initial idea for the name.
I will try to figure our some better name

2021-03-03 06:23 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
>                  routeConfiguration.setAnnotatedRoute(navigationTarget);
The API is confusing: `routeConfiguration.getTemplate(navigationTarget)` returns `Optional<String>`.
Perhaps it return the primary route path. Because I don't see how to get aliases. The registry API with `RouteData` gives a better API.

2021-03-03 06:26 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
> +        }
Done.

2021-03-03 06:29 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
>                  routeConfiguration.setAnnotatedRoute(navigationTarget);
I could see a clear use case for adding a `getRouteData(Class targetClass)` in the registry as it's anyway populated on demand and not reused. The build already exists in `AbstractRouteRegistry::populateRegisteredRoutes` would just need to create the public method.

2021-03-03 06:36 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
>                  routeConfiguration.setAnnotatedRoute(navigationTarget);
Well, that's fine. But this is about `RouteConfiguration`  API which is out of scope of this PR.
Regardless of this change a registry copy is still preferable for me here since:
- it gives a copy of everything that has been stored
- the way of data collection is the same code which is used for the main registry
- the above observations allows to avoid any fragile code/assumptions which may be broken with some changes in the registry impl
- it's extremely easy to correct the code in case there will be need to remove more data stored in the registry (if there will be any need in this): comparing to any custom storage which will require changes
- I still need a class to store the data inside the context instance (and `List` class is not suitable: some wrapper is needed anyway): there is already a simple registry subclass with an empty impl.

So overall the current approach requires less efforts to maintain the code.

2021-03-03 06:39 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
> +    private static class PreviouslyStoredRoutesImmutableRegistry
As long as it's a RouteRegistry it's not immutable. Else I'm fine with the naming.

2021-03-03 06:42 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
> +    private static class PreviouslyStoredRoutesImmutableRegistry
It's effectively immutable: once created it's never changed.

But I'm going to the same direction of usage here.....
Let it be `PreviouslyStoredRoutesRegistry`

2021-03-03 06:46 UTC, caalador approved these changes

2021-03-03 07:28 UTC, merged