chore: add isInternalRequest for use in VaadinSpringSecurity helper
vaadin/flow pull request #10185
Opened 2021-03-03 12:15 UTC by joheriks

2021-03-03 13:43 UTC, Artur- requested changes

2021-03-03 13:43 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/internal/SecurityHelper.java
> +    public static boolean isInternalRequest(HttpServletRequest request) {
What does "internal" mean? It is always safe? It is only for authenticated users?

2021-03-03 13:43 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/internal/SecurityHelper.java
> +        String referer = request.getHeader("referer");
Is this a security related feature? You cannot rely on headers for that

2021-03-03 13:53 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/internal/SecurityHelper.java
> +        String referer = request.getHeader("referer");
Yes, realized this is not a viable solution.

2021-03-03 15:34 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/internal/SecurityHelper.java
> +    public static boolean isInternalRequest(HttpServletRequest request) {
The `isInternalRequest` logic (from Bakery) is there used for two purposes: 1) in `CustomRequestCache` to check whether to save a request for redirect (which should be fine), but also 2) to grant `permitAll` to all internal requests (in which case the `Referer` check is a direct security hole):
https://github.com/vaadin/bakery-app-starter-flow-spring/blob/master/src/main/java/com/vaadin/starter/bakery/app/security/SecurityConfiguration.java#L83-L107
The helper would need to be specified to be used only for the first case.

2021-03-03 15:35 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/internal/SecurityHelper.java
> +    public static boolean isInternalRequest(HttpServletRequest request) {
And as a corollary, it's not really a security feature and so should probably be moved to a more appropriate class.

2021-03-04 08:32 UTC, joheriks commented
Closing this as not clear whether `isInternalRequest` logic is useful enough as a helper method. Fix in bakery:
https://github.com/vaadin/bakery-app-starter-flow-spring/pull/1160

2021-03-04 08:32 UTC, closed without merging