cache stats.json from classpath
vaadin/flow pull request #10244
Opened 2021-03-09 17:26 UTC by knoobie

Fixes #10116

2021-03-09 17:28 UTC, knoobie commented
@mshabarov  like we discussed, a more lightweight PR to fix the problem. 

My described problem(?) from the last PR is still present: 

About OSGI.. my implementation probably helps with the stats.json bundle deployment at a later time. But there is currently no way to force / refresh the cache when e.g. an already cached stats.json is redeployed / changed and the context isn't cleared. Should we do something about this? Like adding a method `clearCachedStatsJson` which could be invoked by OSGI on bundle deployment?

2021-03-10 06:30 UTC, mshabarov commented
> About OSGI.. my implementation probably helps with the stats.json bundle deployment at a later time. But there is currently no way to force / refresh the cache when e.g. an already cached stats.json is redeployed / changed and the context isn't cleared. Should we do something about this? Like adding a method clearCachedStatsJson which could be invoked by OSGI on bundle deployment?

I believe this case is rare (if even exists), when someone uses `stats.json` from another bundle, or even from another place by creating a custom `ResourceProvider`. I don't really know well all these scenarios, but adding such an API looks cheap and useful, so let's try to add it.

2021-03-10 09:58 UTC, knoobie commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
> +          Class.forName("com.vaadin.flow.server.frontend.FrontendUtils$Stats")
There shouldn't be a problem. This could remove some redundancy of the string. `Stats` is private, that's why I had to use `Class::forName` here.

2021-03-10 10:00 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +                stream = new ByteArrayInputStream(
I wasn't sure if the stream is already used up like e.g. HttpResponse where you can only read the body once. Gonna test it later and change it!

2021-03-10 10:44 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +                return null;
Done. Changed the method to `Optional<LocalDateTime>` and use it like this `modified.isAfter(statistics.getLastModified().orElse(LocalDateTime.MIN)` because `isPresent()` and `get()` would create multiple `LocalDateTime`.

2021-03-10 10:44 UTC, knoobie commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
> +          Class.forName("com.vaadin.flow.server.frontend.FrontendUtils$Stats")
Done.

2021-03-10 10:45 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +                stream = new ByteArrayInputStream(
`InputStream` can only be read once - changing this results in multiple test failures. The same code is used in the old method as well.

2021-03-10 11:35 UTC, mshabarov requested changes

2021-03-10 11:35 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
> +            System.err.println("Could not access cache key for stats.json!");
Please replace `System.err.println` with `Assert.fail`.
This would make it fail fast and easier to investigate the failed tests in `FrontendUtilsTest`.

2021-03-10 11:44 UTC, knoobie commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
> +            System.err.println("Could not access cache key for stats.json!");
Done :)

2021-03-10 12:43 UTC, merged

2021-03-10 18:28 UTC, mshabarov commented
@knoobie I'll take care of it. Older versions need a manual backport.