fix: fix shortcuts when listenOn is a dialog
vaadin/flow pull request #10264
Opened 2021-03-11 11:35 UTC by pleku

This makes it possible for a component to specify a client side only
element that should be used for listening keydown events on when the
component is setup as the listenOn target for a Shortcut. This is needed
for components like Vaadin Dialog which transport the dialog contents
inside an overlay that only exists on the client side and thus breaks
shortcut event handling.

Related to #7799, vaadin/vaadin-dialog#229

2021-03-11 12:28 UTC, caalador requested changes

2021-03-11 12:28 UTC, caalador commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DialogShortcutView.java
> +        // ui.add(this);
Commented out code that doesn't make sense as a comment.

2021-03-11 12:28 UTC, caalador commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DialogShortcutView.java
> +        // ui.remove(this);
Commented out code that doesn't make sense as a comment.

2021-03-11 12:30 UTC, pleku commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DialogShortcutView.java
> +        // ui.add(this);
Done

2021-03-11 12:30 UTC, pleku commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DialogShortcutView.java
> +        // ui.remove(this);
Done

2021-03-11 12:33 UTC, caalador approved these changes

2021-03-11 13:34 UTC, merged

2021-03-12 09:43 UTC, pleku commented
Cherry-picked manually to 2.5 and 2.6.