[plugin] extract flowResourcesFolder into AdapterBase
vaadin/flow pull request #10319
Opened 2021-03-17 23:27 UTC by stbischof

Gives Plugins possability to define FLOW_RESOURCES_FOLDER. 

Closes #10318

2021-03-22 10:35 UTC, caalador requested changes
`BuildFrontendUtil::runNodeUpdater` L241 still has the hardcoded folder  
```
        File flowResourcesFolder = new File(adapter.npmFolder(),
                DEFAULT_FLOW_RESOURCES_FOLDER);
```

Also as this is only set in BuildFrontend I guess running only prepare will generate a different result as it will still use the default target directory `File flowResourcesFolder = new File(baseDir, DEFAULT_FLOW_RESOURCES_FOLDER);` `DevModeInitialize:L278` The given folder should be also delegated here when only running PrepareFrontend

2021-03-22 10:35 UTC, caalador commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
> +
```suggestion
```

2021-03-22 10:35 UTC, caalador commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
> +     */
```suggestion
    /**
     * Default target folder to copy front-end resources to from jars present
     * on the classpath and project local frontend files in
     * frontendResourcesDirectory.
     *
     * @return {@link String}
     */
```

2021-03-22 17:12 UTC, stbischof commented
There is an other issue that will fix the static use of the target folder.

2021-03-23 05:08 UTC, caalador commented
But that is another case. Here we are adding the `flowResourcesFolder` through the plugin which should probably be written to the token file to get it into the configuration object in prepare-frontend and then removed from there in build-frontend step as then we shouldn't have any paths stored in the token file.

DevModeInitializer should then read the `PARAM_FLOW_RESOURCES` from the configuration as `File flowResourcesFolder = new File(baseDir, config.getStringProperty(PARAM_FLOW_RESOURCES, DEFAULT_FLOW_RESOURCES_FOLDER));`

2021-04-09 11:23 UTC, caalador commented
Is there still a need for this change as #10335 was fixed and the resources will go according to the defined build directory?

2021-04-09 19:09 UTC, stbischof commented
yes this should be enough!

2021-04-09 19:09 UTC, closed without merging