fix: Add reflections input filter
vaadin/flow pull request #10333
Opened 2021-03-18 11:26 UTC by caalador

Add input filtering so we only handle
class files from the classpath in
ReflectionsClassFinder

Closes #10304

2021-03-19 15:59 UTC, taefi requested changes

2021-03-19 15:59 UTC, taefi commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/server/scanner/ReflectionsClassFinder.java
> +                file -> file.endsWith(".class") && !file
```suggestion
                fileName -> fileName.endsWith(".class") && !fileName
```

2021-03-23 05:18 UTC, caalador commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/server/scanner/ReflectionsClassFinder.java
> +                file -> file.endsWith(".class") && !file
Actually the method says `sets the input filter for all resources to be scanned` so perhaps it should be `resource` instead of file or fileName?

2021-03-23 08:33 UTC, taefi commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/server/scanner/ReflectionsClassFinder.java
> +                file -> file.endsWith(".class") && !file
changed it to `resourceName` to also make the String nature of the argument more obvious.

2021-03-24 06:59 UTC, taefi approved these changes

2021-03-24 07:02 UTC, merged