feat: Add API to control whether Binder converts back to presentation…
vaadin/flow pull request #10343
Opened 2021-03-18 18:21 UTC by knoobie

… (forward port from FW 8 (framework#12246))

fixes #10342

2021-03-18 18:22 UTC, knoobie commented
@pleku If you want additional tests, like you mentioned in the pr that introduced this behavior (https://github.com/vaadin/flow/pull/9227) just let me know.

2021-03-19 07:39 UTC, pleku requested changes
Can you please add the `@see #...` links to the `withConverter` methods in `BindingBuilder` for the added API here. An mayhaps even clarify the javadocs for those that 
`The converter value is applied back to the field by default, but this can be controlled with the method {@link ...}.` 
I can do it myself too later on if needed. I should have done it for the original PR but lets fix things now.

Even as this adds API, I consider it to be a fix instead of feature since this is addressing a mistake in the original feature, thus I would land this as a fix to v19.

2021-03-19 07:39 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +         *
```suggestion
         * <p>
         * As of version 6.0, when a converter is used on a binding and the user input value is modified by the converter,
         * the value from the converter is applied back to the input. It is possible to control this behavior with this API.
         *
```

2021-03-19 07:45 UTC, knoobie commented
@pleku Sure, gonna update the other javadocs as well and improve your suggested message I just accepted to align with the character limit

2021-03-22 07:36 UTC, pleku approved these changes

2021-03-22 07:38 UTC, merged

2021-03-22 07:39 UTC, pleku commented
Thanks @knoobie.

2021-03-22 09:00 UTC, pleku commented
I don't know what happened but I apparently didn't use squash 🤦‍♂️

2021-03-22 09:07 UTC, knoobie commented
Want me to do something about it or can you fix it somehow with force push? I can create a pr for 6.0 as well

2021-03-24 10:07 UTC, pleku commented
Thanks for the manual CP @knoobie.

It would be now possible to cherry-pick both of the changes to 2.6 too but keep the default behavior (not write back changes).

2021-03-24 10:12 UTC, knoobie commented
@pleku The original change from Tatu did not land in 2.x (https://github.com/vaadin/flow/pull/9227) - should this be backported as well? Personally I would not backport Tatu and my change to 2.x but add a migration note to the next LTS (22) that the default behaviour is changed and can be configured with the new methods. 

My next step would have been to forward port https://github.com/vaadin/framework/issues/12207 with a proper test

2021-03-24 10:16 UTC, pleku commented
> should this be backported as well? 

Yes, that is what I meant to backport both the behavior change + the API to control it to get the value to the 14-series and it could allow upgrading towards next LTS behavior inside 14, if one wants to do so. But looking at vaadin/framework#12207 that would be more important.

2021-03-24 10:19 UTC, knoobie commented
Okay! Gonna forward port https://github.com/vaadin/framework/issues/12207 and see what I can do with cherry picking the changes from master to 2.x with a changed default value of `private boolean convertBackToPresentation = true;` to `false`.