chore: skip InjectManifestPlugin for non PWAs
vaadin/flow pull request #10361
Opened 2021-03-22 13:24 UTC by haijian-vaadin

A low-hanging optimization by skip creating the InjectManifestPlugin for non-PWAs.

2021-03-22 15:11 UTC, joheriks requested changes

2021-03-22 15:11 UTC, joheriks commented on flow-server/src/main/resources/webpack.generated.js
> +  };
Does it actually provide any performance improvement to wrap `swManifestTransform` into a function, since the value is already a function (meaning that the body doesn't get executed until it is actually called).

2021-03-22 15:20 UTC, haijian-vaadin commented on flow-server/src/main/resources/webpack.generated.js
> +  };
good catch, fixed.

2021-03-22 15:28 UTC, joheriks approved these changes

2021-03-24 08:20 UTC, joheriks approved these changes

2021-03-24 08:21 UTC, merged