chore: internal helper identifying framework internal requests
vaadin/flow pull request #10363
Opened 2021-03-22 14:54 UTC by joheriks

2021-03-23 10:17 UTC, pleku requested changes
One comment in code and also I'm not sure how "secure" is this API as one can quite easily just fake such a request type. Should the code maybe be in `HandlerHelper` instead to downplay this as a _security_ thing and maybe be more discoverable.

2021-03-23 10:17 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/internal/SecurityHelper.java
> +                .anyMatch(r -> r.getIdentifier().equals(parameterValue));
Would it make sense to refactor this code to reuse `HandlerHelper` code
```java
    public static boolean isRequestType(VaadinRequest request,
            RequestType requestType) {
```
as basically this is just doing the same but looking at all request types ?

2021-03-23 10:25 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/internal/SecurityHelper.java
> +        return parameterValue != null && Stream
You need to look at the URL also. A request to `/admin/verysecret.png?some=parameter` is not an internal framework request

2021-03-26 09:52 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/internal/SecurityHelper.java
> +                .anyMatch(r -> r.getIdentifier().equals(parameterValue));
Moved the method to HandlerHelper but `isRequestType` cannot be used as it requires a `VaadinRequest`

2021-03-26 09:53 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/internal/SecurityHelper.java
> +        return parameterValue != null && Stream
Fixed

2021-03-26 10:42 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/internal/SecurityHelper.java
> +                .anyMatch(r -> r.getIdentifier().equals(parameterValue));
Shouldn't `/myview?v-r=init` count as an internal request? At least Fusion client sends such requests to initialize Flow when opening a non-root server-side route:
https://github.com/vaadin/flow/blob/a685db13dc42012400c448834b2286ea595d8167/flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts#L338

2021-03-26 11:11 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/internal/SecurityHelper.java
> +                .anyMatch(r -> r.getIdentifier().equals(parameterValue));
I see, the problem is that you cannot use only pathInfo for this. Spring Security matchers always combine `getServletPath()` with `getPathInfo` so you get the full path relative to the context path. 

When e.g. requesting `"/VAADIN/build/vaadin-devmodeGizmo-2aa6cd8571de3aa0f313.cache.js"` pathInfo is `null` and `servletPath` is set to `"/VAADIN/build/vaadin-devmodeGizmo-2aa6cd8571de3aa0f313.cache.js"`. Similarly for `http://localhost:9090/bar` where `bar` should the path info but with Spring Security you get `"/bar"` as `servletPath` and `null` as `pathInfo`

We cannot ignore the path completely because that would mean that a secure resource like `/secret/topsecret.pdf` would become an internal Vaadin request by adding `?v-r=init` and probably then set to public access at the same time.

2021-03-26 11:14 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/internal/SecurityHelper.java
> +                .anyMatch(r -> r.getIdentifier().equals(parameterValue));
Is it correct that Flow.ts sends the `v-r=init` request to the current location or should it always send it to the context root?

2021-03-26 14:08 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/internal/SecurityHelper.java
> +                .anyMatch(r -> r.getIdentifier().equals(parameterValue));
So you can trust `pathInfo` in Spring when calling a servlet it seems. When fetching a static resource or calling an endpoint, it is `null`. So I think this approach should work if we can merge #10431

2021-03-26 14:50 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +            return Stream.of(RequestType.values()).anyMatch(r -> r.getIdentifier().equals(parameterValue));
This code looks like a hot code paths. I would personally don't use `Stream::of` here and use the gold old `for(RequestType r : RequestType.values()` for better performance.

2021-03-26 18:05 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +            return Stream.of(RequestType.values()).anyMatch(r -> r.getIdentifier().equals(parameterValue));
I think we could actually simplify it to `return parameterValue != null`

2021-03-26 18:10 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +            return Stream.of(RequestType.values()).anyMatch(r -> r.getIdentifier().equals(parameterValue));
I would argue against this, because in the end `parameterValue` is a user value and should be validated / sanitized against the valid values? Or am I too overly cautious?

2021-03-26 18:34 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +            return Stream.of(RequestType.values()).anyMatch(r -> r.getIdentifier().equals(parameterValue));
In this case we probably want to block all requests to `/` with an unknown `v-r` value and make it clear that is reserved for Vaadin internal use

2021-03-31 11:57 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +    public static boolean isFrameworkInternalRequest(
This really needs an additional check. If you map a `VaadinServlet` as `/myvaadin/*` then this would still return true for a request to `/?v-r?init`

2021-04-08 07:56 UTC, pleku requested changes

2021-04-08 07:56 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> -        return request.getService().getBootstrapUrlPredicate()
Should this API in the service be killed since it is not used from anywhere after this PR - both the setter and the getter are dead code ?

2021-04-08 07:56 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
> +    public void internal_request_no_bootstrap_page() {
nit: please stick to the existing test method naming convention next time

2021-04-08 08:04 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +        if (requestedPathWithoutServletMapping == null
They actually check different things. The check on 172 returns false if the path is not inside the servlet mapping. This method considers a `null` `pathInfo` the same as `""` and checks the request type

2021-04-08 08:04 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> -        return request.getService().getBootstrapUrlPredicate()
It is still used

2021-04-08 08:41 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +        if (requestedPathWithoutServletMapping == null
Doesn't that mean that for the same `VaadinServletRequest` request, whether it is considered internal or not, can be different for the two `isFrameworkInternalRequest` overload methods then ?
Since the one which takes `VaadinRequest` reports _an internal request_ when `requestedPathWithoutServletMapping == null` but the `requestTypeParameter` is not.
And one that takes `HttpServletRequest` reports _not internal_ `requestedPathWithoutServletMapping == null` regardless of the presence of the `requestTypeParameter`. So I take it that this is intentional, but I don't understand exactly why based on the code.

Maybe what is missing for being able to understand this even later on, is the intention on when each method should be called or how do they differ, which should be in the javadocs. Now they just take different parameters but have the same name and javadocs.

2021-04-08 08:43 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> -        return request.getService().getBootstrapUrlPredicate()
But there is nothing ever setting the predicate to anything else than the default which always return true ? Or is it being set from Spring ?

2021-04-08 08:46 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> -        return request.getService().getBootstrapUrlPredicate()
It has nothing to do with this change

2021-04-08 08:49 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +        if (requestedPathWithoutServletMapping == null
The only difference between the two methods is that the method taking `VaadinRequest` knows that the request is targeting a vaadin servlet. The other method first checks that the request is targeting a Vaadin servlet, using the given `servletMappingPath`

2021-04-08 08:50 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +        if (requestedPathWithoutServletMapping == null
The version taking a `VaadinRequest` is only needed to do an extra check in `BootstrapHandler` and `IndexHtmlRequestHandler` to ensure that they do not bootstrap something for an "internal request". It could be better to move it to `IndexHtmlRequestHandler` instead

2021-04-08 08:52 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +        if (requestedPathWithoutServletMapping == null
But that would mean that ```
isInternalRequestInsideServlet(
            String requestedPathWithoutServletMapping,
            String requestTypeParameter) {
```
would need to be public, which it shouldn't be...

2021-04-08 09:04 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> -        return request.getService().getBootstrapUrlPredicate()
Sure, it can be axed in a following PR

2021-04-08 09:04 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +        if (requestedPathWithoutServletMapping == null
Please just add the javadoc that documents that

2021-04-08 09:05 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +        if (requestedPathWithoutServletMapping == null
Ok, I moved one of the methods to `BootstrapHandler` instead so it is out of sight. Changed some docs and made the `getPathIfInsideServlet` method return an `Optional` instead so the return value from that is not confused with a `null` `pathInfo` value

2021-04-08 09:05 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +     * are not internal, even resource requests for the JS bundle.
Rewrote it

2021-04-08 09:07 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +            url += servletPath;
This branch lacks test coverage, would it make sense to add a test like:
```
    @Test
    public void test() {
        HttpServletRequest request = createRequest("/", RequestType.INIT);
        Mockito.when(request.getServletPath()).thenReturn("/abc");

        Assert.assertTrue(
                HandlerHelper.isFrameworkInternalRequest("/abc", request));
        Assert.assertFalse(
                HandlerHelper.isFrameworkInternalRequest("/", request));
    }
```

2021-04-08 09:16 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +            url += servletPath;
Added

2021-04-08 09:27 UTC, pleku submitted a review, later dismissed
...

2021-04-08 09:27 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/HandlerHelperTest.java
> +    public void test() {
`test()` ?

2021-04-08 09:29 UTC, Artur- commented on flow-server/src/test/java/com/vaadin/flow/server/HandlerHelperTest.java
> +    public void test() {
Removed

2021-04-08 09:51 UTC, pleku approved these changes

2021-04-08 10:55 UTC, merged