Remove offline stub
vaadin/flow pull request #10360
Opened 2021-03-22 11:53 UTC by joheriks

2021-03-25 20:23 UTC, haijian-vaadin requested changes
Looks good and works fine, great work.
A minor comment could be updated.
What's the breaking change? why use feat! instead of feat?

2021-03-25 20:33 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
>          // List of icons for precache
Fixed.

2021-03-25 20:59 UTC, joheriks commented
> Looks good and works fine, great work.
> A minor comment could be updated.
> What's the breaking change? why use feat! instead of feat?

Right, maybe `feat` is enough (my original line of thought behind was that it's breaking in the sense that `offlinePath` now has real impact on Fusion applications, whereas previously it was deprecated).

2021-03-26 07:20 UTC, haijian-vaadin submitted a review, later dismissed

2021-03-29 03:58 UTC, platosha submitted a review, later dismissed

2021-03-29 08:15 UTC, haijian-vaadin approved these changes

2021-03-29 08:15 UTC, merged

2021-03-29 08:42 UTC, haijian-vaadin commented
> Hi @joheriks , this commit cannot be picked to 6.0 by this bot, can you take a look and pick it manually?

cherry-picked in https://github.com/vaadin/flow/pull/10454