refactor: init adoption of vaadin gradle plugin in flow repo
vaadin/flow pull request #10377
Opened 2021-03-23 14:36 UTC by taefi

The goal for this adoption is:
- To test it against the changes in flow-plugin-base and flow-server and make
sure it is not broken.
- To be able to release it more easily with the same version as platform.
The source remains in kotlin and gradle will be used to build it under maven.

2021-03-24 06:49 UTC, caalador requested changes

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/build.gradle
> +group 'com.vaadin'
```suggestion
group '${pom.parent.groupId}'
```
So we use the pom groupId

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/build.gradle
> +    classifier = 'sources'
```suggestion
    archiveClassifier= 'sources'
```

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/build.gradle
> +                'Implementation-Version': version,
```suggestion
                'Implementation-Version': archiveVersion,
```

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/build.gradle
> +    maven { url 'target/dependencies' }
Do we actually need this as everything is installed into the local .m2 and should be gotten from there automatically

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/pom.xml
> +                <artifactId>maven-dependency-plugin</artifactId>
What exactly is this copying? I don't think that parents have anything worth copying and anything we need should come from the local .m2 anyway as they are installed.

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/AbstractGradleTest.kt
> +    val vaadinVersion = "20.0.0.alpha3"
```suggestion
    val flowVersion = System.getenv("vaadin.version").takeUnless { it.isNullOrEmpty() } ?: "7.0-SNAPSHOT"
```
We should probably get the version from the pom in some way.

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscMultiModuleTest.kt
> +                    compile("com.vaadin:vaadin-core:$vaadinVersion")
```suggestion
                    compile("com.vaadin:flow:$flowVersion")
```

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscMultiModuleTest.kt
> +                    compile("com.vaadin:vaadin-core:$vaadinVersion")
```suggestion
                    compile("com.vaadin:flow:$flowVersion")
```

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
> +            vaadin14 {
```suggestion
            vaadinPlatform {
```
The custom target should not be named 14 as this plugin version doesn't work with that. `Platform` is better.

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
> +                compile("com.vaadin:vaadin-core:$vaadinVersion")
```suggestion
                compile("com.vaadin:flow:$flowVersion")
```

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
> +                compile("com.vaadin:vaadin-core:$vaadinVersion")
```suggestion
                compile("com.vaadin:flow:$flowVersion")
```

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
> +                compile("com.vaadin:vaadin-core:$vaadinVersion")
```suggestion
                compile("com.vaadin:flow:$flowVersion")
```

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
> +                compile("com.vaadin:vaadin-core:$vaadinVersion")
```suggestion
                compile("com.vaadin:flow:$flowVersion")
```

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
> +                implementation('com.vaadin:vaadin-spring-boot-starter')
```suggestion
                implementation('com.vaadin:vaadin-spring-boot-starter:20.0-SNAPSHOT')
```

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
> +    fun testVaadin17SpringProjectProductionMode() {
```suggestion
    fun testVaadinSpringProjectProductionMode() {
```

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
> +                    mavenBom "com.vaadin:vaadin-bom:${"$"}{vaadinVersion}"
```suggestion
                    mavenBom "com.vaadin:flow:${"$"}{flowVersion}"
```

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
> +    fun testVaadin17SpringProjectProductionMode() {
This test should probably be run under platform only

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
> +                compile("com.vaadin:vaadin-core:$vaadinVersion")
```suggestion
                compile("com.vaadin:flow:$flowVersion")
```

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
> +                compile("com.vaadin:vaadin-core:$vaadinVersion")
```suggestion
                compile("com.vaadin:flow:$flowVersion")
```

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
> +                compile("com.vaadin:vaadin-core:$vaadinVersion")
```suggestion
                compile("com.vaadin:flow:$flowVersion")
```

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
> +                compile("com.vaadin:vaadin-core:$vaadinVersion")
```suggestion
                compile("com.vaadin:flow:$flowVersion")
```

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
> +        expect(false, buildInfo.toJson()) { buildInfo.getBoolean(Constants.SERVLET_PARAMETER_PRODUCTION_MODE) }
```suggestion
        expect(false, buildInfo.toJson()) { buildInfo.getBoolean(InitParameters.SERVLET_PARAMETER_PRODUCTION_MODE) }
```

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
> +        expect(false, buildInfo.toJson()) { buildInfo.getBoolean(Constants.SERVLET_PARAMETER_PRODUCTION_MODE) }
```suggestion
        expect(false, buildInfo.toJson()) { buildInfo.getBoolean(InitParameters.SERVLET_PARAMETER_PRODUCTION_MODE) }
```

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
> +        expect(true, buildInfo.toJson()) { buildInfo.getBoolean(Constants.SERVLET_PARAMETER_PRODUCTION_MODE) }
```suggestion
        expect(true, buildInfo.toJson()) { buildInfo.getBoolean(InitParameters.SERVLET_PARAMETER_PRODUCTION_MODE) }
```

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
> +import elemental.json.JsonObject
```suggestion
import com.vaadin.flow.server.Constants
import com.vaadin.flow.server.InitParameters
import elemental.json.JsonObject
```

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinCleanTask.kt
> +                "${project.projectDir}/package.json",
```suggestion
```
We shouldn't delete the package.json as there may be custom changes by the user.

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinCleanTask.kt
> +                      "tsconfig.json, types.d.ts, pnpm-lock.yaml, pnpmfile.js, package*.json and webpack.*.js"
```suggestion
                      "tsconfig.json, types.d.ts, pnpm-lock.yaml, pnpmfile.js and package-lock.json"
```

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
> +import com.vaadin.flow.server.frontend.FrontendTools
```suggestion
import com.vaadin.flow.server.Constants
import com.vaadin.flow.server.InitParameters
import com.vaadin.flow.server.frontend.FrontendTools
```

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
> +     * Vaadin, for example `"v12.16.0"`. Defaults to [FrontendTools.DEFAULT_NODE_VERSION].
```suggestion
     * Vaadin, for example `"v14.15.4"`. Defaults to [FrontendTools.DEFAULT_NODE_VERSION].
```

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
> +        val pnpmEnableProperty: Boolean? = project.getBooleanProperty(Constants.SERVLET_PARAMETER_ENABLE_PNPM)
```suggestion
        val pnpmEnableProperty: Boolean? = project.getBooleanProperty(InitParameters.SERVLET_PARAMETER_ENABLE_PNPM)
```

2021-03-24 06:49 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPlugin.kt
> +            extensionName = "vaadin14"
```suggestion
            extensionName = "vaadinPlatform"
```
Should not be named 14 as it is not supported by this version.

2021-03-24 08:33 UTC, caalador requested changes

2021-03-24 08:33 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/pom.xml
> +    <artifactId>vaadin-gradle-plugin</artifactId>
```suggestion
    <artifactId>flow-gradle-plugin</artifactId>
```

2021-03-24 08:33 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/build.gradle
> +archivesBaseName = 'vaadin-gradle-plugin'
```suggestion
archivesBaseName = '${pom.artifactId}'
```

2021-03-24 08:58 UTC, taefi commented on flow-plugins/vaadin-gradle-plugin/pom.xml
> +                <artifactId>maven-dependency-plugin</artifactId>
This copies the output of `flow-plugin-base` into the current module's `target/dependencies` and the `build.gradle` refers to this location for the dependency. The article was saying since the Gradle build is not aware of the maven reactor env, it would have some problems finding the dependencies directly from local `.m2`, but I haven't tested it. So I remove this and change `build.gradle`'s repositories after I evaluted whether it can work with local `.m2` or not.

2021-03-24 08:58 UTC, ZheSun88 commented on flow-plugins/vaadin-gradle-plugin/pom.xml
> +        <platform.version>20.0.0.alpha3</platform.version>
platform version should not be here.

2021-03-24 09:05 UTC, taefi commented on flow-plugins/vaadin-gradle-plugin/build.gradle
> +    maven { url 'target/dependencies' }
The article was saying gradle is not aware of the maven reactor and would have some problem finding the artifacts of the dependencies built in the current build session. I need to make sure if it can resolve that dependency from local .m2 before removing this.

2021-03-24 09:08 UTC, taefi commented on flow-plugins/vaadin-gradle-plugin/build.gradle
> + *
So, would it be like this?
```suggestion
 * Copyright 2018-2019 Devsoap Inc.
 * Copyright 2019-2021 Vaadin Ltd.
 *
```

2021-03-24 09:14 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/pom.xml
> +    </build>
```suggestion
    </build>
    

    <profiles>
        <profile>
            <id>windows_profile</id>
            <activation>
                <os>
                    <family>Windows</family>
                </os>
            </activation>
            <properties>
                <gradle.executable>./gradlew.bat</gradle.executable>
            </properties>
        </profile>
    </profiles>
```

Windows users will need this as `./gradlew` is not a valid windows executable

2021-03-24 09:19 UTC, caalador reviewed
Build should fail as the `MiscSingleModule::testVaadin8Vaadin14MPRProject` test using Vaadin14 wasn't changed to VaadinPlatform

2021-03-24 09:19 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/build.gradle
> +    archiveClassifier= 'sources'
```suggestion
    archiveClassifier = 'sources'
```
Formatting mistake

2021-03-24 09:20 UTC, taefi commented on flow-plugins/vaadin-gradle-plugin/pom.xml
> +        <platform.version>20.0.0.alpha3</platform.version>
Thanks! Yeah, it was a temporary thing for testing in the initial spike. Will be removed.

2021-03-24 09:20 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/build.gradle
> + *
Yes. Also you can batch apply suggestions if you are in the files changed tab.

2021-03-24 09:33 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/build.gradle
> +version = project.hasProperty('version') ? getProperty('version') : '20.0-SNAPSHOT'
```suggestion
group pom.parent.groupId
version = project.hasProperty('vaadin.version') ? project.getProperty('vaadin.version') : pom.parent.version
```

`version` seems to always be undefined so it always exists as a property.

2021-03-24 09:35 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/build.gradle
> +archivesBaseName = '${pom.artifactId}'
```suggestion
archivesBaseName = pom.artifactId
```

2021-03-24 09:38 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/build.gradle
> +archivesBaseName = '${pom.artifactId}'
These should aparently be direct reference or then a String e.g. `archivesBaseName = "${pom.artifactId}"`

2021-03-24 12:45 UTC, caalador commented on flow-plugins/vaadin-gradle-plugin/pom.xml
> +            <!-- execute Gradle command -->
The execution should probably be in 2 different profiles. One for running with tests and one for when we have skipTests

the `skipTests` profile should execute with the extra argument `-x functionalTest`

2021-03-24 22:31 UTC, taefi commented on flow-plugins/vaadin-gradle-plugin/build.gradle
> +    maven { url 'target/dependencies' }
I ensured that if the needed dependency (flow-plugin-base) is not available on non of the repositories (local, mavencentral, prereleases, etc.), even if it is being installed on the local .m2 prior to running the gradle build (in the same build session), initiated gradle build from maven cannot resolve it. So, I would keep it as the highest priority especially for local builds that need the latest changes from flow-plugin-base in the same build session.

2021-03-24 22:32 UTC, taefi commented on flow-plugins/vaadin-gradle-plugin/pom.xml
> +                <artifactId>maven-dependency-plugin</artifactId>
I ensured that if the needed dependency (flow-plugin-base) is not available on non of the repositories (local, mavencentral, prereleases, etc.), even if it is being installed on the local .m2 prior to running the gradle build (in the same build session), initiated gradle build from maven cannot resolve it. So, I would keep it as the highest priority especially for local builds that need the latest changes from flow-plugin-base in the same build session.

2021-03-24 22:32 UTC, taefi commented on flow-plugins/vaadin-gradle-plugin/pom.xml
> +            <!-- execute Gradle command -->
`skipTests` profile added.

2021-03-24 22:40 UTC, taefi commented
> Build should fail as the `MiscSingleModule::testVaadin8Vaadin14MPRProject` test using Vaadin14 wasn't changed to VaadinPlatform

fixed.

2021-03-25 05:05 UTC, caalador reviewed
Seems to build fine and most things are as expected. Now it's ok to move this to a feature branch

2021-03-25 06:38 UTC, caalador commented
Closing PR for move to feature branch after something with the license server is figured out.

2021-03-25 06:38 UTC, closed without merging