fix: Provide info on file name when Json parsing fails
vaadin/flow pull request #10423
Opened 2021-03-25 19:43 UTC by mshabarov

Adds a package file name to exception message in case of JsonException in order to provide clean explanation where to look into.

Fixes #10323

2021-03-31 10:21 UTC, caalador requested changes

2021-03-31 10:21 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
> +                "{ some broken json ", UTF_8);
This can be done only in the test and the file will be removed even without the teardown as it is in the temporaryFolder created by the test.

2021-03-31 15:07 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
>      }
Oh, stupid me. Thanks! done.

2021-03-31 15:07 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
> +                "{ some broken json ", UTF_8);
done

2021-03-31 15:08 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +                throw new RuntimeException(
Yes, it's better. Done

2021-04-01 03:49 UTC, caalador approved these changes

2021-04-01 03:50 UTC, merged