Make JavaScriptBootHandler only respond to servlet path and not all sub paths
vaadin/flow pull request #10431
Opened 2021-03-26 11:44 UTC by Artur-

Needed for #10363 and vaadin/spring#735

2021-03-26 14:58 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
> +        `?v-r=init` + (serverSideRouting ? `&location=${encodeURI(this.getFlowRoute(location))}` : '');
The same simplification could be applied also for the `HEAD` request ping to `sw.js` (used for setting the loading indicator state):
https://github.com/vaadin/flow/blob/a685db13dc42012400c448834b2286ea595d8167/flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts#L379-L380

2021-03-26 19:07 UTC, Artur- commented on flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
> +        `?v-r=init` + (serverSideRouting ? `&location=${encodeURI(this.getFlowRoute(location))}` : '');
Sure, created #10436 as it has nothing to do with this change

2021-04-06 09:05 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +            this.route = initRoute();
An alternative would be to pass a function `Function<VaadinRequest, Location>` initRoute` to the ctor the do the caching in the ctor as `this.route =  initRoute.apply(request)`, to make explicit that the route calculation must depend only on the request.

2021-04-06 09:42 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +            this.route = initRoute();
Do you think that would be clearer, i.e. should I change it?

2021-04-06 09:45 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +            this.route = initRoute();
It could prevent potential future confusion of someone trying to access a member field in the `JavaScriptBootstrapHandler` implementation and finds it to be null because this is called via the constructor.

2021-04-06 10:24 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +        }
Fixed

2021-04-06 10:24 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +            this.route = initRoute();
Fixed

2021-04-07 07:45 UTC, pleku requested changes
Would it be a terrible idea to add an IT that verifies that someone does later on add code that breaks the assumption that sub paths don't work with JSBH ? So basically checking that a request to `/foo?v-r=init...` would not work ?

2021-04-07 07:55 UTC, Artur- commented
Added a unit test

2021-04-07 08:23 UTC, pleku approved these changes
I was requesting for an IT but this is better than nothing.

2021-04-07 08:24 UTC, Artur- commented
What would an IT test? It is not an end user feature

2021-04-07 08:29 UTC, pleku commented
> What would an IT test? It is not an end user feature

Verify that nothing is served from bootstrap if you craft an init request with subpath. But now thinking about it, not sure what adding it would even gain.

2021-04-07 12:47 UTC, merged