Provide route path and parameters through BootstrapContext
vaadin/flow pull request #10449
Opened 2021-03-29 07:48 UTC by Artur-

Based on #10448

2021-04-06 12:03 UTC, pleku requested changes
Comments (see below) and also again the whole PR context is missing, please add the _why_ part too for the history books

2021-04-06 12:03 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
> +            return BootstrapHandler.requestToLocation(path, parameters);
Why is the `Location` created like this here instead of using the `BootstrapHandler::requestToLocation(VaadinRequest)` (that was added and to be moved elsewhere) ? I'm thinking that it is because there is a specific location parameter in the request. Sure. But the code is very weird as that is handled here in a private static method that calls then a super class public static method that says "this is only for v14 bootstrapping". IMO code would require some restructuring

2021-04-06 12:03 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java
> +import static org.mockito.Mockito.when;
meh, the import ordering gets broken here but it aint not wörth fixin

2021-04-06 13:32 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +     * Note that this is only valid for V14 mode bootstrap requests
Deleted the helpers in favor of #10570

2021-04-06 13:32 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +    public static Location requestToLocation(VaadinRequest request) {
Deleted the helpers in favor of #10570

2021-04-07 07:08 UTC, pleku approved these changes

2021-04-07 07:10 UTC, merged