fix: use getContentLengthLong instead getContentLength
vaadin/flow pull request #10506
Opened 2021-03-30 13:11 UTC by denis-anisimov

fixes #10392

2021-03-30 13:25 UTC, denis-anisimov commented
> @denis-anisimov how about reviewing #10438 instead ?

Done.

2021-03-31 13:48 UTC, mshabarov requested changes

2021-03-31 13:48 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinRequest.java
> +        return getContentLength();
`getContentLength()` returns `int`, which is then being casted to `long`.
And it still can have `-1` in case of integer max overflow.
From my understanding this method should delegate to `ServletRequest::getContentLengthLong`, isn't it?

2021-03-31 13:52 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinRequest.java
> +        return getContentLength();
This is only the `default` implementation. For `VaadinServletRequest` it is automatically overwritten because `VaadinServletRequest` extends `HttpServletRequestWrapper` which implements `ServletRequest` and automatically overwrites the default method. 

See the test:  https://github.com/vaadin/flow/pull/10506/files#diff-e157b1141a9838f0b904592b55a1936d0c23055958eafb4fd0de66d7e43e6ac3

2021-03-31 13:56 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinRequest.java
> +        return getContentLength();
Ah, thanks, now I see.

2021-03-31 14:15 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
>      protected long getContentLength(VaadinRequest request) {
Do you mean that the `VaadinRequest::getContentLengthLong` should be used instead? Makes sense.

2021-03-31 14:15 UTC, mshabarov approved these changes

2021-03-31 14:16 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
>      protected long getContentLength(VaadinRequest request) {
exactly that :)

2021-03-31 14:47 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
>      protected long getContentLength(VaadinRequest request) {
I'm not merging this PR, let @denis-anisimov decide whether it's needed.

2021-04-01 06:08 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
>      protected long getContentLength(VaadinRequest request) {
Done.

2021-04-01 06:10 UTC, mshabarov approved these changes

2021-04-01 06:34 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
> +        long contentLength = getContentLength(request);
```suggestion
        long contentLength = request.getContentLength();
```

2021-04-01 06:59 UTC, merged