Add support for parsing query string in QueryParameters
vaadin/flow pull request #10521
Opened 2021-03-31 07:29 UTC by Artur-

2021-04-01 10:11 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +                StandardCharsets.UTF_8);
The only place where apache.http.client is used is in devmode for downloading node - that has been copied from frontend-maven-plugin. And that code should be removed from `flow-server` to its own place so that would not be leaking to user applications. But this is not your fault.

But if you introduce a further dependency to it, then it will be more difficult for us to make this refactoring.
The code not the same exactly, but close to what `Location` does too to query parameters. Would it be possible to reuse-modify the code there instead ?

2021-04-01 11:13 UTC, pleku requested changes
(just changing status to show that this is not waiting for review)

2021-04-01 16:14 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +    public static QueryParameters fromString(String queryString) {
Added mentioned that it is needed by #10431

2021-04-01 16:21 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +                StandardCharsets.UTF_8);
I will move the code from `Location.parseParams` to replace this. Would have helped a lot if it had been in the correct class earlier. 

Sadly the implementation is partly broken so it also needs to be fixed at the same time

2021-04-01 16:43 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +                StandardCharsets.UTF_8);
Overall I don't understand why we have this generic util methods implemented in the framework in a slightly broken way when there are perfectly fine and tested util libraries out there that you can use.

The current method needed two fixes to be compatible with what `HttpServletRequest.getParameters` returns:
1. It needs to decode values
2. A parameter like "?hello" should map to an empty string and not no value at all like the old method did

Hopefully this does not break something else then

2021-04-06 07:50 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +                StandardCharsets.UTF_8);
> Overall I don't understand why we have this generic util methods implemented in the framework in a slightly broken way when there are perfectly fine and tested util libraries out there that you can use

The problem is the broken code in the code base. We should not try reinvent the wheel, but also not bring in libraries only to depend on a subset of the code there. It is a balancing act.

2021-04-06 07:54 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +                StandardCharsets.UTF_8);
If you want to avoid external dependencies, there is always the possibility of rebasing the given class and including it directly in the project. Then it is possible to update it etc for new releases, there are no conflicts and no dependencies either

2021-04-06 08:24 UTC, pleku requested changes
One question and suggestion.

The changes in this PR are fine, but when I look at the code flow (which this PR doesn't change, just the implementation), it does smell a bit. It seems like the code in the framework could be (later) improved to 
1) only parse the query parameters when needed
2) cache the query strings for the ongoing request, now parse again and again
3) see if the query string parsing code from the http request implementation could be reused, like from `AtmosphereRequest` since it handles both 1+2 from above
I can create an issue for this after this is merged.

2021-04-06 08:24 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +     *
I think the code is fine. But as the string can come from the user, this parsing might be a subject for DoS exploit, but I think the computations done inside the stream-map-collect are so simple that the query string limit of 1024 characters should not make it exploitable. Do you agree ?

I would consider adding some clarification to the method javadocs that this is code here is not checking for the length of the given query string - it is the responsibility of the caller.

2021-04-06 08:27 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +                StandardCharsets.UTF_8);
Yes I think that is the least bad solution, to copy-paste the code and update it manually, in case the code cannot be / is not released as a standalone module.

2021-04-06 08:49 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +                StandardCharsets.UTF_8);
So should we do it here? In that case I would revert to the original version more or less to use the lib and then make a separate PR about including it directly in the project instead of as a dependency

2021-04-06 08:53 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +                StandardCharsets.UTF_8);
Because of the internal dependencies, it might not make sense to copy paste... It would lead to extracting the whole `httpcore` jar into the project

2021-04-06 09:34 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +     *
Where would the DoS exploit possibility come from?

2021-04-06 09:41 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +     *
Like discussed separately, from using this code to parse a string that originates from client and it is very very long and because it is for some reason limited to 1024. This comment is enough for now.

2021-04-06 09:42 UTC, pleku approved these changes

2021-04-06 11:07 UTC, merged