feat!: endpoint access is denied by default
vaadin/flow pull request #10526
Opened 2021-03-31 10:33 UTC by joheriks

2021-03-31 11:18 UTC, haijian-vaadin commented
The code change looks good to me. Just one remind from Leif regarding the error message for access denied:
For production mode, the current message is fine.
For dev mode, in case a dev forgets to add any annotations, we could show an error message like
"The access is denied by default, you can use the following annotations to the endpoint to allow access"

2021-03-31 11:43 UTC, knoobie commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
> -
I think this should stay and changed to `return false` otherwise you could run into NPE later on with `rolesAllowed.value()`.

2021-03-31 11:50 UTC, joheriks commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
> -
It's guarded by the caller a few lines above (`rolesAllowed != null && roleAllowed(rolesAllowed, request)`). I'd prefer non-nullable parameter by default (like `request`).

2021-03-31 11:53 UTC, knoobie commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
> -
Ahh thanks! I was looking at the original code, where it's called without the guard.

2021-04-01 06:10 UTC, joheriks commented
> The code change looks good to me. Just one remind from Leif regarding the error message for access denied:
> 
> * For production mode, the current message is fine.
> * For dev mode, in case a dev forgets to add any annotations, we could show an error message like
>   "The access is denied by default, you can use the following annotations to the endpoint to allow access"

The message shown in dev mode is now more detailed, nudging the dev towards using the annotations.

2021-04-01 06:10 UTC, haijian-vaadin requested changes

2021-04-01 06:10 UTC, haijian-vaadin commented on fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessCheckerTest.java
> +    public void should_notShowHelpfulMessage_When_accessDeniedInDevMode()
ProductionMode?

2021-04-01 06:12 UTC, haijian-vaadin approved these changes

2021-04-01 06:12 UTC, joheriks commented on fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessCheckerTest.java
> +    public void should_notShowHelpfulMessage_When_accessDeniedInDevMode()
A copy-paste typo, fixed.

2021-04-01 09:42 UTC, merged