feat: Add gradle plugin
vaadin/flow pull request #10542
Opened 2021-04-01 08:07 UTC by caalador

Add gradle plugin into the plugins-module.

2021-04-01 12:11 UTC, pleku commented on flow-plugins/flow-gradle-plugin/README.md
> +| 0.20.0.0.alpha3              | Vaadin 20 and higher, experimental support for Vaadin 19 |
```suggestion
| 0.20.0.0.alpha3              | experimental support for Vaadin 19 and 20 |
| 20.0.0                            | Vaadin 20 and higher |
```

2021-04-01 12:30 UTC, pleku requested changes
Couple of comments + questions

2021-04-01 12:30 UTC, pleku commented on flow-plugins/flow-gradle-plugin/README.md
> +* `vaadinClean` will clean the project completely and removes JavaScript packaging-related
Just commenting that we don't have this for the maven plugin but should make it unified.

2021-04-01 12:30 UTC, pleku commented on flow-plugins/flow-gradle-plugin/README.md
> +  pnpmEnable = true
I don't get this - how does `pnpmEnable` relate to enabling vaadin gradle plugin? Or is it surplus ? Should it be production mode instead ?

2021-04-01 12:30 UTC, pleku commented on flow-plugins/flow-gradle-plugin/README.md
> +All configuration options follow. Note that you **RARELY** need to change anything of the below.
I disagree, production mode is something that you should be aware of.

2021-04-01 12:30 UTC, pleku commented on flow-plugins/flow-gradle-plugin/README.md
> +The main entry to the plugin is the `VaadinPlugin` class. When applied to the project, it will register
I wonder if this is still valid, will see soon

2021-04-01 12:30 UTC, pleku commented on flow-plugins/flow-gradle-plugin/README.md
> +## Branches
This is not up to date, should just remove it

2021-04-01 12:30 UTC, pleku commented on flow-plugins/flow-gradle-plugin/pom.xml
> +
Description missing - please add with information on how this relates to `vaadin-gradle-plugin`

2021-04-01 12:30 UTC, pleku commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
> + * @since 2.0
```suggestion
```

2021-04-01 12:30 UTC, pleku commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
> +public open class VaadinFlowPluginExtension(project: Project) {
Just commenting that there are a lot of things that are not configurable via maven here - are these configurations still valid for gradle ? Like deciding if bundle should be created or npm install run after updating the dependencies

2021-04-06 03:59 UTC, caalador commented on flow-plugins/flow-gradle-plugin/README.md
> +  pnpmEnable = true
I think it's from a time when npm was the default instead of pnpm so before v14.3?

2021-04-06 05:11 UTC, mstahv commented on flow-plugins/flow-gradle-plugin/build.gradle
> + * Copyright 2018-2019 Devsoap Inc.
I wonder what is left from the Devsoap version here in the build script that is worth copyright notice. Also, this is build script, maybe remove the license header altogether 🤔

2021-04-06 05:11 UTC, mstahv commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
> +public open class VaadinFlowPluginExtension(project: Project) {
@mvysny You might be the best source to comment.

2021-04-06 05:32 UTC, caalador commented on flow-plugins/flow-gradle-plugin/README.md
> +  pnpmEnable = true
We should probably only have the development info in the README and the rest should live in the docs.

2021-04-06 07:18 UTC, pleku commented on flow-plugins/flow-gradle-plugin/build.gradle
> + * Copyright 2018-2019 Devsoap Inc.
I missed this, but nor do I understand how build scripts would even have license header (similar to pom.xml) and we'll just drop the header

2021-04-06 08:01 UTC, mvysny commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
> +public open class VaadinFlowPluginExtension(project: Project) {
Those settings were taken from Maven plugin 14.3.x's sources and they were most probably not cleaned up when adding support for Vaadin 20. We should find such settings and remove them, so that Gradle plugin has the same set of settings as Maven plugin does.

2021-04-06 08:03 UTC, mvysny commented on flow-plugins/flow-gradle-plugin/README.md
> +All configuration options follow. Note that you **RARELY** need to change anything of the below.
True, we should reword this to "...apart from the production mode, there's rarely any need to change..." or similar. The point was to stop users from tinkering with the settings, shooting themselves to the foot.

2021-04-06 08:10 UTC, mvysny commented on flow-plugins/flow-gradle-plugin/README.md
> +* `vaadinClean` will clean the project completely and removes JavaScript packaging-related
In such case I propose to add similar functionality to Maven plugin as requested here: https://github.com/vaadin/flow/issues/8885 . I have seen Vaadin Dance being helpful to users, and `vaadinClean` essentially performs the dance very quickly.

2021-04-06 08:30 UTC, pleku commented on flow-plugins/flow-gradle-plugin/README.md
> +* `vaadinClean` will clean the project completely and removes JavaScript packaging-related
At least now the issue has a reference to here so it should be OK for now

2021-04-06 11:29 UTC, taefi commented on flow-plugins/flow-gradle-plugin/README.md
> +The main entry to the plugin is the `VaadinPlugin` class. When applied to the project, it will register
As the structure of gradle plugin was not changed during the process of adopting its source code under flow project, I believe this is still valid.

2021-04-06 12:08 UTC, pleku requested changes
Readme changes still missing, outdated content to be 🪓

2021-04-06 12:34 UTC, taefi commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
> +public open class VaadinFlowPluginExtension(project: Project) {
I scanned all the setting properties defined in `VaadinFlowPluginExtension.kt` and noticed all of them are present either in `FlowModeAbstractMojo.java` or in `BuildFrontendMojo.java`, especially `runNpmInstall` and `generateBundle`. Although there may be no way to configure them even in the maven and always their default values are in use, I propose to keep them for now, and clean them up in a separate task for both maven and gradle plugins at the same time.

2021-04-06 12:42 UTC, taefi commented on flow-plugins/flow-gradle-plugin/build.gradle
> + * Copyright 2018-2019 Devsoap Inc.
The license header is removed.

2021-04-06 12:42 UTC, taefi commented on flow-plugins/flow-gradle-plugin/pom.xml
> +
Added.

2021-04-06 12:42 UTC, taefi commented on flow-plugins/flow-gradle-plugin/README.md
> +## Branches
Done.

2021-04-06 12:43 UTC, taefi commented on flow-plugins/flow-gradle-plugin/README.md
> +All configuration options follow. Note that you **RARELY** need to change anything of the below.
`## Configuration` heading is removed from README and will be added to the docs.

2021-04-06 12:43 UTC, taefi commented on flow-plugins/flow-gradle-plugin/README.md
> +  pnpmEnable = true
Removed from README.

2021-04-06 13:00 UTC, pleku approved these changes

2021-04-06 13:00 UTC, pleku commented on flow-plugins/flow-gradle-plugin/README.md
> +
Several topics from above here are too not related to developing the plugin ... but you can revisit those after working on the docs

2021-04-06 18:11 UTC, merged