fix: Do not use hardcoded target directory
vaadin/flow pull request #10569
Opened 2021-04-06 11:41 UTC by caalador

Any code writing to the build directory should
not depend on a hardcoded `target` directory
as for instance gradle uses `build` and it may
be configured also in Maven.

Fixes #10335

2021-04-07 11:26 UTC, taefi commented on flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
> -            testProject.build("-Pvaadin.productionMode", "clean", "build")
Are these *clean*s removed because of having no effect as `testProject` is created before each task?

2021-04-07 11:33 UTC, caalador commented on flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
> -            testProject.build("-Pvaadin.productionMode", "clean", "build")
The build fails the `clean` step due to clean being `UP-TO-DATE` instead of `SUCCESS`

2021-04-08 17:52 UTC, taefi commented on flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
> +        ReflectionUtils.setVariableValueInObject(mojo, "projectBasedir",
Is the `dir` in `projectBasedir` not camel-case intentionally?

2021-04-08 18:45 UTC, taefi requested changes
Please consider sonar deprecation comments where possible.

2021-04-08 18:45 UTC, taefi commented on flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
> +
Should we add another test to make sure when the `projectBuildDir` is set to `build`, nothing is created in the maven default `target` folder?

2021-04-08 18:45 UTC, taefi commented on flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
> +
These import statics are better to be moved below other imports.

2021-04-08 18:45 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
> +                new File(baseDir, "target/classes"), WEBPACK_CONFIG,
```suggestion
                new File(baseDir, TARGET + "/webapp"),
                new File(baseDir, TARGET + "/classes"), WEBPACK_CONFIG,
```

2021-04-09 03:58 UTC, caalador commented on flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
> +        ReflectionUtils.setVariableValueInObject(mojo, "projectBasedir",
It's from the refactoring so probably not intentional, but not a part for this PR.

2021-04-09 07:47 UTC, taefi approved these changes

2021-04-09 07:55 UTC, merged