fix: store spring csrf to bootstrap page
vaadin/flow pull request #10577
Opened 2021-04-07 12:05 UTC by haijian-vaadin

2021-04-08 10:14 UTC, joheriks requested changes

2021-04-08 10:14 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +                if( springCsrfTokenJson!=null ){
Maybe guard this also with `springCsrfTokenJson.hasKey("token") && springCsrfTokenJson.hasKey("headerName")`? 

nit: The formatting is off.

2021-04-08 10:26 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +                if( springCsrfTokenJson!=null ){
done, also extracted strings to constants

2021-04-08 11:09 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/Authentication.ts
> +    csrfHeaderNameMetaTag.content = headerName;
Could the duplicate part be split out into a method with a signature like `updateMetaTag(name, value)`?

2021-04-08 11:10 UTC, fluorumlabs requested changes

2021-04-08 11:18 UTC, haijian-vaadin commented on flow-client/src/main/resources/META-INF/resources/frontend/Authentication.ts
> +    csrfHeaderNameMetaTag.content = headerName;
good point, done

2021-04-08 11:24 UTC, haijian-vaadin commented on flow-client/src/main/resources/META-INF/resources/frontend/Authentication.ts
> +  if (Object.keys(newHeaders).length > 0) {
that's basically what it does in the code.
The thing is the meta tags are not always necessary in the document, e.g. when starting offline, then we need to add. If it already exists, then we update the value.
remove and append would have the same level of complexity. 
We could on the other hand reduced some duplicated code make it look less complex.

2021-04-08 11:37 UTC, fluorumlabs commented on flow-client/src/main/resources/META-INF/resources/frontend/Authentication.ts
> +  if (Object.keys(newHeaders).length > 0) {
I was thinking of something like

```javacript
    Array.from(document.head.querySelectorAll('meta[name="_csrf"], meta[name="_csrf_header"]'))
        .forEach(el => el.remove());
    Array.from(doc.head.querySelectorAll('meta[name="_csrf"], meta[name="_csrf_header"]'))
        .forEach(el => document.head.appendChild(el));
```

2021-04-08 12:11 UTC, haijian-vaadin commented on flow-client/src/main/resources/META-INF/resources/frontend/Authentication.ts
> +  if (Object.keys(newHeaders).length > 0) {
Good suggestion

2021-04-08 14:43 UTC, platosha commented on flow-client/src/main/resources/META-INF/resources/frontend/Authentication.ts
> +  if (Object.keys(newHeaders).length > 0) {
Moving nodes across documents may not be supported in DOM API, AFAIK you need [document.importNode](https://developer.mozilla.org/en-US/docs/Web/API/Document/importNode) or adoptNode in between:

```javascript
...
.forEach(el => document.head.appendChild(document.importNode(el)));
```

2021-04-08 15:03 UTC, platosha requested changes

2021-04-08 15:03 UTC, platosha commented on flow-client/src/test/frontend/AuthenticationTests.ts
> +        throw new LogoutError('failed to logout with response 403');
Please insert a mock 403 response here instead of throwing in the `fetch` mock callback, so that we actually test a code path for when `fetch` returns a non-2xx response.

2021-04-08 15:03 UTC, platosha commented on flow-client/src/test/frontend/AuthenticationTests.ts
> +        throw new LogoutError('failed to logout with response 403');
Also don’t throw but have a mock unauthorised response.

2021-04-08 15:03 UTC, platosha commented on flow-client/src/test/frontend/AuthenticationTests.ts
> +        throw new LogoutError('failed to logout with response 403');
Also don’t throw but have a mock unauthorised response.

2021-04-08 16:43 UTC, haijian-vaadin commented on flow-client/src/main/resources/META-INF/resources/frontend/Authentication.ts
> +      delete (window as any).Vaadin.TypeScript.csrfToken;
good catch, done

2021-04-08 16:45 UTC, haijian-vaadin commented on flow-client/src/main/resources/META-INF/resources/frontend/Authentication.ts
> +  const responseText = await response.text();
good catch, done

2021-04-08 16:45 UTC, haijian-vaadin commented on flow-client/src/main/resources/META-INF/resources/frontend/Authentication.ts
> +  if (Object.keys(newHeaders).length > 0) {
done

2021-04-08 16:45 UTC, haijian-vaadin commented on flow-client/src/test/frontend/AuthenticationTests.ts
> +        throw new LogoutError('failed to logout with response 403');
very good point, done

2021-04-08 16:45 UTC, haijian-vaadin commented on flow-client/src/test/frontend/AuthenticationTests.ts
> +        throw new LogoutError('failed to logout with response 403');
very good point, done

2021-04-08 16:46 UTC, haijian-vaadin commented on flow-client/src/test/frontend/AuthenticationTests.ts
> +        throw new LogoutError('failed to logout with response 403');
very good point, done

2021-04-08 20:20 UTC, fluorumlabs submitted a review, later dismissed

2021-04-09 07:21 UTC, platosha approved these changes

2021-04-09 07:32 UTC, joheriks approved these changes

2021-04-09 07:32 UTC, merged