fix: Extract theme name from proper folder and skip generated files
vaadin/flow pull request #10584
Opened 2021-04-07 14:33 UTC by mshabarov

Extract a custom theme name from frontend generated folder and skips theme handling when the theme generated file is being created/updated.

Related-to #10451, #10544

2021-04-08 11:50 UTC, mshabarov commented
Test for switching a theme name is in progress, but this fix can be validated manually and merged, as the issue is severe.

2021-04-09 07:26 UTC, pleku requested changes

2021-04-09 07:26 UTC, pleku commented on flow-server/src/main/resources/plugins/theme-live-reload-plugin/package.json
> +  "version": "2.0.0",
Not sure if it makes any difference, but should this just be a maintenance/minor bump ?

2021-04-09 07:36 UTC, mshabarov commented on flow-server/src/main/resources/plugins/theme-live-reload-plugin/theme-live-reload-plugin.js
> +              if (file.endsWith('.generated.js')) {
done

2021-04-09 07:37 UTC, mshabarov commented on flow-server/src/main/resources/plugins/theme-live-reload-plugin/package.json
> +  "version": "2.0.0",
I followed the rule that changing the API (constructor) is a breaking change, and, thus, is a `+1.0.0`.

2021-04-09 09:06 UTC, pleku reviewed
Testing the changes:
- adding /components and new files there seems to work
- adding & removing css that is imported to `styles.css` seems to work
- switching the theme on the fly:
1) first try failed with
```ERROR in ./generated/theme.js
Module not found: Error: Can't resolve './theme-myapp.generated.js' in 'C:\Users\Pekka\workspaces\my-app\frontend\generated'
 @ ./generated/theme.js 1:0-69 2:26-37
 @ ./generated/vaadin.ts
Child HtmlWebpackCompiler:
     1 asset
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
       1 module
Child InjectManifest:
     1 asset
    Entrypoint InjectManifest = sw.js
    [../target/sw.ts] 3.1 KiB {InjectManifest} [built]
        + 92 hidden modules
i ?wdm?: Failed to compile.

------------------ Frontend compilation failed. ------------------
```
2. second try later on, it worked
3. third try, back to original theme, worked

2021-04-09 09:10 UTC, pleku commented on flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
> +                "vaadin-text-field.css");
Should it test instead creating the file after the webpack is running ? Or should there be another test that does that? To cover both: changing existing component css and adding a new component css file with theme ?

2021-04-09 10:04 UTC, mshabarov commented on flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
> +                "vaadin-text-field.css");
> Should it test instead creating the file after the webpack is running ?

Currently, a new component css file is being created. And it happens after webpack is running.

> To cover both: changing existing component css and adding a new component css file with theme ?

I will add one more test to check the existing component css file changing.

2021-04-09 12:53 UTC, pleku approved these changes

2021-04-09 12:53 UTC, pleku commented on flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
> +    private String convertRgbToHex(String styleString) {
I think there is plenty of CSS that could be used without involving colors and complex converting code for test like this, it feels like a waste of time for me to check the color of something when you could just change something else ...

2021-04-09 12:57 UTC, pleku commented on flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
>                  "Red background is not expected before applying the styles",
Would it make sense to split the test into two:
- create css - reload works
- create font - reload works

2021-04-09 14:44 UTC, mshabarov commented on flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
> +    private String convertRgbToHex(String styleString) {
Yes, I've reverted it because it doesn't work anyway. Trying to use an attached element (similar to java live reload tests) and check its counter. Checking the client callback in Flow seems to work unstable and sometimes the checking code is faster than the live reload.

2021-04-09 14:54 UTC, pleku requested changes

2021-04-09 14:54 UTC, pleku commented on flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
> +        waitUntilComponentCustomColor(BORDER_RADIUS);
..CustomColor(BORDER_RADIUS); ?

2021-04-09 14:54 UTC, pleku commented on flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
> +        waitUntilComponentCustomColor(OTHER_BORDER_RADIUS);
...CustomColor(BORDER_RADIUS); ?

2021-04-09 14:54 UTC, pleku commented on flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
> +        waitUntil(driver -> isComponentCustomStyle(borderRadius));
Should this be just removed or ?

2021-04-09 15:02 UTC, mshabarov commented on flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
>                  "Red background is not expected before applying the styles",
Divided into two tests.

2021-04-09 15:05 UTC, mshabarov commented on flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
> +        waitUntilComponentCustomColor(BORDER_RADIUS);
Renamed

2021-04-09 15:06 UTC, mshabarov commented on flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
> +        waitUntilComponentCustomColor(OTHER_BORDER_RADIUS);
Renamed

2021-04-09 15:06 UTC, mshabarov commented on flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
> +        waitUntil(driver -> isComponentCustomStyle(borderRadius));
Why? I believe not

2021-04-09 15:46 UTC, pleku approved these changes

2021-04-09 15:48 UTC, pleku commented on flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
>                  "Red background is not expected before applying the styles",
Not done ? I meant that there would be several `@Test` for different changes. But that was a question/suggestion, it is just refactoring

2021-04-12 09:27 UTC, mshabarov commented on flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
>                  "Red background is not expected before applying the styles",
Unfortunately, I cannot split those tests, because TB runs them concurrently (despite `@NotThreadSafe` on the class), or I don't know who is a culprit, but they erase styles of each other when running from different methods.
I'm going to create an issue in TB regarding that, it's not a first time I notice that behaviour, WDYT @pekka?

2021-04-12 10:05 UTC, pleku commented on flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
>                  "Red background is not expected before applying the styles",
Ok. That sounds very bad indeed. It should be trivial (for users, like us) to make a TB test not executed in parallel.

Please make an issue and we'll have to look at that later on

2021-04-12 10:12 UTC, pleku reviewed
I'll have to retest things as the watched configuration was changed

2021-04-12 10:12 UTC, pleku commented on flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
> +    public void webpackLiveReload_newComponentCssCreatedAndDeleted_stylesUpdatedOnFly() {
Now I'm confused - you commented above that this cannot be done as the tests might be run parallel - which would also imply that in this case there might be a random-sequence of reloads in the browser since the execution of the each `@Test` could cause a reload when run in parallel in the CI ?

2021-04-12 10:33 UTC, mshabarov commented on flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
> +    public void webpackLiveReload_newComponentCssCreatedAndDeleted_stylesUpdatedOnFly() {
Hmm, you're right. Another test can trigger live reload right after another test changes the styles. That could lead to 'false positive' test result, i.e. live reload doesn't work for one of those two cases, but another test triggers it => test passed erroneously.
Well, then they should be in the same method.

2021-04-12 12:04 UTC, pleku approved these changes
Retested live reload and seems to work. Only get an unrelated error when swapping the theme from `readManifestPaths` but when I remove the `@PWA` then the theme swap works again.

Just one thing to note is that any changes to `theme.json` do not trigger a recompilation until the resources are referenced from the css or Java code is recompiled, but this is fine.

2021-04-12 12:12 UTC, pleku commented
Would it be time to separate the fix into another PR and take the fix in ?

2021-04-12 12:14 UTC, mshabarov commented
> Would it be time to separate the fix into another PR and take the fix in without the not-working integration tests ?
Yes, will do

2021-04-15 05:51 UTC, mshabarov commented
Apparently, the problem was in having https://github.com/vaadin/flow/issues/9948, and the test failed when it was waiting until rendering the attached identifier element after deleting component style - the page probably was refreshed too early before actual webpack re-compilation, thus, the identifier was obsolete and wait condition failed.

2021-04-15 09:57 UTC, pleku requested changes

2021-04-15 09:57 UTC, pleku commented on flow-tests/test-application-theme/test-theme-component-live-reload/pom.xml
> +            <version>${project.version}</version>
nit: this probably should be in test scope but it is very little difference

2021-04-15 09:57 UTC, pleku commented on flow-tests/test-application-theme/test-theme-component-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadIT.java
> +            doActionAndWaitUntilLiveReloadComplete(() -> {
It seems weird that the cleanup code does wait for live reload to happen - is there a reason for that ? Is it part of the test ? Probably _the why_ should commented

2021-04-15 10:09 UTC, mshabarov commented on flow-tests/test-application-theme/test-theme-component-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadIT.java
> +            doActionAndWaitUntilLiveReloadComplete(() -> {
I wrapped these delete actions in a wait loop because:
1. To not leave the server in a reloading state after the test. There might be a second test rerun and the reload can affect it, and it then would be confusing for investigator what actually happened.
2. In case when in the future there comes any other `@Test` methods potentially (after solving TB parallel execution), it's good to start it without any live reload ongoing.

Will add an explanation comment there.

2021-04-15 10:11 UTC, mshabarov commented on flow-tests/test-application-theme/test-theme-component-live-reload/pom.xml
> +            <version>${project.version}</version>
done

2021-04-15 10:11 UTC, mshabarov commented on flow-tests/test-application-theme/test-theme-component-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadIT.java
> +            doActionAndWaitUntilLiveReloadComplete(() -> {
added

2021-04-15 10:21 UTC, pleku approved these changes

2021-04-15 11:06 UTC, merged