feat: Use (p)npm to install flow plugins
vaadin/flow pull request #10596
Opened 2021-04-08 10:03 UTC by caalador

This also simplifies plugin development
by having the plugins in the build folder.

Fixes #10306

2021-04-08 10:03 UTC, caalador commented
Depends on #10569 to not use hardcoded folders.

2021-04-12 08:31 UTC, pleku requested changes
This change is a bit weird in the sense that the issue is about being able to
1) install dependencies with npm
2) run webpack manually

which is a "new feature". The suggested change here fixes things so that it possible to now achieve 1+2 (?) but it is not tested in any way that it is actually possible now or it won't get broken later on. So this seems like this is not a new feature (as there are no tests that validate this) but just refactoring that makes things work for now.

2021-04-12 08:31 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPlugins.java
>       * Copy Flow webpack plugins into the given nodeModulesFolder.
Javadocs not updated

2021-04-12 08:31 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPlugins.java
> +    protected static final String PLUGIN_TARGET = "plugins";
Nit: missing javadocs for protected

2021-04-12 08:31 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPlugins.java
> +    protected static List<String> getPlugins() {
Even though this API might be possible to be converted to be static, I'm not sure if it should be just done so and still kept in this class - doesn't seem clean as this is supposed to be a _task to install webpack plugins_ but now it has some static API that is used for something else. Should these be in an util or some other class instead ?

2021-04-12 08:31 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
> +            String buildDir) {
Refactoring: should there be some context/configuration object or some pojo that encapsulates the needed things instead of introducing more and more parameters ? The thing goes for other classes like `NodeUpdater`

2021-04-12 08:46 UTC, caalador commented
>  not tested in any way
There is the test that the plugins are added to the package.json and for the functionality we have all tests in flow-tests that test and depend on this functionality as webpack.generated.js depends on the existence of the plugins.

2021-04-12 09:03 UTC, pleku commented
> > not tested in any way

> There is the test that the plugins are added to the package.json and for the functionality we have all tests in flow-tests that test and depend on this functionality as webpack.generated.js depends on the existence of the plugins.

Is that the same as what I described as 1) and 2) in my comment, the "feature" ?  I don't understand how those tests validate that the feature of using _npm install and webpack manually_ is working and done. I understand that it just tests our webpack plugins are installed and where those are installed.

2021-04-12 09:44 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
> +            String buildDir) {
The whole `Task*` should be updated and refactored. I would perhaps add a ticket about it (and then do it perhaps even before this feature) as it will not be a minor extra on top.

2021-04-12 09:44 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPlugins.java
>       * Copy Flow webpack plugins into the given nodeModulesFolder.
Moved and Docs added.

2021-04-12 09:44 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPlugins.java
> +    protected static final String PLUGIN_TARGET = "plugins";
Moved and Docs added.

2021-04-12 09:45 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPlugins.java
> +    protected static List<String> getPlugins() {
Created new utility class.

2021-04-12 09:52 UTC, caalador commented
Before this change the plugins were installed after npm install task was executed so that npm doesn't clear the plugins (especially if the node_modules should be empty) and now the plugins need to be copied before the npm install is executed.

Our npm install and a manual npm install doesn't differ in actual execution. 

Also our running of webpack doesn't differ from the manual running of webpack except for speed and log output.

I don't see how this could be tested "outside" the framework except by running a shellscript on an existing project if the fact that the task execution order is not seen as a functionality change.

2021-04-13 08:18 UTC, pleku approved these changes

2021-04-13 08:18 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/WebpackPluginsUtil.java
> +    protected static JsonObject getJsonFile(String jsonFilePath)
First thought this could be moved to `JsonUtils`, but then it would be weird if that one has a dependency to `FrontendUtils` which should in theory be outside of `flow-server` anyway ... so maybe this is fine

2021-04-13 08:19 UTC, pleku commented
> I don't see how this could be tested "outside" the framework except by running a shellscript on an existing project if the fact that the task execution order is not seen as a functionality change.

@caalador I'd just mark this as either a fix or refactor - I don't see how from users perspective we're adding a new feature that should be highlighted in the release notes. We can change the linked issue to be a bug fix instead

2021-04-14 07:01 UTC, merged

2021-04-14 07:11 UTC, pleku commented
Just to clarify - we're not going to backport this to v19. Right @caalador ?

2021-04-14 07:41 UTC, caalador commented
No. I don't think this should be backported to 19.