Separate endpoint registry out from connect controller
vaadin/flow pull request #10610
Opened 2021-04-09 17:49 UTC by Artur-

Prerequisite for #10608

2021-04-13 06:47 UTC, haijian-vaadin requested changes
Got the following error when using this PR
```
APPLICATION FAILED TO START
***************************

Description:

Parameter 3 of constructor in com.vaadin.flow.server.connect.VaadinConnectController required a bean of type 'com.vaadin.flow.server.connect.EndpointRegistry' that could not be found.
```
Should probably register EndpointRegistry as a Bean in `VaadinConnectControllerConfiguration`, same as `EndpointUtil`

2021-04-13 10:05 UTC, Artur- commented
Added bean to VCCC

2021-04-13 12:43 UTC, haijian-vaadin commented
Why changing the injecting of EndpointNameChecker into the field instead of the constructor? I feel the tests were cleaner before.

2021-04-13 12:50 UTC, Artur- commented
Where do I get it from in `VaadinConnectControllerConfiguration`?

2021-04-13 13:23 UTC, haijian-vaadin commented
```
@Bean
public EndpointRegistry endpointRegistry(EndpointNameChecker endpointNameChecker) {
    return new EndpointRegistry(endpointNameChecker);
}
```
this would work?

2021-04-14 06:28 UTC, Artur- commented
Fixed... This morning I took my coffee before coding. Seems like a better idea.

2021-04-14 06:31 UTC, haijian-vaadin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java
> +    public EndpointRegistry endpointRegistry(EndpointNameChecker nameChecker) {
Sorry, one final small thing, I think it would fail the JavaDoc check, should also doc the parameter.

2021-04-14 06:54 UTC, Artur- commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java
> +    public EndpointRegistry endpointRegistry(EndpointNameChecker nameChecker) {
Fixed

2021-04-14 06:58 UTC, haijian-vaadin approved these changes

2021-04-14 08:00 UTC, merged