Add EndpointUtil.isAnonymousEndpoint
vaadin/flow pull request #10611
Opened 2021-04-09 17:53 UTC by Artur-

Fixes #10608

Based on #10610

2021-04-14 08:03 UTC, haijian-vaadin commented
#10610 has been merged, this one could be rebased?

2021-04-14 08:09 UTC, Artur- commented
Done. Is it a problem to change the `spring-web` dependency version?

2021-04-14 08:19 UTC, haijian-vaadin commented
> Done. Is it a problem to change the `spring-web` dependency version?

updating the version should be fine. But why not change the `spring.version` property to 5.3.0? so that other spring dependencies would be updated as well?

2021-04-14 08:22 UTC, Artur- commented
I can do that but won't this mean dropping support for Spring Boot < 2.4? https://spring.io/blog/2020/11/12/spring-boot-2-4-0-available-now mentions that Spring Boot 2.4 upgrades to Spring 5.3

2021-04-14 08:28 UTC, Artur- commented
Fixed. Upgrading the Spring dependency should not be a problem as we are not backporting this change anyway

2021-04-14 08:57 UTC, haijian-vaadin requested changes

2021-04-14 08:57 UTC, haijian-vaadin commented on fusion-endpoint/pom.xml
> +            <version>${spring.vesion}</version>
vesion->version

2021-04-14 08:57 UTC, haijian-vaadin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/EndpointUtil.java
> +
could update the magic variables? e.g.
p->parse
e->mathInfo

2021-04-14 08:57 UTC, haijian-vaadin commented on fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/EndpointUtilTest.java
> +    }
These two methods could be merged into 1?
Also had to think a while about what `testAnon` means. could maybe change the name to 
`verifyEndpointMethodsAreAnonymousAllowed()`

2021-04-14 08:57 UTC, haijian-vaadin commented on fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/EndpointUtilTest.java
> +    private void testAnon(String path, boolean expected) {
had to think even for this `testAnon`, could maybe change that name to
veryEndpointPathIsAnonymous().

2021-04-14 08:57 UTC, haijian-vaadin commented on fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/EndpointUtilTest.java
> +        testAnon("RolesAllowedAdminEndpoint", "anonymousallowed");
Seems it only tests the anonymous endpoints are anonymous, not testing the non-anonymous endpoints are non-anonymous

2021-04-14 10:14 UTC, Artur- commented on fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/EndpointUtilTest.java
> +        testAnon("RolesAllowedAdminEndpoint", "anonymousallowed");
It checks through all endpoints and gets the `expected` value from the strings here

2021-04-14 10:14 UTC, Artur- commented on fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/EndpointUtilTest.java
> +    private void testAnon(String path, boolean expected) {
Done

2021-04-14 10:14 UTC, Artur- commented on fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/EndpointUtilTest.java
> +    }
Done

2021-04-14 10:14 UTC, Artur- commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/EndpointUtil.java
> +
Done

2021-04-14 10:14 UTC, Artur- commented on fusion-endpoint/pom.xml
> +            <version>${spring.vesion}</version>
Done

2021-04-14 12:29 UTC, haijian-vaadin commented on fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/EndpointUtilTest.java
> +        testAnon("RolesAllowedAdminEndpoint", "anonymousallowed");
ah, ok, I misread the code.

2021-04-14 12:30 UTC, haijian-vaadin approved these changes

2021-04-15 06:45 UTC, joheriks approved these changes

2021-04-15 06:46 UTC, merged