test: Add test for custom theme name switch
vaadin/flow pull request #10629
Opened 2021-04-13 09:16 UTC by mshabarov

Changes the custom theme name in `@Theme` definition and check that the live reload happens and styles are applied.

Related-to #10451

2021-04-14 06:58 UTC, pleku requested changes

2021-04-14 06:58 UTC, pleku commented on flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
> +        waitUntilOtherTheme();
Should there be a check here that reports that what failed in case the theme swap doesn't work ?
Now it only waits until timeout and fails then without any clear message ?

2021-04-14 07:19 UTC, mshabarov commented on flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
> +        waitUntilOtherTheme();
The problem is that the TB 'waitUntil' API does not have a message supplier.
Basically `waitUntilOtherTheme()` waits without any meaningful message, like other waits calls in this test. 
And when it fails, you can distinguish the failure reason by inspecting method name in the stacktrace.
This is not convenient, I agree.
Two options for that are:
1. Change TB API to allow passing message/message supplier to `waitUntil` overrides.
2. Wrap it like this:
```java
    private void waitUntilWithMessage(ExpectedCondition<?> condition,
            String message, long time) {
        try {
            waitUntil(condition, time);
        } catch (TimeoutException te) {
            Assert.fail(message);
        }
    }
```
And put this method in `ChromeBrowserTest`

2021-04-14 08:10 UTC, mshabarov commented
This test is unstable: 2 of 7 runs are failing because `com.vaadin.flow.uitest.ui.ThemeLiveReloadIT.waitUntilCustomFont`.
For some reason, this test is triggered for the second time, although the theme switching was fine according to logs.

I give up and extract the switch theme test into another maven submodule.

Another warning is that this exception is thrown after Jetty restart and refreshing browser page:

```
[Atmosphere-Shared-0] ERROR com.vaadin.flow.server.communication.PushAtmosphereHandler - Exception in push connection
org.eclipse.jetty.io.EofException
        at org.eclipse.jetty.server.HttpConnection$SendCallback.reset(HttpConnection.java:728)
        at org.eclipse.jetty.server.HttpConnection$SendCallback.access$300(HttpConnection.java:688)
        at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:547)
        at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:824)
        at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:901)
        at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:283)
        at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:267)
        at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:705)
        at org.eclipse.jetty.server.Response.flushBuffer(Response.java:1057)
        at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:215)
        at org.atmosphere.cpr.AtmosphereResponseImpl.flushBuffer(AtmosphereResponseImpl.java:506)
        at org.atmosphere.cpr.AtmosphereInterceptorWriter.flush(AtmosphereInterceptorWriter.java:102)
        at org.atmosphere.cpr.AtmosphereResponseImpl$Stream.flush(AtmosphereResponseImpl.java:1001)
        at org.atmosphere.handler.AbstractReflectorAtmosphereHandler.onStateChange(AbstractReflectorAtmosphereHandler.java:156)
        at com.vaadin.flow.server.communication.PushAtmosphereHandler.onStateChange(PushAtmosphereHandler.java:52)
        at org.atmosphere.cpr.DefaultBroadcaster.invokeOnStateChange(DefaultBroadcaster.java:1037)
        at org.atmosphere.cpr.DefaultBroadcaster.prepareInvokeOnStateChange(DefaultBroadcaster.java:1057)
        at org.atmosphere.cpr.DefaultBroadcaster.executeAsyncWrite(DefaultBroadcaster.java:871)
        at org.atmosphere.cpr.DefaultBroadcaster$2.run(DefaultBroadcaster.java:474)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

But I don't see how it's related and probably it's a known issue.

2021-04-14 19:03 UTC, mshabarov commented
Updated startup performance IT threshold also here, in this PR, because it's imposible to even check this PR. It always fails due threshold exceed.

2021-04-15 05:55 UTC, mshabarov commented on flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
> +        waitUntilOtherTheme();
I did option 2. for waitUntil methods.

2021-04-15 08:15 UTC, mshabarov commented
4 build have passed after my last changes, so the test looks stable.

2021-04-15 10:05 UTC, pleku requested changes

2021-04-15 10:05 UTC, pleku commented on flow-tests/test-application-theme/test-theme-switch-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeSwitchLiveReloadIT.java
> +        waitUntilAppTheme();
Again it looks weird that there is changes done in the after phase and then waiting until things happen - please comment on why this is done

2021-04-15 10:05 UTC, pleku commented on flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
> +                        : 13500;
Huh ? This seems a bit odd for this PR which doesn't introduce any related code changes.

Is it failing for other PRs too ? Has there been a regression to this recently ?

2021-04-15 10:43 UTC, mshabarov commented on flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
> +                        : 13500;
Good question!
`StartupPerformanceIT` was failing 3-4 times in a row for _this_ PR and there were some single failures in snapshot validation:
https://bender.vaadin.com/project.html?tab=testDetails&projectId=Flow_Flow70&testNameId=4287072265800670240&page=1

so to even see that my tests are even passing in CI I've added it here, ofc it should not be included when merged.

BUT: I've just checked other PRs validation and `StartupPerformanceTest` fails only for _this_ branch, i.e. changes in this PR.

Thus, I will revert 13500 back to prev value and see what could cause this.

2021-04-15 10:51 UTC, mshabarov commented on flow-tests/test-application-theme/test-theme-switch-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeSwitchLiveReloadIT.java
> +        waitUntilAppTheme();
comment added

2021-04-15 10:51 UTC, mshabarov commented on flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
> +                        : 13500;
reverted

2021-04-15 12:42 UTC, mshabarov commented
From the PR build history, is can be infered that startup perf test has been failing since adding a new maven module, but I can't explain that.
As a random assumption, one of these could be impacted by changing in maven structure, but...looks weird.

```
    Tensor<Integer> tensor;
    TensorSliceDataset dataSet;
    WriteAudioSummary writeAudioSummary;
    SegmentSum<Integer> segmentSum;
    DecodeJpeg decodeJpeg;
    Multimap<String, String> mmap;
    Injector injector;
    MetricRegistry registry;
    MetricSet metricSet;
    ConsoleReporter reporter;
    Gauge gauge;
    Actor actor;
    ActorSelection actorSelection;
```

2021-04-21 07:59 UTC, mshabarov commented
Alright, it seems to work.
All those three theme live reload tests now run in a separate step `Run theme live-reload tests` right after main `Run validation` step.

2021-04-22 16:57 UTC, mshabarov commented
I use an existing 'run-tests' profile to reorder the tests, because the solution with categories is over-over-complicated.
Should wait until https://github.com/vaadin/flow/pull/10777 is merged.

2021-04-23 08:02 UTC, pleku approved these changes

2021-04-23 09:07 UTC, merged