fix: Only override older package versions
vaadin/flow pull request #10630
Opened 2021-04-13 10:58 UTC by caalador

If package dependency version in
package json is newer than in versions.json
then we leave the newer version unchanged.

Fixes #9793

2021-04-13 12:18 UTC, pleku requested changes

2021-04-13 12:18 UTC, pleku commented on flow-server/src/main/resources/pnpmfile.js
> +        if (dependencies[key].startsWith('./') || compareVersions(dependencies[key], versions[key]) === -1) {
Would it be impossible to just use something like https://docs.npmjs.com/cli/v7/using-npm/semver in here so that we don't have to have our own parsing ?

2021-04-13 12:18 UTC, pleku commented on flow-server/src/main/resources/pnpmfile.js
> +  const sp2 = v2Array[v2Array.length - 1];
sp?

2021-04-13 14:15 UTC, caalador commented on flow-server/src/main/resources/pnpmfile.js
> +    throw new Error('Invalid argument not valid semver (\'' + version + '\' received)');
It would show up in the logs as `ERROR? Invalid argument not valid semver ('./target/flow-frontend' received)at validate                 pnpmfile.js:81` failing pnpm install

2021-04-13 14:35 UTC, caalador commented
I'll rework the version comparison if this doesn't cause new problems.

2021-04-14 04:19 UTC, caalador commented
Closing this as it brings more problems and enables getting mixed versions.

2021-04-14 04:19 UTC, closed without merging