fix: report the parameter name in the exception message
vaadin/flow pull request #10716
Opened 2021-04-19 10:49 UTC by denis-anisimov

fixes #9994

2021-04-19 11:25 UTC, caalador requested changes

2021-04-19 11:25 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/router/RouteParametersTest.java
> +                        CoreMatchers.containsString("'foo'")));
I would rather expect the full message in all tests as it's not that long.

2021-04-19 11:25 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/router/RouteParameters.java
> +                    "Couldn't parse '%s' paramter value '%s' as long",
```suggestion
                    "Couldn't parse '%s' parameter value '%s' as long",
```

2021-04-19 11:25 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/router/RouteParameters.java
> +                    "Couldn't parse '%s' paramter value '%s' as integer",
```suggestion
                    "Couldn't parse '%s' parameter value '%s' as integer",
```

2021-04-19 14:26 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/router/RouteParametersTest.java
> +                        CoreMatchers.containsString("'foo'")));
done

2021-04-20 04:04 UTC, caalador approved these changes

2021-04-20 04:05 UTC, merged