chore: use squash for cherry picks from bot
vaadin/flow pull request #10721
Opened 2021-04-19 19:19 UTC by mshabarov

2021-04-19 20:18 UTC, ZheSun88 requested changes

2021-04-19 20:18 UTC, ZheSun88 commented on scripts/autoMerge.js
>      await postComment(url, "This PR has been merged with 'rebase' method.[Message is sent from bot]");
Here also mentioned the “rebase” method.  And you can add [skip-ci] to the next commit message to skip the IT tests. 😃

2021-04-20 05:18 UTC, ZheSun88 commented on scripts/autoMerge.js
>      await postComment(url, "This PR has been merged with 'rebase' method.[Message is sent from bot]");
i updated the comment.

2021-04-20 05:18 UTC, ZheSun88 approved these changes

2021-04-20 05:35 UTC, mshabarov commented on scripts/autoMerge.js
>      await postComment(url, "This PR has been merged with 'rebase' method.[Message is sent from bot]");
Thanks, @ZheSun88 ! D missed this extra 'rebase'.

2021-04-20 05:58 UTC, merged