fix: backwards-compatible offline in V14 legacy mode
vaadin/flow pull request #10737
Opened 2021-04-20 08:38 UTC by joheriks

Part of #9412

2021-04-21 12:30 UTC, haijian-vaadin requested changes
Should there be a test that `TaskGenerateTsConfig` and `TaskGenerateTsDefinitions` are executed in v14 bootstrap mode?

2021-04-21 14:57 UTC, joheriks commented
> Should there be a test that `TaskGenerateTsConfig` and `TaskGenerateTsDefinitions` are executed in v14 bootstrap mode?

Done.

2021-04-21 19:20 UTC, haijian-vaadin requested changes
after the constructor changes, many of the tests could be updated, so they would look unchanged.

2021-04-21 19:20 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
>      }
same here

2021-04-21 19:20 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
> +            SerializableBiFunction<Class<?>, Class<? extends Annotation>, List<? extends Annotation>> annotationFinder,
And here

2021-04-21 21:13 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
>      }
Not sure it really makes sense here to create too many constructors here? This class is package-private it shouldn't be a breaking change. Restored the previous constructor of `FrontendDependencies` though, since that class is public.

2021-04-21 21:13 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/PwaConfiguration.java
>          this(true, pwa.name(), pwa.shortName(), pwa.description(),
Done.

2021-04-21 21:13 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/PwaConfiguration.java
> +    public PwaConfiguration(boolean useV14Bootstrap) {
Good idea, done.

2021-04-21 21:13 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
> +            SerializableBiFunction<Class<?>, Class<? extends Annotation>, List<? extends Annotation>> annotationFinder,
See above comment.

2021-04-22 11:54 UTC, haijian-vaadin requested changes

2021-04-22 11:54 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/PwaConfiguration.java
> +            String display, String startPath, String[] offlineResources,
Could also restore the original constructor here? otherwise, this is also a breaking change.

2021-04-22 11:54 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesScanner.java
>          public FrontendDependenciesScanner createScanner(
Also could restore this createScanner() method, as it would be a breaking change.

2021-04-22 11:54 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
> +                        classFinder, true, false),
Could remove the parameter here after the original createScanner() method is restored.

2021-04-22 11:54 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
> +                        .createScanner(true, finder, true, false),
Could remove the parameter here after the original createScanner() method is restored.

2021-04-22 11:54 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
> +                        .createScanner(true, finder, true, false),
Could remove the parameter here after the original createScanner() method is restored.

2021-04-22 11:54 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
> +                        classFinder, true, false),
Could remove the parameter here after the original createScanner() method is restored.

2021-04-22 11:54 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
> +                        classFinder, true, false),
Could remove the parameter here after the original createScanner() method is restored.

2021-04-22 11:54 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
> +                        classFinder, true, false),
Could remove the parameter here after the original createScanner() method is restored.

2021-04-22 11:54 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsWithByteCodeScannerTest.java
> +                .createScanner(false, finder, true, false);
Could remove the parameter here after the original createScanner() method is restored.

2021-04-22 11:54 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsWithFullCPScannerTest.java
> +                .createScanner(true, finder, true, false);
Could remove the parameter here after the original createScanner() method is restored.

2021-04-22 11:54 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesWithByteCodeScannerTest.java
> +                .createScanner(false, finder, true, false);
Could remove the parameter here after the original createScanner() method is restored.

2021-04-22 11:54 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesWithFullCPCodeScannerTest.java
> +                .createScanner(true, finder, true, false);
Could remove the parameter here after the original createScanner() method is restored.

2021-04-22 11:54 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
> +                        Collections.singleton(this.getClass())), false, false);
Could remove the parameter here after the original createScanner() method is restored.

2021-04-22 11:54 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
> +                AppShell.class.getAnnotation(PWA.class), false);
Could remove the parameter here after the original PwaConfiguration constructor is restored.

2021-04-22 11:54 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
> +                AppShellWithOfflinePath.class.getAnnotation(PWA.class), false);
Could remove the parameter here after the original PwaConfiguration constructor is restored.

2021-04-22 11:54 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateImportsWithByteCodeScannerTest.java
> +                .createScanner(false, finder, true, false);
Could remove the parameter here after the original createScanner() method is restored.

2021-04-22 11:54 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateImportsWithFullCPScannerTest.java
> +                .createScanner(true, finder, true, false);
Could remove the parameter here after the original PwaConfiguration constructor is restored.

2021-04-22 11:54 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
> +                }, false);
Could remove the parameter here after the original method is restored.

2021-04-22 12:12 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/PwaConfiguration.java
> +            String display, String startPath, String[] offlineResources,
Missed, now restored.

2021-04-22 12:12 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesScanner.java
>          public FrontendDependenciesScanner createScanner(
Done.

2021-04-22 12:12 UTC, joheriks commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
> +                        classFinder, true, false),
Done.

2021-04-22 13:15 UTC, haijian-vaadin approved these changes

2021-04-22 13:15 UTC, merged