Generate nullable TS types for Java types by default
vaadin/flow pull request #10754
Opened 2021-04-21 10:19 UTC by Lodin

Resolves #8849.

2021-04-21 10:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=10754) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=10754) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=10754) it.</sub>

2021-04-22 12:50 UTC, haijian-vaadin requested changes

2021-04-22 12:50 UTC, haijian-vaadin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeCheckerHelper.java
> +                    && !field.isAnnotationPresent(JsonIgnore.class);
Missing a `isRequired()` Check on the field? so that property would subject for checking if it's marked as NotNull/Nonnull explicitly.

2021-04-22 12:50 UTC, haijian-vaadin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/ConnectUtils.java
> +public final class ConnectUtils {
Connect is the legacy name for Fusion, let's avoid using that. Sth like EndpointGeneratorutils.
Or maybe we can move this into the existing GeneratorUtils and mark that as public.

2021-04-23 10:19 UTC, Lodin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeCheckerHelper.java
> +                    && !field.isAnnotationPresent(JsonIgnore.class);
Should I check it this way then (pseudo names used)?
```java
return (!Modifier.isStatic(field.getModifiers())
                    && !isNullable(field);
                    && !field.isAnnotationPresent(JsonIgnore.class)) 
                    || isRequired(field);
```

2021-04-23 16:43 UTC, platosha commented on fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/ExplicitNullableTypeCheckerTest.java
> +    public String stringNotNull() {
Identical to the one below. Maybe remove?

2021-04-27 10:55 UTC, haijian-vaadin requested changes

2021-04-27 10:55 UTC, haijian-vaadin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/Annotation.java
> +public final class Annotation {
Annotation is too general here, maybe `NonNullChecker` or sth similar would be better?

2021-04-27 10:55 UTC, haijian-vaadin commented on fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/AbstractEndpointGenerationTest.java
> +            if (parameters[index].isAnnotationPresent(NotNull.class)
shouldn't we only check `@Nonnull` as agreed?

2021-04-27 10:55 UTC, haijian-vaadin commented on fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/AbstractEndpointGenerationTest.java
> +            if (expectedSchemaField.isAnnotationPresent(NotNull.class)
shouldn't we only check `@Nonnull` as agreed?

2021-04-28 06:58 UTC, haijian-vaadin requested changes

2021-04-28 06:58 UTC, haijian-vaadin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeCheckerHelper.java
> +                    || isElementRequired(field);
should be && instead of ||?

2021-04-28 20:28 UTC, haijian-vaadin requested changes

2021-04-28 20:28 UTC, haijian-vaadin commented on fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/IndentationUtils.java
> +        public boolean isEmpty() {
also here, no need to have it as public.

2021-04-28 20:28 UTC, haijian-vaadin commented on fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/collectionendpoint/expected-CollectionEndpoint.ts
> + * Get a collection by author name. The generator should not mix this type  with the Java's Collection type.
looks like we shouldn't add the extra space, the test is failing on CI because of this, the test goes green after removing the extra space.

2021-04-28 20:28 UTC, haijian-vaadin commented on fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/modelpackage/expected-ModelPackageEndpoint.ts
> + * Get a collection by author name. The generator should not mix this type  with the Java's Collection type.
looks like we shouldn't add the extra space, the test is failing on CI because of this, the test goes green after removing the extra space.

2021-04-28 20:28 UTC, haijian-vaadin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/NonnullAnnotationChecker.java
> +public final class NonnullAnnotationChecker {
Sorry, after another thought, I was thinking, maybe we can just move these two methods into `ExplicitNullableTypeChecker`? since the required checks are quite relevant to that class.

Also as I mentioned in the previous review, both methods could be named as `isRequired()`, no need to put the parameter type into the method name.

2021-04-29 10:05 UTC, haijian-vaadin requested changes

2021-04-29 10:05 UTC, haijian-vaadin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
> +    public static boolean isRequired(NodeWithAnnotations<?> node) {
Missing JavaDoc for this method. Each public method should have JavaDoc, otherwise, CI would fail.

2021-04-29 10:07 UTC, haijian-vaadin requested changes

2021-04-29 10:07 UTC, haijian-vaadin commented on fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/IndentationUtils.java
> +final class IndentationUtils {
hmm, looks like this class is only used for test? Let's move it from the src/main/java to src/main/test

2021-04-29 10:10 UTC, Lodin commented on fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/IndentationUtils.java
> +final class IndentationUtils {
Yes, that class is only for tests, and it is already in `src/test/java`.

2021-04-29 10:11 UTC, Lodin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
> +    public static boolean isRequired(NodeWithAnnotations<?> node) {
Hmm, how should I do that? Just copy-paste the JavaDoc from the sibling method?

2021-04-29 10:13 UTC, haijian-vaadin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
> +    public static boolean isRequired(NodeWithAnnotations<?> node) {
Yes

2021-04-29 10:13 UTC, haijian-vaadin commented on fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/IndentationUtils.java
> +final class IndentationUtils {
ah, sorry, my bad.

2021-04-30 08:09 UTC, haijian-vaadin submitted a review, later dismissed

2021-05-03 19:03 UTC, knoobie commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
> +        return element.isAnnotationPresent(Nonnull.class);
What do you think about changing this from `javax.annotation.Nonnull` to a string check against "Nonnull" /  "NonNull" and "Notnull" / "NotNull" ? This would remove the direct Dependency on javax (having Jakarta namespace in mind) and additionally allowing the usage of other annotations like e.g.:

- custom annotation 
- Jetbrains annotation 
- Spring annotation 
- Findbugs annotation 
- Lombok annotation 
- Micrometer annotation 

and so on.

2021-05-04 06:40 UTC, haijian-vaadin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
> +        return element.isAnnotationPresent(Nonnull.class);
Yes, that's a very good idea, we should do that. ping @Lodin

2021-05-04 06:43 UTC, haijian-vaadin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
> +        return element.isAnnotationPresent(Nonnull.class);
Just a small clarification, I think we would go with ignore case string comparison with `Nonnull`, but not using `NotNull`. `NotNull` is for validation, which means that there would be validation errors if the value is null, but the value itself could be null, otherwise, the validation would never fail.

2021-05-04 06:45 UTC, haijian-vaadin requested changes
Let's update the `isRequired()` check to use string comparison.

2021-05-04 06:48 UTC, knoobie commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
> +        return element.isAnnotationPresent(Nonnull.class);
I was not sure if `isAnnotationPresent` can handle ignore case comparison, that's why I mentioned both spellings I have seen in the wild

2021-05-04 06:55 UTC, haijian-vaadin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
> +        return element.isAnnotationPresent(Nonnull.class);
I was thinking sth simple as
```
Stream.of(element.getAnnotations()).anyMatch(anno -> "Nonnull"
                .equalsIgnoreCase(anno.annotationType().getSimpleName()))
```

2021-05-04 07:10 UTC, knoobie commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
> +        return element.isAnnotationPresent(Nonnull.class);
I wanted to argue against using `Stream`, but I just saw what `NodeWithAnnotations::isAnnotationPresent` did under the hood - so nvm :) Sounds like a good way!

2021-05-05 10:17 UTC, joheriks commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
> +                            .equals("org.jetbrains.annotations.NotNull");
Does this (erroneously) match some annotation that for contains "nonnull" as a substring? Would perhaps be simpler to have a single regexp that covers everything.

2021-05-05 10:40 UTC, Lodin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
> +                            .equals("org.jetbrains.annotations.NotNull");
Used `equalsIgnoreCase` instead of regex. It is simpler and less bug-prone.

2021-05-05 10:48 UTC, joheriks commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
> +                            .equals("org.jetbrains.annotations.NotNull");
The magic constant `"nonnull"` is repated, would still put it in a `final static String`.

2021-05-07 11:05 UTC, haijian-vaadin approved these changes

2021-05-07 11:43 UTC, merged