test: unignore tests in PopStateHandlerIT
vaadin/flow pull request #10750
Opened 2021-04-21 06:57 UTC by platosha

Fixes #10485

2021-04-26 07:56 UTC, haijian-vaadin requested changes

2021-04-26 07:56 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/component/page/History.java
> +        final String pathWithQueryParameters = Optional.ofNullable(location)
could extract this into a separate method? since it's also used in the `replaceState()`?

2021-04-26 07:56 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/component/page/History.java
> +        final String pathWithQueryParameters = Optional.ofNullable(location)
maybe would be a bit better to use simple if-else with some comments to explain why it's now needed to get the lastHandledLocation from UI (not before), which would help to understand the code better than the Optional.orElse()

2021-04-26 07:56 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
> +            // FIXME(platosha): pass the history state from the client side
Does this work without client-side change already? If not, let's remove the code and make a separate ticket about it.

2021-04-27 14:47 UTC, platosha commented on flow-server/src/main/java/com/vaadin/flow/component/page/History.java
> +        final String pathWithQueryParameters = Optional.ofNullable(location)
I’m trying to keep the code style consistent, there are other lines like that in the same file:
```java
        pushState(state,
                Optional.ofNullable(location).map(Location::new).orElse(null));
```

Actually it is not necessary to get last location from UI, removed that.

What I’m after here is to support `null` location argument in this method. as the jsdoc explicitly allowed.

2021-04-27 14:48 UTC, platosha commented on flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
> +            // FIXME(platosha): pass the history state from the client side
It does work, but does not pass the state. That was just a self reminder to get back to that — now fixed that.

2021-04-27 19:11 UTC, haijian-vaadin requested changes

2021-04-27 19:11 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
> +            getPage().getHistory().setHistoryStateChangeHandler(
Not sure about this. What if the user has defined a `HistoryStateChangeHandler` in the app, this would override the one defined by the user?

2021-04-27 19:11 UTC, haijian-vaadin commented on flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PopStateHandlerIT.java
> +    @Ignore("Ignored because if the issue https://github.com/vaadin/flow/issues/10825")
```suggestion
    @Ignore("Ignored because of the issue https://github.com/vaadin/flow/issues/10825")
```

2021-04-28 08:40 UTC, haijian-vaadin requested changes
Looks like the failing test is about a trailing slash, if I change the `assertLastMessage("/routerlink",`  to `assertLastMessage("/routerlink/",`
in line 48 of `NavigationTriggerIT`, should we do that and then merge the PR?

2021-05-05 06:45 UTC, haijian-vaadin approved these changes

2021-05-05 06:45 UTC, merged