Move access checker and @AnonymousAllowed to flow-server
vaadin/flow pull request #10758
Opened 2021-04-21 12:42 UTC by Artur-

This allows them to be used for view access control also

2021-04-21 13:11 UTC, knoobie commented on flow-server/pom.xml
> +            <version>${javax.annotation.api.version}</version>
Should this be changed to 

```xml
<dependency>
    <groupId>jakarta.annotation</groupId>
    <artifactId>jakarta.annotation-api</artifactId>
    <version>1.3.5</version>
</dependency>
```

to align with Spring Boot and others that have adopted the current release of the latest non-jakarta-namespace jars?

2021-04-21 13:12 UTC, Artur- commented on flow-server/pom.xml
> +            <version>${javax.annotation.api.version}</version>
Sounds like that should be part of #10366

2021-04-21 13:21 UTC, knoobie commented on flow-server/pom.xml
> +            <version>${javax.annotation.api.version}</version>
That's something different - the `1.3.5` of `jakarta` still has the old `javax` namespace. The ticket is about the new API with `jakarta`.

2021-04-28 07:40 UTC, haijian-vaadin requested changes
For @AnonymousAllowed annotation, instead of just moving, would it worth having a duplicate and mark the one in connect package as deprecated for the sake of easier migration?

2021-04-28 07:42 UTC, Artur- commented
Any idea on how that would work since the checker is in `flow-server` and don't want to depend on `fusion-endpoint` where the old annotation is?

2021-04-28 07:43 UTC, Artur- commented
My assumption was that `@AnonymousAllowed` is not the mostly used annotation and therefore updating imports would be fine

2021-04-28 08:05 UTC, haijian-vaadin requested changes

2021-04-28 08:05 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/auth/AccessControlTestClasses.java
> +    public static class NoAnnotationEndpoint {
Rename these XXXXEndpoint to XXXXClass? Since they are not endpoints, just generic classes?

2021-04-28 08:08 UTC, pleku reviewed
I'm not sure exactly if this change is even necessary at this point as it might be that this code will not end up to `flow-server` anyway.

2021-04-28 08:08 UTC, pleku commented on flow-server/pom.xml
> +            <version>${javax.annotation.api.version}</version>
Could/should this be `optional` scope instead

2021-04-28 08:08 UTC, pleku commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
> +import com.vaadin.flow.server.auth.AnonymousAllowed;
So now`fusion-endpoint` will be even more tied to `flow-server`. Is this ideal at this point that these things are in `flow-server` at this point ? @haijian-vaadin @joheriks

2021-04-28 08:08 UTC, haijian-vaadin commented
> Any idea on how that would work since the checker is in `flow-server` and don't want to depend on `fusion-endpoint` where the old annotation is?

Right, then I update the title and description of the PR, so the breaking change would be mentioned in the release note.

2021-04-28 08:10 UTC, pleku commented
>>Any idea on how that would work since the checker is in flow-server and don't want to depend on fusion-endpoint where the old annotation is?

>Right, then I update the title and description of the PR, so the breaking change would be mentioned in the release note.

Or should it be in some `vaadin-base` or `frameworks-base` or whatever instead ? I mean if the desire is to NOT have `fusion-endpoint` depend on `flow-server` in the end

2021-04-28 08:11 UTC, Artur- commented
If classes are one day moved from `flow-server` elsewhere, then that is a problem for a lot of classes. How is it related to this change?

2021-04-28 08:13 UTC, Artur- commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
> +import com.vaadin.flow.server.auth.AnonymousAllowed;
Not really "more" but it sure is tied after this, just like it is today.

2021-04-28 08:13 UTC, haijian-vaadin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
> +import com.vaadin.flow.server.auth.AnonymousAllowed;
Should be OK to leave them in flow-server for now.
If we split in the way that Flow specific parts are moved away from the current flow-server, then the remaining would become the common/base part, which would include this.

2021-04-28 08:13 UTC, Artur- commented on flow-server/pom.xml
> +            <version>${javax.annotation.api.version}</version>
Why?

2021-04-28 08:13 UTC, Artur- commented on flow-server/src/test/java/com/vaadin/flow/server/auth/AccessControlTestClasses.java
> +    public static class NoAnnotationEndpoint {
Done

2021-04-28 08:15 UTC, haijian-vaadin approved these changes

2021-04-28 08:16 UTC, pleku commented
> If classes are one day moved from flow-server elsewhere, then that is a problem for a lot of classes. How is it related to this change?

It is related since this topic is relevant at the moment. It is not mandatory, but I'm just raising the question

2021-04-28 08:17 UTC, joheriks commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
> +import com.vaadin.flow.server.auth.AnonymousAllowed;
This just means that `AccessAnnotationChecker` and `AnonymousAllowed` belong in the future common `flow` and `fusion` module (and hence, at the moment, in `flow-server`).

2021-04-28 10:08 UTC, pleku commented on flow-server/pom.xml
> +            <version>${javax.annotation.api.version}</version>
To avoid potential conflicts and issues down the road due to introducing a dependency that existing projects might be using already, but actually optional doesn't even help there.

2021-04-28 10:40 UTC, merged