Add helpers for using current request and simplify naming
vaadin/flow pull request #10767
Opened 2021-04-22 06:56 UTC by Artur-

2021-04-28 08:15 UTC, denis-anisimov commented
The first two commits are entirely fusion related changes,
They should be reviewed by the fusion team.

I don't get why some classes have been moved to `flow-server` (what's the usecase for app without fusion in the `@AnonymousAllowed` annotation) but this is a part of another PR anyway.

2021-04-28 08:17 UTC, haijian-vaadin commented
> The first two commits are entirely fusion related changes,
> They should be reviewed by the fusion team.
> 
> I don't get why some classes have been moved to `flow-server` (what's the usecase for app without fusion in the `@AnonymousAllowed` annotation) but this is a part of another PR anyway.

It depends on https://github.com/vaadin/flow/pull/10758, might be better to review this PR after 10758 is merged and this PR is rebased.

2021-04-28 10:42 UTC, Artur- commented
Rebased

> I don't get why some classes have been moved to flow-server (what's the usecase for app without fusion in the @AnonymousAllowed annotation) but this is a part of another PR anyway.

The same annotations can be used for view access control

2021-04-29 06:04 UTC, denis-anisimov requested changes

2021-04-29 06:04 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessAnnotationChecker.java
> +        VaadinServletRequest request = VaadinServletRequest.getCurrent();
I would remove any API which assumes there is something implicit.
`VaadinServletRequest.getCurrent()` is a magic assumption: I recall it was your attempt to clean up the code
to avoid using `Current`  whenever it's possible.

There can be a helper method outside of this class which may be used by a developer (not by Flow internal code).
But the original code should avoid `Current`  implicits.

2021-04-29 06:04 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessAnnotationChecker.java
> +        VaadinServletRequest request = VaadinServletRequest.getCurrent();
Current implicit

2021-04-29 06:13 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessAnnotationChecker.java
> +        VaadinServletRequest request = VaadinServletRequest.getCurrent();
This is a helper to be used by the developer

2021-04-29 07:49 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessAnnotationChecker.java
> +        VaadinServletRequest request = VaadinServletRequest.getCurrent();
https://github.com/vaadin/spring/pull/780/files#diff-8ee7e28928834d56e852315edccd85c18bab05e3ca39fb7de7c037e38b31b2ceR114 is an example of how you would use it

2021-04-29 11:58 UTC, denis-anisimov submitted a review, later dismissed

2021-04-30 07:23 UTC, haijian-vaadin submitted a review, later dismissed

2021-04-30 07:31 UTC, joheriks approved these changes

2021-04-30 08:15 UTC, haijian-vaadin approved these changes

2021-04-30 08:55 UTC, merged