fix: don't publish flow-client TS sources in JAR
vaadin/flow pull request #10765
Opened 2021-04-22 06:43 UTC by Haprog

Improve performance of webpack build by only shipping precompiled JS of the flow-frontend TS sources, so webpack doesn't try to use the TS sources which is slightly slower than using JS (and `.d.ts`) directly. The TS sources shouldn't be needed in the JAR anyway and this has the benefit of making the JAR a bit smaller in size also. Related to #10281.

2021-04-22 06:46 UTC, Legioth commented
I guess one drawback of this is that it would give worse source maps for anyone trying to locally debug anything related to the code for which the original TS files are missing.

2021-04-22 11:10 UTC, Haprog commented
> I guess one drawback of this is that it would give worse source maps for anyone trying to locally debug anything related to the code for which the original TS files are missing.

I don't think that's an issue since we have:
```json
    "sourceMap": true,
    "inlineSources": true,
```
in `tsconfig.json` (for the flow-client build)

The `.js.map` files seem to contain the full TS sources too.

2021-04-23 06:47 UTC, haijian-vaadin requested changes

2021-04-23 06:47 UTC, haijian-vaadin commented on flow-client/src/main/frontend/Flow.ts
> +      const bootstrapMod = await import('../resources/META-INF/resources/frontend/FlowBootstrap');
Tried the snapshot build, got frontend compile errors 
ERROR in ../target/flow-frontend/Flow.js
Module not found: Error: Can't resolve '../resources/META-INF/resources/frontend/FlowBootstrap'

2021-04-23 08:43 UTC, Haprog commented
After moving also `FlowClient` and `FlowBootstrap` (`.js` and `.d.ts`) it seems to work now. I tested locally in a Flow app. Let's see if the CI also passes now.

2021-04-23 09:43 UTC, Haprog commented
I forgot to mvn clean before installing flow-client locally when testing so I didn't catch some problems. New try now. Tested locally working again.

2021-04-23 09:58 UTC, Haprog commented on flow-client/.eslintrc.js
> +    },
Add an entry for `.eslintrc.js` files so it doesn't complain about `module.exports = {` line in the eslint configs.

2021-04-23 09:59 UTC, Haprog commented on flow-client/scripts/.eslintrc.js
> +    "node": true,
New eslint config for the `scripts` dir with `node` env so it doesn't complain about usage of `require()` in node scripts.

2021-04-23 10:05 UTC, Haprog commented on flow-client/scripts/client.js
> +  .forEach(file => fs.copyFileSync(sourceDir + file, targetDir + file));
Use `mkdirp` to create this target dir as it's not automatically populated by Maven anymore due to moving the source files.

Now we also need to copy the FlowClient and FlowBootstrap files (`.js` and `.d.ts`) from source to target dir due to moving the source files. `tsc` (TS compiler) outputs the compiled results of TS files into target but doesn't copy the JS sources for these files that aren't written in TS. Here we just copy all `.d.ts` and `.js` from source to target to be more future proof.

Previously this script was only writing the generated `FlowClient.js` into both source and target. Now it's written into source first and then it gets copied to target also as part of this step.

2021-04-23 10:49 UTC, Haprog commented on flow-client/src/main/frontend/Flow.ts
> +      const bootstrapMod = await import('../resources/META-INF/resources/frontend/FlowBootstrap');
Problem fixed.

2021-04-23 10:54 UTC, haijian-vaadin commented
I just tried, now it indeed works. Good job!

2021-04-23 12:06 UTC, haijian-vaadin approved these changes

2021-04-23 12:06 UTC, merged