Update CSRF token with the one returned from the login call
vaadin/flow pull request #10787
Opened 2021-04-23 09:30 UTC by Artur-

This fixes a problem introduced in #10697

2021-04-23 09:39 UTC, joheriks approved these changes

2021-04-23 12:26 UTC, haijian-vaadin requested changes

2021-04-23 12:26 UTC, haijian-vaadin commented on flow-client/src/main/frontend/Authentication.ts
> +      const springCsrfToken = response.headers.get('Spring-CSRF-token') || undefined;
Would be better to have a comment to mention where the headers  (Spring-CSRF-header, Spring-CSRF-token) are set, otherwise looks quite magic here.

2021-04-23 12:45 UTC, Artur- commented on flow-client/src/main/frontend/Authentication.ts
> +      const springCsrfToken = response.headers.get('Spring-CSRF-token') || undefined;
Added comment

2021-04-26 07:40 UTC, haijian-vaadin approved these changes

2021-04-26 07:40 UTC, merged