feat: Backport 'Inject Lumo CSS also into shadow roots' to 2.6
vaadin/flow pull request #10836
Opened 2021-04-28 14:41 UTC by mshabarov

Adds support for
"lumoImports": ["color", "typography", "badge", ... ]
to theme.json to override the default ["color", "typography"]

If you do not have an application theme specified, Lumo imports are injected by generated-flow-imports.js like before.
If you have an application theme, Lumo imports are injected as part of applying the theme.

In both cases, Lumo imports are added to the beginning of <head> so they are considered before any other styles, such as @CssImport:ed stylesheets. This allows overriding Lumo CSS rules no matter how you add the CSS.

Related-to #9767

2021-04-29 08:52 UTC, mshabarov commented
Alright, I did a manual testing with `V14.6 pre` generated project having these changes https://github.com/vaadin/start/pull/1160 and local flow `2.6-SNAPSHOT` having these lumo imports backporting, and the badges styles are rendered properly and `myapp.generated.js` now includes all necessary lumo imports injections.

2021-04-29 12:55 UTC, taefi requested changes

2021-04-29 12:55 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
> +                                            .matcher(html).replaceAll(""), commentToken)));
Why to write those lines as commented in the first place, while an Application Theme is going to take care of them in another place? Isn't this making the code a little hard to understand? Are those lines supposed to be uncommented by the user later?

2021-04-29 12:55 UTC, taefi commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
> +// This is copied from flow-generated-import
Is this comment helping with understanding something? I suggest to either remove it or we add some clear descriptions about what it's doing.

2021-04-29 12:55 UTC, taefi commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
> +  globalCssCode.push(`injectGlobalCss(${variable}.toString(), target);\n    `);
Is `\n` working properly for the generated files on Windows machines? 
Is it an overkill if we consider the the `os` package to get the line break character? 
```JS
var os = require('os')
// ...
var eolChar = JSON.stringify(os.EOL);
```

2021-04-30 08:58 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
> +                                            .matcher(html).replaceAll(""), commentToken)));
I would also skip adding anything instead of adding thing as commented.

2021-04-30 08:58 UTC, caalador commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
> +  globalCssCode.push(`injectGlobalCss(${variable}.toString(), target);\n    `);
`\n` works fine for windows also and it will become a new line when the string is written to the file.

2021-04-30 10:04 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
> +                                            .matcher(html).replaceAll(""), commentToken)));
I skipped writing these lines in case of application theme.
As I understand it, theme generated file is not needed to be explored or changed by developers.
For us, there is a comment in the source code
```
// There is no application theme in use, write theme includes here.
// Otherwise they are written by the application theme
```
explaining the behaviour.

2021-04-30 10:05 UTC, mshabarov commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
> +// This is copied from flow-generated-import
Agree, I see no worth for developers to see this comment.
Removed.

2021-04-30 13:19 UTC, taefi approved these changes

2021-04-30 13:22 UTC, merged