feat: Make helper method public to allow Spring to use it
vaadin/flow pull request #10863
Opened 2021-04-30 14:27 UTC by Artur-

2021-05-06 17:03 UTC, taefi requested changes

2021-05-21 19:06 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +    public static Optional<String> getPathIfInsideServlet(
Fixed

2021-05-21 19:06 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
>          if (servletMappingPath.endsWith("/*")) {
Fixed

2021-05-24 09:53 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +            }
Minor: I would avoid unnecessary `else` and the resulting indented codes inside the `else` block when those cases in the above have explicit `return` statements. Just makes it more readable IMO.

2021-05-24 10:02 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +            }
Removed

2021-05-24 10:11 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
>          }
This would simplify it even further:
```suggestion
        if ("/*".equals(servletMappingPath) || "/".equals(servletMappingPath)) {
            // All paths are inside a /* servlet and a / servlet
            return Optional.of(requestedPath);
        } 
        
        if (servletMappingPath.endsWith("/*")) {
            String servletPrefix = servletMappingPath.substring(0,
                    servletMappingPath.length() - 1); // Only remove "*"
            if (requestedPath.startsWith(servletPrefix)) {
                return Optional
                        .of(requestedPath.substring(servletPrefix.length()));
            }
            return Optional.empty();
        } 
        
        // Servlet is mapped only to a static path such as "" or /foo/bar
        String servletMappingWithoutSlash;

        if (servletMappingPath.startsWith("/")) {
            // Requested path should not contain the initial slash
            servletMappingWithoutSlash = servletMappingPath.substring(1);
        } else {
            servletMappingWithoutSlash = servletMappingPath;
        }

        if (requestedPath.equals(servletMappingWithoutSlash)) {
            return Optional.of(requestedPath
                    .substring(servletMappingWithoutSlash.length()));
        }

        return Optional.empty();
```

2021-05-24 10:54 UTC, taefi approved these changes

2021-05-24 11:30 UTC, merged