fix: pin platform transitive dependencies with npm
vaadin/flow pull request #10864
Opened 2021-04-30 16:22 UTC by pleku

Uses the same vaadin_versions.json file based pinning as with pnpm.
In case the application has @NpmPackage annotation with a certain version,
then that is used over the platform pinned version. When that is older,
a warning is logged (like with pnpm).
In case a dependency has been pinned directly in package.json, then that
is used over the platform pinned version. When that is older, a warning
is logged (like with pnpm).

Fixes #10572

2021-05-03 13:31 UTC, Artur- commented
Trying to use this with `20.0-SNAPSHOT` results in
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @vaadin/vaadin-core@20.0-SNAPSHOT.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

2021-05-04 08:06 UTC, caalador requested changes

2021-05-04 08:16 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
> +    public static FrontendVersion tryParseVersion(JsonObject sourceJson,
> Also anything actually using this method should just check and get the string by itself and not delegate it to something that should basically be a value object.

I can move it somewhere else but not sure where. I just don't want to repeat "parsing a frontend dependency version from json" code in many places. In this case it is also needed that things don't fail. I'll try to figure out where it could go

2021-05-04 08:40 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
> +     *            better error message if the parsing failes
Refactoring, not applicable

2021-05-04 08:42 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
> +    public FrontendVersion(String name, String version, String location) {
Refactored so not directly applicable - but one problem is that the error messaging we have tends to be poor giving enough details to the users and splitting it out to many parts is just makes the problem appear over and over again.

2021-05-04 08:50 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
> +        } else {
Done (but elsewhere)

2021-05-04 08:53 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +        return versionsJson;
Done

2021-05-04 09:34 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +            // added to not get NPEs
It is in `TaskUpdatePackages`

```java
    private boolean updatePackageJsonDependencies(JsonObject packageJson,
            Map<String, String> applicationDependencies) throws IOException {
        int added = 0;

        JsonObject dependencies = packageJson.getObject(DEPENDENCIES);
```

If I remove this all my new unit tests that only execute TaskUpdatePackages fail ... somehow it feels weird that this code is here but then it does not add those parts. But I guess it is because it will be triggered always before `TaskUpdatePackages` is and something adds those parts there. If not, then `TaskUpdatePackages` would just fail with NPE (even without my changes)

2021-05-04 09:38 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +            // added to not get NPEs
I guess basically everything should execute the addDefaultDependencies or have a pre-generated json for tests (also some routes will not write the fileso it may be left empty), but I don't have anything against adding empty dependency objects here just that then we should probably add both dependency objects.

2021-05-04 09:52 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +            // added to not get NPEs
Done

2021-05-04 09:53 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +            if (platformPinnedDependencies != null) {
Done

2021-05-04 12:41 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +        return versionsJson;
Not done - it would be too messy for pnpm-versions locking if this returns and empty object that it is cleaner to leave it the way it is

2021-05-04 12:42 UTC, pleku commented
>Trying to use this with 20.0-SNAPSHOT results in
>npm ERR! code ETARGET
npm ERR! notarget No matching version found for @vaadin/vaadin-core@20.0-SNAPSHOT.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

Still need to fix and add a test for this

2021-05-04 12:43 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +            if (platformPinnedDependencies != null) {
Not done - it would be too messy for pnpm-versions locking if this returns and empty object that it is cleaner to leave it the way it is

2021-05-05 09:09 UTC, caalador requested changes

2021-05-05 12:41 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
> +
Done

2021-05-05 12:41 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
> +                            "dependencies/package.json");
Done

2021-05-05 12:41 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
> +                            "vaadin-dependencies/package.json");
Done

2021-05-06 06:11 UTC, caalador approved these changes

2021-05-06 06:15 UTC, merged

2021-08-12 10:56 UTC, pleku commented
This wasn't picked to 14-series, but to be honest, I don't remember why it was not - my bet is that due to "caution" it was to be tested in 7.0 (v20) first, where it seems to be working out fine.