fix: Remove old router layouts content before navigation
vaadin/flow pull request #10973
Opened 2021-05-11 20:08 UTC by mshabarov

## Description

Recursively removes content of the all nested router layouts of the given old content when the navigation occurs. 
This is needed to let Dependency Injection frameworks (Spring and CDI add-ons) to re-create managed components with no duplicates/leftovers.
Consider the following router target chain before navigation:
```
MainRouterLayout
|__SubRouterLayout
     |__MyRouteView
```
And after navigation the whole chain can be replaced:
```
AnotherRouterLayout
|__AnotherRouteView
```
Or some part of it:
```
MainRouterLayout
|__AnotherRouteView
```
Route target `MyRouteView` will be removed before navigation in order to let DI framework to insert it by itself with no leftovers, depending on the scope of `MyRouteView`. It might be a new instance of `MyRouteView` or a preserved one.

Fixes https://github.com/vaadin/cdi/issues/345

Co-authored-by: @roeltje25

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-05-12 09:01 UTC, denis-anisimov reviewed
It might be that the change makes sense but it requires a lot of unit tests which checks that
all the layouts (the topmost and interim) are cleaned up properly.

It also requires ITs even though they will be quite hacky since there are no scopes in Flow and the components are recreated every time (removed are not reused).

One option would be to implement some custom scope without any DI (for pure Flow) and use a custom `Instantiator` which use the scope. That's doable and not that hard: just make sure that other tests are not affected.

Or hacky way: use `UI.getCurrent` in detach listeners of the removed components to set info in the "attached" UI even from the component which is detached.

2021-05-12 09:13 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +        Map<RouterLayout, HasElement> oldChildren = new LinkedHashMap<>();
The order is needed here `oldChildren.forEach(RouterLayout::removeRouterLayoutContent);` when I want to remove the children content from their parents, starting from most bottom layouts and ending with top most layouts.

2021-05-12 11:31 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +        Map<RouterLayout, HasElement> oldChildren = new LinkedHashMap<>();
However, I've double checked and it indeed doesn't matter in which order to detach the contents from its parents.
Will revert it back to `HashMap`

2021-05-14 18:09 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +                        oldContent = oldChildren.get(oldContent);
Done

2021-05-17 06:21 UTC, denis-anisimov requested changes
No ITs ?

2021-05-17 06:21 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +        Map<RouterLayout, HasElement> oldChildren = new HashMap<>();
I recommend to use `IdentityHashMap` here since you don't need `equals` and `hashCode` but the identity of the objects.
Don't forget that `RouterLayout` is implemented by the app developer and he may do mistakes in `equals` and `hashCode` which may break the implementation.

2021-05-17 06:21 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +                routerLayout = (RouterLayout) oldContent;
Don't mutate the parameter provided in the method .
Make a new one for mutation. The good code practice: make method parameters effectively final.

2021-05-17 06:29 UTC, mshabarov commented
> No ITs ?

Here is an IT:
https://github.com/vaadin/flow/pull/10973/files#diff-fb6cd17d229cc75410811ed67e2a0c86e3d7c3b95e31dcd83a1f128e9ad77cef

2021-05-17 06:43 UTC, denis-anisimov requested changes

2021-05-17 06:43 UTC, denis-anisimov commented on flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/RouterLayoutCustomScopeServlet.java
> +                SerializableFunction<Class<? extends Component>, Component> instanceSupplier) {
This is a factory. So the parameter name should be `factory` .

2021-05-17 06:43 UTC, denis-anisimov commented on flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/RouterLayoutCustomScopeServlet.java
> +    public @interface CustomUIScope {
Since this is a test I would go without annotation which allows to configure the behavior.
It's enough to make the default behavior (UI) scoped e.g. : always store the instances .
That will work only for this servlet so there should be no any issues with that.

But that's not blocking , it's just complicates things a bit.

2021-05-17 06:43 UTC, denis-anisimov commented on flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RemoveRoutersLayoutContentIT.java
> +    protected void open() {
Isn't it only enough to override `getTestPath` method ?

2021-05-17 06:44 UTC, denis-anisimov commented
> > No ITs ?
> 
> Here is an IT:
> https://github.com/vaadin/flow/pull/10973/files#diff-fb6cd17d229cc75410811ed67e2a0c86e3d7c3b95e31dcd83a1f128e9ad77cef
> 
> I'm also going to add a regression IT to the CDI add-on repo.

Ah, github showed my only a piece of the changes by the link from e-mail.
OK, thanks.

2021-05-17 10:30 UTC, mshabarov commented on flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/RouterLayoutCustomScopeServlet.java
> +                SerializableFunction<Class<? extends Component>, Component> instanceSupplier) {
Renamed

2021-05-17 10:31 UTC, mshabarov commented on flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/RouterLayoutCustomScopeServlet.java
> +    public @interface CustomUIScope {
Annotation excluded and appropriate comment added

2021-05-17 10:32 UTC, mshabarov commented on flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RemoveRoutersLayoutContentIT.java
> +    protected void open() {
Yes, it's enough, thanks! Fixed.

2021-05-17 10:43 UTC, denis-anisimov approved these changes

2021-05-17 11:42 UTC, merged