test: fix mockito errors accessing protected API in JDK16
vaadin/flow pull request #11034
Opened 2021-05-19 14:20 UTC by manolo

related with https://github.com/vaadin/flow-components/pull/998

2021-05-24 12:25 UTC, manolo commented
Notice that removing easymock is out of the scope of this PR, it should be done separately https://github.com/vaadin/flow/issues/11064

2021-05-25 06:28 UTC, mshabarov requested changes

2021-05-25 06:28 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/component/webcomponent/WebComponentTest.java
> +        // JsonValue has a different number of arguments
This is a bit unclear: previously, a different `executeJs` overload was invoked (with 2 params), and that's why the expected `Mockito.times()` was 1. And this was explained in the comment.
Now the same overload is invoked (2 params) but for some reason it is expected to be invoked 5 times. This is not explained, but instead `// JsonValue has a different number of arguments` is present giving basically no explicit clarifications on why is the times = 5.
Do we really expect times = 5 here? And if yes, could you please add more comments explaining that.

2021-05-25 07:17 UTC, manolo commented on flow-server/src/test/java/com/vaadin/flow/component/webcomponent/WebComponentTest.java
> +        // JsonValue has a different number of arguments
Actually, I don't know the exact cause, I guess mockito implenentation now does not differentiates by the signature of the method but the name, or something. The fact is that the test needs this change, and it still checks whether the correct code is called, so I think the number of internal count calls is not important at this point.

2021-05-25 07:37 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java
> +import static com.vaadin.flow.server.frontend.FrontendUtils.DEFAULT_FLOW_RESOURCES_FOLDER;
`import static` methods should go after all 'normal' imports according to our code styles https://sites.google.com/a/vaadin.com/fw-flow-team-s-wiki/contributing-code/code-style/intellij-idea

2021-05-25 07:45 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java
> +    @Ignore("mockito 3.0 does not use the instance classloader, probably because it uses bytebuddy, see https://github.com/mockito/mockito/issues/2304")
I believe this needs a ticket on flow side to modify and enable this test. Should I create it (if not exists yet) ?

2021-05-25 07:49 UTC, mshabarov commented on fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
> +        Enhancer enhancer = new Enhancer();
Why is this needed?

2021-05-25 07:55 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/component/webcomponent/WebComponentTest.java
> +        // JsonValue has a different number of arguments
> mockito implenentation now does not differentiate the signature of the method but the name

Yeah, this makes sense. Thanks.

2021-05-25 09:13 UTC, manolo commented on fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
> +        Enhancer enhancer = new Enhancer();
Context: https://vaadin.slack.com/archives/CDNTYMS9H/p1621592967091900

Basically, fusion only supports cglib proxies, since mockito was using it in previous version the test simply worked, now mockito uses bytebuddy proxies, hence we need to create a cglib proxy by hand, and this is the code

2021-05-25 09:13 UTC, manolo commented on flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java
> +    @Ignore("mockito 3.0 does not use the instance classloader, probably because it uses bytebuddy, see https://github.com/mockito/mockito/issues/2304")
Please create it, so as we do not forget about this.

2021-05-25 09:13 UTC, manolo commented on flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java
> +import static com.vaadin.flow.server.frontend.FrontendUtils.DEFAULT_FLOW_RESOURCES_FOLDER;
Ups, my eclipse did it. Will revert the movement.

2021-05-25 09:17 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java
> +    @Ignore("mockito 3.0 does not use the instance classloader, probably because it uses bytebuddy, see https://github.com/mockito/mockito/issues/2304")
Sure, will do.

2021-05-25 10:12 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java
> +    @Ignore("mockito 3.0 does not use the instance classloader, probably because it uses bytebuddy, see https://github.com/mockito/mockito/issues/2304")
```suggestion
    @Ignore("mockito 3.0 does not use the instance classloader, probably because it uses bytebuddy, see https://github.com/vaadin/flow/issues/11071, https://github.com/mockito/mockito/issues/2304")
```

2021-05-25 10:12 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java
> +    @Ignore("mockito 3.0 does not use the instance classloader, probably because it uses bytebuddy, see https://github.com/mockito/mockito/issues/2304")
Added a link to corresponding issue.

2021-05-25 10:13 UTC, mshabarov approved these changes

2021-05-25 11:54 UTC, mshabarov approved these changes

2021-05-25 12:36 UTC, merged

2021-05-26 06:30 UTC, ZheSun88 commented
FYI: as this has been reverted from 7.0 branch, i update the label manually.