test: fix mockito errors accessing protected API in JDK16 (#11034) (CP: 6.0)
vaadin/flow pull request #11086
Opened 2021-05-26 21:10 UTC by manolo

2021-05-27 11:40 UTC, pleku requested changes

2021-05-27 11:40 UTC, pleku commented on flow-client/src/main/frontend/form/index.ts
> +  version: /* updated-by-script */ '6.0-SNAPSHOT'
I don't get how is this change related ?

2021-05-31 11:10 UTC, pleku commented
ping @manolo

2021-06-01 12:29 UTC, manolo commented on flow-client/src/main/frontend/form/index.ts
> +  version: /* updated-by-script */ '6.0-SNAPSHOT'
I reverted this, but still shouldn't that version say 6.0 since it's flow 6.0 branch ?

2021-06-01 12:41 UTC, pleku approved these changes

2021-06-01 13:14 UTC, merged