feat: allow defining access control annotations on view super classes
vaadin/flow pull request #11097
Opened 2021-05-27 14:35 UTC by taefi

## Description

This allows leaving child views unannotated 
with any of the access annotations and the 
access rules to be defined by the view's 
superclasses. 

Fixes #10705

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [x] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-05-31 14:05 UTC, Artur- commented
I think this changes how endpoint security checks work in an undesired way. It should be scoped to only change view aka class based access control

2021-05-31 16:16 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessAnnotationChecker.java
> +     *             if the input <code>cls</code> is null
```suggestion
     * @return the first annotated class in {@code cls}'s hierarchy that
     *         annotated with one of the access annotations, starting from
     *         the input {@code cls} class itself, going up in the hierarchy.
     *         WARNING: Note that interfaces are ignored.
     *         <p>
     *         If no class in the hierarchy was annotated with any of the access
     *         annotations, the {@code cls} input parameter itself would be
     *         returned.
     *         <p>
     *         Access annotations that being checked are:
     *         <ul>
     *         <li>{@code @AnonymousAllowed}
     *         <li>{@code @PermitAll}
     *         <li>{@code @RolesAllowed}
     *         <li>{@code @DenyAll}
     *         </ul>
     *
     * @throws NullPointerException
     *             if the input {@code cls} is null
```

2021-06-01 06:41 UTC, haijian-vaadin requested changes

2021-06-01 06:41 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessAnnotationChecker.java
> +            clazz = clazz.getSuperclass();
For the case that a view doesn't have any access control annotations, and also non of the ancestors have any annotations, should we return the view class itself instead of the Object? The end result is probably the same but feels more right that way.

2021-06-01 11:43 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessAnnotationChecker.java
> +            clazz = clazz.getSuperclass();
It returns the view class itself currently,  doesn't it?
Consider class hierarchy `Object <- A <- B`, where `B` is an input and no-one is annotated. Then `clazz` finally would be an `Object` and method returns `cls` which is a view class `B`.

2021-06-01 11:46 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessAnnotationChecker.java
> +     *         WARNING: Note that interfaces are ignored.
```suggestion
     *         <em>Note:</em> interfaces in the {@code cls}'s hierarchy are ignored.
```

2021-06-01 12:02 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/auth/AccessControlTestClasses.java
> +    }
I would also add a test case when a tested class is an interface or it's parent is an interface:
```java
@AnonymousAllowed
public static interface CustomComponent extends HasElement {
}

public static class CustomComponentImpl implements CustomComponent {
}
```
This is not maybe a real case, but since the API is public and javadocs warns about interfaces skipping, good to tests it either.

2021-06-01 13:02 UTC, mshabarov commented
> I think this changes how endpoint security checks work in an undesired way. It should be scoped to only change view aka class based access control

@Artur- could you please elaborate more what do you mean, or point me to the docs/classes/ticket where the behaviour is being changed by this implementation?

2021-06-01 14:40 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/auth/AccessControlTestClasses.java
> +    }
Done.

2021-06-01 14:48 UTC, mshabarov approved these changes

2021-06-01 15:10 UTC, taefi commented
> I think this changes how endpoint security checks work in an undesired way. It should be scoped to only change view aka class-based access control

I should argue a little to deepen my understanding - or misunderstanding ;)

If I understood @Artur-'s discussion about this change correctly, he is concerned about the behavior change of the following method of `AccessAnnotationChecker`:
```Java
public AnnotatedElement getSecurityTarget(Class<?> cls){ ... }
```
Before changes in this PR (as it is in master), the security target for endpoints was working as follows:
- If the endpoint's methods weren't annotated with any of the access annotations, the security target has been falling back to Endpoint class, and the above method was resolving it to the class itself, so if the Endpoint class also wasn't annotated with any access annotation, The `DenyAll` logic was applying. 

Now (after this change), when the endpoint security target for unannotated methods falls back to the Endpoint class, it would go up in the hierarchy and ... (rest of the story would be the same as flow views). 

I'm not sure why is this behavior change should be "undesired", and even I'm in favor of this change as an enhancement for the fusion endpoint security, but **it is a breaking change** anyway.

2021-06-02 06:16 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessAnnotationChecker.java
> +            clazz = clazz.getSuperclass();
right, my bad, misread that it returns clazz at the end.

2021-06-02 06:19 UTC, haijian-vaadin commented
@taefi @mshabarov The discussion is here in the fusion channel https://vaadin.slack.com/archives/CDNTYMS9H/p1622458536274100

I think this change looks good, but we need to how this security checks work for both Fusion and Flow and make them aligned, also to be aligned how it works with Spring Security.

2021-06-02 06:50 UTC, Artur- commented
I have not tested how it affects endpoints but as the same access checker is used for views and endpoints, it is likely that it changes how endpoint access checks work.

Endpoint access checks need to be in sync with how the annotation checking works in e.g. Spring Boot, which should follow JSR 250. Otherwise you might end up in a situation where you are using the same annotation in different parts of your application, say `@Endpoint` and `@Service` classes, but the meaning of the annotations are different depending on the case. We do not want that.

If I interpreted JSR 250 correctly it seems to say:
1. You can always figure out the annotation based on looking at only one file
2. The file to use is the one where the method is declared (or overridden)
3. Method annotation always override class annotation
4. You never look at any super (overridden) method or super class
5. You never look at interfaces

If this PR changes it so that 4. is no longer true because the super class of an endpoint is checked then you have a mismatch in how Vaadin and Spring decides if access is allowed or denied. This would make it hard to understand if the application is properly secured or not.

2021-06-02 06:52 UTC, Artur- commented
JSR 250 only considers method level security with the class being the place where you can do a fallback configuration. For view based access control we need class based security with another, more generic place as the fallback. For this, the only logical place is a super class.

2021-06-02 07:38 UTC, haijian-vaadin approved these changes

2021-06-02 08:47 UTC, merged