fix: set routes first into the template
vaadin/flow pull request #11107
Opened 2021-05-28 10:23 UTC by denis-anisimov

fixes psi#26

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-05-28 10:29 UTC, fluorumlabs requested changes

2021-05-28 10:29 UTC, fluorumlabs commented on flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
> +        template = template.replace("{{additionalInfo}}", additionalInfo);
Please add comment emphasizing that the order of replacements is important (for the future you), similar to https://github.com/vaadin/flow/blob/30886fd96c0cfdb8cc7d8546972666528126fddb/flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java#L1148-L1150

2021-05-28 10:45 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
> +        template = template.replace("{{additionalInfo}}", additionalInfo);
I've added the comment but this is extra.
There is a test which tests that it works as expected.
Comment doesn't force anything: too easy to ignore it.

2021-05-28 10:52 UTC, fluorumlabs commented on flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
> +        template = template.replace("{{additionalInfo}}", additionalInfo);
The test is not ideal as it only tests injection via `{{path}}` (not `{{additionalInfo}}` which is also present in production template). And obviously it won't catch the cases when, at some point, a new placeholder will be added.

So it's better to have the comment. While it won't prevent issues, it will at least lower the chance.

2021-05-31 14:34 UTC, mshabarov approved these changes

2021-06-01 05:58 UTC, mshabarov commented
@fluorumlabs could you please review this PR? Merge is blocked since you requested changes. Thanks!

2021-06-01 06:20 UTC, fluorumlabs approved these changes

2021-06-01 06:40 UTC, merged