Make generated TS array be able to have undefined values
vaadin/flow pull request #11124
Opened 2021-06-01 06:29 UTC by Lodin

Fixes vaadin/fusion#24.

2021-06-01 06:52 UTC, Haprog approved these changes

2021-06-01 07:27 UTC, Haprog requested changes
Should make sure that arrays of primitive types (from Java) won't get `undefined` inside the array in the TS type, as we discussed in the daily.

I guess these:

```java
int[] array1;
List<int> array2;
```

should result in something like this?:

```typescript
let array1: Array<number>;
let array2: Array<number> | undefined;
```

2021-06-08 08:42 UTC, Lodin commented
I suppose we can ignore @vaadin-bot here because all the issues are not caused by my changes

2021-06-08 14:32 UTC, platosha approved these changes
Great job here! 👍

2021-06-09 07:34 UTC, platosha approved these changes

2021-06-09 09:26 UTC, Haprog approved these changes

2021-06-09 09:26 UTC, merged