fix: do not open FileSystem for unknown schemes
vaadin/flow pull request #11235
Opened 2021-06-15 08:32 UTC by caalador

Don't open a filesystem for unknown schemes
that are probably custom for container and
have no FileSystem Provider implementation added.

Fixes #11230

2021-06-15 08:56 UTC, pleku reviewed
Looking good, couple of questions

2021-06-15 08:56 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
> +                        "Can not read scheme '" + fileURI.getScheme() + "'");
Should it output the full uri for debugging purposes to be able to figure out the causing resource ? The catching block only logs this error its message.

Or since the code is not actually doing anything itself, but just checking if it is a directory, maybe the message could reflect that "this is fine" and the error can be "ignored".

2021-06-15 08:56 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
> +                fileServer.isStaticResourceRequest(request));
How difficult would it be to add a unit test that actually verifies that the serving of the jar from the jar works, meaning that also `serveStaticResource` method call would be checked for this case ? As we don't have a regression test for that either but the added code here could help in adding the test case

2021-06-15 09:37 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
> +                        "Can not read scheme '" + fileURI.getScheme() + "'");
Just a question or hint - this whole "resource" handling is quite tricky.. I've seen multiple issues on spring / spring boot over the last years with the same problems.. the amount of "protocol" and combinations is just absurd.. (e.g. jar, war, wsjar, zip, bundle..)

I'm not sure if you have looked around, but there is a handy spring framework class that handles this in spring, which could be used to get some ideas how they do it?

https://github.com/spring-projects/spring-framework/blob/main/spring-core/src/main/java/org/springframework/core/io/support/PathMatchingResourcePatternResolver.java

2021-06-15 10:26 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
> +                fileServer.isStaticResourceRequest(request));
It would seem like we would need to unzip the initial jar to be able to check the secondary jar content.

2021-06-15 10:26 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
> +                        "Can not read scheme '" + fileURI.getScheme() + "'");
Yes I'm certain that we can not support everything, but should only take care of the basic one and use the old resolution for anything else.

2021-06-15 10:26 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
> +                        "Can not read scheme '" + fileURI.getScheme() + "'");
Added more info to the exception.

2021-06-15 11:43 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
> +                fileServer.isStaticResourceRequest(request));
Added test to show expectation of feature.

2021-06-15 11:51 UTC, pleku requested changes

2021-06-15 11:51 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
> +            warOutputStream.closeEntry();
This creation code could be extracted and reused for both added tests instead of 1-1 duplication

2021-06-15 11:56 UTC, pleku requested changes

2021-06-15 11:56 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
> +    public void jarInaJar_fileIsLoadedCorrectly()
To me test name is invalid, it should be `isStaticResource_jarInAJar_detectsAsStaticResources`

2021-06-15 11:56 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
> +    public void jarWarFileScheme_() throws IOException {
To me test name is invalid, it should be `isStaticResource_jarWarFileScheme_detectsAsStaticResources`

2021-06-15 11:58 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
> +                fileServer.isStaticResourceRequest(request));
Just noting that we don't still have tests that the actual serving of the files will work (which I intended), only that those are detected properly.

2021-06-15 11:58 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
> +    public void jarWarFileScheme_() throws IOException {
done

2021-06-15 11:58 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
> +    public void jarInaJar_fileIsLoadedCorrectly()
done

2021-06-15 11:58 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
> +            warOutputStream.closeEntry();
done

2021-06-15 12:01 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
> +                fileServer.isStaticResourceRequest(request));
Serving of files is tested for instance in `serveStaticResource` and jar resources are mainly served by the ServletContainer due to the spec. Any classResource that we serve should have their own test already.

2021-06-16 07:22 UTC, pleku approved these changes

2021-06-16 10:14 UTC, merged

2021-06-16 10:56 UTC, knoobie commented
Has the bot a problem because this isn't targeting master?

2021-06-16 10:59 UTC, caalador commented
Could be. I'll make a PR for master and have that trickle down instead. Even though I have used the bot for automating from  2.7 to 2.6.

2021-06-23 21:20 UTC, estronque commented
Thanks, the fix works!