feat: generate jandex index for Flow
vaadin/flow pull request #11241
Opened 2021-06-15 11:13 UTC by caalador

Generate a jandex index for Flow
to use with quarkus.

part of vaadin/quarkus#1
Flow support for #9862 when no platform in use

2021-06-16 09:24 UTC, denis-anisimov requested changes

2021-06-16 09:24 UTC, denis-anisimov commented on flow-jandex/pom.xml
> +            <artifactId>flow-html-components-testbench</artifactId>
Is this needed at runtime (not for tests) ?

2021-06-16 09:24 UTC, denis-anisimov commented on flow-jandex/pom.xml
> +            <artifactId>flow-client</artifactId>
Is there any Java file which should be included into the index and used at runtime ?
Shouldn't be.

2021-06-16 09:24 UTC, denis-anisimov commented on flow-jandex/pom.xml
> +</project>
new line

2021-06-16 09:24 UTC, denis-anisimov commented on flow-jandex/pom.xml
> +                                <outputDirectory>${project.build.outputDirectory}</outputDirectory>
is it a correct place for unpacking ?
This is a jar project, so won't the unpacked classes be packaged into one big jar file in the result ?

2021-06-16 10:57 UTC, caalador commented on flow-jandex/pom.xml
> +            <artifactId>flow-client</artifactId>
Shouldn't be needed. Removed.

2021-06-16 10:57 UTC, caalador commented on flow-jandex/pom.xml
> +            <artifactId>flow-html-components-testbench</artifactId>
Shouldn't be needed. Removed.

2021-06-16 10:57 UTC, caalador commented on flow-jandex/pom.xml
> +                                <outputDirectory>${project.build.outputDirectory}</outputDirectory>
We unpack any com.vaadin so that they get read as the jandex plugin doesn't go through jar file contents as far as I could configure it and we exclude all classes from the generated jar.

2021-06-16 10:57 UTC, caalador commented on flow-jandex/pom.xml
> +</project>
added

2021-06-17 06:09 UTC, denis-anisimov approved these changes

2021-06-18 04:56 UTC, merged