Consider upload requests an internal request to work with Spring Security
vaadin/flow pull request #11278
Opened 2021-06-17 13:05 UTC by Artur-

2021-06-18 15:08 UTC, pleku requested changes

2021-06-18 15:08 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +                .matches("VAADIN/dynamic/resource/.*/.*/upload");
With this check, one can make a call to `VAADIN/dynamic/resource/../../../upload` and this will return `true`.
I don't see any encoding done here (see `isPathUnsafe` method). In theory, one could have mapped something to `/upload` or `/some-prefix-path/upload` that is secured. That makes at least the contract for the `HandlerHelper` API method a bit broken as I don't think that URL should return `true`. There is also no mention of encoding/prechecking the request in the javadocs.

I would fix it just to be safe, even if it is not exploitable through `VaadinWebSecurityConfigurerAdapter.java` in Spring add-on (I don't know if that is the case) by bypassing security measures there for a fake upload request.

2021-06-21 09:36 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +                .matches("VAADIN/dynamic/resource/.*/.*/upload");
Changed to check the whole string for valid characters

2021-06-21 11:31 UTC, pleku approved these changes

2021-06-21 11:33 UTC, merged

2021-07-01 09:11 UTC, darjag commented
I have this issue in Vaadin 20.0.3 with VaadinWebSecurityConfigurerAdapter. In my case I use with a property vaadin.urlMapping and don't test without.

2021-07-01 11:24 UTC, Artur- commented
The wast majority of Flow related features and fixed for Spring Security is only in Vaadin 21. For Vaadin 20 you can manually add a rule for allowing requests to `VAADIN/dynamic/resource/[0-9]*/[a-z0-9-]**/upload` to bypass the CSRF check