Support non-nullability for collection items
vaadin/flow pull request #11290
Opened 2021-06-18 15:44 UTC by Lodin

Resolves vaadin/fusion#42

2021-06-22 12:00 UTC, haijian-vaadin requested changes

2021-06-22 18:53 UTC, haijian-vaadin requested changes
Looks like it's working for entities now, but not on Endpoint methods. E.g, 
given
```
public List<@Nonnull String> mList(){
    return new ArrayList<>();
}
```
the generated ts code is still
```
function _mList(): Promise<Array<string | undefined> | undefined> {
 return client.call('SamplePersonEndpoint', 'mList');
}
export {_mList as mList};
```

2021-06-23 06:39 UTC, haijian-vaadin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/GeneratorType.java
> +    boolean isType(Class<?>... clazz) {
In the original SchemaResolver, there were 2 methods, `isType()` and `isTypeOf`, `isType()` here is the old `isTypeOf()`, the `isType()` is missing, which at least should be used for the Iterable type checking, otherwise it will introduce regression in the `SchemaResolverTest`.

2021-06-23 14:36 UTC, Lodin commented
@haijian-vaadin, I addressed the issue with the missing generation for endpoint parameters and return types

2021-06-23 19:08 UTC, haijian-vaadin requested changes

2021-06-24 06:56 UTC, Lodin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/GeneratorType.java
> +            Class<?>... classes) {
I don't think we should do that. `isExactType` uses the internal class `type` property, and `isType` accepts a type as an argument. We can make `isExactType` receiving a type as an argument but it breaks the similarity between `isExactType` and `isAssignableType` which goes agains DX in my opinion. Also, while `isExactType` and `isAssignableType` are public interface, the `isType` method is just an internal implemnetation. That's why it is `private`.

2021-06-24 07:02 UTC, haijian-vaadin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/GeneratorType.java
> +            Class<?>... classes) {
OK, then let's keep it. Does it have to be a static method? Looks like it's only used internally by instance methods, we can make this one as an instance method as well?

2021-06-24 07:20 UTC, Lodin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/GeneratorType.java
> +            Class<?>... classes) {
Well... In JS it is a common practice to move any method that does not use `this` to static. The logic is that `static` is a function, not a method. I used the same approach here. Not sure what is the best practice for Java 😅

2021-06-24 07:53 UTC, haijian-vaadin approved these changes

2021-06-24 11:15 UTC, haijian-vaadin approved these changes

2021-06-24 11:15 UTC, merged