feat: Do not serialize VaadinSession by default in development
vaadin/flow pull request #11304
Opened 2021-06-22 07:48 UTC by Artur-

Fixes #11151

2021-06-23 13:42 UTC, Artur- commented
Seems like this approach has a problem at least with Jetty. Jetty (in the included test) serializes the session after each request so after the first serialization, when `sessionWillPassivate` has been called, the `VaadinSession` is no longer found and the application does not work.

2021-06-23 14:04 UTC, Artur- commented
Took another approach which skips serialization instead of removing it from the session

2021-06-24 08:27 UTC, pleku requested changes
I'm going to test with some other projects+servers too

2021-06-24 08:27 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +        if (session != null && !session.valid) {
non-blocking: In this context the `session.valid` gives me a different impression, as in the session was invalidated. Some other name would be more understandable but the name eludes me

2021-06-24 08:50 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
> -
Fixed

2021-06-24 08:50 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +    String getSessionAttributeName() {
Reverted

2021-06-24 08:50 UTC, Artur- commented on flow-tests/test-jetty-reload/src/test/java/com/vaadin/flow/uitest/ui/SessionValueIT.java
> +    public void sessionValuePreservedOnRefresh() throws InterruptedException {
Changed to reload

2021-06-24 08:50 UTC, Artur- commented on flow-tests/test-jetty-reload/src/test/java/com/vaadin/flow/uitest/ui/SessionValueIT.java
> +        Assert.assertEquals(customAttribute, customAttributeAfterReload);
Done

2021-06-24 08:50 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +        if (session != null && !session.valid) {
Inverted and changed to `deserializedAsEmpty`

2021-06-24 10:59 UTC, pleku submitted a review, later dismissed
Tested with TomEE and it worked there too. Tried with Jboss/Wildfly but run into other issues and could not get to test hot deploy capabilities easily ... 

@denis-anisimov are you going to take a look or not ?

2021-06-24 11:02 UTC, pleku commented
Also, maybe there should be a mention of this behavior in https://github.com/vaadin/docs/blob/latest/articles/guide/live-reload/index.asciidoc, can you make a PR there @Artur- ? Essentially I would just add a note that this behavior is there to make it easier to develop apps while keeping authentication features enabled, and that the behavior will not be the same for production apps.

2021-06-24 11:12 UTC, denis-anisimov commented
Immediate question: is it only targets the `master` version or it will be picked into other versions ?

2021-06-24 11:15 UTC, Artur- commented
Only master

2021-06-24 11:17 UTC, denis-anisimov commented
>@denis-anisimov are you going to take a look or not ?

yes.

Is there any rush ?

2021-06-24 11:25 UTC, denis-anisimov requested changes

2021-06-24 11:25 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
> +    boolean isDevModeSerializeSession();
The name is cryptic so much that I can't understand what's that without reading javadocs.

I don't think there is a sense to care about prefix `is` for boolean property.
We already have e.g `disableAutomaticServletRegistration` method.
So getting rid of `if` allows to make the proper name for the method.

2021-06-24 11:25 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
> +    boolean isDevModeSerializeSession();
This introduces a new API.
And the question related to my initial question: what versions this PR targets?

If it should be picked to other versions then there should be 2 PRs most likely: one which doesn't change API and just introduce a property which can be used even without `DeploymentConfiguration` and then change in `DeploymentConfiguration`.
Otherwise it won't be trivial to pick this change.
Or it you are going to pick the change in other branches by yourself then it's fine.

2021-06-24 11:25 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
> +    public boolean isDevModeSerializeSession() {
The question here but may be it should be asked in the `DeploymentConfiguration`:
- is this the proper class to have this method ?

`DeploymentConfiguration` is 1:1 with a VaadinServlet in the app.
`ApplicationConfiguration` is 1:1 with the _app_.

So the question is :  do you really want to disable/enable session serialiation per VaadinServlet or per applicaiton?
So is the code ready for the case when application has several servlets and one servlet allows serialization and another doesn't ?

And does this have any sense at all ?

If it should be a setting per application then this is a wrong class along with `DeploymentConfiguration` interface.

2021-06-24 11:32 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
> +    public boolean isDevModeSerializeSession() {
You don't, just like you don't want to enable production mode / dev mode per servlet and a lot of (all?) other parameters in `DeploymentConfiguration`. But I think it falls out of scope for this PR.

2021-06-24 11:33 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
> +    boolean isDevModeSerializeSession();
What are you suggesting as the name? `devModeSerializeSession`?

2021-06-24 11:34 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
> +    boolean isDevModeSerializeSession();
There is `isDevModeLiveReloadEnabled` right above this. It is named in the same way except with an extra `Enabled` that gives no additional information

2021-06-24 11:42 UTC, Artur- commented
Docs in https://github.com/vaadin/docs/pull/584

2021-06-24 11:42 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
> +    boolean isDevModeSerializeSession();
Documented in https://github.com/vaadin/docs/pull/584 as 

`devmode.serializeSession`::
Determines whether the `VaadinSesion(s)` of the users are serialized on server shutdown when running in development mode. 

Naming here and in the docs should match

2021-06-24 11:43 UTC, denis-anisimov requested changes

2021-06-24 11:43 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +        if (session != null && session.deserializedAsEmpty) {
What is `session.deserializedAsEmpty`?
a public field in the session ?

There can't be any `public` fields.

2021-06-24 11:43 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +    transient boolean deserializedAsEmpty = false;
Every field may be only `private` .
Make an getter or setter with a proper modifier.

2021-06-24 11:43 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +    transient boolean deserializedAsEmpty = false;
`false` is a default value for a boolean field.
It's extra

2021-06-24 11:43 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +            this.serialize = false;
`serialize` can be calculated at any time.
Is there any reason to introduce this as a field and then care about its `transient` nature ?

2021-06-24 11:43 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +        if (!wasSerialized) {
I don't understand this code.
It just returns if serialization has not happened.

It means that the state of the object is not restored proeprly.
It means e.g. that transient `pendingAccessQueue` has `null` value which means that the code becomes broken.

So: shouldn't this code just thrown an exception if an object is deserialized being not serialized ?

2021-06-24 11:43 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +        stream.writeBoolean(this.serialize);
`this` is extra here and below.

2021-06-24 11:43 UTC, denis-anisimov commented on flow-tests/test-jetty-reload/src/main/java/com/vaadin/flow/uitest/ui/SessionValueView.java
> +}
new line

2021-06-24 11:47 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
> +    public boolean isDevModeSerializeSession() {
No.
It's a part of the PR.
There is already `ApplicationConfiguration` and `AbstractConfiguration`.
And there is `isProductionMode` in the `AbstractConfiguration`.
So you should just use the proper class and decide which scope for the config should be used: application or sevlet.
There is nothing else to do.
Since this is a new property it should be decided now, here in this PR.
Only existing properties can be considered separately.

2021-06-24 11:48 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +        if (!wasSerialized) {
The whole change is about conditionally not including `VaadinSession` in the serialized HTTP session.

If you throw an exception during serialization or deserialization, then you abort the whole process.

When the session is deserialized, it is marked as "empty" and then ignored and removed by `VaadinService` when encountered.

2021-06-24 11:48 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +            this.serialize = false;
I think there was a reason in the first version of the PR but probably not anymore. Shouldn't be anything preventing reading `configuration` in `writeObject`

2021-06-24 11:49 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
> +    boolean isDevModeSerializeSession();
`isDevModeSessionSerializationEnabled` is already better.
But I would go with `enableDevModeSessionSerialization` (`disable` ) or something like this.

2021-06-24 11:53 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +            this.serialize = false;
Fixed

2021-06-24 11:53 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +    transient boolean deserializedAsEmpty = false;
Fixed

2021-06-24 11:53 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +        if (session != null && session.deserializedAsEmpty) {
Fixed

2021-06-24 11:56 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
> +    public boolean isDevModeSerializeSession() {
`ApplicationConfiguration` sounds better then. I will move it.

2021-06-24 12:09 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
> +    boolean isDevModeSerializeSession();
Changed to `isDevModeSessionSerializationEnabled` which is similar to `isDevModeLiveReloadEnabled`. The property then is also similar: `devmode.sessionSerialization.enabled`

2021-06-24 12:15 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +        if (session != null && session.isDeserializedAsEmpty()) {
Does this mean that the deserialized `VaadinSession` instance will be disregarded and a new one will be created instead ?
Would be good to have this in the comments then.

2021-06-24 12:18 UTC, denis-anisimov requested changes

2021-06-24 12:18 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +        if (session != null && session.isDeserializedAsEmpty()) {
Is this tested by the way anyhow ?

2021-06-24 12:18 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +        if (!wasSerialized) {
Would be good to have this in the comments.

Another thing which I would like to see here: protection from using the instance which is not properly deserialized.
It should make itself as invalid (via some flag or somehow else) and then every access to the instance should throw an exception which says that the instance is invalid: a new one should have been created and used instead.

2021-06-24 12:19 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +        if (session != null && session.isDeserializedAsEmpty()) {
Added

2021-06-24 12:21 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +        if (session != null && session.isDeserializedAsEmpty()) {
The whole thing is tested by the IT which makes it impossible to serialize the test UI but checks that the session is still serialized and deserialized. If this did not work, then you would not get a new UI after server restart + browser refresh

2021-06-24 12:23 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +        if (!wasSerialized) {
Added an assert to `checkHasLock` which is called from most methods

2021-06-24 12:25 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +        if (!wasSerialized) {
Added javadoc

2021-06-24 12:34 UTC, denis-anisimov requested changes

2021-06-24 12:34 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +        assert deserializedAsEmpty == false : "The session was discarded during serialization and should not be used";
I think it should not be an `assert`.
`assert` is for Flow developers: it most likely will be disabled for the app developer (since you have to enable it explicitely via `-ea` ).
it should throw an exception.

2021-06-24 12:36 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +        assert deserializedAsEmpty == false : "The session was discarded during serialization and should not be used";
Yes and this can only fail because of a bug in Flow. The error message has no meaning for anybody else

2021-06-24 12:37 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +        assert deserializedAsEmpty == false : "The session was discarded during serialization and should not be used";
May be you are right.

2021-06-24 12:37 UTC, denis-anisimov submitted a review, later dismissed

2021-06-25 08:38 UTC, pleku approved these changes

2021-06-25 08:42 UTC, merged