10965 avoid not found trigger 2.7
vaadin/flow pull request #11334
Opened 2021-06-25 12:45 UTC by denis-anisimov

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-06-29 08:56 UTC, pleku requested changes
Like discussed in the ticket, not sure if this should be taken in or not, so blocking for now.

Personally I can't say which is better, to allow certain accept headers or to block certain accept headers. To be continued in the ticket.

2021-07-08 10:25 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +                || typesWithWeight.contains(XHTML_TYPE_WEIGHT);
I think the [suggestion](https://github.com/vaadin/flow/issues/10965#issuecomment-870460570) from @Legioth makes sense,  what do you think @denis-anisimov ?

> Anything with text/html in the group with highest priority should certainly cause a UI to be created.
If we want to slightly reduce the risk of regressions, then we could consider to also create a UI for requests with text/html at a lower priority, or with only */* as the only value.
We should definitely not create an UI if the browser doesn't at all ask for text/html or if it has */* only to supplement some more specific request.

2021-07-09 06:20 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +                || typesWithWeight.contains(XHTML_TYPE_WEIGHT);
I don't think I understand what you mean.

>Anything with text/html in the group with highest priority should certainly cause a UI to be created.

Implemented here in this PR.

>If we want to slightly reduce the risk of regressions, then we could consider to also create a UI for requests with text/html at a lower priority, or with only / as the only value.
We should definitely not create an UI if the browser doesn't at all ask for text/html or if it has / only to supplement some more specific request.

It is possible to configure `Accept` header manually in the browser so technically it may contain anything (and  unexpected things) but any meaningful request contains `Accept` header which accepts _everything_ with lower weight.
E.g. image request `Accept` header is `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`.
`*/*` matches `text/html`.

So it doesn't add anything to clarify the PR/direction to improve it.

If you see some exact steps which may be done here please just describe them in the details.

2021-07-26 11:54 UTC, Legioth commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +                || typesWithWeight.contains(XHTML_TYPE_WEIGHT);
If the browser specifically asks for `text/html` at any priority, then that's a clear indication that the browser might intend to use the response body as HTML.

Browsers usually include `*/*` at a low priority as a fallback (e.g. `text/css,*/*;q=0.1`), so it would defeat the purpose if we would interpret that to match `text/html` even though it does match from a strictly technical sense.

As an exception to the exception, asking for only `*/*` could still be defined to return a Flow bootstrap page since that's a very generic request for which we cannot make any assumptions for what the browser might do.

> It is possible to configure `Accept` header manually in the browser so technically it may contain anything

If the user has configured the browser to send an arbitrary `Accept` header value, then it's quite acceptable that the error handling might not work in the best possible way. The only result is that the user will see a generic 404 response instead of seeing a Flow view that says that nothing was found for the given URL. If the value doesn't match any of the patterns that we look for, then we can treat it the same way as if no `Accept` header was present.

2021-08-16 10:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=11334) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=11334) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=11334) it.</sub>

2021-11-01 12:10 UTC, pleku commented
Closing this PR for now as it is not deemed important enough to make it better.

Please comment on the issue #10965 if this is important for someone.

2021-11-01 12:10 UTC, closed without merging