fix: Update buildIdentifier comparison
vaadin/flow pull request #11353
Opened 2021-06-29 11:16 UTC by caalador

Fix buildIdentifier comparison so
values compare correctly.

fixes #11352

2021-06-29 11:49 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
> +    private int compareBuildIdentifier(FrontendVersion other) {
Just out of curiousity - what if someone uses e.g. `2.0.0.1` for some reason - does it end up to the build identifier ? Can you add a test that it wins over prerelease versions like `2.0.0-alpha5`.

2021-06-29 11:58 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
> +    private int compareBuildIdentifier(FrontendVersion other) {
But ain't that eXo Versioning of Major.Minor.Maintenance.Patch-Qualifier and we support semantic versioning of Major.Minor.Revision-BuildIdentifier (we ofc actually accept . . . . instead of . . . - because it's simpler)
Also no it returns wrong as did the previous version.

2021-06-29 12:12 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
> +    private int compareBuildIdentifier(FrontendVersion other) {
That should cover it also.

2021-06-29 19:36 UTC, pleku requested changes

2021-06-29 19:36 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
> +                if (otherMatcher.group(1).isEmpty()) {
I don't get this code and I think it is not just me - if the string for `otherMatcher.group(1)` is empty, why is it then compared ? Isn't it just the case that there is no _string_ group for that one and thus the numeric value will mean that it is newer ?

2021-06-29 19:36 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java
> +                test.isOlderThan(new FrontendVersion("2.0.0.5")));
Please test also that it works the other way around

2021-06-29 19:36 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java
> +    }
Please add a test that `2.0.0.6` is older than `2.0.0.11` for both ways

2021-06-29 19:36 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java
> +                test.isOlderThan(new FrontendVersion("2.0.0-alpha13")));
Looking at the code logic, I wonder if all the comparisons here should be double checked the other way too, e.g. 
```java
assertFalse("2.0.0-alpha13 should not be older than 2.0.0-alpha20",
                new FrontendVersion("2.0.0-alpha13").isOlderThan(test));
```

2021-06-30 05:23 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
> +                if (otherMatcher.group(1).isEmpty()) {
Fixed. Also other issues in the check.

2021-06-30 05:23 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java
> +                test.isOlderThan(new FrontendVersion("2.0.0-alpha13")));
added older newer checks for multiple choices.

2021-06-30 05:23 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java
> +    }
added

2021-06-30 05:23 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java
> +                test.isOlderThan(new FrontendVersion("2.0.0.5")));
added older newer checks for multiple choices.

2021-06-30 05:47 UTC, pleku requested changes
Almost, one minor comment

2021-06-30 05:47 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
> +            if (thisMatcher.group(1).compareTo(otherMatcher.group(1)) != 0) {
Shouldn't this ignore the case like below? In the unlikely event that someone would have caps on?

2021-06-30 05:47 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java
> +        test = new FrontendVersion("2.0.0.alpha20");
There is a dot here instead of dash but that is fine

2021-06-30 06:03 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
> +            if (thisMatcher.group(1).compareTo(otherMatcher.group(1)) != 0) {
done

2021-06-30 06:03 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java
> +        test = new FrontendVersion("2.0.0.alpha20");
done

2021-06-30 06:26 UTC, manolo approved these changes

2021-06-30 06:27 UTC, manolo commented
Tested manually in my local and works ok.

2021-06-30 07:34 UTC, pleku approved these changes

2021-06-30 07:38 UTC, merged