fix: use dedicated exception for Location validation
vaadin/flow pull request #11367
Opened 2021-06-30 12:06 UTC by denis-anisimov

fixes #11302

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-07-01 08:03 UTC, pleku commented
@denis-anisimov this adds what I consider public API (the bot added the `+0.1.0` label) and thus cannot be backport to 2.6 and 7.0.

For 8.0 it should be fine since we're not yet in beta.

2021-07-01 08:18 UTC, pleku requested changes
Blocking for now since I've been working on #9443 and I'm not sure if it makes sense to make this change or not https://github.com/vaadin/flow/issues/11302#issuecomment-872032301

2021-07-01 08:18 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/router/InvalidLocationException.java
> +     * @since 1.4
Where does this come from ?

2021-07-01 08:21 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/router/InvalidLocationException.java
> +     * @since 1.4
copy paste from the RuntimeException docs

2021-07-06 12:06 UTC, pleku submitted a review, later dismissed
Decided to approve this and I'll use the introduced exception to validate the `Location` in `BoostrapHandler` to adjust behavior for #9443 to return 400 code

2021-07-08 10:26 UTC, pleku approved these changes

2021-07-08 10:26 UTC, merged