fix: Move generated theme files to frontend/generated
vaadin/flow pull request #11370
Opened 2021-07-01 08:25 UTC by caalador

Any theme file that is generated is
now generated into `frontend/generated`

Fixes #11180

2021-07-02 09:16 UTC, pleku requested changes

2021-07-02 09:16 UTC, pleku commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
> +    themeFile += `import {applyTheme as applyBaseTheme} from 'generated/${themeProperties.parent}.generated.js';`;
This is different from `master` branch which has 
```javascript
themeFile += `import {applyTheme as applyBaseTheme} from './theme-${themeProperties.parent}.generated.js';`;
```

There are other changes too that can be seen with `git diff master issues/11180_move_generated_theme_file -- flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js`

2021-07-02 09:16 UTC, pleku commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
> +const nameRegex = /generated\/(.*).generated.js/;
The is a diff here too to `master`, seen with `git diff master issues/11180_move_generated_theme_file -- flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js`

2021-07-02 09:16 UTC, pleku commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
> +    fs.writeFileSync(path.resolve(options.frontendGeneratedFolder, themeName + '.generated.js'), themeFile);
In `master` the file is written as `(options.frontendGeneratedFolder, 'theme-' + themeName + '.generated.js'), themeFile);`

which one it should be ?

2021-07-02 09:16 UTC, pleku commented on .gitignore
> +/flow-tests/**/frontend/generated/
This should be added to the V14 branches on starters too, as probably newer branches have it already due to fusion

2021-07-02 09:25 UTC, caalador commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
> +    fs.writeFileSync(path.resolve(options.frontendGeneratedFolder, themeName + '.generated.js'), themeFile);
For this it is `[themeName].generated.js` I don't know why master has added a `theme-` to the generated name.
The same is why was `theme-generated.js` not ok and was changed to `theme.js` in master?
The other diffs are also a bit related to that.

2021-07-02 10:54 UTC, caalador commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
> +    fs.writeFileSync(path.resolve(options.frontendGeneratedFolder, themeName + '.generated.js'), themeFile);
Did the renaming to match master

2021-07-06 06:57 UTC, pleku approved these changes

2021-07-06 06:59 UTC, pleku commented
Intentionally not picking this to 2.6 to reduce regression risks.

2021-07-06 09:56 UTC, pleku approved these changes

2021-07-06 09:56 UTC, merged