fix: extract validation error handler from Binder
vaadin/flow pull request #11384
Opened 2021-07-06 11:56 UTC by denis-anisimov

part of #10598, replacement for #10683

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-07-08 11:50 UTC, pleku requested changes
I feel like we should also check/test whether this causes any UX changes to the components.
Also adding documentation to the binder chapter would be good too, but can be done later.

2021-07-08 11:50 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/binder/DefaultBinderValidationErrorHandler.java
> + * the {@link ValidationResult} instance is applied.
Please give an example of what the theme name would be, e.g. 
> For example, for `ErrorLevel.WARNING` the element will get the `"theme"="warning"` attribute and value in HTML.

2021-07-08 11:50 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/binder/BinderValidationErrorHandler.java
> +     * given field.
Could add a mention that "See #clearError for clearing the error."

2021-07-08 11:50 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/binder/BinderValidationErrorHandler.java
> +     * Clears the error condition of the given field, if any.
```suggestion
     * Clears the error condition of the given field, if one has been
     * previously set with {@link #handleError}.
```

2021-07-08 11:50 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/binder/BinderValidationErrorHandler.java
> +     *            the field with an invalid value
```suggestion
     *            the field to clear the previous error from
```

2021-07-08 11:50 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/binder/BinderValidationErrorHandler.java
> +public interface BinderValidationErrorHandler extends Serializable {
### API review comment/speculation:

An alternative would have been to make this a functional interface so a lambda could have been used.
For example:
```java
binder.setValidationErrorHandler(field, result -> {
    if (result.isError()) {
        ...
    } else { // OK
        ... 
    }
});
```
But to be honest, when I think about this, one would probably make a reusable class for this and use it for all `Binder`s in their application. Or extend and create their own `MyBinder` that changes is explicitly. And now the default implementation can be customized quite easily if required as it protected API.

So I'm OK with the taken approach here by Denis. Do you have any strong opinion on this @knoobie, would the suggested approach work for you ?

2021-07-08 11:50 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +     * Sets the validation error handler to update error status for fields.
```suggestion
     * Sets the validation error handler to update error status for fields
     * when the user input is validated.
```

2021-07-08 12:00 UTC, knoobie commented on flow-data/src/main/java/com/vaadin/flow/data/binder/BinderValidationErrorHandler.java
> +public interface BinderValidationErrorHandler extends Serializable {
We already have a custom `_ProductName_Binder` class that extends `Binder` because of some internal helper methods we have added for i18n. 

I would personally prefer the current implementation over functional interface style. People familiar with the binder concept already know both names `handleError` and `clearError` as both are already available as `protected` methods. So the whole `ValidationErrorHandler` is just a nice abstraction on top - "No new concept to learn". :)

2021-07-08 12:09 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/binder/BinderValidationErrorHandler.java
> +public interface BinderValidationErrorHandler extends Serializable {
Thanks for the input, lets go with this.

2021-07-09 06:58 UTC, denis-anisimov commented on flow-data/src/main/java/com/vaadin/flow/data/binder/BinderValidationErrorHandler.java
> +     * given field.
done

2021-07-09 07:00 UTC, denis-anisimov commented on flow-data/src/main/java/com/vaadin/flow/data/binder/DefaultBinderValidationErrorHandler.java
> + * the {@link ValidationResult} instance is applied.
done

2021-07-13 18:30 UTC, pleku approved these changes
Tested that the UX has not changed for the components. In my opinion, this can be added to 8.0 and 2.7 directly as it basically retains existing behavior and makes it just more customizable. The added part is applying the HTML attribute e.g. `"theme"="warning"`.
And I think it is safe for the LTS version too as the added API is
1) In `Binder` very straight forward
2) In CSS it is based on `theme` attribute and the `ErrorLevel` from Java which has been as-is since Vaadin 8.0 and not likely to change.

(FYI @Artur- )

2021-07-13 18:31 UTC, pleku commented
Can be tested with eg. 
```java
@Route("binder-test")
public class BinderErrorLevelTest extends VerticalLayout {

    private class Bean {
        private String email;

        public String getEmail() {
            return email;
        }

        public void setEmail(String email) {
            this.email = email;
        }
    }

    private final TextField field;

    public BinderErrorLevelTest() {
        field = new TextField("empty:system, < 2 critical, < 4 error, < 6 warning, < 8 info");
        field.setValueChangeMode(ValueChangeMode.EAGER);
        field.setWidthFull();
        final Binder<Bean> binder = new Binder<>(Bean.class);
        binder.forField(field).withValidator((value, context) -> {
            if (value == null || value.length() == 0) {
                return ValidationResult.create("system", ErrorLevel.SYSTEM);
            }
            if (value.length() < 2) {
                return ValidationResult.create("critical", ErrorLevel.CRITICAL);
            } else if (value.length() < 4) {
                return ValidationResult.create("error", ErrorLevel.ERROR);
            } else if (value.length() < 6) {
                return ValidationResult.create("warning", ErrorLevel.WARNING);
            } else if (value.length() < 8) {
                return ValidationResult.create("info", ErrorLevel.INFO);
            }
            return ValidationResult.ok();
        }).bind("email");

        add(field);
    }
}
```

2021-07-13 18:32 UTC, merged