Add a single file to import endpoints
vaadin/flow pull request #11401
Opened 2021-07-09 09:14 UTC by Lodin

Resolves vaadin/fusion#32

2021-07-09 11:43 UTC, Lodin commented on fusion-endpoint/src/main/java/com/vaadin/fusion/generator/ConnectClientGenerator.java
> +        outputFilePath = Paths.get(outputDirectory.toAbsolutePath().toString(),
@sonatype-lift help

2021-07-18 06:11 UTC, manolo requested changes

2021-07-18 06:11 UTC, manolo commented on fusion-endpoint/src/main/java/com/vaadin/fusion/frontend/TaskGenerateConnectImpl.java
>  public class TaskGenerateConnectImpl extends AbstractTaskConnectGenerator
It might be replace Connect with Fussion. Connect was the legacy name of the project. Not a blocker

2021-07-18 06:11 UTC, manolo commented on fusion-endpoint/src/main/java/com/vaadin/fusion/generator/BarrelGenerator.java
> +class BarrelGenerator {
Didn't know this Barrel concept in Ts until reading this file. It might be worth to explain a little bit what is it in the class jdoc.

2021-07-18 06:11 UTC, manolo commented on fusion-endpoint/src/main/java/com/vaadin/fusion/generator/ConnectClientGenerator.java
> +public class ConnectClientGenerator {
Isnt this the fusion api file ? I'm a bit confused with names and explanations here

2021-07-18 06:11 UTC, manolo commented on fusion-endpoint/src/main/java/com/vaadin/fusion/generator/Generator.java
> +    public Generator(File openApiJsonFile, File outputDirectory) {
Just Generator is quite generic name for this class. It might be a better description at least in the doc, saing that this is the main generator that runs others. A good name for this might be FusionGenerator or MainGenerator ?

2021-07-18 06:11 UTC, manolo commented on fusion-endpoint/src/main/java/com/vaadin/fusion/generator/GeneratorDirectory.java
> +class GeneratorDirectory {
Others generators have the Generator verb at the end of the name, I think this should be named DirectoryGenerator or FolderGenerator

2021-07-18 06:11 UTC, manolo commented on fusion-endpoint/src/test/java/com/vaadin/fusion/generator/openapi/OpenApiSpecBasedTests.java
>  public class OpenApiSpecBasedTests {
Why is this class in plural?

2021-07-19 14:26 UTC, Lodin commented on fusion-endpoint/src/main/java/com/vaadin/fusion/generator/GeneratorDirectory.java
> +class GeneratorDirectory {
The idea was that it is a wrapper for a directory that belongs to a generator

2021-07-19 14:33 UTC, Lodin commented on fusion-endpoint/src/main/java/com/vaadin/fusion/generator/ConnectClientGenerator.java
> +public class ConnectClientGenerator {
Well, I just removed `Vaadin` part from the name of that class. However, you're right, I just have to use Fusion name here.

2021-07-20 15:05 UTC, Lodin commented on fusion-endpoint/src/main/java/com/vaadin/fusion/generator/ClientAPIGenerator.java
> +        Path endpointPrefixPath = Paths.get(endpointPrefix).normalize();
@sonatype-lift ignore

2021-07-21 09:59 UTC, manolo approved these changes

2021-07-21 10:02 UTC, merged