fix: don't override web.xml, annotation config with classpath flow-build-info.json settings
vaadin/flow pull request #11482
Opened 2021-07-27 18:04 UTC by rudiejd

## Description

flow-server was overriding parameters set in web.xml/annotations with those found in *any flow-build-info.json* on the classpath. Now it only overrides parameters which weren't already set. Fixes #11479.

## Type of change

- [X] Bugfix
- [ ] Feature

## Checklist
- [ X] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ X] I have added a description following the guideline.
- [ X] The issue is created in the corresponding repository and I have referenced it.
- [ X] I have added tests to ensure my change is effective and works as intended.
- [ X] New and existing tests are passing locally with my change.
- [ X] I have performed self-review and corrected misspellings.

2021-07-27 18:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=11482) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=11482) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=11482) it.</sub>

2021-07-28 05:56 UTC, denis-anisimov requested changes

2021-07-28 05:56 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
> +            for (Map.Entry<String, String> e : properties.entrySet()) {
Don't use one letter variable.
`entry` instead of `e` would be better here.

2021-07-28 05:56 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
> +    public void createInitParameters_valuesFromTokenAreIgnored_valuesAreTakenFromservletConfig()
`valuesFromTokenAreIgnored`:
the second part of the name is usually precondition.
So it should say that properties are provided via init parameters and token file at the same time.
And the last part is a result : `valuesFromTokenFileOverridenByInitParams` e.g.

2021-07-28 05:56 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
> +                config.getConfigParameter(SERVLET_PARAMETER_PRODUCTION_MODE))
That checks only one parameter.
 Don't know how hard it is but would be better to check every init parameter.
I think the values has only  two types: boolean and String.

So it should be possible to make to arrays of properties and go through these arrays and do the check

2021-07-28 13:29 UTC, rudiejd commented on flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
> +                config.getConfigParameter(SERVLET_PARAMETER_PRODUCTION_MODE))
I added another boolean parameter, and added a string parameter so we can capture both types. I also added a parameter that isn't overridden by the servlet config.

2021-07-28 13:41 UTC, rudiejd commented on flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
> +                config.getConfigParameter(SERVLET_PARAMETER_PRODUCTION_MODE))
should I do *all* init parameters? wasn't sure whether that is necessary since the behavior is the same

2021-07-29 05:50 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
> +                config.getConfigParameter(SERVLET_PARAMETER_PRODUCTION_MODE))
I would recommend to do it for all init parameters, yes.
It might be that the code may be modified so it works properly for most of parameters but is broken for one.

What I suggest is : split parameter names into two complementary set . One set contains parameters whose type is String and another with boolean type.
`InitParameters` class can be used to get all parameter names via reflection.
Then just use a couple of unit test methods: go through all the parameters and make a check.

2021-07-29 15:24 UTC, rudiejd commented on flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
> +                config.getConfigParameter(SERVLET_PARAMETER_PRODUCTION_MODE))
okay, I think I'll just be hardcoding a set of string parameters (not sure how else to tell if value is a string, can't use getAssignableType or anything) and getting the boolean ones through reflection, then making assertions for each

2021-07-30 05:56 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
> +                    .get(new InitParameters());
The field is static so there is no need to instantiate an object. `null` can be passed as an arg here.
But it's minor.

2021-07-30 06:02 UTC, denis-anisimov requested changes
Since there is an important request: add message to every assertion with a parameter name I would also like to ask to refactor the code to extract cycles which initializes mocks into separate methods to improve readability: the test itself may be very short if it just calls initializer methods.

2021-07-30 16:57 UTC, rudiejd commented
> Since there is an important request: add message to every assertion with a parameter name I would also like to ask to refactor the code to extract cycles which initializes mocks into separate methods to improve readability: the test itself may be very short if it just calls initializer methods.

I have refactored the generation of the token and the mocking into two different private methods. I tried to make them a bit generic to encourage reuse for similar test cases

2021-07-30 17:49 UTC, rudiejd commented
https://teamcity.vaadin.com/viewLog.html?buildId=85356&buildTypeId=Flow_FlowTests
can someone tell me why run validation is failing and/or re run? everything's passing locally

2021-07-30 19:12 UTC, denis-anisimov commented
`flow-client` failed with unknown reason.
I've restarted the build.

2021-07-30 19:38 UTC, rudiejd commented
@denis-anisimov same thing again. the client unit/integration tests run locally though, so i can't figure out if i broke something... it doesn't show any test as failing on teamcity either

2021-08-02 06:22 UTC, denis-anisimov approved these changes

2021-08-02 10:37 UTC, denis-anisimov commented
There were some issues with builds.
Now they should be fixed.
At least `flow-client` validation has passed.

2021-08-02 12:25 UTC, merged