documentation: Add missing throws in JavaDocs
vaadin/flow pull request #11503
Opened 2021-07-30 12:54 UTC by TatuLund

see: https://github.com/vaadin/flow/issues/11502

2021-08-02 06:08 UTC, denis-anisimov requested changes

2021-08-02 06:08 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/router/RouterLink.java
> +     * @throws IllegalArgumentException
`throws IllegalArgumentException` could be added to the constructors to show explicitly that it may be thrown.

Also please add `throws IllegalArgumentException` to  `RouterLink::setRoute`

2021-08-02 08:18 UTC, TatuLund commented on flow-server/src/main/java/com/vaadin/flow/router/RouterLink.java
> +     * @throws IllegalArgumentException
> Also please add throws IllegalArgumentException to RouterLink::setRoute

I did that already

2021-08-02 08:57 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/router/RouterLink.java
> +     * @throws IllegalArgumentException
No.

```
public RouterLink(Router router, String text,
            Class<? extends Component> navigationTarget) throws IllegalArgumentException`

2021-08-16 10:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=11503) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=11503) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=11503) it.</sub>

2021-08-23 11:35 UTC, TatuLund commented on flow-server/src/main/java/com/vaadin/flow/router/RouterLink.java
> +     * @throws IllegalArgumentException
Done

2021-08-23 12:04 UTC, denis-anisimov approved these changes

2021-08-23 12:04 UTC, denis-anisimov commented
Formatter validation fails.
Please apply formatter.

2021-08-23 12:28 UTC, denis-anisimov approved these changes

2021-08-23 12:28 UTC, merged