fix: Fail with a message if user home contains whitespaces
vaadin/flow pull request #11517
Opened 2021-08-04 07:31 UTC by mshabarov

## Description

Checks that the npm version accepts whitespaces in user home path and explains how to fix that otherwise.

Fixes https://github.com/vaadin/flow/issues/10084

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-08-04 09:35 UTC, denis-anisimov requested changes

2021-08-04 09:35 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +    void checkNpmAcceptsWhitespacesInUserHome() {
`throws IllegalStateException`

2021-08-04 09:35 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +    void checkNpmAcceptsWhitespacesInUserHome() {
Why is it user home only ?

2021-08-04 09:35 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
> +                tools.checkNpmAcceptsWhitespacesInUserHome();
Why user home is so specific in this case ?

And quite related question: why tools should be aware of this specific case (if any) ?
User home is just a directory which has no any specific meaning for `FrontendTools`. So the existence of such method is very weird.
 `FrontendTools` may have method  `checkNpmAcceptsWhitespacesInDir` or just `checkNpmAcceptsWhitespaces` and accept a File as a parameter.

2021-08-04 09:35 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
> +                tools.checkNpmAcceptsWhitespacesInUserHome();
Another question: should the method throw or just return a `boolean` ?
I can't answer for sure to this question but it might be that the caller of the method should decide how to handle the case of spaces in the path instead of the callee : the callee  defines only one hardcoded handler but the every caller may decide how to handle this instead only one way.

2021-08-04 09:35 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
> +            System.setProperty(USER_HOME, "C:\\Users\\Windows User");
quite dangerous test since it modifies globally user home and any other test which relies or modifies the same property may fail itself or fail this test.
Though I don't know how make it better.

2021-08-04 09:35 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
> +    public void runNpmInstall_getPnpmExecutable_whitespacesInUserHomeChecked()
`npm` ?
It this test needed at all ?
`TaskRunPnpmInstallTest` extends `TaskRunNpmInstallTest` so it runs all its methods.
If this test should tests _PNPM_ then it should be renamed.

2021-08-04 10:43 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +    void checkNpmAcceptsWhitespacesInUserHome() {
> `throws IllegalStateException`

Not sure I got this comment. Exception description is added to javadoc and methods signature doesn't require it's declaration.

2021-08-04 11:09 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +    void checkNpmAcceptsWhitespacesInUserHome() {
> Why is it user home only ?

Because the original issue description and relevant SO link to npm issue tell about problems exactly with whitespaces in user name (=> user home) reported by developers, see https://github.com/zkat/npx/issues/146.
Npm cache directory is located in app data folder inside user home directory by default, so if user name contains spaces - it fails.
However, you right that the method should take the path as a parameter and check it.
And it's better to check the path to npm cache folder instead of user nome, since the cache folder can be customised and contains whitespaces as well.
Then, the `TaskRunNpmInstall` should call this method and give a path to npm cache directory, provided by `FrontendTools`.

2021-08-04 11:12 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
> +                tools.checkNpmAcceptsWhitespacesInUserHome();
Yes, I agree. I'm going to improve it as follows:
- rename the method to be not connected to user home, but receive the `File` to be checked.
- throw the exception on the `TaskRunNpmInstall`, because it is a caller code and it should decide how to handle this.

2021-08-04 11:14 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
> +            System.setProperty(USER_HOME, "C:\\Users\\Windows User");
I'm going to check npm cache folder instead of user home, it's technically more precise. So, this one won't be needed soon and the npm cache getter can be stubbed then.

2021-08-04 11:14 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
> +    public void runNpmInstall_getPnpmExecutable_whitespacesInUserHomeChecked()
The test method is about PNPM. I'll rename it.

2021-08-04 12:10 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +    void checkNpmAcceptsWhitespacesInUserHome() {
> Exception description is added to javadoc and methods signature doesn't require it's declaration.

Javadocs also are not required for the exception which is `RuntimeException`.
It's optional.
And the last thing which I do when I use a method: read javadocs and almost never check the exceptions in the javadocs.
Ideally there should not be any unchecked exceptions: everything should be checked. Then every such exception has to be declared in the signature.
The reality in our code is different.
But if you mention unchecked exception in the javadocs then it's a good thing to add throws in the method declaration.
Because I will not even be aware of the exception when I use a method: I never read javadocs. But I can check the method signature and see that there is a `throws` and then this may be an indicator that I there are cases when it's thrown and this is the only reason why I can find javadocs description for `throws`.

Shortly : javadocs `throws` is useless without `throws` in the method declaration. Even `throws` in the method declaration for unchecked exception is quite useless since it doesn't force me to do anything about it but at least it may give a hint . Javadocs `throws` doesn't give anything if you are not aware of it.

2021-08-05 19:17 UTC, mshabarov commented
`TaskRunPnpmInstallTest` and `FrontendToolsTest` tests successfully run on Windows agent and shows the message as expected.

2021-08-06 12:12 UTC, denis-anisimov requested changes

2021-08-06 12:12 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +    boolean npmAcceptsWhitespaces(File dirToBeChecked)
The method name is confusing.
I don't see how the parameter is related to the method: it looks like the method doesn't require any parameter.
The method says something about npm and it's not clear how the parameter is used in the context.

2021-08-06 12:12 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +    boolean npmAcceptsWhitespaces(File dirToBeChecked)
By the way : whitespace is just one of possible checks.
There is no reason to have this word in the name.
The method could have name `folderIsAllowedByNpm` or something like this.
The impl may include other checks.

2021-08-06 12:12 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +    private String parseCommandOutput(String output) {
parse ?
What kind of parsing?
This is rather a conversation or just a "normalization"

2021-08-06 12:12 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +        } catch (Exception e) {
Please never catch `Exception` unless there are serious well understood reasons for this.
There are no reasons to catch `Exception` here: only exceptions related to the process execution may be caught.
Everything else indicate a problem in the code which may no be thrown as a `CommandExecutionException`.

2021-08-06 12:12 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
> +            if (enablePnpm) {
So it does matter only when Pnpm is used and the check can be skipped in case of NPM ?

2021-08-06 12:12 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
> +    private static final String USER_HOME = "user.home";
Is this still needed ?

2021-08-06 15:29 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +     * Checks whether it's fine to have a whitespaces in user home path, and, if
Fixed

2021-08-06 15:29 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +    boolean npmAcceptsWhitespaces(File dirToBeChecked)
Renamed to `folderIsAcceptableByNpm`

2021-08-06 15:30 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +    private String parseCommandOutput(String output) {
Yes, it's not a parsing, renamed to `removeLineBreaks`.

2021-08-06 15:33 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +        } catch (Exception e) {
Good comment! I reworked it in a way to handle all the checked exceptions in the caller's code (`TaskRunNpmInstall`), it ignores the whole check if something goes wrong and just logs it.

2021-08-06 15:48 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
> +            if (enablePnpm) {
Yes. The error occurs when `pnpm` is installed via `npx`.

2021-08-06 15:48 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
> +    private static final String USER_HOME = "user.home";
no. Removed

2021-08-09 06:00 UTC, denis-anisimov approved these changes

2021-08-09 06:00 UTC, merged