fix: Prevent deadlock in findOrCreateVaadinSession
vaadin/flow pull request #11520
Opened 2021-08-05 11:44 UTC by TatuLund

It is possible findOrCreateVaadinSession leaves session locked if HTTP session is invalidated in an another thread between lockSession and unlockSession calls. This PR changes the implementation so that this can no longer happen.

This is a cherry pick from: https://github.com/vaadin/framework/pull/12355

See details: https://github.com/vaadin/framework/issues/12352

2021-08-05 12:16 UTC, denis-anisimov requested changes

2021-08-05 12:16 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +        assert ((ReentrantLock) lock)
Is this something with github or you missed the `lock` parameter in the method signature ?

2021-08-05 12:16 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
>      protected void unlockSession(WrappedSession wrappedSession) {
Seems `lock` parameter is missed.
The question is : which version do you target this fix?
Only `master` ?
This won't go into 2.x series ?

Because this is API change technically.

So : is it only for `master`?
If no: then how you are going to deal with API change and why there is no labels for cherry-picks ?

2021-08-05 12:16 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +    protected Lock lockSession(WrappedSession wrappedSession) {
This is also API change (see comments in `unlock`).

2021-08-05 12:18 UTC, denis-anisimov commented
>fix: Prevent deadlock in findOrCreateVaadinSession


Strictly speaking you are not preventing any deadlock. Deadlock happens when two mutexes are acquired in a different order and two threads may not proceed because they are waiting each other.

Here the mutex is not released in the thread which acquired it.

2021-08-05 12:38 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +    protected void unlockSession(WrappedSession wrappedSession, Lock lock) {
Another question: is `wrappedSession` argument needed here ?
The implementation doesn't need it. 
Do you have a cases when this parameter can be needed ?
Shouldn't it be just removed ?

2021-08-05 12:40 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +        assert ((ReentrantLock) lock)
Please don't "Resolve" the comment by yourself.
You should just answer somehow that this is done.

It's the question/comment maker who should "Resolve" the comment,

2021-08-05 12:50 UTC, TatuLund commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +    protected void unlockSession(WrappedSession wrappedSession, Lock lock) {
With Leif we came to conclusion that if for some unlikely reason someone has overriden the method, it is good to offer this partial backwards compatibility.

2021-08-05 12:57 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +    protected void unlockSession(WrappedSession wrappedSession, Lock lock) {
The method has to be implemented anyhow since it's a new one.
So it's not backward compatible.
But if there is a vanishing chance that in the overriden method `wrappedSession` is used for something else than just getting the attribute the new signature will help to preserve the impl.
So OK.

2021-08-05 17:11 UTC, TatuLund commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
>      protected void unlockSession(WrappedSession wrappedSession) {
Fixed

2021-08-05 17:12 UTC, TatuLund commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +    protected Lock lockSession(WrappedSession wrappedSession) {
Yes, as mentioned in comments.

2021-08-06 06:11 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +    protected Lock lockSession(WrappedSession wrappedSession) {
API change makes this impossible to cherry-pick this fix into 2.x series.
That was the point of the comment.

It's fine for this PR in the `master` branch.

2021-08-06 06:12 UTC, denis-anisimov approved these changes

2021-08-06 06:12 UTC, merged