fix: pin platform trans. deps with npm CP: #10864
vaadin/flow pull request #11567
Opened 2021-08-12 13:05 UTC by pleku

Uses the same vaadin_versions.json file based pinning as with pnpm.
In case the application has @NpmPackage annotation with a certain version,
then that is used over the platform pinned version. When that is older,
a warning is logged (like with pnpm).
In case a dependency has been pinned directly in package.json, then that
is used over the platform pinned version. When that is older, a warning
is logged (like with pnpm).

Fixes #10572

2021-08-13 06:40 UTC, caalador requested changes

2021-08-13 06:40 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +            packageJson.put(DEV_DEPENDENCIES, Json.createObject());
This isn't needed as there is the `addDefaultObjects(packageJson)` right after this `if` clause.
There were other cases that were missing the default objects so they are checked each time.

2021-08-13 06:40 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
> +            .spy(LoggerFactory.getLogger(NodeUpdater.class));
logger that is not used anywhere?

2021-08-16 10:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=11567) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=11567) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=11567) it.</sub>

2021-08-17 07:49 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +            packageJson.put(DEV_DEPENDENCIES, Json.createObject());
done

2021-08-17 07:49 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
> +            .spy(LoggerFactory.getLogger(NodeUpdater.class));
Done

2021-08-17 07:54 UTC, caalador approved these changes

2021-08-17 11:40 UTC, merged