fix: avoid setting null href and handle removeHref for disabled Anchor
vaadin/flow pull request #11578
Opened 2021-08-16 09:35 UTC by denis-anisimov

fixes #11571

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-08-16 09:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=11578) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=11578) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=11578) it.</sub>

2021-08-23 09:41 UTC, pleku requested changes
I'm not happy with the original design done in #10924 nor the missing javadocs updates of due to the behavior. I would propose a change in the behavior completely

2021-08-23 09:41 UTC, pleku commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
>      /**
I think the `setHref` javadocs should be updated to the fact that when the anchor is inside a disabled component container, the `href` is hidden and the anchor cannot be interacted with.

Also to me the following is odd design:
```java
Anchor anchor = new Anchor("google.com", "google");
anchor.setEnabled(false); // <-- hides href

anchor.setHref("vaadin.com"); // <-- href comes visible again ...
```
I would instead think that all `setHref`, `removeHref` and `getHref` (#11260) can be called whenever the anchor is disabled, but the changes are not applied to the client/DOM until it is enabled again. And this should be clarified in javadocs for both `setEnabled` and `setHref`.

2021-08-23 10:17 UTC, denis-anisimov commented
I don't see how any of comments are related to the PR which is going to fix #11571.
This PR is not aiming to fix any design issues done in #10924 (it's not clear why the ticket was ready to do if the design is not confirmed).

This PR fixes #11571 and makes remove href behavoir consistent to update href functionality. It doesn't do anything else.

So only two actions can be done _here_:
- ?correct? and merge this PR as a fix for #11571 . Then may be create other tickets to correct unrelated things.
- close this PR since the whole functionality is originally poorly designed and it has no sense to fix #11571. Instead fix for  #10924 should be just reverted .

I'm totally fine with any approach. I also don't like design in #10924 but since the design looked accepted in the ticket I implemented it as described.

2021-08-24 05:35 UTC, pleku commented
> I'm totally fine with any approach. I also don't like design in #10924 but since the design looked accepted in the ticket I implemented it as described.

I don't see any/much design done in the issue itself, other than just what is the behavior of the element in the browser. The Java API has been left for "implementation and review to decide" but in my opinion it was not considered. I'm OK for closing this and making a revert for the original PR or just fixing it directly. Noting @miguelatvaadin as he was the original PR reviewer.

2021-08-24 05:53 UTC, closed without merging

2021-08-24 08:05 UTC, mstahv commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
>      /**
I agree with Pekka that this is how it should work. Updating href while anchor is disabled should work fine, but the new value should end up in the dom only after it is enabled.

2021-08-24 08:36 UTC, denis-anisimov commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
>      /**
I kind of agree with this too except I don't see a proper way to implement this.

I insist on the fact of synchronization of Component API and Element API.
So the resulting design of the original ticket should clarify the question of synchronization.

1. Question: Anchor.setEnabled(false); Anchor:setHref("foo"). What happens with Anhcor::getHref and with Anchor::getElement::getAttribute("href");
2. Question Anchor.setEnabled(false), Anchor::getElement::setAttribute("href", "bar"); What happens with Anchor::getHref ?
3.  Question Anchor.setEnabled(false), Anchor::getElement::setAttribute("href", "bar");  What happens with Anhcor::getHref  and  Anchor::getElement::getAttribute("href");  _AFTER_  Anchor.setEnabled(true) ?
4.  Question: Anchor.setEnabled(false) . What do return Anhcor::getHref and Anchor::getElement::getAttribute("href"); ?

Since there is no way to synchronize Component and Element API I don't see how the original ticket may be done.
To be able to disable "href" attribute on the client side ONLY this required dramatic changes in the generic StateNode low level API and client side which is too much for such a small enhancement.

That's why I don't want to take responsibility of any decision made here and don't want to participate in design : there is no way to make it based on current StateNode API properly.