feat: Support Pageable, Page and UUID in endpoints
vaadin/flow pull request #11648
Opened 2021-08-25 14:11 UTC by Artur-

Fixes https://github.com/vaadin/flow/issues/10207
Fixes https://github.com/vaadin/fusion/issues/18
Fixes https://github.com/vaadin/fusion/issues/17

2021-08-30 19:55 UTC, haijian-vaadin requested changes

2021-08-30 19:55 UTC, haijian-vaadin commented on fusion-endpoint/src/test/java/com/vaadin/fusion/endpointransfermapper/EndpointTransferMapperTest.java
> +        // Assert.assertEquals(PageableDTO.class,
should these be removed or uncommented?

2021-08-30 19:55 UTC, haijian-vaadin commented on fusion-endpoint/src/test/java/com/vaadin/fusion/generator/endpoints/AbstractEndpointGenerationTest.java
> +                }
maybe better to extract to a separate function?

2021-08-31 05:08 UTC, Artur- commented on fusion-endpoint/src/test/java/com/vaadin/fusion/generator/endpoints/AbstractEndpointGenerationTest.java
> +                }
Done

2021-08-31 05:08 UTC, Artur- commented on fusion-endpoint/src/test/java/com/vaadin/fusion/endpointransfermapper/EndpointTransferMapperTest.java
> +        // Assert.assertEquals(PageableDTO.class,
Uncommented, done

2021-08-31 06:15 UTC, haijian-vaadin approved these changes

2021-08-31 08:23 UTC, merged