fix: Update current UI instance upon locale change
vaadin/flow pull request #11725
Opened 2021-09-02 06:19 UTC by mshabarov

## Description

Sets the UI on which the locale is being changed as a current UI for the thread.

Fixes #11599

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-09-02 06:26 UTC, Legioth commented on flow-server/src/main/java/com/vaadin/flow/component/UI.java
> +        if (component.getUI().isPresent() && component.getUI().get() != this) {
Doesn't seem to have any relationship with "Update current UI instance upon locale change"

2021-09-02 06:28 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/component/UI.java
> +        if (component.getUI().isPresent() && component.getUI().get() != this) {
Well, this can be extracted into another PR

2021-09-02 07:05 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/component/UI.java
> +        if (component.getUI().isPresent() && component.getUI().get() != this) {
Done

2021-09-06 11:17 UTC, denis-anisimov requested changes

2021-09-06 11:17 UTC, denis-anisimov commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LocaleChangeView.java
> +            session.lock();
Is it needed ?
Every Flow listener should be called under the session lock arelady.

2021-09-06 11:17 UTC, denis-anisimov commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LocaleChangeView.java
> +            session.lock();
Again: is this needed?

2021-09-06 11:48 UTC, mshabarov commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LocaleChangeView.java
> +            session.lock();
Yeah, it's not needed. `VaadinSession::setLocale` checks that it already has a lock.

2021-09-06 11:53 UTC, mshabarov commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LocaleChangeView.java
> +            session.lock();
Done

2021-09-06 11:53 UTC, mshabarov commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LocaleChangeView.java
> +            session.lock();
No.
Done.

2021-09-06 14:10 UTC, denis-anisimov approved these changes

2021-09-07 12:18 UTC, merged