chore: Upgrade webpack-dev-server to 4.0.0+
vaadin/flow pull request #11783
Opened 2021-09-07 11:45 UTC by fluorumlabs

## Description

Flow/Fusion currently uses webpack-dev-server 3.11.0, which depends on chokidar 2.x. According to sources, chokidar 2.x breaks/doesn't work properly on node 14+. Besides, this version of chokidar brings glob-parent with known vulnerability (https://nvd.nist.gov/vuln/detail/CVE-2020-28469), which is getting reported by Software Composition Analysis tools.
Fixes #11762

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-09-07 12:08 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +        defaults.put("webpack-dev-server", "4.10.0");
4.1.1 is the lastest https://github.com/webpack/webpack-dev-server/releases/tag/v4.1.1 ?

2021-09-07 12:12 UTC, Artur- commented
Have you tested this manually? I can't remember if the compilation error/warning dialog in the webpack5 branch comes from webpack 5 or the new dev server

2021-09-07 12:12 UTC, fluorumlabs commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +        defaults.put("webpack-dev-server", "4.10.0");
🤦🏻 4.1.0 is the latest at https://www.npmjs.com/package/webpack-dev-server at the moment of writing

2021-09-07 12:13 UTC, fluorumlabs commented
I haven't :) Let the validation validate first

2021-09-07 12:13 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +        defaults.put("webpack-dev-server", "4.10.0");
4.1.1 has a CVE fix

2021-09-07 12:20 UTC, fluorumlabs commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +        defaults.put("webpack-dev-server", "4.10.0");
(published 22 minutes ago)

2021-09-07 12:24 UTC, fluorumlabs commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +        defaults.put("webpack-dev-server", "4.10.0");
`ansi-html` is also used in `webpack-dev-server` 3.x

CVE is ReDoS: https://github.com/advisories/GHSA-whgm-jr23-g3j9

2021-09-07 13:07 UTC, Artur- commented
```
------------------ Starting Frontend compilation. ------------------
The command moved into a separate package: @webpack-cli/serve
Would you like to install serve? (That will run npm install -D @webpack-cli/serve) (yes/NO) : 
```

2021-09-08 05:49 UTC, fluorumlabs commented
The `webpack-cli` message above is caused by me forgetting to bump webpack-cli...

However, I'm pretty much stuck in many places (due to the lack of knowledge of webpack):
- wds4 doesn't print usable markers when compilation is successful/unsuccessful (apart from `ERROR in .*`
- Not sure about the client configuration. I suspect we need `client: false` or `--no-client` argument, but not sure about implications
- I have disabled HMR (which is on by default), because `contenthash` can't be used with HMR. `customElement` registration won't work with HMR (probably) anyway

2021-09-15 10:12 UTC, platosha commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerImpl.java
> +        if (!failed) {
`cumulativeOutput` is used below to populate `failedOutput`. Would `failedOutput` always be empty now?

2021-09-15 10:19 UTC, fluorumlabs commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerImpl.java
> +        if (!failed) {
No, this change will prevent from `: Failed to compile.` line to appear there: if there were any errors, they will be there in `failedOutput`, but not this last line as it's redundant and doesn't look well in error box shown in the application

2021-09-15 18:26 UTC, platosha requested changes

2021-09-15 18:26 UTC, platosha commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerImpl.java
> +                        "--devtool=eval")
```suggestion
                        "--devtool=eval-source-map")
```

"eval" alone does not allow to see original code in the developer tools when debugging, which makes debugging in the browser harder. In practice, with this option I was unable to navigate to the `my-view.ts` file in the debugger, because it was merged with other files into a single source listing. 

The prior `-d` flag was documented as:
```
  -d           shortcut for --debug --devtool eval-cheap-module-source-map
               --output-pathinfo                                       [boolean]
```

The closest option [from this list](https://v4.webpack.js.org/configuration/devtool/#devtool) is "cheap-module-eval-source-map". "eval-source-map" is a bit slower, but includes a more detailed mapping.

2021-09-17 06:31 UTC, haijian-vaadin commented
Needs a rebase from master to pass the validation.

2021-09-17 10:21 UTC, platosha approved these changes

2021-09-17 10:22 UTC, merged