chore: update outdated javadoc in AppShellSettings
vaadin/flow pull request #11800
Opened 2021-09-09 11:00 UTC by haijian-vaadin

## Description

There are outdated javadoc for some methods on `AppShellSettings`, which depends on an `UI` instance that is not available for client-side bootstrapping, marked those as deprecated to not confuse users.

Fixes https://github.com/vaadin/fusion/issues/60

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-09-09 11:35 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/AppShellSettings.java
>      public Optional<LoadingIndicatorConfiguration> getLoadingIndicatorConfiguration() {
To communicate the deprecation `@Deprecated` could be added.

2021-09-09 11:40 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/AppShellSettings.java
>      public Optional<LoadingIndicatorConfiguration> getLoadingIndicatorConfiguration() {
right, thanks for the catch, only added to the comment, forgot to add it to the method as well, now fixed.

2021-09-09 14:17 UTC, platosha approved these changes

2021-09-10 11:00 UTC, pleku requested changes

2021-09-10 11:00 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/AppShellSettings.java
> +     *             server-side views.
Same as above

2021-09-10 11:16 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/AppShellSettings.java
> +     *             server-side views.
Yes, good point, throwing an unsupported exception sounds better.

2021-09-13 06:31 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/AppShellSettings.java
> +     *             server-side views.
now updated the code to throw an unsupported exception, can you help to take another look?

2021-09-15 06:30 UTC, pleku reviewed
Would it be big effort to drop in unit tests that validate the behavior ? If it is just a few lines to an existing test, I would go for it

2021-09-15 08:10 UTC, pleku approved these changes

2021-09-15 08:10 UTC, pleku commented
Needs a rebase from master due to the client dependency update breaking gwt-compilation

2021-09-15 09:13 UTC, merged