Downgrade to swagger-codegen-generators 1.0.20
vaadin/flow pull request #11812
Opened 2021-09-10 11:53 UTC by Artur-

Fixes #11806

2021-09-10 11:58 UTC, fluorumlabs requested changes

2021-09-10 11:58 UTC, fluorumlabs commented on fusion-endpoint/pom.xml
>          <swagger.codegen.version>3.0.27</swagger.codegen.version>
`swagger.codegen` and `swagger.codegen.generators` patch versions should probably go in sync. Swagger do not strictly follow semver, so there are elevated chances to have issues.

```suggestion
        <swagger.codegen.version>3.0.20</swagger.codegen.version>
```

2021-09-10 13:27 UTC, haijian-vaadin approved these changes

2021-09-10 13:31 UTC, haijian-vaadin requested changes
Seems there are more changes in https://github.com/vaadin/flow/pull/11743, should we just revert that commit/pr instead?

2021-09-10 13:34 UTC, fluorumlabs commented
Only reverting swagger version bump is enough

2021-09-10 15:38 UTC, haijian-vaadin approved these changes

2021-09-13 06:08 UTC, fluorumlabs approved these changes

2021-09-13 06:27 UTC, merged