fix: Use pinned supported pnpm version by default
vaadin/flow pull request #11859
Opened 2021-09-15 10:33 UTC by mshabarov

## Description

Introduces a new configuration parameter `pnpm.global` enabling the globally installed pnpm to be used for frontend packages installation.
By default, this parameter is `false` and the pinned supported version of pnpm tool is used: `npx --yes --quiet --ignore-existing pnpm@5.18.10 install`. No version check needed, because the version is pinned.
Once the `pnpm.global` is set to `true`, then the global pnpm is being looked for via `where/which`. If not found, or it's version is too old, the exception is thrown.

Fixes #11730

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-09-17 10:19 UTC, caalador requested changes

2021-09-17 10:19 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
> +                "Found too old globally installed 'pnpm'. Please upgrade 'pnpm' to at least 5.0.0"));
ExpectedException rule is basically deprecated and using `Assert.assertThrows` is preferred.

2021-09-17 10:19 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
> +            tools.getSuitablePnpm();
```suggestion
            IllegalStateException e = Assert.assertThrows(
                IllegalStateException.class, () -> tools.getSuitablePnpm());

            Assert.assertTrue("unexpected content in message '"+e.getMessage()+"'", e.getMessage().contains("Found too old globally installed 'pnpm'. Please upgrade 'pnpm' to at least 5.0.0"));
```

2021-09-17 14:16 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
> +            tools.getSuitablePnpm();
Done

2021-09-17 14:16 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
> +                "Found too old globally installed 'pnpm'. Please upgrade 'pnpm' to at least 5.0.0"));
Done

2021-09-20 05:26 UTC, caalador approved these changes

2021-09-20 05:28 UTC, merged