fix: upgrade to lit 2.0.0
vaadin/flow pull request #11898
Opened 2021-09-21 05:48 UTC by Artur-

2021-09-21 09:49 UTC, Haprog submitted a review, later dismissed

2021-09-21 10:28 UTC, haijian-vaadin requested changes
why it is fix?
Besides, we need to update the fusion and common frontend package as well, I will get those done and update this PR.

2021-09-21 11:14 UTC, Haprog approved these changes

2021-09-22 06:06 UTC, Haprog commented
The status of "Flow Pull Requests Run Validation (Flow Public)" build seems to be stuck but the build has in fact passed as green. Can we force that to recheck the status somehow? Also I think the change request by @haijian-vaadin is still blocking so I think he needs to approve even though latest changes were from him.

2021-09-22 06:09 UTC, haijian-vaadin commented
> The status of "Flow Pull Requests Run Validation (Flow Public)" build seems to be stuck but the build has in fact passed as green. Can we force that to recheck the status somehow? Also I think the change request by @haijian-vaadin is still blocking so I think he needs to approve even though latest changes were from him.

I blocked the PR on purpose, want to try it out on a starter project manually to see if the `peerdependency` change on the fusion-frontend works on both npm 7 and 6. Will approve it once it's verified.

2021-09-22 09:55 UTC, haijian-vaadin approved these changes

2021-09-22 09:57 UTC, merged