fix: auto register Vaadin servlet even if there is no routes
vaadin/flow pull request #11907
Opened 2021-09-22 09:13 UTC by denis-anisimov

fixes #4850

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-09-27 08:01 UTC, caalador submitted a review, later dismissed

2021-09-27 08:01 UTC, caalador commented
Conflicting files
flow-server/src/test/java/com/vaadin/flow/server/startup/ServletDeployerTest.java

2021-09-27 08:37 UTC, caalador commented
```
/opt/agent/work/a69251da2b2bb9e9/flow-server/src/test/java/com/vaadin/flow/server/startup/ServletDeployerTest.java:[118,37] method getContextEvent in class com.vaadin.flow.server.startup.ServletDeployerTest cannot be applied to given types;
  required: javax.servlet.ServletRegistration[]
  found: boolean,boolean,javax.servlet.ServletRegistration
  reason: varargs mismatch; boolean cannot be converted to javax.servlet.ServletRegistration
```

2021-09-27 10:19 UTC, denis-anisimov commented
done

2021-09-28 04:19 UTC, caalador requested changes

2021-09-28 04:19 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/startup/ServletDeployerTest.java
>      }
Doesn't this now assert that a servlet is registered and not no servlets registered. 
Also the compatibilityMode boolean doesn't do anything in the method so it seems a bit non functional, and makes
`registeredServlets_compatibilityMode_servletsAreNotRegistered` and `registeredServlets_servletsAreNotRegistered` the same test, so I'm not certain what these actually test.

2021-09-28 06:19 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/startup/ServletDeployerTest.java
>      }
Yeah, a number of confusions.

compatibility mode is not checked anymore anyhow. This is a leftover from previous versions where `"frontend"` URL mapping servlet was registered as well.

The test has a precondition with non vaddin servlets and it checks that Vaadin servlet is registered. And previously the precondition was also no routes and no web components , that's why it checked that Vaadin servlet is not registered.
Now it should check that it's registered.
I've changed the names.

2021-09-28 06:22 UTC, caalador approved these changes

2021-09-28 11:30 UTC, merged