fix: Use proper npm/pnpm commands for Windows
vaadin/flow pull request #11905
Opened 2021-09-22 07:25 UTC by mshabarov

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-09-23 06:21 UTC, denis-anisimov requested changes

2021-09-23 06:21 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +                            FrontendUtils.isWindows() ? "pnpm.cmd" : "pnpm")
`NpmCliTool` already contains something similar.
It makes sense to update this class and use it here.

2021-09-23 06:31 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +                            FrontendUtils.isWindows() ? "pnpm.cmd" : "pnpm")
True. But I didn't do that because the name of this enum is `NpmCliTool` and I wasn't sure about pnpm cli.
But okay, this enum can be renamed and extended with pnpm. Will fix.

2021-09-28 13:52 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +                            FrontendUtils.isWindows() ? "pnpm.cmd" : "pnpm")
Done

2021-09-29 05:57 UTC, denis-anisimov requested changes

2021-09-29 05:57 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +            if (script == null) {
Private class....
It's too much for the private class.

I suggest to add `Objects.requireNotNull` in the CTOR and remove this exception from here.

2021-09-29 07:37 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +            if (script == null) {
Adding `Objects.requireNotNull` would means quite different thing.
Pnpm cli javascript file is not applicable, it is not provided (at least it is not provided with the default installation and I didn't find any mentions of this JS file in the docs), so I added `null` into the script parameter. It can be `null` because it is not applicable for pnpm.
Then, If someone tries to get the script for pnpm, it would throw an exception saying that this is not supported.

2021-09-29 07:40 UTC, denis-anisimov approved these changes

2021-09-29 08:20 UTC, denis-anisimov approved these changes

2021-09-29 09:39 UTC, merged