feat: add WhiteSpace setter and getter methods
vaadin/flow pull request #11919
Opened 2021-09-23 12:12 UTC by denis-anisimov

fixes #4577

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-09-24 09:04 UTC, knoobie commented
Personally, I don't really see the need of this addition; it bloats the `HasText` interface and the `getWhiteSpace` does not really give the precise value (somebody would expect; calculated from the browser) instead it returns the value that was given by `set` or a default value that could even be wrong if styled with CSS.

2021-10-01 12:15 UTC, mshabarov commented
> the getWhiteSpace does not really give the precise value (somebody would expect; calculated from the browser) instead it returns the value that was given by set or a default value that could even be wrong if styled with CSS.

If it behaves like this, then maybe better to not add `getWhiteSpace` at all, or describe it's limitation in javadoc.

2021-10-01 12:18 UTC, mshabarov approved these changes
I'm not familiar with the `white-space` CSS properties that much, but the new API look good to me.

2021-10-01 12:18 UTC, mshabarov commented
Added Leif as he was the author of this enhancement.

2021-10-04 08:20 UTC, Legioth commented
The implementation seems to be in line with what I have expected. My only remark is that there's some new API in the enum that is implicitly public that doesn't have javadocs, but that's up to the team do decide what policy you have for such cases.

2021-10-05 05:25 UTC, mshabarov requested changes

2021-10-05 05:25 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/component/HasText.java
> +    enum WhiteSpace {
Add javadoc

2021-10-05 05:49 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/HasText.java
> +    enum WhiteSpace {
done

2021-10-05 05:51 UTC, mshabarov approved these changes

2021-10-05 07:16 UTC, merged