refactor: Use settings object for TaskRunNpmInstall
vaadin/flow pull request #11951
Opened 2021-09-30 05:31 UTC by caalador

Use a settings object with TaskRunNpmInstall
so it is easier to see and controll what settings
are used.

2021-09-30 06:13 UTC, denis-anisimov requested changes

2021-09-30 06:13 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
> +    public static class NpmSettings {
The class contains public setters which allows to modify the object and confuses the contract.
In fact the setters are not needed: they are used only when the object is constructed even though it's 
better to avoid complicated CTOR with a bunch of args and use methods to set the values.
Once the object is constructed if becomes immutable.

`Builder` pattern is used normally for avoiding complicated CTORs. 
So since this should improve the contract of settings I suggest to avoid confusing contract with mutability.
Two options can be used:
- `Builder` pattern which produces an immutable object in the result
- `Builder` requires quite much code so setters still can be used but then they should be `private`. If settings class is moved as nested class inside NodeTasks then it's possible to access it's private methods and fields.

2021-09-30 06:13 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
> +    TaskRunNpmInstall(NpmSettings settings) {
I don't see any point to use separate fields since they are already available in the settings class.
Just assign the settings class as a whole to a field and that's it. Any value can be received from there directly.
Just make the class immutable.

2021-09-30 07:27 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
> +    public static class NpmSettings {
The contract is that you can change the setter and it the setttings are locked in when creating the Task.

2021-09-30 08:05 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
> +    public static class NpmSettings {
The builder which produces an immutable instance allows to do this more properly.
The implementation will be more verbose for the builder but then the fields inside the TaskRunNpmInstall
 are not required : the settings can be used as is since it's immutable.

2021-10-01 11:35 UTC, mshabarov requested changes

2021-10-01 11:35 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
> +    TaskRunNpmInstall(NpmSettings settings) {
Let's deprecate the old CTOR and not remove it.
Never know who uses this API, although it's supposed to be internal API.
FrontendTools is an another example which is used in the start project.

2021-10-01 11:37 UTC, closed without merging