fix: set style property priority using proper API method
vaadin/flow pull request #12019
Opened 2021-10-12 13:30 UTC by denis-anisimov

fixes #11981

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-11-02 15:02 UTC, mshabarov requested changes
@pleku the way how the `important` rule is identified in the input value string looks for me a bit tricky, but I don't know a better solution. The main idea behind, I believe, is to verify that the passed input contains a proper rule by parsing it through the test element and check the result of `element.getStyle().getPropertyPriority(name)`. Unit tests and usage test are in place.
I'm not sure the line 754 is needed, but otherwise LGTM.

2021-11-03 13:58 UTC, pleku commented on flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
> +            styleElement.setProperty(name, value);
Seems like that, unless it is for backup if the following code fails... but then there are other problems like unnecessary CSS updates. Lets see what happens if it is removed.

2021-11-03 13:58 UTC, pleku commented on flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
> +            styleElement.setProperty(name, value);
```suggestion
```

2021-11-03 13:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=12019) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=12019) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: pleku<br/>:x: Denis Anisimov<br/><hr/>**Denis Anisimov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=12019) it.</sub>

2021-11-03 14:06 UTC, mshabarov approved these changes

2021-11-04 07:18 UTC, merged