fix: Avoid processing value change event due writing back of converted value
vaadin/flow pull request #12183
Opened 2021-10-27 11:23 UTC by TatuLund

This is both a optimization by skipping duplicate validation round and avoids ConcurrentModificationExpectation being thrown certain corner cases.

Cherry pick from: vaadin/framework#12360

2021-11-10 15:09 UTC, Artur- commented on flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
> +    private int count;
yes, using e.g. `AtomicInteger`. At the same time, it would make sense to assert the count after each step and not only the total count

2021-11-11 07:09 UTC, anssit requested changes
Please update the test based on review comments.

2021-11-11 08:21 UTC, Artur- submitted a review, later dismissed

2021-11-11 11:05 UTC, anssit approved these changes

2021-11-11 11:25 UTC, merged

2021-11-11 11:57 UTC, anssit commented
Updated the label to `0.0.1` from `1.0.0`. The bot was mistaken because of other changes in target branch.