Lit templates in dev and prod mode
vaadin/flow pull request #12204
Opened 2021-11-01 07:41 UTC by joheriks

Dev mode: load template from devserver:port/VAADIN/template.ts
Prod mode: copy templates to META-INF/VAADIN/config/templates/template.ts.ts

TODO:
- Polymer templates
- Tests

2021-11-01 13:26 UTC, Artur- requested changes
Is there a reason we should not change webpack to work the same way at the same time?

2021-11-01 13:26 UTC, Artur- commented on flow-tests/test-frontend/vite-production/src/main/java/com/vaadin/viteapp/views/template/PolymerComponent.java
> +    public interface Model extends TemplateModel {
nit: A custom model class is not mandatory

2021-11-01 13:26 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/WebpackHandler.java
> +        // Webpack does not provide access to sources by URL, stats.json file
What does this mean? Can't you fetch all frontend source files from the webpack dev server?

2021-11-01 13:26 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/internal/DevModeHandler.java
> +     *            the path to the source file
path relative to what? Should it be named `path` and not `url` if is is a path?

2021-11-01 13:26 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    // Ignore, used only in V14 bootstrap mode
Who should ignore this?

2021-11-01 13:26 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ViteHandler.java
> +        String relativeUrl = url.replaceFirst("^\\./", "");
Is this the correct place to handle `./` prefixes or should it be in the caller?

2021-11-02 07:13 UTC, caalador requested changes

2021-11-02 07:13 UTC, caalador commented on flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImpl.java
>                      source = getSourcesFromStats(service, url);
```suggestion
                if (source == null) {
                  if(FeatureFlags.get(service.getContext()).isEnabled(FeatureFlags.VITE)) {
                    source = getTemplateFromServer(url);
                  } else {
                    source = getSourcesFromStats(service, url);
```
Vite shouldn't try get from stats.

2021-11-02 07:13 UTC, caalador commented on flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
> +            String source;
All the same comments as for Lit

2021-11-02 07:13 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/internal/DevModeHandler.java
> +    InputStream getFileContents(String url) throws IOException;
DevModeHandler doesn't really need this especially if it's not universally supported like it seems now. This should instead be a method in `FrontendUtils` that handles the getting of the file from the devServer.

2021-11-02 22:58 UTC, joheriks commented on flow-tests/test-frontend/vite-production/src/main/java/com/vaadin/viteapp/views/template/PolymerComponent.java
> +    public interface Model extends TemplateModel {
Done.

2021-11-02 22:59 UTC, joheriks commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/WebpackHandler.java
> +        // Webpack does not provide access to sources by URL, stats.json file
Modified `webpack.generated.js` to have the dev server serve files from `./frontend` and fetch them there instead of parsing `stats.json`.

2021-11-02 23:00 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/internal/DevModeHandler.java
> +     *            the path to the source file
Done.

2021-11-02 23:00 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    // Ignore, used only in V14 bootstrap mode
Comment was a note-to-self and not intended to be in the PR, removed.

2021-11-02 23:00 UTC, joheriks commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ViteHandler.java
> +        String relativeUrl = url.replaceFirst("^\\./", "");
Moved to caller.

2021-11-03 07:26 UTC, caalador commented on flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImpl.java
>                  .getResourceAsStream(url);
This should be updated to be OSGi compliant so it should be:
```
ResourceProvider resourceProvider = service.getContext()
        .getAttribute(Lookup.class).lookup(ResourceProvider.class);
URL statsUrl = resourceProvider.getApplicationResource(url);
if (statsUrl != null) {
    try (InputStream stream = statsUrl.openStream()) {
        return FrontendUtils.streamToString(stream);
    }
}
```

2021-11-03 15:48 UTC, joheriks commented on flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImpl.java
> +        }
Created method `getFrontendFileFromDevModeHandler` to retrieve the file. The URL at which the files are served differs between Webpack (`/`) and Vite (`/VAADIN`) so this is returned by `DevModeHandler::getFrontendFilePathPrefix()`.

2021-11-03 15:48 UTC, joheriks commented on flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImpl.java
> +            String url) throws IOException {
Done, moved exception catcher into `getSourcesFromTemplate`.

2021-11-03 15:49 UTC, joheriks commented on flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImpl.java
>                      source = getSourcesFromStats(service, url);
Getting sources from stats now removed for both Webpack and Lit.

2021-11-03 15:49 UTC, joheriks commented on flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
> +            String source;
Done.

2021-11-03 15:49 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/internal/DevModeHandler.java
> +    InputStream getFileContents(String url) throws IOException;
Method moved to `FrontendUtils`. As Webpack and Vite serve the frontend files at different paths, I've added a method `getFrontendFilePathPrefix` to the interface.

2021-11-04 07:42 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFiles.java
> + * are parsed from stats.json.
```suggestion
 * when in production mode.
```
Webpack also now uses the actual files.

2021-11-04 07:42 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFiles.java
> +public class TaskCopyTemplateFiles implements FallibleCommand {
This now ignores possible template files in jars that are now not copied to the correct place. As the expected location of template files is in `config/templates` any jar templates should also be copied to the templates directory.

This task should also get resourcesToScan like `TaskCopyFrontendFiles` that could then be checked if a local file is not found.

2021-11-05 10:49 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFiles.java
> +public class TaskCopyTemplateFiles implements FallibleCommand {
It now copies the files from `flow-frontend`, relying on `TaskCopyFrontendFiles` to have placed all relevant frontend file there. This required a change in the plugin to always copy files regardless of project type (previously they were only copied for jar projects.

2021-11-05 13:35 UTC, joheriks commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
>          // might not be able to read files from jar path.
Fixed, sorry for the leftover. Thanks for spotting.

2021-11-08 06:35 UTC, caalador reviewed
Seems fine as long as the webpack functionality is validated on Bakery or other template heavy application.

2021-11-08 06:35 UTC, caalador commented on flow-server/src/main/resources/webpack.generated.js
>        devServer.app.get(`/stats.json`, function (req, res) {
The stats.json and stats.hash endpoins could be removed as they are not used anymore.

2021-11-08 06:35 UTC, caalador commented on flow-server/src/main/resources/webpack.generated.js
>        devServer.app.get(`/stats.json`, function (req, res) {
Also stats plugin can be removed and only have the generated `stats.json` contain the result from ?`stats.assetsByChunkName` but this cleanup can be in a different ticket that should be created.

2021-11-08 06:35 UTC, caalador commented on flow-tests/test-frontend/vite-production/src/main/java/com/vaadin/viteapp/views/template/TemplateView.java
> +public class TemplateView extends Div {
As the TemplateView and TemplateIT are equal should we have a common package with tests that would be used by both development tests and production tests?
see `flow-tests/test-embedding/embedding-test-assets` and `flow-tests/test-embedding/embedding-test-assets` for reference.

2021-11-08 10:33 UTC, joheriks commented on flow-server/src/main/resources/webpack.generated.js
>        devServer.app.get(`/stats.json`, function (req, res) {
Done. Ticket for the remaining refactoring here: https://github.com/vaadin/flow/issues/12301

2021-11-08 10:33 UTC, joheriks commented on flow-tests/test-frontend/vite-production/src/main/java/com/vaadin/viteapp/views/template/TemplateView.java
> +public class TemplateView extends Div {
Done.

2021-11-08 12:04 UTC, caalador commented on flow-tests/test-frontend/pom.xml
> +        <module>addon-with-templates</module>
```suggestion
        <module>addon-with-templates</module>
        <module>vite-test-assets</module>
```
Copy paste name and wrong order.

2021-11-08 12:13 UTC, joheriks commented on flow-tests/test-frontend/pom.xml
> +        <module>addon-with-templates</module>
😣 , done

2021-11-08 12:31 UTC, joheriks commented
Bakery verified working with this PR snapshot:
|   | Vite  | Webpack |
|--| ---- | --------- |
| Dev  |✅ | ✅
| Prod  |✅  |✅|

2021-11-08 13:54 UTC, caalador approved these changes

2021-11-08 16:19 UTC, Artur- approved these changes

2021-11-08 16:22 UTC, merged