feat: support vite in v14 bootstrap
vaadin/flow pull request #12259
Opened 2021-11-03 10:25 UTC by caalador

Support vite build in the v14 bootstrap
to have exported webcomponents working.

Closes #12057

2021-11-08 09:33 UTC, Artur- commented
Test?

2021-11-08 12:38 UTC, caalador commented
Added tests

2021-11-10 12:33 UTC, joheriks requested changes

2021-11-10 12:33 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +                        .compile("src=\\\"VAADIN\\/build\\/(.*.js)\\\"")
```suggestion
                        .compile("src=\\\"VAADIN\\/build\\/(.*\\.js)\\\"")
```

2021-11-10 12:33 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +                        .compile("href=\\\"VAADIN\\/build\\/(.*.css)\\\"")
```suggestion
                        .compile("href=\\\"VAADIN\\/build\\/(.*\\.css)\\\"")
```

2021-11-10 12:40 UTC, joheriks approved these changes

2021-11-11 07:29 UTC, merged