feat: enable pwa for vite
vaadin/flow pull request #12363
Opened 2021-11-15 11:41 UTC by caalador

Enable pwa installation for vite.
PWA doesn't work in development
mode with this feature.

Part of #12052

2021-11-15 12:26 UTC, Artur- commented on flow-server/src/main/resources/vite.generated.ts
> +            return html.replace('</head>', '<link rel="manifest" href="manifest.webmanifest"></head>');
Return an object instead, see `inject-entrypoint-script`

2021-11-15 12:27 UTC, Artur- commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw-vite.ts
> +importScripts("https://storage.googleapis.com/workbox-cdn/releases/3.6.3/workbox-sw.js");
Does this make all applications load from googleapis.com? We should not do that

2021-11-15 13:17 UTC, caalador commented on flow-server/src/main/resources/vite.generated.ts
> +            return html.replace('</head>', '<link rel="manifest" href="manifest.webmanifest"></head>');
Removed it altogether as noted that if pwa is enabled the link will be added from the server when index html is served.

2021-11-15 13:18 UTC, caalador commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw-vite.ts
> +importScripts("https://storage.googleapis.com/workbox-cdn/releases/3.6.3/workbox-sw.js");
Still trying to figure out how to not need the cdn, but haven't understood how to get the ts file tranpiled by vite so we could use : `import { precacheAndRoute } from 'workbox-precaching'`

2021-11-19 08:20 UTC, Artur- requested changes

2021-11-19 08:20 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateSettingsFile.java
> +    private String getEscapedRelativeWebpackPath(Path path) {
Webpack?

2021-11-19 08:20 UTC, Artur- commented on flow-server/src/main/resources/vite.generated.ts
> +            input: path.resolve(settings.clientServiceWorkerSourceDir, settings.serviceWorkerSource),
Can't we just pass the full path to sw.ts/sw.js in settings and not pass the dir at all?

2021-11-19 08:20 UTC, Artur- commented on flow-server/src/main/resources/vite.generated.ts
> +          const rollup = require('rollup') as typeof Rollup
Please add a comment here about what this is doing. I still have a feeling that this will cause problems at some point and that there is a much better way to do it but cannot say exactly what that way is right now. We can go with this for now but a comment will help in the future if we need to figure out another way

2021-11-19 08:20 UTC, Artur- commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw-vite.ts
> +/// <reference lib="webworker" />
Do we need a separate copy? The only difference seems to be 
```
+declare var OFFLINE_PATH_ENABLED: boolean; // defined by webpack.generated.js
+declare var OFFLINE_PATH: string; // defined by webpack.generated.js
-const offlinePath = OFFLINE_PATH;
+const appShellPath = '.';
+const offlinePath = OFFLINE_PATH_ENABLED ? OFFLINE_PATH : appShellPath;
```

2021-11-19 09:03 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateSettingsFile.java
> +    private String getEscapedRelativeWebpackPath(Path path) {
Renamed

2021-11-19 09:04 UTC, caalador commented on flow-server/src/main/resources/vite.generated.ts
> +            input: path.resolve(settings.clientServiceWorkerSourceDir, settings.serviceWorkerSource),
done

2021-11-19 09:04 UTC, caalador commented on flow-server/src/main/resources/vite.generated.ts
> +          const rollup = require('rollup') as typeof Rollup
done

2021-11-19 09:04 UTC, caalador commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw-vite.ts
> +/// <reference lib="webworker" />
unified

2021-11-19 10:01 UTC, Artur- submitted a review, later dismissed

2021-11-19 10:02 UTC, Artur- commented
Some conflicts remain

2021-11-19 11:14 UTC, Artur- approved these changes

2021-11-22 13:23 UTC, joheriks approved these changes

2021-11-24 14:23 UTC, merged