feat: Add async mode to flush operation and API to turn it own
vaadin/flow pull request #12378
Opened 2021-11-17 08:08 UTC by TatuLund

In async mode data fetching is wrapped in future.

2021-11-17 08:51 UTC, knoobie commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +    ExecutorService executor = Executors.newCachedThreadPool();
What do you think about an method "setAsyncExecutorService"? This is probably needed if there is already a pool for such tasks created by the developer.

2021-11-17 10:18 UTC, TatuLund commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +    ExecutorService executor = Executors.newCachedThreadPool();
Yes, I just modified the solution

2021-11-24 11:56 UTC, pleku requested changes

2021-11-24 11:56 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +    ExecutorService executor = null;
Nit: it should just be private

2021-11-24 11:56 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +        this.executor = executor;
Probably should do something to an old service or at least any pending request-future when for some reason a new executor is set

2021-11-24 11:56 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +    public void setExecutorForAsyncUpdates(ExecutorService executor) {
This should validate via the component->getUI that the push mode is actually enabled, and probably also that it is _automatic_ mode since I'm not sure if this can ever work with manual push mode.

If push is not enabled, then it should IMO throw

2021-11-24 11:56 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +        ui = UI.getCurrent();
Using thread local should be avoided - instead use 
```suggestion
        ui = ((StateTree) stateNode.getOwner()).getUI();
```

2021-11-24 11:56 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +        ui = UI.getCurrent();
Another option would be to create a method that gets the UI but maybe this is even safer in the long run as it always exists here and doesn't exist after `handleDetach` is called

2021-11-24 11:56 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +        ui = null;
I think you need to cancel any pending future here too or things will go wrong if/when it returns
```suggestion
        ui = null;
        if (future != null) {
            future.cancel(true);
            future = null;
        }
```

2021-11-24 11:56 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +        ui = null;
Another question is that should a reference to the executor also be nullified - probably not desired as the grid could be just moved.

Anyway this needs to work so that a shared executor service never has tasks (to execute or to finish) that have references to data communicators that are detached already or its state has been invalidated. Thus you need to cancel the future also from `reset()` method and a few other setters.

2021-11-24 11:56 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +                            activation);
Based on the code, it should be so that a new request cannot change the state in the between as it would make any pending update cause unsync. issues. This is good.

However, this is not strictly enforced in any way in the code - what I'm trying to say is that I think there could be benefits for having
1) some encapsulation for the state of the data communicator update, like `oldActive, effectiveRequested, previousActive, activation` here but in a POJO
2) when the returning future is being processed, it would verify that the state that it expects is still valid - nothing has broken things in the meanwhile

This is maybe slightly overengineering, but I see that in the long run it could help making more maintainable code and not cause regressions if there are some changes done. Not sure if I'm able to explain my concern, but I tried.

2021-11-24 11:56 UTC, pleku commented on flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorAsyncTest.java
> +public class DataCommunicatorAsyncTest {
I would want to see a test, in Flow, where some component is waiting for the job to be executed, and the user refreshes the browser in the middle of that. It plays a bit differently depending on whether `@PreserveOnRefresh` is used or not as the component is / is not thrown away. Something like this would be bound to happen and it should just work, which I'm not sure based on the current implementation that it does (without some changes).

2021-11-24 11:57 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +    ExecutorService executor = Executors.newCachedThreadPool();
The API would be in the component to pass the items and the executor service or just the executor service itself.

2021-12-14 08:43 UTC, TatuLund commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +    ExecutorService executor = null;
Done

2021-12-14 08:43 UTC, TatuLund commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +    public void setExecutorForAsyncUpdates(ExecutorService executor) {
Done

2021-12-14 08:43 UTC, TatuLund commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +        this.executor = executor;
Done

2021-12-14 08:43 UTC, TatuLund commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +        ui = UI.getCurrent();
Done

2021-12-14 08:43 UTC, TatuLund commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +        ui = null;
Done

2021-12-14 08:45 UTC, TatuLund commented on flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorAsyncTest.java
> +public class DataCommunicatorAsyncTest {
Not possible to make this non-flake

2021-12-14 11:22 UTC, TatuLund commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +                ui.access(() -> {
ignore

2021-12-14 11:22 UTC, TatuLund commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +            future.thenAccept(activation -> {
ignore

2021-12-31 10:03 UTC, joheriks requested changes

2021-12-31 10:03 UTC, joheriks commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +            // will perfrom fetch from data provider with given range.
```suggestion
            // will perform fetch from data provider with given range.
```

2022-01-03 09:55 UTC, TatuLund commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +        if (ui.getPushConfiguration().getPushMode() != PushMode.DISABLED) {
Actually I need to move the check from here to elsewhere in order it to work reliably. At this point of time there is some chance that ui is null, but even more so a timing conflict. If you have set Push with annotation, ui.getPushConfiguration().getPushMode() will still return disabled here. I will throw the exception in flush instead. I tested it and seemed to work reliably. Also that provoked the test to fail as there were insufficient mocks. I'll fix that too.

2022-01-03 09:58 UTC, TatuLund commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +        if (ui.getPushConfiguration().getPushMode() != PushMode.DISABLED) {
I will also add unit test for it.

2022-01-03 10:10 UTC, TatuLund commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +     * be enabled in order this to work.
Done

2022-01-03 10:10 UTC, TatuLund commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +                    "Asynchronous DataCommunicator updatres require Push to be enabled and PushMode.AUTOMATIC");
Done

2022-01-03 10:10 UTC, TatuLund commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +            future.cancel(true);
Done

2022-01-03 10:25 UTC, TatuLund commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +     *            The ExecutorService used for async updates.
Done

2022-01-03 10:26 UTC, TatuLund commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +            // will perfrom fetch from data provider with given range.
Done

2022-01-17 20:58 UTC, joheriks commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +            this.executor.shutdown();
Shutting down here would preclude having a single `ExecutorService` thread pool shared among several `DataCommunicator` and potentially other instances. Could this method instance accept an `Executor` instead since `DataCommunicator` only needs to create threads rather than manage the thread pool.

2022-01-17 21:14 UTC, joheriks commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +    public void setExecutorForAsyncUpdates(ExecutorService executor) {
I'd suggest modifying the signature to `enablePushUpdates(Executor executor)` to more clearly inidicate that this method primarily enables the async updates. See next comment for argument type change motivation.

2022-01-18 11:26 UTC, TatuLund commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +            this.executor.shutdown();
Agree, semantically it is better. Done changes.

2022-01-18 11:27 UTC, TatuLund commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +    public void setExecutorForAsyncUpdates(ExecutorService executor) {
Done

2022-01-25 12:22 UTC, joheriks approved these changes

2022-01-25 14:08 UTC, merged