fix: update URL if Vite reload happens during navigation
vaadin/flow pull request #12375
Opened 2021-11-16 15:11 UTC by Artur-

Fixes #12179

2021-11-16 15:11 UTC, Artur- commented
Still needs a test

2021-11-17 11:02 UTC, caalador requested changes

2021-11-17 12:21 UTC, caalador commented
Formatter needs running.

2021-11-17 12:41 UTC, Artur- commented
Formatted, resolved conflicts

2021-11-17 13:05 UTC, caalador approved these changes

2021-11-17 13:36 UTC, merged