New mechanism for usage data collection
vaadin/flow pull request #12381
Opened 2021-11-17 09:03 UTC by samie

Move client-side component usage  statistics collection and data to server-side.

2021-11-25 07:48 UTC, Artur- commented
I will make some cleanup for this

2021-11-25 13:31 UTC, pleku requested changes

2021-11-25 13:31 UTC, pleku commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/DevModeUsageStatistics.java
> +        getLogger().debug("Telemetry " + (enabled ? "enabled" : "disabled"));
Not sure if it would just make sense to log whether the config is explicitly enabled or not in devmode. In production mode, it should just return already earlier (if it even ever gets to this phase).

2021-11-25 13:31 UTC, pleku commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/StatisticsStorage.java
> +     * Updates <code>FIELD_LAST_SENT</code> and <code>FIELD_LAST_STATUS</code>.
Non blocking, but this also updates 
- FIELD_SEND_INTERVAL
- FIELD_SERVER_MESSAGE

2021-11-25 13:31 UTC, pleku commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/StatisticsStorage.java
> +        return json.has(StatisticsConstants.FIELD_SERVER_MESSAGE)
Missing null check, like it was in `getNumberOfProjects`

2021-11-25 14:05 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/DevModeUsageStatistics.java
> +                && config.isUsageStatisticsEnabled());
Changed

2021-11-25 14:05 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/DevModeUsageStatistics.java
> +        getLogger().debug("Telemetry " + (enabled ? "enabled" : "disabled"));
Changed

2021-11-29 08:44 UTC, manolo commented
Is this something that need to  be in v22 ?

2021-11-29 08:44 UTC, Artur- commented
It's a bit late for 22.0.0

2021-11-29 09:11 UTC, Artur- commented
If you have earlier opted out from stats, you have run
```
npm config set @vaadin/vaadin-usage-statistics:disabled true
```

We could check this so that stats are disabled if 
```
npm config get @vaadin/vaadin-usage-statistics:disabled
```
returns `true`

2021-11-29 13:51 UTC, pleku submitted a review, later dismissed

2021-11-29 13:51 UTC, pleku commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/StatisticsStorage.java
> +    private static ObjectNode getProjectData(ObjectNode fullJson,
Nit: `getOrCreateProjectData` would be better so the side effect is easier to understand

2021-11-29 14:13 UTC, pleku approved these changes

2021-11-29 14:17 UTC, merged

2022-01-05 11:59 UTC, knoobie commented
I'm currently trying v23.alpha1 and I get the following in the JS log from a new starter project:

```log
XML Parsing Error: not well-formed  (submit:1:7)
Location: https://tools.vaadin.com/usage-stats/submit
Line Number 1, Column 7: submit:1:7
```

Given URL (https://tools.vaadin.com/usage-stats/submit) returns 400 via browser as well.