test: Clear threadlocals before running tests
vaadin/flow pull request #12385
Opened 2021-11-17 13:30 UTC by Artur-

2021-11-17 14:01 UTC, manolo requested changes

2021-11-17 14:01 UTC, manolo commented on flow-test-generic/src/main/java/com/vaadin/flow/testutil/CurrentInstanceCleaner.java
> +package com.vaadin.flow.testutil;
Failing in CI with error:
```
java.lang.ClassNotFoundException: com.vaadin.flow.testutil.CurrentInstanceCleaner
```
but `flow-server` depends on `flow-test-generic`, that is weird

2021-11-17 14:21 UTC, Artur- commented on flow-test-generic/src/main/java/com/vaadin/flow/testutil/CurrentInstanceCleaner.java
> +package com.vaadin.flow.testutil;
It fails because of `build-tools` which runs tests but does not depend on `flow-test-generic`

2021-11-18 13:49 UTC, Legioth commented
Would it be better to instead explicitly check after each test that it hasn't leaked any of our thread locals? In that way, we could catch situations where framework code accidentally leaks.

2021-11-18 14:41 UTC, manolo commented
platform has already the test for versions https://github.com/vaadin/platform/pull/2549 you can remove `build-tools` module

2021-11-18 17:44 UTC, Artur- commented
> Would it be better to instead explicitly check after each test that it hasn't leaked any of our thread locals
It is not interesting in 99,9% of the tests if it leaks or not. What is interesting it that a test is run without thread locals that potentially breaks it

2021-11-19 07:09 UTC, manolo approved these changes

2021-11-19 07:14 UTC, manolo submitted a review, later dismissed

2021-11-19 09:27 UTC, manolo commented
flow-client does not depend on flow-test-generic, should we include the dependency in the module or remove the listener ?

2021-11-19 11:46 UTC, manolo approved these changes

2021-11-19 11:48 UTC, manolo commented
Now the dnd module

2021-11-19 12:43 UTC, Artur- commented
For `flow-tests` and `flow-plugin-base` it should probably be turned off

2021-11-22 10:06 UTC, manolo approved these changes

2021-11-22 10:37 UTC, joheriks approved these changes

2021-11-22 13:09 UTC, merged