fix: Restrict which files Vite publishes
vaadin/flow pull request #12390
Opened 2021-11-18 07:26 UTC by Artur-

Fixes #12362

2021-11-18 11:06 UTC, caalador approved these changes

2021-11-18 12:11 UTC, caalador commented
The access tests never see that the server would be up and running.
```
13:13:21   ------------------ Starting Frontend compilation. ------------------
13:13:22   
13:13:22   ----------------- Frontend compiled successfully. -----------------
13:13:22   
13:13:29   [INFO] Running com.vaadin.viteapp.BasicsIT
13:13:29   [INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.113 s - in com.vaadin.viteapp.BasicsIT
13:13:29   [INFO] Running com.vaadin.viteapp.FileAccessIT
13:13:29   [ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 5.222 s <<< FAILURE! - in com.vaadin.viteapp.FileAccessIT
13:13:29   [ERROR] mostFoldersNotAccessible(com.vaadin.viteapp.FileAccessIT)  Time elapsed: 5.222 s  <<< ERROR!
13:13:29   java.lang.IllegalStateException: Dev server never finished

```

2021-11-18 19:33 UTC, Artur- commented
Increased the test timeout...

2021-11-18 19:35 UTC, joheriks approved these changes

2021-11-19 05:11 UTC, caalador requested changes

2021-11-19 05:11 UTC, caalador commented on flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/FileAccessIT.java
> +                + fileInProject);
`java.lang.AssertionError: Request for http://localhost:8888/VAADIN/@fsC:\Users\mikae\Code\flow\flow-tests\test-frontend\vite-basics/target/vaadin-dev-server-settings.json should not succeed` seems like it returned the file even though the result is the no route found page

The request should be in the format:
`http://localhost:8888/VAADIN/@fs/C:/Users/mikae/Code/flow/flow-tests/test-frontend/vite-basics/target/vaadin-dev-server-settings.json` to work correctly and get 403 so get fsUrl should take into account windows file path and use `FrontendUtils.getUnixPath` for the file path and check to add a `/` if not exists.

2021-11-19 08:04 UTC, Artur- commented on flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/FileAccessIT.java
> +                + fileInProject);
Does it work on windows now?

2021-11-19 08:16 UTC, caalador commented on flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/FileAccessIT.java
> +        // http://localhost:8888/VAADIN/@fs/C:/Users/mikae/Code/flow/flow-tests/test-frontend/vite-basics/target/vaadin-dev-server-settings.json
```suggestion
        // http://localhost:8888/VAADIN/@fs/C:/Code/flow/flow-tests/test-frontend/vite-basics/target/vaadin-dev-server-settings.json
```

TMI I don't need my paths there. else works now with windows

2021-11-19 08:22 UTC, caalador approved these changes

2021-11-19 09:16 UTC, merged