Make it easier to see the relevant part of InternalServerError
vaadin/flow pull request #12402
Opened 2021-11-19 09:23 UTC by tarekoraby

Fixes #9493

2021-11-19 09:50 UTC, joheriks requested changes

2021-11-19 09:50 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java
> +            isRootCauseAvailable = true;
```suggestion
        String rootCause = getRootCause(parameter);
        boolean isRootCauseAvailable = rootCause != null && !rootCause.isEmpty();
        if (isRootCauseAvailable) {
```

2021-11-19 09:50 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java
> +
I suggest writing this as one method and using iteration rather than (tail) recursion. Secondly, assuming the `availableRecursiveLevels` is there to catch recursive exception (`cause[.getCause()]*==cause`), I think this would be better caught with checking whether the cause in the loop is the original cause. An arbitrary constant like 10 may give an arbitrary root cause in a long recursive exception.

2021-11-19 11:03 UTC, tarekoraby commented on flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java
> +
> I suggest writing the two methods getRootCause and doGetRootCause as one method and using iteration rather than (tail) recursion. 

Sure, we can do that. But what's the advantage of using iteration over recursion? Is it a functional or aesthetic recommendation?

> An arbitrary constant like 10 may give an arbitrary root cause in a long exception chain (such as a stack overflow).

As it's currently implemented, if the arbitrary constraint (say 10) is met, then `getRootCause()` will return `null`, and the implementation will default to the current output from `parameter.hasCustomMessage()`.

2021-11-19 11:07 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java
> +
This looks rather complicated as a whole; there are a  lot of good "find root cause" "algorithmn" out there - you could get some inspiration from e.g. [Spring](https://github.com/spring-projects/spring-framework/blob/main/spring-core/src/main/java/org/springframework/core/NestedExceptionUtils.java) or [Apache](https://github.com/apache/commons-lang/blob/master/src/main/java/org/apache/commons/lang3/exception/ExceptionUtils.java#L232)

2021-11-19 11:40 UTC, tarekoraby commented on flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java
> +
Thanks @knoobie! I pushed a refactoring based on the Spring implementation. 

The whole thing could be simplified even more if `parameter.hasCustomMessage()` is discarded altogether. I'm unsure though if there is any edge case in which the root cause would be unavailable for some reason. Any thoughts?

2021-11-19 11:49 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java
> +
Thanks for considering! Never say never ;) I would probably check for it, just in case somebody refactores the implementation of no route found to be a specific exception without a cause.

2021-11-24 09:49 UTC, joheriks requested changes
In addition to the message addition `"with the root cause"` could we also have an explicit mention in the same string that the full stack trace can be seen in the server log. After this the code also need to be formatted correctly (run `mvn formatter:format` in the `flow` project).

2021-11-24 10:20 UTC, tarekoraby commented
Actually, the full exception will continue to be printed under this `h3` element. So then we will have to say something like "see full stack trace below or in the server logs". 
I slightly prefer not to add this extra note as I feel that the stack trace will not be missed (but I have no super-strong objections if you insist on adding it).

2021-11-24 14:06 UTC, joheriks commented
> Actually, the full exception will continue to be printed under this `h3` element. So then we will have to say something like "see full stack trace below or in the server logs". I slightly prefer not to add this extra note as I feel that the stack trace will not be missed (but I have no super-strong objections if you insist on adding it).

My main worry was that the beginning of the `<pre>` element could be misunderstood as being the stack trace of the root cause (tempting to copy-paste the `<h3>` line + only the first stack trace believing this to be the root cause into a ticket / chat) without some clear identification what is what. But on second thought the `<h3>` plus the gray background of the section serves to delineate them sufficiently, so I would be okay with this.

![Screenshot 2021-11-24 at 15 57 57](https://user-images.githubusercontent.com/2838896/143251980-343f5de4-1a32-4d47-b604-549f9f730eb4.png)

(As a separate ticket/PR, a further DX improvement would be to make the stack trace easily copyable via the lower right-hand gizmo).

2021-11-26 14:37 UTC, joheriks approved these changes

2021-11-26 14:39 UTC, merged