WIP: feat: allow adding true modal dialogs to UI
vaadin/flow pull request #12434
Opened 2021-11-24 09:03 UTC by pleku

Introduces the possibility to add a modal dialog to a UI in a way
that the server side will ignore interaction with all other components
(from client side) until the modal dialog is removed. Modal dialogs can
be stacked on top of each other. This is similar to setting a component disabled,
but is not the same and does not show in the UI in any way - it would be
up to the modal dialog to show a modalityy curtain on top of the outside
UI to the dialog. The feature is thus a server side security feature,
and makes the framework enforce
https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal guidelines.

The implementation relies on a new server side only state tree feature InertData, which
makes it possible to make a component/element/statenode and its children not accept any
updates from client side, but it not the same as disabled. The inert
state is by default inherited to child nodes, except that any child can declare
itself to ignore parent inert state which means that updates are allowed for
itself and its children, unless those are explicitly made inert.

WIP:
- missing bunch of integration tests for trying to break inept UI,
which are TODOs in InertComponentIT
- the public API in the UI should be removed and only entry point would be in UIInternals.
- this also disables all UI level listeners - like UI resize listener, which might not be desirable

Resolves #10172

2021-11-24 11:42 UTC, knoobie commented
Just a note: this could be really awesome for other use cases as well, like blocking the UI while a long running task is enqueued - e.g. pressing a button and ignoring every other client action until the server is done.

2021-11-25 10:43 UTC, pleku commented
> Just a note: this could be really awesome for other use cases as well, like blocking the UI while a long running task is enqueued - e.g. pressing a button and ignoring every other client action until the server is done.

Ok, thanks for the suggestion. I think then I'll retain the API in the `UI` to keep it visible, but I have to think about the naming.
I would think that in those cases - when the UI is blocked - there would be a notification/dialog shown to the user that tells them to wait, and typically that would be something that has a modality-curtain shown too (like `Dialog`).

2021-11-25 11:33 UTC, knoobie commented
Having this API inside the UI would be really good way to discover it! I wanted to mention the other use case because they probably work a little bit different like the dialog use case, as e.g. buttons aren't removed - they just finish they job. I had the following pattern in mind where no additional overlay is added https://github.com/vaadin/web-components/issues/842

Naming is probably the hardest part here - still awesome addition!

2021-11-29 08:38 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/dom/Element.java
> +                PropertyChangeListener listener) {
Faulty formatting change

2021-11-29 08:38 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/communication/ReturnChannelHandler.java
> -
unneeded removal of line

2021-11-29 13:28 UTC, pleku commented
> Having this API inside the UI would be really good way to discover it! I wanted to mention the other use case because they probably work a little bit different like the dialog use case, as e.g. buttons aren't removed - they just finish they job. I had the following pattern in mind where no additional overlay is added vaadin/web-components#842

I think for this case it would be simply enough to make the UI inert and set nothing modal to it - but currently the API design in the `UI` doesn't directly allow this. This API can be added quite easily later on. It is also just possible to just add an invisible modal component to the UI 😄 and it will be the same effect. Or by getting the root layout (under UI) and setting it as modal via the setter in `UI`.

Like the current API's javadocs says - the developer/component needs to just take care of showing a clear indication to the user that something is happening and the UI won't work - so they don't try to do something while waiting.

2021-11-29 14:49 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/communication/ReturnChannelHandler.java
> -
Done

2021-11-29 14:49 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/dom/Element.java
> +                PropertyChangeListener listener) {
Done

2021-12-21 13:35 UTC, joheriks requested changes

2021-12-21 13:35 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/InertData.java
> + * Copyright 2000-2020 Vaadin Ltd.
```suggestion
 * Copyright 2000-2021 Vaadin Ltd.
```
I'm fine with 2022 as well 😝 But let's keep this consistent in so we don't miss it in the 2021 -> 2022 update

2021-12-21 13:35 UTC, joheriks commented on flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/InertDataTest.java
> + * Copyright 2000-2020 Vaadin Ltd.
```suggestion
 * Copyright 2000-2021 Vaadin Ltd.
```
😛

2021-12-21 13:35 UTC, joheriks commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ModalDialogView.java
> + * Copyright 2000-2020 Vaadin Ltd.
```suggestion
 * Copyright 2000-2021 Vaadin Ltd.
```

2021-12-21 13:35 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/InertData.java
> + * should ignore inhering inert state from parent. By default the node is not
```suggestion
 * should ignore inheriting inert state from parent. By default the node is not
```

2021-12-21 13:35 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/InertData.java
> + * become inert, the state is does not block any pending executions until
```suggestion
 * become inert, the inert state does not block any pending executions until
```

2021-12-21 13:35 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/InertData.java
> +    public boolean isInertSelf() {
Add JavaDoc

2021-12-21 13:35 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/InertData.java
> +    public boolean isIgnoreParentInert() {
Add JavaDoc

2021-12-21 13:35 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/InertData.java
> +            LinkedList<StateNode> stack = new LinkedList<>();
Would make sense to use `ArrayDeque`.

2021-12-21 13:35 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +            modalComponentStack = new Stack<>();
Would make sense to use `ArrayDeque`.

2021-12-21 13:37 UTC, joheriks commented on flow-client/src/main/frontend/Flow.ts
>          };
Remove debug statements from this method.

2021-12-28 07:58 UTC, joheriks submitted a review, later dismissed

2021-12-28 10:28 UTC, joheriks submitted a review, later dismissed

2021-12-28 14:31 UTC, joheriks approved these changes

2021-12-28 14:38 UTC, merged