fix: Make flow-build-info.json deterministic
vaadin/flow pull request #12431
Opened 2021-11-23 14:49 UTC by Artur-

Fixes #7556

2021-11-25 08:45 UTC, caalador requested changes

2021-11-25 08:45 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ClassFinder.java
>              }
Shouldn't this add also be sorted for the classes array.
So something like `Arrays.stream(classes).sorted(Comparator.comparing(Class::getName)).forEach(this.classes::add);`
As there is nothing guaranteeing that the classes is always ordered when given.

2021-11-25 12:56 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ClassFinder.java
>              }
It is not needed for ClassFinder to be deterministic. For the Set constructor it is needed as the iteration order for the same classes differ when run multiple times. Wouldn't it be expected that the classes are scanned in the order they are given?

2021-11-25 13:12 UTC, caalador requested changes
A more certain place to keep the build file in order would be to order the written imports in `TaskUpdateImports::populateFallbackData`

At least the token file should be asserted in the test

2021-11-25 13:12 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ClassFinder.java
>              }
Also it seems this constructor is used only in tests.

2021-11-25 13:12 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
> +        Assert.assertEquals(expectedCssImports, cssImports.toJson());
Should also assert the tokenFile content for the written data here.

2021-11-25 13:26 UTC, Artur- commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
> +        Assert.assertEquals(expectedCssImports, cssImports.toJson());
That can be done although the token file contains nothing else than the fallback chunk

2021-11-25 13:27 UTC, Artur- commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
> +        Assert.assertEquals(expectedCssImports, cssImports.toJson());
Added

2021-11-26 04:48 UTC, caalador approved these changes

2021-11-26 04:49 UTC, merged