chore: Make formatter:format work again
vaadin/flow pull request #12430
Opened 2021-11-23 13:46 UTC by Artur-

2021-11-24 06:46 UTC, manolo requested changes

2021-11-24 06:46 UTC, manolo commented on pom.xml
> +                    <configFile>https://raw.githubusercontent.com/vaadin/flow/9.0/eclipse/VaadinJavaConventions.xml</configFile>
I would use `master` instead, to assure that latest conventions are loaded.
Contributor [doc guide](https://vaadin.com/docs/latest/contributing/overview) links to `master` as well.

2021-11-24 06:49 UTC, Artur- commented on pom.xml
> +                    <configFile>https://raw.githubusercontent.com/vaadin/flow/9.0/eclipse/VaadinJavaConventions.xml</configFile>
That's fine, assuming we will never ever move it out from `master`. Otherwise the build for all old Flow versions will fail the day it is removed from `master`

2021-11-24 15:50 UTC, manolo commented on pom.xml
> +                    <configFile>https://raw.githubusercontent.com/vaadin/flow/9.0/eclipse/VaadinJavaConventions.xml</configFile>
Makes sense too. My only concern is that devs would update the file in master and they might never cherry pick it to 9.0, probably no one remembers that.

2021-11-25 07:58 UTC, Artur- commented on pom.xml
> +                    <configFile>https://raw.githubusercontent.com/vaadin/flow/9.0/eclipse/VaadinJavaConventions.xml</configFile>
Changed to `master`. We can consider moving it later

2021-11-25 08:02 UTC, manolo approved these changes

2021-11-25 08:07 UTC, merged