Add issue templates
vaadin/flow pull request #12521
Opened 2021-12-07 08:56 UTC by caalador

2021-12-07 08:59 UTC, mstahv approved these changes

2021-12-07 09:07 UTC, Artur- commented on .github/ISSUE_TEMPLATE/bug_report.md
> +### Description of the bug / feature
```suggestion
### Description of the bug
```

2021-12-07 09:07 UTC, Artur- commented on .github/ISSUE_TEMPLATE/bug_report.md
> +### Description of the bug / feature
```suggestion
### Description of the bug
```

2021-12-07 09:07 UTC, Artur- commented on .github/ISSUE_TEMPLATE/bug_report.md
> +For feature requests, always include your use case - what are you trying to achieve and why.
```suggestion
```

2021-12-07 09:07 UTC, Artur- commented on .github/ISSUE_TEMPLATE/bug_report.md
> +NOTE: Issues concerning certain UI components should go to the components repository https://github.com/vaadin/flow-components .
```suggestion
NOTE: Issues concerning UI components (e.g. Button, Grid, TextField, ...) should go to the components repository https://github.com/vaadin/flow-components .
```

2021-12-07 09:07 UTC, Artur- commented on .github/ISSUE_TEMPLATE/bug_report.md
> +Only use GitHub issues for bugs and feature requests.
```suggestion

```

2021-12-07 09:07 UTC, Artur- commented on .github/ISSUE_TEMPLATE/vite-bug-report.md
> +Only use GitHub issues for bugs and feature requests.
```suggestion
```

2021-12-07 09:07 UTC, Artur- commented on .github/ISSUE_TEMPLATE/vite-bug-report.md
> +NOTE: Issues concerning certain UI components should go to the components repository https://github.com/vaadin/flow-components .
```suggestion
NOTE: Issues concerning UI components (e.g. Button, Grid, TextField, ...) should go to the components repository https://github.com/vaadin/flow-components .
```

2021-12-07 09:07 UTC, Artur- commented on .github/ISSUE_TEMPLATE/vite-bug-report.md
> +For feature requests, always include your use case - what are you trying to achieve and why.
```suggestion
```

2021-12-07 09:07 UTC, Artur- commented on .github/ISSUE_TEMPLATE/vite-bug-report.md
> +### Description of the bug / feature
```suggestion
### Description of the bug
```

2021-12-07 09:07 UTC, Artur- commented on .github/ISSUE_TEMPLATE/vite-bug-report.md
> +<!-- Explain briefly what is broken or what you want to achieve -->
```suggestion
<!-- Explain briefly what is broken -->
```

2021-12-07 09:07 UTC, Artur- commented on .github/ISSUE_TEMPLATE/bug_report.md
> +<!-- Explain briefly what is broken or what you want to achieve -->
```suggestion
<!-- Explain briefly what is broken -->
```

2021-12-07 12:28 UTC, gilberto-torrezan requested changes

2021-12-07 12:28 UTC, gilberto-torrezan commented on .github/ISSUE_TEMPLATE/bug_report.md
> +labels: ''
No `bug` label?

2021-12-07 12:28 UTC, gilberto-torrezan commented on .github/ISSUE_TEMPLATE/vite-bug-report.md
> +    - IDE (if applicable):
Since this is dedicated to Vite, we can ask specific questions, such as "Are you using development or production build?", "are you using Vite from a downloaded project in start.vaadin.com, or via the Vaadin gizmo?".

2021-12-07 12:28 UTC, gilberto-torrezan commented on .github/ISSUE_TEMPLATE/vite-bug-report.md
> +-->
Note for the future: add a link in the template to our post explaining how to activate Vite in new and existing projects.

2021-12-07 12:28 UTC, gilberto-torrezan commented on .github/ISSUE_TEMPLATE/vite-bug-report.md
> +-->
It's worth mentioning that Vite only works for V22+ projects, to avoid reports from users on V14 or V21.

2021-12-07 12:28 UTC, gilberto-torrezan commented on .github/ISSUE_TEMPLATE/vite-bug-report.md
> +about: Issues for Vite support in flow
Not just in Flow.
You can just say "Issues about the Vite support"

2021-12-07 12:28 UTC, gilberto-torrezan commented on .github/ISSUE_TEMPLATE/bug_report.md
> +NOTE: Issues concerning UI components (e.g. Button, Grid, TextField, ...) should go to the components repository https://github.com/vaadin/flow-components .
Another note: Issues concerning Vaadin Fusion should go to the Fusion repository https://github.com/vaadin/fusion

2021-12-08 04:44 UTC, caalador commented on .github/ISSUE_TEMPLATE/bug_report.md
> +labels: ''
It's not a bug until triaged.

2021-12-08 06:22 UTC, caalador commented on .github/ISSUE_TEMPLATE/bug_report.md
> +NOTE: Issues concerning UI components (e.g. Button, Grid, TextField, ...) should go to the components repository https://github.com/vaadin/flow-components .
done

2021-12-08 06:22 UTC, caalador commented on .github/ISSUE_TEMPLATE/vite-bug-report.md
> +about: Issues for Vite support in flow
done

2021-12-08 06:22 UTC, caalador commented on .github/ISSUE_TEMPLATE/vite-bug-report.md
> +    - IDE (if applicable):
Done. 
Feel free to add anything extra you feel would help.

2021-12-08 08:52 UTC, gilberto-torrezan approved these changes

2021-12-08 12:13 UTC, anssit approved these changes

2021-12-08 14:13 UTC, merged