fix: Do not throw NPE for UI.access called when session has expired
vaadin/flow pull request #12531
Opened 2021-12-08 08:32 UTC by Artur-

Fixes #12100

2021-12-08 18:49 UTC, caalador requested changes

2021-12-08 18:49 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/component/UITest.java
> +                output.getAbsolutePath());
This doesn't sound too thread safe as some other test could add unexpected logs failing the test, so would it be better to use the `com.vaadin.flow.server.frontend.MockLogger` and make the `UI.getLogger` method package protected and overridable.

2021-12-09 08:17 UTC, Artur- commented on flow-server/src/test/java/com/vaadin/flow/component/UITest.java
> +                output.getAbsolutePath());
Good point, makes the code better also

2021-12-09 08:17 UTC, Artur- commented on flow-server/src/test/java/com/vaadin/flow/component/UITest.java
> +                output.getAbsolutePath());
Done

2021-12-09 08:32 UTC, caalador approved these changes

2021-12-09 08:57 UTC, merged

2021-12-09 09:05 UTC, Artur- commented
#12547