test: add -amd flag to ITs
vaadin/flow pull request #12582
Opened 2021-12-15 14:46 UTC by manolo

2021-12-16 09:33 UTC, Artur- commented on .github/workflows/validation.yml
> +            mvn -B install -DskipITs -pl flow-tests/test-fusion-csrf
Isn't this code exactly what `-am` does?

2021-12-17 13:00 UTC, manolo commented on .github/workflows/validation.yml
> +            mvn -B install -DskipITs -pl flow-tests/test-fusion-csrf
-am also compiles and run tests for flow-server flow-client etc

2021-12-27 07:56 UTC, ZheSun88 approved these changes

2021-12-27 08:08 UTC, ZheSun88 commented
it looks there are some flakiness with the test set. 
check the validation history.. https://github.com/vaadin/flow/actions/workflows/validation.yml?query=branch%3Asubmodules++

2021-12-27 08:10 UTC, Artur- commented on scripts/computeMatrix.js
> +  // When running `flow-tests/test-mixed/pom-npm.xml` together with the following
Is this still accurate after the system property changes in another PR?

2021-12-27 08:10 UTC, ZheSun88 requested changes
the it test:7 module failed, but the build passes?
i think the build result should be catch the failure

2021-12-27 09:44 UTC, manolo commented on scripts/computeMatrix.js
> +  // When running `flow-tests/test-mixed/pom-npm.xml` together with the following
It's in the border, it takes 32 seconds, I use weight unit each 30 secs. So 1 or 2 is ok for this module.

2021-12-27 09:52 UTC, manolo commented
> the it test:7 module failed, but the build passes? i think the build result should be catch the failure

You are right, container 7 was cancelled by GH actions after a failure in checkout, we need to fail not only on failures but also in cancellation

2021-12-27 12:20 UTC, manolo commented
I think there are issues in GH actions, I had never seen this error:
```
Warning: Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/ec3a7ce113134d7a93b817d10a8272cb61118579'. Error: The operation was canceled.
Warning: Back off 28.44 seconds before retry.
Download action repository 'actions/setup-node@v2' (SHA:04c56d2f954f1e4c69436aa54cfef261a018f458)
Download action repository 'pnpm/action-setup@v2.0.1' (SHA:646cdf48217256a3d0b80361c5a50727664284f2)
Download action repository 'actions/setup-java@v2' (SHA:f0bb91606209742fe3ea40199be2f3ef195ecabf)
Download action repository 'actions/cache@v1' (SHA:70655ec8323daeeaa7ef06d7c56e1b9191396cbe)
Warning: Failed to download action 'https://api.github.com/repos/actions/cache/tarball/70655ec8323daeeaa7ef06d7c56e1b9191396cbe'. Error: The operation was canceled.
Warning: Back off 14.096 seconds before retry.
Warning: Failed to download action 'https://api.github.com/repos/actions/cache/tarball/70655ec8323daeeaa7ef06d7c56e1b9191396cbe'. Error: The operation was canceled.
Warning: Back off 21.342 seconds before retry.
Error: The operation was canceled.
```

2021-12-28 08:56 UTC, manolo commented
seems that `Failed to download action` is not an issue now, I guess it was a problem in azure infra where actions are run.

2021-12-29 07:47 UTC, ZheSun88 commented
> I think there are issues in GH actions, I had never seen this error:
> 
> ```
> Warning: Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/ec3a7ce113134d7a93b817d10a8272cb61118579'. Error: The operation was canceled.
> Warning: Back off 28.44 seconds before retry.
> Download action repository 'actions/setup-node@v2' (SHA:04c56d2f954f1e4c69436aa54cfef261a018f458)
> Download action repository 'pnpm/action-setup@v2.0.1' (SHA:646cdf48217256a3d0b80361c5a50727664284f2)
> Download action repository 'actions/setup-java@v2' (SHA:f0bb91606209742fe3ea40199be2f3ef195ecabf)
> Download action repository 'actions/cache@v1' (SHA:70655ec8323daeeaa7ef06d7c56e1b9191396cbe)
> Warning: Failed to download action 'https://api.github.com/repos/actions/cache/tarball/70655ec8323daeeaa7ef06d7c56e1b9191396cbe'. Error: The operation was canceled.
> Warning: Back off 14.096 seconds before retry.
> Warning: Failed to download action 'https://api.github.com/repos/actions/cache/tarball/70655ec8323daeeaa7ef06d7c56e1b9191396cbe'. Error: The operation was canceled.
> Warning: Back off 21.342 seconds before retry.
> Error: The operation was canceled.
> ```

I have seen this failure when reran this PR, after 2 try, it looks this failure has disappeared. 
the first system flaky issue?

2021-12-29 11:21 UTC, ZheSun88 approved these changes

2021-12-30 10:33 UTC, manolo commented
Build passes. There have been some failures in this PR unrelated to the changes, one was the problem checking out the repo described above, which means problems in the GH infra, the same with the following error, that points to random failures in networking.
@Artur-  @ZheSun88  I think this PR can safely be merged, since otherwise we are not checking all tests in flow.

```
Error:  Failed to execute goal on project addon-with-templates: Could not resolve dependencies for project com.vaadin:addon-with-templates:jar:999.99-SNAPSHOT: The following artifacts could not be resolved: com.google.code.gson:gson:jar:2.8.8, com.github.docker-java:docker-java:jar:3.2.12, com.github.docker-java:docker-java-core:jar:3.2.12, com.github.docker-java:docker-java-api:jar:3.2.12: Could not transfer artifact com.google.code.gson:gson:jar:2.8.8 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/com/google/code/gson/gson/2.8.8/gson-2.8.8.jar: Connection timed out (Read failed) -> [Help 1]
```

2021-12-30 10:45 UTC, merged