fix: Proper handling of href when the anchor is disabled/enabled
vaadin/flow pull request #12616
Opened 2021-12-21 08:54 UTC by mstahv

## Description

Disabling and enabling component using the Java API now works as expected. href is always saved in the component implementation, but not stored in element if disabled.

Fixes #10924

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

2021-12-21 11:12 UTC, joheriks requested changes

2021-12-21 11:12 UTC, joheriks commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
> +        if (href != null) {
Could this `if` expression also contain the guard `isEnabled()`, as it would simplify the callers.

2021-12-21 11:36 UTC, mstahv commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
> +        if (href != null) {
Then I'd refactor the change as we'd be doing conditional checks twice in onEnabledStateChange.

2021-12-22 06:53 UTC, joheriks submitted a review, later dismissed

2021-12-22 08:18 UTC, caalador commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
> +        // the disabled Anchor returns null, otherwise some String.
Just an idea. Would it break much if for a streamResource we would return the `AbstractStreamResource::getName`  as `StreamResource for 'AbstractStreamResource::getName'`

As then at least it would be clear that there is something set to the anchor.

2021-12-22 08:29 UTC, mstahv commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
> +        // the disabled Anchor returns null, otherwise some String.
Even though it still wouldn't work perfectly, that might be a tiny enhancement. That could help if people are testing the existence of href when the component is disabled like this:

if(getHref().isEmpty()) {
   // do stuff with things
}

I guess we can't really get the actual uri for the resources as it (might be it) is not attached when ancsdhor is disabled 🤔

I guess the academically correct way would be to deprecate setHref(StreamResource) and have setStreamResource method separately. Then we could have a symmetric getter for it.

Up to you to decide. I'd get this in now as this and refine if we get more input from the users.

2021-12-22 08:57 UTC, caalador commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
> +        // the disabled Anchor returns null, otherwise some String.
Well there is the static method `StreamResourceRegistry.getURI(AbstractStreamResource)` which if registered will give the actual href.

2021-12-22 11:04 UTC, mstahv commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
> +        // the disabled Anchor returns null, otherwise some String.
Checked the implementation and to me it looks like it should always return something sane. Pushed a change like that.

2021-12-22 11:04 UTC, mstahv commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
> +        // the disabled Anchor returns null, otherwise some String.
No test for it though 😬

2021-12-22 11:11 UTC, mstahv commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
> +        // the disabled Anchor returns null, otherwise some String.
Now the tests cover this as well

2021-12-23 07:36 UTC, caalador approved these changes

2021-12-23 07:36 UTC, merged