feat: lock versions with npm overrides
vaadin/flow pull request #12635
Opened 2021-12-23 12:29 UTC by haijian-vaadin

## Description
How it works?
1. generate `versions.json` also for npm mode
2. if `npm` mode, create an `"overrides"` section in the `package.json` file if the file does not exist.
3. iterate through dependencies in the `version.json` file, add each dependency to the overrides section as @vaadin/xxx: $@vaadin/xxx if there is no @vaadin/xxx in the "overrides" section.

Requires npm 8.3.0 or newer which has the "overrids" feature. 
Fixes https://github.com/vaadin/fusion/issues/164

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-01-03 12:20 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +        if(enablePnpm) {
Ah right, this is used for `npm` only

2022-01-03 12:21 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +        if(enablePnpm) {
Should we write this info to `package.json` also for pnpm and read the overrides from the same place instead of having two different approaches?

2022-01-03 13:20 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +                    overridesSection.put(dependency, "$"+dependency);
How can I manually override a version? This looks like it would overwrite all my manual changes?

2022-01-03 13:27 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +                    overridesSection.put(dependency, "$"+dependency);
if you define a version in the dependencies section, e.g. `"@vaadin/button": "23.0.0-alpha3"`, then it will write into the overrides section `"@vaadin/button": "$@vaadin/button"`, so that the user-defined version is used. 

if you define sth in the overrides section, e.g. `"@vaadin/button": "23.0.0-alpha3"`, then NodeUpdater will leave it untouched.

2022-01-04 09:50 UTC, Artur- requested changes

2022-01-04 09:50 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +     * Generate versions json file for pnpm.
Isn't this also for npm now?

2022-01-04 09:50 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +                    | lockVersionForNpm(packageJson);
This really needs to be fixed or somebody will change it to `||` one day without realizing it breaks the code

Store the results into two separate booleans or something similar

2022-01-04 09:50 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
> +                createPnpmFile(packageUpdater.generateVersionsJson());
We should find one place to generate the version json. It just makes everything harder if `pnpm` runs it as part of install and `npm` runs it in `TaskUpdatePackages`

2022-01-04 09:50 UTC, Artur- commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
> +            @Override
Where is the test for this whole feature? I see no test testing that an `overrides` section is even written

2022-01-04 10:15 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +     * Generate versions json file for pnpm.
good catch, will update the doc

2022-01-04 10:15 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
> +                createPnpmFile(packageUpdater.generateVersionsJson());
yes, will try to refactor

2022-01-04 10:16 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
> +            @Override
not yet, it's a draft PR, working in progress, doing it now

2022-01-04 21:57 UTC, TomMD commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +                    | lockVersionForNpm(packageJson);
Do I understand correctly that your preference would be to remove this warning message because it is inaccurate and could be harmful?

2022-01-04 22:03 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +                    | lockVersionForNpm(packageJson);
Yes, the code has been refactored already, the warning is outdated.

2022-01-05 07:50 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
> +            @Override
Added some tests, can you help to take another look?

2022-01-05 07:50 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +                    overridesSection.put(dependency, "$"+dependency);
does it sound good or do you have other concerns?

2022-01-05 08:17 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +        if(enablePnpm) {
It works that both `npm` and `pnpm` read the pinned dependencies from the generated versions.json file. The difference is that `npm` locks the version with an `overrides` section in the `package.json` file, `pnpm` locks the version by creating a hook, the `pnpmfile.js`.
`npm` overrides uses the "$" syntax for the dependency version, where `pnpm` needs the explicit version, so it won't work.
Aslo the pnpm hook now works with the versions.json file directly `const versionsFile = require('path').resolve(__dirname, 'target/frontend/versions.json');`. To change it to read from `package.json` would actually make it more complicated.

2022-01-05 08:18 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
> +                createPnpmFile(packageUpdater.generateVersionsJson());
I am now thinking maybe we do the refactor in a separate PR? So that we can get this PR merged and make a release before the PiT.

2022-01-05 08:22 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +                    deleteNpmLockFile();
When is this a problem? We really shouldn't be deleting the lock file, ever.

2022-01-05 08:38 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +                    deleteNpmLockFile();
It's needed for the existing project with npm mode. `npm` version locking only works after deleting the npm lock file.

2022-01-05 08:43 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +                    deleteNpmLockFile();
hmm, take another thought, seems it's only a problem with an existing project that has duplicated dependencies already. I will update the code.

2022-01-05 09:43 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
> +                createPnpmFile(packageUpdater.generateVersionsJson());
Wouldn't it be better to make the final version and test that ?

2022-01-05 11:54 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
> +                createPnpmFile(packageUpdater.generateVersionsJson());
done, it took less effort than expected. Now it generates the `version.json` file in `TaskUpdatePackages`, the file path is passed as a field, same as `modified`.

2022-01-05 14:35 UTC, Artur- commented
I think we need to update the `hash` calculation to include the `overrides` section. Right now this does not work:
1. Run `mvn spring-boot:run`
2. Edit package.json and add an override like `"json-schema": ">=0.4.0"`
3. Run `mvn spring-boot:run`

If the original npm installation used 0.3.0 like in my app, it will still use 0.3.0. This is only because 
```
Skipping `npm install` because the frontend packages are already installed in the folder '.../node_modules' and the hash in the file '.../node_modules/.vaadin/vaadin.json' is the same as in 'package.json'
```

2022-01-05 14:36 UTC, Artur- commented
Then a small nit: I would place the `overrides` section before the `vaadin` section so that package.json first contains the "standard" things and then vaadin specifics at the end

2022-01-07 07:52 UTC, haijian-vaadin commented
> I think we need to update the `hash` calculation to include the `overrides` section. Right now this does not work:
> 
> 1. Run `mvn spring-boot:run`
> 2. Edit package.json and add an override like `"json-schema": ">=0.4.0"`
> 3. Run `mvn spring-boot:run`
> 
> If the original npm installation used 0.3.0 like in my app, it will still use 0.3.0. This is only because
> 
> ```
> Skipping `npm install` because the frontend packages are already installed in the folder '.../node_modules' and the hash in the file '.../node_modules/.vaadin/vaadin.json' is the same as in 'package.json'
> ```

I think this could done in a separate PR, made a [ticket](https://github.com/vaadin/flow/issues/12682). The main purpose of this PR is to lock the versions of Vaadin managed dependencies.

2022-01-07 09:04 UTC, joheriks commented
> Requires npm 8.3.0 or newer which has the "overrids" feature.
Should the version validation be updated then?
https://github.com/vaadin/flow/blob/5e19cb3bf2abd82e5ae5777403872c9f9509b545/flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java#L113-L114

2022-01-07 09:08 UTC, haijian-vaadin commented
> > Requires npm 8.3.0 or newer which has the "overrids" feature.
> 
> Should the version validation be updated then?
> 
> https://github.com/vaadin/flow/blob/5e19cb3bf2abd82e5ae5777403872c9f9509b545/flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java#L113-L114

@Artur- did a [change](https://github.com/vaadin/flow/pull/12660/files) to upgrade to Node 17 + npm 8.3. Is that enough?
I think npm 6.14 is still supported, as in V14, just that it doesn't have the overrides feature available.

2022-01-07 09:19 UTC, Artur- commented
It would be nice to let the users know that it will work better if you upgrade to npm 8.3+ if they are using an older globally installed node/npm. We cannot really require the latest version of npm though and we need to make sure that node 16 with its bundled npm works in a standard (i.e no addons) project

2022-01-07 09:20 UTC, joheriks commented
So if I have an older `npm` version that doesn't support `overrides` the section will be ignored, and there will be no version locking (as it is currently working when using `npm` instead of `pnpm`). Is there a risk of a silent regression if I have been relying on `pnpm` now that the default switched to `npm` but my pre-installed version is too old?

2022-01-07 09:31 UTC, haijian-vaadin commented
Is it enough to mention this in the upgrade guide? For people relying on the pnpm locking and cannot upgrade to npm 8.3, they can keep using pnpm.

2022-01-07 09:40 UTC, Artur- commented
The place you would run into this is most of the time when you get a browser warning that a custom element has already been defined. This would be the best place to provide additional info on how the solve the problem but it feels like a separate issue/pr

2022-01-07 10:43 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +        }
I feel we should not return for pnpm, but just wrap the end result in `pnpm` JsonObject and clear out the code for pnpmfile.js

2022-01-07 10:43 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +                    overridesSection.put(dependency, "$" + dependency);
If `pnpm { override { } }` doesn't work with `$[dependencyKey]` then we should just write the version here.

2022-01-07 10:43 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
> +    }
Shouldn't this be in `TaskRunPnpmInstallTest` as it is only used from there?

2022-01-07 10:43 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +                        && !NodeUpdater.DEP_NAME_FLOW_JARS.equals(dependency)) {
Shouldn't the skip, skip any dependency that targets a directory e.g. anything that has the value as `startsWith("./" + buildFolder())` and not only `@vaadin/flow-frontend` also what about `DEP_NAME_FLOW_DEPS = "@vaadin/flow-deps"`?

2022-01-07 10:43 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesNpmVersionLockingTest.java
> +    public void shouldNotNotUpdatesOverrides_whenHasUserModification()
```suggestion
    public void shouldNotUpdateOverrides_whenHasUserModification()
```
What is the expected place to have user modificatio? Override or dependencies? should override be populated for user dependency that is overriding framework version?

2022-01-07 10:53 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +                    overridesSection.put(dependency, "$" + dependency);
Wouldn't that mean duplicating every single version in one more place? Also that if you manually update a version of a dependency, then you would still get an old version unless you remember to update the overrides also?

2022-01-07 11:03 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +                    overridesSection.put(dependency, "$" + dependency);
It should ofc be automatically updated.

2022-01-07 11:14 UTC, caalador commented
Also missing is cleaning of the override in `CleanFrontendMojo`

2022-01-07 11:18 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +                    overridesSection.put(dependency, "$" + dependency);
I guess it depends on whether we consider a valid use case to manually update Vaadin managed dependencies. If so, it would indeed be surprising to have to update the `overrides`section as well. If not, and it is all automated it shouldn't matter. At least `pnpm` (`5.18.10`)  doesn't seem to fail on the `overrides: { @dep: "$@dep" }` syntax. Since we have already version pinning in `pnpmfile.js`, would it anyway be better to keep this (then `pnpmfile.js` could just later be removed if [pnpm adds the compatible option](https://github.com/pnpm/pnpm/issues/4190)).

2022-01-07 11:25 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +                    overridesSection.put(dependency, "$" + dependency);
It should be 100% ok to update a vaadin dependency if there is an incompatibility with for instance an add-on that would else work or if you want to use something newer in the project (for instance charts version)

2022-01-07 11:53 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +                    overridesSection.put(dependency, "$" + dependency);
I would be inclined to keep `@dep: "$@dep"`, adding duplicate versions seems like setting up for more trouble ahead.

2022-01-07 12:00 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +                    overridesSection.put(dependency, "$" + dependency);
Well my point was just that if it doesn't work with pnpm (is changed so that both generate the overrides) then it should lock it with the version. else it should reference.

2022-01-07 12:01 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +        }
I think it's better to leave pnpm lock alone in this PR, so that if npm locking for some reason doesn't work, they can switch back to pnpm.
We could do the pnpm locking change in a different PR.

2022-01-07 12:04 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
> +    }
good point, move it there

2022-01-07 12:06 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesNpmVersionLockingTest.java
> +    public void shouldNotNotUpdatesOverrides_whenHasUserModification()
the overrides section might have user modifications. A user could update the values in the overrides section manually, if there are such changes, we just leave them alone.

2022-01-07 12:06 UTC, haijian-vaadin commented
> Also missing is cleaning of the override in `CleanFrontendMojo`

Good catch, done

2022-01-07 12:06 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +                        && !NodeUpdater.DEP_NAME_FLOW_JARS.equals(dependency)) {
good point, updated

2022-01-07 12:21 UTC, joheriks commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesNpmVersionLockingTest.java
> +    public void shouldNotNotUpdatesOverrides_whenHasUserModification()
If the update has pinned a Vaadin managed dep (e.g. updated in the `overides` section `"@polymer/iron-a11y-announcer": "$@polymer/iron-a11y-announcer"` -> `"@polymer/iron-a11y-announcer": "3.1.0"`), this is also cleaned. But maybe this is fine.

2022-01-07 12:26 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesNpmVersionLockingTest.java
> +    public void shouldNotNotUpdatesOverrides_whenHasUserModification()
right, it's an edge case and should be fine.

2022-01-07 13:16 UTC, platosha commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
> +        getNodeUpdater().versionsPath = "./version.json";
Let’s align the filename:

```suggestion
        getNodeUpdater().versionsPath = "./versions.json";
```

2022-01-07 13:19 UTC, platosha approved these changes

2022-01-07 13:19 UTC, platosha commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
> +        getNodeUpdater().versionsPath = "./version.json";
```suggestion
        getNodeUpdater().versionsPath = "./versions.json";
```

2022-01-07 13:19 UTC, platosha commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
> +        getNodeUpdater().versionsPath = "./version.json";
Maybe align the filename?

```suggestion
        getNodeUpdater().versionsPath = "./versions.json";
```

2022-01-07 13:19 UTC, platosha commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
> +                    "NodeUpdater failed to genereate the version.json file");
```suggestion
                    "NodeUpdater failed to genereate the versions.json file");
```

2022-01-07 14:05 UTC, joheriks submitted a review, later dismissed

2022-01-07 15:33 UTC, Artur- approved these changes

2022-01-07 16:09 UTC, merged

2022-01-24 22:34 UTC, imsys commented
> now that it will work better if you upgrade to npm 8.3+ if they are using an older globally installed node/npm. We cannot really require the latest version of npm though and we need to make sure that node 16 with its bundled npm works in a standard (i.e no addons) project

As someone who fell in this thread almost by accident, when I saw the issue at https://github.com/pnpm/pnpm/issues/4190, and I don't know much about this project, but I thought to give my two cents, that you could add some version specification in the package.json

```json
"engines": {
    "npm": ">=8.3.0"
    "pnpm": ">=5.10.1"
}
```
> "Unless the user has set the `engine-strict` config flag (see `.npmrc`), this field is advisory only and will only produce warnings when your package is installed as a dependency." - from npmjs documentation

2022-01-25 08:17 UTC, haijian-vaadin commented
Hi @imsys, thanks a lot for the proposal, that's a very good idea, I made an enhancement [ticket](https://github.com/vaadin/flow/issues/12824) out of your suggestion.