fix: Always use defined node version
vaadin/flow pull request #12695
Opened 2022-01-11 07:54 UTC by caalador

If defined always use the node version
and download root url is defined.

Closes #12686

2022-01-13 08:17 UTC, joheriks requested changes

2022-01-13 08:17 UTC, joheriks commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +                    .error("NODE_DOWNLOAD_ROOT defined incorrectly", e);
Should the logged error contain the literal value of `NODE_DOWNLOAD_ROOT` (`node.download.root`) instead

2022-01-13 08:34 UTC, caalador commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +                    .error("NODE_DOWNLOAD_ROOT defined incorrectly", e);
clarified.

2022-01-13 12:51 UTC, joheriks approved these changes

2022-01-17 07:52 UTC, joheriks approved these changes

2022-01-17 09:17 UTC, merged