fix: move source maps to frontend dest (#12701) (CP: 2.8)
vaadin/flow pull request #12729
Opened 2022-01-14 14:48 UTC by vursen

## Description

A cherry-pick of #12701 to 2.8.

## Type of change

- [x] Bugfix

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

2022-01-14 14:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=12729) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=12729) before we can accept your contribution.<br/>**9** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: caalador<br/>:white_check_mark: Artur-<br/>:white_check_mark: mstahv<br/>:white_check_mark: anssit<br/>:white_check_mark: TatuLund<br/>:white_check_mark: mshabarov<br/>:white_check_mark: vursen<br/>:white_check_mark: joheriks<br/>:white_check_mark: pleku<br/>:x: Denis<br/><hr/>**Denis** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=12729) it.</sub>

2022-01-24 07:57 UTC, caalador commented
This could be closed as 2.8 doesn't support Vite

2022-01-25 09:46 UTC, platosha approved these changes

2022-01-25 09:54 UTC, caalador requested changes
What is the value of this for V14 as it doesn't support Vite?

2022-01-25 10:21 UTC, caalador approved these changes

2022-01-25 11:06 UTC, merged