feat: Fallback to alternative node when preferred is unsupported
vaadin/flow pull request #12768
Opened 2022-01-19 15:52 UTC by mcollovati

## Description

When project or global node version is detected but deemed incompatible with Vaadin, alternative node installation (~./vaadin/node) is used as fallback (and downloaded if not present).

Fixes #12494 

## Type of change

- [ ] Bugfix
- [X] Feature

## Checklist

- [X] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [X] I have added a description following the guideline.
- [X] The issue is created in the corresponding repository and I have referenced it.
- [X] I have added tests to ensure my change is effective and works as intended.
- [X] New and existing tests are passing locally with my change.
- [X] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [X] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-01-20 06:48 UTC, caalador requested changes

2022-01-20 06:48 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +                        SUPPORTED_NODE_VERSION.getFullVersion());
Would be nice if we could info if it's the global node or a project installed node that is too old. (e.g. is nodeExecutable starts with baseDir or not)

2022-01-20 06:48 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +                    foundNodeVersionAndExe.getSecond());
This would sound more like debug log

2022-01-20 06:48 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +                    getNpmExecutable(false).get(0));
Would also have this log on the debug level

2022-01-20 06:48 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
> +            throw new InstallationException(errorMessage, e);
I would keep the exception message short and sweet with extra information in the log output.
```suggestion
            getLogger().error("Node.js download failed. This may be due to loss of internet connection.\n"
                    + "If you are behind a proxy server you should configure your proxy settings.\n"
                    + "Verify connection and proxy settings or follow the https://nodejs.org/en/download/ guide to install Node.js globally.");
            throw new InstallationException( "Could not download Node.js. Check your connection and proxy settings.", e);
```

2022-01-20 07:41 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +                    getNpmExecutable(false).get(0));
done

2022-01-20 07:41 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +                    foundNodeVersionAndExe.getSecond());
done

2022-01-20 07:42 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +                        SUPPORTED_NODE_VERSION.getFullVersion());
done

2022-01-20 07:42 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
> +            throw new InstallationException(errorMessage, e);
done. Thanks for suggestion

2022-01-20 07:46 UTC, caalador approved these changes

2022-01-20 10:18 UTC, mcollovati commented
I managed to locally reproduce failure of `MultipleNpmPackageAnnotationsIT.pageShouldContainTwoPaperComponents` test.
The test doesn't fail at first execution, but if always fail afterwards, due to the following error 

```
[ForkJoinPool.commonPool-worker-7] INFO com.vaadin.base.devserver.AbstractDevServerRunner - Running Webpack to compile frontend resources. This may take a moment, please stand by...
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker - [webpack-cli] Failed to load '/home/marco/projects/vaadin/flow_develop/flow-tests/test-npm-only-features/test-npm-no-buildmojo/webpack.config.js' config
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker - [webpack-cli] Error: Cannot find module '@vaadin/build-status-plugin'
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker - Require stack:
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker - - /home/marco/projects/vaadin/flow_develop/flow-tests/test-npm-only-features/test-npm-no-buildmojo/webpack.generated.js
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker - - /home/marco/projects/vaadin/flow_develop/flow-tests/test-npm-only-features/test-npm-no-buildmojo/webpack.config.js
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker - - /home/marco/projects/vaadin/flow_develop/flow-tests/test-npm-only-features/test-npm-no-buildmojo/node_modules/.pnpm/webpack-cli@4.9.0_714d72df2bebb3ac089d7453aabd5d57/node_modules/webpack-cli/lib/webpack-cli.js
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker - - /home/marco/projects/vaadin/flow_develop/flow-tests/test-npm-only-features/test-npm-no-buildmojo/node_modules/.pnpm/webpack-cli@4.9.0_714d72df2bebb3ac089d7453aabd5d57/node_modules/webpack-cli/lib/bootstrap.js
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker - - /home/marco/projects/vaadin/flow_develop/flow-tests/test-npm-only-features/test-npm-no-buildmojo/node_modules/.pnpm/webpack-cli@4.9.0_714d72df2bebb3ac089d7453aabd5d57/node_modules/webpack-cli/bin/cli.js
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker - - /home/marco/projects/vaadin/flow_develop/flow-tests/test-npm-only-features/test-npm-no-buildmojo/node_modules/.pnpm/webpack-dev-server@4.1.1_webpack-cli@4.9.0+webpack@4.46.0/node_modules/webpack-dev-server/bin/webpack-dev-server.js
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     at Module.require (node:internal/modules/cjs/loader:1005:19)
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     at require (/home/marco/projects/vaadin/flow_develop/flow-tests/test-npm-only-features/test-npm-no-buildmojo/node_modules/.pnpm/v8-compile-cache@2.3.0/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     at Object.<anonymous> (/home/marco/projects/vaadin/flow_develop/flow-tests/test-npm-only-features/test-npm-no-buildmojo/webpack.generated.js:16:27)
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     at Module._compile (/home/marco/projects/vaadin/flow_develop/flow-tests/test-npm-only-features/test-npm-no-buildmojo/node_modules/.pnpm/v8-compile-cache@2.3.0/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     at Module.load (node:internal/modules/cjs/loader:981:32)
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     at Module.require (node:internal/modules/cjs/loader:1005:19) {
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -   code: 'MODULE_NOT_FOUND',
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -   requireStack: [
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     '/home/marco/projects/vaadin/flow_develop/flow-tests/test-npm-only-features/test-npm-no-buildmojo/webpack.generated.js',
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     '/home/marco/projects/vaadin/flow_develop/flow-tests/test-npm-only-features/test-npm-no-buildmojo/webpack.config.js',
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     '/home/marco/projects/vaadin/flow_develop/flow-tests/test-npm-only-features/test-npm-no-buildmojo/node_modules/.pnpm/webpack-cli@4.9.0_714d72df2bebb3ac089d7453aabd5d57/node_modules/webpack-cli/lib/webpack-cli.js',
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     '/home/marco/projects/vaadin/flow_develop/flow-tests/test-npm-only-features/test-npm-no-buildmojo/node_modules/.pnpm/webpack-cli@4.9.0_714d72df2bebb3ac089d7453aabd5d57/node_modules/webpack-cli/lib/bootstrap.js',
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     '/home/marco/projects/vaadin/flow_develop/flow-tests/test-npm-only-features/test-npm-no-buildmojo/node_modules/.pnpm/webpack-cli@4.9.0_714d72df2bebb3ac089d7453aabd5d57/node_modules/webpack-cli/bin/cli.js',
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     '/home/marco/projects/vaadin/flow_develop/flow-tests/test-npm-only-features/test-npm-no-buildmojo/node_modules/.pnpm/webpack-dev-server@4.1.1_webpack-cli@4.9.0+webpack@4.46.0/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -   ]
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker - }
[ForkJoinPool.commonPool-worker-7] INFO com.vaadin.base.devserver.AbstractDevServerRunner - Started Webpack. Time: 2065ms
```

If I remove `node_modules` directory from the project owning the test, it runs succesfully again.
Don't know if this is related to the changes of this PR or not.

2022-01-20 11:13 UTC, mcollovati commented
Locally, the reason for failure on repetitive test launches may be that in module `flow-test-npm-no-buildmojo`, maven clean plugin is configured to delete `@vaadin` and `@polymer` from `node_modules`, but it does not clean `node_modules/.vaadin/vaadin.json`. 
For this reason `npm  install` is not triggered and `node_modules/@vaadin` remains empty; thus, the module not found error

2022-01-21 06:30 UTC, caalador approved these changes

2022-01-21 06:30 UTC, merged