feat: add map component feature flag
vaadin/flow pull request #12782
Opened 2022-01-20 15:06 UTC by sissbruecker

## Description

Adds a feature flag for the map component that is currently in development. During development, and also after completion of the initial project, we want to consider the component to be in an experimental state and force users to opt-in into its usage. The purpose of the flag is:
- to provide a way for the Flow map component to check whether the feature is enabled
- to automatically enable the web component feature flag (https://github.com/vaadin/web-components/pull/3321) through the webpack or vite builds for Hilla apps, if the Java flag is enabled. This would happen in a follow up PR.

We want to move this flag into this repo in order to re-use the existing constructs around feature flags, provide a consistent experience for using them for our users, and to support the automation for Hilla apps.

Part of https://github.com/vaadin/flow-components/issues/2495

## Type of change

- [x] Feature (not sure if you want to tag this as feature, feel free to modify)

2022-01-20 15:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=12782) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=12782) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=12782) it.</sub>

2022-01-20 15:25 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
> +            "Enable the Map component", "enableMapComponent",
Should there be some kind of flag that this is a pro component?

2022-01-21 10:09 UTC, sissbruecker commented
Changed to a draft, will add support for defining the feature flags on the client-side after all.

2022-01-21 11:33 UTC, sissbruecker commented
Updated the PR to add an implementation for generating a client-side file that defines the globals that are required by the web component.

2022-01-21 11:40 UTC, sissbruecker commented
Looks like there is a test failure in `StatisticsSenderTest`, not sure how that is related to my changes 🤔

2022-01-21 13:17 UTC, Artur- requested changes

2022-01-21 13:17 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
> +            "Enable the Map component", "enableMapComponent",
```suggestion
            "Map component (Pro)", "enableMapComponent",
```

2022-01-21 13:17 UTC, Artur- commented
>Looks like there is a test failure in StatisticsSenderTest, not sure how that is related to my changes 🤔

It is not related. It is a problem with the test

2022-01-21 14:00 UTC, Artur- submitted a review, later dismissed

2022-01-21 14:02 UTC, sissbruecker commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateFeatureFlags.java
> +                "window.Vaadin.experimental = window.Vaadin.experimental || {};");
Was orienting myself on the keys in the properties file here, but I agree, using using `featureFlags` is clearer and more consistent. Done.

2022-01-21 14:02 UTC, sissbruecker commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    public static final String FEATURE_FLAGS_FILE_NAME = "feature-flags.ts";
Sure, could be helpful to relate the two files. Done.

2022-01-21 14:02 UTC, sissbruecker commented on flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
> +            "Enable the Map component", "enableMapComponent",
Done

2022-01-24 13:57 UTC, Artur- approved these changes

2022-01-24 13:57 UTC, merged