feat: make Vite PWA apps work offline in dev mode
vaadin/flow pull request #12928
Opened 2022-02-03 16:24 UTC by vursen

## Description

This PR focuses on making Vite PWA apps work offline in dev mode. The PR achieves it in a bit different manner than it is done for Webpack. The central idea here and difference from Webpack is that every `/VAADIN/` request ends up cached for offline only after it has been requested once online. This approach has been taken because we don't want to perform any pre-scaning / pre-caching of the whole project during Vite startup for the sake of performance. This approach also appears to be in line with the Vite general concept that is, everything is processed on demand.

A brief overview of the PR's changes:

- [x] Configured a `NetworkFirst` strategy handler (caches everything at runtime) for `/VAADIN/*` requests in the service worker. The runtime cache gets cleaned on every service worker `activate` event.
- [x] Added a `NetworkFirst` strategy handler for `/index.html` that activates when the offline fallback path points to `index.html`. In other cases, Flow defines the offline fallback path in the manifest which leads to its pre-caching).
- [x] `/VAADIN/__vite_ping` requests are refused when offline to prevent a recurring page reload.
- [x] ~~Configured a watcher that triggers re-building for the service worker for the case when the user has a custom service worker.~~ (Reverted)
- [x] Added tests on the basic PWA app with Vite in dev mode

Fixes https://github.com/vaadin/flow/issues/12383

## Type of change

- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

2022-02-09 09:20 UTC, vursen commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw.ts
> +self.skipWaiting();
https://developers.google.com/web/tools/workbox/modules/workbox-core#the_skipwaiting_wrapper_is_deprecated

> For these reasons, workbox-core's skipWaiting() is deprecated, and developers should switch to calling self.skipWaiting() directly. Unlike with self.clients.claim(), self.skipWaiting() will not throw an exception if called at the "wrong" time, so there is no need to wrap it in an event handler.

2022-02-15 17:07 UTC, platosha reviewed
Missing source maps for `sw.js` in dev mode for some reason.

I tried enabling them by adding the `bundle.write({sourcemap: true})` option, but this resulted in an empty source map file in the output and served.

2022-02-15 17:07 UTC, platosha commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw.ts
> +if (process.env.NODE_ENV === 'development') {
Tried this with webpack, seems that currently it alters the dev mode offline behaviour also for webpack.

How about adding some env flag, so that we only change the dev mode behaviour for Vite?

2022-02-17 07:28 UTC, vursen commented on flow-server/src/main/resources/vite.generated.ts
> +      // })
It was only for testing purposes. Reverted it back.

2022-02-17 07:30 UTC, vursen commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw.ts
> +if (process.env.NODE_ENV === 'development') {
Good point, added a flag `VITE_ENABLED`. Not sure about the naming, let me know if you would like to use a different one.

2022-02-17 09:42 UTC, vursen commented on flow-server/src/main/resources/vite.generated.ts
> +            if (id.endsWith('sw.ts')) {
```suggestion
            if (id.endsWith('/sw.ts')) {
```

2022-02-18 17:07 UTC, vursen commented on flow-server/src/main/resources/vite.generated.ts
> +          }
ignore

2022-02-18 17:07 UTC, vursen commented on flow-server/src/main/resources/vite.generated.ts
> +          }
@sonatype-lift ignore

2022-02-18 17:08 UTC, vursen commented on flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDeviceTest.java
> +            String jsonString = json.toString();
@sonatype-lift ignore

2022-02-21 08:23 UTC, Artur- requested changes

2022-02-21 08:23 UTC, Artur- commented on flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
> +            mutableCapabilities.setCapability("se:cdp", devtoolsUrl);
Can't these be set before creating the original driver instead without using any reflection?
E.g. 
```
chromeOptions.setCapability("se:cdp", devtoolsUrl);
```

2022-02-21 08:23 UTC, Artur- commented on flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
> +     * Note, there is already a CDP connection provided by {@class DevTools} but
```suggestion
     * Note, there is already a CDP connection provided by {@link DevTools} but
```

2022-02-21 10:54 UTC, vursen commented on flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
> +            mutableCapabilities.setCapability("se:cdp", devtoolsUrl);
It would be great. However, it doesn't seem possible since it requires `sessionId` that becomes only available after a session is created. I also looked up if there is a template format, but didn't find anything like that.

Anyway, I decided to move this workaround back to `ChromeDeviceTest.java` where the web driver initializes as this somewhat feels to be a more appropriate place for it.

2022-02-21 10:56 UTC, vursen commented on flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
> +            System.err.println(
Good point, throwing the runtime exception now.

2022-02-21 10:56 UTC, vursen commented on flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
> +     * Note, there is already a CDP connection provided by {@class DevTools} but
Fixed.

2022-02-22 08:29 UTC, platosha approved these changes

2022-02-22 08:32 UTC, Artur- submitted a review, later dismissed

2022-02-22 10:11 UTC, Artur- approved these changes

2022-02-22 10:48 UTC, merged

2022-02-22 11:14 UTC, Artur- commented
This should not be picked after all