chore: do not import modules of featured-flag components
vaadin/flow pull request #12993
Opened 2022-02-11 06:43 UTC by manolo

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-02-11 10:11 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ClassFinder.java
> +            return excludedClasses != null ? excludedClasses
Maybe wrap this with `Collections.unmodifiableList`

2022-02-11 10:12 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
> +            "com.vaadin.flow.server.frontend.NodeTestComponents$ExampleExperimentalComponent");
We probably should really remove this EXAMPLE feature, but could be in a separate PR.

2022-02-11 10:20 UTC, manolo commented on flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
> +            "com.vaadin.flow.server.frontend.NodeTestComponents$ExampleExperimentalComponent");
yes it needs more work because it's used in tests. So it's worth a separated PR for mocking correctly the Feature

2022-02-11 10:25 UTC, manolo commented on flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
> +            "com.vaadin.flow.server.frontend.NodeTestComponents$ExampleExperimentalComponent");
done

2022-02-11 10:47 UTC, manolo commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ClassFinder.java
> +            return excludedClasses != null ? excludedClasses
done: storing it in the class as unmodifialble.

2022-02-14 11:49 UTC, Artur- requested changes

2022-02-14 11:49 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
> +                f.setEnabled(Boolean.valueOf(
How is this related to the change? Won't it break if the value is "foo" and the old one did not?

2022-02-14 11:49 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
> +                    .filter(c -> !experimental.contains(c.getName()))
Why should this be `contains` and not `equals`?

2022-02-14 11:49 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ClassFinder.java
> +    void setExcludedClassNames(List<String> classNames);
Looks to me like you are completely breaking the architecture here. A ClassFinder is immutable and you are changing this only to be able to use ClassFinder as a way to pass data from one class to another class. ClassFinder does not even use the data. Surely there is a better way?

Maybe it can be done in `FrontendDependenciesScannerFactory.createScanner`

2022-02-15 06:49 UTC, manolo commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
> +                    .filter(c -> !experimental.contains(c.getName()))
experimental is a list, then I want to know whether the current class to be visited is in the list, or I don't understand what it's your suggestion. What should the code look like then?

2022-02-15 06:53 UTC, manolo commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ClassFinder.java
> +    void setExcludedClassNames(List<String> classNames);
well, probably it's not the best way,  but I found this way simpler because class-finder is a utility class that is passed always in all implementations, I didn't consider that it should be inmutable. Tough I'll give try to the way you propose.

2022-02-15 07:00 UTC, manolo commented on flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
> +                f.setEnabled(Boolean.valueOf(
It's unrelated to this PR, it just cause surprise to me not use the Boolean api to know whether a string is actually true or TRUE, everything else is false, like the previous code. So the only change here is that we now also accept uppercase in the true string.
"foo" always return false in previous code and use the Boolean API.
But I can revert this change if you are not confident with, not a big deal

2022-02-15 07:01 UTC, manolo commented on flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
> +                f.setEnabled(Boolean.valueOf(
It's unrelated to this PR, it just cause surprise to me not use the Boolean api to know whether a string is actually true or TRUE, everything else is false, like the previous code. So the only change here is that we now also accept uppercase in the true string.
"foo" always return false in previous code and use the Boolean API.
But I can revert this change if you are not confident with, not a big deal

2022-02-15 07:15 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
> +                    .filter(c -> !experimental.contains(c.getName()))
Looks like I misread the code and interpreted it as comparing the name

2022-02-15 08:46 UTC, manolo commented on flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
> +                f.setEnabled(Boolean.valueOf(
added a 'foo' test

2022-02-15 08:46 UTC, manolo commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ClassFinder.java
> +    void setExcludedClassNames(List<String> classNames);
reverted classFinder and moved logic to scanners,

2022-02-15 10:23 UTC, Artur- approved these changes

2022-02-15 12:10 UTC, merged