WIP: feat: use Vaadin component container bundles in Vite dev mode
vaadin/flow pull request #13039
Opened 2022-02-16 07:59 UTC by platosha

Fixes #12941

2022-02-18 14:40 UTC, Artur- commented
Tested in Start with the following issue:
```
Uncaught SyntaxError: The requested module '/VAADIN/@fs/.../node_modules/@vaadin/vaadin-lumo-styles/all-imports.js?v=51a2d3b5' does not provide an export named 'badge'
```

originates from
```
import { badge } from '@vaadin/vaadin-lumo-styles';
```
in the generated theme js

and http://localhost:8080/VAADIN/@fs/.../node_modules/@vaadin/vaadin-lumo-styles/all-imports.js?v=51a2d3b5 contains 
```
import { init as VaadinBundleInit, get as VaadinBundleGet } from '/VAADIN/@fs/Users/artur/workspace/vaadin/start/node_modules/@vaadin/bundles/vaadin.js?v=51a2d3b5';
await VaadinBundleInit('default');
const {  } = (await VaadinBundleGet('./node_modules/@vaadin/vaadin-lumo-styles/all-imports.js'))();
export {  };
```

Likely a problem with the `@vaadin/bundles` `v23.0.0-beta2` as `vaadin-bundle.json` does not contain `badge.js` and it contains
```
        "./all-imports.js": {
          "exports": []
        },
```

2022-02-21 11:43 UTC, Artur- requested changes

2022-02-21 11:43 UTC, Artur- commented on flow-server/src/main/resources/vite.generated.ts
> +
Is there a reason that `vaadinBundleJson` is not read and parsed here? Makes it a bit more difficult to follow the code

2022-02-21 11:43 UTC, Artur- commented on flow-server/src/main/resources/vite.generated.ts
> +            '@vaadin/router',
Why should this and nothing else be excluded? It looks very random here

2022-02-21 11:43 UTC, Artur- commented on flow-server/src/main/resources/vite.generated.ts
> +            '@polymer/iron-meta',
What does this really mean? Is it a Vite bug? Something else?

2022-02-21 11:43 UTC, Artur- commented on flow-server/src/main/resources/vite.generated.ts
> +    name: 'vaadin-bundle',
If this would happen to not work in my project, is there a way to disable it until the problem has been fixed? Can I remove the bundles plugin in my vite.config.ts?

2022-02-21 15:05 UTC, platosha commented on flow-server/src/main/resources/vite.generated.ts
> +    name: 'vaadin-bundle',
Doing so requires an ugly workaround to filter-out the plugin as of now.

Unfortunately, Vite config structure (and Rollup in general) does not seem to be friendly to passing options down to custom plugins defined elsewhere.

Some options on my mind:
- Add a custom Vaadin options argument in `overrideVaadinConfig` and add expose an option there. Would probably be most user-friendly, with TypeScript typings.
- Release a special version tag to use with the npm package version overrides: `npm install --save-dev @vaadin/bundles#optout` installs an empty package, then the plugin disables itself.

2022-02-21 15:12 UTC, Artur- commented on flow-server/src/main/resources/vite.generated.ts
> +    name: 'vaadin-bundle',
For now I think an ugly workaround is enough

2022-02-21 15:31 UTC, platosha commented on flow-server/src/main/resources/vite.generated.ts
> +            '@polymer/iron-meta',
This was fixed in the Vaadin bundles build. Removed those.

2022-02-21 15:33 UTC, platosha commented on flow-server/src/main/resources/vite.generated.ts
> +    name: 'vaadin-bundle',
Yes, however it’s a bit quirky to filter-out a plugin from the generated config list. We should probably provide a more friendly way than that. How about:

- An argument in the `overrideVaadinConfig` with a custom option exposed to disable Vaadin bundles
- A special version tag for the npm package, so that when you depend on `@vaadin/bundles#optout`, then it installs an empty stub and disables the plugin.

2022-02-21 15:53 UTC, platosha commented on flow-server/src/main/resources/vite.generated.ts
> +        'generated/vaadin.ts'
Does not make, I think. It has no dependencies, nothing to optimize there.

2022-02-21 15:56 UTC, platosha commented on flow-server/src/main/resources/vite.generated.ts
> +
I used async file IOs for that, but now thinking more, probably sync ones would work just fine. Done.

2022-02-21 15:59 UTC, platosha commented on flow-server/src/main/resources/vite.generated.ts
> +            '@vaadin/router',
Moved into the general config section, does not make sense in the plugin context indeed.

Still makes sense to exclude the router in general, I think, it is rolled up already.

2022-02-22 07:37 UTC, Artur- commented
Something broke `BundlesIT` in the last set of changes

2022-02-22 10:23 UTC, vursen commented on flow-server/src/main/resources/vite.generated.ts
> +import path
The formatting is broken.

2022-02-22 10:24 UTC, vursen commented on flow-server/src/main/resources/vite.generated.ts
> +  function resolveVaadinBundleJsonPath() {
**nit:** Empty function.

2022-02-22 10:25 UTC, vursen commented on flow-server/src/main/resources/vite.generated.ts
> +      preserveSymlinks: true,
Is it necessary after all?

2022-02-22 10:30 UTC, platosha commented on flow-server/src/main/resources/vite.generated.ts
> +      preserveSymlinks: true,
it simplifies the loader, currently it just matches the path after `./node_modules` against the bundle JSON.

2022-02-22 11:16 UTC, Artur- approved these changes

2022-02-22 11:24 UTC, merged