fix: use vaadin-core to check platform update
vaadin/flow pull request #13059
Opened 2022-02-17 10:26 UTC by joheriks

To decide whether the platform has been updated, compare
the version of vaadin-core in package.json with the platform
published version. Was previously using vaadin-shrinkwrap,
which is removed in V23.

Part of #13008

2022-02-17 10:34 UTC, caalador approved these changes

2022-02-17 10:36 UTC, Artur- commented
What is `@vaadin/vaadin-core` used for as you do not typically ever have that as a dependency?

2022-02-17 10:42 UTC, Artur- commented
If it is about knowing which version installed `node_modules`, why don't we write the Flow version into `node_modules/.vaadin/vaadin.json` e.g.
```
{
  "hash": "d4e92e3e993a8edd30596cf4d06dbc632cafe53573253c110f1c97fe26ce7120",
  "flowVersion": "23.0.1"
}
```
or the Vaadin version if that is the relevant one?

2022-02-17 11:02 UTC, caalador commented
`@vaadin/vaadin-core` is always available as it is brought in by `@vaadin/vaadin` or if you depend on vaadin-core for the free components 
Also the feature is explicitly for when the platform version has updated not flow so we shouldn't depend on flow as it may stay on the same patch version if platform releases for only components changes.

2022-02-17 11:04 UTC, Artur- commented
Nobody is depending on `@vaadin/vaadin` either

2022-02-17 11:05 UTC, Artur- commented
What is special about upgrading a platform version compared to updating anything by hand in package.json?

2022-02-17 11:17 UTC, caalador commented
Humm... What project was I looking at because I did always get the vaadin packages in that one.

The main reason for this has been that upgrading platform version broke the node_modules more often than acceptable.

2022-02-17 11:31 UTC, joheriks commented
Next attempt will be to add platform version to `node_modules/.vaadin/vaadin.json` and compare against that then.

2022-02-17 20:59 UTC, joheriks commented
Now doing it like that, ready for review again.

2022-02-18 06:08 UTC, caalador requested changes

2022-02-18 06:08 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
> +        // TODO: Fixme
I feel this test is not needed as it now stands

2022-02-18 07:27 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/Platform.java
> +                    versionErrorLogged = true; // NOSONAR
nit: NOSONAR should no longer needed here as the method is static

2022-02-18 09:03 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +     * vaadin-core version, then version is considered updated.
Good catch, the above code would actually delete `package-lock.json` on initial install which slows things down. Modified to return false when `node_modules` is absent.

2022-02-18 09:03 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/Platform.java
> +                    versionErrorLogged = true; // NOSONAR
Done.

2022-02-18 09:03 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
> +            if (content != null && content.hasKey(HASH_KEY)) {
Done.

2022-02-18 09:03 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +            return null;
Done.

2022-02-18 09:07 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +                    || !vaadinJsonContents.hasKey(NodeUpdater.VAADIN_VERSION)) {
```suggestion
            if (!vaadinJsonContents.hasKey(NodeUpdater.VAADIN_VERSION)) {
```
Null check is not needed as we always get a JsonObject.

2022-02-18 09:12 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +                    || !vaadinJsonContents.hasKey(NodeUpdater.VAADIN_VERSION)) {
Thanks, missed it. Done.

2022-02-18 11:10 UTC, caalador approved these changes

2022-02-18 11:12 UTC, merged

2022-02-21 09:36 UTC, joheriks commented
Picked in #13099