refactor: make Webpack use web-component.html
vaadin/flow pull request #13165
Opened 2022-02-27 19:58 UTC by vursen

## Description

WIP

A follow-up to #13148 

## Type of change

- [x] Refactoring

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

2022-03-15 11:18 UTC, Artur- commented
Rebased to get rid of all the extra commits. Still needs some work though

2022-04-20 13:26 UTC, Artur- commented on flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
> +    @Ignore("Ignored until it is known how the bootstrap is compiled in ts mode")
What does this mean?

2022-04-21 07:31 UTC, Artur- commented
One test fails: https://github.com/vaadin/flow/blob/master/flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/NpmOnlyIndexIT.java#L48

This counts the number of `style` tags inside the exported wc. Is this supposed to change or is it a problem in the new implementation? It likely affects the Vite version as well...

2022-04-21 08:29 UTC, Artur- commented
The old version has
```
<style>
      :host {
        position: relative;
        display: inline-block;
      }
    </style>

<style type="text/css">body {height:100vh;width:100%;margin:0;}.v-reconnect-dialog,.v-system-error {position: absolute;color: black;background: white;top: 1em;right: 1em;border: 1px solid black;padding: 1em;z-index: 10000;max-width: calc(100vw - 4em);max-height: calc(100vh - 4em);overflow: auto;} .v-system-error {color: indianred;pointer-events: auto;} .v-system-error h3, .v-system-error b {color: red;}</style>
```

The new version has only the first one
```
<style>
      :host {
        position: relative;
        display: inline-block;
      }
    </style>
```

Should the second one be there or not?

2022-04-21 08:52 UTC, caalador commented
Looking at issue #7005 I would expect that the second styling should be available.

2022-04-21 08:55 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
> +    @Ignore("Ignored until it is known how the bootstrap is compiled in ts mode")
It's means that figuring out how the `web-component.html` is built for the new version as right now it uses a premade html with a export...js. So the probelm is 2 things:
- figure out how the web-component.html get generated so we can generate it for the tests
- figure out how to the bundle is decided so that we can get either vaadin-export... or vaadin-bundle... into the html

2022-04-25 11:51 UTC, mshabarov commented
@vursen do you need a help with this feature and move it forward?

2022-04-25 12:00 UTC, vursen commented
It is actually a leftover refactoring of the Vite 6-weeks project that I haven't managed to finish due to lack of time.

The refactoring is mainly done, the only problem is the tests that are currently failing. They apparently rely on some `BootstrapHandler`-specific API and check chunk statistics while it is no longer used with the new approach, so some adaptation is needed to fix them.

2022-05-06 07:43 UTC, Artur- commented
The excluded CSS consists of two parts:
```
body {height:100vh;width:100%;margin:0;}
```
and
```
.v-reconnect-dialog,.v-system-error {position: absolute;color: black;background: white;top: 1em;right: 1em;border: 1px solid black;padding: 1em;z-index: 10000;max-width: calc(100vw - 4em);max-height: calc(100vh - 4em);overflow: auto;} .v-system-error {color: indianred;pointer-events: auto;} .v-system-error h3, .v-system-error b {color: red;}
```

The first certainly does not make sense to include in exported web components. An exported web component should not change body styles.

The second part should probably be included

2022-05-07 10:50 UTC, Artur- commented
I would assume this is ready to review then. Fixes the system-error styles with Vite also

2022-05-09 06:46 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
> +    @Ignore("Ignored until it is known how the bootstrap is compiled in ts mode")
This test should be removed if it no longer makes any sense.

2022-05-12 06:23 UTC, Artur- commented on flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
> +    @Ignore("Ignored until it is known how the bootstrap is compiled in ts mode")
Should it just be removed then? Does it make any sense?

2022-05-19 18:09 UTC, taefi requested changes

2022-05-19 18:09 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
> +    @Ignore("Ignored until it is known how the bootstrap is compiled in ts mode")
According to what I understood so far, I suggest changing this test's name to something like `writeBootstrapPage_alwaysExpectExportChunk()` and changing the `assert` to verify the existence of `/VAADIN/build/vaadin-export-...` instead.

2022-05-23 08:36 UTC, Artur- submitted a review, later dismissed
I think everybody involved has both coded and reviewed now. If there anything that is blocking still, please comment quickly :)

2022-05-23 11:32 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
> +    public void writeBootstrapPage_alwaysExpectExportChunk()
Seeing that this is exactly the same as the test `writeBootstrapPage_withExportChunk` above with the exception of
`config.setApplicationOrSystemProperty(SERVLET_PARAMETER_STATISTICS_JSON, VAADIN_SERVLET_RESOURCES + "config/stats_no_export.json");`  which I guess is a property not used in the new version the test should just be removed.

2022-05-23 11:41 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
> +    public void writeBootstrapPage_alwaysExpectExportChunk()
Exactly, the only difference is that property which seems to be no longer in use. I'll remove the test.

2022-05-23 11:42 UTC, Artur- approved these changes

2022-05-23 12:44 UTC, caalador approved these changes

2022-05-24 05:50 UTC, Artur- commented
@taefi is still blocking this?

2022-05-24 06:39 UTC, taefi approved these changes

2022-05-24 06:39 UTC, merged

2022-05-25 06:15 UTC, mshabarov commented
This change caused an issues in Vaadin Portlet, since it is based on embedded web components, uses a customised WebComponentBootstrapRenderer and probably doesn't work well with Vite.

Vaadin Portlet throws the following exceptions and doesn't render the content:

```
[INFO] [talledLocalContainer] Caused by: com.vaadin.flow.server.ServiceException: java.lang.NullPointerException
[INFO] [talledLocalContainer]   at com.vaadin.flow.server.VaadinService.handleExceptionDuringRequest(VaadinService.java:1613) ~[flow-server-23.1-SNAPSHOT.jar:23.1-SNAPSHOT]
[INFO] [talledLocalContainer]   at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
[INFO] [talledLocalContainer]   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732)
[INFO] [talledLocalContainer]   at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1576) ~[flow-server-23.1-SNAPSHOT.jar:23.1-SNAPSHOT]
[INFO] [talledLocalContainer]   at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
[INFO] [talledLocalContainer]   at com.vaadin.flow.portal.VaadinPortlet.handleRequest(VaadinPortlet.java:397) ~[vaadin-portlet-2.0-SNAPSHOT.jar:?]
[INFO] [talledLocalContainer]   ... 165 more
[INFO] [talledLocalContainer] Caused by: java.lang.NullPointerException
[INFO] [talledLocalContainer]   at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
[INFO] [talledLocalContainer]   at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
[INFO] [talledLocalContainer]   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[INFO] [talledLocalContainer]   at java.base/java.lang.Thread.run(Thread.java:834)
[INFO] [talledLocalContainer]   at java.io.StringReader.<init>(StringReader.java:50) ~[?:?]
[INFO] [talledLocalContainer]   at org.jsoup.parser.Parser.parse(Parser.java:130) ~[jsoup-1.14.3.jar:?]
[INFO] [talledLocalContainer]   at org.jsoup.Jsoup.parse(Jsoup.java:75) ~[jsoup-1.14.3.jar:?]
[INFO] [talledLocalContainer]   at com.vaadin.flow.server.communication.WebComponentBootstrapHandler$WebComponentBootstrapPageBuilder.getBootstrapPage(WebComponentBootstrapHandler.java:113) ~[flow-server-23.1-SNAPSHOT.jar:23.1-SNAPSHOT]
[INFO] [talledLocalContainer]   at com.vaadin.flow.server.communication.WebComponentBootstrapHandler.synchronizedHandleRequest(WebComponentBootstrapHandler.java:269) ~[flow-server-23.1-SNAPSHOT.jar:23.1-SNAPSHOT]
[INFO] [talledLocalContainer]   at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-23.1-SNAPSHOT.jar:23.1-SNAPSHOT]
[INFO] [talledLocalContainer]   at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1564) ~[flow-server-23.1-SNAPSHOT.jar:23.1-SNAPSHOT]
[INFO] [talledLocalContainer]   at com.vaadin.flow.portal.VaadinPortlet.handleRequest(VaadinPortlet.java:397) ~[vaadin-portlet-2.0-SNAPSHOT.jar:?]
[INFO] [talledLocalContainer]   ... 165 more
``` 

and in the browser's console:

`Refused to execute script from 'http://localhost:8080/test?p_p_id=MyPortlet1_WAR_portletstarter&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_resource_id=%2Fweb-component%2Fweb-component-ui.js&p_p_cacheability=cacheLevelPage?url=http://localhost:8080/test?p_p_id=MyPortlet1_WAR_portletstarter&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_resource_id=%2Fweb-component%2Fweb-component-ui.js&p_p_cacheability=cacheLevelPage' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.`

Reverted in https://github.com/vaadin/flow/pull/13857 . Need further investigation.