feat: Add scrollIntoView method to Component
vaadin/flow pull request #13179
Opened 2022-03-01 09:51 UTC by mstahv

## Description

This change adds back a scrollIntoView method that we had in past framework versions.

The implementation is a trivial shorthand to the similarly named DOM method, and very handy in UI development.
It has been requested by multiple SoF and forum users, but apparently nobody wants to write this trivial enhancement issues as I couldn't find an existing issue for this.

The implementation leaves door open for overloading the method with a version with additional parameters, but already this method should solve most use cases.

## Type of change

- [ ] Bugfix
- [x] Feature

2022-03-08 11:38 UTC, joheriks requested changes

2022-03-08 11:38 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/component/Component.java
> +        getElement().callJsFunction("scrollIntoView");
1. Would it make sense to add `scrollIntoView` also to the `com.vaadin.flow.dom.Element` API and delegate to that?

2. What is the precondition for calling this method? When the component is not attached, e.g. in a constructor, the JS invocation is postponed until the component is attached but it does not scroll still. It also does not work when called from an attachlistener. It could either be documented that the caller must ensure the page is fully rendered before calling this method, or the scrolling action should be deferred somehow.

2022-03-08 11:39 UTC, joheriks commented
Should be rebased.

2022-03-09 12:23 UTC, mstahv commented on flow-server/src/main/java/com/vaadin/flow/component/Component.java
> +        getElement().callJsFunction("scrollIntoView");
Don't really know why it didn't work on new instances, but setTimeout hack fixed it. Moved the implementation to Element.

2022-03-10 12:12 UTC, caalador commented
I guess something went wrong with the rebase `+3,451 −2,208 `

2022-03-10 12:33 UTC, mstahv commented
I guess so, and now it shows conflicts 🤷‍♂️

2022-03-11 13:16 UTC, joheriks commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/scroll/ScrollableView.java
> + * Copyright 2000-2021 Vaadin Ltd.
```suggestion
 * Copyright 2000-2022 Vaadin Ltd.
```

2022-03-11 13:33 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/dom/Element.java
> +                "var el = this; setTimeout(function() {el.scrollIntoView();}, 0);");
I guess this works because the JS is deferred long enough until the page rendering has stabilized. Looks fine to me, but should be tested on the major browsers. Which have you tested so far?  I will test the rest.

2022-03-11 15:56 UTC, mstahv commented on flow-server/src/main/java/com/vaadin/flow/dom/Element.java
> +                "var el = this; setTimeout(function() {el.scrollIntoView();}, 0);");
Safari, Chrome, FF on Mac.

2022-03-14 08:00 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/dom/Element.java
> +                "var el = this; setTimeout(function() {el.scrollIntoView();}, 0);");
Also tested Windows Edge and iOS Safari, seemed to scroll fine.

2022-03-14 08:02 UTC, joheriks approved these changes

2022-03-14 08:04 UTC, merged