fix: Do not load service worker with Vite in 23.0
vaadin/flow pull request #13209
Opened 2022-03-04 11:31 UTC by Artur-

Vite does not serve a service worker in 23.0. It has already been fixed for 23.1 in https://github.com/vaadin/flow/pull/12857 and https://github.com/vaadin/flow/pull/12928

Fixes #13201

2022-03-05 10:34 UTC, vursen commented
As I see, this PR disables the service worker completely for Vite in 23.0 so that it will work neither in prod nor in dev mode. If going this way, any tests testing Vite PWAs don't make sense anymore and should be dropped in this branch.

2022-03-05 10:36 UTC, vursen commented on flow-tests/test-frontend/vite-pwa-production-custom-offline-path/src/test/java/com/vaadin/viteapp/MainIT.java
>      public void init() {
These tests don't make sense if disabling the service worker completely for Vite.

2022-03-05 10:36 UTC, vursen commented on flow-tests/test-frontend/vite-pwa-production/src/test/java/com/vaadin/viteapp/MainIT.java
> -        waitForServiceWorkerReady();
These tests don't make sense if disabling the service worker completely for Vite.

2022-03-07 06:57 UTC, Artur- commented
> As I see, this PR disables the service worker completely for Vite in 23.0 so that it will work neither in prod nor in dev mode. If this is the case, any tests testing Vite PWAs don't make sense anymore and should be dropped in this branch.

It was unclear to me what actually works in 23.0 regarding Vite + service worker. Does a production build work? In dev mode it does not work at all and there are two PRs that are not included: one for dev and one for production

2022-03-07 07:23 UTC, vursen commented
> It was unclear to me what actually works in 23.0 regarding Vite + service worker. Does a production build work? In dev mode it does not work at all and there are two PRs that are not included: one for dev and one for production

Well, it seems that offline should work in production mode in 23.0 because the relevant fix has landed that version: https://github.com/vaadin/flow/commit/3cdb280b460f880be227558c61ae7d642d87c606

It shouldn't work in dev mode though because it was considered a feature and therefore has not been added in 23.0, as far as I understand it.

2022-03-07 09:53 UTC, Artur- commented
So should this PR be limited to disabling it in dev mode?

2022-03-07 10:02 UTC, vursen commented
> So should this PR be limited to disabling it in dev mode?

From my point of view, yes, it should.

2022-03-07 10:07 UTC, vursen requested changes

2022-03-07 10:07 UTC, vursen commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +                && !config.isProductionMode()) {
```suggestion
        if (!FeatureFlags.get(service.getContext()).isEnabled(FeatureFlags.VITE)
                || config.isProductionMode()) {
```

2022-03-07 10:07 UTC, vursen commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +                    && !config.isProductionMode()) {
```suggestion
            if (!FeatureFlags.get(context.getService().getContext())
                    .isEnabled(FeatureFlags.VITE)
                    || config.isProductionMode()) {
```

2022-03-07 19:16 UTC, vursen approved these changes

2022-03-08 07:37 UTC, merged