chore: Change debug level to info as this logging is frequent in harmless cases
vaadin/flow pull request #13400
Opened 2022-03-31 09:17 UTC by TatuLund

Closes: https://github.com/vaadin/flow-components/issues/1157

2022-03-31 09:47 UTC, Artur- commented
Should this even be `info` or is it `debug` logging?

2022-04-04 11:38 UTC, mshabarov requested changes

2022-04-04 11:38 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
> +            getLogger().info("Ignoring RPC for non-existent node: {}",
This looks like hiding the problem, but not fixing. 
I would start with figuring out why does clicking a button ends up with "node not found" errors on the server side.
Data filtering looks not related from the first glance.

2022-04-05 09:37 UTC, TatuLund commented on flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
> +            getLogger().info("Ignoring RPC for non-existent node: {}",
Removal of the component during the event process will result logging this warning, see the simplest case here https://github.com/vaadin/flow-components/issues/1157#issuecomment-1084318223

2022-04-05 09:40 UTC, TatuLund commented on flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
> +            getLogger().info("Ignoring RPC for non-existent node: {}",
Logging is correct, but too vocal as I am assuming that it is allowed to remove the TextField in its value change listener. If you think otherwise, we should clearly document that removal of the textField in its value change listener or other event triggered by the component itself is not allowed.

2022-04-05 10:36 UTC, tarekoraby commented on flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
> +            getLogger().info("Ignoring RPC for non-existent node: {}",
@TatuLund your [comment](https://github.com/vaadin/flow-components/issues/1157#issuecomment-1084318223) describes a situation in which the warning is a false positive. But are there other situations in which the warning would be a true positive, and hence would warrant the `warn` level?

2022-05-13 06:40 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
> +            getLogger().info("Ignoring RPC for non-existent node: {}",
If you get "Ignoring RPC for non-existent node" in your production log. What should you do? It sure sounds to me like info you would need while debugging a problem and not particularly care about in production. If everything works in production, it is a "false positive". If something is broken in production, the error message still gives you no way of finding out what is wrong and how to fix it

2022-05-17 12:30 UTC, mshabarov requested changes
@TatuLund I had an another and more deep look into `AbstractRpcInvocationHandler::handle` method. Changing `warn` to `debug` seems a fine solution, because:
1. When the `node` does not exist on the server state tree, the server basically has no information why, therefore it cannot decide whether log the message and what level to choose, and what do with it in the end.
2. When the `node` is detached, IMO it doesn't make sense to figure out why it is detached. We can probably check if the `node` corresponds to `HasValue` component, but it is a "private" case when such a warnings occur.
3. As Artur said, and I agree with him, these warn message doesn't give a clear understanding of what is broken or what's wrong with the caller's code. But it can be useful for development, debugging or anomaly investigation.
So in short I propose to set `debug` level and apply this patch.

2022-05-17 13:39 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
> +            getLogger().info("Ignoring RPC for non-existent node: {}",
```suggestion
            getLogger().debug("Ignoring RPC for non-existent node: {}",
```

2022-05-17 13:39 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
> +            getLogger().info("Ignoring RPC for detached node: {}",
```suggestion
            getLogger().debug("Ignoring RPC for detached node: {}",
```

2022-05-18 13:47 UTC, mshabarov approved these changes

2022-05-18 14:54 UTC, merged