chore: exclude commons-codec from httpClient
vaadin/flow pull request #13481
Opened 2022-04-11 06:35 UTC by ZheSun88

this current dependency setting failed in platform 
[link](https://bender.vaadin.com/viewLog.html?buildId=299463&buildTypeId=VaadinPlatform_TestReleasePlatformSnapshotToMavenVaadinPrerelease&tab=buildLog)

let us exclude this version properly. 

```
	[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce) @ vaadin ---
[08:59:47]	[INFO] artifact org.webjars.npm:mobile-drag-drop: checking for updates from central
[08:59:47]	[INFO] artifact org.webjars.npm:mobile-drag-drop: checking for updates from vaadin-prereleases
[08:59:47]	[WARNING] 
[08:59:47]	Dependency convergence error for commons-codec:commons-codec:1.11 paths to dependency are:
[08:59:47]	+-com.vaadin:vaadin:14.8-SNAPSHOT
[08:59:47]	  +-com.vaadin:vaadin-core:14.8-SNAPSHOT
[08:59:47]	    +-com.vaadin:flow-server:2.7-SNAPSHOT
[08:59:47]	      +-org.apache.httpcomponents:httpclient:4.5.13
[08:59:47]	        +-commons-codec:commons-codec:1.11
[08:59:47]	and
[08:59:47]	+-com.vaadin:vaadin:14.8-SNAPSHOT
[08:59:47]	  +-com.vaadin:vaadin-core:14.8-SNAPSHOT
[08:59:47]	    +-com.vaadin:flow-server:2.7-SNAPSHOT
[08:59:47]	      +-commons-codec:commons-codec:1.15
[08:59:47]	
```

2022-04-11 07:22 UTC, Artur- commented
Is this really a problem only in 2.7?

2022-04-11 07:25 UTC, ZheSun88 commented
@Artur-  this has only been reported in V14.8 (flow 2.7-SNAPSHOT), though the same change has been in other branches.

2022-04-11 11:04 UTC, mshabarov submitted a review, later dismissed

2022-04-11 11:10 UTC, Artur- requested changes
All changes to master except those that should never go into master

2022-04-11 11:51 UTC, ZheSun88 commented
made PR #13485 to master branch

2022-04-12 06:29 UTC, mshabarov approved these changes

2022-04-13 08:59 UTC, Artur- approved these changes

2022-04-13 08:59 UTC, merged