chore: pass watchdog ip address to dev server process
vaadin/flow pull request #13506
Opened 2022-04-12 08:04 UTC by mcollovati

## Description

Dev server monitors watchdog port on localhost to be sure that Java process
is running, otherwise it kills itself.
It could happend that Java and Node processes resolve localhost ip
address differently (ipv4 vs ipv6), for example when using Node 17 and
setting Java system property `-Djava.net.preferIPv4Stack=true`.
This change resolves the ip address in Java process and provides it to
the node process so it will bind to the correct address.
## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [X] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [X] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [X] New and existing tests are passing locally with my change.
- [X] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-04-12 08:17 UTC, mcollovati commented
Should fix issues like the one described in vaadin/skeleton-starter-flow-cdi#406

2022-04-13 13:05 UTC, taefi submitted a review, later dismissed

2022-04-13 13:28 UTC, taefi requested changes
Changes look fine, but consider adding tests for the change in AbstractDevServerRunner

2022-04-14 12:56 UTC, taefi approved these changes

2022-04-14 12:57 UTC, merged