feat: Add Binder.updateFields()
vaadin/flow pull request #13535
Opened 2022-04-13 12:41 UTC by tarekoraby

2022-04-13 16:47 UTC, knoobie commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +    public void updateFields() {
Instead of update fields, I would suggest refresh fields :) nevertheless huge +1.. I have a custom binder in all my applications with a similar method as well

2022-04-14 06:32 UTC, tarekoraby commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +    public void updateFields() {
I'm neutral between using "update" and "refresh". I can change it if the majority thinks "refresh" is better.

2022-04-14 09:42 UTC, taefi commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +    public void updateFields() {
I'm also in favor of `refreshFields` or even `refreshFieldsValues` ;)

2022-04-14 09:46 UTC, tarekoraby commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +    public void updateFields() {
`refreshFields` it is 👍

2022-04-19 10:01 UTC, taefi requested changes

2022-04-19 10:01 UTC, taefi commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +     */
```suggestion
    /**
     * Refreshes the fields values by reading them again from
     * the currently associated bean via invoking their 
     * corresponding value provider methods. 
     * <p>
     * If no bean is currently associated with this binder ( 
     * {@link #setBean(Object)} has not been called before 
     * invoking this method), the bound fields will be cleared.
     * <p>
     * @see #setBean(Object)
     * @see #readBean(Object)
     * @see #writeBean(Object)
     * @see #writeBeanIfValid(Object)
     */
```

2022-04-25 11:45 UTC, mshabarov commented
@tarekoraby please merge current master to your branch

2022-04-27 10:43 UTC, mshabarov approved these changes

2022-04-27 11:57 UTC, taefi approved these changes

2022-04-27 11:59 UTC, merged