fix: reusable themes with vite
vaadin/flow pull request #13543
Opened 2022-04-14 08:56 UTC by caalador

Fix resolution of reusable themes
when using vite

Fixes #13538

2022-04-14 10:19 UTC, taefi requested changes

2022-04-14 10:19 UTC, taefi commented on flow-server/src/main/resources/vite.generated.ts
> +const appShellUrl = '.'
I suggest keeping the semicolon :)
```suggestion
const appShellUrl = '.';
```

2022-04-14 10:19 UTC, taefi commented on flow-server/src/main/resources/vite.generated.ts
> +            if(existsSync(path.resolve(themeResourceFolder, importee))){
```suggestion
            if (existsSync(path.resolve(themeResourceFolder, importee))) {
```

2022-04-14 10:19 UTC, taefi commented on flow-server/src/main/resources/vite.generated.ts
> +        { find: 'Frontend', replacement: frontendFolder }
Where is this `'Frontend'` referring to?

2022-04-14 10:29 UTC, caalador commented on flow-server/src/main/resources/vite.generated.ts
> +        { find: 'Frontend', replacement: frontendFolder }
* A special prefix used by webpack to map imports placed in the
     * {@link FrontendUtils#DEFAULT_FRONTEND_DIR}. e.g.
     * <code>import 'Frontend/foo.js';</code> references the
     * file<code>frontend/foo.js</code>.

2022-04-14 10:29 UTC, caalador commented on flow-server/src/main/resources/vite.generated.ts
> +            if(existsSync(path.resolve(themeResourceFolder, importee))){
done

2022-04-14 10:29 UTC, caalador commented on flow-server/src/main/resources/vite.generated.ts
> +const appShellUrl = '.'
done

2022-04-14 11:36 UTC, caalador commented on flow-server/src/main/resources/vite.generated.ts
> +        { find: 'Frontend', replacement: frontendFolder }
So basically when you have the js annotation `@JsModule("./my-component.js")` it will be added to `generated-flow-imports.js` as `import 'Frontend/my-component.js';` which will then be modified by webpack/vite to target the correct directory so for instance `C:/Users/user1/flow/flow-tests/test-frontend/vite-basics/frontend/my-component.js`

2022-04-20 09:36 UTC, taefi approved these changes

2022-04-20 09:43 UTC, merged