fix: Optimize Binder#doWriteIfValid to avoid duplicate field level validations
vaadin/flow pull request #13597
Opened 2022-04-22 08:23 UTC by TatuLund

2022-04-25 06:50 UTC, OlliTietavainenVaadin commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +            boolean validatorsInUse = isValidatorsDisabled();
Variable name is inconsistent here; if `isValidatorsDisabled` returns true, I would expect validators not to be in use.

2022-04-25 10:18 UTC, TatuLund commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +            boolean validatorsInUse = isValidatorsDisabled();
Good catch

2022-04-26 12:07 UTC, simasch commented
When will this change be relased?

2022-04-26 15:58 UTC, taefi requested changes
@TatuLund Is there a chance that a field can get an invalid value between the first time bindings are checked and when the `writeFieldValue` is being called on all the bindings? Possibly it wouldn't be a case that an end-user can cause it, but some race condition, maybe!?

2022-04-27 10:24 UTC, taefi approved these changes

2022-04-27 10:25 UTC, merged

2022-05-03 13:15 UTC, simasch commented
If this fix is really in 23.1.0.alpha4 then it's not fixed!

2022-05-06 06:16 UTC, simasch commented
@TatuLund 
I was wrong. The fix works in a simple example. Sorry.