fix: ignore server-modality for poll RPC invocations (CP: #13604)
vaadin/flow pull request #13634
Opened 2022-04-27 13:16 UTC by taefi

Manual CP to 23.0 branch to exclude
the breaking changes of #13604

2022-04-28 08:27 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
> +                && !ignoreInertForPollInvocations(ui, invocationJson)) {
Method `ignoreInertForPollInvocations` should return `false` to pass into "ignoring RPC for inert" code block.
This is misleading.
I would expect something like below for conditional:

```
} else if (!allowInert(node) && node.isInert()
                && ignoreInertForPollInvocations(ui, invocationJson)) {
```

or

```
} else if ((!allowInert(node) && node.isInert()) ||
                ignoreInertForPollInvocations(ui, invocationJson)) {
```

(from the methods naming point of view and semantic)

2022-04-28 10:19 UTC, mshabarov requested changes

2022-04-28 10:19 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
> +                && !ignoreInertForPollInvocations(ui, invocationJson)) {
Maybe to reverse the returning values of `ignoreInertForPollInvocations`?

2022-05-03 08:19 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
> +                && !ignoreInertForPollInvocations(ui, invocationJson)) {
I think the previously existing block of code that logs "Ignored RPC for invocation ..." (regardless of the text being logged) is more of a "blocking" rather than an "ignoring", but I get with your point about the naming weirdness ;)

However, I would change the method name to something like `allowInvocationWhileInert` instead and not the return values nor the `if` conditions. I think this naming change should make the awkwardness go away :) Let me know if this is still not helping. 

Considering that having another method like `allowInert` is making the code confusing, I would mark it as deprecated if you show a thumbs up, as it doesn't clearly say what it does and has no javadoc. Its input parameters has already changed in the `master` (while keeping the same name, unfortunately). That also can/should be renamed to a more generic and self-descriptive name like `allowInvocationWhileInert` (but that is a separate issue).

2022-05-05 06:04 UTC, mshabarov approved these changes

2022-05-05 06:04 UTC, merged