feat: Support view access checking in background threads with Spring
vaadin/flow pull request #13675
Opened 2022-05-04 07:45 UTC by Artur-

Based on #13674

2022-05-11 12:17 UTC, mshabarov approved these changes

2022-05-11 14:19 UTC, mshabarov requested changes
```
Error:  Failures: 
Error:    SpringClassesSerializableTest>ClassesSerializableTest.classesSerializable:334->ClassesSerializableTest.serializeAndDeserialize:362 com.vaadin.flow.spring.AuthenticationHelper
```

2022-05-12 06:45 UTC, Artur- commented
Renamed the helper class to `Util` as this seems to be the common pattern

2022-05-12 06:59 UTC, mshabarov approved these changes

2022-05-12 09:48 UTC, merged