fix: Improve message sender / handler robustness in resync scenarios
vaadin/flow pull request #13733
Opened 2022-05-11 09:21 UTC by TatuLund

This PR is adopted from similar fixes for Vaadin 8

https://github.com/vaadin/framework/pull/11791
https://github.com/vaadin/framework/pull/12043
https://github.com/vaadin/framework/pull/12178

This is alternative and possibly more comprehensive fix than

https://github.com/vaadin/flow/pull/13727

2022-05-12 11:02 UTC, Artur- requested changes

2022-05-12 11:26 UTC, pepijnve commented
@TatuLund could you have a look at the changes I made in #13727 as well? I think a variant of that might still be useful. `forceMessageHandling` still calls `RequestResponseTracker#endRequest` which may already call `MessageSender#sendInvocationsToServer`. If that happens the later call to `MessageSender#resynchronize` will set the flag, but this will not actually get sent since a request may already be in progress. It might be a good idea to set the `resynchronizeRequested` first before triggering `endRequest`.

2022-05-12 11:36 UTC, TatuLund commented on flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java
> +    private boolean resynchronizeRequested = false;
Thanks for the question, that provoked me to make additional small change as endRequest was refactored away from MessageSender and I had overlooked that one.

2022-05-12 11:40 UTC, TatuLund commented
@pepijnve Yes, I had overlooked that part.

2022-05-12 13:26 UTC, TatuLund commented on flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
> +    private boolean resyncInProgress;
Done

2022-05-13 08:30 UTC, mshabarov commented on flow-client/src/main/java/com/vaadin/client/communication/RequestResponseTracker.java
> +                        .getResynchronizationState() == ResynchronizationState.SEND_TO_SERVER) {
Could you please elaborate more why is this condition needed here?
A single place where `SEND_TO_SERVER` is being set is in `resynchronize()` method.
`resynchronize()` method calls `sendInvocationsToServer()`.
So `sendInvocationsToServer()` should be already invoked when the code execution comes here.

Additionally, I don't understand why send invocations is needed while we are going to send resync message to server? Should the condition be like instead:

```
if ((registry.getUILifecycle().isRunning()
                && registry.getServerRpcQueue().isFlushPending())
                && registry.getMessageSender()
                        .getResynchronizationState() != ResynchronizationState.SEND_TO_SERVER) {
```
?

2022-05-13 08:42 UTC, mshabarov commented
How did you test this patch? Could we use the approach suggested here https://github.com/vaadin/flow/issues/13726#issue-1231669450 to make an IT test?

2022-05-13 09:04 UTC, TatuLund commented
@mshabarov My understanding is that approach for test described in the ticket is not deterministic enough for automated IT test.

2022-05-13 09:06 UTC, TatuLund commented on flow-client/src/main/java/com/vaadin/client/communication/RequestResponseTracker.java
> +                        .getResynchronizationState() == ResynchronizationState.SEND_TO_SERVER) {
The PR changes the sending the resynch request via normal message queue. Thus the check is needed here, so that message is really send when resynch state requires it.

2022-05-16 07:38 UTC, pepijnve commented
> @mshabarov My understanding is that approach for test described in the ticket is not deterministic enough for automated IT test.

The original issue, resynchronise fails because another request is in flight and the UI then gets stuck, is tricky to reproduce in a controlled fashion due to the number of components involved indeed.

The necessary conditions I observed are:
1. Out-of-order reply delivery is required so that the forceMessageHandling timer gets scheduled.
2. The missing reply needs to be missing long enough for the forceMessageHandling to actually trigger.
3. Prior to firing forceMessageHandling an additional RPC request needs to have been queued. In our application this was being done by the client side polling timer.

At that point when forceMessageHandling kicks in, endRequest will send the queued RPC request, and the subsequent attempt to send a resynchronise request fails due to another RPC request already being in flight.

Orchestrating all this in a 100% reliable/deterministic integration test will indeed not be trivial. Perhaps a unit test of the client side code where the timers are taken out of the picture and the relevant methods are invoked in the required order to trigger the error condition is a possibility?

2022-05-17 11:11 UTC, mshabarov commented
The issue from this [ticket](https://github.com/vaadin/flow/issues/10670#issue-858755151) is still reproducible with this patch, but we didn't expect it to be resolved 100% thought. Since the patch was proven with the legacy framework, I'll propose to apply it.

2022-05-17 13:39 UTC, mshabarov requested changes
Thanks @pepijnve , I'll have a look how we can combine these two solutions.

2022-05-18 13:45 UTC, mshabarov commented
@pepijnve thanks a lot for rebasing your changes. I've applied your patch to the current branch, it look good.

2022-05-19 06:29 UTC, merged