fix: Check url mapping using various potential property names
vaadin/flow pull request #13791
Opened 2022-05-17 11:53 UTC by Artur-

The properties in application.properties use a relaxed mapping strategy in
Spring Boot so all variants of "url-mapping","urlmapping","urlMapping" are
mapped to the same value in VaadinConfigurationProperties.
This imitates the behavior as VaadinConfigurationProperties is not available
for injection when the conditions are resolved.

2022-05-18 14:18 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/RootMappedCondition.java
> +    public static String getUrlMapping(ListableBeanFactory beanFactory,
`beanFactory` argument is never used, can it be removed?

2022-05-18 14:52 UTC, mshabarov requested changes

2022-05-18 14:52 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java
> +     * This is a helper needed only when VaadinConfigurationProperties is not
```suggestion
     * This is a helper method needed only when VaadinConfigurationProperties is not
```

2022-05-18 14:52 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/RootMappedCondition.java
> +     * This is a helper needed only when VaadinConfigurationProperties is not
"This is a helper needed only when ..." looks like copy-paste from `VaadinConfigurationProperties`. Or should it be "RootMappedCondition" instead?

2022-05-18 14:58 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java
> +        Class<?> resourcesClass = resolveClass(SPRING_BOOT_WEBPROPERTIES_CLASS);
How? We still need to resolve the class

2022-05-18 14:59 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/RootMappedCondition.java
> +                        "com.vaadin.flow.spring.VaadinConfigurationProperties")
`VaadinConfigurationProperties` is Spring Boot specific and `RootMappedCondition` is not

2022-05-18 15:10 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/RootMappedCondition.java
> +     * This is a helper needed only when VaadinConfigurationProperties is not
Fixed

2022-05-18 15:10 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java
> +     * This is a helper needed only when VaadinConfigurationProperties is not
Fixed

2022-05-19 05:56 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java
> +        Class<?> resourcesClass = resolveClass(SPRING_BOOT_WEBPROPERTIES_CLASS);
Ah, sorry, I overlooked `resourcesClass` is used further.

2022-05-19 06:00 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java
> +        Class<?> resourcesClass = resolveClass(SPRING_BOOT_WEBPROPERTIES_CLASS);
Maybe then make `resolveClass` public and reuse it?

2022-05-19 06:02 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/RootMappedCondition.java
> +                        "com.vaadin.flow.spring.VaadinConfigurationProperties")
Alright, so `VaadinConfigurationProperties` might be not present for "non-Boot" Spring apps. Thanks.

2022-05-19 06:10 UTC, mshabarov approved these changes

2022-05-19 06:10 UTC, merged