feat: notify component about identifier provider changes
vaadin/flow pull request #13902
Opened 2022-06-03 10:02 UTC by sissbruecker

## Description

Components like `Grid` or `MultiSelectComboBox` are supposed to reuse the identifier provider of the Flow data classes to identify items, for example to manage a selection state. However retrieving the identifier provider from a component is problematic at the moment as developers can set an identifier provider on any data view, and there is no way to react to that apart from extending individual implementations of data view classes to implement a custom notification mechanism that the `setIdentifierProvider` method was called.

This change introduces a `IdentifierProviderChangeEvent` that is fired when the developer sets an identifier provider on a data view. Components like `Grid` or `MultiSelectComboBox` can listen for this event, and retrieve the new identifier provider from it.

## Type of change

- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-06-03 13:02 UTC, mshabarov requested changes

2022-06-03 13:02 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
> +        ComponentUtil.fireEvent(component, new IdentifierProviderChangeEvent<>(
It makes sense to add `addIdentityProviderChangeListener` new method to this class and call `ComponentUtil.addListener` in it, so you can subscribe your component to listen these events through the DataView API.

2022-06-03 15:11 UTC, sissbruecker commented on flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
> +        ComponentUtil.fireEvent(component, new IdentifierProviderChangeEvent<>(
Done

2022-06-06 11:29 UTC, mshabarov approved these changes

2022-06-06 11:30 UTC, merged