feat: enable components to notify binder when validation state changes
vaadin/flow pull request #13940
Opened 2022-06-09 14:25 UTC by taefi

## Description
Adds the needed API to notify Binder about validation status changes that happen in field components.

Fixes #8242 
Related to https://github.com/vaadin/flow-components/issues/1158

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-06-15 11:02 UTC, mshabarov requested changes

2022-06-15 11:02 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/binder/ValidationStatusChangeListener.java
> + * The listener interface for receiving {@link ValidationStatusChangeEvent}
Do you expect if any other classes, rather than a `Binder`, would use this API to react to validation status change listener? For example, if someone would want to modify the view/page according to a validation status of the field, e.g. put a banner, disable buttons etc. ? If we expect such a use cases, then maybe worth to describe them here.

2022-06-15 11:48 UTC, taefi commented on .github/workflows/validation.yml
> +    timeout-minutes: 20
This is moved to: https://github.com/vaadin/flow/pull/13973

2022-06-15 18:35 UTC, taefi commented on flow-data/src/main/java/com/vaadin/flow/data/binder/ValidationStatusChangeListener.java
> + * The listener interface for receiving {@link ValidationStatusChangeEvent}
More descriptions were added to announce the primary purpose and other possibilities through the newly added API.

2022-06-16 06:14 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/binder/HasValidator.java
> +     * status to the observers. This method is
```suggestion
     * status to the observers.
```

2022-06-16 06:15 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/binder/HasValidator.java
> +     * <strong>Note:</strong> This method should be overridden by the
```suggestion
     * <strong>Note:</strong> This method can be overridden by the
```

2022-06-16 06:32 UTC, mshabarov approved these changes

2022-06-16 10:33 UTC, mshabarov approved these changes

2022-06-16 10:55 UTC, merged

2022-07-05 06:28 UTC, knoobie commented
@mshabarov I would like to work on a solution do deactivate this feature; I was wondering if you guys would prefer it on Binder-level or Binding-level. 

This could later be enhanced from `private boolean enableFieldValidation = false / true` as default to `private boolean enableFieldValidation = FeatureFlags.get(BINDER_FIELD_VALIDATION);` if you guys wanna put it behind a feature flag and swap the default value later on.