feat: Find a parent component with a given type
vaadin/flow pull request #14002
Opened 2022-06-16 17:53 UTC by mstahv

## Description

Add a helper method to seek the parent component of given type from the component tree. 

Fixes #13984

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-06-20 17:47 UTC, mcollovati commented
Personally I don't like that much the idea of traversing the tree and directly interact with an ancestor component, but I can get the points expressed in the related issue.
In addition we do not prevent this in any way and I'm pretty sure many developer may have already implemented such a helper on their own projects.

Some cosiderations on the proposed implementation:

- I would maybe move the implementation to `ComponentUtil` class since we already have some traversal helpers in that class.
- If instead we want to have it in `Component`, I think the API should not be public. I see it more as an internal helper for the component, rather than a way to traverse tree from outside.
- Do not restrict the component type to `Component` make sense to me; it is implicit that we will find a `Component`, but it may be useful to search it for example by a mixin or a custom interface.
- I would maybe call the method `findAncestor` rather than `findParent`

2022-06-21 04:58 UTC, mstahv commented
ComponentUtil feels like a set of internal helpers to me and it is not documented at all (other than JavaDocs), so I think far less developers would find it from there.

Renamed. Much better!

Also make protected. This is bit controversial. I guess most often one uses that from component, so protected *should* be fine, but somehow I have a feeling that someday I find my self opening that method directly as public in some Vaadin view 🤷‍♂️

2022-06-21 10:28 UTC, mcollovati reviewed
I would still move the implementation to `ComponentUtil` and then have the method in `Component` that delegates to it.
But it is up to you.
Other than that, LGTM

2022-06-22 10:55 UTC, mshabarov requested changes
> I would still move the implementation to ComponentUtil and then have the method in Component that delegates to it.

This sounds better for me as well.
By the way, I don't get the idea why you made it `protected`? The use case is to get the layout/menu or other high level component to modify it somehow. This method is invoked for some child component, so should the application actually extend the component to use this API, since is a protected, not public.
I would make it public, but transfer the implementation to the utils.

2022-06-22 12:32 UTC, mshabarov commented
Well, I would say it can be reused when moved to utils. But it can also be reused if placed to component directly.

2022-06-22 12:32 UTC, mshabarov submitted a review, later dismissed

2022-06-22 12:34 UTC, mstahv commented
👌 I'll write some basic unit test for this and convert to actual PR.

2022-06-22 14:11 UTC, mstahv commented
@mshabarov I'm ready with this!

2022-06-23 05:39 UTC, mshabarov approved these changes

2022-06-23 05:41 UTC, merged