fix: separate core and commercial components version files
vaadin/flow pull request #14014
Opened 2022-06-21 11:54 UTC by taefi

## Description

Previously, the vaadin_versions.json contained
both core and commercial components listed
which led to including them all in package.json
even if the user only used vaadin-core. Now
platform generates vaadin-core-version.json in
vaadin-core and vaadin-version.json to include
commercial components in vaadin artifact.
This commit will adopt having separate files
while generating package.json and pinning the
platform dependencies.

Fixes: #13749

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

2022-06-21 12:01 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +                    Constants.VAADIN_VERSIONS_JSON);
Is there a way to determine if a commercial component is used? Otherwise this would be printed always and kinda looks like a bad advertisement every-time the app is build.

2022-06-21 12:10 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +                    Constants.VAADIN_VERSIONS_JSON);
Thanks, @knoobie. I must admit This PR is not a draft but probably episode 1 of 2, since tests would be added in a separate PR. And of course, good hints like this are welcomed, and if for some reason they might not apply to this PR, they would be appreciated and applied to the next one.

2022-06-21 14:46 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +                    Constants.VAADIN_VERSIONS_JSON);
For now, I changed it to `trace` instead of `info` to determine if it is actually needed there or not later.

2022-06-22 05:14 UTC, caalador commented
This sounds all wrong as the vaadin-versions should just be used to generate the versions.json used to lock versions in pnpm and nothing from it should be added to the package.json
I guess this is an issue with npm which for some reason adds everything also as dependency when it should only use it for the overrides package if the package exists in dependencies.

So I would see that the issue is that with an empty package.json (and no NpmPackage annotations) running the generation should leave you with only the default packages from NodeUpdater.

2022-06-23 03:54 UTC, caalador commented
Right. Npm became the default in [10.0.0.alpha1](https://github.com/vaadin/flow/releases/tag/10.0.0.alpha1) e.g. 23 so the issue should be there since v20 (?) as it was picked to 7.0, but was not noticed as pnpm was used instead.

Then this way is fine as I thought it was a side effect from the `overrides` change that was introduced to v23

2022-06-23 04:14 UTC, caalador requested changes

2022-06-23 04:14 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +        }
As the same lines are duplicated I would perhaps add a `resourceToJson` method that is called instead. e.g. `private JsonObject resourceToJson(URL resource) { ... }`

2022-06-23 04:14 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +        URL commVersionsResource = finder
```suggestion
        URL vaadinVersionsResource = finder
```
commVersionsResource sounds like some communication package or other. Would call it vaadinVersionsResource or just versionsResource (to be the same as core) to reflect better what it is.

2022-06-23 04:14 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +                    Constants.VAADIN_VERSIONS_JSON);
I feel this is probably extra log, also it should note that non core components are not pinned. 
Also if coreVersionsResource logged that no pinning is done then probably this shouldn't log at all.

2022-06-23 08:40 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +        URL commVersionsResource = finder
Done.

2022-06-23 08:40 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +        }
Done.

2022-06-23 08:46 UTC, caalador approved these changes

2022-06-23 10:02 UTC, caalador commented
You need to do a `mvn formatter:format`

2022-06-23 10:37 UTC, mshabarov approved these changes

2022-06-23 10:52 UTC, mshabarov approved these changes

2022-06-23 11:20 UTC, merged