Improving UX of Query parameters
vaadin/flow pull request #14034
Opened 2022-06-22 13:23 UTC by mstahv

* made it easier to use both query and url parameters
 * shorthand to create URL parameters from single key-value pair

Fixes #14013

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-06-23 13:51 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +        return getQueryString();
nit: I'm personally not a big fan of toString methods without object identifier like class names, e.g. `QueryParameters(foo=bar)` instead of `foo=bar`.

The other part of the implementation looks good to me! (Not sure if you need to add unit-test for the new methods in UI tho)

2022-06-23 13:56 UTC, mstahv commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +        return getQueryString();
✅

There is an integration test so I think that is even better covered.

2022-06-23 13:57 UTC, mstahv commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +        return getQueryString();
Oh, but it covers just the other new navigate method...

2022-06-23 14:01 UTC, mstahv commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +        return getQueryString();
Now both are covered.

2022-06-27 12:45 UTC, mcollovati requested changes

2022-06-27 12:45 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/UI.java
> +            QueryParameters queryParameters) {
Are the parameter mentions in javadocs valid for this method?

2022-06-27 12:49 UTC, mstahv commented on flow-server/src/main/java/com/vaadin/flow/component/UI.java
> +            QueryParameters queryParameters) {
As far as I know. Do you see something wrong here 🤔

I think they could be better, but should be improved all (overloaded methods) at once. IIRC, I copied the formulations from existing javadocs.

2022-06-27 14:14 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/UI.java
> +            QueryParameters queryParameters) {
I'm asking because I do not see any parameter in this specific method, nor the need for the view to be a `HasUrlParameter`.
I supposed it was a copy/paste from the other method, but not clean up

2022-06-29 07:52 UTC, mcollovati requested changes

2022-06-29 07:52 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/UI.java
> +     * as defined in the route target HasUrlParameter.
```suggestion
     * Updates this UI to show the view corresponding to the given navigation
     * target and query parameters.
```

2022-06-29 07:52 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/UI.java
> +     * <p>
```suggestion
```

2022-06-29 07:52 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/UI.java
> +     *             or @WildcardParameter.
```suggestion
```

2022-06-29 10:15 UTC, mstahv commented on flow-server/src/main/java/com/vaadin/flow/component/UI.java
> +            QueryParameters queryParameters) {
Oh, not type parameter but route parameter :-)

2022-06-29 12:21 UTC, mcollovati approved these changes

2022-06-29 18:46 UTC, merged

2022-06-29 18:58 UTC, mcollovati commented
Perhaps a temporary network error