Let DataCommunicator#flush keep track of which StateTree is supposed to execute its flushRequest
vaadin/flow pull request #14068
Opened 2022-06-27 11:08 UTC by willemv

## Description

As described in #14067 the `DataCommunicator#flush` can get stuck when its `StateNode` is moved between `StateTree` instances.

This change keeps track of the `StateTree` that will execute its `flushRequest` and forces a new `flushRequest` when the current `StateTree` and the one associated with the existing `flushRequest` don't match.

Fixes #14067

## Type of change

- [x] Bugfix

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [/] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

2022-06-27 11:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=14068) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=14068) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=14068) it.</sub>

2022-07-08 21:02 UTC, czp13 commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +import com.vaadin.flow.internal.*;
I like better single imports for visibility, but in that case where no name clashing can happen, probably it is not a big thing, so it is just preference.

2022-07-08 21:32 UTC, czp13 reviewed
Thanks for contribution.

I think I understand what we would like to achieve:
- storing flushUpdateDataRequestRegistrations and flushRequestRegistrations anytime we flush, and if they are not null and cannot execute for the next time, then we try the flush again on the stateNode.

But I am not sure about the potential (side) effects of this change, and it is doing what we would like to so, **would be very good to cover it with some tests, if possible...**

2022-07-09 06:03 UTC, mcollovati commented
Hi, thanks for the contribution!

I tried to setup some unit tests that should mimic the problem with `@PreserveOnRefresh`. You can add them to `com.vaadin.flow.data.provider.DataCommunicatorTest`

Unfortunately I'm still not able to setup a proper integration test

```
    // Simulates a flush request enqueued during a page reload with
    // @PreserveOnRefresh
    // see https://github.com/vaadin/flow/issues/14067
    @Test
    public void reattach_differentUI_requestFlushExecuted() {
        dataCommunicator.setDataProvider(createDataProvider(), null);
        dataCommunicator.setRequestedRange(0, 50);

        MockUI newUI = new MockUI();
        // simulates preserve on refresh
        // DataCommunicator has a flushRequest pending
        // that should be rescheduled on the new state tree
        newUI.getInternals().moveElementsFrom(ui);
        ui = newUI;
        fakeClientCommunication();

        Assert.assertEquals("Expected initial full reset.",
                Range.withLength(0, 50), lastSet);
    }

    // Simulates a flush request enqueued during a page reload with
    // @PreserveOnRefresh
    // see https://github.com/vaadin/flow/issues/14067
    @Test
    public void reattach_differentUI_requestFlushUpdatedDataExecuted() {
        List<Item> items = new ArrayList<>();
        for (int i = 0; i < 2; i++) {
            items.add(new Item(i));
        }
        // Abusing the fact that ListDataProvider doesn't copy the backing store
        ListDataProvider<Item> dataProvider = new ListDataProvider<>(items);
        dataCommunicator.setDataProvider(dataProvider, null);

        dataCommunicator.setRequestedRange(0, 50);
        fakeClientCommunication();

        Item originalItem = items.get(0);
        String key = dataCommunicator.getKeyMapper().key(originalItem);

        Assert.assertSame(originalItem,
                dataCommunicator.getKeyMapper().get(key));

        Item updatedItem = new Item(originalItem.id, "Updated");
        items.set(0, updatedItem);
        dataCommunicator.refresh(updatedItem);

        MockUI newUI = new MockUI();
        // simulates preserve on refresh
        // DataCommunicator has a flushRequest pending
        // that should be rescheduled on the new state tree
        newUI.getInternals().moveElementsFrom(ui);
        ui = newUI;
        fakeClientCommunication();

        Assert.assertSame(updatedItem,
                dataCommunicator.getKeyMapper().get(key));
    }

```

2022-07-09 06:18 UTC, mcollovati reviewed
I would avoid changing the `ExecutionRegistration` interface, because it is  a public API (even if we provide implementation only in `StateNode`).

I would like to restrict changes only to the `DataCommunicator` class if possible.
A way could be to introduce an internal class that stores the `StateNode` owner at the moment of the `beforeClientResponse` registration and then provides the `canExecute` method that check the stored owner with the one from current NodeState

Something like this

```java
    private FlushRequest flushRequest;
    private FlushRequest flushUpdatedDataRequest;

    private static class FlushRequest implements Serializable {

        private NodeOwner owner;

        static FlushRequest register(StateNode stateNode,
                SerializableConsumer<ExecutionContext> action) {
            FlushRequest request = new FlushRequest();
            request.owner = stateNode.getOwner();
            stateNode.runWhenAttached(ui -> {
                request.owner = stateNode.getOwner();
                ui.getInternals().getStateTree().beforeClientResponse(stateNode,
                        action);
            });
            return request;
        }

        boolean canExecute(StateNode stateNode) {
            return owner instanceof NullOwner || owner == stateNode.getOwner();
        }
    }


    private void requestFlush(boolean forced) {
        if ((flushRequest == null || !flushRequest.canExecute(stateNode)
                || forced) && fetchEnabled) {
            // flushRequest = context -> {
            flushRequest = FlushRequest.register(stateNode, context -> {
                if (!context.isClientSideInitialized()) {
                    reset();
                    arrayUpdater.initialize();
                }
                flush();
                flushRequest = null;
            });
        }

    private void requestFlushUpdatedData() {
        if (flushUpdatedDataRequest == null
                || !flushUpdatedDataRequest.canExecute(stateNode)) {
            // flushUpdatedDataRequest = context -> {
            flushUpdatedDataRequest = FlushRequest.register(stateNode, context -> {
                        flushUpdatedData();
                        flushUpdatedDataRequest = null;
                    });
        }
    }

```

Let me know what do you think about this approach

2022-07-13 07:11 UTC, mcollovati commented
Hi @willemv do you have some time to check the proposed changes?
If you are busy we can create a new PR and mention you as co-author

2022-07-19 15:53 UTC, willemv commented
@mcollovati regarding the tests : one of the testcases does not fail before the fix.

Specifically, `reattach_differentUI_requestFlushUpdatedDataExecuted` succeeds even without the changes in `DataCommunicator`

The other test (`reattach_differentUI_requestFlushExecuted`) _does_ fail as expected before the fix, and passes after the fix, so that seems to be in order.

2022-07-20 05:46 UTC, mcollovati commented
@willemv seems like `flushUpdatedData()` is not called on attach and, furthermore, the callback registered by `requestFlush()` resets updated data.
So changes to `flushUpdatedData()` and the `reattach_differentUI_requestFlushUpdatedDataExecuted` test can be removed, or we can leave it there to prevent future regressions.

2022-07-20 07:02 UTC, willemv commented
> So I propose to remove the `reattach_differentUI_requestFlushUpdatedDataExecuted` test. We can leave the changes on the `flushUpdatedData()` method to make it consistent with `requestFlush()`

Agreed. I will adjust the PR

2022-07-20 08:14 UTC, mcollovati requested changes

2022-07-20 08:14 UTC, mcollovati commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +import com.vaadin.flow.internal.*;
@willemv May I ask you to use single class imports, as this is a Vaadin convention?

https://vaadin.com/docs/latest/contributing/editor-settings-intellij-idea/#imports

2022-07-20 08:17 UTC, mcollovati commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +import com.vaadin.flow.internal.*;
```suggestion
import com.vaadin.flow.internal.ExecutionContext;
import com.vaadin.flow.internal.JsonUtils;
import com.vaadin.flow.internal.NodeOwner;
import com.vaadin.flow.internal.NullOwner;
import com.vaadin.flow.internal.Range;
import com.vaadin.flow.internal.StateNode;
import com.vaadin.flow.internal.StateTree;
```

2022-07-20 08:58 UTC, willemv commented
Should I rebase this branch to the latest `master` already, or are you still reviewing and would that interrupt your workflow?

Similarly, do you want me to squash these commits? The intermediary commits are not that interesting, I just kept them like this to facilitate your incremental reviews.

2022-07-20 09:02 UTC, mcollovati commented
> Should I rebase this branch to the latest `master` already, or are you still reviewing and would that interrupt your workflow?

There are no merge conflicts right now, so rebase is not needed

> Similarly, do you want me to squash these commits? The intermediary commits are not that interesting, I just kept them like this to facilitate your incremental reviews.

We will squash on merge, so no need for you to do it

2022-07-20 09:29 UTC, mcollovati approved these changes

2022-07-20 13:39 UTC, taefi approved these changes

2022-07-20 13:51 UTC, merged