fix: Always use frontendGeneratedFolder for generated files
vaadin/flow pull request #14060
Opened 2022-06-24 14:15 UTC by mcollovati

## Description

Currently some node tasks hard-code the generated folder as child
of the frontend directory, whereas other tasks uses the
frontendGeneratedFolder configuration.
This change makes all tasks use the value of frontendGeneratedFolder.

Part of #12880

## Type of change

- [X] Bugfix
- [ ] Feature

## Checklist

- [X] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [X] I have added a description following the guideline.
- [X] The issue is created in the corresponding repository and I have referenced it.
- [X] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-06-28 10:42 UTC, taefi commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
> +    public var generatedTsFolder: File? = null
Why defer the initialization? It is only dependent on the `frontendDirectory` which has already been initialized and has not changed. 
```suggestion
    public var generatedTsFolder: File = File(frontendDirectory, FrontendUtils.GENERATED)
```

2022-06-28 12:17 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
> +    public void should_importFrontendIndexTS_customFrontendFolder()
```suggestion
    public void should_importFrontendIndexTS_fromCustomFrontendFolder()
```

2022-06-28 12:58 UTC, taefi requested changes

2022-06-28 12:58 UTC, taefi commented on flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/pom-generatedTsDir.xml
> +    </build></project>
```suggestion
    </build>
</project>

```

2022-06-28 18:34 UTC, taefi approved these changes

2022-07-09 06:23 UTC, mcollovati commented
Closing as superseded by #14144

2022-07-09 06:23 UTC, closed without merging