fix: always generate themes in frontend 'generated' directory subfolder
vaadin/flow pull request #14144
Opened 2022-07-06 12:56 UTC by mcollovati

## Description

Forces generated themes files to be stored in 'generated' folder under
frontend directory, instead of using the 'generatedTsFolder' setting.
Also fixes relative paths assuming frontend directory to be './frontend',
and maven and gradle plugins to clean the 'frontendDirectory/generated' folder.

Fixes #12880

## Type of change

- [X] Bugfix
- [ ] Feature

## Checklist

- [X] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [X] I have added a description following the guideline.
- [X] The issue is created in the corresponding repository and I have referenced it.
- [X] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [X] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-07-06 13:01 UTC, mcollovati commented
This is an alternative solution to fix #12880, by storing all generated files (excluding hilla endpoints) in `${frontendDirectory}/generated` and fixing path references.
Moving generated stuff into build directory my be implemented as a new enhancement PR.

2022-07-07 08:29 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTs.java
> +        String generatedToBuildRelativePath = FrontendUtils.getUnixRelativePath(
Just out of curiosity, does the name for `generatedToBuildRelativePath` variable means "'generated' directory relative path to build directory", right?

2022-07-07 08:31 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
>      TaskUpdateThemeImport(File npmFolder, ThemeDefinition theme,
Should we deprecate this constructor that accepts a custom `frontendGeneratedFolder`?

2022-07-07 08:32 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
> +    /**
Same comment here for deprecating the old constructor.

2022-07-07 08:39 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTs.java
> +        String generatedToBuildRelativePath = FrontendUtils.getUnixRelativePath(
Yes, that was the intention :)

2022-07-07 08:41 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
>      TaskUpdateThemeImport(File npmFolder, ThemeDefinition theme,
I would deprecate it only If we do not have any plan to move generated files to build directory some day.
Otherwise it will be deprecated and then the deprecation will be removed; can be a bit confusing

2022-07-07 08:51 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTs.java
> +        String generatedToBuildRelativePath = FrontendUtils.getUnixRelativePath(
I wish I could suggest some name that was relatively short but could reveal the same meaning :)

2022-07-07 09:21 UTC, mcollovati commented
> Should we consider adding a test that checks some of the generated files especially `theme-[theme name].generated.js` is not generated under the default frontend directory anymore when there is a custom frontend directory defined?

It seems a good idea. I'll try to add a test for this

2022-07-07 10:28 UTC, taefi approved these changes

2022-07-07 16:49 UTC, Artur- requested changes
No major comments but if we are hardcoding the use of `generated` for theme files we should use the same hardcoded path also for all other generated files and drop the possibility to customize the name/location of the `generated` folder

2022-07-07 16:49 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +    TaskUpdateThemeImport(File npmFolder, ThemeDefinition theme,
Is there a need to add this instead of changing the below one?

2022-07-07 16:49 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
> +    TaskUpdateWebpack(File frontendDirectory, File webpackConfigFolder,
Is there a need to add this instead of changing the existing one if this should always be used?

2022-07-08 05:44 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
> +    TaskUpdateWebpack(File frontendDirectory, File webpackConfigFolder,
done

2022-07-08 05:44 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +    TaskUpdateThemeImport(File npmFolder, ThemeDefinition theme,
done

2022-07-08 05:50 UTC, mcollovati commented
After this change, the only `generated` folder that can be customized will be the target folder for Hilla endpoints.
The maven/gradle setting is `generatedTsFolder`.
We can eventually remove this setting and hard-code it to `${frontendDirectory}/generated` in another PR, after checking usages also in Hilla repository.

2022-07-08 07:12 UTC, Artur- approved these changes

2022-07-08 08:27 UTC, merged