feat: add binder-level flag to disable HasValidator validation status change listener registration
vaadin/flow pull request #14158
Opened 2022-07-11 07:49 UTC by knoobie

## Description

Allow disabling of the newly added feature on binder-level. 

Open for naming / feature related discussion (DRAFT?)

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [X] Feature

## Checklist

- [X] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [X] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [X] I have added tests to ensure my change is effective and works as intended.
- [X] New and existing tests are passing locally with my change.
- [X] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-07-11 12:43 UTC, knoobie commented
@mcollovati Based on my discussion here: https://github.com/vaadin/flow-components/pull/3406#discussion_r908427652 and my comment here: https://github.com/vaadin/flow/pull/13940#issuecomment-1174668400

Idea behind this is: first enhancement to allow this change to be toggled by a FeatureFlag. I would love to gradually test this change with multiple applications before I do a big flip on all our forms and applications in a minor release (23.2) and going crazy with problems regarding "not meaningful error messages" and "user has no idea why the field is red".

2022-07-14 12:30 UTC, mcollovati commented
LGTM, but I would like for one additional review

I wonder if it would be good to be able to enable/disable the feature also for a single Binding

2022-07-14 12:37 UTC, knoobie commented
> LGTM, but I would like for one additional review

You okay with the name? It was really hard to come up with something.. and even that name feels clumsy.. 

> I wonder if it would be good to be able to enable/disable the feature also for a single Binding 

I had the feeling as well, but wanted to get something out first ;) I had multiple questions as well, but neglected them all in my first throw to make it simple. Should this not stop the listener registration and instead stop the execution of the validate() call.. allowing this to be changed on the fly, instead of only once per binder and so on..

2022-07-14 13:14 UTC, mcollovati commented
> You okay with the name? It was really hard to come up with something.. and even that name feels clumsy..

I agree that the name feels clumsy. I tried to find an alternative but was unsuccessfully. That's why I would like for another review.

2022-07-14 13:15 UTC, mcollovati commented
> Should this not stop the listener registration and instead stop the execution of the validate() call.. allowing this to be changed on the fly, instead of only once per binder and so on

Interesting point

2022-07-20 13:22 UTC, taefi requested changes
@knoobie the whole thing sounds like a good feature! Thanks for the contribution. Just suggested some changes.

2022-07-20 13:22 UTC, taefi commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +            if (!builder.getBinder()
```suggestion
            if (!getBinder()
```

2022-07-21 08:11 UTC, mcollovati approved these changes

2022-07-21 08:13 UTC, knoobie commented
Reminder: that the PR description probably has to be updated to something more meaningful, before a release is pushed with this encrypted message

2022-07-21 11:30 UTC, taefi approved these changes

2022-07-21 12:08 UTC, merged