fix: Let DataCommunicator#flush keep track of its StateTree
vaadin/flow pull request #14195
Opened 2022-07-21 11:21 UTC by taefi

fix: Let DataCommunicator#flush keep track of which StateTree is supposed to execute its flushRequest (#14068)

* DataCommunicator#flush can be stuck when moving between UI instances, for instance when the @PreserveOnRefresh annotation is present.

Co-authored-by: Marco Collovati mcollovati@gmail.com

(cherry picked from commit c55bdcc6dd9dac75be42291b5752d1d86d5a9997)

2022-07-21 11:37 UTC, mcollovati requested changes

2022-07-21 11:37 UTC, mcollovati commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +        return String.format("The data provider hasn't ever called %s() " + "method on the provided query. "
```suggestion
        return String.format("The data provider hasn't ever called %s() method on the provided query. "
```

2022-07-21 12:21 UTC, mcollovati approved these changes

2022-07-21 12:34 UTC, merged

2022-09-21 11:18 UTC, ZheSun88 commented
has been picked bea6386525bd4628d0cac78b4bf3ef124e6f6dc6