feat: add configuration to `TaskGenerateHilla`
vaadin/flow pull request #14221
Opened 2022-07-26 14:08 UTC by cromoteca

Adds a method to `TaskGenerateHilla` that allows implementations to get some configuration, notably the path of the current Maven project.

Closes #14218

2022-07-26 14:21 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +                        builder.getBuildDirectory());
Shouldn't 'hillaTask` be added to commands? I think task are not meant to be execute eagerly

2022-07-26 14:21 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateHilla.java
> +    void configure(File projectDirectory, String buildDirectoryName);
Could it be a default method with empty body if the logic is in `execute` method?

2022-07-26 14:26 UTC, cromoteca commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +                        builder.getBuildDirectory());
Sure, it was not meant to replace the other line, but added to it. I don't know how I managed to create the commit this way as I absolutely need the command to be added.

2022-07-26 14:26 UTC, cromoteca commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateHilla.java
> +    void configure(File projectDirectory, String buildDirectoryName);
Yes, that can be done of course.

2022-07-27 05:50 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateHilla.java
> +    default void configure(File projectDirectory, String buildDirectoryName) {
Being a public API we should perhaps add Javadocs. For example we can make it explicit that this method will always be invoked once and before `execute`

2022-07-29 07:20 UTC, mcollovati requested changes

2022-07-29 07:20 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateHilla.java
> +     *            the name of the build directory (i.e.&nbsp;"build" or
I think HTML space entity is not needed
```suggestion
     *            the name of the build directory (i.e. "build" or
```

2022-07-29 07:24 UTC, cromoteca commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateHilla.java
> +     *            the name of the build directory (i.e.&nbsp;"build" or
Actually, I don't remember if @param description are shown in short format somewhere, so I put that there just in case.

2022-07-29 07:39 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateHilla.java
> +     *            the name of the build directory (i.e.&nbsp;"build" or
Sorry, I don't understand why using a single `&nbsp;`. Can you please elaborate your previous answer?

2022-07-29 07:45 UTC, cromoteca commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateHilla.java
> +     *            the name of the build directory (i.e.&nbsp;"build" or
I don't think it's needed as only method descriptions are truncated to the first sentence in Javadoc Summaries. I think that parameter description are never truncated.

2022-07-29 07:52 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateHilla.java
> +     *            the name of the build directory (i.e.&nbsp;"build" or
Thanks for explanation

2022-07-29 07:54 UTC, mcollovati submitted a review, later dismissed

2022-07-29 09:08 UTC, mcollovati approved these changes

2022-07-29 09:09 UTC, merged