feat: Support Object type keys in Component#getTranslation
vaadin/flow pull request #14287
Opened 2022-08-08 09:54 UTC by TatuLund

Fixes #14286

2022-08-09 12:01 UTC, mshabarov requested changes

2022-08-09 12:01 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/component/Component.java
> +    public String getTranslation(Object key, Locale locale, Object... params) {
I propose to not include this method into master - looks weird when you add a new method and tell that it is deprecated :)
If it is still needed for V14, let's deprecate it there only.

2022-08-09 13:11 UTC, TatuLund commented on flow-server/src/main/java/com/vaadin/flow/component/Component.java
> +    public String getTranslation(Object key, Locale locale, Object... params) {
It will not be deprecated in V14.

2022-08-10 10:27 UTC, TatuLund commented on flow-server/src/main/java/com/vaadin/flow/component/Component.java
> +    public String getTranslation(Object key, Locale locale, Object... params) {
See https://github.com/vaadin/flow/pull/14312

2022-08-11 06:23 UTC, mshabarov requested changes

2022-08-11 06:23 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/component/Component.java
> +    public String getTranslation(Object key, Locale locale, Object... params) {
This is not clear for me still...You add a new method and immediately recommend to not use it.
Can we remove it and use another one in the overloaded method (needs to swap first two parameters):

```java
    public String getTranslation(Object key, Object... params) {
        return getTranslation(getLocale(), key, params);
    }
```

2022-08-11 10:37 UTC, mshabarov approved these changes

2022-08-11 10:37 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/component/Component.java
> +    public String getTranslation(Object key, Locale locale, Object... params) {
Discussed offline that we keep the deprecated method for the sake of consistency between V14 and V23, because the same API has been added into V14.

2022-08-11 10:38 UTC, merged