feat: Introduced component-based security configuration for Spring
vaadin/flow pull request #14303
Opened 2022-08-09 13:52 UTC by MarcinVaadin

## Description

Introduced component-based security configuration for Spring

Fixes #13910

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [x] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-08-12 06:26 UTC, caalador submitted a review, later dismissed
This also fixes first WARN mentioned in #13868
The `pattern='/images/*.png'` is in the starter application so should be fixed there after this is merged. Also stareters should be updated to use the new way.

2022-08-12 11:11 UTC, MarcinVaadin commented
> This also fixes first WARN mentioned in #13868 The `pattern='/images/*.png'` is in the starter application so should be fixed there after this is merged. Also stareters should be updated to use the new way.

Changed approach of registering public resources (from ignoring to permitAll) to fix mentioned issues.

2022-08-12 11:39 UTC, caalador approved these changes

2022-08-12 12:31 UTC, MarcinVaadin commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> + * Copyright 2000-2021 Vaadin Ltd.
Same currently:
```
@Bean
    @Override
    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
        http.authorizeRequests().antMatchers("/admin-only/**")
                .hasAnyRole(ROLE_ADMIN);
        http.authorizeRequests().antMatchers("/public/**").permitAll();
        setLoginView(http, LoginView.class, getLogoutSuccessUrl());
        return super.filterChain(http);
    }
```

2022-08-12 12:33 UTC, mcollovati commented
Same thought about the old `configure(WebSecurity web)`
Should we maybe expose a `WebSecurityCustomizer` bean with logic previously from `configure(WebSecurity web)`?
If we adopt the same pattern, the migration would be likely just change the super class

2022-08-12 12:36 UTC, MarcinVaadin commented
> Same thought about the old `configure(WebSecurity web)` Should we maybe expose a `WebSecurityCustomizer` bean with logic previously from `configure(WebSecurity web)`? If we adopt the same pattern, the migration would be likely just change the super class

The functionality of `configure(WebSecurity web)` has been moved into `filterChain(HttpSecurity http)` and TBH I don't see a point leaving empty bean. 

Yes, it should be described in migration docs.

2022-08-12 12:41 UTC, mcollovati commented on flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
> +    @Bean
I would also set a specific name for the bean, to avoid it to be replaced unintentionally by some other user security configuration, as I think there can be many SecurityFilterChain beans

2022-08-12 12:47 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> + * Copyright 2000-2021 Vaadin Ltd.
What I mean is that to migrate, user need to entirely change the old definition and remeber to add the Bean annotaion.
If we preserve protected `configure` method, they do not need to change anything other than the superclass, and the bean is exposed by the super class itself

2022-08-12 12:57 UTC, mshabarov commented
After this feature applied, we also need to update the following article to not mention the deprecated adapter, but describe a new approach https://vaadin.com/docs/latest/security/enabling-security

2022-08-12 13:10 UTC, mcollovati commented on flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
> +    @Bean
look good to me

2022-08-15 08:38 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> + * Copyright 2000-2021 Vaadin Ltd.
So in practice it would mean changing
```
public SecurityFilterChain filterChain(HttpSecurity http)
```
to
```
protected SecurityFilterChain configure(HttpSecurity http)
```
in `VaadinWebSecurity` ?

Makes sense to me. 
It would help to save efforts during migration.

2022-08-15 10:19 UTC, mshabarov requested changes

2022-08-16 05:17 UTC, MarcinVaadin commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +    @Bean
My intention was to create no-op bean that user can use without any additional actions (same approach as 
 previously in `VaadinWebSecurityConfigurerAdapter` - default implementations of `@Configure` method).

Addind `@Bean` on abstract parent does not require Javadocs update: 
```
To use this, create your own web security class by extending this class and
 * annotate it with <code>@EnableWebSecurity</code> and
 * <code>@Configuration</code>.
 * <p>
 * For example <code>
&#64;EnableWebSecurity
&#64;Configuration
```

The only remark noted by @mcollovati is that to ease migration maybe parent methods should still remain their names `configure` and then in implementation:
```
@Bean
public SecurityFilterChain filterChain(HttpSecurity http) {
   configure(http);
   return http.build();
}
```
instead of chaining `return super.filterChain(http);`. It makes sense to call `.build()` on child class.

2022-08-16 05:41 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +    @Bean
My idea was to preserve configure methods and having the bean definition only on parent class, without overriding it in subclass. This way migration should be only changing the extend clause in user project

2022-08-16 06:04 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +    @Bean
@MarcinVaadin thanks for explanations! So do we need `@Bean` annotation in both places: abstract class and implementation class?

Just repeating that Marco said, because it seems reasonable to me as well: from the API point of view and a matter of easy migration: could we make the new abstract class `VaadinWebSecurity` be so that the methods and annotations of this class would be as much as possible similar to old implementations extending `VaadinWebSecurityConfigurerAdapter`, see current docs to understand what I mean
https://vaadin.com/docs/latest/security/enabling-security/#security-configuration-class.

So can we design `VaadinWebSecurity` API in a way that developers would need only to change their `SecurityConfig` implementations to `extends VaadinWebSecurity` and nothing more?

2022-08-16 06:21 UTC, MarcinVaadin commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +    @Bean
It is not possible just to change the parent class due to component approach (`@Bean`) and filter chains. Also it is important to mention that we have moved a `WebSecurity` configuration into `SecurityFilterChain`.

The good point is that migration is optional. Minimal migration effort would be to:
1. Extend `VaadinWebSecurity`
2. Update methods to follow filters approach
3. Update `WebSecurity` configuration if needed

2022-08-16 06:28 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +    @Bean
I can't get why it is not possible to just change parent class, if all bean definition are in parent class. Can you please elaborate the reason why it can't be done?

2022-08-16 06:29 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +    @Bean
For "change the parent class" I mean updating child class to extend VaadinWebSecurity instead of VaadinWebSecurityConfigurerAdapter

2022-08-16 06:34 UTC, MarcinVaadin commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +    @Bean
Ok, if user did not do any updates, just pure:
```
public class MySecurity extends VaadinWebSecurity { }
```
And proper chaining bean is present in parent it will work.

2022-08-16 09:02 UTC, mcollovati requested changes

2022-08-16 09:02 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +     */
We can perhaps add a note in javadocs to mention that provided configuration can be customized by overriding `configure(HttpSecurity)` method

2022-08-16 09:02 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +     * Default no {@link WebSecurity} customization is performed.
We can perhaps add a note in javadocs to mention that configuration can be customized by overriding `configure(WebSecurity)` method

2022-08-16 09:04 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +     */
And maybe also add javadocs to `configure(HttpSecurity)` suggesting remembering to call `super.configure(...)` when overriding

2022-08-16 09:22 UTC, MarcinVaadin commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +     */
> Remember to call configure(WebSecurity) to apply default security configuration. Calling configure(WebSecurity) will apply anyRequest matcher that disallows adding further request matchers.

Will it be ok?

2022-08-16 09:35 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +     */
Was thinking something like

```
    /**
     * Applies Vaadin default configurations to {@link HttpSecurity}.
     * 
     * Typically subclasses should call super to apply default Vaadin configuration in addition to custom rules.
     * 
     * @param http
     * @throws Exception
     */
    protected void configure(HttpSecurity http) throws Exception {
```

2022-08-16 09:37 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +     */
And for the bean exposing method, just adding something like

```
HttpSecurity configuration can be customized by overriding configure(HttpSecurity)
```

2022-08-16 10:20 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +     * @param http
Missing javadoc for http and Exception

2022-08-16 10:23 UTC, mshabarov submitted a review, later dismissed
Missing javadocs, otherwise LGTM: old configure methods are there for backwards compatibility and a new Spring classes for filter chain and web customisation are also available through dedicated methods as a beans.

2022-08-16 12:51 UTC, mcollovati approved these changes

2022-08-16 12:52 UTC, mshabarov approved these changes

2022-08-16 13:29 UTC, merged