feat: Support Object type keys in Component#getTranslation
vaadin/flow pull request #14312
Opened 2022-08-10 10:27 UTC by TatuLund

Fixes #14286 for Vaadin 14

2022-08-10 10:53 UTC, mcollovati requested changes

2022-08-10 10:53 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/Component.java
> +     * @deprecated Use {@link #getTranslation(Locale, String, Object...)}
```suggestion
     * @deprecated Use {@link #getTranslation(String, Locale, Object...)}
```

2022-08-10 13:28 UTC, TatuLund commented on flow-server/src/main/java/com/vaadin/flow/component/Component.java
> +     * @deprecated Use {@link #getTranslation(Locale, String, Object...)}
Good catch, the @depracatd should not be there at all, it was copy paste left over from V23.

2022-08-11 07:13 UTC, mshabarov approved these changes

2022-08-11 07:26 UTC, mcollovati approved these changes

2022-08-11 07:27 UTC, merged