Revert "fix!: Always load static files from context root (#13795)"
vaadin/flow pull request #14357
Opened 2022-08-16 08:31 UTC by mshabarov

Revert "fix!: Always load static files from context root (#13795)"

This reverts commit af975389

2022-08-23 08:35 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
> +                            Collections.sort(mappings);
Is there a need for this `mapping` local variable to be sorted?

2022-08-23 08:44 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
> +        return frontendMapping;
Just a minor suggestion: would it make sense to create uniformity between the field name and its getter (to rename either of them, most likely the field)? It seems we just pick the first mapping from the list of mappings, and then we call it `frontendMapping`, but having a field named this way somehow implies that you could specifically set the `frontendMapping` unless you read the `public void init(ServletConfig servletConfig)` method implementation.

2022-08-23 08:53 UTC, taefi approved these changes

2022-08-23 10:23 UTC, taefi requested changes

2022-08-23 10:23 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
> +                            Collections.sort(mappings);
Is there a need for this `mappings` local variable to be sorted?

2022-08-23 12:20 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
> +                            Collections.sort(mappings);
Well ... the mapping should obviously be sorted before `mappings.get(0)`... It is a way to ensure that `frontendMapping` is deterministic as `getMappings()` return a set.

2022-08-23 12:22 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
> +                            Collections.sort(mappings);
Changed

2022-08-23 12:25 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
> +        return frontendMapping;
Renamed to `frontendMapping`. Spring sets this through a property and being able to set "the first deployed servlet mapping" makes no sense

2022-08-23 13:59 UTC, taefi approved these changes

2022-08-24 10:59 UTC, mshabarov commented
Got these errors when running 23.2.0.beta2 starter with this patch:

```
NetworkOnly.js:93 Uncaught (in promise) no-response: The strategy could not generate a response for 'http://localhost:54524/VAADIN/'. The underlying error is TypeError: Failed to fetch.
    at NetworkOnly._handle (http://localhost:8080/sw.js:3617:19)
    at async NetworkOnly._getResponse (http://localhost:8080/sw.js:1642:24)
```

So it requests `http://localhost:54524/VAADIN/` for some reason and fails.

2022-08-24 12:16 UTC, taefi commented
Tested #14239 with the changes in this PR, and it works as expected.

2022-08-24 12:38 UTC, Artur- commented
> Got these errors when running 23.2.0.beta2 starter with this patch:
> 
> ```
> NetworkOnly.js:93 Uncaught (in promise) no-response: The strategy could not generate a response for 'http://localhost:54524/VAADIN/'. The underlying error is TypeError: Failed to fetch.
>     at NetworkOnly._handle (http://localhost:8080/sw.js:3617:19)
>     at async NetworkOnly._getResponse (http://localhost:8080/sw.js:1642:24)
> ```
> 
> So it requests `http://localhost:54524/VAADIN/` for some reason and fails.

Vite 3 uses `/VAADIN` and the Vite port as its ping URL (see #13826) so you see this error at least if you shut down the server while keeping the app open. Not sure why you would see it otherwise but also it should have nothing at all to do with this PR

2022-08-24 13:43 UTC, mshabarov commented
https://github.com/vaadin/flow/issues/14227 is not solved, but let's fix it in a separate PR.

2022-08-24 13:56 UTC, taefi approved these changes

2022-08-24 14:01 UTC, merged