no client updates when setText() does nothing
vaadin/flow pull request #14389
Opened 2022-08-19 08:58 UTC by Manfred-on-github

## Description
when invoking setText(sometext) on an Element, using the same text as before, this still triggers some dom changes being sent to browser, even though nothing changes. This causes unnecessary network traffic and browser code to run.
The same situation is handled correctly for setProperty(prop,value) etc., so it should work the same way also for setText().

Fixes #14388

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x ] I have added a description following the guideline.
- [x ] The issue is created in the corresponding repository and I have referenced it.
- [x ] I have added tests to ensure my change is effective and works as intended.
- [x ] New and existing tests are passing locally with my change.
- [x ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-08-19 08:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=14389) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=14389) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=14389) it.</sub>

2022-08-19 08:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=14389) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=14389) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=14389) it.</sub>

2022-08-22 14:23 UTC, mshabarov requested changes
@Manfred-on-github thank you for contribution!
The motivation for this fix is clear, but I'm not sure I get the implementation details right.

2022-08-22 14:23 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/dom/Element.java
> +            if (oneChild == child) {
`Element.setText` returns `this`, so `child` always points to the same object as `oneChild` does.
Thus, the condition is always `true` and it never removes all children and append children, if it's a text node.
So the following patch does the same.

```java
    private void setTextContent(String textContent) {
        Element child;
        if (getChildCount() == 1 && getChild(0).isTextNode()) {
            getChild(0).setText(textContent);
            return;
        } else {
            child = createText(textContent);
            removeAllChildren();
            appendChild(child);
        }
    }
```

Could you elaborate more why you're comparing the child element objects references?
Thanks

2022-08-22 21:32 UTC, Manfred-on-github commented on flow-server/src/main/java/com/vaadin/flow/dom/Element.java
> +            if (oneChild == child) {
you are right, this code does the same -  
however I did not want to assume that setText() will always return the same object, therefore, being extra careful, have added this if.
So your choice what to accept as final version...

2022-08-23 06:35 UTC, mshabarov requested changes

2022-08-23 06:35 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/dom/Element.java
> +            if (oneChild == child) {
The contract of `setText` methods says the returned object is `this` element and we have many tests relying on that, so in my opinion this reference check is not needed.

I would propose to make this method look like:
```java
    private void setTextContent(String textContent) {
        Element child;
        if (getChildCount() == 1 && getChild(0).isTextNode()) {
            getChild(0).setText(textContent);
        } else {
            child = createText(textContent);
            removeAllChildren();
            appendChild(child);
        }
    }
```
Unit test looks good.
Also I've tested this patch with the started project, works as expected.

2022-08-23 06:36 UTC, mshabarov commented
@Manfred-on-github please also run `mvn formatter:format`.

2022-08-26 07:36 UTC, mshabarov approved these changes

2022-08-26 13:07 UTC, merged