feat: Automatically use available converters in Binder  Merged
vaadin/flow pull request #14392
Opened 2022-08-19 10:30 UTC by melihkurtaran

## Description

Backporting #13337

When binding a field and a property which do not have the same value type
an exception is thrown. With this change, an attempt is made to
automatically pick a suitable converter from the ones provided by the framework.

## Type of change

- [ ] Bugfix
- [X] Feature

## Checklist

- [X] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [X] I have added a description following the guideline.
- [X] The issue is created in the corresponding repository and I have referenced it.
- [X] I have added tests to ensure my change is effective and works as intended.
- [X] New and existing tests are passing locally with my change.
- [X] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [X] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-08-19 10:45 UTC, mcollovati requested changes

2022-08-19 10:45 UTC, mcollovati commented on flow-data/src/main/java/com/vaadin/flow/data/converter/ConverterFactory.java
> +}
newline missing

2022-08-19 10:45 UTC, mcollovati commented on flow-data/src/test/java/com/vaadin/flow/data/converter/DefaultConverterFactoryTest.java
> +}
newline missing

2022-08-19 11:56 UTC, mcollovati commented
needs rebase on 2.8 and fixing conflicts

2022-08-22 12:18 UTC, melihkurtaran commented
Closing this PR and created #14412

2022-08-22 12:18 UTC, closed without merging