feat: allow to set a feature flag using a system property
vaadin/flow pull request #14408
Opened 2022-08-22 10:38 UTC by cromoteca

Accepts a value for a feature flag passed through a system property and overrides existing value.

Closes #14407

2022-08-22 10:58 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
> +            var prop = System.getProperty("featureFlag-" + f.getId());
Should the system property be prefixed with `vaadin-` like the name of the property file?

2022-08-22 14:13 UTC, taefi requested changes

2022-08-22 14:13 UTC, taefi commented on flow-server/src/test/java/com/vaadin/experimental/FeatureFlagsTest.java
> +        System.setProperty("featureFlag-exampleFeatureFlag", "true");
In general, if we set some system properties during a test, it is highly recommended to hold their pre-change states and restore them after the test ends. The impact of setting this specific property might not be very obvious but in the future, this might mess up some other test results.

2022-08-22 14:13 UTC, taefi commented on flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
> +            var prop = System.getProperty("featureFlag-" + f.getId());
Thanks, @cromoteca for the contribution, I also prefer to see a `vaadin-` prefix with the property name to prevent any possible clash with some unwanted properties, even though it might be very rare.

2022-08-23 10:10 UTC, taefi approved these changes

2022-08-23 10:11 UTC, merged