feat: throw exception if webpack config file exist and running with Vite
vaadin/flow pull request #14418
Opened 2022-08-23 18:46 UTC by taefi

## Description

Throw exception if webpack config file exist in the project and running with Vite.

Fixes #14417

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed a self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [x] Enhancement / new feature was discussed in internal slack.

2022-08-23 18:58 UTC, knoobie commented
I would argue that this is a huge DX-downer, resulting in every project updating from < 23.2 to fail with an exception even tho only the default (generated webpack file by Vaadin!) which is probably the default for 70-90% of all flow developer.

Ist there a way to reliable detect e.g. with a simple checksum check that's the Default content in the file and just "migrate" to vite? Instead of forcing the developer to delete the file by hand?

2022-08-23 19:30 UTC, mcollovati commented
I think we should throw only if a custom web pack.config.js is present. If it is the default one provided by Vaadin we can just ignore it or add a log message stating that webpack files can be safely deleted

2022-08-24 05:20 UTC, mcollovati commented
Perhaps we should also skip the check if webpack feature flag is set to true

2022-08-24 06:11 UTC, mshabarov commented
I agree with the comments above.
We supposed to have a __custom__ webpack config detection, not just a webpack config file detection.
Since it is being generated by Vaadin for all the projects, it presents always, so this detection would trigger always.
The detection should check that the config file contains non-empty object to merge, or it has an extra codes for handling `flowDefaults`.
Here is an example of webpack config in starter project:
https://github.com/vaadin/skeleton-starter-flow-spring/blob/v23/webpack.config.js
(however it is slightly different from the template in the flow-server).

Detection should somehow extract the meaningful part of the config: either second parameter object in `merge` or an extra codes apart from `module.exports = merge(flowDefaults, {})`

2022-08-24 06:16 UTC, taefi commented
> Perhaps we should also skip the check if webpack feature flag is set to true

I think this one has already been taken care of, as the validation task is only added if Vite is in use.

2022-08-29 10:01 UTC, mshabarov requested changes

2022-08-29 10:01 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskNotifyWebpackConfExistenceWhileUsingViteTest.java
> +    public void should_executeWithoutWarning_when_webpackConfigFileDoesNotExist() {
There should be also a test checking that no warning message is present if webpack is used.

2022-08-29 14:15 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskNotifyWebpackConfExistenceWhileUsingViteTest.java
> +    public void should_executeWithoutWarning_when_webpackConfigFileDoesNotExist() {
Verifying the log message for this specific case needs a very complicated mocking for a lot of static methods, as in this case, the NodeTask execution will not fail and the next steps would result in errors that are not in the scope of this test. Instead, another test created in `NodeTasksWebpackTest` to ensure that the `TaskNotifyWebpackConfExistenceWhileUsingVite` is not even added to the list of fallible commands when `webpack` is activated via its feature flag, so no warn or exception would happen in this case.

2022-08-29 14:16 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskNotifyWebpackConfExistenceWhileUsingVite.java
> +                "(?:/\\*(?:[^*]|(?:\\*+[^*/]))*\\*+/)|(?://.*)", "");
The existing test was modified to have different types of possible comments in the mock `webpack.config.js` content and it is verified to be working correctly as it still detects the config file as the default generated one.

2022-08-29 14:16 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskNotifyWebpackConfExistenceWhileUsingVite.java
> +            throw new IllegalStateException(String.format(ERROR_MESSAGE));
Done.

2022-08-29 14:16 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskNotifyWebpackConfExistenceWhileUsingVite.java
> + * accidental misconfiguration in webpack related config files while using vite.
Done.

2022-08-30 06:31 UTC, mshabarov commented
I've tested with starter project with webpack configuration:
- default webpack config - > warning shown
- custom webpack config -> app stopped with message
- renamed config -> starts with no warnings
- custom config + reactivated webpack -> starts with no warnings.

Works as expected.

2022-08-30 06:33 UTC, merged