test: remove spring-data-jpa and h2 db from ITs
vaadin/flow pull request #14461
Opened 2022-09-02 12:20 UTC by taefi

H2 db instance sometimes fails to stop
and it leads to the failure of spring
tests. The data services mocked
and replaced jpa repositories. This also
improves the validation build time as it
removes the necessity of restarting the
in-memory db instance between tests.

2022-09-09 06:28 UTC, Artur- requested changes

2022-09-09 06:28 UTC, Artur- commented on flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/service/AccountService.java
> +    private static final Map<String, Account> ACCOUNT_CACHE = new HashMap<>(2);
This should be a concurrent map

2022-09-09 06:28 UTC, Artur- commented on flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/service/UserInfoService.java
> +    private static final Map<String, UserInfo> USER_INFO_CACHE = new HashMap<>(
This should be a concurrent map

2022-09-09 06:28 UTC, Artur- commented on flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/UIAccessContextIT.java
> +        String expectedAdminBalance = "Hello Emma the Admin, your bank account balance is $200000.";
Why does this change when you remove the database?

2022-09-09 06:41 UTC, taefi commented on flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/UIAccessContextIT.java
> +        String expectedAdminBalance = "Hello Emma the Admin, your bank account balance is $200000.";
This doesn't have anything to do with the DB. The locale settings on the CI server somehow forced this format of the BigDecimal outputs. First I thought maybe the CI server instance locale settings might be messed up, but the flow-data module also has some unit tests with checkings for the formatted outputs and they are passing without any change. Needs more investigation in case we insist on keeping the previous format.

2022-09-09 09:08 UTC, Artur- commented on flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/UIAccessContextIT.java
> +        String expectedAdminBalance = "Hello Emma the Admin, your bank account balance is $200000.";
Doesn't seem super relevant although I don't get why the CI server would change when you drop the DB. Maybe the test app should explicitly set the locale to avoid surprises in the future

2022-09-09 12:25 UTC, taefi commented on flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/UIAccessContextIT.java
> +        String expectedAdminBalance = "Hello Emma the Admin, your bank account balance is $200000.";
Maybe it was related to how precision was being set on a BigDecimal object which is being instantiated by JPA when reading from the h2 DB, even though, there wasn't any precision and scale information defined in the bean before. Anyway, I reverted the changes to the expected output and changed the way that the balance property was being initialized. As these tests are related to the security aspects, I guess they can be considered sufficient for the sake of this refactoring.

2022-09-09 12:26 UTC, taefi commented on flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/service/AccountService.java
> +    private static final Map<String, Account> ACCOUNT_CACHE = new HashMap<>(2);
Done.

2022-09-09 12:26 UTC, taefi commented on flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/service/UserInfoService.java
> +    private static final Map<String, UserInfo> USER_INFO_CACHE = new HashMap<>(
Done.

2022-09-12 07:15 UTC, Artur- approved these changes

2022-09-12 10:35 UTC, merged