fix: Do not overwrite generate files with the same content
vaadin/flow pull request #14510
Opened 2022-09-13 08:50 UTC by Artur-

Overwriting the files will cause the frontend tooling to recompile when there is no need to do that

Fixes #14490

2022-09-19 08:35 UTC, mcollovati reviewed
May we add some tests for `writeIfChanged`?

2022-09-19 08:35 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractTaskClientGenerator.java
> +                StandardCharsets.UTF_8);
nit: we can maybe use a static import for `UTF_8`, as we do in `writeIfChanged`
```suggestion
        return FileUtils.readFileToString(generatedFile, UTF_8);
```

2022-09-19 08:41 UTC, mshabarov requested changes

2022-09-19 08:41 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractTaskClientGenerator.java
> +    static void writeIfChanged(File file, String content) throws IOException {
We need at least a unit test for this.

2022-09-19 11:52 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractTaskClientGenerator.java
> +    static void writeIfChanged(File file, String content) throws IOException {
Added

2022-09-19 11:53 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractTaskClientGenerator.java
> +                StandardCharsets.UTF_8);
Done

2022-09-20 06:23 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractTaskClientGeneratorTest.java
> +import com.nimbusds.jose.util.StandardCharset;
Should be `java.nio.charset.StandardCharsets` ?

2022-09-20 06:27 UTC, Artur- commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractTaskClientGeneratorTest.java
> +import com.nimbusds.jose.util.StandardCharset;
Fixed

2022-09-20 06:27 UTC, mshabarov submitted a review, later dismissed

2022-09-20 08:45 UTC, mshabarov approved these changes

2022-09-20 09:06 UTC, merged