fix: Added support for custom frontendDirectory in TaskCopyTemplateFiles
vaadin/flow pull request #14527
Opened 2022-09-14 12:34 UTC by MarcinVaadin

## Description

Added support for custom `frontendDirectory` in `TaskCopyTemplateFiles`. 

I didn't want to implement solution within `FrontendUtils.resolveFrontendPath` as it is referenced during Lit/Polymer templates parsing.

Fixes #14415

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-09-15 08:18 UTC, taefi requested changes
Would there be some new Tests to validate this functionality?

2022-09-15 08:18 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFiles.java
> +                    }
Reading the whole method gives me this sense that it uses the `frontendDirectory` as a fallback value for the path coming from the `@JsModule`. Shouldn't it be looking always into the `frontendDirectory` when defined? Or am I missing a point here?

2022-09-15 08:23 UTC, MarcinVaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFiles.java
> +                    }
If you check `FrontendUtils.resolveFrontendPath` you will notice that it looks for frontend resources in few different locations:
```
File localFrontendFolder = new File(projectRoot,
                FrontendUtils.FRONTEND);
        File nodeModulesFolder = new File(projectRoot, NODE_MODULES);
        File flowFrontendFolder = new File(nodeModulesFolder,
                "@vaadin/" + DEFAULT_FLOW_RESOURCES_FOLDER);
```
I thought replacing that logic with single call to `this.frontendDirectory` is too risky.

2022-09-15 08:27 UTC, MarcinVaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFiles.java
> +                    }
Yes, there are no tests for custom frontedDirectory for the moment, I will add them.

2022-09-15 08:33 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFiles.java
> +                    }
I think we should not replace the whole logic in `FrontendUtils.resolveFrontendPath` since it is handling some order as well. I think the **custom** `frontendDirectory` value should affect the hardcoded `localFrontendFolder` value which always points to `{projectRoot}/frontend`.

2022-09-15 10:26 UTC, taefi commented
It seems that the `TaskCopyTemplateFilesTest.java` file has incompatible formatting.

2022-09-15 11:41 UTC, taefi requested changes

2022-09-15 11:41 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +     * Looks up the front file at the given path. If the path starts with
In the first sentence (I know it comes from the previously existing method) what is it exactly `the front file` referring to? The frontend folder/path?

2022-09-15 11:41 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +     * @param localFrontendFolder
I would not call the third parameter `localFrontendFolder`. I'm not sure even why it has bean called that before, something like `defaultFronendFolder` could be more meaningful back then. Now, I would suggest to rename it to `frondendFolder` or `frontendDirectory`, as it can hold the "default" or a custom path to the so called `frontend` directory in this method.

2022-09-15 12:13 UTC, mshabarov requested changes
The patch looks good to me, but I propose to add an IT test using production mode to be sure that the copied file is handled correctly and bundled.

2022-09-15 12:28 UTC, MarcinVaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +     * Looks up the front file at the given path. If the path starts with
I've just copied the javadocs from existing method ;-) Ok, I will update them.

2022-09-15 12:38 UTC, mshabarov commented
@MarcinVaadin the easiest way to make an IT test is not take an existing test module which tests templates, add a custom pom file there (we already have a similar examples in the flow-tests with custom poms) and set production mode and a custom frontend folder in this custom pom file (through the flow-maven-plugin parameters).

2022-09-15 12:59 UTC, MarcinVaadin commented
> @MarcinVaadin the easiest way to make an IT test is not take an existing test module which tests templates, add a custom pom file there (we already have a similar examples in the flow-tests with custom poms) and set production mode and a custom frontend folder in this custom pom file (through the flow-maven-plugin parameters).

Well... I've used `vite-production`, it contains `@JsModule("./lit-invalid-imports.ts")` so should be fine.

2022-09-15 13:12 UTC, taefi approved these changes

2022-09-15 13:51 UTC, mshabarov requested changes

2022-09-15 13:51 UTC, mshabarov commented on flow-tests/test-frontend/vite-production-custom-frontend/frontend-custom/lit-invalid-imports.ts
> +console.log(customElement, ce2, ce3, property, p2, state, unsafeHTML, classMap);
This doesn't look as a good lit element example :) but a hack with imports without "js" extension.
Also, you copied a lots of tests and resources which are not needed here, compression etc.

I would better propose to remove all those tests, images, themes, hacks and so on and use example like this:
1. Simple Java component, exampe: https://github.com/vaadin/flow/blob/master/flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/TestForm.java 
2. Lit component counterpart, exaple https://github.com/vaadin/flow/blob/master/flow-tests/test-root-context/frontend/lit-templates/test-form.js
3. Open page with a Lit component, check that it's properly rendered. Example of the test https://github.com/vaadin/flow/blob/master/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/littemplate/ReattachIT.java

2022-09-16 09:04 UTC, MarcinVaadin commented on flow-tests/test-frontend/vite-production-custom-frontend/frontend-custom/lit-invalid-imports.ts
> +console.log(customElement, ce2, ce3, property, p2, state, unsafeHTML, classMap);
Tests simplified

2022-09-16 09:10 UTC, mshabarov approved these changes

2022-09-16 09:10 UTC, mshabarov commented on flow-tests/test-frontend/vite-production-custom-frontend/frontend-custom/lit-templates/test-form.js
> +customElements.define('test-form', TestForm);
```suggestion
customElements.define('test-form', TestForm);

```

2022-09-16 09:10 UTC, mshabarov commented on flow-tests/test-frontend/vite-production-custom-frontend/src/main/java/com/vaadin/viteapp/littemplate/TestForm.java
> +}
```suggestion
}

```

2022-09-16 09:11 UTC, mshabarov approved these changes

2022-09-16 10:36 UTC, mshabarov approved these changes

2022-09-16 10:44 UTC, merged