Adapt to new auto configuration in spring boot. The spring.factories …
vaadin/flow pull request #14629
Opened 2022-09-23 13:00 UTC by aspan

…support for auto configuration was removed in spring boot 3.0.0-M5.

## Description

Spring Boot introduced a new location for auto configuration entries in spring boot 2.7.0. The new location is `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports`. This has until spring boot 3.0.0-M5 worked in parallel with the spring.factories configuration.
The spring.factories support was removed in spring boot 3.0.0-M5 so this move has to be done now in order for the auto configuration to be picked up.

Fixes #14628

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

2022-09-23 13:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=14629) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=14629) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=14629) it.</sub>

2022-09-23 13:23 UTC, mcollovati requested changes

2022-09-23 13:23 UTC, mcollovati commented on vaadin-spring/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
> +com.vaadin.flow.spring.VaadinScopesConfig
new line missing
```suggestion
com.vaadin.flow.spring.VaadinScopesConfig

```

2022-09-23 17:50 UTC, mcollovati commented
Thanks for the contribution

2022-09-23 17:51 UTC, mcollovati submitted a review, later dismissed

2022-09-23 18:14 UTC, Artur- commented
Should this be done for master?

2022-09-26 09:01 UTC, MarcinVaadin approved these changes

2022-09-26 11:20 UTC, mshabarov commented
@Artur- @aspan current `master` uses Spring Boot 2.7, so I think this patch can target `master`. I will make a PR to master soon. 
@aspan thanks for contribution!

2022-09-27 12:57 UTC, mshabarov approved these changes
I've also made a patch for master https://github.com/vaadin/flow/pull/14659

2022-09-28 12:42 UTC, merged