feat: Bring back vaadin servlet mapping behind feature flag
vaadin/flow pull request #14694
Opened 2022-09-29 12:06 UTC by MarcinVaadin

## Description

As there is a need to support custom servlet mapping after it has been removed (#14602) - it has been bring back behind feature flag.

Fixes #14641

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [x] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-09-30 07:04 UTC, Artur- requested changes

2022-09-30 07:04 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
> +    public static final Feature SERVLET_MAPPING = new Feature(
```suggestion
    public static final Feature VAADINSERVLET_PUSH_MAPPING = new Feature(
```

2022-09-30 07:04 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
> +            "Use non-root servlet mapping (/vaadinServlet)", "vaadinServlet",
```suggestion
            "Use /vaadinServlet mapping for push (deprecated)", "vaadinServletForPush",
```

2022-09-30 07:04 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
> +        if (FeatureFlags.get(VaadinService.getCurrent().getContext())
Is there really a current `VaadinService` available at this point?

2022-09-30 10:13 UTC, MarcinVaadin commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
> +        if (FeatureFlags.get(VaadinService.getCurrent().getContext())
Yes, here it is present, there are few issues still that I’m working on:
- Lookup is not available during SpringBootAutoconfiguration so I cannot use FeatureFlags.get( )
- VaadinWebSecurity requires access to Feature flag in static methods
I’m testing solution that for Spring feature is defined within Application Properties - they are available almost from the startup of spring-boot (edited)

2022-10-07 06:30 UTC, mshabarov requested changes

2022-10-07 06:30 UTC, mshabarov commented on flow-tests/vaadin-spring-tests/test-spring-boot-push-mapping/src/main/resources/application.properties
> +vaadin.pushServletMapping=true
I'd propose "nonRootPushServletMapping" (or vice versa - "pushRootServletMapping", true by default) as a name for this parameter, because "pushServletMapping" doesn't tell much about its meaning. Also, not "pushServletMapping=false" doesn't make sense, since mapping is always there.

2022-10-07 06:30 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
> +            mapping = VaadinServletConfiguration.VAADIN_SERVLET_PUSH_MAPPING;
`mapping` is used here not for push endpoint, but for SpringServlet registration, which is fine.
Apart from Push, it is fine to have `/vaadinServlet` mapped spring servlet.
We only talk about mapping path for `JSR356_MAPPING_PATH`, it should be changed, not the spring servlet.
Or I terribly missed something.

2022-10-07 06:30 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
> +            mapping = VaadinServletConfiguration.VAADIN_SERVLET_PUSH_MAPPING;
So in my opinion you should change `pushRegistrationPath` to include `/VAADIN/push` in case of root mapping, but not `mapping` itself.

2022-10-07 06:30 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringServlet.java
> +                return (boolean) Class.forName(
Why we have to do this? Isn't `VaadinConfigurationProperties` instance available in the context where the method `isPushServletMappingEnabled` is needed?

2022-10-07 06:30 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinMVCWebAppInitializer.java
> +            mapping = VaadinServletConfiguration.VAADIN_SERVLET_PUSH_MAPPING;
`mapping` should be "/vaadinServlet", because it corresponds to the servlet, not to the push registration.
`pushRegistrationPath` should be modified.

2022-10-07 06:31 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
> +        } else {
Did I understand correctly that if I've set a custom vaadin url mapping (e.g. `/ui/*`), the mapping for PUSH will be the on `/ui/*` and not on `/ui/VAADIN/push`?
If so, the AJP reverse proxy configuration will still have the same problem of missing a dedicate path for websockets

2022-10-07 06:41 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
> +        } else {
Yes, it would be `/ui/*` and it was so in the past event with `/vaadinServlet`. So seems like if someone uses AJP with non root url mapping, this fix wouldn't work.

2022-10-07 06:44 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
> +        } else {
What if we add `VAADIN/push` always when this new parameter is turned on?

2022-10-07 07:34 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
> +        } else {
I agree, it seems more consistent to me

2022-10-07 09:29 UTC, MarcinVaadin commented
Closing a PR due to approach change. New PR will be created.

2022-10-07 09:29 UTC, closed without merging