Fix Javadoc rendering in AppShellConfigurator
vaadin/flow pull request #14795
Opened 2022-10-10 13:54 UTC by lbruun

## Description

Fixes rendering issue of the example code in the Javadoc for the `AppShellConfigurator` class.
See [Javadoc.io](https://javadoc.io/doc/com.vaadin/flow-server/latest/com/vaadin/flow/component/page/AppShellConfigurator.html) and note how the example code in the class header comment is rendered as one long line.

Fixes #14794.

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-10-10 13:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=14795) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=14795) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=14795) it.</sub>

2022-10-10 13:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=14795) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=14795) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=14795) it.</sub>

2022-10-11 10:36 UTC, caalador requested changes

2022-10-11 10:36 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/component/page/AppShellConfigurator.java
> + * <pre>
The `<pre>` should be added around the `<code>` so that we would get a formatted code block and not replace the code block.

2022-10-11 11:22 UTC, lbruun commented on flow-server/src/main/java/com/vaadin/flow/component/page/AppShellConfigurator.java
> + * <pre>
@caalador : Got it. I take it that you would like to retain the special rendering that Vaadin API site does where `<code>` is rendered on a _grey background_ ? (because in standard Javadoc, you would not be able to see any difference by retaining the `<code>` tag in our example; it would would look exactly the same with or without)

In any case, I've found a few other classes where this is a problem, so I need to update this PR in any case. Might as well fix all places in Flow where this problem occurs in one PR.

2022-10-11 12:06 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/component/page/AppShellConfigurator.java
> + * <pre>
Yes.
Fixing all similar problems at once would be fine.

2022-10-12 04:45 UTC, caalador submitted a review, later dismissed

2022-10-12 04:57 UTC, caalador reviewed
Seems the formatter wants an empty line before `<pre>`

2022-10-12 04:57 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/component/page/AppShellConfigurator.java
> + * <pre>
```suggestion
 * Example:
 * 
 * <pre>
```

2022-10-12 04:57 UTC, caalador commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> + * <pre>
```suggestion
 * For example:
 * 
 * <pre>
```

2022-10-12 04:57 UTC, caalador commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
> + * <pre>
```suggestion
 * For example:
 * 
 * <pre>
```

2022-10-12 06:26 UTC, lbruun commented
> Seems the formatter wants an empty line before `\<pre\>`

Fixed by a new push.

2022-10-12 07:36 UTC, caalador approved these changes

2022-10-12 08:13 UTC, merged