chore!: Require Node 18 (npm 8.6) for Vaadin 24
vaadin/flow pull request #15043
Opened 2022-11-08 12:03 UTC by Artur-

Node 18 is the latest LTS version and what everbody should at least have going forward

2022-11-09 05:26 UTC, caalador approved these changes

2022-11-09 05:49 UTC, caalador requested changes
Slow tests build shows that the autoUpdate tests need to be fixed:
https://teamcity.vaadin.com/buildConfiguration/Flow_FlowPullRequestsValidationSet_ValidationSlow/150996?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&expandBuildTestsSection=true

2022-11-09 05:58 UTC, caalador commented
There are 2 places in `.github/workflows/validation.yml` that have
```
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
```
I guess this could be updated to 18.12.1 so that 2 threads do not try to install the local node version breaking each other.

2022-11-09 07:32 UTC, Artur- commented
Updated GH actions. I think the autoupdate tests were fixed by the autoupdate PR, let's see

2022-11-10 05:05 UTC, caalador approved these changes

2022-11-10 06:58 UTC, merged