doc: list supported transformations (WIP)
vaadin/flow pull request #15097
Opened 2022-11-10 16:28 UTC by vursen

## Description

This PR adds a section to README.md with a list of transformations supported by the Polymer to Lit converter.

Part of #14957

2022-11-11 15:40 UTC, vursen commented on flow-polymer2lit/README.md
> +If your project is using Lit 1 (Vaadin < 23), you can use the `vaadin.useLit1` argument to enforce Lit 1 compatible imports:
```suggestion
If your project is using Lit 1 (Vaadin < 21), you can use the `vaadin.useLit1` argument to enforce Lit 1 compatible imports:
```

2022-11-11 21:51 UTC, vursen commented on flow-polymer2lit/README.md
> +An example of what the converter cannot handle is complex Polymer observers:
```suggestion
Complex Polymer observers is an example of what the converter cannot handle:
```

2022-11-12 16:46 UTC, vursen commented on flow-polymer2lit/README.md
> +An example of what the converter cannot handle is complex Polymer observers:
```suggestion
Complex Polymer observers is an example of what the converter cannot handle:
```

2022-11-12 16:47 UTC, vursen commented on flow-polymer2lit/README.md
> +This is a basic overview of the transformations that can be performed automatically by the converter:
```suggestion
This is an overview of the transformations that can be performed automatically by the converter:
```

2022-11-14 08:04 UTC, mshabarov requested changes

2022-11-14 08:06 UTC, vursen commented on flow-polymer2lit/README.md
> +An example of what the converter cannot handle is complex Polymer observers:
I would still keep "example" in this sentence as it is not the only unsupported thing.

2022-11-14 08:07 UTC, vursen commented on flow-polymer2lit/README.md
> +An example of what the converter cannot handle is complex Polymer observers:
Ah, I see. You suggest making it a list.

2022-11-14 08:09 UTC, mshabarov commented on flow-polymer2lit/README.md
> +An example of what the converter cannot handle is complex Polymer observers:
Yes

2022-11-14 08:14 UTC, vursen commented on flow-polymer2lit/README.md
> +TypeScript source files are not supported.
```suggestion
TypeScript source files are not supported because proper type conversion almost always requires knowing project specifics.
```

2022-11-14 08:17 UTC, vursen commented on flow-polymer2lit/README.md
> +TypeScript source files are not supported.
```suggestion
TypeScript source files are not supported as type organization is almost always project-specific so it is hard to identify common cases.
```

2022-11-14 08:18 UTC, vursen commented on flow-polymer2lit/README.md
> +TypeScript source files are not supported.
Check out these ones: https://github.com/vaadin/flow/pull/15097/files#r1021185748

2022-11-14 08:19 UTC, vursen commented on flow-polymer2lit/README.md
> +TypeScript source files are not supported.
```suggestion
TypeScript source files are not supported because proper type conversion almost always requires knowing project specifics.
```

2022-11-14 10:06 UTC, vursen commented on flow-polymer2lit/README.md
> +An example of what the converter cannot handle is complex Polymer observers:
Made it a list and also added a few more examples. Please, check it out.

2022-11-14 12:20 UTC, mshabarov commented on flow-polymer2lit/README.md
> +- Complex Polymer observers are not supported (`userListChanged(users.*, filter)`).
The previous full code snippet was more explanatory, could we bring it back?

2022-11-14 13:31 UTC, mshabarov approved these changes

2022-11-14 15:43 UTC, merged