feat: Add the authentication context API to the Vaadin Web Security
vaadin/flow pull request #15129
Opened 2022-11-15 13:13 UTC by mshabarov

AuthenticationContext bean provides an API for getting authenticated user details and logout capabilities.

Fixes https://github.com/vaadin/flow/issues/14958

2022-11-15 14:36 UTC, heruan requested changes

2022-11-15 14:36 UTC, heruan commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
> +    <U extends UserDetails> Optional<U> getAuthenticatedUser(Class<U> userType);
Bounding the generic type to `UserDetails` is problematic since that interface is e.g. not implemented by the `DefaultOidcUser` which is the user principal provided by the Spring Security OpenID Connect helpers.

Either we use a less restrictive interface, such as `AuthenticatedPrincipal` or we just unbind the generic type and let the user specify any.

2022-11-15 14:36 UTC, heruan commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +    }
We must be sure this happens after the `filterChain` method has been invoked, since we need to be sure that the `HttpSecurity` instance has all the logout handlers set (i.e. the chain is already built).

Adding `@DependsOn("VaadinSecurityFilterChainBean")` might be enough, but this needs to be tested 🙂

2022-11-15 14:38 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +    }
Good point, I've just noticed that tests fail because of empty logout handlers lists.

2022-11-18 09:48 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +            new DefaultAuthenticationContext();
I'm really not sure whether we should make this bean extendable on the client's codes. My vision is that it's like a service bean providing logout and authenticated user common services and should be configured by Vaadin. If the developer wants to configure the logout handlers or to, for example, invalidate session on logout, he better uses `LogoutConfigurer` in the overriden `configure(HttpSecurity http)` method. Or I missed something?

2022-11-18 10:00 UTC, knoobie commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +            new DefaultAuthenticationContext();
Understandable! If it's by design not overrideable, you could think about the removal of the Interface all together making it implicit that this can't be overwritten and see how people gonna use / complain about it. 

Your example was exactly what I had in mind :) we normally invalide sessions on logout and I was confused why the default implementation doesn't do it and was wondering how I can override it.

2022-11-18 11:29 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +            new DefaultAuthenticationContext();
Yes, good point, I also thought to add invalidation by default.

2022-12-05 14:27 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
> +     * been authenticated, or empty if the user is not authenticated.
@heruan what do you think? Does it make sense to throw an exception (ClassCastException) if the current user object does not match the expected one?

2022-12-06 10:06 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
> +    default Optional<AuthenticatedPrincipal> getAuthenticatedUser() {
Having `AuthenticatedPrincipal` as potential return type may cause problems because, for example, `org.springframework.security.core.userdetails.User` does not implement it and `UserDetails` does not extend it.
Does it make sense to you to simply return an `Optional<Object>`, since also `Authentication::getPrincipal` return type is `Object`?
If a developer needs a specific type, the `getAuthenticatedUser(Class<U> userType)` method can be used.

2022-12-06 10:12 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
> +    default Optional<AuthenticatedPrincipal> getAuthenticatedUser() {
Or even remove the method at all and replace it with a `boolean isAuthenticated()`, since I think the only use of this signature may be something like `if (authContext.getAuthenticatedUser().isPresent()) { ... }`

2022-12-06 10:14 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
> +    default Optional<AuthenticatedPrincipal> getAuthenticatedUser() {
Yes, having `Optional<Object> getAuthenticatedUser()` means that `<U> Optional<U> getAuthenticatedUser(Class<U> userType);` would be used almost always. Having `boolean isAuthenticated()` instead sounds good!

2022-12-07 07:57 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/UidlRedirectStrategy.java
> +            UI.getCurrent().getPage().setLocation(url);
In theory, the `Page.setLocation()` should only be engaged as a result of a user interaction (e.g. pressing a button that invokes `AuthenticationContext.logout()` or the same function invoked through `UI.access()`), but it makes sense to add a check and a WARN or DEBUG log message to be able to debug potentially unexpected situations

2022-12-07 08:21 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +    protected void addLogoutHandlers(Consumer<LogoutHandler> registry) {
Should it be `SerializableConsumer` ?

2022-12-07 08:23 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +    protected void addLogoutHandlers(Consumer<LogoutHandler> registry) {
It should not be needed, since the Consumer should not be referenced anywere in the VaadinSession

2022-12-07 09:32 UTC, heruan commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +    }
Has this been addressed?

2022-12-07 09:35 UTC, heruan commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
> +     * been authenticated, or empty if the user is not authenticated.
Yes, it makes sense to me: let's throw an exception if the casting fails.

2022-12-07 09:35 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +    }
Sorry, I missed the comment. I'll check it

2022-12-07 09:38 UTC, heruan commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
> +    default Optional<AuthenticatedPrincipal> getAuthenticatedUser() {
I'm in favor of adding a `boolean isAuthenticated()` and also unbinding the user type, but then I'd also remove the `Optional<Object> getAuthenticatedUser()` in favor of the `Optional<T> getAuthenticatedUser(Class<? extends T> type)` overload.

2022-12-07 09:39 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +    }
The bean definition method does not take the `HttpSecurity` parameter anymore.
It returns a field initialized instance, that is configured within `filterChain`

2022-12-07 09:45 UTC, mcollovati commented
A summary of the change:

*  `AuthenticationContext` is a concrete class that gets access to the authenticated user and allows performing logout integrated with Spring Security
* Developers can plug additional `LogoutHandler`s in `VaadinWebSecurity.addLogoutHandlers()`
* `VaadinWebSecurity` configures a LogoutSuccessHandler with a redirect strategy that can handle also XHR UIDL requests (`UidlRedirectStrategy`)

2022-12-07 10:09 UTC, heruan approved these changes

2022-12-07 10:20 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
> +            new DefaultAuthenticationContext();
Session is now invalidated by default.  Additional `LogoutHandler`s can be configured with `VaadinWebSecurity.addLogoutHandlers()`

2022-12-07 10:42 UTC, merged