feat!: check license for flow-polymer-template (WIP)
vaadin/flow pull request #15138
Opened 2022-11-15 19:19 UTC by vursen

## Description

Fixes #15137

## Type of change

- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

2022-11-17 12:05 UTC, mshabarov requested changes

2022-11-17 12:05 UTC, mshabarov commented on flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/AbstractTemplate.java
> + * 4.0 (CVDLv4).
Besides the headers, we have to add `LICENSE` file to the module root and update `bnd.bnd`.

2022-11-17 12:05 UTC, mshabarov commented on flow-polymer-template/pom.xml
> +        <cvdlName>flow-polymer-template</cvdlName>
it is used in `bnd.bnd`

2022-11-17 13:14 UTC, vursen commented on flow-polymer-template/pom.xml
> +        <cvdlName>flow-polymer-template</cvdlName>
Done.

2022-11-17 13:17 UTC, vursen commented on flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java
> +                    .warn("Unable to read the version.properties file.", e);
Good point, thanks! Done.

2022-11-17 13:48 UTC, mshabarov submitted a review, later dismissed

2022-11-17 13:55 UTC, mshabarov commented on flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java
> +                    .warn("Unable to read the version.properties file.", e);
You lost the exception throwing.
I meant this code
```
        } catch (Exception e) {
            LoggerFactory.getLogger(PolymerTemplate.class.getName())
                    .error("Unable to read the version.properties file.");
            throw new ExceptionInInitializerError(e);
        }
```
If you won't throw, the NPE will be thrown anyway 2 lines after

2022-11-17 13:57 UTC, vursen commented on flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java
> +                    .error("Unable to read the version.properties file.", e);
```suggestion
            LoggerFactory.getLogger(PolymerTemplate.class.getName())
                    .error("Unable to read the version.properties file.");
            throw new ExceptionInInitializerError(e);
```

2022-11-17 13:57 UTC, vursen commented on flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java
> +                    .warn("Unable to read the version.properties file.", e);
Ah, right. Fixed.

2022-11-17 14:40 UTC, mshabarov approved these changes

2022-11-17 15:02 UTC, Artur- requested changes

2022-11-17 15:02 UTC, Artur- commented on flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java
> +        try {
We do not need a separate version.properties for this module. It is fine to use `com.vaadin.flow.server.Version`

2022-11-18 08:42 UTC, vursen commented on flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java
> +        try {
Good point. Let me update the PR.

2022-11-18 10:55 UTC, vursen commented on flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java
> +        try {
Done.

2022-11-18 10:55 UTC, vursen commented on flow-polymer-template/pom.xml
> +        <resources>
Done.

2022-11-18 11:35 UTC, mshabarov approved these changes

2022-11-18 14:11 UTC, Artur- approved these changes

2022-11-18 14:12 UTC, merged