#14641 Remove pushUrl configuration option; Use dedicated mapping for…
vaadin/flow pull request #15188
Opened 2022-11-17 14:45 UTC by tepi

Removes pushUrl configuration option, and instead maps push always to a dedicated path (/VAADIN/push).

Fixes #14641

2022-11-28 10:45 UTC, mshabarov requested changes

2022-11-28 10:45 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
> +            firstMapping = reg.getMappings().stream().findFirst().orElse("/");
I propose to sort the mappings before taking the first one to make it deterministic and return the same mapping always.

2022-11-30 07:09 UTC, tepi commented
Note: if this is merged, we also need the change the push configuration documentation accordingly

2022-11-30 07:22 UTC, mshabarov approved these changes

2022-11-30 07:46 UTC, merged