feat: Session resynchronization for embedded webcomponents
vaadin/flow pull request #15421
Opened 2022-12-09 10:03 UTC by MarcinVaadin

## Description

This PR adds session resynchronization and embedded web components reloading in case of session expiration. 

Fixes #12592

## Type of change

- [x] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [x] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-12-09 10:15 UTC, MarcinVaadin commented
Known - to be done - issues:
1. Without active server connection component disconnect throws exception: 
```
TypeError: this.$server.disconnected is not a function
$error @ FlowClient.js:10503
$handleError @ FlowClient.js:3789
onUncaughtException @ FlowClient.js:1943
reportUncaughtException @ FlowClient.js:1096
errorHandler @ FlowClient.js:1060
windowRef.onerror @ FlowClient.js:1070
$recreateNodes @ FlowClient.js:3853
accept_14 @ FlowClient.js:3895
$consume @ FlowClient.js:11390
$forEachRemaining_0 @ FlowClient.js:11359
forEachRemaining_1 @ FlowClient.js:11402
$forEach_0 @ FlowClient.js:11538
execute_6 @ FlowClient.js:3905
runScheduledTasks @ FlowClient.js:1257
$flushPostEventPumpCommands @ FlowClient.js:1157
execute_0 @ FlowClient.js:1304
execute @ FlowClient.js:1235
apply_1 @ FlowClient.js:962
entry0 @ FlowClient.js:1001
(anonymous) @ FlowClient.js:989
callback @ FlowClient.js:1276
```
2. When reattaching component some client side readonly constants are already present and it was failing, I've commented out assertion - not sure if safe:
`ConstantPool.importFromJson`: `// assert !constants.has(key);`

2022-12-12 10:14 UTC, Artur- requested changes

2022-12-12 10:14 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/communication/SessionResyncRequestHandler.java
> +        Class<? extends UI> uiClass = getUIClass(request);
It looks quite similar to what `WebComponentBootstrapHandler` does. Could we use that somehow?

2022-12-12 10:25 UTC, MarcinVaadin commented on flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
> -                        registry.getUILifecycle().setState(UIState.TERMINATED);
For non embedded applications there is `WidgetUtil.redirect(url);` so it ends lifecycle eventually. It could be a problem when someone uses own systemErrorHandler (don't know if it is possible or used by anyone).

2022-12-12 10:26 UTC, MarcinVaadin commented on flow-client/src/main/java/com/vaadin/client/flow/ConstantPool.java
> -            assert !constants.has(key);
Good point. As the app is resyncing we always get full state tree with all properties so IMO `ConstantPool` could be cleared without additional issues.

2022-12-12 10:27 UTC, MarcinVaadin commented on flow-server/src/main/java/com/vaadin/flow/server/communication/SessionResyncRequestHandler.java
> +public class SessionResyncRequestHandler extends WebComponentBootstrapHandler {
It could be but as we need to recreate UI lot of helper methods should be duplicated. As this solution is targeted for embedded components currently it was easier just to extend `WebComponentBootstrapHandler`.

2022-12-12 10:31 UTC, MarcinVaadin commented on flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
> +        Xhr.get(serviceUrl, new Xhr.Callback() {
I would need to extend `XhrConnection` and overwrite `getUri()` as I am sending different request type (session-resync instead of uidl).

2022-12-12 10:33 UTC, MarcinVaadin commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +    public static String createSessionResyncJSON(boolean async, UI ui) {
Yes, it looks it could be reused.

2022-12-12 10:36 UTC, MarcinVaadin commented on flow-server/src/main/java/com/vaadin/flow/server/communication/SessionResyncRequestHandler.java
> +        Class<? extends UI> uiClass = getUIClass(request);
I'm afraid not because of `writeBootstrapPage(response, document.head(), serviceUrl);`, I'm already extending `WebComponentBootstrapHandler` and reusing some of it's methods.

2022-12-12 12:02 UTC, Artur- commented
When testing this, I see a request to http://localhost:8080/?v-r=session-resync but that has a 403 response saying "session expired"

2022-12-12 12:39 UTC, MarcinVaadin commented
> When testing this, I see a request to http://localhost:8080/?v-r=session-resync but that has a 403 response saying "session expired"

<img width="441" alt="image" src="https://user-images.githubusercontent.com/106965834/207047235-422b9f31-cd44-470a-b519-46de5b7e6a77.png">
That's strange...

2022-12-12 12:57 UTC, MarcinVaadin commented on flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
> -                        registry.getUILifecycle().setState(UIState.TERMINATED);
Reverted after adding `Registry.reset()`.

2022-12-12 13:06 UTC, MarcinVaadin commented on flow-client/src/main/java/com/vaadin/client/flow/ConstantPool.java
> -            assert !constants.has(key);
Added `Registry.reset()`, no relevant anymore.

2022-12-12 13:26 UTC, MarcinVaadin commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +    public static String createSessionResyncJSON(boolean async, UI ui) {
Removed in favor of `UidlWriter.createUidl`.

2022-12-13 20:30 UTC, MarcinVaadin commented
> Would also need at least one test

Test added

2022-12-13 20:34 UTC, MarcinVaadin commented on flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
> +        Xhr.get(serviceUrl, new Xhr.Callback() {
I've tried to utilize `MessageSender` but `XhrConnector` is part of `Registry` and creating new one is IMO pointless. Heartbeat also send XHR's directly, not through `MessageSender`.

2022-12-19 11:46 UTC, mcollovati commented
Tested manually and it seems to work as expected

2022-12-19 16:17 UTC, mcollovati requested changes

2022-12-19 16:25 UTC, mcollovati commented
A random thought: If we allow `SESSION_RESYNC` request type to create a new session (`VaadinServletService.requestCanCreateSession -> isOtherRequest`), can we just merge the logic of `SessionResyncRequestHandler` into `WebComponentBootstrapHandler`, and on the client side only issue a POST on `<serviceUrl>/web-component/web-component-bootstrap.js`?

2022-12-20 08:32 UTC, MarcinVaadin commented on flow-client/src/main/java/com/vaadin/client/Registry.java
> +    }
Good point

2022-12-20 09:18 UTC, MarcinVaadin commented on flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
> +                Console.log(exception);
Yes, it is a neat way.

2022-12-20 10:38 UTC, MarcinVaadin commented on flow-client/src/main/java/com/vaadin/client/Registry.java
> +    }
I've refactored it in slightly different way - using new instance suppliers in case of registry entry can be reset.

2022-12-20 10:44 UTC, mcollovati commented on flow-client/src/main/java/com/vaadin/client/Registry.java
> +     * resynchronization.
I would not mention "session resynchronization" here because the registry knows nothing about the reasons `reset()` will be invoked.
I think it will be enough to say that the singleton will be recreated in case of registry reset

2022-12-20 10:45 UTC, mcollovati commented on flow-client/src/main/java/com/vaadin/client/Registry.java
> +    }
Good job, I like this solution

2022-12-20 10:50 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +        SESSION_RESYNC(ApplicationConstants.REQUEST_TYPE_SESSION_RESYNC),
I wonder if we should use a name more related to web components, since it is handled by a `WebcomponentBootstrapHandler`

2022-12-20 10:51 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +        SESSION_RESYNC(ApplicationConstants.REQUEST_TYPE_SESSION_RESYNC),
Something like `webcomponent-resync` or `embedded-resync`

2022-12-21 10:01 UTC, MarcinVaadin commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +        SESSION_RESYNC(ApplicationConstants.REQUEST_TYPE_SESSION_RESYNC),
Name updated

2022-12-21 10:01 UTC, MarcinVaadin commented on flow-client/src/main/java/com/vaadin/client/Registry.java
> +     * resynchronization.
Updated

2022-12-21 10:01 UTC, MarcinVaadin commented
> A random thought: If we allow SESSION_RESYNC request type to create a new session (VaadinServletService.requestCanCreateSession -> isOtherRequest), can we just merge the logic of SessionResyncRequestHandler into WebComponentBootstrapHandler, and on the client side only issue a POST on <serviceUrl>/web-component/web-component-bootstrap.js?

Great tip! It allowed removing one XHR request!

2022-12-21 10:03 UTC, MarcinVaadin commented on flow-server/src/main/java/com/vaadin/flow/server/communication/SessionResyncRequestHandler.java
> +public class SessionResyncRequestHandler extends WebComponentBootstrapHandler {
Not relevant after last updates

2022-12-21 10:04 UTC, MarcinVaadin commented on flow-server/src/main/java/com/vaadin/flow/server/communication/SessionResyncRequestHandler.java
> +        Class<? extends UI> uiClass = getUIClass(request);
`WebComponentBootstrapHandler` has been extending with new single method handling webcomponents resynchronization.

2022-12-21 11:32 UTC, mcollovati requested changes
A minor change on a test, but other than that LGTM

2022-12-21 11:32 UTC, mcollovati commented on flow-tests/test-frontend/vite-embedded-session-resync/src/test/java/com/vaadin/viteapp/BasicComponentIT.java
> +        }
I would replace this one with a `waitUntil` to avoid the try/catch
```suggestion
        // Wait for embedded component refresh
        waitUntil(d -> $("login-form").first().$("button").first());
```

2022-12-21 11:58 UTC, MarcinVaadin commented on flow-tests/test-frontend/vite-embedded-session-resync/src/test/java/com/vaadin/viteapp/BasicComponentIT.java
> +        }
I've tested suggestion and it does not resolve the problem - component is physically present so `waitUntil` goes forward and then on first interaction with component `StaleElementReference` is still thrown.

2022-12-21 11:59 UTC, MarcinVaadin commented on flow-tests/test-frontend/vite-embedded-session-resync/src/test/java/com/vaadin/viteapp/BasicComponentIT.java
> +        }
One minor update would be renaming test from `vite-embedded-session-resync` to `vite-embedded-webcomponent-resync`.

2022-12-21 12:02 UTC, mcollovati commented on flow-tests/test-frontend/vite-embedded-session-resync/src/test/java/com/vaadin/viteapp/BasicComponentIT.java
> +        }
> I've tested suggestion and it does not resolve the problem - component is physically present so waitUntil goes forward and then on first interaction with component StaleElementReference is still thrown.

Weird :thinking: 
I tested it locally, and it worked for me, but perhaps it is a timing question. So let's use try/catch since it seems to work seamlessly

2022-12-21 12:02 UTC, mcollovati commented on flow-tests/test-frontend/vite-embedded-session-resync/src/test/java/com/vaadin/viteapp/BasicComponentIT.java
> +        }
> One minor update would be renaming test from vite-embedded-session-resync to vite-embedded-webcomponent-resync

It seems like a good idea

2022-12-21 12:08 UTC, mcollovati approved these changes

2022-12-21 12:54 UTC, mcollovati approved these changes

2022-12-21 13:02 UTC, merged