feat: Compare bundle and package.json contents
vaadin/flow pull request #15504
Opened 2022-12-15 12:31 UTC by caalador

Compare the stored hash of the bundle and package.json compare the dependency modules in bundle and package json compate NpmPackage annotations and bundle modules.

part of #15376

2022-12-15 14:27 UTC, Artur- requested changes

2022-12-15 14:27 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +            if (!options.productionMode && options.isDevBundleBuild()) {
This could have a comment why it is exaclty in this position

2022-12-15 14:27 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +            // without stats.json in bundle we can not say if it is up to date
You can never get here as the method throws an exception. Maybe it should not

2022-12-15 14:27 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +            if (!bundleNpmModules.hasKey(dependency)) {
Is version comparison for another PR?

2022-12-15 14:27 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +        if (!hasAllNpmModules(statsJson, packageJson, npmPackages)) {
Cannot `hasAllNpmModules` and `bundleModulesEqual` be combined into one?

2022-12-16 07:04 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +        if (!hasAllNpmModules(statsJson, packageJson, npmPackages)) {
Combined checks

2022-12-16 10:16 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +                .collect(Collectors.toList());
This checks `dependencies` against `dependencies`, which gives an empty collection always. Should it check `bundleModules` agains `dependencies`?

2022-12-16 10:23 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +        collection = Arrays.stream(dependencies.keys())
Can we merge these two checks (dependencies exists and version match) into one loop, so it would take less time?

2022-12-16 10:28 UTC, mshabarov requested changes

2022-12-16 10:28 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +        if (packageJsonHash == null || packageJsonHash.isEmpty()) {
We can put a warning message here, because this is something unexpected if package.json doesn't have a hash.

2022-12-16 10:29 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +        collection = Arrays.stream(dependencies.keys())
Well this choice was more of a being able to give a good exception message. Either it is missing or then the version is wrong. Also how big are the sets normally?

2022-12-16 10:31 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +                .collect(Collectors.toList());
fixed.

2022-12-16 10:31 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +        if (packageJsonHash == null || packageJsonHash.isEmpty()) {
added

2022-12-16 10:32 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +        collection = Arrays.stream(dependencies.keys())
Hundreds of items I guess, which is nothing basically. Ok, let's keep it as is, ignore me :)

2022-12-16 10:33 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +                .collect(Collectors.toList());
Do the tests need a tweak because of that ? :)

2022-12-16 10:44 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +                .collect(Collectors.toList());
The test: `hashesMatch_statsMissingPackageJsonPackage_compilationRequired` tests that and the original mistake should have failed the test because the next part throws `java.lang.NullPointerException: Cannot invoke "elemental.json.JsonString.getString()" because the return value of "elemental.json.impl.JreJsonObject.get(String)" is null` Why the test passes even though something is thrown...

2022-12-16 10:45 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +                .collect(Collectors.toList());
Oh. needsBuild eats exceptions and only logs them and says do rebuild

2022-12-16 10:53 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +                .collect(Collectors.toList());
change test to use the internal method that doesn't catch

2022-12-16 11:17 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +        List<String> collection = Arrays.stream(dependencies.keys())
```suggestion
        List<String> missingFromBundle = Arrays.stream(dependencies.keys())
```

2022-12-16 11:18 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +                        .equals(bundleModules.getString(pkg)))
Won't an equals check always fail for range versions like `^1` or `~2.3.4` ?

2022-12-16 11:20 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +    private static boolean missingNpmPackages(Map<String, String> npmPackages,
```suggestion
    private static boolean dependenciesContainsAllPackages(Map<String, String> npmPackages,
```
+ inverse logic to be more readable

2022-12-16 11:45 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +                        .equals(bundleModules.getString(pkg)))
Yes. Didn't think about that as we always use specific versions. I'll update it to use FrontendVersion.

2022-12-16 12:05 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +                        .equals(bundleModules.getString(pkg)))
Now this is a can of worms for the acceptance.

2022-12-16 12:06 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +        List<String> collection = Arrays.stream(dependencies.keys())
done

2022-12-16 12:06 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +    private static boolean missingNpmPackages(Map<String, String> npmPackages,
done,

2022-12-16 12:54 UTC, mshabarov approved these changes

2022-12-16 14:03 UTC, merged