feat: Add dev-bundle-build mojo
vaadin/flow pull request #15526
Opened 2022-12-19 13:10 UTC by caalador

Add a maven mojo to generate
a dev-bundle for express mode.
Add test bundle module.

Next is checking/using dev bundle from jar.

Part of #15376

2022-12-19 14:56 UTC, Artur- commented
Why would this ever need to be done from Maven?

2022-12-19 18:50 UTC, caalador commented
To not need to run up a server just to create a development bundle.
It's not meant for use by others so should not be documented or mentioned.

2022-12-19 19:01 UTC, Artur- commented
If it is only for us, we should not add it in the flow maven plugin. To me it sounds ok to start and stop a server to create a dev bundle for testing

2022-12-19 19:24 UTC, caalador commented
But that's not how it should work. There is no need of a server that requires a port and all of the other things when it is actually just a simple method that needs to be executed. Also it's also for the platform bundle and not just for flow tests.
It could basically also be a simple application that you run, but maven knows the paths by default and we have all that is needed there already. As a proto running a server to generate the bundle is fine, but actually generating it should not be dependent on the overhead and external things.
I can make another plugin just for this so it's not added to the vaadin-maven-plugin.

2022-12-20 15:25 UTC, mshabarov requested changes

2022-12-20 15:25 UTC, mshabarov commented on flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
> +    private File webpackOutputDirectory;
Maybe rename it to `webappOutputDirectory`, because no webpack in V24 anymore?

2022-12-20 15:25 UTC, mshabarov commented on flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
> +    private String useDeprecatedV14Bootstrapping;
Shouldn't be here, since we target V24.

2022-12-20 15:25 UTC, mshabarov commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +                    .withWebpack(adapter.webpackOutputDirectory(),
No webpack

2022-12-20 15:25 UTC, mshabarov commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +                    .useV14Bootstrap(false).enablePackagesUpdate(true)
No legacy V14 bootstrap mode

2022-12-20 15:25 UTC, mshabarov commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +                adapter.logWarn("Unable to delete token file", e);
Should be bundle built be interrupted in this case by throwing an exception?

2022-12-20 15:25 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
>              // TODO: check for jar dev-bundle
This TODO is probably not needed anymore, if hasJarBundle() is in place?

2022-12-20 15:25 UTC, mshabarov commented on flow-tests/test-dev-bundle/pom.xml
> +<!--        </dependency>-->
Remove commented codes

2022-12-20 15:25 UTC, mshabarov commented on flow-tests/test-dev-bundle/src/main/java/com/vaadin/devbundle/Deps.java
> +}
```suggestion
}

```

2022-12-20 15:25 UTC, mshabarov commented on flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
> +    private boolean eagerServerLoad;
As this plugin's main usage is to build the default dev bundle, maybe we can just apply the default values to most of the parameters here? The list of parameters looks really huge. And if developers are not supposed to configure this plugin by themselves, these configurable parameters are probably not needed.

2022-12-20 15:25 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +                .getResource("vaadin-dev-bundle/" + filename);
What is we expose the name `vaadin-dev-bundle` as a constant for platform? Then it can be reused there. Otherwise, we would have two places with a hardcoded directory name.

2022-12-20 15:25 UTC, mshabarov commented on flow-tests/test-npm-only-features/pom.xml
> +        <module>test-dev-bundle-no-plugin</module>
What is this module for?

2022-12-20 15:25 UTC, mshabarov commented on flow-tests/test-npm-only-features/test-dev-bundle-no-plugin/src/main/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/MultipleNpmPackageAnnotationsView.java
> +//    }
Remove commented codes

2022-12-21 05:09 UTC, caalador commented on flow-plugins/flow-dev-bundle-plugin/README.md
> +Goal that generates a dev-bundle for the frontend.
Actually you need to use `mvn com.vaadin:flow-dev-bundle-plugin:build-dev-bundle` as the `mvn flow:prepare-frontend` is basically the same as `mvn flow-maven-plugin:prepare-frontend` as maven only infers the `-maven-plugin` part.
Perhaps if we want the shorthand we should rename the plugin to `flow-dev-bundle-maven-plugin` then I think it should work as `mvn flow-dev-bundle:build-dev-bundle` if defined in the pom, but I don't see the need for that.

2022-12-21 06:56 UTC, mshabarov commented on flow-plugins/flow-dev-bundle-plugin/README.md
> +Goal that generates a dev-bundle for the frontend.
Yeah, we can keep the naming as is. But then all the more better to indicate here how to run this goal: `mvn com.vaadin:flow-dev-bundle-plugin:build-dev-bundle`

2022-12-21 07:48 UTC, caalador commented on flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
> +    private String useDeprecatedV14Bootstrapping;
Removed after merge from master

2022-12-21 07:49 UTC, caalador commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +                    .useV14Bootstrap(false).enablePackagesUpdate(true)
was removed after merge form master.

2022-12-21 08:57 UTC, mshabarov approved these changes

2022-12-21 08:58 UTC, merged