Added Svg component
vaadin/flow pull request #15540
Opened 2022-12-21 17:55 UTC by mstahv

A very trivial implementation capable only do display static SVG at this point.

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-12-22 08:06 UTC, OlliTietavainenVaadin commented on flow-server/src/main/java/com/vaadin/flow/component/Svg.java
> +            throw new IllegalArgumentException("HTML cannot be null or empty");
SVG, not HTML

2022-12-23 13:53 UTC, mstahv commented
If any of @vaadin/flow team member or other core hackers would have good idea how to quickly implement a way to create to root element with createElementNS or another hack how to get rid of the wrapper div, it would be cleaner and good for forward compatibility (in case we ever get SVG support to Element API). Otherwise I believe this component would already help people as such.

2022-12-28 10:36 UTC, taefi commented
Thanks @mstahv for the contribution. Just a question, why isn't using the `Image` helping? For example, I'm representing an SVG logo like this: 

```
Image logo = new Image("images/some-logo.svg", "logo"); // where it is located under META-INF.resources
```
and add it directly to the layout.

2022-12-29 08:14 UTC, mstahv commented
@taefi : "Compared to using SVG as Image source, the SVG content displayed using this component can be styled with CSS."

With CSS you can for example change colors of icons without actually touching the SVG itself. @anezthes Can provide you more details.

I don't think dynamic creation of SVG itself has nothing to do with this case, that can be done with Image already if needed. This is more about styling and discoverability/documentation.

2022-12-29 12:28 UTC, taefi requested changes

2022-12-29 12:28 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/component/Svg.java
> +        super(new Element("div"));
```suggestion
        this();
```

2022-12-29 12:28 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/component/Svg.java
> +        super(new Element("div"));
```suggestion
        this();
```

2022-12-29 12:28 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/component/Svg.java
> +    }
IMO, there is a behavioural inconsistency between this `setSvg(String svg)` method and the constructor that accepts `String svg` as input argument. If a `null` or empty svg content is valid (as it is assumed so in this method), that constructor should not check the input for a `null` or empty content and should just call this setter method. Otherwise, let's move that logic into this method and again call this setter within the constructor.

2022-12-29 12:28 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/component/SvgTest.java
> +                                    """;
(Not really that important)
Is the extra line and empty string in the end intentional? Otherwise, we can remove it:
```suggestion
            </svg>""";
```

2022-12-29 12:28 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/component/SvgTest.java
> +                                    """;
Same for the next SVG static content definitions.

2022-12-29 12:28 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/component/SvgTest.java
> +        Svg html = new Svg(TRIVIAL_SVG);
I suggest to improve the naming of local variable `html`, for example to something like `svg`. (Same for the next tests)

2022-12-29 12:28 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/component/SvgTest.java
> +                html.getElement().getProperty("innerHTML").startsWith("<svg"));
I would suggest to add an additional method like `getSvgContent` to the `Svg` component, so that the user don't have to deal with low-level API to get the content anymore.

2022-12-29 12:30 UTC, taefi requested changes

2022-12-29 12:30 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/component/Svg.java
> +     * Creates an instance based on the given SVG string. The the string must
```suggestion
     * Creates an instance based on the given SVG string. The string must
```

2022-12-29 12:36 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/component/Svg.java
> +    public void setSvg(String svg) {
I suggest to rename the setters for the content of the Svg component to `setContent`, since having a `svg` variable and calling a `setSvg` method on it is verbose and even a little confusing.
```suggestion
    public void setContent(String svgContent) {
```

2022-12-29 12:44 UTC, mstahv commented on flow-server/src/main/java/com/vaadin/flow/component/Svg.java
> +    }
Yeah, remains of a copy pasted initial poc from Html...

2022-12-29 12:47 UTC, mstahv commented on flow-server/src/main/java/com/vaadin/flow/component/Svg.java
> +    public void setSvg(String svg) {
I don't agree. That method name would confuse people to pass in only content of the top level svg element.

2022-12-29 12:49 UTC, mstahv commented on flow-server/src/main/java/com/vaadin/flow/component/Svg.java
> +    public void setSvg(String svg) {
In Image we have setSrc. Don't like that either, especially in that shorthand form.

2022-12-29 13:23 UTC, mstahv commented
@taefi This is because Vaadin is creating the svg element on the client side with createElement, should use createElmentNS (or something to create it with the different namespace).

2022-12-29 13:26 UTC, mstahv commented
Do I remember wrong or was there some "virtual child" concept? That with some JS hack maybe (if we don't want to touch the client side code and add an actual framework feature)?

2022-12-29 13:49 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/component/Svg.java
> +    public void setSvg(String svg) {
I get your concern about a situation that someone might pass children contents of a `svg` instead of including the `<svg ...> </svg>` itself as well, but imagining myself reading/reviewing a code/documentation/tutorial (having a `Svg svg = new Svg();` in the context), I still prefer:
```
svg.setContent("<svg ...></svg>");
```
over
```
svg.setSvg("<svg ...></svg>");
```
Maybe this is only my personal taste.

Btw, we can address that issue by a good documentation. Also, given the fact that the implementation of the `validateAndSet` is taking care of the presence of additional contents such as `<?xml ...>` or `<!DOCTYPE svg... >`, or not having the `<svg ...>` in the input, I don't see a reason to add the verbosity.

2022-12-29 14:44 UTC, taefi commented
> @taefi This is because Vaadin is creating the svg element on the client side with createElement, should use createElmentNS (or something to create it with the different namespace).

I'm not sure if this is somehow related as well, but there seems to be an open issue for rendering `<svg>` in shadow dom:
https://github.com/WICG/webcomponents/issues/179

2023-01-01 09:12 UTC, taefi commented
@mstahv please `format` and push one last time to make it OK to merge. 

Another issue for could be created labeled as improvement. It is good to be merged IMO.

2023-01-02 07:00 UTC, mstahv commented
Formatted✅

Enhancement issue: https://github.com/vaadin/flow/issues/15601

2023-01-02 09:17 UTC, taefi approved these changes

2023-01-02 09:19 UTC, merged