feat: add API to get/fetch page direction
vaadin/flow pull request #15598
Opened 2023-01-01 00:46 UTC by taefi

## Description

Add API to fetch the document.dir from browser
and pass it to the provided callback.

Fixes #15597 

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2023-01-01 00:48 UTC, taefi commented
This change has no dependency on the new features of the platform, and it can be back-ported to all the versions.

2023-01-01 11:25 UTC, mcollovati requested changes
Just a thought: it seems a bit odd to me that we set the direction on `UI`, but fetch it from `Page`.

Would it make sense to store direction value in `UI` or in `UIInternals` (as we do for title, for example) and have also a `UI.getDirection()` method?

2023-01-01 11:25 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
> +        UI.getCurrent().getPage().executeJs("return document.dir")
Do we need `UI.getCurrent().getPage()` here, since the method is not static? Could it be simply a call to `executeJs`?
```suggestion
        executeJs("return document.dir")
```

2023-01-01 18:18 UTC, taefi commented
> Would it make sense to store direction value in `UI` or in `UIInternals` (as we do for title, for example) and have also a `UI.getDirection()` method?

IMO, keeping the state for those kind of stuff that can be changed on the client-side (for instance with a custom Js script)  makes it hard to keep it in sync with the corresponding value on the server side, and would make it complicated to cover corner cases, and it becomes unreliable as the result. Reading it from the browser on demand would be much simpler. But, I'm open to new ideas. 

> Just a thought: it seems a bit odd to me that we set the direction on `UI`, but fetch it from `Page`.

It is a little hard to decide where to put an API when it comes to decide Page and UI, and to be honest, I also struggled over this a little, but in the end I decided to put into the Page class since it was technically close to `fetchCurrentUrl` method. But, there's no heart feelings ;) I can move it to the UI class, as the added method and the correspondent tests aren't complicated and dependent on something in the Page class specifically.

2023-01-01 18:19 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
> +        UI.getCurrent().getPage().executeJs("return document.dir")
This was a left over from my draft codes, good catch!

2023-01-01 18:28 UTC, mcollovati commented
If we don't hold state and always fetch the information from the client, I think it is fine to have the method on Page class

2023-01-01 18:36 UTC, mcollovati approved these changes

2023-01-02 09:35 UTC, merged

2023-01-04 09:49 UTC, ZheSun88 commented
this is  a new feature, which should not be picked to maintenance branch.  23.2 and 23.3