feat: Util for opening a file in the IDE running the application
vaadin/flow pull request #15605
Opened 2023-01-02 09:31 UTC by Artur-

Supports Eclipse, IntelliJ and VS Code

Depends on #15602 and #15604

2023-01-02 11:08 UTC, knoobie commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains("eclipse")) {
Missing NetBeans here? ;)

2023-01-02 14:01 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains("eclipse")) {
Yes! It is missing! :)

2023-01-02 14:23 UTC, knoobie commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains("eclipse")) {
You can mark this question as done if it's not intended to be supported for netbeans :) was just wondering because I've seen 2-3 people using it in discord

2023-01-02 14:50 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains("eclipse")) {
It can be added later on if there is demand and if netbeans provides a way to open a file on a given line number.

2023-01-04 17:03 UTC, Artur- commented
Can't think of how this could be auto tested

2023-01-05 18:20 UTC, czp13 commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains("eclipse")) {
Does it make sense to use constants where we use at least twice a String?
for example: `eclipse`, `intellij`, `vscode`  Here.

And `.java` in vaadin-dev-server/src/main/java/com/vaadin/base/devserver/IdeIntegration.java could be constants.

2023-01-05 18:33 UTC, czp13 commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/IdeIntegration.java
> +            getLogger().error(getClass().getSimpleName()
I do not see based on this PR, but is there any check or information somewhere else to block the execution of this when we are in production? (maybe the full devserver concept is only executed when we are in dev mode? I assume)

2023-01-05 20:00 UTC, czp13 commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/IdeIntegration.java
> +                System.out.println(location);
Does it make sense to use getLogger().info or debug() something for logging, not System.out.println()?

2023-01-05 20:00 UTC, czp13 commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/IdeIntegration.java
> +            System.out.println(location);
here as well just like above, could make sense.

2023-01-05 20:04 UTC, czp13 commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains("vscode") || cmdLower.contains("vs code")
could make sense to not just lower but remove spaces as well?:
- `String cmdLowerNoSpace = cmdLower.replaceAll("\\s","");`

And then i the if-s it can be a bit shorter and maybe more robust.

2023-01-05 20:09 UTC, czp13 commented
Added some minor comments. 🙇 Thank you.

2023-01-05 20:09 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/IdeIntegration.java
> +                System.out.println(location);
The idea here is explicitly not to log, but to output to the IDE console in a format so that the IDE converts it to a clickable link (in the case the IDE was not identified correctly)

2023-01-05 22:06 UTC, czp13 commented
> Can't think of how this could be auto tested
Maybe with:
-  mocked unit tests, to see if the log formatting 
- and if/else are always running properly in every case, and we are in a good execution branch,
- and so make sure to not break with any further changes,
  
and do not have many test cases probably with mc/dc coverage testing, or at least some smoke tests...

p.s: thanks for considering other comments

2023-01-10 08:31 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/IdeIntegration.java
> +public class IdeIntegration {
nit: we can maybe make the class `final`

2023-01-10 08:31 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +package com.vaadin.base.devserver;
License header missing

2023-01-10 08:33 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +public class OpenInCurrentIde {
nit: perhaps can be final and have a private constructor throwing an exception, as the only public method of the class is static

2023-01-10 08:46 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains(INTELLIJ_IDENTIFIER)) {
Tried this locally running from IDEA on Linux, but it was unable to detect the IDE.

Here's the list of commands checked by the above code
```
/home/marco/.sdkman/candidates/java/17.0.2-tem/bin/java
/home/marco/local/tools/idea/2021.3/jbr/bin/java
/usr/lib/systemd/systemd
```

2023-01-10 08:54 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains(INTELLIJ_IDENTIFIER)) {
How did you start the application? A Maven target or running a Spring Boot application class?

2023-01-10 08:58 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains(INTELLIJ_IDENTIFIER)) {
Right click on Application class and then Run

2023-01-10 09:29 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains(INTELLIJ_IDENTIFIER)) {
So detecting "idea" would work in this case..

2023-01-10 09:39 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains(INTELLIJ_IDENTIFIER)) {
Ah, should it look at `p.info().arguments()` and check for `com.intellij.idea.Main`, is that how it is launched on Linux?

2023-01-10 09:46 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains(INTELLIJ_IDENTIFIER)) {
Only if I unzip the IDE into an `idea` directory.
Would it make sense to search the token in `info().commandLine()` instead of `info().command()`?
For IDEA, `intellij` string should match at least a jar name.
Another way could be to search for the system properties added by IDEA (e.g. ` -Didea.vendor.name=JetBrains`)

2023-01-10 09:56 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains(INTELLIJ_IDENTIFIER)) {
> Ah, should it look at `p.info().arguments()` and check for `com.intellij.idea.Main`, is that how it is launched on Linux?

`arguments()` is always empty for me

2023-01-10 10:04 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains(INTELLIJ_IDENTIFIER)) {
And this is weird because if I do a  `ps` I can see then `com.intellij.idea.Main` paramter

2023-01-10 10:13 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains(INTELLIJ_IDENTIFIER)) {
It seems like that Java `Info` object has a cut command line, compared to what I get with the `ps` command

2023-01-10 10:26 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +public class OpenInCurrentIde {
Done

2023-01-10 10:26 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +package com.vaadin.base.devserver;
Done

2023-01-10 10:26 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/IdeIntegration.java
> +public class IdeIntegration {
Done

2023-01-10 10:26 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/IdeIntegration.java
> +package com.vaadin.base.devserver;
Done

2023-01-10 10:26 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains(INTELLIJ_IDENTIFIER)) {
Try again now

2023-01-10 10:49 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains(INTELLIJ_IDENTIFIER)) {
Now the IDE is detected :+1: 
`OpenInCurrentIde.openFile()` does not work with the `idea` protocol for me, but it is for sure because of missing configuration on my laptop

2023-01-10 11:50 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains(INTELLIJ_IDENTIFIER)) {
So if you put `idea://open?file=foo.java` in the browser location bar, it does not work either?

2023-01-10 11:54 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains(INTELLIJ_IDENTIFIER)) {
It seems like that `idea` protocol does not work with the latest IDEA version 

https://youtrack.jetbrains.com/issue/IDEA-284396

I'm on 2022.3

2023-01-10 12:19 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains(INTELLIJ_IDENTIFIER)) {
2022.1.3 on Mac -> works fine

2023-01-10 12:25 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains(INTELLIJ_IDENTIFIER)) {
Yeah, it seems `idea` protocol works only on Mac

2023-01-10 12:52 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains(INTELLIJ_IDENTIFIER)) {
Then we can use the idea launch command but that requires `findIdeCommand()` then to return the proper command. Does it do that?

2023-01-10 13:25 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains(INTELLIJ_IDENTIFIER)) {
I added a main method to `com.vaadin.base.devserver.OpenInCurrentIde` so that this can be debugged now and in the future. If you post the result we can make it into a unit test to see that it works properly

2023-01-10 13:56 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains(INTELLIJ_IDENTIFIER)) {
```
Process:
Command: /home/marco/.sdkman/candidates/java/17.0.5-tem/bin/java
Command line: /home/marco/.sdkman/candidates/java/17/bin/java -javaagent:/home/marco/local/tools/idea/2021.3/lib/idea_rt.jar=46177:/home/marco/local/tools/idea/2021.3/bin -Dfile.encoding=UTF-8 -classpath /home/marco/tmp/my-app-v24/target/classes:/home/marco/.m2/repository/com/vaadin/vaadin/24.0-SNAPSHOT/vaadin-24.0-20230110.022317-120.jar:/home/marco/.m2/repository/com/vaadin/vaadin-core/24.0-SNAPSHOT/vaadin-core-24.0-20230110.022311-120.jar:/home/marco/.m2/repository/com/vaadin/flow-server/24.0-SNAPSHOT/flow-server-24.0-SNAPSHOT.jar:/home/marco/.m2/repository/com/vaadin/servletdetector/throw-if-servlet3/1.0.2/throw-if-servlet3-1.0.2.jar:/home/marco/.m2/repository/com/vaadin/flow-commons-upload/24.0-SNAPSHOT/flow-commons-upload-24.0-SNAPSHOT.jar:/home/marco/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar:/home/marco/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.14.1/jackson-core-2.14.1.jar:/home/marco/.m2/repository/org/jsoup/jsoup/1.15.3/jsoup-1.15.3.jar:/home/marco/.m2/repository/com/helger/ph-css/6.5.0/ph-css-6.5.0.jar:/home/marco/.m2/repository/com/helger/commons/ph-commons/10.1.6/ph-commons-10.1.6.jar:/home/marco/.m2/repository/com/vaadin/external/gentyref/1.2.0.vaadin1/gentyref-1.2.0.vaadin1.jar:/home/marco/.m2/repository/org/apache/commons/commons-compress/1.22/commons-compress-1.22.jar:/home/marco/.m2/repository/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar:/home/marco/.m2/repository/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar:/home/marco/.m2/repository/com/vaadin/vaadin-dev-server/24.0-SNAPSHOT/vaadin-dev-server-24.0-SNAPSHOT.jar:/home/marco/.m2/repository/com/vaadin/open/8.4.0.3/open-8.4.0.3.jar:/home/marco/.m2/repository/com/vaadin/flow-lit-template/24.0-SNAPSHOT/flow-lit-template-24.0-SNAPSHOT.jar:/home/marco/.m2/repository/com/vaadin/flow-push/24.0-SNAPSHOT/flow-push-24.0-SNAPSHOT.jar:/home/marco/.m2/repository/com/vaadin/external/atmosphere/atmosphere-runtime/3.0.0.slf4jvaadin2/atmosphere-runtime-3.0.0.slf4jvaadin2.jar:/home/marco/.m2/repository/jakarta/inject/jakarta.inject-api/2.0.1/jakarta.inject-api-2.0.1.jar:/home/marco/.m2/repository/com/vaadin/flow-client/24.0-SNAPSHOT/flow-client-24.0-SNAPSHOT.jar:/home/marco/.m2/repository/com/vaadin/flow-html-components/24.0-SNAPSHOT/flow-html-components-24.0-SNAPSHOT.jar:/home/marco/.m2/repository/com/vaadin/flow-data/24.0-SNAPSHOT/flow-data-24.0-SNAPSHOT.jar:/home/marco/.m2/repository/com/vaadin/flow-dnd/24.0-SNAPSHOT/flow-dnd-24.0-SNAPSHOT.jar:/home/marco/.m2/repository/org/webjars/npm/vaadin__vaadin-mobile-drag-drop/1.0.1/vaadin__vaadin-mobile-drag-drop-1.0.1.jar:/home/marco/.m2/repository/org/webjars/npm/mobile-drag-drop/2.3.0-rc.2/mobile-drag-drop-2.3.0-rc.2.jar:/home/marco/.m2/repository/com/vaadin/vaadin-lumo-theme/24.0-SNAPSHOT/vaadin-lumo-theme-24.0-20230109.170111-251.jar:/home/marco/.m2/repository/com/vaadin/vaadin-material-theme/24.0-SNAPSHOT/vaadin-material-theme-24.0-20230109.170111-251.jar:/home/marco/.m2/repository/com/vaadin/vaadin-accordion-flow/24.0-SNAPSHOT/vaadin-accordion-flow-24.0-20230109.170111-251.jar:/home/marco/.m2/repository/com/vaadin/vaadin-avatar-flow/24.0-SNAPSHOT/vaadin-avatar-flow-24.0-20230109.170111-251.jar:/home/marco/.m2/repository/com/vaadin/vaadin-button-flow/24.0-SNAPSHOT/vaadin-button-flow-24.0-20230109.170111-251.jar:/home/marco/.m2/repository/com/vaadin/vaadin-checkbox-flow/24.0-SNAPSHOT/vaadin-checkbox-flow-24.0-20230109.170111-251.jar:/home/marco/.m2/repository/com/vaadin/vaadin-combo-box-flow/24.0-SNAPSHOT/vaadin-combo-box-flow-24.0-20230109.170111-251.jar:/home/marco/.m2/repository/com/vaadin/vaadin-confirm-dialog-flow/24.0-SNAPSHOT/vaadin-confirm-dialog-flow-24.0-20230109.170111-251.jar:/home/marco/.m2/repository/com/vaadin/vaadin-custom-field-flow/24.0-SNAPSHOT/vaadin-custom-field-flow-24.0-20230109.170111-251.jar:/home/marco/.m2/repository/com/vaadin/vaadin-date-picker-flow/24.0-SNAPSHOT/vaadin-date-picker-flow-24.0-20230109.170111-251.jar:/home/marco/.m2/repository/com/vaadin/vaadin-date-time-picker-flow/24.0-SNAPSHOT/vaadin-date-time-picker-flow-24.0-2023010

Process:
Command: /home/marco/local/tools/idea/2021.3/jbr/bin/java
Command line: /home/marco/local/tools/idea/2021.3/jbr/bin/java -classpath /home/marco/local/tools/idea/2021.3/lib/util.jar:/home/marco/local/tools/idea/2021.3/lib/app.jar:/home/marco/local/tools/idea/2021.3/lib/3rd-party-rt.jar:/home/marco/local/tools/idea/2021.3/lib/platform-statistics-devkit.jar:/home/marco/local/tools/idea/2021.3/lib/jps-model.jar:/home/marco/local/tools/idea/2021.3/lib/stats.jar:/home/marco/local/tools/idea/2021.3/lib/protobuf.jar:/home/marco/local/tools/idea/2021.3/lib/external-system-rt.jar:/home/marco/local/tools/idea/2021.3/lib/forms_rt.jar:/home/marco/local/tools/idea/2021.3/lib/intellij-test-discovery.jar:/home/marco/local/tools/idea/2021.3/lib/annotations.jar:/home/marco/local/tools/idea/2021.3/lib/groovy.jar:/home/marco/local/tools/idea/2021.3/lib/3rd-party-native.jar:/home/marco/local/tools/idea/2021.3/lib/annotations-java5.jar:/home/marco/local/tools/idea/2021.3/lib/byte-buddy-agent.jar:/home/marco/local/tools/idea/2021.3/lib/error-prone-annotations.jar:/home/marco/local/tools/idea/2021.3/lib/externalProcess-rt.jar:/home/marco/local/tools/idea/2021.3/lib/idea_rt.jar:/home/marco/local/tools/idea/2021.3/lib/intellij-coverage-agent-1.0.682.jar:/home/marco/local/tools/idea/2021.3/lib/jsch-agent.jar:/home/marco/local/tools/idea/2021.3/lib/jsp-base.jar:/home/marco/local/tools/idea/2021.3/lib/junit.jar:/home/marco/local/tools/idea/2021.3/lib/junit4.jar:/home/marco/local/tools/idea/2021.3/lib/kotlin-script-runtime.jar:/home/marco/local/tools/idea/2021.3/lib/platform-duplicates-analysis.jar:/home/marco/local/tools/idea/2021.3/lib/platform-objectSerializer-annotations.jar:/home/marco/local/tools/idea/2021.3/lib/platform-structuralSearch.jar:/home/marco/local/tools/idea/2021.3/lib/rd.jar:/home/marco/local/tools/idea/2021.3/lib/tools-testsBootstrap.jar:/home/marco/local/tools/idea/2021.3/lib/util_rt.jar:/home/marco/local/tools/idea/2021.3/lib/xml-dom-impl.jar:/home/marco/local/tools/idea/2021.3/lib/xml-dom.jar:/home/marco/local/tools/idea/2021.3/lib/ant/lib/ant.jar -Xms128m -Xmx750m -XX:ReservedCodeCacheSize=512m -XX:+UseG1GC -XX:SoftRefLRUPolicyMSPerMB=50 -XX:CICompilerCount=2 -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -XX:+IgnoreUnrecognizedVMOptions -XX:CompileCommand=exclude,com/intellij/openapi/vfs/impl/FilePartNodeRoot,trieDescend -ea -Dsun.io.useCanonCaches=false -Dsun.java2d.metal=true -Djbr.catch.SIGABRT=true -Djdk.http.auth.tunneling.disabledSchemes="" -Djdk.attach.allowAttachSelf=true -Djdk.module.illegalAccess.silent=true -Dkotlinx.coroutines.debug=off -Dsun.tools.attach.tmp.only=true -Xmx1985m -XX:ErrorFile=/home/marco/java_error_in_idea_%p.log -XX:HeapDumpPath=/home/marco/java_error_in_idea_.hprof -Djb.vmOptionsFile=/home/marco/.config/JetBrains/IdeaIC2022.3/idea64.vmoptions -Djava.system.class.loader=com.intellij.util.lang.PathClassLoader -Didea.vendor.name=JetBrains -Didea.paths.selector=IdeaIC2022.3 -Djna.boot.library.path=/home/marco/local/tools/idea/2021.3/lib/jna/amd64 -Dpty4j.preferred.native.folder=/home/marco/local/tools/idea/2021.3/lib/pty4j -Djna.nosys=true -Djna.nounpack=true -Didea.platform.prefix=Idea -Dsplash=true --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.ref=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.nio.charset=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.base/java.time=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/jdk.interna [...]

2023-01-10 14:02 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains(INTELLIJ_IDENTIFIER)) {
> Then we can use the idea launch command but that requires `findIdeCommand()` then to return the proper command. Does it do that?

I'm uncertain if this will work in any situation
For example, the command I get is an execution of an internal `java` installation, not a simple bash script.
So, I suppose the full command line should be executed with the filename as parameter, but as reported above, the command line is unfortunately not complete.
It seems like it is truncated at a fixed number of characters, perhaps by the native call that fills the `Info` object

2023-01-10 14:58 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains(INTELLIJ_IDENTIFIER)) {
One way would be to take the bin folder from this `-javaagent:/home/marco/local/tools/idea/2021.3/lib/idea_rt.jar=46177:/home/marco/local/tools/idea/2021.3/bin`  and check for `idea` and `idea.bat` in `/home/marco/local/tools/idea/2021.3/bin`

2023-01-10 15:08 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains(INTELLIJ_IDENTIFIER)) {
If we detect `idea.sh` we can simply call `idea.hs --line XX /path/to/MyClass.java`, as documented here

https://www.jetbrains.com/help/idea/opening-files-from-command-line.html#a8ecf027

2023-01-11 07:07 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +            if (cmdLower.contains(INTELLIJ_IDENTIFIER)) {
Maybe it might work now for you

2023-01-11 16:54 UTC, Artur- commented
Now there is at least one test for each `Eclipse, IDEA, VS Code`+ `Linux, Mac, Windows` combination. I am pretty sure there will be some edge cases though but I don't think we can find them upfront

2023-01-12 07:21 UTC, Artur- commented
Any more considerations @mcollovati ?

2023-01-12 07:45 UTC, mcollovati requested changes

2023-01-12 07:45 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +                    run(cmd, "--line", lineNumber + "", absolutePath);
This does actually not work on my environment (IDEA on Linux)
It starts a jvm, but not IDEA
```
/home/marco/local/tools/idea/2021.3/jbr/bin/java --line 12 /home/marco/tmp/my-app-v24/src/main/java/com/example/application/views/helloworld/HelloWorldView.java
```

Using `processInfo.commandLine()` may work, but only if the command is short enough not to be truncated by the native call that gets process info

2023-01-12 07:45 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +        cmd.add(command);
We should split `command` into separated tokens to avoid potential exceptions (e.g. `java.io.IOException: error=36, File name too long`)

```suggestion
        cmd.addAll(Arrays.asList(command.split("\\s")));
```

2023-01-12 07:55 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +                    run(cmd, "--line", lineNumber + "", absolutePath);
Coding is hard yo.. Maybe now that it actually uses the binary it detects?

2023-01-12 07:56 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +        cmd.add(command);
Command here should just be the binary, not all the arguments

2023-01-12 08:24 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +                .indexOf("-javaagent:");
`-javaagent` seems to be present only on the command line that run the application, not in the one that lauches the IDE

```
/home/marco/local/tools/idea/2021.3/jbr/bin/java -classpath /home/marco/local/tools/idea/2021.3/lib/util.jar:/home/marco/local/tools/idea/2021.3/lib/app.jar:/home/marco/local/tools/idea/2021.3/lib/3rd-party-rt.jar:/home/marco/local/tools/idea/2021.3/lib/platform-statistics-devkit.jar:/home/marco/local/tools/idea/2021.3/lib/jps-model.jar:/home/marco/local/tools/idea/2021.3/lib/stats.jar:/home/marco/local/tools/idea/2021.3/lib/protobuf.jar:/home/marco/local/tools/idea/2021.3/lib/external-system-rt.jar:/home/marco/local/tools/idea/2021.3/lib/forms_rt.jar:/home/marco/local/tools/idea/2021.3/lib/intellij-test-discovery.jar:/home/marco/local/tools/idea/2021.3/lib/annotations.jar:/home/marco/local/tools/idea/2021.3/lib/groovy.jar:/home/marco/local/tools/idea/2021.3/lib/3rd-party-native.jar:/home/marco/local/tools/idea/2021.3/lib/annotations-java5.jar:/home/marco/local/tools/idea/2021.3/lib/byte-buddy-agent.jar:/home/marco/local/tools/idea/2021.3/lib/error-prone-annotations.jar:/home/marco/local/tools/idea/2021.3/lib/externalProcess-rt.jar:/home/marco/local/tools/idea/2021.3/lib/idea_rt.jar:/home/marco/local/tools/idea/2021.3/lib/intellij-coverage-agent-1.0.682.jar:/home/marco/local/tools/idea/2021.3/lib/jsch-agent.jar:/home/marco/local/tools/idea/2021.3/lib/jsp-base.jar:/home/marco/local/tools/idea/2021.3/lib/junit.jar:/home/marco/local/tools/idea/2021.3/lib/junit4.jar:/home/marco/local/tools/idea/2021.3/lib/kotlin-script-runtime.jar:/home/marco/local/tools/idea/2021.3/lib/platform-duplicates-analysis.jar:/home/marco/local/tools/idea/2021.3/lib/platform-objectSerializer-annotations.jar:/home/marco/local/tools/idea/2021.3/lib/platform-structuralSearch.jar:/home/marco/local/tools/idea/2021.3/lib/rd.jar:/home/marco/local/tools/idea/2021.3/lib/tools-testsBootstrap.jar:/home/marco/local/tools/idea/2021.3/lib/util_rt.jar:/home/marco/local/tools/idea/2021.3/lib/xml-dom-impl.jar:/home/marco/local/tools/idea/2021.3/lib/xml-dom.jar:/home/marco/local/tools/idea/2021.3/lib/ant/lib/ant.jar -Xms128m -Xmx750m -XX:ReservedCodeCacheSize=512m -XX:+UseG1GC -XX:SoftRefLRUPolicyMSPerMB=50 -XX:CICompilerCount=2 -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -XX:+IgnoreUnrecognizedVMOptions -XX:CompileCommand=exclude,com/intellij/openapi/vfs/impl/FilePartNodeRoot,trieDescend -ea -Dsun.io.useCanonCaches=false -Dsun.java2d.metal=true -Djbr.catch.SIGABRT=true -Djdk.http.auth.tunneling.disabledSchemes="" -Djdk.attach.allowAttachSelf=true -Djdk.module.illegalAccess.silent=true -Dkotlinx.coroutines.debug=off -Dsun.tools.attach.tmp.only=true -Xmx1985m -XX:ErrorFile=/home/marco/java_error_in_idea_%p.log -XX:HeapDumpPath=/home/marco/java_error_in_idea_.hprof -Djb.vmOptionsFile=/home/marco/.config/JetBrains/IdeaIC2022.3/idea64.vmoptions -Djava.system.class.loader=com.intellij.util.lang.PathClassLoader -Didea.vendor.name=JetBrains -Didea.paths.selector=IdeaIC2022.3 -Djna.boot.library.path=/home/marco/local/tools/idea/2021.3/lib/jna/amd64 -Dpty4j.preferred.native.folder=/home/marco/local/tools/idea/2021.3/lib/pty4j -Djna.nosys=true -Djna.nounpack=true -Didea.platform.prefix=Idea -Dsplash=true --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.ref=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.nio.charset=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.base/java.time=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/jdk.internal.vm=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.fs=ALL-UNNAMED --add-opens=java.base/sun.security.ssl=ALL-UNNAMED --add-opens=java.base/sun.security.util=ALL-UNNAMED --add-opens=java.desktop/com.sun.java.swing.plaf.gtk=ALL-UNNAMED --add-opens=java.desktop/java.awt=ALL-UNNAMED --add-opens=java.desktop/java.awt.dnd.peer=ALL
```

What about checking for `-Didea.vendor.name`?

2023-01-12 08:26 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +                .indexOf("-javaagent:");
Yes but that should not matter if we can get the idea location from the bin part of javaagent. Does it still not work?

2023-01-12 08:27 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +                .indexOf("-javaagent:");
What about checking for `lib/idea_rt.jar` and then search the idea script in `../bin`?

2023-01-12 08:30 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +                .indexOf("-javaagent:");
> Yes but that should not matter if we can get the idea location from the last part of the javaagent parameter. Does it still not work?

On the inspected command line, `javaagent` is not present at all

2023-01-12 08:35 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +                .indexOf("-javaagent:");
Are you saying there is something wrong with the `ideaOnLinuxDetected` test then because that one should be based exactly on your environment...

2023-01-12 08:36 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +                .indexOf("-javaagent:");
Yes that test seems to include javaagent for the wrong process

2023-01-12 08:50 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +                .indexOf("-javaagent:");
Fixed the test and the code so that is passes

2023-01-12 09:04 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +                .indexOf("-javaagent:");
Unfortunately, still does not work when running in debug mode. Here is the command line.
Seems like in this case `javaagent` does not have a reference to the bin folder

```
/home/marco/.sdkman/candidates/java/17/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:59773,suspend=y,server=n -javaagent:/home/marco/local/tools/idea/2021.3/plugins/java/lib/rt/debugger-agent.jar=file:/tmp/capture.props -Dfile.encoding=UTF-8 ....
```

2023-01-12 09:14 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +                .indexOf("-javaagent:");
Another corner case is if other java agents are using while running the application
```
/home/marco/.sdkman/candidates/java/17/bin/java -javaagent:/home/marco/.sdkman/candidates/java/11.0.15-trava/lib/hotswap/hotswap-agent.jar=autoHotswap=true -javaagent:/home/marco/local/tools/idea/2021.3/lib/idea_rt.jar=34585:/home/marco/local/tools/idea/2021.3/bin ....
```

We should maybe find the exact entry for `idea_rt.jar`

2023-01-12 10:19 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +                .indexOf("-javaagent:");
Can you post the whole process tree when running in debug mode so I can add another test?

2023-01-12 10:27 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +                .indexOf("-javaagent:");
```
/home/marco/.sdkman/candidates/java/17/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:46225,suspend=y,server=n -javaagent:/home/marco/local/tools/idea/2021.3/plugins/java/lib/rt/debugger-agent.jar -Dfile.encoding=UTF-8 -classpath /home/marco/projects/vaadin/misc/processtree/target/classes:/home/marco/.m2/repository/com/vaadin/open/8.4.0.3/open-8.4.0.3.jar:/home/marco/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar:/home/marco/local/tools/idea/2021.3/lib/idea_rt.jar com.example.application.Application
Connected to the target VM, address: '127.0.0.1:46225', transport: 'socket'
isMac? false
isLinux? true
isWindows? false
isWsl? false
Process tree:
String cmd = "/home/marco/.sdkman/candidates/java/17.0.5-tem/bin/java";
String[] args = new String[]{
"-agentlib:jdwp=transport=dt_socket,address=127.0.0.1:46225,suspend=y,server=n",
"-javaagent:/home/marco/local/tools/idea/2021.3/plugins/java/lib/rt/debugger-agent.jar",
"-Dfile.encoding=UTF-8",
"-classpath",
"/home/marco/projects/vaadin/misc/processtree/target/classes:/home/marco/.m2/repository/com/vaadin/open/8.4.0.3/open-8.4.0.3.jar:/home/marco/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar:/home/marco/local/tools/idea/2021.3/lib/idea_rt.jar",
"com.example.application.Application",
};
Command line: /home/marco/.sdkman/candidates/java/17.0.5-tem/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:46225,suspend=y,server=n -javaagent:/home/marco/local/tools/idea/2021.3/plugins/java/lib/rt/debugger-agent.jar -Dfile.encoding=UTF-8 -classpath /home/marco/projects/vaadin/misc/processtree/target/classes:/home/marco/.m2/repository/com/vaadin/open/8.4.0.3/open-8.4.0.3.jar:/home/marco/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar:/home/marco/local/tools/idea/2021.3/lib/idea_rt.jar com.example.application.Application

String cmd = "/home/marco/local/tools/idea/2021.3/jbr/bin/java";

String cmd = "/usr/lib/systemd/systemd";
String[] args = new String[]{
"--user",
};
Command line: /usr/lib/systemd/systemd --user

String[] args = new String[]{
};
Command line: /sbin/init 
```

2023-01-12 10:27 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +                .indexOf("-javaagent:");
Do you need also the one with an additional agent?

2023-01-12 10:43 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +                .indexOf("-javaagent:");
Added two more tests... this is becoming a bit hacky

2023-01-12 10:44 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +                .indexOf("-javaagent:");
Always looking for `idea_rt.jar` could be a bit more stable

2023-01-12 10:55 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +                .indexOf("-javaagent:");
I would go for `idea_rt.jar`
For example running on another project with no evident differences in `Run configuration` I get this for the javaagent param

`-javaagent:/home/marco/local/tools/idea/2021.3/plugins/java/lib/rt/debugger-agent.jar=file:/tmp/capture.props`

and the detection fails because of the `file:/tmp/...` part

2023-01-12 11:00 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +                .indexOf("-javaagent:");
Changed once again. Does it work now? :)

2023-01-12 11:22 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +                .indexOf("-javaagent:");
Can confirm it now works on my laptop! :partying_face:

2023-01-12 11:23 UTC, mcollovati approved these changes

2023-01-12 11:27 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +                .indexOf("-javaagent:");
OMG. I am sure you will figure out how to break it tomorrow though

2023-01-12 11:35 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
> +                .indexOf("-javaagent:");
I can perhaps try to install Eclipse... :laughing:

2023-01-12 11:48 UTC, merged