feat: support for index.tsx
vaadin/flow pull request #15621
Opened 2023-01-03 10:12 UTC by MarcinVaadin

See #15529 for details

2023-01-03 11:40 UTC, Artur- submitted a review, later dismissed

2023-01-03 13:44 UTC, cromoteca requested changes
As @MarcinVaadin pointed out in the issue, `TaskGenerateIndexTs` should also probably be taken into account.

2023-01-03 14:12 UTC, MarcinVaadin commented
What is the purpose of
```
private void compareActualIndexTsOrJsWithIndexTempalate(File indexTs,
            File indexJs) {
        if (indexTs.exists() || indexJs.exists()) {
            File indexFileExist = indexTs.exists() ? indexTs : indexJs;
            String indexContent = null;
            String indexTemplate = null;
            try {
                indexContent = IOUtils.toString(indexFileExist.toURI(), UTF_8);
                indexTemplate = getFileContent();
            } catch (IOException e) {
                log().warn("Failed to read file content", e);
            }
            if (indexContent != null && !indexContent.equals(indexTemplate)) {
                UsageStatistics.markAsUsed(Constants.STATISTIC_ROUTING_CLIENT,
                        Version.getFullVersion());
            }
        }
    }
```
it was supposed to compare file with some template but on failure it just reports some statistic?

2023-01-03 14:16 UTC, Artur- commented
It detects that a custom index.ts is used and marks this in the stats as "client side routing"

2023-01-03 14:18 UTC, cromoteca commented
> What is the purpose of `TaskGenerateIndexTs.compareActualIndexTsOrJsWithIndexTempalate` ?

You can also fix the typo in the method name in the process :)

2023-01-03 14:18 UTC, MarcinVaadin commented
Ok... and what's the point of those stats? Or should .tsx be also compared with that template?

2023-01-03 14:19 UTC, Artur- commented
To know if client routing is used.. :)

2023-01-03 14:20 UTC, Artur- commented
It allows distinguishing between Flow and Hilla usage. I think. Kind of. I don't think it is relevants for tsx/jsx

2023-01-03 14:25 UTC, Artur- commented
> As @MarcinVaadin pointed out in the issue, TaskGenerateIndexTs should also probably be taken into account.

That only generates the default index.ts if no index.js or index.ts exists. Nothing to do with this I think

2023-01-03 14:27 UTC, MarcinVaadin commented
> > As @MarcinVaadin pointed out in the issue, TaskGenerateIndexTs should also probably be taken into account.
> 
> That only generates the default index.ts if no index.js or index.ts exists. Nothing to do with this I think

But if .tsx only exists .ts will be autogenerated I guess. So maybe I will just add checking if .tsx also does not exist?

2023-01-03 14:29 UTC, Artur- commented
Right. It should not do anything if one of index.js/index.ts/index.tsx exist

2023-01-03 14:42 UTC, cromoteca commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTs.java
>          if (indexTs.exists() || indexJs.exists()) {
If `index.tsx` is used, it will not be detected in stats. Is that the intended behavior?

2023-01-03 14:45 UTC, MarcinVaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTs.java
>          if (indexTs.exists() || indexJs.exists()) {
Probably not, but if there is no "template" should I treat any .tsx as custom?

2023-01-03 16:06 UTC, cromoteca approved these changes

2023-01-04 06:30 UTC, MarcinVaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTs.java
> +                .map(type -> new File(frontendDirectory, type))
@sonatype-lift ignore

2023-01-04 06:34 UTC, merged