test: Test devBuild with add-ons
vaadin/flow pull request #15660
Opened 2023-01-10 12:03 UTC by caalador

Test that a pure server add-on
doesn't require a devBundle, but
an add-on with frontend files does.

Closes #15656

2023-01-11 08:41 UTC, caalador commented on flow-tests/test-express-build/frontend-add-on/src/main/java/com/vaadin/flow/todo/TodoCreator.java
> +    private void createTodo(String task, String user) {
Not relevant as ClientCallable method.

2023-01-11 08:42 UTC, caalador commented on flow-tests/test-express-build/frontend-add-on/src/main/java/com/vaadin/flow/todo/TodoCreator.java
> +    private Random rand = new Random(System.currentTimeMillis());
Not relevant. Used for in-memory item id.

2023-01-11 08:43 UTC, caalador commented on flow-tests/test-express-build/frontend-add-on/src/main/resources/META-INF/resources/frontend/TodoElement.js
> +        this.user = "";
Not a username, just a creator name,

2023-01-11 08:43 UTC, caalador commented on flow-tests/test-express-build/frontend-add-on/src/main/resources/META-INF/resources/frontend/TodoCreator.js
> +        this.user = "";
Not a user name, just a task creator name

2023-01-11 13:31 UTC, mshabarov requested changes

2023-01-11 13:31 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +                            + options.isEnableDevServer() + " devBundle "
```suggestion
                            + options.isEnableDevServer() + " devBundle: "
```

2023-01-11 13:31 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
> +    private boolean enableDevServer = false;
Wouldn't this give a regression when some of the frontend build task will not start the dev server by default?

2023-01-11 13:31 UTC, mshabarov commented on flow-tests/test-express-build/frontend-add-on/src/main/assembly/MANIFEST.MF
> +Implementation-Version: ${project.version}
```suggestion
Implementation-Version: ${project.version}

```

2023-01-11 13:31 UTC, mshabarov commented on flow-tests/test-express-build/frontend-add-on/src/main/java/com/vaadin/flow/todo/Todo.java
> +}
```suggestion
}

```

2023-01-11 13:31 UTC, mshabarov commented on flow-tests/test-express-build/frontend-add-on/src/main/java/com/vaadin/flow/todo/TodoCreator.java
> +}
```suggestion
}

```

2023-01-11 13:31 UTC, mshabarov commented on flow-tests/test-express-build/frontend-add-on/src/main/java/com/vaadin/flow/todo/TodoElement.java
> +}
```suggestion
}

```

2023-01-11 13:31 UTC, mshabarov commented on flow-tests/test-express-build/java-add-on/src/main/assembly/MANIFEST.MF
> +Implementation-Version: ${project.version}
```suggestion
Implementation-Version: ${project.version}

```

2023-01-11 13:31 UTC, mshabarov commented on flow-tests/test-express-build/java-add-on/src/main/java/com/vaadin/flow/select/SelectElement.java
> +}
```suggestion
}

```

2023-01-11 13:31 UTC, mshabarov commented on flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/TodoIT.java
> +        // shouldn't create a dev-bundle
```suggestion
        // should create a dev-bundle
```

2023-01-11 13:31 UTC, mshabarov commented on flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/TodoIT.java
> +                new File(baseDir, "tsconfig.json").exists());
Is it a copy-paste mistake? I expected that it's fine if these files are created when the dev-bundle is recompiled?

2023-01-11 13:31 UTC, mshabarov commented on flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/TodoIT.java
> +        TestBenchElement template = $(TestBenchElement.class).id("template");
General comment: since we are testing only the express build dev bundle here, maybe we can simplify the frontend add-on a bit to have a less functionality and less codes? Like just a list with a couple of tasks.

2023-01-11 13:31 UTC, mshabarov commented on flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/TodoIT.java
> +    public void noFrontendFilesCreated() {
```suggestion
    public void frontendFilesCreated() {
```

2023-01-11 13:31 UTC, mshabarov commented on flow-tests/test-express-build/test-dev-bundle-java-add-on/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/AddOnIT.java
> +        // These should not be generated either, but at the moment they are
False comment

2023-01-12 04:50 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +                            + options.isEnableDevServer() + " devBundle "
Debug log that should not be. Removed.

2023-01-12 04:50 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
> +    private boolean enableDevServer = false;
It shouldn't. DevModeHandler always sets this in `DevModeHandler::initDevModeHandler`
`prepare-frontend` goal doesn't run the dev server (which is why this is changed to false) and `build-frontend` doesn't run a dev server either as it builds a production bundle.

2023-01-12 04:50 UTC, caalador commented on flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/TodoIT.java
> +                new File(baseDir, "tsconfig.json").exists());
They should be created. the comment is wrong. Removed

2023-01-12 04:50 UTC, caalador commented on flow-tests/test-express-build/test-dev-bundle-java-add-on/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/AddOnIT.java
> +        // These should not be generated either, but at the moment they are
removed

2023-01-12 05:38 UTC, caalador commented on flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/TodoIT.java
> +        TestBenchElement template = $(TestBenchElement.class).id("template");
Well it doesn't need to be functional, but it is nicer to test manually when it is.

2023-01-12 07:24 UTC, mshabarov approved these changes

2023-01-12 07:52 UTC, merged