fix: Use the servlet host and port for the Vite websocket connection
vaadin/flow pull request #15689
Opened 2023-01-15 17:51 UTC by Artur-

This proxies the Vite websocket connection the same way we proxy http requests

2023-01-15 17:58 UTC, Artur- commented
The checker plugin still connects to the wrong URL because it has its own websocket logic. When https://github.com/fi3ework/vite-plugin-checker/issues/200 is fixed it should also work correctly

2023-01-16 14:25 UTC, Artur- commented
Upgrading the plugin to latest fixed the ws url issue

2023-01-16 15:49 UTC, mcollovati requested changes

2023-01-16 15:49 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java
> + * Copyright 2000-2022 Vaadin Ltd.
```suggestion
 * Copyright 2000-2023 Vaadin Ltd.
```

2023-01-16 15:49 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketEndpoint.java
> + * Copyright 2000-2022 Vaadin Ltd.
```suggestion
 * Copyright 2000-2023 Vaadin Ltd.
```

2023-01-16 15:49 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketProxy.java
> + * Copyright 2000-2022 Vaadin Ltd.
```suggestion
 * Copyright 2000-2023 Vaadin Ltd.
```

2023-01-16 15:49 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketEndpointInitializer.java
> +        implements ServletContextListener {
It looks like that the only usage of this class is in `ViteHandler` and it is instantiated manually.
What is the purpose of making it implement `ServletContextListener`?
Is it meant for manual registrations in `ServeltContext`?

2023-01-16 15:49 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketEndpoint.java
> +            getLogger().debug("Error creating Vite proxy connection", e);
Should we log at `error` level to make it more evident why it is not working as expected?

2023-01-16 15:49 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java
> +                + clientWebSocket.getSubprotocol() + " protocol");
nit:
```suggestion
        getLogger().debug("Connecting to {} using the {} protocol", uri,
                clientWebSocket.getSubprotocol());
```

2023-01-16 15:49 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java
> +        getLogger().debug("Message from Vite: " + msg);
nit:
```suggestion
        getLogger().debug("Message from Vite: {}", msg);
````

2023-01-16 15:49 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java
> +    private Consumer<String> onMessage;
nit: can be final
```suggestion
    private final Consumer<String> onMessage;
```

2023-01-16 15:49 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketProxy.java
> +            CompletableFuture<WebSocket> send = clientWebSocket.get()
Where is `clientWebSocket` supposed to be initialized?
When I get a `ping` message, this listener always throws a NPE

2023-01-16 16:15 UTC, mcollovati commented
I did a try with the plain java flow starter and got this error when loading the web page

```
Caused by: java.lang.RuntimeException: Cannot load platform configurator
	at jakarta.websocket.server.ServerEndpointConfig$Configurator.fetchContainerDefaultConfigurator(ServerEndpointConfig.java:96)
	at jakarta.websocket.server.DefaultServerEndpointConfig.<init>(DefaultServerEndpointConfig.java:57)
	at jakarta.websocket.server.ServerEndpointConfig$Builder.build(ServerEndpointConfig.java:262)
	at com.vaadin.base.devserver.viteproxy.ViteWebsocketEndpointInitializer.<init>(ViteWebsocketEndpointInitializer.java:64)
	at com.vaadin.base.devserver.ViteHandler.doStartDevModeServer(ViteHandler.java:179)
	at com.vaadin.base.devserver.AbstractDevServerRunner.runOnFutureComplete(AbstractDevServerRunner.java:171)
	at com.vaadin.base.devserver.AbstractDevServerRunner.lambda$new$0(AbstractDevServerRunner.java:162)
```

2023-01-17 08:10 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java
> + * Copyright 2000-2022 Vaadin Ltd.
Shouldn't we use the same header in all files?

2023-01-17 08:10 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketEndpoint.java
> +            getLogger().debug("Error creating Vite proxy connection", e);
Let's do that and revert if it turns out that it logs a lot of intermittent failures during restarts or similar

2023-01-17 08:10 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketEndpointInitializer.java
> +        implements ServletContextListener {
It is from an earlier version and no longer needed. Removed.

2023-01-17 08:10 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketProxy.java
> +            CompletableFuture<WebSocket> send = clientWebSocket.get()
Uh, looks like it was deleted during some refactoring..

2023-01-17 09:36 UTC, Artur- commented
> I did a try with the plain java flow starter and got this error when loading the web page
>
> Caused by: java.lang.RuntimeException: Cannot load platform configurator

It seems like `jetty:run` has a problem with finding its own server configurator (https://github.com/eclipse/jetty.project/issues/9180). Added a custom one as a workaround

2023-01-17 09:52 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java
> + * Copyright 2000-2022 Vaadin Ltd.
You're right. I thought the headers were already up to date, but they aren't up to date yet

2023-01-17 10:18 UTC, mcollovati requested changes
I'm testing the latest changes on plain Java starter, and it seems that after a while from the first connection (~30 secs) the websocket channels are closed.

For example, if after 30 secs I try to type something wrong in a typescript source I get this error

```
[HttpClient-2-Worker-3] DEBUG com.vaadin.base.devserver.viteproxy.ViteWebsocketProxy - Error sending message to browser
java.io.IOException: java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.util.FutureCallback.block(FutureCallback.java:163)
	at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketBasicRemote.sendText(JakartaWebSocketBasicRemote.java:121)
	at com.vaadin.base.devserver.viteproxy.ViteWebsocketProxy.lambda$new$0(ViteWebsocketProxy.java:56)
	at com.vaadin.base.devserver.viteproxy.ViteWebsocketConnection.onText(ViteWebsocketConnection.java:82)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask.processText(WebSocketImpl.java:635)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask.run(WebSocketImpl.java:443)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.websocket.core.internal.WebSocketSessionState.onOutgoingFrame(WebSocketSessionState.java:184)
	at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.sendFrame(WebSocketCoreSession.java:514)
	at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketRemoteEndpoint.sendFrame(JakartaWebSocketRemoteEndpoint.java:141)
	at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketBasicRemote.sendText(JakartaWebSocketBasicRemote.java:120)
	... 9 more
````

2023-01-17 10:18 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java
> +    private WebSocket clientWebSocket;
nit: can be final

2023-01-17 10:27 UTC, mcollovati commented
Works fine with Spring.

However, an error is logged when reloading the page

```
2023-01-17T11:26:34.198+01:00 DEBUG 65602 --- [ient-9-Worker-2] c.v.b.d.viteproxy.ViteWebsocketProxy     : Error sending message to browser

java.lang.IllegalStateException: The WebSocket session [f] has been closed and no method (apart from close()) may be called on a closed session
	at org.apache.tomcat.websocket.WsSession.checkState(WsSession.java:989) ~[tomcat-embed-websocket-10.1.1.jar:10.1.1]
	at org.apache.tomcat.websocket.WsSession.getBasicRemote(WsSession.java:546) ~[tomcat-embed-websocket-10.1.1.jar:10.1.1]
	at com.vaadin.base.devserver.viteproxy.ViteWebsocketProxy.lambda$new$0(ViteWebsocketProxy.java:56) ~[vaadin-dev-server-24.0-SNAPSHOT.jar:na]
	at com.vaadin.base.devserver.viteproxy.ViteWebsocketConnection.onText(ViteWebsocketConnection.java:82) ~[vaadin-dev-server-24.0-SNAPSHOT.jar:na]
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask.processText(WebSocketImpl.java:635) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask.run(WebSocketImpl.java:443) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230) ~[java.net.http:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

2023-01-17 10:36 UTC, Artur- commented
The default idle timeout seems to be 30s and Vite was pinging with a 30s interval so likely it had time to close before the ping arrived. I increased it to 60s but it seems that reopening of connections still need to be handled somehow as the same situation will probably occur if you close your laptop for more than a minute now

2023-01-17 10:45 UTC, Artur- commented
Ah there is the separate vite checker plugin connection which does not send any pings..

2023-01-17 10:47 UTC, mcollovati commented
> Ah there is the separate vite checker plugin connection which does not send any pings..

Yes, can confirm that the websockets connection opend by the vite checker plugin gets still closed after the max idle timeout

2023-01-17 13:21 UTC, Artur- commented
Refactored so endpoint initialization takes place in the servlet context listener and not in a separate thread, which was what was causing the Jetty issues. Now also closes the other connection if one of them is closed

2023-01-17 14:29 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java
> +    private Runnable onClose;
nit: can be final

2023-01-17 14:34 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java
> +    private Runnable onClose;
You are starting to sound like a static code analyzer

2023-01-17 16:52 UTC, mcollovati commented
I have not found the cause, but it seems Vite ws proxying does not work when setting a `context-path` (e.g. `server.servlet.context-path=/ui`)
I have tested this only on spring-based project right now

2023-01-17 19:31 UTC, Artur- commented
Yes the context path should not be included in the endpoint mapping but it must be included in the Vite base path, as Vite has no idea about any context path. Fixed and now it should work both with context and/or servlet path mappings

2023-01-18 08:19 UTC, mcollovati commented
Tested again with context path and url mapping and it works fine.
I also did a test with an HTTPS reverse proxy in front of the application, and it works, except for the `vaadin-dev-tools` connection that connects directly to Vite port.

@Artur- Do you think we can proxy also this connection through Vaadin Flow?

2023-01-18 08:22 UTC, Artur- commented
Which vaadin-dev-tools connection would that be? Right now there should be:
1. vaadin-dev-tools connects to `ws://localhost:8080/VAADIN/push?v-r=push&debug_window`
2. If you use push, it connects to `ws://localhost:8080/VAADIN/push?v-r=push`
3. Vite connects to `ws://localhost:8080/VAADIN` with this PR
4. The checker plugin in Vite connects to the same URL
5. Live reload connects to ws://localhost:35729/

2023-01-18 08:23 UTC, mcollovati commented
My mistake, the failing connection is not to Vite, but to Spring Boot livereload port

2023-01-18 08:23 UTC, Artur- commented
For live reload there is #13646 which would use the dev tools ws instead of a separate connection and additionally work if you have multiple apps running

2023-01-18 08:24 UTC, mcollovati approved these changes

2023-01-18 08:25 UTC, merged

2023-01-18 08:40 UTC, mcollovati commented
Just for the record, the checker plugin disconnects after 60 seconds, but it seems not to be a problem because if there are changes to typescript files, the page is reloaded because of the other Vite WS connection and all connections are established again

2023-01-18 09:00 UTC, Artur- commented
I think the checker plugin related issues will be solved once https://github.com/fi3ework/vite-plugin-checker/issues/200 is implemented