feat: validate frontend file hash
vaadin/flow pull request #15682
Opened 2023-01-13 12:34 UTC by caalador

When having jar-resources validate contents
through hash.

Closes #15668

2023-01-17 15:14 UTC, mshabarov requested changes

2023-01-18 05:39 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +            getLogger().info("No dev-bundle stats.json found for validation.");
This will just make a new dev bundle so there is nothing to recommend as it is just info on why we are generating a new devBundle.

2023-01-18 05:39 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +            getLogger().info("No dev-bundle found.");
As it is just an indication on why a new dev-bundle is made it only matters that we tell that it is made due to no dev-bundle available.

2023-01-18 05:39 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +            getLogger().info("Faulty content for files: ", faultyContent);
Updated and formatted better.

2023-01-18 05:39 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +                getLogger().info("No has info for '{}'", jarImport);
fixed

2023-01-18 08:02 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +            getLogger().info("No dev-bundle found.");
It can be so that the developer forgets to add `vaadin-dev-bundle` dependency, and we can let him know about that at that point.

2023-01-18 08:03 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +            getLogger().info("No dev-bundle found.");
But let's see how DX tests go :)

2023-01-18 08:03 UTC, mshabarov approved these changes

2023-01-18 08:05 UTC, merged

2023-01-18 08:06 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +            getLogger().info("No dev-bundle found.");
They can, but then they have actively added express mode into the flags file. which is not needed if you add the vaadin-dev-bundle dependency