Added a commonly needed helper method to get current route target
vaadin/flow pull request #15709
Opened 2023-01-17 17:32 UTC by mstahv

## Description

In layouts and menus it is a common need to detect the active view/route/navigationtarget/whatever-we-call-it. Currently we offer no good ways how to get that. The basically undocumented and cumbersome getActiveChain() method in AfterNavigationEvent is the closest available method.

Fixes #4565

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2023-01-19 17:27 UTC, mstahv commented
Note for @vaadin/flow team: if you are ok with it, I (and @knoobie) would like to drop the Optional usage still 🤓

This method is not randomly returning null, only in certain known states (when not attached to the dom and when not using routing) and developer should be able to know those cases.

2023-01-19 17:46 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/component/UI.java
> +            return Optional.empty();
We could even throw a meaningful exception if the route is null / log a meaningful message for the developer why the route could be null - with the normal culprits: used before attached and other variants we've seen by developer, making it easier for them to understand the problem and fix it

2023-01-19 22:19 UTC, MarcinVaadin commented
All other similar helper methods are within `UIInternals`, IMO same should be in that case. As for the idea itself - LGTM.

2023-01-19 22:20 UTC, MarcinVaadin requested changes
All other similar helper methods are within UIInternals, IMO same should be in that case. As for the idea itself - LGTM.

2023-01-20 06:37 UTC, mstahv commented
That UIInternals is not the place to add API for framework users. Both the naming and API docs say that quite clearly:

_Holds UI-specific methods and data which are intended for internal use by the framework.
For internal use only. May be renamed or removed in a future release._

2023-01-20 06:41 UTC, mcollovati reviewed
Since `getCurrentView()` is a public API, it would be good to have dedicated tests for it

2023-01-20 06:41 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/UI.java
> +        } catch (Exception e) {
What exceptions may be raised by this code?
If it is only to catch `IndexOutOfBoundsException`, I would prefer a check on `List.isEmpty()`.

2023-01-20 06:43 UTC, mstahv commented on flow-server/src/main/java/com/vaadin/flow/component/UI.java
> +        } catch (Exception e) {
NPE (router can be null for example with embedded web components, didn't check, but read it from some javadocs).

2023-01-20 06:48 UTC, mstahv commented on flow-server/src/main/java/com/vaadin/flow/component/UI.java
> +        } catch (Exception e) {
Actually, it doesn't seem to go to Router at all, but only ArrayList<HasElement> routerTargetChain that is always initialized. So there shouldn't be NPEs.

2023-01-20 06:53 UTC, mstahv commented on flow-server/src/main/java/com/vaadin/flow/component/UI.java
> +        } catch (Exception e) {
So this should do it as well, but somebody could comment on the communitys (or at least mine and knoobies) wish about returning component directly, instead of Optional.

       if(getInternals().getActiveRouterTargetsChain().isEmpty()) {
            return Optional.empty();
        }
        return Optional.of((Component) getInternals()
                    .getActiveRouterTargetsChain().get(0));

2023-01-20 07:17 UTC, mcollovati commented
> Note for @vaadin/flow team: if you are ok with it, I (and @knoobie) would like to drop the Optional usage still nerd_face
> 
> This method is not randomly returning null, only in certain known states (when not attached to the dom and when not using routing) and developer should be able to know those cases.

I'm fine with dropping the Optional, but I would throw an `IllegalStateException` if the routerTargetChain is empty, to make it clear that the method is invoked from a wrong path

2023-01-20 07:51 UTC, mstahv commented
Pushed a version without Optional 👍

2023-01-26 10:18 UTC, mcollovati requested changes

2023-01-26 10:18 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/UI.java
> +     * those an empty optional is returned.
Javadoc needs to be updated, as now we throw an exception instead of return an Optional

2023-01-26 11:07 UTC, mcollovati approved these changes

2023-01-26 11:07 UTC, merged