fix: Allow Gradle builds to use custom sourcesets
vaadin/flow pull request #15739
Opened 2023-01-21 19:50 UTC by mc1arke

## Description

When a sourceset other than `main` is used for holding classes using Vaadin components, or for providing a resolution scope for Vaadin dependencies, the `prepareVaadinFrontend` task does not correctly extract the correct Node libraries required by those classes, and the `buildVaadinFrontend` task subsequently fails to complete due to Vite requiring those Node dependencies to have been extracted into the project so failing to find all of its front-end dependencies.

The `VaadinFlowPluginExtension` is being altered to include a `sourceSetName` field, that defaults to `main` for backwards compatibility but allows users to specify a custom sourceset to use for the prepare and build tasks. As the use of a custom sourceset generally implies that different Gradle tasks will be executed for operating on those sourcesets, and a different dependency scope generated for the custom sourceset, fields have also been added to the extension that allow users to override the values the plugin uses, whilst the default values follow the Gradle conventions for both `main` and non-`main` sourcesets.

Fixes #15738

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

2023-01-21 19:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=15739) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=15739) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=15739) it.</sub>

2023-01-21 19:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=15739) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=15739) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=15739) it.</sub>

2023-01-23 17:49 UTC, mcollovati requested changes

2023-01-23 17:49 UTC, mcollovati commented on flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
> +                maven { url 'https://repo.spring.io/milestone' }
Is this repo really needed? Validation build is failing because of certificate verification.

2023-01-23 18:36 UTC, mc1arke commented on flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
> +                maven { url 'https://repo.spring.io/milestone' }
Removed. The Spring plugins are in Maven Central so a direct mirror isn't required.

2023-01-23 20:03 UTC, mcollovati requested changes

2023-01-23 20:03 UTC, mcollovati commented on flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
> +                uiImplementation('com.vaadin:vaadin-spring-boot-starter')
This dependency needs the platform BOM, and we should not use it. 
Do we really need it for the test?
Can't we use an artifact produced by current build (e.g `com.vaadin:flow:$flowVersion`)

2023-01-24 07:22 UTC, mcollovati approved these changes
LGTM
As a follow-up, we need to update [documentation](https://vaadin.com/docs/latest/guide/start/gradle/#all-options) adding the configuration properties added by this change

2023-01-25 12:32 UTC, merged