feat: Use Vite dev server for Hilla projects by default
vaadin/flow pull request #15768
Opened 2023-01-27 13:17 UTC by mshabarov

2023-01-27 13:44 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
> +        boolean hillaIsUsed;
```suggestion
        boolean defaultFrontendHotdeploy;
```

2023-01-27 14:43 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/shared/util/SharedUtil.java
> +
Definitely the wrong class for this

2023-01-27 18:06 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/shared/util/SharedUtil.java
> +
Found nothing better than `EndpointRequestUtil`, not maybe a good choice either.

2023-01-30 10:01 UTC, mshabarov commented
Tested with a starter project having Flow + Hilla, triggers hotdeploy mode by default as expected. Removing all related to Hilla triggers the express build mode by default as expected.

2023-01-30 14:10 UTC, Artur- requested changes

2023-01-30 14:10 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/internal/hilla/EndpointRequestUtil.java
> +     * Shows whether the Hilla is used in the project.
```suggestion
     * Checks if Hilla is available.
```

2023-01-30 14:10 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/internal/hilla/EndpointRequestUtil.java
> +    static boolean isEndpointUsed() {
```suggestion
    static boolean isHillaAvailable() {
```

2023-01-30 14:10 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/internal/hilla/EndpointRequestUtil.java
> +     * @return true if Hilla is used, false otherwise
```suggestion
     * @return true if Hilla is available, false otherwise
```

2023-01-30 14:10 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/internal/hilla/EndpointRequestUtil.java
> +            // This class belongs to fusion-endpoint and is not available in
```suggestion
```

2023-01-30 14:10 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/internal/hilla/EndpointRequestUtil.java
> +            // Flow projects. By checking for its availability, we can show the
```suggestion
```

2023-01-30 14:10 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/internal/hilla/EndpointRequestUtil.java
> +            // right project name in the Vaadin devmode gizmo
```suggestion
```

2023-01-30 14:10 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/internal/hilla/EndpointRequestUtil.java
> +            Class.forName("dev.hilla.EndpointController", false,
Is there any need for more than `Class.forName("dev.hilla.EndpointController")` if you moved it to the `flow-server` package?

2023-01-30 14:10 UTC, Artur- commented
Tested that it works correctly with start.vaadin.com

2023-01-30 15:46 UTC, cromoteca commented
@platosha @Lodin I propose to define a class in Hilla that is officially a marker of Hilla being used. Here `dev.hilla.EndpointController` is used at the moment.

2023-01-30 18:22 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/internal/hilla/EndpointRequestUtil.java
> +            Class.forName("dev.hilla.EndpointController", false,
Probably not, changed.

2023-01-31 07:21 UTC, caalador approved these changes

2023-01-31 07:28 UTC, Artur- approved these changes

2023-01-31 07:29 UTC, merged