fix: Make Flow compatible with ASM framework
vaadin/flow pull request #15770
Opened 2023-01-30 08:58 UTC by mshabarov

Solution for https://github.com/vaadin/flow/issues/15625, until https://github.com/payara/Payara/issues/6127 is fixed.

Thanks @knoobie for inspiration!

2023-01-30 09:05 UTC, MarcinVaadin submitted a review, later dismissed

2023-01-30 09:16 UTC, MarcinVaadin commented
Why not to simplify `SortDirection` to:

```
public enum SortDirection {

    /**
     * Ascending (e.g. A-Z, 1..9) sort order
     */
    ASCENDING,

    /**
     * Descending (e.g. Z-A, 9..1) sort order
     */
    DESCENDING;

    /**
     * Get the sort direction that is the direct opposite to this one.
     *
     * @return a sort direction value
     */
    public SortDirection getOpposite() {
        return ASCENDING.equals(this) ? DESCENDING : ASCENDING;
    }
}
```
?

2023-01-30 09:26 UTC, mcollovati requested changes

2023-01-30 09:26 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentTracker.java
> +    public static class Location implements Serializable {
As we are replacing a record, we can declare fields as final and remove setters

2023-01-30 09:26 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentTracker.java
> +    public static class Location implements Serializable {
Also, making accessors without `get`  (e.g. `className` instead of `getClassName`) may simplify a future migration back to record

2023-01-30 09:41 UTC, Artur- commented
The summary makes no sense. Is about making it compatible with an old ASM version?

2023-01-30 09:47 UTC, mshabarov commented
> The summary makes no sense. Is about making it compatible with an old ASM version?

Yes, for older than 9. Changed the summary.

2023-01-30 10:19 UTC, mcollovati approved these changes

2023-01-30 11:45 UTC, MarcinVaadin approved these changes

2023-01-31 07:23 UTC, Artur- commented
Without a test, I give this one week before it is broken

2023-01-31 08:34 UTC, mshabarov commented
> Without a test, I give this one week before it is broken

We have a tests for CDI add-on vs Payara server validation (which will be enabled soon I hope), in my opinion only these can reliably check that Flow is fully compatible with the ASM. We could have a tests in Flow checking that there is no record classes, but IMO Flow can break by other reasons, like we seen with abstract classes in enum.

2023-01-31 09:07 UTC, merged