fix: fixed support for Spring EnableMethodSecurity (#15059)
vaadin/flow pull request #15786
Opened 2023-01-31 10:01 UTC by MarcinVaadin

Vaadin clone of https://github.com/vaadin/flow/pull/15671 plus tests

Fixes #15059

2023-01-31 10:10 UTC, MarcinVaadin commented
@aspan - I've copied your solution and added test. It works as expected, thanks for contributing 👍

2023-01-31 10:25 UTC, MarcinVaadin commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinAwareSecurityContextHolderStrategyConfiguration.java
> +        VaadinAwareSecurityContextHolderStrategy vaadinAwareSecurityContextHolderStrategy = new VaadinAwareSecurityContextHolderStrategy();
@sonatype-lift ignoreall

2023-02-03 07:25 UTC, mcollovati requested changes
Just a new line missing, other than that LGTM

2023-02-03 07:25 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinAwareSecurityContextHolderStrategyConfiguration.java
> +}
new line missing
```suggestion
}

```

2023-02-03 07:35 UTC, mcollovati approved these changes

2023-02-03 21:09 UTC, knoobie commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinAwareSecurityContextHolderStrategyConfiguration.java
> +    public SecurityContextHolderStrategy securityContextHolderStrategy() {
Should this return `VaadinAwareSecurityContextHolderStrategy` instead? 

> When declaring a @Bean method, provide as much type information as possible in the method’s return type. For example, if your bean’s concrete class implements an interface the bean method’s return type should be the concrete class and not the interface. Providing as much type information as possible in @Bean methods is particularly important when using bean conditions as their evaluation can only rely upon to type information that’s available in the method signature.

Spring Docs: https://docs.spring.io/spring-boot/docs/2.4.2/reference/html/spring-boot-features.html#boot-features-bean-conditions 

Also, should this Bean also add `@ ConditionalOnMissingBean` to make sure it's easily override able by users if needed? Without using Primary hacks

2023-02-06 07:09 UTC, MarcinVaadin commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinAwareSecurityContextHolderStrategyConfiguration.java
> +    public SecurityContextHolderStrategy securityContextHolderStrategy() {
I agree for both, thanks 👍

2023-02-06 08:03 UTC, mcollovati approved these changes

2023-02-06 08:20 UTC, merged