fix: add push servlet mapping & fix automatic push endpoint location
vaadin/flow pull request #15791
Opened 2023-01-31 12:59 UTC by tepi

## Description

Introduces a parameter to set push servlet mapping. Fixes automatic determination of said mapping if an explicit mapping is not provided.

Fixes #15565

2023-02-01 14:02 UTC, tepi commented on flow-server/src/main/java/com/vaadin/flow/internal/BootstrapHandlerHelper.java
> +        String pushURL = pushServletMapping + Constants.PUSH_MAPPING;
@sonatype-lift ignore

2023-02-01 14:03 UTC, tepi commented on flow-server/src/main/java/com/vaadin/flow/internal/BootstrapHandlerHelper.java
> +                        .getPushServletMapping());
@sonatype-lift ignore

2023-02-02 11:05 UTC, caalador requested changes

2023-02-03 06:38 UTC, tepi commented on flow-server/src/main/java/com/vaadin/flow/internal/BootstrapHandlerHelper.java
> +                vaadinSession.getConfiguration().getPushServletMapping());
@sonatype-lift ignore

2023-02-03 06:49 UTC, caalador approved these changes

2023-02-03 18:43 UTC, merged