fix: Check for changes in project frontend files
vaadin/flow pull request #15992
Opened 2023-02-22 16:50 UTC by mshabarov

Extends frontend files modification detection so that it checks also project's frontend files in `frontend/`.

Fixes https://github.com/vaadin/flow/issues/15970

2023-02-23 09:53 UTC, Artur- commented on flow-server/src/main/resources/vite.generated.ts
> +      generatedImports.filter((line: string) => line.startsWith("Frontend/")).forEach((line: string) => {
IMO this should not at all look at the generated imports file. It should look at which files were used in the compilation. Now it can only react to the files you have imported from Java and not at all to the files those files in turn import. E.g. if you have
```
import './another.ts';
```

in your index.ts, then no changes to `another.ts` will ever cause a rebuild

2023-02-23 11:47 UTC, mshabarov commented on flow-server/src/main/resources/vite.generated.ts
> +      generatedImports.filter((line: string) => line.startsWith("Frontend/")).forEach((line: string) => {
Yes, makes sense. I'm looking into it.

2023-02-24 13:35 UTC, mshabarov commented on flow-server/src/main/resources/vite.generated.ts
> +      generatedImports.filter((line: string) => line.startsWith("Frontend/")).forEach((line: string) => {
So I did it in the following way:
- Frontend compiled TS/JS files are collected from `modules` in the `statsExtracterPlugin()` and placed into `frontendHashes` during bundle build.
- Flow takes files listed in `frontendHashes` and checks the presence of the files in the `frontend` folder.
- Then it checks the hash of the file if it exists, otherwise it considered as deleted.

2023-02-27 09:06 UTC, caalador requested changes

2023-02-27 09:06 UTC, caalador commented on flow-tests/test-express-build/pom.xml
> +                <module>test-dev-bundle-frontend-resource</module>
Does this module bring enough over just junit tests to warrant the overhead of npm etc?
Also if really needed couldn't this be added to one of the existing modules that always builds a new bundle?

2023-02-27 09:34 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +                        FrontendUtils.FRONTEND_FOLDER_ALIAS.length()))
`?inline` is removed from imports before jarImports and projectImport.
What was missing is the test stylesheet file and it's hash.
Done.

2023-02-27 09:46 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +
Yes, it is not needed indeed.

2023-02-27 12:28 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +        getLogger().info(message, removedFiles);
Done

2023-02-27 12:28 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +        getLogger().info(message, removedFiles);
I've put {} into the methods, so it's added internally.
Done.

2023-02-27 12:28 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +
Done

2023-02-27 12:29 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +        expectedFrontendFiles.remove(FrontendUtils.INDEX_TSX);
Makes sense. Refactored.

2023-02-27 12:29 UTC, mshabarov commented on flow-server/src/main/resources/vite.generated.ts
> +        // \r\n from windows made files may be used ro remove to be only \n
Done.

2023-02-27 12:32 UTC, mshabarov commented on flow-tests/test-express-build/pom.xml
> +                <module>test-dev-bundle-frontend-resource</module>
I've put it into `flow-test-dev-bundle-frontend-add-on`, other test modules seem completely unrelated to the goal of this test.
This test is needed to be sure that the entries (file name and hash) for project's frontend files are generated properly in stats.json and the template is rendered (however, the template render is not a goal of this fix).

2023-02-27 12:56 UTC, caalador approved these changes

2023-02-27 13:04 UTC, merged