fix: Do not import Lumo twice for the document
vaadin/flow pull request #16243
Opened 2023-03-13 11:55 UTC by Artur-

All Lumo modules except utility are loaded and injected into <head> by https://github.com/vaadin/flow-components/blob/main/vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java We should not do that another time

2023-03-13 12:39 UTC, Artur- commented
This depends on  #16230 for the test

2023-03-13 12:57 UTC, Artur- commented
Scrap that, it does not need that test nor does it yet resolve #16231. That needs another PR

2023-03-14 08:43 UTC, mshabarov requested changes
Any test covering this patch?

2023-03-14 08:43 UTC, mshabarov commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
> +      if (lumoImport === 'utility') {
```suggestion
      // Lumo is injected to the document by Lumo itself, except for the utility module
      if (lumoImport === 'utility') {
```

2023-03-14 09:00 UTC, Artur- commented
All existing tests that use Lumo pass so they should test that Lumo still works. I would not add a test that Lumo is not loaded twice because that tests the code and not any feature. 

The real problem that should be resolved is #16231, which has a disabled test in #16241. It can be fixed more easily once the test and this PR have been merged. It is an attempt to keep PRs reasonably sized

2023-03-14 09:03 UTC, mshabarov approved these changes

2023-03-14 09:04 UTC, Artur- commented
Do we need this for 24.0? I think the theme loading changes that are needed are not in general suitable for a bugfix release

2023-03-14 09:08 UTC, mshabarov commented
> Do we need this for 24.0? I think the theme loading changes that are needed are not in general suitable for a bugfix release

Since this patch fixes what was recently added to 24.0, I assumed 24.0 deserves this fix, especially that the codebase is almost equivalent and this won't require any additional maintenance effort from us.

2023-03-14 09:41 UTC, merged