chore!: Add runtime license checking to Flow
vaadin/flow pull request #16379
Opened 2023-03-23 14:57 UTC by mshabarov

2023-03-23 15:00 UTC, mshabarov commented on flow-server/bnd.bnd
> +CvdlName: ${cvdlName}
As the license checking is only in flow-server, I'm not sure whether we need cvdl name for other modules or not.

2023-03-28 16:12 UTC, mshabarov commented on flow-server/pom.xml
> +                            <CvdlName>${cvdlName}</CvdlName>
Same for CVDL entries in manifest for other Flow modules. Not sure if we need this entry for all the modules or only for flow-server, as other modules might hardly be used without flow-server.

2023-04-02 13:00 UTC, czp13 commented
Executed the tests some times, ended up with these errors:
- https://github.com/vaadin/flow/pull/16379/checks?check_run_id=12429972674

All of the 40 tests are failing having the same characteristics:
- error message:
```
com.vaadin.pro.licensechecker.LicenseException: 
Unable to validate the license, please check your internet connection. If you need to work offline then please go to https://vaadin.com/pro/validate-license?getOfflineKey=mid-d9819704-d22fea3c to retrieve an offline key.
For CI/CD build servers, you need to download a server license key, which can work offline to create production builds. You can download a server license key from https://vaadin.com/myaccount/licenses.
For troubleshooting steps, see https://vaadin.com/licensing-faq-and-troubleshooting.
	at com.vaadin.pro.licensechecker.LicenseChecker.checkLicense(LicenseChecker.java:292)
	at com.vaadin.pro.licensechecker.LicenseChecker.checkLicense(LicenseChecker.java:226)
	at com.vaadin.pro.licensechecker.LicenseChecker.checkLicense(LicenseChecker.java:129)
	at com.vaadin.pro.licensechecker.LicenseChecker.checkLicense(LicenseChecker.java:104)
```
- coming from `flow-polymer-template`sub project

The related code is:
```        if (proKey == null) {
            // No proKey found - probably first launch

            proKey = vaadinComIntegration.openBrowserAndWaitForKey(product, noKeyUrlHandler);
            if (proKey != null) {
                LocalProKey.write(proKey);
                if (proKeyValidator.validate(product, proKey, machineId, buildType) == Result.OK) {
                    // Online validation OK
                    return;
                }
            }
        }
````

My best guess really is that we do not have a server key or pro key (not sure which one we use for building servers), added here).  I will catch up with Zhe this Monday.

2023-04-02 13:00 UTC, czp13 requested changes
ProKey/Server key thin blocking this and manual testing.

2023-04-03 09:59 UTC, czp13 approved these changes

2023-04-04 07:15 UTC, mshabarov commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +        LicenseChecker.checkLicense("flow", Version.getFullVersion(),
The product name for Flow is "flow", hope it is fine and not overlap any existing product on the license server. After this getting merged, we need to add it to the product list.

2023-04-04 07:19 UTC, mshabarov commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +        validateLicense();
Commercial components check was not backported into Flow 9.0, thus, there is no check like in the latest versions, see https://github.com/vaadin/flow/blob/ca8bdee13523451da585b5afe865ffa67f4a6a9a/flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java#L515.

Since the Flow 9.1 is now a commercial itself, maybe components check is not needed, but I'm not sure 100%.

2023-04-05 06:37 UTC, Artur- requested changes

2023-04-05 06:37 UTC, Artur- commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +        validateLicense();
Sounds like out of scope for this change. The other parts can be backported but shouldn't be unless there is a good reason.

2023-04-05 06:37 UTC, Artur- commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +        LicenseChecker.checkLicense("flow", Version.getFullVersion(),
Should be fine

2023-04-05 06:37 UTC, Artur- commented on flow-server/bnd.bnd
> +CvdlName: ${cvdlName}
I don't think we need CvdlName at all

2023-04-05 06:37 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
> +            // Using a null BuildType to allow trial licensing builds
Where does this come from? Why not use `BuildType.DEVELOPMENT`?

2023-04-05 06:37 UTC, Artur- commented on pom.xml
> +                <version>1.12.3</version>
@ZheSun88 should this be a property instead for some auto-updating?

2023-04-05 10:41 UTC, mshabarov commented on flow-server/bnd.bnd
> +CvdlName: ${cvdlName}
Hmm, since we call the LC directly for Flow, probably this parameter is not needed, yes. It is needed to let LC know what this is a commercial product and what is the name of it (e.g. commercial components)

2023-04-05 10:47 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
> +            // Using a null BuildType to allow trial licensing builds
I spied it here https://github.com/vaadin/sso-kit/pull/58/files#diff-ebb4a6381d3d39073dbcdd3726cf525e28136f738aad157c7d7fa6c8c098c762R45

Will change to BuildType.DEVELOPMENT. Agree

2023-04-05 10:58 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
> +            // Using a null BuildType to allow trial licensing builds
Done

2023-04-05 10:58 UTC, mshabarov commented on flow-server/bnd.bnd
> +CvdlName: ${cvdlName}
Removed

2023-04-05 13:11 UTC, Artur- approved these changes

2023-04-06 06:58 UTC, merged