feat: HMR for theme styles.css in bundle mode
vaadin/flow pull request #16455
Opened 2023-03-29 08:28 UTC by Artur-

2023-04-04 09:47 UTC, sissbruecker commented on vaadin-dev-server/frontend/vaadin-dev-tools.ts
> +        (linkTag as any).href = `${path}?${new Date().getTime()}`;
In Firefox, stylesheets that are `@import`ed from the main stylesheet are not updated when changing the URL.


https://user-images.githubusercontent.com/357820/229753888-d8845cfc-2f93-4fba-accb-b844ee7a024c.mp4

Chrome and Safari do not have this problem.

2023-04-04 10:42 UTC, sissbruecker commented on vaadin-dev-server/frontend/vaadin-dev-tools.ts
> +        (linkTag as any).href = `${path}?${new Date().getTime()}`;
Just noting that the refresh also quite sluggish on my system (around 1 second), and causes some flashing of the styles, at least in Chrome and Firefox.

2023-04-04 10:44 UTC, Artur- commented on vaadin-dev-server/frontend/vaadin-dev-tools.ts
> +        (linkTag as any).href = `${path}?${new Date().getTime()}`;
The flashing can probably be fixed by first loading the new styles and then removing the old. Any idea where the sluggishness come from?

2023-04-04 10:49 UTC, Artur- commented on vaadin-dev-server/frontend/vaadin-dev-tools.ts
> +        (linkTag as any).href = `${path}?${new Date().getTime()}`;
Ah I see, you should test with #16458. The current file watcher is slow

2023-04-04 10:56 UTC, Artur- commented on vaadin-dev-server/frontend/vaadin-dev-tools.ts
> +        (linkTag as any).href = `${path}?${new Date().getTime()}`;
Any other ideas to fix the Firefox issue except rewiting all imports so they also have a query parameter?

2023-04-04 11:58 UTC, sissbruecker commented on vaadin-dev-server/frontend/vaadin-dev-tools.ts
> +        (linkTag as any).href = `${path}?${new Date().getTime()}`;
> Ah I see, you should test with https://github.com/vaadin/flow/pull/16458. The current file watcher is slow

Nice, that's a huge improvement 👍

> The flashing can probably be fixed by first loading the new styles and then removing the old.

Sounds good. One thing to keep in mind maybe is that updates can happen very frequently with the theme editor (rapidly clicking undo/redo), so this could result in loading multiple stylesheets in parallel.

> Any other ideas to fix the Firefox issue except rewiting all imports so they also have a query parameter?

The only other thing I can think of is recursively inlining all imported files into `styles.css` and then push that to the dev tool. Dev tool replaces `<link>` with style tag or constructed stylesheet. I'm not sure how difficult inlining the styles would be, there are probably several edge-cases like importing from an URL rather than a file.

As for your suggestion, I'm not sure where we would rewrite the imports - we don't want to change the actual project files?

2023-04-04 12:06 UTC, Artur- commented on vaadin-dev-server/frontend/vaadin-dev-tools.ts
> +        (linkTag as any).href = `${path}?${new Date().getTime()}`;
Right now, it feels like we should read and combine styles.css on the server in `DevModeHandlerManagerImpl` when the file watcher is triggered. Instead of sending the path to the dev tools, we should send the combined content directly. Then we can use a `<style>` instead of `<link>` and make everything work + get rid of the flashing

2023-04-04 12:18 UTC, sissbruecker commented on vaadin-dev-server/frontend/vaadin-dev-tools.ts
> +        (linkTag as any).href = `${path}?${new Date().getTime()}`;
Yes, that's what I meant. The only tricky part could be resolving imports, or leaving them as is if they reference a URL.

2023-04-04 17:19 UTC, Artur- commented on vaadin-dev-server/frontend/vaadin-dev-tools.ts
> +        (linkTag as any).href = `${path}?${new Date().getTime()}`;
Updated to use `<style>` tag and combining the CSS on the server. It still has a few shortcuts that need to be fixed but should now work also in Firefox

2023-04-05 08:50 UTC, sissbruecker commented on vaadin-dev-server/frontend/vaadin-dev-tools.ts
> +        (linkTag as any).href = `${path}?${new Date().getTime()}`;
Can confirm it works 👍. Flashing seems to be gone as well.

2023-04-05 08:59 UTC, sissbruecker commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/CssBundler.java
> +            .compile("@import\\s*(url\\(\\s*)(\\'|\\\")?(\\S*)(\\2\\s*\\));?");
Wrapping with `url("...")` seems to be optional: https://developer.mozilla.org/en-US/docs/Web/CSS/@import#importing_css_rules

2023-04-05 14:16 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/CssBundler.java
> +            .compile("@import\\s*(url\\(\\s*)(\\'|\\\")?(\\S*)(\\2\\s*\\));?");
Yes, this file definitely needs some tests and then some fixes The syntax is
```
@import =    @import [ <url> | <string> ] [ layer | layer( <layer-name> ) ]? <import-conditions> ;
```

so I guess we should as a minimum handle
```
@import "foo.css"
@import 'foo.css'
import url(foo.css)
import url('foo.css');
@import url("foo.css");
```

2023-04-06 09:26 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/CssBundler.java
> +            .compile("@import\\s*(url\\(\\s*)(\\'|\\\")?(\\S*)(\\2\\s*\\));?");
Now it should be a little bit more generic and even has a test

2023-04-06 10:56 UTC, mshabarov requested changes
Tested with Vaadin 24.1 pre starter and HMR works like a charm for me in Chrome.
Some minor comments.

2023-04-06 10:56 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +        File frontendDirectory = new File("frontend");
This should get the frontend folder from configuration.

2023-04-06 10:56 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +        element.attr("data-dev-id",
This can be any key name basically. However `data-dev-id` doesn't say much what is it. Maybe `styles-id` or `styles-path` would be better?

2023-04-06 10:56 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +            e.printStackTrace();
Don't forget to handle it properly: log that the styling fails or throw.

2023-04-06 10:56 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/CssBundler.java
> +            return result.group();
The logic behind this method is a bit encrypted for me, need to make another attempt to understand it later.

2023-04-06 10:56 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +        String projectThemeName = maybeThemeName.orElse(null);
What happens if `projectThemeName` is null ? :thinking_face:

2023-04-06 11:00 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +        element.attr("data-dev-id",
I would keep `styles` out of it as the `styles` tag already tells that. If we want to avoid conflicts then custom attributes should start with `data-`. Vite uses `data-vite-dev-id`, that's where the current `data-id` comes from. Would `data-file-path` be better?

2023-04-06 11:03 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +        element.attr("data-dev-id",
> Would data-file-path be better?

Yes, would be better +

2023-04-06 11:26 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
> +        String projectThemeName = maybeThemeName.orElse(null);
That's not even from this commit, it's from the parent :)

2023-04-06 11:27 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +        element.attr("data-dev-id",
Renamed

2023-04-06 11:27 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +            e.printStackTrace();
Foxed

2023-04-06 11:30 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/CssBundler.java
> +            return result.group();
Well that's the only difficult part of this PR :)

I added a comment about the source of the regexp. Otherwise it just tries to find imports and inline them in the CSS if they are in the project

2023-04-06 11:40 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +        File frontendDirectory = new File("frontend");
Fixed to use correct method

2023-04-06 11:42 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/CssBundler.java
> +            return result.group();
The tests are the one that are supposed to prove then that it actually does what it promises

2023-04-06 13:56 UTC, Artur- commented
Now this also fixes #16366 ...

2023-04-11 08:24 UTC, mshabarov approved these changes

2023-04-11 08:25 UTC, merged