fix: Initialize the route only once when using eager server load
vaadin/flow pull request #16498
Opened 2023-04-01 07:26 UTC by Artur-

Changes bootstrap for eager mode so that the index page contains the <flow-container-[appId]> div and the virtual child for this element is created eagerly on the server. This allows the initial render on the client side to put the content inside the flow-container instead of document body as happened before.
    
By using a convention on how the container div is created and id is set, we no longer need to communicate the element tag and id from the client.
    
Fixes #16046

2023-04-03 06:26 UTC, Artur- commented
This depends on #16497

2023-04-04 08:45 UTC, mcollovati requested changes

2023-04-04 08:45 UTC, mcollovati commented on flow-tests/test-eager-bootstrap/src/test/java/com/vaadin/flow/eagerbootstrap/ParameterIT.java
> +    }
This test passes also without the fix if it runs isolated.
Is there another way to ensure that the view is not initialized twice?

2023-04-04 09:36 UTC, Artur- commented on flow-tests/test-eager-bootstrap/src/test/java/com/vaadin/flow/eagerbootstrap/ParameterIT.java
> +    }
Right, the real test is `setParameterCalledAsExpected` and apparently the same view instance is reused even though navigation happens twice. Maybe we can just delete this test as `setParameterCalledAsExpected` ensures that `setParameter` is only called once

2023-04-04 09:38 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/component/UI.java
> +            }
Fixed

2023-04-04 09:39 UTC, Artur- commented on flow-tests/test-eager-bootstrap/src/test/java/com/vaadin/flow/eagerbootstrap/ParameterIT.java
> +    }
Removed and simplified

2023-04-04 12:55 UTC, mcollovati approved these changes

2023-04-04 12:55 UTC, merged