refactor: integrate CSS HMR into theme editor
vaadin/flow pull request #16516
Opened 2023-04-03 12:54 UTC by sissbruecker

## Description

Integrates Vite HMR into theme editor:
- Remove loading of the full theme editor CSS into preview stylesheet
- Instead do an optimistic update by adding CSS rules for single property updates to preview stylesheet
- Change CSS HMR to dispatch a DOM event after Vite has updated style modules
- Listen for that event in theme editor, and when it is triggered, remove optimistic style updates, and refresh property values shown in editor. This should ensure that the correct property values are shown in all cases (change property, clear property, change class name, undo, redo).
- Removes mechanism for preventing live reload from the dev tools

Only works with the Vite hot deploy mode currently. For dev bundle mode, CSS HMR needs to be implemented first, after which the HMR mechanism can be made to dispatch the same event that is currently used in Vite mode.

2023-04-03 14:01 UTC, MarcinVaadin submitted a review, later dismissed
Works fine after last commit, LGTM.

2023-04-03 14:26 UTC, Artur- requested changes

2023-04-03 14:26 UTC, Artur- commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
> +  import.meta.hot.on('vite:afterUpdate', (update) => {
This should be inside `if (import.meta.hot)` above

2023-04-03 14:27 UTC, Artur- commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
> +  import.meta.hot.on('vite:afterUpdate', (update) => {
Oh, it actually is inside that...

2023-04-03 14:27 UTC, Artur- submitted a review, later dismissed

2023-04-04 10:26 UTC, sissbruecker commented
Rebased the PR on top of https://github.com/vaadin/flow/pull/16455, and added dispatching of the theme change event to the dev tools as well.

2023-04-13 14:59 UTC, Artur- commented
rebased

2023-04-17 21:26 UTC, MarcinVaadin approved these changes
LGTM, tested and work. Support for _themeEditorLoadPreview_ command can be removed from debug message handler.

2023-04-17 21:27 UTC, merged