refactor: added UsageStatistics for ThemeEditor
vaadin/flow pull request #16555
Opened 2023-04-06 13:53 UTC by MarcinVaadin

## Description

Added UsageStatistics `flow/ThemeEditor` to Theme Editor.

2023-04-06 15:08 UTC, sissbruecker commented on vaadin-dev-server/frontend/theme-editor/editor.ts
> +import { ServerInfo } from '../vaadin-dev-tools';
This creates a circular dependency between `editor.ts` and `vaadin-dev-tools.ts`, which itself imports `editor.ts`. Might not be an issue here, since it only imports a type for now, but should be avoided in general. Would be better to extract the interface into a separate module and import that in both dev tools and editor. Or check if the Flow version is available through some global via `window.Vaadin.Flow`, then passing the server info as property is not necessary.

2023-04-06 16:26 UTC, Artur- commented on vaadin-dev-server/frontend/theme-editor/editor.ts
> +        registrations.push({ is: registrationId, version: this.serverInfo.flowVersion });
Why do you build your own tracker in TS when you could send a message to Java (or use an existing one) and call `markAsUsed`?

2023-04-06 19:56 UTC, MarcinVaadin commented on vaadin-dev-server/frontend/theme-editor/editor.ts
> +        registrations.push({ is: registrationId, version: this.serverInfo.flowVersion });
TBH using `UsageStatistics.markAsUsed` was my initial idea, approach updated

2023-04-07 04:41 UTC, Artur- requested changes
What's with all the unrelated changes?

2023-04-07 06:00 UTC, MarcinVaadin commented
> What's with all the unrelated changes?

I've run 'npm prettier' same as I run maven formatter. It was mentioned in readme.

2023-04-13 16:26 UTC, Artur- commented on vaadin-dev-server/frontend/vaadin-dev-tools.ts
> +export interface ServerInfo {
Should this be here?

2023-04-13 16:49 UTC, Artur- submitted a review, later dismissed

2023-04-14 05:53 UTC, MarcinVaadin commented on vaadin-dev-server/frontend/vaadin-dev-tools.ts
> +export interface ServerInfo {
```suggestion
interface ServerInfo {
```

2023-04-14 05:54 UTC, MarcinVaadin commented on vaadin-dev-server/frontend/vaadin-dev-tools.ts
> +export interface ServerInfo {
No, leftover. Removed.

2023-04-14 06:03 UTC, Artur- approved these changes

2023-04-14 06:23 UTC, merged