refactor!: Move generated Flow files into frontend/generated/flow
vaadin/flow pull request #16565
Opened 2023-04-11 06:54 UTC by Artur-

Removes the need for importing from the target folder and simplifies when all generated frontend files are in the same folder

2023-04-11 12:59 UTC, Artur- commented
Hm, now `versions.json` go into `frontend/generated/flow` which is probably wrong as that is not and should not be part of the frontend build

2023-04-13 08:25 UTC, caalador requested changes

2023-04-13 08:25 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
> +                    && !module.contains("Frontend/generated/flow/")) {
Would be good to have `"Frontend/generated/flow/"` as a constant so breaking it with a typo later is less likely.

Already in this file I see it used 3 times.

2023-04-13 08:25 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    }
JDocs missing for public methods

2023-04-13 08:25 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
>                      FrontendUtils.FALLBACK_IMPORTS_NAME);
```suggestion
                    FrontendUtils
                            .getFlowGeneratedFolder(
                                    options.getFrontendDirectory()),
                    FrontendUtils.FALLBACK_IMPORTS_NAME);
```
Lets use the simple folder instead of the one with the extra file name

2023-04-13 11:55 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
>                      FrontendUtils.FALLBACK_IMPORTS_NAME);
Fixed

2023-04-13 11:55 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    }
Added

2023-04-13 11:55 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
> +                    && !module.contains("Frontend/generated/flow/")) {
Done

2023-04-13 12:57 UTC, merged