fix: clean Frontend/generated folder
vaadin/flow pull request #16647
Opened 2023-04-20 12:12 UTC by caalador

Clean the frontend generated folder
on prepare-frontend task (maven/gradle)
and spring contextInitialization.

Closes #16640

2023-04-20 12:31 UTC, Artur- commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPrepareFrontendTask.kt
> +        project.delete(extension.generatedTsFolder.absolutePath)
Can Gradle not fail at this?

2023-04-20 12:31 UTC, Artur- commented on flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
> +                    "Failed to generate old file to Frontend/generated/flow");
```suggestion
                    "Failed to generate old.js in Frontend/generated/flow");
```

2023-04-20 12:31 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
> +                final String frontendFolder = config.getStringProperty(
This is a weird place to do it. Where does the cleaning happen if you run an embedded Jetty?

2023-04-21 03:58 UTC, caalador commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPrepareFrontendTask.kt
> +        project.delete(extension.generatedTsFolder.absolutePath)
I went according to VaadinCleanTask and also what I get from the API documentation it only returns  true/false for deleted something or not: https://gradle.github.io/kotlin-dsl-docs/api/org.gradle.api/-project/delete.html

2023-04-21 04:09 UTC, caalador commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
> +                final String frontendFolder = config.getStringProperty(
Yes. Did this part a bit in a hurry yesterday. Moved to DevModeInitializer

2023-04-21 06:51 UTC, caalador commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
> +                final String frontendFolder = config.getStringProperty(
That was a worse place to have it.
Can't come up with where this cleaning should happen for a start from app.

2023-04-21 06:56 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
> +                final String frontendFolder = config.getStringProperty(
If we would tie it to startup of Vite, then https://github.com/vaadin/flow/blob/38ffaa84158981de846b0f991139f092c6ce72d7/vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java#L202 should only be reached on the first startup and not on server restarts?

2023-04-21 07:01 UTC, caalador commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
> +                final String frontendFolder = config.getStringProperty(
But that is too late in the initialization as we have already generated all the new files.

2023-04-21 07:05 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
> +                final String frontendFolder = config.getStringProperty(
If there is no difference between a server startup and restart, maybe we need to do it in a Spring specific way then? Spring can tell the difference I think as spring dev tools related classes are retained over a restart

2023-04-21 11:28 UTC, caalador commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
> +                final String frontendFolder = config.getStringProperty(
What I have gotten to is that we can have an `ApplicationListener` for `ApplicationStartingEvent`  or a bit later `ApplicationContextInitializedEvent`, but I don't know how I would see if the event is from a dev tools restart so it cleans the folder for each run. 
Also a problem is that it does the clean even for running from maven which is not a big deal as it should be cleared anyway and we don't have the configuration so we could distinguish production execution.

2023-04-24 07:19 UTC, caalador commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
> +                final String frontendFolder = config.getStringProperty(
As I've not found a good solution for this I made issue #16670 for solving the spring app start case.

2023-04-24 07:57 UTC, mshabarov requested changes

2023-04-24 07:57 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
> +import static com.vaadin.flow.server.frontend.FrontendUtils.PARAM_FRONTEND_DIR;
Changes in this class have been reverted, so these imports are not needed too.

2023-04-25 04:15 UTC, merged