feat: Add convenience DoubleClickEvent and SingleClickEvent
vaadin/flow pull request #16644
Opened 2023-04-20 09:03 UTC by TatuLund

Fixes https://github.com/vaadin/flow-components/issues/2173

2023-04-20 10:55 UTC, Legioth commented on flow-server/src/main/java/com/vaadin/flow/component/ClickNotifier.java
> +            Registration internalEventReg = this.addClickListener(event -> {
This seems overly complicated. What about instead doing something like this (along with adding `@DomEvent("click")` to the event type):
```
return ComponentUtil.addListener(this, DoubleClickEvent.class, listener,
  registration -> registration.setFilter("event.detail == 2"));
```

Aside from less code, this would also have the benefit that filtering happens already on the client so that redundant requests aren't even sent to the server.

2023-04-20 10:55 UTC, Legioth commented on flow-server/src/main/java/com/vaadin/flow/component/DoubleClickEvent.java
> + * Event fired when a component is single clicked.
double clicked

2023-04-20 10:55 UTC, Legioth commented on flow-server/src/main/java/com/vaadin/flow/component/DoubleClickEvent.java
> +        // source, notClient, 4 coordinates, clickCount, button, 4 modifier
There's 12 items in this list but only 11 passed parameters

2023-04-20 10:55 UTC, Legioth commented on flow-server/src/main/java/com/vaadin/flow/component/AbstractClickEvent.java
> + * Abstract super class event for e.g. DoubleClickEvent and SingleClickEvent.
Any reason to not consistently use this for all click events, including the existing `ClickEvent` class?

2023-04-20 11:00 UTC, TatuLund commented on flow-server/src/main/java/com/vaadin/flow/component/DoubleClickEvent.java
> +        // source, notClient, 4 coordinates, clickCount, button, 4 modifier
Forgot to delete clickCount from the comment

2023-04-20 11:10 UTC, Legioth commented on flow-server/src/main/java/com/vaadin/flow/component/AbstractClickEvent.java
> + * Abstract super class event for e.g. DoubleClickEvent and SingleClickEvent.
Now when I think about it further, I wonder whether separate event types are really needed at all when the only practical difference is the `getClickCount()` method?

2023-04-20 11:20 UTC, TatuLund commented on flow-server/src/main/java/com/vaadin/flow/component/AbstractClickEvent.java
> + * Abstract super class event for e.g. DoubleClickEvent and SingleClickEvent.
Especially filtering the single click event, which currently requires hacks. So this is convenience, and DX improvement.

2023-04-20 11:22 UTC, TatuLund commented on flow-server/src/main/java/com/vaadin/flow/component/AbstractClickEvent.java
> + * Abstract super class event for e.g. DoubleClickEvent and SingleClickEvent.
> Any reason to not consistently use this for all click events, including the existing ClickEvent class?**

I could modify ClickEvent to extend this if that is preferred. I was just conservative with my approach.

2023-04-20 11:42 UTC, TatuLund commented on flow-server/src/main/java/com/vaadin/flow/component/AbstractClickEvent.java
> + * Abstract super class event for e.g. DoubleClickEvent and SingleClickEvent.
Fixed now

2023-04-20 11:44 UTC, TatuLund commented on flow-server/src/main/java/com/vaadin/flow/component/ClickNotifier.java
> +            Registration internalEventReg = this.addClickListener(event -> {
Fixed

2023-04-20 13:10 UTC, Legioth commented on flow-server/src/main/java/com/vaadin/flow/component/AbstractClickEvent.java
> + * Abstract super class event for e.g. DoubleClickEvent and SingleClickEvent.
From the DX perspective, it's just `button.addSingleClickListener(event -> doSomething())` regardless of whether there's a dedicated event type.

As for the hacks, I would still suggest to do filtering in the browser instead by using the `ComponentUtil.addListener` overload with a callback for modifying the low-level `DomListenerRegistration` to add a filter.

2023-04-24 13:07 UTC, Legioth commented
No further comment from my side, but I leave final review in the hands of the Flow team who maintains the code.

I would recommend them to discuss what they think on the question about using multiple different event classes vs using the familiar `ClickEvent` class throughout (and then changing the double click to filter on `event.detail == 2` instead of listening for the `dblclick` event).

2023-04-28 09:40 UTC, mcollovati commented
Personally, I would prefer the solution with only one `ClickEvent` and the filter: 
* the effect is the same as having multiple events and it will provide the same DX as there will be a `addDoubleClickListener` method
* less code to maintain
* a simpler API, as there will be only `addClickListener` and `addDoubleClickListener`
* we can consider to add also the proposed `addSingleClickListener`, using a similar filter or an overload of `addClickListener` that takes the number of expected clicks

2023-04-28 10:14 UTC, TatuLund commented
> we can consider to add also the proposed addSingleClickListener,

@mcollovati This was the actual need of my customer.

2023-04-28 10:32 UTC, mcollovati commented
@TatuLund Sorry, I missed that part. So, it makes sense to add that method

2023-05-09 08:18 UTC, TatuLund commented
> Personally, I would prefer the solution with only one ClickEvent and the filter:

@mcollovati simplification is done now, tests pass. So I hope it is finally ok.

2023-05-09 08:57 UTC, mcollovati requested changes
LGTM.
There's just a copy/paste typo in javadocs.
Could you also please change the PR title, as now the mentioned event does not exist anymore? 
Maybe something like  "Added single and double click event listeners registration methods"?

2023-05-09 08:57 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/ClickNotifier.java
> +     * Adds a single click listener to this component.
```suggestion
     * Adds a double click listener to this component.
```

2023-05-09 13:49 UTC, merged