feat!: add DataProvider API for refreshing without clearing selection
vaadin/flow pull request #16650
Opened 2023-04-20 13:27 UTC by tltv

Adds new method `DataProvider#refreshItems(boolean)` as a replacement for `DataProvider#refreshAll()` to allow choosing to either clear or keep selection. 
`DataChangeEvent` has new method `isClearSelection()` that `DataProvider` change listeners can utilize.

Fixes #16532

2023-04-21 08:53 UTC, mcollovati requested changes

2023-04-21 08:53 UTC, mcollovati commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataProvider.java
>      void refreshAll();
Should we also add the `@Deprecated` annotation here?

2023-04-21 08:53 UTC, mcollovati commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataProvider.java
>       * when it's called. It allows to update UI components when user changes
```suggestion
     * when they are called. It allows to update UI components when user changes
```

2023-04-21 11:37 UTC, mcollovati approved these changes

2023-04-24 11:08 UTC, merged

2023-09-28 10:10 UTC, mshabarov commented
Reverted, because of changed design from having DataProvider methods to a several selection modes on a Component level, see https://github.com/vaadin/platform/issues/4486.