feat: Use default prod bundle if possible
vaadin/flow pull request #16653
Opened 2023-04-20 14:05 UTC by mshabarov

Re-uses re-bundle checker in production mode. Copies default bundle files from JAR to application's resource folder in `target` and skips re-bundling or executes usual frontend build codes if it sees any customisations.

Fixes https://github.com/vaadin/flow/issues/16627

2023-04-20 14:09 UTC, mshabarov commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
> +        if (generateBundle() && !BuildFrontendUtil.bundleExists(this)) {
This means that to re-build the prod bundle, one should `clean` the project, i.e. completely remove Vaadin generated files from build/output folder. If it's may break projects in some way, we have to pass/throw the `needBuild` result this place to not run the checker again.

2023-04-20 14:14 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
> +            getLogger().warn("There is no production bundle in the classpath.");
Is this a warning or just an information? Looking at the following scenario:
- use Vite instead of Dev Bundle
- don't have a Prod Bundle available in CI because Vite is also running in CI to create a bundle every time the application is build (no shared storage in between CI runs)

2023-04-20 14:33 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
> +        if (options.isSkipDevBundle()) {
We can perhaps extend this parameter to production mode as well.

2023-04-20 14:40 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
> +            getLogger().warn("There is no production bundle in the classpath.");
Are you sure that's always in the class path? Looking at the recommendation to exclude `vaadin-dev`from production builds to reduce the final artefact size, I'm not sure if it's also there.. or are you goint to add it to the `maven/gradle` plugin as dependency?

2023-04-20 14:47 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
> +            getLogger().warn("There is no production bundle in the classpath.");
You can close/resolve this :) Just saw the PR at the platform repo where it's done (added to the plugins, instead of flow-server)

2023-04-21 08:48 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
> +            getLogger().warn("There is no production bundle in the classpath.");
> maven/gradle plugin as dependency

Yes, this is the plan so far.

2023-04-26 11:45 UTC, mshabarov commented on flow-tests/test-express-build/test-dev-bundle-no-plugin/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/NoAppBundleIT.java
> +        // TODO: for default prod bundle these are still generated
https://github.com/vaadin/flow/issues/16696

2023-04-26 12:44 UTC, caalador requested changes

2023-04-26 12:44 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +            if (!options.isProductionMode() && options.isBundleBuild()) {
The comment can be moved inside if and the productionMode flag removed when this is added as an `else if {` after the `if(productionMode)`

2023-04-26 12:44 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
> +    public static boolean needsBundleBuild(Options options,
I would perhaps move these 2 methods out from BundleValidationUtil as they are production bundle specific.
Could perhaps have a class `CheckBundleRequirement` that would have the needsBuild checks for both production bundle and the dev bundle that is now in `TaskRunDevBundleBuild`

2023-04-26 12:44 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
> +        if (!options.isProductionMode()
Seems this is moved from TaskRunDevBundleBuild here, but it is development mode specific even though it is used from the `needsBuildProdBundle` method.

2023-04-26 12:44 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
> +        }
I would perhaps have the start separate for development and production bundle and have the rest of the checks mutual in the Util class.

2023-04-26 12:44 UTC, caalador commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
> +        if (generateBundle() && !BuildFrontendUtil.bundleExists(this)) {
Do we need to have this check? shouldn't it be fine to run the checker to see if a build is needed or not?

2023-04-26 12:44 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyBundleFiles.java
> +public class TaskCopyBundleFiles implements FallibleCommand {
JavaDoc missing

2023-04-26 12:44 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyBundleFiles.java
> +package com.vaadin.flow.server.frontend;
Header missing.

2023-04-26 12:44 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFiles.java
> +                if (!options.isProductionMode() && options.isBundleBuild()) {
Could add the `isDevBundleBuild()` to Options as the written out check. so it would just combine the not production want bundle build.

2023-04-26 13:05 UTC, mshabarov commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
> +        if (generateBundle() && !BuildFrontendUtil.bundleExists(this)) {
The checker is used on the previous step `BuildFrontendUtil.runNodeUpdater` when Flow makes a decision to generate `package.json`, install packages etc. We could check here again, but this is double work. I'd prefer to re-use the result of checker also here, but I don't know a good way to pass this flag here without changing the API.

2023-04-27 03:57 UTC, caalador commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
> +        if (generateBundle() && !BuildFrontendUtil.bundleExists(this)) {
We could perhaps utilize the token file so in the check when we know the result we would do:
```
        final JsonObject token = Json.parse(
                FileUtils.readFileToString(options.getTokenFile(),
                        StandardCharsets.UTF_8));
        token.put("needsBundle", false);
        FileUtils.write(options.getTokenFile(), token.toJson(), StandardCharsets.UTF_8);
```
And then change `bundleExists` to 
```
        final File tokenFile = getTokenFile(adapter);
        if (!tokenFile.exists()) {
            adapter.logWarn(
                    "Require bundle build due to missing token file.");
            return false;
        }
        try {
            String json = FileUtils.readFileToString(tokenFile,
                    StandardCharsets.UTF_8.name());
            JsonObject buildInfo = JsonUtil.parse(json);
            if(!buildInfo.hasKey("needsBundle")) {
                return false;
            }
            return buildInfo.getBoolean("needsBundle");
        }catch(IOException e){}
```

2023-04-27 06:42 UTC, caalador commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
> +        if (generateBundle() && !BuildFrontendUtil.bundleExists(this)) {
And clean the field in `updateBuildFile()` so we don't have leftovers in the end result.

2023-04-27 14:03 UTC, mshabarov commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
> +        if (generateBundle() && !BuildFrontendUtil.bundleExists(this)) {
Thanks for the suggestion, I did it in https://github.com/vaadin/flow/pull/16653/commits/90cde687aacfafff0c49aae878fdd8fd6f7682a2 , but seems something overrides the token file between `BuildFrontendUtil.runNodeUpdater(this);` and `BuildFrontendUtil.needsBundleBuild(this)` - i.e. after I write the flag into it and before I try to restore the flag. 

It looks as though it is done by `BuildFrontendUtil.updateBuildFile(this);`, however this line goes even after I try to restore the flag, so I'm confused. Need to check later on.

2023-04-28 04:11 UTC, caalador commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
> +        if (generateBundle() && !BuildFrontendUtil.bundleExists(this)) {
I don't see anything that would touch the file in between.
It will be cleaned after, but for that part it should just stay as it is.

2023-04-28 10:19 UTC, mshabarov commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
> +        if (generateBundle() && !BuildFrontendUtil.bundleExists(this)) {
Two thing that I get and that I don't completely understand: this file is being overridden and it always has result `true`, which I cannot explain at all. To not depend on the logic of handling token file, I made a separate temp file which has this flag.

2023-04-28 10:21 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
> +    public static boolean needsBundleBuild(Options options,
Refactored to have one public method taking a `Mode` as a parameter, then two private methods that has mode specific things and one internal method that has overall checking logic.

2023-04-28 10:22 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
> +        if (!options.isProductionMode()
Refactored

2023-04-28 10:22 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
> +        }
Refactored to have one public method taking a `Mode` as a parameter, then two private methods that has mode specific things and one internal method that has overall checking logic.

2023-04-28 10:51 UTC, caalador commented
Seems ok, but build has a failing test
`BundleValidationTest.bundleMissesSomeEntries_skipBundleBuildSet_noBundleRebuild:1602 Rebuild should be skipped`

2023-04-28 11:05 UTC, mshabarov commented
> Seems ok, but build has a failing test `BundleValidationTest.bundleMissesSomeEntries_skipBundleBuildSet_noBundleRebuild:1602 Rebuild should be skipped`

Fixed, this test is for dev mode currently, since production mode has no yet such a feature to skip rebundling.

2023-04-28 11:41 UTC, caalador approved these changes

2023-04-28 12:44 UTC, merged