More eager cleanup for UIs using Beacon API
vaadin/flow pull request #16657
Opened 2023-04-20 16:53 UTC by mstahv

Notifies server about closed UIs using a beacon request on pagehide event.

At the same time unifies behaviour in certain edge cases, where Safari maintained the state when brought back from page cache. Previously Safari in some situations kept the state.

Missing: automated tests, currently only tested manually with Safari, Chrome, Firefox and validated results using VisualVM

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2023-04-21 11:46 UTC, mstahv commented
Included IT only runs in Chrome 🤔 Might be good to get it run also on Chrome and Safari + permutation with Push on, but some team member can probably configure that about 10k time faster than me 👼

2023-04-21 11:58 UTC, mstahv commented
Looks like Push is on by default for these tests, I think that is enough as the xhr mode has much less moving parts. Also heard that in "platform tests" these tests are run on other browsers, so all should be covered.

2023-04-26 14:55 UTC, knoobie commented on flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
> +        Browser.getWindow().addEventListener("pagehide", e -> {
General Note / Question: Should this be enabled / toggled by the developer on application level? 

I was wondering if this could interfere with people's expectation that the UI is still present after the UI was redirected to e.g. PayPal or other payment providers and afterwards gets redirected again to the Vaadin UI.. where the user's session could be instantly lost because all UIs were immediately closed?

2023-04-26 15:05 UTC, mstahv commented on flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
> +        Browser.getWindow().addEventListener("pagehide", e -> {
Finally, I already told the Flow team that this is all done, except it is still waiting for a review by @knoobie  :-)

Now that I changed the behaviour on Monday that the beacon request is ignored on the server side for UIs with "preserveonrefresh" on, no need for that. For other UIs the state is lost anyways and we are still never dropping the session, that can(and should be) used for such state.

2023-04-26 15:37 UTC, knoobie commented on flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
> +        Browser.getWindow().addEventListener("pagehide", e -> {
You can always expect me lurking somewhere 😉 

Thanks for thinking this though before I was here 😅 My job here is done 😎

2023-04-27 04:16 UTC, mstahv commented on flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
> +        Browser.getWindow().addEventListener("pagehide", e -> {
I seriously value your insights a lot. You have good eye for code and so much experience of Vaadin that I don't see why your reviews wouldn't be enough 🙇

2023-04-27 06:38 UTC, mcollovati requested changes
Some typo and nits.
I would also like @heruan to have a brief look, to be sure this change may not break beacon handling in Collaboration Kit

2023-04-27 06:38 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
> +                                "Something was not sent to client on an UI that was already closed by beacon reqeuest or similar. This seems to happen with Safari occassionally when navigating away f
```suggestion
                                "Something was not sent to client on an UI that was already closed by beacon request or similar. This seems to happen with Safari occassionally when navigating away from a UI.");
```

2023-04-27 06:38 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
> +                        "Eager UI close ignorer for PreserveOnRefresh view");
```suggestion
                        "Eager UI close ignored for @PreserveOnRefresh view");
```

2023-04-27 06:38 UTC, mcollovati commented on flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/UIsCollectedWithBeaconAPIIT.java
> +    public void firstRun() {
nit: I would rename so that it should be easier to immediately understand what we are testing.
Something like `beaconHandling_navigateAwayFromApplication_uiClosedEarly`

2023-04-27 07:26 UTC, mstahv commented
I briefly looked at what @heruan  et co have done in collaboration engine with beacon api, and my hunch is that no issues with that. Currently you seem to be hooking on unload event, which is kind of deprecated but works most often. Depending on how you use it, you might in some cases now (after this change) use normal detach listeners, but I'd expect that you should at least in upcoming versions also detect visibility changes as well (e.g. to gray out a user who has switched to another tab) 🤷‍♂️

2023-04-27 10:00 UTC, mcollovati approved these changes
LGTM (unless there are troubles with Collaboration KIT)

2023-04-27 10:09 UTC, czp13 commented on flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
> +import elemental.dom.Document;
Not used, could be removed:
```suggestion
```

2023-04-27 10:10 UTC, czp13 commented on flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
> +            // now with beacon API request, it is probably
```suggestion
            // now with Beacon API request, it is probably
```

2023-04-27 10:46 UTC, mcollovati approved these changes

2023-04-27 11:11 UTC, czp13 approved these changes
👍

2023-04-27 11:44 UTC, merged