fix: Lazy load CSS also
vaadin/flow pull request #16709
Opened 2023-04-27 14:47 UTC by Artur-

2023-05-03 07:58 UTC, caalador requested changes

2023-05-03 07:58 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
> +    protected List<String> getCssLines(List<CssData> css) {
The index for cssLine should be a rising global as now we will get 0 for each css key

2023-05-03 10:11 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
> +    protected List<String> getCssLines(List<CssData> css) {
This should now be fine in master, but needs conflict resolution.

2023-05-03 10:21 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
> +    protected List<String> getCssLines(List<CssData> css) {
Is it fine to have
```
import $cssFromFile_0 from 'Frontend/foo.css?inline';
injectGlobalCss($cssFromFile_0.toString(), 'CSSImport end', document);
```

in multiple JS files?

2023-05-03 10:25 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
> +    protected List<String> getCssLines(List<CssData> css) {
I think it should be fine to have the same import identifier in different files, but ofc not having the same numbering might be better.

2023-05-03 10:31 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
> +    protected List<String> getCssLines(List<CssData> css) {
The question is not really the numbering but does `injectGlobalCss` handle deduplication and does having the import in multiple files cause overhead or not? I think the answer is "yes" and "does not cause overhead" but maybe it needs to be checked

2023-05-03 10:36 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
> +    protected List<String> getCssLines(List<CssData> css) {
Aa. The css is checked for if it has been injected with the exact same hash when target is document so it handles duplication. So overhead is duplicate data transmitted/stored in bundle and hash generation.

2023-05-03 10:55 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
> +    protected List<String> getCssLines(List<CssData> css) {
Ok, then this version could work

2023-05-04 04:08 UTC, caalador approved these changes

2023-05-04 04:09 UTC, merged