feat!: deprecate Label and add NativeLabel as replacement
vaadin/flow pull request #16708
Opened 2023-04-27 13:44 UTC by knoobie

## Description

Note: This Pull Request isn't finished. I wanted to start the discussion if you wanna include this in 24.1 (before beta). I'm going to finish the migration in flow (add TestBench class and refactor flow tests) if you are on board.

Fixes #4384

Related to #3532

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [x] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2023-05-09 12:29 UTC, tltv commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Label.java
> +@Deprecated(since = "24.1", forRemoval = true)
This deprecation should be documented well in Javadoc. Deprecating `Label` alone may not help those who are doing migration from old versions. 
How about adding Javadoc with `@deprecated` telling shortly why `Label` is deprecated and hint to use `Span` or `Div` instead to show text label and `NativeLabel` only if also `for` attribute is used.

2023-05-10 06:33 UTC, knoobie commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Label.java
> +@Deprecated(since = "24.1", forRemoval = true)
So, I take this comment as: 'Go for it.'? See the initial PR comment. For further information regarding this change, see the discussion and last comments in https://github.com/vaadin/flow/issues/3532

2023-05-12 11:57 UTC, mshabarov commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Label.java
> +@Deprecated(since = "24.1", forRemoval = true)
@knoobie @tltv thanks for the contribution and review! And sorry for a long reply, I took a break to dig into context. I like the idea, and see no obstacles to do it. I've heard a talks about usage of `Label` quite many times, so the misunderstanding of it turns into an issue in our framework. 

Not sure we can target this to Vaadin 24.1, because only few days remain to Beta release, so I propose to thoughtfully complete this feature and target it to 24.2. 

So in short, I vote to continue with this pull request, add a warning and explanatory javadoc. We can auto-replace all the usages of `Label` to `NativeLabel` in Flow tests at this point I think. Replacing it with `Span` would take an extra efforts.

Ping @Legioth just in case, but this feature is in accordance with his suggestion, so I suppose move forward.

2023-05-12 11:58 UTC, mshabarov commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Label.java
> +@Deprecated(since = "24.1", forRemoval = true)
I'm going to replace `!` from the title, because it is not a breaking change so far.

2023-05-12 13:17 UTC, knoobie commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Label.java
> +@Deprecated(since = "24.1", forRemoval = true)
I'm going to finish the PR on the weekend to get it rdy for you guys.

2023-05-12 16:50 UTC, knoobie commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Label.java
> +@Deprecated(since = "24.1", forRemoval = true)
Added proper deprecation notice and refactored tests to use `NativeElement` and `NativeElementLabel`. Should be ready for a proper review now.

2023-05-13 06:02 UTC, knoobie commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Label.java
> +@Deprecated(since = "24.1", forRemoval = true)
> add a warning

Added a warning about wrong usage of the Label in https://github.com/vaadin/flow/pull/16708/commits/4644275c69dbed49242afc951c41e1096e5227fd. This should only be logged in development mode, so that this does not create problems for Ops Teams and the Developer isn't bad-mouthed by the framework in front of their clients in production logs.. I was considering sanitizing `getText()` before logging it, but it wasn't really worth it, because it's only logged in development mode, where it shouldn't be problem.

2023-05-15 12:56 UTC, tltv requested changes

2023-05-15 12:56 UTC, tltv commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Label.java
> +    private static Boolean productionMode = null;
Move to top of the class next to the other static field.

2023-05-15 12:56 UTC, tltv commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Label.java
> +            LoggerFactory.getLogger(Label.class.getName())
Showing a warning only when label is detached is a bit late. It would be great to get this warning earlier.
Instead of doing this on detach, how about doing it earlier in following way on attach:
```
@Override
protected void onAttach(AttachEvent attachEvent) {
   super.onAttach(attachEvent);
   if (!isProductionMode(attachEvent)) {
      onetTimeExecutionRegistration = attachEvent.getUI().beforeClientResponse(this, ctx -> {
         onetTimeExecutionRegistration.remove();
         
         // show warning here when needed
      });
   }
}
```

2023-05-15 13:04 UTC, mshabarov commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Label.java
> +            LoggerFactory.getLogger(Label.class.getName())
I suppose the same warning should be added to `NativeLabel`, as it is valid/expected that even `NativeLabel` might be used as a plain text erroneously.

2023-05-15 13:11 UTC, tltv commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Label.java
> +            LoggerFactory.getLogger(Label.class.getName())
Maybe also limit this to only to initial attach with `attachEvent.isInitialAttach()`.

2023-05-15 14:07 UTC, knoobie commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Label.java
> +            LoggerFactory.getLogger(Label.class.getName())
done

2023-05-15 14:08 UTC, knoobie commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Label.java
> +            LoggerFactory.getLogger(Label.class.getName())
Once you guys are happy with the impl in Labe, I'm going to copy paste it to NativeLabel. (Even tho, I personally would not add it there; people using the new `NativeLabel` should know what they do (hopefully))

2023-05-16 06:15 UTC, mshabarov commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Label.java
> +        checkForAttributeOnAttach = attachEvent.getUI()
I suppose that before adding a new listener by `beforeClientResponse`, it should check
```java
if (checkForAttributeOnAttach == null) { 
```
otherwise I don't understand why we use `beforeClientResponse` at all.

2023-05-16 06:16 UTC, mshabarov commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Label.java
> +            LoggerFactory.getLogger(Label.class.getName())
Yes, good comment. For `NativeLabel` we can skip adding a warning.

2023-05-16 06:31 UTC, mshabarov commented
The build validation stops because of compilation errors:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project flow-html-components: Compilation failure
Error:  flow/flow-html-components/src/main/java/com/vaadin/flow/component/html/Label.java:[184,33] cannot access jakarta.servlet.http.HttpSessionBindingListener
Error:    class file for jakarta.servlet.http.HttpSessionBindingListener not found
```
This pull request doesn't add.import this class, this is weird.

2023-05-16 06:57 UTC, knoobie commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Label.java
> +        checkForAttributeOnAttach = attachEvent.getUI()
done

2023-05-16 07:00 UTC, knoobie commented on flow-html-components/pom.xml
> +        </dependency>
@mshabarov 

> he build validation stops because of compilation errors

Looks like the culprit is the usage of `VaadinSession` because it has `jakarta` imports.. My first try would be to add the servlet-api as provided, if you don't like. We could think about changing the logik to get the production mode information from `VaadinService.getCurrent().getDeploymentConfiguration().isProductionMode()` instead of using the AttachEvent.

2023-05-16 07:47 UTC, tltv commented on flow-html-components/pom.xml
> +        </dependency>
I like usage of `VaadinService` as you suggested as long as it helps to avoid adding new dependency. Otherwise import should be fine too.

2023-05-16 07:59 UTC, knoobie commented on flow-html-components/pom.xml
> +        </dependency>
Done

2023-05-16 11:44 UTC, tltv approved these changes

2023-05-16 11:46 UTC, mshabarov approved these changes

2023-05-16 12:22 UTC, merged

2023-06-21 12:22 UTC, knoobie commented
@mshabarov I just realized that there are a lot of usages within the flow-components that are still using the old Label and polluting the logs because they are not associated on the server side, but on the client side thanks to the slot=label Attribute. I'm wondering if we should add this condition also to the list of valid usages to reduce the amount of work the component team has to do urgendly to remove the log spam for users. 

Example FormLayout or RadioGroup