Fix: theme change should trigger dev bundle build in all cases (#16667) (CP: 24.0)
vaadin/flow pull request #16717
Opened 2023-04-28 13:54 UTC by czp13

_As the automatic cherry-pick was failing I did the manual one._

## Description

Steps to reproduce:
1. build/trigger a custom dev-bundle
2. change something in your `theme.json` (removal is the best) 
`theme.json "lumoImports": [ "typography", "badge" ]`-> `theme.json "lumoImports": [ "typography"]`
3. dev bundle build will not be triggered, so `stat.json` will not handle the change but will have the old values:
```
 "themeJsonContents": {
  "my-theme": "{\n  \"lumoImports\" : [ \"typography\", \"badge\"]\n}\n"
 },
```

The expected outcome **should** be this:
```
 "themeJsonContents": {
  "my-theme": "{\n  \"lumoImports\" : [ \"typography\"]\n}\n"
 },
```

Added covering tests and did manual testing as well.

Fixes # (issue)
https://github.com/vaadin/flow/issues/16419

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2023-04-28 13:57 UTC, czp13 commented
As I see it better, we need first maybe to cherry-pick this commit: 6de8705df801d29bb14cb8eb48d437366e5937d8
To have the util classes, and refactoring at first place here.

2023-05-03 07:54 UTC, mshabarov requested changes

2023-05-03 07:54 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/ThemeValidationUtilTest.java
> +public class ThemeValidationUtilTest {
These tests should go to `TaskRunDevBundleBuildTest`, because there is no `ThemeValidationUtil` in 24.0.

2023-05-03 08:28 UTC, mshabarov approved these changes

2023-05-03 09:06 UTC, merged