feat: add license check for production bundle
vaadin/flow pull request #16728
Opened 2023-05-03 08:58 UTC by caalador

Collect pro-components from stats.json
which are used in the project and check
license for those.

Closes #16720

2023-05-04 08:36 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
> +            LicenseChecker.checkLicense(component.getName(),
Can't we integrate this into the existing `validateLicenses` in `BuildFrontendUtil`? Possibly by even deleting what there currently is to find the commercial frontend dependencies

2023-05-04 11:00 UTC, mshabarov requested changes

2023-05-04 11:00 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
> +
The codes in `needsBuildProdBundle` runs for either pre-compiled and new bundle cases. The license checking mechanism should be the same as in `BuildFrontendUtil::validateLicenses`, but with one exception that it should load `cvdlName` from `node_modules` in one case and from `stats.json` in another case. Thus, I propose to move `validateLicenses(adapter);` from `BuildFrontendUtil.runFrontendBuild(this);` to this place, otherwise the license checking would happen two times when one needs to build a new bundle for production.

Also, this patch seems not checking Java Components (like Spreadsheet), but `validateLicenses` does:
```java
        List<Product> commercialComponents = findCommercialFrontendComponents(
                nodeModulesFolder, statsFile);
        commercialComponents.addAll(findCommercialJavaComponents(adapter));
```
This is another reason for moving and reusing existing method `validateLicenses` here (but with different source of cvdlName value).

2023-05-04 11:02 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
> +
Why would we not load cvdlName from stats.json in all cases?

2023-05-04 13:09 UTC, Artur- commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +            // without stats.json in bundle we can not say if it is up-to-date
When would this happen and should it be an exception?

2023-05-05 04:59 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
> +
done

2023-05-05 04:59 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
> +            LicenseChecker.checkLicense(component.getName(),
done

2023-05-05 09:08 UTC, mshabarov commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
> +            BuildFrontendUtil.validateLicenses(this);
I didn't get why you call `validateLicenses` twice.
Would it be the same result, if you do 
```java
if (generateBundle() && BundleValidationUtil
                .needsBundleBuild(servletResourceOutputDirectory())) {
           ....
 }

LicenseChecker.setStrictOffline(true);
BuildFrontendUtil.validateLicenses(this);
```
and remove the second call to `setStrictOffline` and `validateLicenses` from inside of `runFrontendBuild`?

2023-05-05 09:38 UTC, caalador commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
> +            BuildFrontendUtil.validateLicenses(this);
They are not the same as if we build/need a bundle we validate against the built bundle and if we do no build we validate against the prepackaged default bundle.

2023-05-05 10:28 UTC, mshabarov commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
> +            BuildFrontendUtil.validateLicenses(this);
No, I mean that no matter is it a new bundle or pre-compiled, you can always call `BuildFrontendUtil.validateLicenses(this);` in a way I shown above. Then this one 
```
        // Check License
        validateLicenses(adapter);
```
is not needed.

2023-05-05 10:29 UTC, mshabarov requested changes

2023-05-05 10:29 UTC, mshabarov commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
> +            BuildFrontendUtil.validateLicenses(this);
The same should be done for gradle plugin I suppose.

2023-05-05 11:04 UTC, mshabarov commented
Two observations when I tested this feature with starter project:
1. The folder with bundle is not deleted, so I still have files in `target/classes/META-INF/VAADIN/webapp/VAADIN/build` after running `build-frontend`.
2. The license is being checked even if I don't use commercial components in the project. And it happens with both `vaadin` and `vaadin-core` in my pom.xml, here is a small snipped from the logs:
```
[DEBUG] Checking license for Product [name=vaadin-board, version=24.1.0-alpha8]
[DEBUG] Online validation using proKey for Product [name=vaadin-board, version=24.1.0-alpha8]
[DEBUG] No pro key found
[DEBUG] Offline validation using offlineKey for Product [name=vaadin-board, version=24.1.0-alpha8]
[DEBUG] No offline key found
[INFO] Opening system browser to validate license. If the browser is not opened, please open .... manually
[INFO] For CI/CD build servers, you need to download a server license key, which can only be used for production builds. You can download a server license key from https://vaadin.com/myaccount/licenses.
If you are working offline in development mode, please visit .... for an offline development mode license.
[DEBUG] Polling server for pro key
[DEBUG] Polling server for pro key
[DEBUG] Writing pro key to ....
[DEBUG] Online validation using proKey for Product [name=vaadin-board, version=24.1.0-alpha8]
[DEBUG] Checking if license for Product [name=vaadin-board, version=24.1.0-alpha8] has recently been checked
[DEBUG] Last check for Product [name=vaadin-board, version=24.1.0-alpha8] was on ....
[DEBUG] Skipping check as product license was recently validated.
[DEBUG] Checking license for Product [name=vaadin-chart, version=24.1.0-alpha8]
[DEBUG] Found proKey in ....
[DEBUG] Online validation using proKey for Product [name=vaadin-chart, version=24.1.0-alpha8]
[DEBUG] Checking if license for Product [name=vaadin-chart, version=24.1.0-alpha8] has recently been checked
[DEBUG] Last check for Product [name=vaadin-chart, version=24.1.0-alpha8] was on ....
[DEBUG] Skipping check as product license was recently validated.
[DEBUG] Checking license for Product [name=vaadin-cookie-consent, version=24.1.0-alpha8]
[DEBUG] Found proKey in ....
[DEBUG] Online validation using proKey for Product [name=vaadin-cookie-consent, version=24.1.0-alpha8]
[DEBUG] Checking if license for Product [name=vaadin-cookie-consent, version=24.1.0-alpha8] has recently been checked
[DEBUG] Last check for Product [name=vaadin-cookie-consent, version=24.1.0-alpha8] was on ....
[DEBUG] Skipping check as product license was recently validated.
[DEBUG] Checking license for Product [name=vaadin-crud, version=24.1.0-alpha8]
[DEBUG] Found proKey in ....
[DEBUG] Online validation using proKey for Product [name=vaadin-crud, version=24.1.0-alpha8]
[DEBUG] Checking if license for Product [name=vaadin-crud, version=24.1.0-alpha8] has recently been checked
[DEBUG] Last check for Product [name=vaadin-crud, version=24.1.0-alpha8] was on....
[DEBUG] Skipping check as product license was recently validated.
[DEBUG] Checking license for Product [name=vaadin-grid-pro, version=24.1.0-alpha8]
[DEBUG] Found proKey in ....
[DEBUG] Online validation using proKey for Product [name=vaadin-grid-pro, version=24.1.0-alpha8]
[DEBUG] Checking if license for Product [name=vaadin-grid-pro, version=24.1.0-alpha8] has recently been checked
[DEBUG] Last check for Product [name=vaadin-grid-pro, version=24.1.0-alpha8] was on ....
[DEBUG] Skipping check as product license was recently validated.

```

2023-05-05 11:41 UTC, caalador commented
Why would build be removed if the validation didn't fail?

2023-05-05 11:45 UTC, mshabarov commented
> Why would build be removed if the validation didn't fail?

Right, my license is valid, so it signal that I don't have a pro key locally, but it doesn't throw. Forget this comment then.

2023-05-08 07:19 UTC, mshabarov commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
> -            logger.info("Not running webpack since generateBundle is false")
I suggest to preserve this log message, but to replace the webpack with Vite.

2023-05-08 07:20 UTC, mshabarov commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
> -            logger.info("Not running webpack since generateBundle is false")
Ah, this message is present only for gradle. So yeah, let's delete it or add in both plugins.

2023-05-08 07:38 UTC, mshabarov commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +            URL statsJson = adapter.getClassFinder().getResource(
I think that we should keep the old way for loading stats.json here
```java
        File statsFile = new File(adapter.servletResourceOutputDirectory(),
                Constants.VAADIN_CONFIGURATION + "/stats.json");
```
, because:
1. At this point we have either pre-compiled bundle copied from JAR or a new bundle in the same directory: `target/classes/META-INF/VAADIN/webapp` and `config`.
2. Not sure loading it from classpath with `adapter.getClassFinder().getResource()` really works here.

2023-05-08 08:09 UTC, caalador commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +            URL statsJson = adapter.getClassFinder().getResource(
Tests show that the adapter classfinder loads the resources correctly as expected, but we can have a full path also.

2023-05-08 08:13 UTC, mshabarov commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +            URL statsJson = adapter.getClassFinder().getResource(
Ok, if it works for maven and gradle, we can keep it as is.

2023-05-08 08:33 UTC, mshabarov approved these changes
Codes look good to me. I need to re-test on my side to be sure.

2023-05-08 10:08 UTC, mshabarov commented
Successfully re-tested with starter having platform `24.1.0.alpha4` and flow `24.1-SNAPSHOT` with this patch.
It adds cvdl names into `stats.json` as expected and:
1. Triggers license check if using commercial components
2. Doesn't trigger if uses only free components.

2023-05-08 10:08 UTC, mshabarov commented
Unit tests needs a mock for stats.json as now it is checked by license checker.

2023-05-08 10:57 UTC, mshabarov approved these changes

2023-05-08 10:57 UTC, mshabarov approved these changes

2023-05-08 11:31 UTC, merged