fix: Do not generate extra files
vaadin/flow pull request #16735
Opened 2023-05-04 04:56 UTC by caalador

When using the production bundle
do not generate un-needed files
for npm and vite.

Fixes #16696

2023-05-04 08:19 UTC, mshabarov requested changes

2023-05-04 08:19 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
> +                && !options.isBundleBuild();
This might be simplified a bit:
```java
boolean needsNodeModules = options.isFrontendHotdeploy() || options.isBundleBuild();
        if (!npmNotFound.isEmpty() && getLogger().isInfoEnabled()
                && needsNodeModules) {
            getLogger().info(notFoundMessage(npmNotFound,
                    "Failed to find the following imports in the `node_modules` tree:",
                    getImportsNotFoundMessage()));
        }
```

2023-05-04 08:19 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +        if ((options.isProductionMode() && options.isBundleBuild())
Can we get rid of `(options.isProductionMode() && options.isBundleBuild())` in this condition, since `isBundleBuild` is supposed to signal about making a new bundle or not, with no matter is it prod or dev mode? Some tests would be broken (they were, when I did a similar change before), but this might be a matter of wrong expectation in tests.

2023-05-04 08:19 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +                || (options.isProductionMode() && options.isBundleBuild())
Same here, can we exclude `options.isProductionMode() && options.isBundleBuild()`?

2023-05-08 06:21 UTC, mshabarov commented on flow-tests/test-express-build/test-prod-bundle-no-plugin/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/NoAppBundleIT.java
> +        } catch (NoSuchElementException e) {
This is not needed, because this test module now runs with production always, so it is never in dev mode -> no need to check this.

2023-05-08 06:21 UTC, mshabarov commented on flow-tests/test-express-build/test-prod-bundle-no-plugin/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/NoAppBundleIT.java
> +                new File(baseDir, Constants.DEV_BUNDLE_LOCATION).exists());
Also not needed, since this module runs in prod mode always.

2023-05-08 08:05 UTC, caalador commented on flow-tests/test-express-build/test-prod-bundle-no-plugin/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/NoAppBundleIT.java
> +        } catch (NoSuchElementException e) {
done

2023-05-08 08:32 UTC, merged