feat: Allow listening to additional jar-resources folders
vaadin/flow pull request #16732
Opened 2023-05-03 12:49 UTC by Artur-

This enables listening to `src/main/resources/META-INF` in another module in a multi module project so that live reload works for frontend resources

Usage:
```
vaadin.frontend.hotdeploy.dependencies=../relative-path-to-module-with-frontend-resources, ../possibly-another-module
```
in `application.properties` or as a system property

2023-05-04 08:34 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
> +    public static final String FRONTEND_HOTDEPLOY_DEPENDENCIES = "frontend.hotdeploy.dependencies";
Would that also work for the following multi-module structure?

- vaadin-theme
  - frontend/theme-name/....
  - vite config etc.
- app1
  - include vaadin-theme as dep
  - has no vite config or frontend folder
- app2
  - include vaadin-theme as dep
  - has no vite config or frontend folder
- root pom with modules vaadin-theme, app1 and app2 as module

to allow sharing the whole frontend files between multiple projects in the same multi module project without having to compile the theme multiple times? Or do you have another use-case in mind?

2023-05-04 12:31 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
> +    public static final String FRONTEND_HOTDEPLOY_DEPENDENCIES = "frontend.hotdeploy.dependencies";
It sounds like it should be possible to support a theme from another module also but the code in this PR is not enough for that

2023-05-04 12:36 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
> +    public static final String FRONTEND_HOTDEPLOY_DEPENDENCIES = "frontend.hotdeploy.dependencies";
ahh! Sounds like the use-case for add-on development. Thanks for clarification!

2023-05-08 07:48 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
> +            ExternalDependencyWatcher dependencyWatcher = new ExternalDependencyWatcher(
I will move this to `DevModeHandlerManagerImpl` to simplify a thing or two

2023-05-09 14:12 UTC, mcollovati requested changes
Tested with two modules and it works fine.
Also removing/renaming files works as expecting, with page reloads, JavaScript failures due to missing resources, and the page successfully loading once the file is moved back/recreated.
Some nits and comments

2023-05-09 14:12 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ExternalDependencyWatcher.java
> +            return;
I would add a WARN message if the folder does not exist, to simplify troubleshooting.

2023-05-09 14:12 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ExternalDependencyWatcher.java
> +                    IOUtils.copy(src, target.toFile());
Would it make sense to use JDK `Files.copy(...)` instead of the commons-io utility?

2023-05-09 15:18 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerManagerImpl.java
> +    private Set<Closeable> watchers = new HashSet<>();
Done

2023-05-09 15:21 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ExternalDependencyWatcher.java
> +            return;
That would almost always trigger one warning as there is both `frontend` and `resources/frontend` that can contain frontend files and you would have only one of them. Also in the follow up PRs, this is called more in a "watchAndCopyIfTheFolderExists` way

2023-05-09 15:22 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ExternalDependencyWatcher.java
> +                    IOUtils.copy(src, target.toFile());
Sure, if it means we can some day remove the commons-io dependency. Changed

2023-05-09 15:37 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ExternalDependencyWatcher.java
> +    private static Set<FileWatcher> watchers = new HashSet<>();
Done

2023-05-09 15:39 UTC, Artur- commented
https://github.com/vaadin/docs/issues/2412 for docs

2023-05-09 15:53 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ExternalDependencyWatcher.java
> +            return;
Got it. Maybe some helpful WARN message can be introduced in the other PR, if possible

2023-05-09 15:55 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ExternalDependencyWatcher.java
> +            return;
A WARN would certainly make sense in the case that you defined the property manually and it found no folder to listen to. Let's see if I can add that

2023-05-09 16:06 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ExternalDependencyWatcher.java
> +            return;
Perfect!

2023-05-09 16:07 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ExternalDependencyWatcher.java
> +                    hotdeployDependencies.split(","));
@Artur- it this something you will take care in this PR?

2023-05-09 16:11 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ExternalDependencyWatcher.java
> +                    hotdeployDependencies.split(","));
Seems I missed that comment, added `trim()`

2023-05-09 16:22 UTC, mcollovati commented
I just noticed a drawback using Files.copy: when editing the file in IDEA, the log gets flooded by failed copy warning messages for temporary files created by the IDE. This is a bit annoying

```
[ForkJoinPool.commonPool-worker-5] WARN com.vaadin.base.devserver.ExternalDependencyWatcher - Unable to copy modified file from /flow/flow-tests/test-live-reload-multimodule/ui/../library/src/main/resources/META-INF/frontend/in-frontend.js~ to /flow/flow-tests/test-live-reload-multimodule/ui/frontend/generated/jar-resources/in-frontend.js~
java.nio.file.NoSuchFileException: /home/marco/projects/vaadin/flow/flow/flow-tests/test-live-reload-multimodule/ui/../library/src/main/resources/META-INF/frontend/in-frontend.js~
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:548)
	at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:257)
	at java.base/java.nio.file.Files.copy(Files.java:1305)
	at com.vaadin.base.devserver.ExternalDependencyWatcher.lambda$watchAndCopy$1a23d9b4$1(ExternalDependencyWatcher.java:107)
	at com.vaadin.base.devserver.FileWatcher.lambda$new$0(FileWatcher.java:56)
	at io.methvin.watcher.DirectoryWatcher.onEvent(DirectoryWatcher.java:425)
	at io.methvin.watcher.DirectoryWatcher.runEventLoop(DirectoryWatcher.java:388)
	at io.methvin.watcher.DirectoryWatcher.lambda$watchAsync$1(DirectoryWatcher.java:232)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

2023-05-09 16:23 UTC, Artur- commented
Is that related to FIles.copy or just that I added logging of the exception, which was missing before?  We can probably safely exclude `*~` from all listeners

2023-05-09 16:24 UTC, Artur- commented
and also maybe avoid logging `NoSuchFileException`

2023-05-09 16:36 UTC, mcollovati commented
Excluding `NoSuchFileException` and files ending with `~`  seems safe to me. Good solution! :+1:

2023-05-09 16:39 UTC, mcollovati requested changes

2023-05-09 16:44 UTC, mcollovati approved these changes

2023-05-09 17:17 UTC, merged