feat: Enable custom theme for pre-compiled prod bundle
vaadin/flow pull request #16751
Opened 2023-05-05 16:27 UTC by mshabarov

Uses the same mechanism with adding style tags to `head` to style application when the pre-compiled prod bundle is used, as Flow does for dev bundle.
Copies project's custom theme files to the output folder, so they are available in the runtime in class-path.
Also loads application's theme from AppShellRegistry.

Fixes https://github.com/vaadin/flow/issues/16718

2023-05-08 09:05 UTC, Artur- requested changes

2023-05-08 09:05 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/ThemeUtils.java
> +    public static Optional<String> getThemeName(VaadinContext context,
Does it make sense to pass the config separately as you can get it using `ApplicationConfiguration.get(context)`

2023-05-08 09:05 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +                BootstrapHandler
Wouldn't this always add the stylesheet in production mode, also when a custom production bundle was built?

2023-05-08 09:05 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskPrepareProdBundle.java
> +        this.frontendDependenciesScanner = frontendDependencies;
Where is the scanner needed?

2023-05-08 09:05 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/ThemeUtils.java
> +        if (config.isProductionMode()) {
Why should the theme lookup work differently in dev and prod mode?

2023-05-08 10:01 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/ThemeUtils.java
> +        if (config.isProductionMode()) {
Because theme name is needed in runtime, and in production mode you don't know anything about project files, also don't have a generated theme file where the theme name is placed.

2023-05-08 10:03 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +                BootstrapHandler
Currently yes, and this is not correct. Should use stylesheet only for pre-compiled bundle. I'm looking for a good way to pass this info (pre-compiled bundle or custom) into runtime. Probably an extra entry in `stats.json` would work.

2023-05-08 10:06 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/ThemeUtils.java
> +        if (config.isProductionMode()) {
Yes, I think it would be better. Will fix it.

2023-05-08 11:01 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/ThemeUtils.java
> +        if (config.isProductionMode()) {
done

2023-05-08 11:01 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskPrepareProdBundle.java
> +        this.frontendDependenciesScanner = frontendDependencies;
Not needed. This was a leftover from previous versiins.

2023-05-08 11:03 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +                BootstrapHandler
Added a new entry `pre-compiled` to the stats. Not sure if we need a new enum name for pre-compiled bundle, like `Mode.PRODUCTION_PRE_COMPILED`, having also `Mode.PRODUCTION` that means custom bundle.

2023-05-08 11:04 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/ThemeUtils.java
> +            AbstractConfiguration config) throws IOException {
No. Removed.

2023-05-08 11:04 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/ThemeUtils.java
> +    public static Optional<String> getThemeName(VaadinContext context,
Extra config parameter exluded.

2023-05-09 13:55 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/ThemeUtils.java
> +        if (config.isProductionMode()) {
Reverted back the code for extracting from generated file, because frontend live reload initialiser doesn't get the theme name when trying to get it from annotation (in DevModeHandlerManagerImpl).

2023-05-10 10:49 UTC, caalador commented on flow-tests/test-express-build/pom.xml
> +                <module>test-parent-theme-express-build/pom-prod.xml</module>
Is there any other wat o actually have the same sources for multiple different modules?
Here also both poms should start with cleaning any generated files so that for instance the production doesn't by mistake use dev files and vice versa.
Also this makes at least idea have bad module handling (could be other ides also, but I don't use any other at the moment)

2023-05-10 10:49 UTC, caalador commented on flow-tests/test-express-build/test-parent-theme-express-build/src/test/java/com/vaadin/flow/devbuild/ParentThemeIT.java
> +            // ignore in prod mode
The need for these not in X mode would warrant having own modules for prod and dev modes.

2023-05-10 11:08 UTC, mshabarov commented on flow-tests/test-express-build/test-parent-theme-express-build/src/test/java/com/vaadin/flow/devbuild/ParentThemeIT.java
> +            // ignore in prod mode
It's better to make its own modules and codes for prod mode. Taking into account possible additions in the future, I think this would be a better way. Will fix.

2023-05-10 12:37 UTC, mshabarov commented on flow-tests/test-express-build/test-parent-theme-express-build/src/test/java/com/vaadin/flow/devbuild/ParentThemeIT.java
> +            // ignore in prod mode
done

2023-05-11 05:14 UTC, caalador approved these changes

2023-05-11 06:49 UTC, Artur- requested changes

2023-05-11 06:49 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleUtils.java
> +    public static boolean isPreCompiledBundle() {
```suggestion
    public static boolean isPreCompiledProductionBundle() {
```

2023-05-11 06:49 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleUtils.java
> +    public static boolean isPreCompiledBundle() {
```suggestion
    public static boolean isPreCompiledProductionBundle() {
```

or is this also for dev bundle?

2023-05-11 06:49 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskPrepareProdBundle.java
> +        if (index >= 0) {
So if the path to statsJson does not contain `.jar!/` then stats.json is the jar?

Seems like this code has not changed though..

2023-05-11 06:49 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskPrepareProdBundle.java
> +            throw new RuntimeException(e);
Why `RuntimeException` when the the method below throws `ExecutionFailedException`?

2023-05-11 06:49 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/ThemeUtils.java
> +        if (config.isProductionMode()) {
Why doesn't it get it?

2023-05-11 06:49 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/ThemeUtils.java
> +    public static Optional<JsonObject> getThemeJson(String themeName,
Looks like you are leaking `Options` outside node tasks. Pass the frontend directory instead

2023-05-11 06:49 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
> +        URL resourceUrl = ThemeUtils.getThemeResourceFromBundle(assetPath);
Maybe `getThemeResourceFromBundle` and `getThemeResourceFromJar` should be combined into `getThemeResourceFromPrecompiledProductionBundle`?

2023-05-11 12:40 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
> +                || (config.getMode() == Mode.PRODUCTION
Good idea! Done

2023-05-11 12:43 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
> +            resourceUrl = findAssetInProdBundleOrClassPath(filenameWithPath
The themes located in the project frontend are copied to the same `VAADIN/static/themes` directory as it's done with the Vite application theme plugin. Should work, but not tested. I also aligned the copy logic with the plugin to take `webappResourcesDirectory` parameter into account.

2023-05-11 12:43 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleUtils.java
> +    public static boolean isPreCompiledBundle() {
Done

2023-05-11 12:44 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleUtils.java
> +    public static boolean isPreCompiledBundle() {
Done

2023-05-11 12:44 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskPrepareProdBundle.java
> +            throw new RuntimeException(e);
Replaced by EFE

2023-05-11 12:44 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
> +        URL resourceUrl = ThemeUtils.getThemeResourceFromBundle(assetPath);
Done

2023-05-12 07:25 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskPrepareProdBundle.java
> +        if (index >= 0) {
The expectation is always have stats.json in the JAR always at this point of app execution.
So maybe we should `assert` instead of `if()`

2023-05-12 08:16 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/ThemeUtils.java
> +        if (config.isProductionMode()) {
I'm not sure why. If I run in debug mode and stop at the point when DevModeHandlerManager tries to fetch the themes, I see that the annotation way works and then after app start-up the live reload also works. If I run without dubugging, I always get it not working.
Thus, I suspect this is a timing issue when it's fetched from annotation, because dev server starts in parallel with the servlet initialisation and we may not have the theme information available sometimes.

2023-05-12 08:17 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/ThemeUtils.java
> +        if (config.isProductionMode()) {
ok so it could be improved in a separate PR at some point

2023-05-12 09:52 UTC, mshabarov commented
I made an issue about static resource here https://github.com/vaadin/flow/issues/16780 . So propose to fix it in a separate patch.

2023-05-12 10:08 UTC, Artur- approved these changes

2023-05-12 10:41 UTC, merged