fix: not require stats.json output when generateBundle is disabled
vaadin/flow pull request #16766
Opened 2023-05-10 14:30 UTC by platosha

Fixes #16763

2023-05-10 15:47 UTC, czp13 commented
I might be wrong, but `BuildFrontendMojo/VaadinBuildFrontendTask.kt` is for the build-frontend goal (maven/gradle), and with this change, the license check will only be executed if the bundle creation is on/happening:
``` 
    /**
     * Whether to generate a bundle from the project frontend sources or not.
     */
    @Parameter(defaultValue = "true")
    private boolean generateBundle;
```

The license check was put under this condition:
```
        if (generateBundle()) {
....
}
 ```
 
I would think a license check shall happen every time, not just related to bundle creation, so every time a frontend build is happening ` BuildFrontendUtil.runNodeUpdater(this);` the license check shall run, so the original condition, execution chain was good imho.

I think another change or refactor is needed to achieve/surpass this error: `No production bundle stats.json available.`. 
But I would need to test and debug it to see exactly what changes. 

I can test this theory (license check is not happening if the bundle is not created) if no one reviews, and confirms it soonish, this week.

2023-05-10 15:49 UTC, czp13 requested changes
It would be good to have some covering tests for the changed logic (now the relevant part was just deleted). 

And manually test through some cases (bundle creation is needed, or not, and if there was already a created bundle or not)

2023-05-11 03:48 UTC, caalador requested changes
This change is not ok as the license should be checked in all cases. There is a default bundle that is pacakged with the `vaadin-maven-plugin` that can always be checked against even when generate bundle is false.

This will need another type of fix which we need to ponder about for a bit @mshabarov

2023-05-11 04:57 UTC, caalador commented
Actually it should be changed as artur noted to what it was here in the before https://github.com/vaadin/flow/pull/16728/commits/a7245c2818d5693a162f5c6e68b1f21b122753c8

2023-05-11 05:54 UTC, mshabarov approved these changes
Looks good to me, so if no bundle generated/copied then nothing to check.

2023-05-11 05:54 UTC, mshabarov commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +            getLogger().debug("No production bundle stats.json available.");
```suggestion
            getLogger().debug("No production bundle stats.json available for licenses validation.");
```

2023-05-11 06:42 UTC, czp13 approved these changes
I think with @caalador changes this seems good!
Only thing missing is test case when `statJson={}`, but I can approve to not block it if we feel like.

2023-05-11 06:43 UTC, czp13 commented on flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
Should we put this back as the original change was reverted as I see?:
```suggestion

        File statsfile = new File(resourceOutputDirectory,
                Constants.VAADIN_CONFIGURATION + "/stats.json");

        statsfile.getParentFile().mkdirs();
        FileUtils.fileWrite(statsfile, "UTF-8", "{}");
```

2023-05-11 06:51 UTC, Artur- approved these changes

2023-05-11 07:16 UTC, Artur- commented on flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
It should not be needed now that `{}` is used when stats.json is not found

2023-05-11 07:17 UTC, merged

2023-05-11 07:43 UTC, czp13 commented on flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
yes, correct, I was on autopilot, morning coffee needs before reviews!