chore: add owner to JavaScriptInvocation class.
vaadin/flow pull request #16834
Opened 2023-05-19 14:35 UTC by czp13

## Description

Adding owner to JavaScriptInvocation class.

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2023-05-22 07:48 UTC, mcollovati reviewed
The change looks good to me.
I just wonder if we should preserve and deprecate the previous `JavaScriptInvocation` constructor, to avoid breaking changes, since this is a public API.

Waiting @mshabarov considerations

2023-05-22 10:27 UTC, mshabarov requested changes
I agree that @mcollovati said: let's preserve the existing API as is, but deprecate it and add a new constructor. Also, since it is possible to construct the invocation without the owner, let's highlight it in the getter's javadoc, that owner can be `null`.

2023-05-23 13:27 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/dom/Element.java
> +        ui.getInternals().addJavaScriptInvocation(invocation);
Isn't this causing the execution to be sent twice to the client?

2023-05-24 10:02 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
>          return ui.getInternals().addJavaScriptInvocation(invocation);
Thanks for the further review, it makes perfect sense. I also was thinking about that rapidly yesterday to avoid code duplication, but at that point I though it is more complicated or produce not nice code, but after did it, it seems way more clean.

Done 👍

2023-05-24 10:02 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/dom/Element.java
> +                            + paramPlaceholderString + ")", getNode(),  jsParameters);
I did not catch this one but now fixed this as well. Thanks for noticing it!

2023-05-24 10:03 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
> +    public ExecutionCanceler executeJavaScript(String expression, StateNode owner,
I don't understand why one needs an owner node to run the JS on the Page? The owner here is always a root node, or I missed something?

2023-05-24 10:15 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/dom/Element.java
> +                            .concat(Stream.of(node), Stream.of(arguments))
this seems to be wrong. `this` is not the `Element` instance, not the `StateNode`.
My bad, I didn't notice that capture of `this`, so using `getNode()` is fine.
I apologize for the mistake

2023-05-24 10:17 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/dom/Element.java
> +                            + paramPlaceholderString + ")", node,  jsParameters);
And if we want to preserve the parameters type check, we can probably just add a `.peek(JsonCodec::encodeWithTypeInfo)` to the `jsParameters` stream flow.

2023-05-24 10:18 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +            this.owner = new StateNode();
I propose to assign a root node to the owner here.

2023-05-24 10:44 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
> +    public ExecutionCanceler executeJavaScript(String expression, StateNode owner,
This will be deleted as discussed. Thanks!

2023-05-24 10:44 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/dom/Element.java
> +                            .concat(Stream.of(node), Stream.of(arguments))
Okey, yap, indeed, fixing it! Thanks!

2023-05-24 10:51 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/dom/Element.java
> +                            + paramPlaceholderString + ")", node,  jsParameters);
Refactored, changed. Thanks for review ✅

2023-05-24 11:59 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +            this.owner = new StateNode();
As discussed internally, it will be null and Optional used for the getter return value!

2023-05-24 12:00 UTC, mshabarov submitted a review, later dismissed

2023-05-24 12:07 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +         * @return the owner state node
nit:
```suggestion
         * Gets the state node that this invocation belongs to, if any.
         *
         * @return the optional owner state node, or an empty optional if no state node has been provided for this invocation.
```

2023-05-24 12:14 UTC, mshabarov approved these changes

2023-05-24 12:15 UTC, mcollovati approved these changes

2023-05-24 12:22 UTC, merged