chore:disable sending updates to client for effectively non-visible nodes (#15885) (CP: 1.0)
vaadin/flow pull request #16875
Opened 2023-05-24 13:57 UTC by czp13

## Description
Manually cherry-picked #15885 PR for 1.0:
- Disable sending updates to client for effectively non-visible nodes
- Fix test: Always set tested component visible first; only assume node has changed if testvalue differs from original value
- Cleanup, and refactoring, in Element, StateNode, UIInternals classes + mvn formatter.

2023-05-24 14:01 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +//                .peek(JavaScriptInvocation::setSentToBrowser)
The only difference between the original and cherry-picked commit, this part can be deleted as this concept does not exist in `1.0` and is not used anywhere else in `1.0`. 

TLDR: So it is safe to delete the setting part (as getting, or using is not existing)

2023-05-24 14:08 UTC, mcollovati commented
I think this manual cherry pick should also consider changes in #16836 and #16855

2023-05-24 14:13 UTC, mshabarov requested changes

2023-05-24 14:13 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +                .filter(invocation -> invocation.getOwner().isPresent() && invocation.getOwner().get().isVisible())
Invocations that have no owners are ready to be send as well - we assume they are for root node, i.e. always visible.

2023-05-24 14:13 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +                .filter(invocation -> !(invocation.getOwner().isPresent() && invocation.getOwner().get().isVisible()))
Same here: this filter condition needs change, because JS invocations for root node would be pending forever.

2023-05-24 14:15 UTC, mshabarov commented
> @mcollovati: I was thinking about merging this one soon.
> 
> And then merge the mentioned two commits together as the third (#16855) fix is a small one, but the second fix/CP (#16836) is quite big and building on top of this. It could be nice for historical reasons, reverting, git tree history to unite the PR-s, and commits like this.
> 
> p.s: but if you feel, I can add those ones to here 🙇

You can add the commits to this branch, but then do "Rebase & Merge", not "Squash" and they will be preserved in history.

2023-05-24 14:28 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +                             .equals(invocation))));
the `node` param in the lambda is already `invocation.getOwner().get()`
```suggestion
      invocation.getOwner().ifPresent(node -> 
              node.addDetachListener(() -> pendingJsInvocations
                     .removeIf(pendingInvocation -> pendingInvocation
                             .equals(invocation))));
```

2023-05-24 14:32 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +                             .equals(invocation))));
Good one, shorter code is usually better. The only reason I do not commit this is I want to have only one commit for this change, then another commit for the other CP-s, to not push like 5-10 commits to the branch. 

So I squash logically related commits together.

2023-05-24 14:33 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +                .filter(invocation -> invocation.getOwner().isPresent() && invocation.getOwner().get().isVisible())
Thanks, fixed!

2023-05-24 14:42 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +                .filter(invocation -> invocation.getOwner().isEmpty() || invocation.getOwner().get().isVisible())
```suggestion
                .filter(invocation -> invocation.getOwner().map(StateNode::isVisible).orElse(true))
```

2023-05-24 15:32 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +                .filter(invocation -> invocation.getOwner().isEmpty() || invocation.getOwner().get().isVisible())
Thanks, changed to negated isPresent() shall be the same.

2023-05-24 15:32 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +                .filter(invocation -> invocation.getOwner().isEmpty() || invocation.getOwner().get().isVisible())
This is good :), I've double-checked.

2023-05-24 15:58 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +                .filter(invocation -> invocation.getOwner().isPresent() && !invocation.getOwner().get().isVisible())
Ok, this seems the same by eye checks. 

Asked my bot friend, who said it is different, then I executed this code for test:

```

import lombok.Data;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

public class InvocationLogicTest {

    @Data
    static class Owner {
        private boolean isVisible;

        public Owner(boolean isVisible) {
            this.isVisible = isVisible;
        }

        public boolean isVisible() {
            return isVisible;
        }
    }

    @Data
    static class Invocation {
        private Owner owner;

        public Invocation(Owner owner) {
            this.owner = owner;
        }

        public Invocation() {
        }

        public Optional<Owner> getOwner() {
            return owner == null ? Optional.empty() : Optional.of(owner);
        }
    }

    public static void main(String[] args) {
        List<Invocation> invocations = List.of(
                new Invocation(new Owner(true)),
                new Invocation(),
                new Invocation(new Owner(false))
        );


        System.out.println("Logic for: invocations.stream().filter(invocation -> invocation.getOwner().isPresent() && !invocation.getOwner().get().isVisible()).collect(Collectors.toList())");
        List<Invocation> filteredList1 = invocations.stream()
                .filter(invocation -> invocation.getOwner().isPresent() && !invocation.getOwner().get().isVisible())
                .collect(Collectors.toList());

        System.out.println(filteredList1.size());  // Output: 1
        System.out.println(filteredList1.get(0) == invocations.get(2));  // Output: true
        System.out.println(filteredList1.get(0));

        System.out.println("Logic for: invocations.stream().filter(invocation -> invocation.getOwner().map(node -> !node.isVisible()).orElse(false)).collect(Collectors.toList())");
        List<Invocation> filteredList2 = invocations.stream()
                .filter(invocation -> invocation.getOwner().map(node -> !node.isVisible()).orElse(false))
                .collect(Collectors.toList());

        System.out.println(filteredList2.size());  // Output: 2
        System.out.println(filteredList2.get(0) == invocations.get(2));  // Output: true
        System.out.println(filteredList2.get(0));


    }

}

```

It showed this output:
```
Logic for: invocations.stream().filter(invocation -> invocation.getOwner().isPresent() && !invocation.getOwner().get().isVisible()).collect(Collectors.toList())
1
true
InvocationLogicTest.Invocation(owner=Optional[InvocationLogicTest.Owner(isVisible=false)])
Logic for: invocations.stream().filter(invocation -> invocation.getOwner().map(node -> !node.isVisible()).orElse(false)).collect(Collectors.toList())
1
true
InvocationLogicTest.Invocation(owner=Optional[InvocationLogicTest.Owner(isVisible=false)])
```

2023-05-24 15:59 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +                .filter(invocation -> invocation.getOwner().isPresent() && !invocation.getOwner().get().isVisible())
And then my bot friend asked for an excuse:

```
Apologies for the confusion caused by the previous response. Upon reviewing the code snippets, I realize that I made an error in explaining the difference. I apologize for any inconvenience caused.

In the given code snippets:

.filter(invocation -> invocation.getOwner().isPresent() && !invocation.getOwner().get().isVisible())
.filter(invocation -> invocation.getOwner().map(node -> !node.isVisible()).orElse(false))
Both snippets will produce the same output and behave identically in terms of filtering the invocations.

To clarify, in the second snippet, when invocation.getOwner() returns an empty optional (Optional.empty()), the map function will not be executed, and the orElse(false) part will immediately provide the default value of false. This means that invocations without an owner will be filtered out in both cases.

I apologize for the incorrect explanation in the previous response. Thank you for pointing it out, and I appreciate your understanding.
```

You can never believe anyone, even if it is a bot. Maybe too much effort but was interesting, I will push your suggestion because it was overtested as well.

2023-05-24 16:01 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +                .filter(invocation -> invocation.getOwner().isPresent() && !invocation.getOwner().get().isVisible())
Oh, yeah, and first it said it is different the 3 cases (he accidentally shown 4 cases, because duplicated one).

2023-05-24 17:28 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +import java.util.*;
I will fix this, accidentally united.

2023-05-24 18:10 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +            ownerNode = ui.getInternals().getStateTree().getRootNode();
Thinking it through:
1. if `invocation.getOwner()` is somehow is null should be equal with `getInternals().getStateTree().getRootNode()` (as we discussed before)
2. also the `registerDetachListenerForPendingInvocation` method should be called with the filled-out owner (and not visible rootnode) based on the 568. line logic

So I can remove those comments.

2023-05-24 21:11 UTC, czp13 commented on flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
> +//        invocation.cancelExecution();
no `cancelExecution`, nor `completeExceptionally`, `complete` methods are implemented for JavaScriptInvocation so I think this test can be deleted. (manipulating and setting up successHandler and errorHandler, which is also missing from this codebase)

2023-05-25 07:02 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +        // invocation.then(callback, callback);
`invocation.then` is the last method that is missing, but also related to `successHandler()` and `errorHandler()`, did not go that deep to see how much effort would be to add these to the code base in a separate PR.

2023-05-25 08:18 UTC, mcollovati requested changes

2023-05-25 08:18 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/shared/Registration.java
> +    }
Probably it does not make sense to add this new API, that will be used only in one place.
It should be easy to apply this logic in the caller.

2023-05-25 08:18 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +        // invocation.then(callback, callback);
Instead of adding the missing APIs, I wonder if we can simply call `onInvocationCompleted` in `dumpPendingJavaScriptInvocations`  for every invocation that will be sent to the browser (`readyToSend` list).
In this case, I would rename `onInvocationCompleted` to something that better explains that we are removing the detach listener because the invocation will be sent to the client and executed.
@mshabarov what do you think?

2023-05-25 09:08 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/shared/Registration.java
> +    }
Thanks Marco! 
My idea was that:
- this is a nice addition/improvement to the codebase, so it was a low hanging fruit, 
- and maybe also next time we will need it, we can find it here, but if it is a private method or part of a method then we will duplicate the code.

If you still feel I can refactor this part and do as you wish! 🙇

2023-05-25 09:09 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +        // invocation.then(callback, callback);
Thanks! Interesting idea,  I will wait for @mshabarov's thoughts on this, then I can check and do the necessary changes. 🙇

2023-05-25 09:21 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/shared/Registration.java
> +    }
My opinion is that we should not be ad new features to 1.0 if not strictly necessary.
In addition, if you want to peek at this a public API you should also port/implement related tests

2023-05-25 09:48 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/shared/Registration.java
> +    }
Adding tests, a very fair point! 👍  I have no problem adding more tests, other than the PR starting to be quite big and making it hard to review it properly (so maybe a separate PR would have been the best solution if we want to add it).

Adding new features to 1.0, but with this you bought me :D, indeed this branch should be just for security fixes, and absolutely necessary commits, and so not much point to add new API-s to it, as probably we will not use it, so yap, let's go with your approach.

2023-05-25 11:21 UTC, mcollovati requested changes

2023-05-25 11:21 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
>                              node.addDetachListener(detachListener));
I would remove the `combine` method, as it introduces a lot of overhead for a single call (e.g, creating `List`s, as it expects potentially more than one registration)
Instead, I would simply create a lambda here

```suggestion
                    Registration registration = node.addDetachListener(detachListener);
                    detachListener.registration = () -> {
                        pendingJsInvocationDetachListeners.remove(node);
                        registration.remove();
                    };
```

2023-05-25 11:23 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +                    return detachListener;
I would remove the combine method, as it introduces a lot of overhead for a single call (e.g, creating Lists, as it expects potentially more than one registration)
Instead, I would simply create a lambda here
```suggestion
                    Registration registration = node.addDetachListener(detachListener);
                    detachListener.registration = () -> {
                        pendingJsInvocationDetachListeners.remove(node);
                        registration.remove();
                    };
```

(Sorry for duplicate, I messed up with comments)

2023-05-25 12:10 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +        // invocation.then(callback, callback);
I agree with this approach, but how can you retrieve `JavaScriptInvocationDetachListener` for `readyToSend` invocations? You need this listener to get the registration to call remove on it.

Ah...you already have a map with node vs listener. Let do it then.

2023-05-25 13:24 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +                    return detachListener;
Thank you vm, makes sense, cleaner! Fixed it, but I could not accept the suggestion (will squash all last commits also no worries), because  `return detachListener;` was needed still.

2023-05-25 14:59 UTC, mcollovati requested changes

2023-05-25 14:59 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +                        .forEach(listener -> listener.removePendingInvocation(invocation)));
It seems a bit complicated to me. Also, it should call `listener.onInvocationCompleted()` instead of `listener.removePendingInvocation()` otherwise the invocation will not be removed from the `JavaScriptInvocationDetachListener`

And as commented before, method `onInvocationCompleted` should be renamed with something more related to the context where it is applied in this PR

```suggestion
        StateNode rootNode = ui.getInternals().getStateTree().getRootNode();
        readyToSend.forEach(i -> {
            JavaScriptInvocationDetachListener listener = pendingJsInvocationDetachListeners.get(i.getOwner().orElse(rootNode));
            if (listener != null) {
                listener.onInvocationCompleted(i);
            }
        });
```

2023-05-25 16:10 UTC, mcollovati approved these changes

2023-05-25 16:34 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +        void removePendingStatusAndRegistrationAndDetachListener(JavaScriptInvocation invocation) {
Super! Thank you! 🎉 
Yes, not the best, I agree, but if the scope is narrower then the name can be longer, based on Uncle Bob clean coding paradigm :), so that is why I was brave enough to make it longer. (https://bpoplauschi.github.io/2021/01/30/Clean-Code-Naming-by-Uncle-Bob-part-3.html)

I will squash the commits and then we can merge! 🙇

2023-05-25 16:38 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +        void removePendingStatusAndRegistrationAndDetachListener(JavaScriptInvocation invocation) {
Let's also wait for @mshabarov

2023-05-25 16:40 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +        void removePendingStatusAndRegistrationAndDetachListener(JavaScriptInvocation invocation) {
Oki, sure. I squashed the commits for clearer `rebase and merge`.

2023-05-26 06:22 UTC, mshabarov approved these changes

2023-05-26 06:23 UTC, mshabarov commented
@mcollovati if you have no comments, we can merge. @czp13 excellent job 👍

2023-05-26 06:26 UTC, mcollovati approved these changes
LGTM. @czp13 great job

2023-05-26 06:27 UTC, merged

2023-05-26 06:44 UTC, czp13 commented
Thank you very much for the constant reviews and ideas for both of you! 🙇