Use SDK http client instead of a separate http-client dependency
vaadin/flow pull request #16897
Opened 2023-05-26 14:40 UTC by mstahv

Less dependencies that might cause conflicts in user projects

Fixes #14538

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2023-06-05 10:13 UTC, mcollovati requested changes
Some minor changes.
The hard-coded timeout settings are a bit opinionated.
It would be good to make them configurable.
Maybe trying to get the value from system properties, otherwise fallback to default?

2023-06-05 10:13 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/StatisticsSender.java
> +            HttpResponse<String> r = client.send(request,
nit: can we rename the variable to 'response' or something similar?

2023-06-05 10:13 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/StatisticsSender.java
> +            getLogger().debug("Failed to send statistics.", ex);
Interrupt flag should probably be reset when catching `InterruptedException`

`Thread.currentThread().interrupt();`

2023-06-05 10:44 UTC, mstahv commented
@mcollovati timeouts were opinionated indeed, copied from some tutorial 😂 I removed them now, going with defaults would be fine I guess? Or were those configurable in the past 🤔

2023-06-05 12:05 UTC, mcollovati commented
I was thinking they were configurable through system properties, as the client builder had `useSystemProperties()` setting.
But it seems like there are no properties for the timeouts in httpclient.
So removing them from the PR could be fine.

2023-06-05 12:19 UTC, mstahv commented
👌 That was done in https://github.com/vaadin/flow/pull/16897/commits/9becd05f08c1509ea97d11f2823c807e74ef4488

2023-06-05 13:31 UTC, mcollovati commented
And this could be interesting to set up tests with proxy: https://github.com/pan-dora/jdk11-httpclient-tests/blob/master/httpclient/src/test/java/net/httpclient/ProxyAuthTest.java

2023-06-05 14:33 UTC, knoobie commented
> Another suggested workaround is to set the Proxy-Authorization header in the request.

keep in mind this old security fix :) https://github.com/apache/httpcomponents-client/commit/a572756592c969affd0ce87885724e74839176fb

2023-06-05 17:13 UTC, mstahv commented
Would be great if we'd know if and how developers use proxies 😬 Building extensive integration tests for this is probably not worth the investement but some smaller smoke test would be great.

2023-06-06 05:24 UTC, mcollovati commented
I propose not adding custom code for handling proxy authentication, but instead updating the documentation at https://vaadin.com/docs/latest/configuration/development-mode/node-js#proxy-settings-for-downloading-the-front-end-toolchain to suggest setting the `-Djdk.http.auth.tunneling.disabledSchemes` if needed

2023-06-06 10:23 UTC, mcollovati approved these changes

2023-06-06 11:42 UTC, mcollovati commented
Created vaadin/docs#2475 and #16966

2023-06-07 08:24 UTC, mcollovati approved these changes

2023-06-08 11:06 UTC, merged

2023-09-19 13:11 UTC, platosha commented
Would it be feasible to backport this to 24.1? Hilla native compilation is broken by httpclient dependency that brings `commons-logging`, this would help.