feat: Added shorthands for QueryParameters class
vaadin/flow pull request #16977
Opened 2023-06-07 08:03 UTC by mstahv

Closes #16975

2023-06-07 08:17 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +    public String getSingleParameter(String key) {
Another overload with (String key, String default) or (String key, T default)? (I personally hate exceptions and prefer default values)

2023-06-07 08:20 UTC, mstahv commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +    public String getSingleParameter(String key) {
Or should this actually return Optional, although you know my generic attitude against them ;-)

2023-06-07 08:25 UTC, mstahv commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +    public String getSingleParameter(String key) {
Now returns Optional so you ought to be able to provide the default value to the chain. Open for other options still as well.

2023-06-07 08:29 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +    public String getSingleParameter(String key) {
I prefer overloaded methods more but that's also a personal taste :) Thanks for the change!

2023-06-08 11:26 UTC, mcollovati requested changes

2023-06-08 11:26 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +        }
Can this method be rewritten to avoid using exceptions for its logic?
Something like
```suggestion
        parameters.getOrDefault(key, Collections.emptyList()).stream().findFirst()
```
Or just get the parameter and check for null and empty

2023-06-08 11:26 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +    public List<String> getParameter(String key) {
I wonder if an empty list could be better when there are no parameters

2023-06-08 11:38 UTC, mstahv commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +    public List<String> getParameter(String key) {
Done, also changed the previous suggestion now compiles. Maybe I'll write quick smoke tests for the shorthands still.

2023-06-08 11:43 UTC, mstahv commented
Went and renamed the other method while doing smoke tests :-)

2023-06-08 11:59 UTC, mcollovati requested changes

2023-06-08 11:59 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +     * @return query parameters or null if there are no parameters with the
```suggestion
     * @return query parameters or an empty list if there are no parameters with the
```

2023-06-08 11:59 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
> +     * @return query parameter value
```suggestion
     * @return query parameter value or empty if there are no parameters
     *               with the given key
```

2023-06-08 11:59 UTC, mcollovati commented on flow-server/src/test/java/com/vaadin/flow/router/QueryParametersTest.java
> +    }
Could you also add an assertion for getting an empty list for `getParameters("bar")`?

2023-06-09 05:06 UTC, mcollovati approved these changes

2023-06-09 07:03 UTC, merged

2023-09-14 10:52 UTC, knoobie commented
@mstahv Just came across this in V24.1 again because I needed them.. What would you think about a method 

`public boolean contains(String key, String value)` which you can easily call like so:

```java
  if(event.getLocation().getQueryParameters().contains("action", "lorem")) {
    // do stuff because the query contains  /blub?action=lorem
  }
  

```

2023-09-20 10:02 UTC, mstahv commented
Do you actually have multiple action parameters? If not, wouldn't that be then the same as:

```
event.getLocation().getQueryParameters().getSingleParameter("action").get().equals("lorem")
```

Decent, but those damn optionals :-)

2023-09-20 10:18 UTC, knoobie commented
Optionals 👎  and this would break, because the action parameter is optional, therefore calling get() on an empty optional would throw (and I dislike throwing even more than optionals)

2023-09-20 10:35 UTC, mstahv commented
I already wrote that and a test, but not sure if I should make the PR. Noticed that there is is getParameters(String), that always returns a List. So this should work:

```
event.getLocation().getQueryParameters().getParameters("foo").contains("bar")
```

More readable and almost as compact 🤔

2023-09-20 10:53 UTC, knoobie commented
Oh, that overload isn't available in 24.1 :) I'm probably fine with that :)

2023-09-20 10:56 UTC, mstahv commented
Added in this PR, coming soon in 24.2😎