feat: web push API
vaadin/flow pull request #16994
Opened 2023-06-09 08:30 UTC by caalador

Add API to use initialize web push on the client from the server.

Related-to https://github.com/vaadin/platform/issues/4037

Fixes https://github.com/vaadin/flow/issues/14606

2023-06-15 10:53 UTC, mshabarov commented
`WebPush` can be created explicitly as `WebPush webPush = new WebPush(keys)` and then for DI frameworks it can be made as a singleton managed bean, e.g. for Spring:

```java
    @Bean(name = "WebPush")
    public WebPush getWebPush() { 
        // keys are injected with AtValue
        return new WebPush(keys);
    }
```

2023-06-15 14:12 UTC, mshabarov commented
Pushed an extension for `WebPushRegistration` regarding sending notifications.

Also updated base web push example here https://gitlab.vaadin.com/flow/base-webpush/-/tree/send-notification-api?ref_type=heads to showcase the API.

2023-06-16 08:12 UTC, mshabarov reviewed
Have some further suggestions, let's discuss.

2023-06-16 08:12 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/webpush/WebPushRegistration.java
> +    public abstract void sendNotification(
We can create an entity class for message (restricted to only title and body at this point) and give it as a parameter here instead. WDYT?

2023-06-16 08:16 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/PwaIcon.java
> +import java.awt.*;
fixed.
Issue of new IDE with wrong settings.

2023-06-16 08:16 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/PwaIcon.java
> +    private BufferedImage drawIconImage(BufferedImage baseImage) {
it fixes the slowness of adding PWA as it generated on start all images and now we only generate images on request instead.

2023-06-16 08:17 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/PwaIcon.java
> +    private BufferedImage drawIconImage(BufferedImage baseImage) {
see 14606

2023-06-16 08:19 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/PwaIcon.java
> +    private BufferedImage drawIconImage(BufferedImage baseImage) {
Thanks, good to have it. We can reference this issue in the commit description.

2023-06-16 09:25 UTC, mshabarov commented
Looking into possible further improvements of Web Push API (outside of this pull request), I made a short analysis of what we might need in the future:

- Notifications might have a link to give users opportunity to navigate to a particular page/content on the web site/mobile app relevant to this notification, so when the user clicks on the notification, browser redirects to a page containing relevant content.
    - discussed here https://stackoverflow.com/questions/43986805/open-a-custom-url-when-clicking-on-a-web-push-notification, need a new parameter for link in the message object passed to `sendNotification` method.

- Updating or removing pending notifications, so that user can see one notification with: "You have 3 unread messages". The ability to replace a notification: replace "You have 3 unread messages" with "You have 7 unread messages" instead of adding a new notification for each message.
    - doesn't need a new Java API, but could be an implementation change

- Dropdown component shown on the notification body with customisable list of clickable links.
    - Java API needs a parameter containing a list of links

- API for seeing whether sending notification is available for the user (feature detection in browsers, allowed or blocked by user)
    - add a new Java API (methods) implementing calls to JavaScript permission API, see https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API

- The ability to clear the pending notifications in browser
    - add a new Java API (method) implementing call to a JavaScript `close` method, see https://developer.mozilla.org/en-US/docs/Web/API/Notification/close

So it seems like we'll need a new methods in `WebPushRegistration` or new fields in the `Message` object, and this can be added iteratively.

2023-06-16 09:33 UTC, caalador commented
Permission check is avaliable in the registration script, but doesn't have a server method.

2023-06-16 09:57 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/webpush/WebPushRegistration.java
> +    public static class WebPushSubscription {
done

2023-06-16 11:17 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/webpush/WebPushRegistration.java
> +    public abstract void sendNotification(
Added

2023-06-16 11:17 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/webpush/WebPushRegistration.java
> + * subscription data on the server for pushing notifications.
Added

2023-06-16 12:01 UTC, mshabarov commented
This is how the Web Push API looks like now:

WebPush service implementation:
```java
@Service
@ApplicationScope
public class WebPushService extends WebPushRegistration {

    private final PushService pushService;

    private final Map<String, WebPushSubscription> endpointToSubscription =
            new HashMap<>();

    /**
     * Create new WebPushRegistration for given publicKey.
     *
     * @param publicKey public key to use for web push
     */
    public WebPushService(@Value("${public.key}") String publicKey,
                          @Value("${private.key}") String privateKey,
                          @Value("${subject}") String subject) throws WebPushException {
        super(publicKey);
        Security.addProvider(new BouncyCastleProvider());
        // Initialize push service with the public key, private key and subject
        try {
            pushService = new PushService(publicKey, privateKey, subject);
        } catch (GeneralSecurityException e) {
            throw new WebPushException("Failed to initialise push service", e);
        }
    }

    @Override
    public void sendNotification(WebPushSubscription subscription,
                                 WebPushMessage message) throws WebPushException {
        try {
            Subscription pushServiceSubscription = new Subscription(
                    subscription.getEndpoint(),
                    new Subscription.Keys(subscription.getP256dh(),
                            subscription.getAuth()));
            pushService.send(new Notification(pushServiceSubscription,
                            message.toJson()));
        } catch (GeneralSecurityException | IOException | JoseException | ExecutionException
                 | InterruptedException e) {
            throw new WebPushException("Failed to send a message", e);
        }
    }

    public void subscribe(UI ui) {
        subscribeWebPush(ui, subscription -> endpointToSubscription.put(
                subscription.getEndpoint(), subscription));
    }

    public void unsubscribe(UI ui) {
        unsubscribeWebPush(ui, subscription -> endpointToSubscription.remove(
                subscription.getEndpoint()));
    }

    /**
     * Send a notification to all subscriptions.
     *
     * @param message web push message with title and body
     */
    public void notifyAll(WebPushMessage message) {
        endpointToSubscription.values().forEach(subscription -> {
            try {
                sendNotification(subscription, message);
            } catch (WebPushException e) {
                getLogger().error("Failed to send a message", e);
            }
        });
    }

    private Logger getLogger() {
        return LoggerFactory.getLogger(WebPushService.class);
    }

}
```

User's view
```java
@Route(value = "user", layout = MainLayout.class)
public class UserView extends VerticalLayout {

    private final Checkbox toggle;

    private final WebPushService webPushService;

    public HelloWorldView(WebPushService webPushService) {
        Paragraph paragraph = new Paragraph("Subscribe for Web Push Notifications to receive " +
                                            "real-time updates, reminders, and other important messages");
        this.webPushService = webPushService;
        toggle = new Checkbox("Subscribed");
        add(paragraph, toggle);
    }

    @Override
    protected void onAttach(AttachEvent attachEvent) {
        super.onAttach(attachEvent);
        UI ui = attachEvent.getUI();
        webPushService.isWebPushRegistered(ui, toggle::setValue);
        // omitted listener removal on detach
        toggle.addValueChangeListener(event -> {
            if (event.getValue()) {
                webPushService.subscribe(ui);
            } else {
                webPushService.unsubscribe(ui);
            }
        });
    }
}
```

And admin view from where the notification can be triggered:
```java
@Route(value = "admin", layout = MainLayout.class)
public class AdminView extends HorizontalLayout {

    private TextField message;
    private Button broadcast;

    public AdminView(WebPushService webPushService) {
        message = new TextField("Message");
        broadcast = new Button("Broadcast message", e ->
                webPushService.notifyAll(new WebPushMessage("Message from user",
                        message.getValue()))
        );
        broadcast.addClickShortcut(Key.ENTER);
        add(message, broadcast);
    }
}
```

2023-06-20 09:52 UTC, mshabarov commented
We discussed API and implementation here are comments to be addressed:
- include `PushService` implementation and whole library to the Flow
- all Web Push related classes can be extracted into a separate module `flow-web-push`
- `WebPushRegistration` to be renamed to `WebPush`
- Subscribe method can take two callbacks and unsubscribe method can take only UI, like shown below:
```java
            if (subscribed) {
                webPush.subscribe(ui,
                        subscription -> subscriptionService.add(subscription.getEndpoint(),
                                subscription),
                        subscription -> subscriptionService.remove(subscription));
            } else {
                webPush.unsubscribe(ui);
            }
```
- Think about method name `isWebPushRegistered` to better reflect what does this method do. Probably we should avoid using "registration" in the methods/class names, and use "subscription" instead.

2023-06-20 11:17 UTC, Artur- commented on flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPush.java
> +@JsModule("./FlowWebPush.js")
Does this actually work? `WebPush` is not a component

2023-06-20 11:35 UTC, caalador commented on flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPush.java
> +@JsModule("./FlowWebPush.js")
at least for devmode it does... Haven't started the application in production mode.

2023-06-20 11:41 UTC, caalador commented on flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPush.java
> +@JsModule("./FlowWebPush.js")
Works fine in production mode also as the class is found as used.

2023-06-20 11:52 UTC, Artur- commented on flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPush.java
> +@JsModule("./FlowWebPush.js")
If it for some reason ends up in a non-eager bundle, it won't work

2023-06-26 07:09 UTC, mshabarov requested changes
Some minor comments about javadoc and feature flags.
About testing: unit tests are not much interesting for this feature, because half of the feature is in the browser.
We need an end-to-end test, but need a discussion how properly set up the testing environment.

2023-06-26 07:09 UTC, mshabarov commented on flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPush.java
> +                getLogger().error("Server error, status code:" + statusCode);
This message can be more detailed on what is failed, like "Web Push Notification sending failed, status code returned by Push Server: "

2023-06-26 07:20 UTC, caalador commented on flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPush.java
> + * This class doesn't include any implementation for the intercommunication with
removed

2023-06-26 07:20 UTC, caalador commented on flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPush.java
> +                    "WebPush feature is not enabled. Enable feature though dev window or feature file.");
Updated.
The problem there is that then you can't use the dev tools window to enable the feature.

2023-06-26 07:20 UTC, caalador commented on flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPush.java
> +                getLogger().error("Server error, status code:" + statusCode);
Updated log message

2023-06-26 07:32 UTC, mshabarov commented on flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPush.java
> +                    "WebPush feature is not enabled. Enable feature though dev window or feature file.");
Then maybe not mention dev tools at all here? How this related to throwing the exception? Can we change from logging to throw?

2023-06-26 07:38 UTC, caalador commented on flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPush.java
> +                    "WebPush feature is not enabled. Enable feature though dev window or feature file.");
We can always throw, but I feel it is more intuitive to add it through the dev tools window than to start figuring out how and where the feature flags file should be.

2023-06-26 07:41 UTC, caalador commented on flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPush.java
> +                    "WebPush feature is not enabled. Enable feature though dev window or feature file.");
Added throws and message

2023-06-26 07:43 UTC, mshabarov approved these changes

2023-06-26 07:44 UTC, mshabarov commented on flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPush.java
> +                    "WebPush feature is not enabled. Enable feature though dev window or feature file.");
Ok, we can consider making dev tools toggle work later on in a separate PR.

2023-06-26 08:59 UTC, caalador commented on flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPush.java
> +@JsModule("./FlowWebPush.js")
Changed to executeJs loading of the scripts on need.

2023-06-26 10:40 UTC, merged