feat: allow disabling component internal validation
vaadin/flow pull request #17029
Opened 2023-06-14 12:09 UTC by vursen

## Description

The PR enhances the `HasValidation` interface to allow disabling components' internal validation.

A part of https://github.com/vaadin/flow-components/issues/5074

## Type of change

- [x] Feature

2023-06-20 07:16 UTC, mshabarov requested changes
@vursen @yuriy-fix this apparently needs more discussion of what would the implementation of this API do for components. The main question is what to do with default validator and Binder, if disabled=true.

2023-06-20 07:16 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/component/HasValidation.java
> +     * Binder or implement custom validation logic.
The javadoc given describes technical details for what happen if the validation is disabled.
It's not really clear what's the value for developers.
I'd make it explicit and highlight the following:
- what is an use case/problem developers can solve with this method. If I understood correct, this is a case when a custom validation logic is used, i.e. doing fields validation on value change.
- describe the scope of this configuration, i.e. is it's disabled, which validation steps are affected - only flow component constraints, affects also binder, default validator ?
- maybe also give some codes example.

2023-06-20 07:16 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/component/HasValidation.java
> +    void setInternalValidationDisabled(boolean disabled);
I don't really like the "internal" word in the middle. It makes me think that this API is internal and not supposed to be used by developers. `setComponentValidationDisabled` would be better IMO.

2023-06-21 13:59 UTC, vursen commented on flow-server/src/main/java/com/vaadin/flow/component/HasValidation.java
> +    void setInternalValidationDisabled(boolean disabled);
We agreed on renaming `setInternalValidationDisabled` to `setManualValidation`.

2023-06-22 11:10 UTC, mshabarov approved these changes

2023-06-22 11:10 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/component/HasValidation.java
> +     * Binder or implement custom validation logic.
Look very good now, thanks 👍

2023-06-22 11:26 UTC, mshabarov requested changes

2023-06-22 11:26 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/component/HasValidation.java
> +    void setManualValidation(boolean enabled);
This is a breaking change for add-on (custom components) which extend this interface. I'd avoid do it in the minor releases. Let's think about providing a default implementation. Even a default implementation is fine IMO if we state it in the javadoc. Composite component implementations can just call `setManualValidation(enabled)` for each child component.

2023-06-26 10:43 UTC, mshabarov requested changes

2023-06-26 10:43 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/component/HasValidation.java
> +        throw new UnsupportedOperationException();
Discussed offline to make the default implementation no-op (empty), so that add-ons can safely call this method according to `setInvalid` javadoc even if an add-on doesn't implement it.

2023-06-26 10:44 UTC, vursen commented on flow-server/src/main/java/com/vaadin/flow/component/HasValidation.java
> +        throw new UnsupportedOperationException();
Done.

2023-06-26 10:47 UTC, mshabarov approved these changes

2023-06-26 10:53 UTC, mshabarov approved these changes

2023-06-26 11:53 UTC, merged