fix: Load Vaadin version from pom.properties instead of from vaadin-c…
vaadin/flow pull request #17034
Opened 2023-06-15 10:20 UTC by mvysny

…ore-versions.json

vaadin-core-versions.json file is present both in vaadin-core.jar and hilla.jar. For hybrid projects, the outcome of Platform.getVaadinVersion() is undeterministic. This causes the function to parse pom.properties file instead.

Fixes #17017

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2023-06-15 11:18 UTC, caalador commented
As a minimum it is missing tests for single vs multiple versions.
I'll leave the selection to marco as I made a competing fix.

2023-06-15 11:18 UTC, mvysny commented
Probably a duplicate of https://github.com/vaadin/flow/pull/17034

2023-06-15 11:55 UTC, mcollovati commented
@mvysny yours is also a good solution indeed, but I prefer the one by @caalador as it works on a file we own directly instead of the one generated by the build tool

2023-06-15 14:31 UTC, mvysny commented
> @mvysny yours is also a good solution indeed, but I prefer the one by @caalador as it works on a file we own directly instead of the one generated by the build tool

@mcollovati yup that makes sense. The problem is that the `vaadin-core-versions.json` file may come from `vaadin-core.jar`, `vaadin-core-internal.jar` and/or `hilla.jar`, and it's quite hard to determine which one is the correct one. The problem is that in all three cases the file is located in the root directory, so you pretty much have to analyze the URL and perform some name matching of the parent jar file (or parent folder), to tell those apart. That of course only works if URLClassLoader is used, which may not be the case for some funky JavaEE servers. And of course the entire heuristics stops working for fatjars (if all jars are unpacked then packed into one fat jar).

The "load Maven pom.properties" solution works always since the pom.properties is stored under different folder within the jar file itself.

2023-06-16 06:06 UTC, mcollovati commented
@mvysny good point!
It seems like that for Vaadin 24 the `vaadin-core-versions.json` is only in `vaadin-core-internal` and not in `vaadin-core`.
However, as mentioned also in the Mikael's PR, a better solution may be having a different file name for Hilla.

2023-06-19 06:09 UTC, mcollovati requested changes

2023-06-19 06:31 UTC, mvysny commented on flow-server/src/test/java/com/vaadin/flow/server/PlatformTest.java
>          Thread.currentThread().setContextClassLoader(oldContextClassLoader);
Done - I've created the `cleanMemoizedValues()` function which is called both before and after tests.

2023-06-19 06:31 UTC, mvysny commented on flow-server/src/main/java/com/vaadin/flow/server/Platform.java
> +    private static final Logger log = LoggerFactory.getLogger(Platform.class);
Good catch, fixed

2023-06-19 07:02 UTC, mcollovati approved these changes

2023-06-19 07:02 UTC, mcollovati commented
As discussed internally, we will proceed reading the version from `pom.properties`, but in the meanwhile we will work on renaming version JSON files and then revisit the `Platform` methods implementations.

2023-06-19 07:16 UTC, merged