fix: get correct vaadin-core-versions.json
vaadin/flow pull request #17035
Opened 2023-06-15 10:48 UTC by caalador

Get the correct core-versions
file if both hilla and flow are available
on the classpath.

Fixes #17017

2023-06-15 11:09 UTC, mcollovati requested changes
Just a newline missing, other than that LGTM

2023-06-15 11:09 UTC, mcollovati commented on flow-server/src/test/java/com/vaadin/flow/server/PlatformVersionTest.java
> +}
newline missing 

```suggestion
}

```

2023-06-15 11:56 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/Platform.java
> +                return loadVersionForUrl(coreVersions.get(0));
Can this be Hilla? Should the check below be done always?

2023-06-15 11:57 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/Platform.java
> +                    .getResources(Constants.VAADIN_CORE_VERSIONS_JSON));
Does Hilla actually need to have a json file with this same name?

2023-06-15 12:01 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/Platform.java
> +                    .getResources(Constants.VAADIN_CORE_VERSIONS_JSON));
Probably should not if it is hilla specific.

2023-06-15 12:01 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/Platform.java
> +                return loadVersionForUrl(coreVersions.get(0));
Yes. it makes it much simpler...

2023-06-15 12:19 UTC, mcollovati approved these changes

2023-06-19 07:06 UTC, mcollovati commented
As discussed internally, we will proceed reading the version from `pom.properties` (#17034), but in the meanwhile we will work on renaming version JSON files and then revisit the Platform methods implementations.

I'll temporarily close this PR, and we can reopen it or create a new one once the JSON files changes are applied on the platform.

2023-06-19 07:06 UTC, closed without merging