fix: delay requests to dev-server during restart
vaadin/flow pull request #17036
Opened 2023-06-15 11:15 UTC by mcollovati

## Description

The dev-server may restart itself when some resources are modified. In this situation incoming requests fails with a connection exception until the server is ready again.
This change introduces a check that delays requests that happen during dev-server restart until the reboot operation has completed.

Fixes #17006

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2023-06-22 09:48 UTC, mshabarov requested changes
Minor suggestions before making a local testing.

2023-06-22 09:48 UTC, mshabarov commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/RestartMonitor.java
> + * Allows to block an execution when a restart is happening and to resume it
```suggestion
 * Allows to block dev-server requests processing when a restart is happening and to resume it
```

2023-06-22 09:48 UTC, mshabarov commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/RestartMonitor.java
> +     * Blocks execution during dev-server restarts.
```suggestion
     * Blocks requests to dev-server during dev-server restarts.
```

2023-06-22 09:48 UTC, mshabarov commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevServerOutputTracker.java
> +     * Gets a guard object that blocks the current execution when dev-server is
```suggestion
     * Gets a guard object that blocks the current request to dev-server when dev-server is
```

2023-06-22 09:48 UTC, mshabarov commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/RestartMonitor.java
> +        lock.lock();
Just an idea: what happens if restart of the dev-server fails (e.g. because of TS compilation errors), would the http request thread be waiting infinitely? Maybe we can lock the thread with a timeout after which the thread can just continue and give not found to the browser?

2023-06-22 09:48 UTC, mshabarov commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/RestartMonitor.java
> +    private boolean serverRestarting = false;
Should it be `volatile` ? I don't remember if Lock synchronisation is enough for visibility.

2023-06-22 09:51 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/RestartMonitor.java
> +    private boolean serverRestarting = false;
It should not be required IIRC, but we can make it `volatile` anyway

2023-06-22 09:57 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/RestartMonitor.java
> +        lock.lock();
The restart pattern catches both successful and failed restarts, so the request should never be blocked indefinitely.
Furthermore, the lock is held for a minimum amount of time, just to update the `serverRestarting` variable.
But if we want to be sure, we can set a timeout when waiting on the condition (`serverRestartedCondition.await()`)

2023-06-22 10:42 UTC, mshabarov commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/RestartMonitor.java
> +        lock.lock();
> The restart pattern catches both successful and failed restarts, so the request should never be blocked indefinitely.

Ok, then I think nothing to worry about.

2023-06-22 10:45 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/RestartMonitor.java
> +        lock.lock();
Requests may hang if Vite server crashes, but then you need to restart the application anyway.
But a sensible timeout makes sense. I'll add it

2023-06-22 11:05 UTC, mshabarov approved these changes
Cannot see the problem anymore with this patch. Excellent fix 👍

2023-06-26 06:31 UTC, mshabarov approved these changes

2023-06-26 06:31 UTC, merged