chore: add method to skip clean
vaadin/flow pull request #17080
Opened 2023-06-22 11:10 UTC by caalador

Add method to build-frontend
plugin that makes it possible
to skip cleaning of frontend
files from extending plugins.

2023-06-22 11:32 UTC, mcollovati requested changes

2023-06-22 11:32 UTC, mcollovati commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
> +    protected boolean cleanFrontentFiles() {
The method name is self-explanatory, but it would be good to have a Javadoc that explains how this flag impacts on the execution

2023-06-22 11:41 UTC, caalador commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
> +    protected boolean cleanFrontentFiles() {
added.

2023-06-22 11:53 UTC, mcollovati approved these changes
A question: is the Gradle plugin also affected by a similar issue?

2023-06-22 11:58 UTC, caalador commented
Yes, Gradle has the same functionality. Added the method there also so it can be overridden to not do the cleaning if necessary.

2023-06-22 12:05 UTC, mcollovati approved these changes
It would be nice to add a test for this, but we can address it in another PR

2023-06-22 12:07 UTC, mcollovati requested changes

2023-06-22 12:07 UTC, mcollovati commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
> +    protected fun cleanFrontentFiles(): boolean {
typo
```suggestion
    protected fun cleanFrontendFiles(): boolean {
```

2023-06-22 12:07 UTC, mcollovati commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
> +            if (cleanFrontentFiles()) {
typo
```suggestion
            if (cleanFrontendFiles()) {
```

2023-06-22 12:09 UTC, caalador commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
> +            if (cleanFrontentFiles()) {
fixed.

2023-06-22 12:58 UTC, mcollovati approved these changes

2023-06-23 06:04 UTC, mcollovati requested changes

2023-06-23 06:04 UTC, mcollovati commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
> +    protected fun cleanFrontendFiles(): Boolean {
Must be declared `open` to allow sub classes to override it
```suggestion
    protected open fun cleanFrontendFiles(): Boolean {
```

2023-06-26 04:48 UTC, mcollovati approved these changes

2023-06-26 04:49 UTC, merged