fix: Fix regression when sync id check is disabled
vaadin/flow pull request #17238
Opened 2023-07-19 08:56 UTC by TatuLund

Fixes: https://github.com/vaadin/flow/issues/17237

2023-07-19 09:21 UTC, mcollovati requested changes
@TatuLund thank you very much for spotting the bug and providing the fix.
The change looks good to me, but I would like to add a test for this case

Could use please add a test to `LongPollingCacheFilterTest` class? 
Something like

```java
    @Test
    public void filter_syncIdCheckDisabled_continueWithCurrentMessage() {
        // a value of -1 means that syncId check is disabled
        setSeenServerSyncIdHeader(-1);
        setTransport(AtmosphereResource.TRANSPORT.LONG_POLLING);
        simulatePushConnection();
        BroadcastAction action = filter.filter("broadcasterId", resource,
                originalMessage, message);
        Assert.assertEquals(ACTION.CONTINUE, action.action());
        Assert.assertSame(
                "Message should not be altered by filter if syncId check is disabled",
                message, action.message());
        verifyMessageIsNotCached();
    }
```

2023-07-19 09:24 UTC, TatuLund commented
> Could use please add a test to LongPollingCacheFilterTest class?

I was already working on that

2023-07-19 09:49 UTC, mcollovati requested changes

2023-07-19 09:49 UTC, mcollovati commented on flow-server/src/test/java/com/vaadin/flow/server/communication/LongPollingCacheFilterTest.java
> +                "Message should not be altered by filter if server sync id header is missing",
A minor change on the assertion message
```suggestion
                "Message should not be altered by filter if syncId check is disabled",
```

2023-07-19 10:02 UTC, TatuLund commented on flow-server/src/test/java/com/vaadin/flow/server/communication/LongPollingCacheFilterTest.java
> +                "Message should not be altered by filter if server sync id header is missing",
Fixed

2023-07-20 04:44 UTC, mcollovati approved these changes

2023-07-20 04:49 UTC, merged