bugfix: fixes and optimizes everything regarding event debouncing :-)
vaadin/flow pull request #17410
Opened 2023-08-09 17:59 UTC by mstahv

More details in Slack thread, coming here later...

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2023-08-11 12:18 UTC, mcollovati requested changes
Just some typos

2023-08-11 12:18 UTC, mcollovati commented on flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DomEventFilterIT.java
> +         * side listenr). This is probably an issue in the original
```suggestion
         * side listener). This is probably an issue in the original
```

2023-08-11 12:18 UTC, mcollovati commented on flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DomEventFilterIT.java
> +         * listeners and handle those somehow separately. My hunch is That it is
```suggestion
         * listeners and handle those somehow separately. My hunch is that it is
```

2023-08-11 12:18 UTC, mcollovati commented on flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DomEventFilterIT.java
> +         * better just to documenta the limitations and focus on somethign that
```suggestion
         * better just to document the limitations and focus on something that
```

2023-08-11 12:33 UTC, mcollovati commented
The overall change looks good, and the tests are more reliable.
However, since the change involves a behavior change (), we need to:

* update documentation (https://vaadin.com/docs/latest/create-ui/creating-components/events#limiting-event-frequency)
* update `DebouncePhase` javadoc

2023-08-11 13:33 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/dom/DomListenerRegistration.java
> +     * </dl>
It seems like `DebouncePhase.LEADING + DebouncePhase.TIMEOUT` is repeated

2023-08-11 13:46 UTC, mstahv commented on flow-server/src/main/java/com/vaadin/flow/dom/DomListenerRegistration.java
> +     * </dl>
fixed

2023-08-11 19:41 UTC, mstahv commented
Nope, it is fine, "just" other slightly related issues (#17430, #17429) causing obsolete server visit.

2023-08-14 12:38 UTC, mstahv commented
Checked the reference docs. Nothing urgent needs to change there. Of course more hands on examples of everything would be nice. And maybe mentioning that combining all modes is weird and may cause double calls for the same event 🤷‍♂️

2023-08-22 11:38 UTC, mshabarov commented
@mstahv With this patch I see the same behaviour as previously, without it, "g" event is triggered on the server first, and "k" goes after it:
```
14:34:24.148306 g-event 5.0
14:34:27.798952 k-event6.0 phase: TRAILING
```
How did you test it?

2023-08-22 12:05 UTC, mstahv commented
Regression in the branch 🤔 Make sure you are not causing another keydown (like shortcut to change focus to IDE) event if you are using the original case in the issue description. I tested the original case with a separate project, but then the changed the implementation still while making the IT test suit more complete 🤷‍♂️ But it still don't seem to contain test with two different event types.

Would have been easier to check two weeks ago 😤

2023-08-22 12:31 UTC, mstahv commented
Added case to DomEventFilterIT/View locally testing with Safari all seems to work fine, but can't these days be sure as the front-end bundle things are rather complex 🤓

2023-08-22 14:01 UTC, mshabarov approved these changes

2023-08-22 14:05 UTC, mshabarov commented
The same behaviour was observed because of pre-compiled dev bundle was used, which did not contain these changes. With forcing the frontend build, these changes are now shown and seems to work as expected: one request to server is sent and events go in order.
Let's apply this patch and check Flow Components tests later.
I propose to include this only to 24.2 until enough time passes by, then we can pick it to other branches.

2023-08-22 14:09 UTC, merged