feat: Micrometer Observation instrumentation
vaadin/flow pull request #17494
Opened 2023-08-24 15:55 UTC by marcingrzejszczak

## Description

- adds a VaadinFilter mechanism to mimic an around-aspect
- adds a Micrometer Observation implementation
- configures VaadinServlet to automatically update the VaadinService with filters
- configures Spring to automatically update the VaadinServlet with filters

What's missing:
- Client side instrumentation
- Tests
- Documentation

Fixes #17436

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [x] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2023-08-24 15:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=17494) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=17494) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=17494) it.</sub>

2023-08-25 05:55 UTC, mshabarov commented
@marcingrzejszczak thank you a lot for your contribution, we appreciate it and will start reviewing it soon 👍

2023-08-25 06:15 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinFilter.java
> +public interface VaadinFilter {
I'm wondering if it would be worth to focus first on this interface and its integration into flow, allowing this to be already added e.g. in the upcoming release - especially since the full integration could take a little bit longer (see Jakarta / Snapshot usage). If I remember correctly, I've seen multiple dicussions quite recently where people needed hooks like this. Shamelessly pinging @mstahv

2023-08-25 09:57 UTC, marcingrzejszczak commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinFilter.java
> +public interface VaadinFilter {
Sure! I didn't know if you want sth like that. Let me split the two then.

2023-08-25 10:12 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinFilter.java
> +public interface VaadinFilter {
wait for Mikhail's response before you do anything. I'm just an external contributor like you ;)

2023-08-25 11:37 UTC, marcingrzejszczak commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinFilter.java
> +public interface VaadinFilter {
I split that https://github.com/vaadin/flow/pull/17502, I still think the change makes sense to be split into 2 PRs. Thanks for the great tip

2023-08-25 13:19 UTC, mstahv commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinFilter.java
> +public interface VaadinFilter {
@knoobie Already subscribed 😎

Quick comment on the VaadinFilter (although now in separate PR): maybe it could also cover UI.access calls coming from separate threads 🤔 And then requests & al are optional or within some context parameter 🤷‍♂️

2023-09-06 10:32 UTC, mshabarov requested changes
I'd propose to extract the Micrometer Observation implementation of request interceptors into a separate maven module `flow-observation` or `flow-micrometer`.
Then the Micrometer dependencies can be normal, i.e. non-optional.
Then we need to add it into `flow-bom` and into `vaadin-bom` on the platform side.
Finally, it can be pluggable, so if a project defines
```xml
            <dependency>
                <groupId>com.vaadin</groupId>
                <artifactId>flow-micrometer</artifactId>
            </dependency>
```
then the Micrometer's `VaadinRequestInterceptor`s add themselves via Service Init Listener. Otherwise, if no dependency is set, Micrometer observation isn't included.

We did something similar with `flow-webpush` module recently, so you can use it as an example.

2023-09-26 08:07 UTC, mshabarov commented
Needs a rebase to main branch.

2023-09-26 09:12 UTC, marcingrzejszczak commented
@mshabarov I wonder if we shouldn't first add instrumentation of the commands. To this, we need to implement this https://github.com/micrometer-metrics/micrometer/pull/3989 and that's not merged yet

2023-09-26 09:47 UTC, mshabarov commented
> I wonder if we shouldn't first add instrumentation of the commands. To this, we need to implement this https://github.com/micrometer-metrics/micrometer/pull/3989 and that's not merged yet

I would suggest to add first the instrumentation for things that already merge and for what we already have a PR. So could we merge the instrumentation proposed in this PR?

2023-09-26 09:54 UTC, marcingrzejszczak commented
I would love to but this https://github.com/vaadin/flow/pull/17494/files#diff-4abe9f264d9d9616e9178b98b70fdfbb13aeea2d49ef4c0e6c30f04882ab55d3R147 is not actually pushed anywhere. I made it work locally because I installed this module in my local .m2. Before this PR gets merged, this PR https://github.com/micrometer-metrics/micrometer/pull/3989 must get merged first :grimacing:

2023-09-26 10:07 UTC, knoobie commented
Just wondering is this targeted for Micrometer 1.12 / Spring Boot 3.2 in November or is it pending a release version, meaning it could at first land in 1.1x / Spring Boot 3.3 in Mai 2024? ;)

2023-09-26 10:13 UTC, marcingrzejszczak commented
I want the PR to merged asap so that it's happening for 1.12 of Micrometer.

2023-09-26 11:46 UTC, mshabarov commented
I see, thanks for explanations 👍 
So we have to wait a bit, no problem.

2023-09-26 12:26 UTC, marcingrzejszczak commented
Do we want to proceed with the command instrumentation in the meantime? Also do you have a chat of some sort (e.g. Slack) where it will be easier to communicate rather than Github issues? :)

2023-09-28 06:22 UTC, mshabarov commented
@marcingrzejszczak 
> Do we want to proceed with the command instrumentation in the meantime?
Yes, let's do. I remember you had a branch with prototype. Could you share it with a new pull request and I'll review?

> Also do you have a chat of some sort (e.g. Slack) where it will be easier to communicate rather than Github issues? :)
Discord is it :) Here is a link https://discord.com/invite/vaadin. You can DM me directly there.

2023-09-28 13:46 UTC, marcingrzejszczak commented
@mshabarov there you go https://github.com/vaadin/flow/pull/17738

2025-09-05 09:16 UTC, mshabarov commented
Closed as stale, but branch should be kept for possible future contributions.

2025-09-05 09:16 UTC, closed without merging