fix: Allow platform dependencies to be linked
vaadin/flow pull request #17560
Opened 2023-09-05 14:30 UTC by Artur-

Do not fail if a managed version is linked to a local copy and thus the version cannot be parsed

2023-09-08 10:32 UTC, mshabarov requested changes
Also would need a unit test.

2023-09-08 10:32 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +        } catch (Exception e) {
Would it be more correct to scope the caught exception to only `NumberFormatException` ?

2023-09-08 10:45 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +        } catch (Exception e) {
What should we do on another exception?

2023-09-08 10:48 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +        } catch (Exception e) {
We don't expect other exceptions in the `FrontendVersion` CTOR, if it throws NPE or other runtime exception, then it throws.

2023-09-12 06:43 UTC, mshabarov approved these changes

2023-09-12 06:43 UTC, merged