perf: optimize RouteUtil.resolve method
vaadin/flow pull request #17604
Opened 2023-09-12 10:12 UTC by tltv

Cache `RoutePathProvider` in `VaadinContext` for faster lookup time in `RouteUtil.resolve` method.

2023-09-13 13:29 UTC, mshabarov requested changes

2023-09-13 13:29 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java
> +            provider = context.getAttribute(RoutePathProvider.class);
This by-passes the Lookup API and, thus, most likely will have issues in other environments, like OSGi.
This isn't a good design as well.
If the lookup takes much time to get the service, maybe we can fix it in the lookup implementation?

2023-09-13 14:03 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java
> +            provider = context.getAttribute(RoutePathProvider.class);
It probably would just use lookup anyway in OSGi environment and would not speed up anything there.
If this can be updated in Lookup, that would be better indeed. I don't know the effort yet but I'll check that.

2023-09-14 11:23 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java
> +            provider = context.getAttribute(RoutePathProvider.class);
I'll prepare now update that adds caching in `SpringLookup`. It will also cache a bit more than just `RoutePathProvider` based on `LookupInitializer.getDefaultImplementations()`.

2023-09-15 09:55 UTC, mshabarov approved these changes

2023-09-15 09:56 UTC, merged