Feature/conditional spring beans
vaadin/flow pull request #17671
Opened 2023-09-20 13:52 UTC by oliveryasuna

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

See details of issue...

Fixes https://github.com/vaadin/flow/issues/17669

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2023-09-25 11:49 UTC, mshabarov commented
Adding this annotation to the methods means that we expose a new API by allowing making a new, for instance, Spring Context Initialiser, custom implementation. However, this might be dangerous in some cases, because currently some of these beans are purely internal and we don't recommend to extend them or change.

Thus, I would like to, as a first step, check what exactly we can mark with this annotation, in other words, what we can allow developers to extend/change in their projects.

For your case, there is a need for custom route registry initialiser, which can be done in another way.

2023-09-29 12:48 UTC, mshabarov commented
@oliveryasuna I agree in general to make Vaadin auto-configuration more extendable.
But it seems to me that just adding this `AtConditionalOnMissingBean` annotation is not enough and that's why:
1. `AbstractRouteRegistryInitializer` isn't really open for extensions. It has a couple of protected methods, but you have to rewrite them for your case. All the private methods in it become useless then.
2. `RouteServletContextListener` has the essential logic in `failFastContextInitialized`, which uses private methods like `getRoutePackages`, `findByAnnotation` and others. So you cannot easily extend it.
3. `RouteServletContextListener` and other context listeners are `private`. This means that you need to replicate all these listeners in your project to make Vaadin work.

Thus, now I'm quite sure that the whole class `VaadinServletContextInitializer` isn't really extendable, but for internal use semantically.

Maybe if you provide your solution for `VaadinServletContextInitializer` custom implementation to me, I can see where I'm wrong.

But at the moment, I don't think it would be correct to let (and even recommend) developers to make a custom `VaadinServletContextInitializer`. This needs more design think over - more abstraction, more common logic, more protected methods/classes.

Let me check the rest of the beans you suggest to annotate.

2023-10-02 13:20 UTC, mshabarov commented
For the rest of the beans, I propose the following:
- `ServletRegistrationBean<SpringServlet>` - makes sense to annotate it 👍 , one may want a custom Spring servlet, e.g. for adding a custom Vaadin service class.
- `VaadinWebsocketEndpointExporter` - not sure if there is any use case which would need to extend Vaadin-provided `ServerEndpointExporter`. I would propose to allow having other beans of type `ServerEndpointExporter`, this would require changing the concrete Vaadin class (don't remember if it needs also specifying a name in the bean annotation):
```java
    @Bean
    public VaadinWebsocketEndpointExporter websocketEndpointDeployer() {
        return new VaadinWebsocketEndpointExporter();
    }
```
- `VaadinBeanFactoryInitializationAotProcessor` - same as for the previous point, without a good understanding where extending the existing class would be needed, I wouldn't allow to override it.
- `VaadinServletContextInitializer` - as I noted in my last comment, I see this useless of adding the annotation until we make this class more extendable (again, maybe I'm wrong, but so far there is no easy way). I think we can also specify a concrete class as a return type, so that it would be possible to add more `ServletContextInitializer` beans to the project.

2023-10-10 08:17 UTC, mcollovati commented
I agree with @mshabarov to avoid encouraging developers to override beans that are meant to be internal components.
This will prevent unexpected behaviors and lets us apply changes in patch releases, that could potentially be considered breaking if the API is made public.
On the other hand, we would love to understand uses cases for overriding Vaadin internals so that we can consider adding hooks or even make the API public, if reasonable.

In detail, I agree on not having conditional annotation on:
* `VaadinBeanFactoryInitializationAotProcessor`: it could make sense for a developer to register additional reflection hints, for example while waiting for a proper fix, but this can also be done by defining an additional `BeanFactoryInitializationAotProcessor` bean.
* `VaadinServletContextInitializer`: agree with Mikhail comments. If there are good uses cases, we can consider allowing developers to provide beans that we can look up and use in the existing components (e.g. a `RouteValidator` interface to be used in `AbstractRouteRegistryInitializer`).
* `VaadinWebsocketEndpointExporter`: honestly, I can't see a reason for a developer to override such a bean


Making `ServletRegistrationBean<SpringServlet>` conditional seems a good improvement.

2023-10-10 08:22 UTC, mcollovati requested changes

2023-10-10 08:22 UTC, mcollovati commented on vaadin-spring/pom.xml
> +        </dependency>
If possible, I would try to avoid adding a dependency.
But if `MockWebApplicationContext` is really needed, let's depend on `vaadin-testbench-unit-shared` instead of `vaadin-testbench`.
In addition, the `testbench.version` property should be used for version because the current project version may not match a Vaadin platform one,

2023-10-23 14:35 UTC, mshabarov commented
Closed in favour of https://github.com/vaadin/flow/pull/17883 (only scoped to ServletRegistration).

2023-10-23 14:35 UTC, closed without merging