Allow specifying `devDependencies` with `@NpmPackage`.
vaadin/flow pull request #17687
Opened 2023-09-21 22:36 UTC by oliveryasuna

## Description

This PR adds a `dev` property to the `@NpmPackage` annotation. Setting `dev = true` adds the package to `devDependencies` instead of `dependencies`. I specifically designed this to be backwards compatible with the current code. It does not affect bundles. I could repeat the motivation here, but enough has been said in the issue.

Fixes https://github.com/vaadin/flow/issues/11032

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [x] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2023-09-22 09:47 UTC, mshabarov commented
@oliveryasuna thank you for your contribution 👍 
The enhancement you are implementing looks as a good addition to existing annotation.
Someone from Flow team will get back to you soon with a review.

2023-09-22 11:12 UTC, caalador requested changes

2023-09-22 11:12 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTestComponents.java
> +    @NpmPackage(value = "vite-plugin-pwa", version = "0.16.5", dev = true)
Just adding the dev package annotation doesn't test the feature.
`FullDependenciesScannerTest` should get a new test that checks that devDependencies are collected correctly and that it doesn't end up in both `getPackages` and `getDevPackages`

2023-09-22 13:53 UTC, oliveryasuna commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +                    entry.getValue());
@caalador What do you mean, "there is no change"?

2023-09-22 13:59 UTC, oliveryasuna commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTestComponents.java
> +    @NpmPackage(value = "vite-plugin-pwa", version = "0.16.5", dev = true)
Though, I just pushed a commit that adds a new test.

2023-09-22 13:59 UTC, oliveryasuna commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
> +import static com.vaadin.flow.server.frontend.scanner.FrontendClassVisitor.*;
Fixed.

2023-09-25 07:59 UTC, caalador requested changes

2023-09-25 07:59 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
> +                if (dev) {
The getValuesForKey only finds given values, so it doesn't check for the default value.
Either we should add a null check for dev here which would equal to false:
```suggestion
                if (dev != null && dev) {
```
Or then the getValuesForKey method in `FrontendAnnotatedClassVisitor` should have the map changed to `.map(h -> h.get(property) == null ? getDefault(property): h.get(property))` so that we would get the correct value.

2023-09-26 08:03 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
> +                if (dev) {
Seems that accepting defaults for the valuesForKey generate probelms in other places so the check should just have a null be the same as `dev=false`

2023-09-29 05:35 UTC, caalador approved these changes

2023-09-29 05:37 UTC, merged

2023-10-24 22:48 UTC, oliveryasuna commented
@caalador How do I know with which version this will be released?

2023-10-25 06:48 UTC, mshabarov commented
@oliveryasuna usually we follow this practice: `main` branch is for next minor release of Vaadin Flow. So once a feature is merged, it is included into next minor pre-release and finally in GA version. The referenced issue is automatically labeled with released version, e.g. `Released with Vaadin 24.1.12`, but this is a "post-factum" information.

Sometimes we backport some features to the older maintained major versions, but this isn't done automatically and the policy is to backport when it is sponsored.

We don't at the moment label pull requests or issues with milestones or other information about target version, but follow the policies described above.

2023-10-25 21:39 UTC, oliveryasuna commented
@mshabarov @caalador Thank you. Very useful information.