fix: detach should be sent for node
vaadin/flow pull request #17695
Opened 2023-09-22 11:05 UTC by caalador

Do not clean the node id or
hasAttached state too early as
then we do not send the detach
event for the node.

Fixes #17653

2023-09-22 11:19 UTC, mcollovati requested changes
Tested locally and could not see detached elements on the browser anymore after removing elements with `removeFromTree()`.

2023-09-22 11:19 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/internal/change/NodeDetachChange.java
> +import com.vaadin.flow.server.Command;
unused import
```suggestion
```

2023-09-22 11:38 UTC, mcollovati commented
Looks like there are issues with PreserveOnRefresh

2023-09-25 13:15 UTC, mcollovati requested changes
Just some minor javadocs changes.
I wonder if we can somehow arrange unit tests for StateNode, to prevent regressions.
Maybe just checking for `id` and `wasAttached` (through `isClientSideInitialized`?) values after invoking `removeFromTree` with true and false.

2023-09-26 04:55 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
> +    private void reset(boolean shouldDetach) {
added

2023-09-26 04:55 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/dom/Element.java
> +    public Element removeFromTree(boolean sendDetach) {
added

2023-09-26 05:34 UTC, mcollovati approved these changes

2023-09-26 05:34 UTC, merged