fix: update role checkers to work in same way
vaadin/flow pull request #17739
Opened 2023-09-28 14:09 UTC by tltv

Added `AuthenticationUtil#getSecurityHolderRoleChecker(String rolePrefix)` method that works now in same way as `SecurityContextHolderAwareRequestWrapper#isGranted(String role)`. Role prefix is set and read in `VaadinRolePrefixHolder` bean by `SpringViewAccessChecker#getRolesChecker(VaadinRequest)`.

2023-10-04 06:35 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java
> +    public VaadinRolePrefixHolder vaadinRolePrefixHolder() {
I wonder if we can inject `GrantedAuthorityDefaults` as a method parameter and get the default role prefix from there.
Also, we could probably make the method `@ConditionalOnMissingBean`, so developers can easily customize it if they need.
Or is this bean supposed to be fully managed by Vaadin, to be in sync with Spring Security settings?

If it's the second case, `VaadinRolePrefixHolder` could most likely be final and have a package protected constructor.

2023-10-04 06:35 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringViewAccessChecker.java
> +
What if we also try to initialize the `VaadinRoleprefix` role prefix in `VaadinWebSecurity`, by looking for `SecurityContextHolderAwareRequestFilter` in `securityFilterChain.getFilters(), after the call to `HttpSecurity.build()`?

Anyway, this call would still be useful if `VaadinWebSecurity` is not in use.

2023-10-05 11:46 UTC, tltv commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java
> +    public VaadinRolePrefixHolder vaadinRolePrefixHolder() {
`GrantedAuthorityDefaults` seems to indeed provide role prefix and its also effective in `SecurityContextHolderAwareRequestWrapper` when provided. So yes this can be done. Unfortunately bean does not exist by default so need to have it as an optional parameter.

It should be safe to add `@ConditionalOnMissingBean` for this.

2023-10-05 13:57 UTC, tltv commented
`GrantedAuthorityDefaults` could have been actually used instead of introducing `VaadinRolePrefixHolder` just by adding it in `SpringSecurityAutoConfiguration` by default with fixed default role prefix `ROLE_` and with `@ConditionalOnMissingBean`. 
But that would just move the fixed default role prefix into other place, although it would help those who uses `GrantedAuthorityDefaults` already, it would not help those who use some other way to override the default role prefix. 

This change should work now no matter how default value is changed. Usage of reflection is downside of it.

2023-10-06 08:29 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringViewAccessChecker.java
> +                        prefixHolder -> prefixHolder.resetRolePrefix(request));
Just a note, but not a blocker: if for some reason `prefixHolder.resetRolePrefix()` fails to set the prefix, or if the prefix has been configured to be `null` (however I don't know if it is really possible), we are going to execute the reflection stuff every time we need the role checker instance.
Would it make sense to set a flag in `VaadinRolePrefixHolder` when `resetRolePrefix` has been executed for the first time (or if a not null value is given to the constructor), and then have a `VaadinRolePrefixHolder.isSet()` instead of the `prefixHolder.getRolePrefix() == null` check?

2023-10-06 08:29 UTC, mcollovati approved these changes

2023-10-06 08:49 UTC, tltv commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringViewAccessChecker.java
> +                        prefixHolder -> prefixHolder.resetRolePrefix(request));
It's indeed possible to set it to null and I totally agree that it makes sense to add this flag to avoid resetting over and over with null prefix..

2023-10-06 09:22 UTC, mcollovati requested changes

2023-10-06 09:22 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinRolePrefixHolder.java
> +     * Method doesn't do anything if role is not found.
```suggestion
     * Method doesn't do anything if role prefix is not found.
```

2023-10-06 09:22 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinRolePrefixHolder.java
> +     * Method doesn't do anything if role is not found.
```suggestion
     * Method doesn't do anything if role prefix is not found.
```

2023-10-06 09:37 UTC, mcollovati approved these changes

2023-10-06 09:59 UTC, merged