feat: Show error view on action exception
vaadin/flow pull request #17791
Opened 2023-10-06 11:56 UTC by caalador

If there is a error view for the
thrown exception during rpc handling
update view to error view.

Fixes #4715

The feature is behind a feature flag for testing out the function.

2023-10-06 12:23 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/DefaultErrorHandler.java
> +                    && throwable instanceof Exception) {
See comment for considering: https://github.com/vaadin/flow/issues/4715#issuecomment-1750168450

2023-10-06 12:25 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/DefaultErrorHandler.java
> +                    .isEnabled(FeatureFlags.HAS_ERROR_OUTSIDE_NAVIGATION)
How should the developer opt-in when they have their own ErrorHandler implemented? Extending the DefaultErrorHandler and overwriting the error method? Most people are probably just implementing `ErrorHandler` where no such methods are available to delegate from/to

2023-10-09 04:58 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/DefaultErrorHandler.java
> +                    && throwable instanceof Exception) {
We check for exact matchin the drawErrorViewForException as at this point we do not know if there is a handler for the exact error and this check is to just be certain that the throwable is an exception and not an error.

2023-10-09 04:58 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/DefaultErrorHandler.java
> +                    .isEnabled(FeatureFlags.HAS_ERROR_OUTSIDE_NAVIGATION)
As the feature itself is not bound to the interface it will most likely become a util class that is used. making it explicitly more opt-in as just testing this out with makes it show how intrusive the feature is when the view redraws when an exception happens.
This state was more for interested parties to try out the feature from behind the feature flag.

2023-10-09 05:33 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/DefaultErrorHandler.java
> +                    && throwable instanceof Exception) {
I see it at line 121 - thanks for confirming the intention!

2023-10-09 14:45 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/DefaultErrorHandler.java
> +                            .isErrorRedirectEnabled()
This new feature should be configured for sure and better to keep the default as is, so turn it off by default. But I'm not so sure that the config parameter is a best option here. 

I would prefer to have a default method in `HasErrorParameter` which returns a boolean for controlling this feature. By default it is false, so no redirecting for non-navigation exceptions. This, as a bonus, would give more flexibility, as they could configure different `HasErrorParameter` differently.

2023-10-09 14:45 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/DefaultErrorHandler.java
> +                            .handleErrorByRedirectingToErrorView(throwable)) {
How the `ErrorHandler` API is relevant to the original issue?

Maybe I misunderstood the acceptance criteria, but I thought that we want to extend `HasErrorParameter` for non-navigation errors. So basically calling its `setErrorParameter` callback in the same cases/places in code that calls for `ErrorHandler::error()`.

2023-10-10 06:00 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
> +import javax.annotation.OverridingMethodsMustInvokeSuper;
Yes. Cleaned.

2023-10-10 06:53 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/DefaultErrorHandler.java
> +                            .isErrorRedirectEnabled()
That has the problem of having to go through the error routes for each error and instantiating the HasErrorParameter view to get the state that is it to be used or not.

2023-10-10 06:59 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/DefaultErrorHandler.java
> +                            .handleErrorByRedirectingToErrorView(throwable)) {
This change does just that. When the error handler gets called we setup the appropriate HasErrorParameter view and call setErrorParameter with the current data and then show the error view on screen.
I don't think calling the error handler and showing the view is what is wanted as then you basically handle the error twice and controlling the errorHandler by making a custom one becomes harder.

2023-10-10 09:14 UTC, mshabarov requested changes
Naming and javadoc suggestions plus question about child exceptions, otherwise looks good 👍

2023-10-10 09:14 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/ErrorHandlerUtil.java
> +                .getHandledExceptionType().equals(exception.getClass())) {
How about handling also children classes of the exception?

2023-10-10 09:46 UTC, caalador commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
> +    boolean isErrorHandlerRedirect();
done

2023-10-10 09:46 UTC, caalador commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
> +    public boolean isErrorHandlerRedirect() {
done

2023-10-10 09:46 UTC, caalador commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
> +    override fun isErrorHandlerRedirect(): Boolean = extension.isErrorHandlerRedirect
done

2023-10-10 09:46 UTC, caalador commented on flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
> +    public boolean isErrorHandlerRedirect() {
done

2023-10-10 09:46 UTC, caalador commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
> +     * If {@code true} navigation error views can be rendered for exceptions during RPC request handling.
changed

2023-10-10 09:46 UTC, caalador commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
> +     * If {@code true} navigation error views can be rendered for exceptions
added

2023-10-10 09:46 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/ErrorHandlerUtil.java
> +                .getHandledExceptionType().equals(exception.getClass())) {
The initial wish was at least for exact matches only. So as I see it extending children should not go through there. This could perhaps be seen as an enhancement to the feature if requested enough.

2023-10-10 09:48 UTC, mshabarov commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
> +    override fun isErrorHandlerRedirect(): Boolean = extension.isErrorHandlerRedirect
Not done apparently

2023-10-10 09:54 UTC, caalador commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
> +    override fun isErrorHandlerRedirect(): Boolean = extension.isErrorHandlerRedirect
I feel cheated by idea.

2023-10-10 09:55 UTC, mshabarov approved these changes

2023-10-10 11:57 UTC, merged