bugfix: jsx files are not taken into front-end build from add-ons
vaadin/flow pull request #17820
Opened 2023-10-11 16:21 UTC by mstahv

We already support tsx, but the more trivial jsx files don't seem to work. Something that people probably try first, especially if the embedded component is only using JS...

## Type of change

- [x] Bugfix
- [] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2023-10-11 16:29 UTC, mcollovati commented
Thanks, @mstahv.
Do you mind updating the tests to cover the added extensions, as done in #13323?

2023-10-11 16:33 UTC, mstahv commented
I was looking at that for a while, but modifying those jar files to include test files made me feel reluctant 😁

2023-10-12 05:18 UTC, mstahv commented
Thanks @caalador, here is a medal for you 🥇

2023-10-12 05:31 UTC, mcollovati requested changes
Just a typo in test error messages

2023-10-12 05:31 UTC, mcollovati commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFilesTest.java
> +                "JSX resource source map should have been copied from jar file",
```suggestion
                "TSX resource source map should have been copied from jar file",
```

2023-10-12 05:31 UTC, mcollovati commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFilesTest.java
> +        Assert.assertTrue("TSX resource should have been copied from jar file",
```suggestion
        Assert.assertTrue("JSX resource should have been copied from jar file",
```

2023-10-12 05:35 UTC, mcollovati approved these changes

2023-10-12 05:54 UTC, merged