feat: Default I18N provider
vaadin/flow pull request #17823
Opened 2023-10-12 09:56 UTC by caalador

Add implementation for a I18N
provider that is loaded if there
are translation properties files
in the defined classpath folder.

If a custom I18N is set default will
never be loaded.

Fixes #5917

2023-10-12 10:17 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
> +            value = new String(value.getBytes("ISO-8859-1"), "UTF-8");
With Vaadin 24.3 enforcing Java 17+, I think the usage of ISO-8859-1 with resourcebundle should not be used anymore. By default it should be UTF-8 or something else, depending on the used system property: [JavaDoc PropertyResourceBundle](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/PropertyResourceBundle.html)

2023-10-12 10:22 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
> +            value = MessageFormat.format(value, params);
Would it make sense to move this in a protected method to allow overwriting this to e.g. implement a caching mechanism? MessageFormat can be quite expensive.

2023-10-12 10:23 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
> +            value = MessageFormat.format(value, params);
Should this be changed to something like: 

```java
      MessageFormat messageFormat = new MessageFormat(value, locale);
      value = messageFormat.format(params);
```

so that the used locale is propagated to the formatter?

2023-10-12 10:26 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
> +            getLogger().warn("Missing resource", e);
Nit: I feel like "ups you are missing a translation label" is not severe enough to justify a warn-level. I would suggest to lower it to info or even debug.

2023-10-12 10:35 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
> +            value = MessageFormat.format(value, params);
I don't think the default implementation brings in so much functionality that it would make sense to override it instead of just implementing your own I18NProvider as you need to anyway set it as you do at the moment.

2023-10-12 10:35 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
> +            value = MessageFormat.format(value, params);
done

2023-10-12 10:35 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
> +            getLogger().warn("Missing resource", e);
lowered

2023-10-12 10:36 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
> +            value = MessageFormat.format(value, params);
I just wanted to ask if you wanna also implement a PropertyPlaceholderResolver in here, with your comment.. I think I know the answer :D Reference of the resolver used by Spring: https://github.com/spring-projects/spring-framework/blob/main/spring-core/src/main/java/org/springframework/util/PropertyPlaceholderHelper.java

2023-10-12 10:39 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
> +        final ResourceBundle bundle = getBundle(locale);
this can return null -> throwing a NPE later on -> should there be a null check and return ""?

2023-10-12 10:44 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
> +                    I18NUtil.getClassLoader());
Should this be intelligent enough so that e.g. a missing Resourcebundle for a locale fallsback to other languages? 

We have something like this:

- Passing in GERMAN
- No ResourceBundle found for GERMAN? Return Locale.ROOT (default resource bundle) 

- Passing in GERMAN
- Resourcebundle found for GERMAN
- Resourcebundle does not contain a translation for the key.. search in ResourceBundle Locale.ROOT for the key
- key in ROOT found -> return the root translation + debug/info logging 
- key ALSO not in ROOT found -> return key + warn logging

2023-10-12 10:50 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
> +        final ResourceBundle bundle = getBundle(locale);
True if there is no default translation file available.
Returning key if no bundle available as the missing bundle will get a warn log.

2023-10-12 11:01 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
> +public class DefaultI18NProvider implements I18NProvider {
General Question: Should this class be registered as Spring Bean with `ConditionalOnMissingBean` so that it's also available for DI in Spring as default and people can inject / use it even without always asking the Instantiator for it.

2023-10-12 11:14 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
> +public class DefaultI18NProvider implements I18NProvider {
The springInitiator actually falls back on the defaultInitiator on this if no bean found:
```
    public I18NProvider getI18NProvider() {
        int beansCount = context.getBeanNamesForType(I18NProvider.class).length;
        if (beansCount == 1) {
            return context.getBean(I18NProvider.class);
        } else {
            if (loggingEnabled.compareAndSet(true, false)) {
                LoggerFactory.getLogger(SpringInstantiator.class.getName())
                        .info("The number of beans implementing '{}' is {}. Cannot use Spring beans for I18N, "
                                + "falling back to the default behavior",
                                I18NProvider.class.getSimpleName(), beansCount);
            }
            return super.getI18NProvider();
        }
    }
```

2023-10-12 11:15 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
> +public class DefaultI18NProvider implements I18NProvider {
Also having Spring annotations is a bit problematic as this is outside of spring in the normal framework.

2023-10-12 11:20 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
> +public class DefaultI18NProvider implements I18NProvider {
Thanks for the explanation! Yeah, I was wondering if it would be worth to add it to the VaadinApplicationConfiguration like a bean:

```java
  @Bean
  @ConditionalOnMissingBean(value = I18NProvider.class)
  public DefaultI18NProvider vaadinI18nProvider() {
    return new DefaultI18NProvider(/* get locales from somewhere*/);
  }

```

2023-10-12 11:24 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
> +                    I18NUtil.getClassLoader());
Well there is an inherent default here that if you have 
`translations_fi_FI.properties` and `translations.properties` requesting for the Finnish locale `Locale("fi","FI)` will return you the fi_FI bundle, but then requesting for instance `Locale("de")` will return the `translations.properties` which is basically then the ROOT (or default) bundle.

2023-10-12 11:25 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
> +                    I18NUtil.getClassLoader());
Recursing bundles down is perhaps not inside the feature scope for this default implementation, but could be a later enhancement

2023-10-12 11:27 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
> +                    I18NUtil.getClassLoader());
Understandable :) (can be closed)

2023-10-13 09:27 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/i18n/I18NUtil.java
> +        if (bundleFolder.exists() && bundleFolder.isDirectory()) {
And it seems not to work even if I put the translations in a JAR file, although I don't know if this can be considered a valid use case for this feature.

```
bundleFolder= file:/xxxxxxxxx/vaadin/starters/skeleton-starter-flow/v-i18n.jar!/vaadin-i18n
bundleFolder.exists() = false
```

2023-10-13 09:32 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/i18n/I18NUtil.java
> +        if (bundleFolder.exists() && bundleFolder.isDirectory()) {
Good Point. I'll look into it and fix the jar path. It will require using the FileSystem, but should be doable.

2023-10-13 09:42 UTC, tltv requested changes

2023-10-13 09:42 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
> +    // Get bundles named `translations` from `translation` folder.
Shouldn't this say "from `vaadin-i18n` folder" instead.

2023-10-13 09:42 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/i18n/I18NUtil.java
> +                    .filter(file -> file.getName().endsWith(PROPERTIES_SUFFIX))
This may need to also filter by `file.getName().startsWith(BUNDLE_FILENAME)` to ignore other files than translation files.

2023-10-13 09:53 UTC, mcollovati commented on flow-server/src/test/java/com/vaadin/flow/i18n/DefaultInstantiatorI18NTest.java
> +
It could be nice to add an assertion to ensure that the base language bundle is taken if we provide the also country and the specific bundle file does not exist.
Of course, not a blocker

```
            Assert.assertEquals("deutsch",
                    i18NProvider.getTranslation("title", new Locale("de", "AT")));
```

2023-10-13 09:58 UTC, mcollovati commented on flow-server/src/test/java/com/vaadin/flow/i18n/I18NUtilTest.java
> +}
nit: new line missing
```suggestion
}

```

2023-10-13 10:02 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/i18n/I18NUtil.java
> +public final class I18NUtil {
added javadoc. 
This is basically internal, but it is used from outside package.

2023-10-13 10:02 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/i18n/I18NUtil.java
> +                    .filter(file -> file.getName().endsWith(PROPERTIES_SUFFIX))
added

2023-10-13 10:02 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/i18n/I18NUtilTest.java
> +}
added

2023-10-13 10:02 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
> +    // Get bundles named `translations` from `translation` folder.
fixed

2023-10-13 10:36 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/i18n/DefaultInstantiatorI18NTest.java
> +
Added tests on this, even though it is a `ResourceBundle` feature.

2023-10-13 13:47 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/i18n/I18NUtil.java
> +        if (bundleFolder.exists() && bundleFolder.isDirectory()) {
Now it knows how to handle the files inside jars also.

2023-10-13 16:10 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/i18n/I18NUtil.java
> +        if (bundleFolder.exists() && bundleFolder.isDirectory()) {
Works great with the resource bundle in JAR!

However, is still fails with the Spring Boot fat JAR, both by adding the properties files in the project or in external JAR.

```
bundleFolder = {File@6570} "file:/xxxx/skeleton-starter-flow-spring/target/spring-skeleton-1.0-SNAPSHOT.jar!/BOOT-INF/classes!/vaadin-i18n"
pathInJar = "/BOOT-INF/classes!/vaadin-i18n"


bundleFolder = {File@8348} "file:/xxxx/skeleton-starter-flow-spring/target/spring-skeleton-1.0-SNAPSHOT.jar!/BOOT-INF/lib/i18n-1.0.jar!/vaadin-i18n"
pathInJar = "/BOOT-INF/lib/i18n-1.0.jar!/vaadin-i18n"
```

For the first case, removing the `!` from `pathInJar` makes the solution work. The second case is more tricky.
I wonder if it could be better to provide some specific implementations in the Spring add-on, or if we have to find some hack 
 to add in the current implementation  :thinking:

2023-10-13 16:50 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/i18n/I18NUtil.java
> +        if (bundleFolder.exists() && bundleFolder.isDirectory()) {
I would suggest to go with a spring based solution in the spring module based on 

ResourcePatternResolver allowing to get all resources within a folder in a spring boot application within one line of code - foul and future proof :) relying on it for years to load our default configurations

2023-10-16 05:08 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
> +            getLogger().warn("Missing resource", e);
added

2023-10-16 05:08 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/i18n/I18NUtil.java
> +                getLogger().debug("failed to read jar file contents", e);
As there is no need to actually handle files I removed fileSystem usage and we just handle jar entry file names as that is enough. Updated exception to contain file name

2023-10-16 05:08 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/i18n/I18NUtil.java
> +                    "Tried to get new filesystem, but it already existed for target uri.",
removed fileSystem usage so this log doesn't exist anymore.

2023-10-16 05:10 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/i18n/I18NUtil.java
> +        if (bundleFolder.exists() && bundleFolder.isDirectory()) {
Seeing as this was supposed to be a small enhancement, I would propose to open a new ticket for creating Spring-Boot fat Jar support by extending the default translation with Spring parts in the spring add-on

2023-10-16 06:22 UTC, mcollovati requested changes

2023-10-16 06:22 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/i18n/I18NUtil.java
> +                        + file.substring(6, file.indexOf('!')) + "'contents",
```suggestion
                        + file.substring(6, file.indexOf('!')) + "' contents",
```

2023-10-16 06:22 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/i18n/I18NUtil.java
> +                        file.substring(6, file.indexOf('!'))).entries();
The substring seems not to work correctly on Linux

```
resource : jar:file:/home/marco/projects/vaadin/starters/skeleton-starter-flow/v-i18n.jar!/vaadin-i18n
file: file:/home/marco/projects/vaadin/starters/skeleton-starter-flow/v-i18n.jar!/vaadin-i18n
substring: home/marco/projects/vaadin/starters/skeleton-starter-flow/v-i18n.jar


[qtp14050562-55] DEBUG com.vaadin.flow.i18n.I18NUtil - failed to read jar file 'home/marco/projects/vaadin/starters/skeleton-starter-flow/v-i18n.jar'contents
java.nio.file.NoSuchFileException: home/marco/projects/vaadin/starters/skeleton-starter-flow/v-i18n.jar
```

2023-10-16 06:31 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/i18n/I18NUtil.java
> +                        file.substring(6, file.indexOf('!'))).entries();
i have that fixed already, but running the test on WSL is really slow.

2023-10-16 06:32 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/i18n/I18NUtil.java
> +                        + file.substring(6, file.indexOf('!')) + "'contents",
done

2023-10-16 06:55 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/i18n/I18NUtil.java
> +        if (bundleFolder.exists() && bundleFolder.isDirectory()) {
It looks like we need a ticket as well for the Quarkus add-on.
The class loader used to detect the bundle folder (` I18NUtil.class.getClassLoader()`) returns null, whereas it works using `Thread.currentThread().getContextClassLoader()`
Would it be possible to replace the `protected static ClassLoader getClassLoader()` method with a non-static version, so it can be overridden to provide the best class loader for each environment?
Or can we have the class loader reference as class member, provided by an additional constructor?

2023-10-16 07:17 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/i18n/I18NUtil.java
> +        if (bundleFolder.exists() && bundleFolder.isDirectory()) {
We can use current as that's not a problem. Sending a loader around becomes too complex for testing from instantiator

2023-10-16 08:25 UTC, mcollovati approved these changes

2023-10-18 05:27 UTC, merged