feat: Use binding object to check for Binder#hasChanges
vaadin/flow pull request #17861
Opened 2023-10-19 16:38 UTC by benedikt-roth

## Description

Allows to check whether specific binding has been changed. So far there is only a generic Binder#hasChanges, which checks all bindings. The new method allows to check whether a specific binding has changes.

Fixes #17395

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [x] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2023-10-19 16:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=17861) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=17861) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=17861) it.</sub>

2023-10-19 16:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=17861) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=17861) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=17861) it.</sub>

2023-10-19 16:45 UTC, mcollovati commented
@benedikt-roth do you mind signing the CLA and formatting the source code as suggested in https://github.com/vaadin/flow/pull/17861#issuecomment-1771359569?

2023-10-20 06:32 UTC, benedikt-roth commented
> @benedikt-roth do you mind signing the CLA and formatting the source code as suggested in [#17861 (comment)](https://github.com/vaadin/flow/pull/17861#issuecomment-1771359569)?

Sure, done that and also fixed the formatting.

2023-10-20 07:21 UTC, mcollovati requested changes
Thanks for the contribution, the change looks good.
I would add tests for `hasChanges` when the binding has been removed from the binder.

I also wonder if we could add the `hasChanges()` method also on the `Binding` interface, so that it would be possible to simply do a `binding.hasChanges()`.
The implementation in `BindingImpl` could use the internal `binder` field to check it `this` binding is in the `changeBindings` set.
And it will throw and `IllegalStateException` if the `binder` is null.

However, this is not mandatory for the PR to be merged

2023-10-20 07:21 UTC, mcollovati commented on flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
> +
We could add a check that `hasChanges` is false just after reading the bean

2023-10-20 07:21 UTC, mcollovati commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +     * Checks whether a field has uncomitted changes.
```suggestion
     * Checks whether a bound field has uncomitted changes.
```

2023-10-20 07:21 UTC, mcollovati commented on flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
> +    public void writeBean_setsHasChangesBindingToFalse() {
The test name doesn't clearly reflect what we are testing, since `writeBean` is never invoked.
Consider changing it to some like `bindinghasChanges_trueWhenFieldValueChanges`
Naming is hard :grin:

2023-10-20 08:05 UTC, benedikt-roth commented on flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
> +    public void writeBean_setsHasChangesBindingToFalse() {
Ah, I changed this multiple times. You are right, this does not really explain what is happening.
Your suggestion looks good. Will use that one.

2023-10-20 08:08 UTC, benedikt-roth commented on flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
> +
Good idea. The more checks the better for this logic.

2023-10-20 08:12 UTC, benedikt-roth commented
> Thanks for the contribution, the change looks good. I would add tests for `hasChanges` when the binding has been removed from the binder.
> 
> I also wonder if we could add the `hasChanges()` method also on the `Binding` interface, so that it would be possible to simply do a `binding.hasChanges()`. The implementation in `BindingImpl` could use the internal `binder` field to check it `this` binding is in the `changeBindings` set. And it will throw and `IllegalStateException` if the `binder` is null.
> 
> However, this is not mandatory for the PR to be merged

Let me look into this one. Definitely would be useful. If it is a quick change, let's include this in this PR.

2023-10-20 09:23 UTC, benedikt-roth commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +         * having uncommitted changes.
@mcollovati please check if this description is a good one

2023-10-20 09:42 UTC, mcollovati requested changes

2023-10-20 09:42 UTC, mcollovati commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +         * having uncommitted changes.
I would not mention Binder here, as the fact we check the change status on Binder is an implementation detail.
Maybe something like "Checks whether the field the binding use has uncommitted changes"?

2023-10-20 09:42 UTC, mcollovati commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +         *             been declared here.
I would not mention the Binder field here, as it is an implementation detail.
What about "if the binding is no longer attached to a Binder", as in the exception thrown by `validate(...)`?
```suggestion
         * @throws IllegalStateException
         *             if the binding is no longer attached to a Binder.
```

2023-10-20 09:42 UTC, mcollovati commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +         * @return True if field has uncommitted changes
```suggestion
         * @return {@literal true} if the field the binding uses has uncommitted changes, otherwise {@literal false}.
```

2023-10-20 09:42 UTC, mcollovati commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +        boolean hasChanges() throws IllegalStateException;
I would skip the exception declaration, as it is a runtime exception.
I think that mentioning the exception in the javadoc is enough.

```suggestion
        boolean hasChanges() throws IllegalStateException;
```

2023-10-20 09:42 UTC, mcollovati commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +                throw new IllegalStateException();
We need an informative message for this exception

```suggestion
                throw new IllegalStateException("This Binding is no longer attached to a Binder");
```

2023-10-20 09:42 UTC, mcollovati commented on flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
> +
Please add also a test that checks the exception is thrown if the binding is unbound.

2023-10-20 10:22 UTC, benedikt-roth commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +        boolean hasChanges() throws IllegalStateException;
Fair enough

2023-10-20 10:46 UTC, benedikt-roth commented on flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
> +
done ✅

2023-10-20 11:08 UTC, mcollovati approved these changes
The change looks good to me. Let's see if the validation passes.
Good job @benedikt-roth

2023-10-20 12:24 UTC, merged