feat: Add Component/Element to ErrorEvent
vaadin/flow pull request #17879
Opened 2023-10-23 12:00 UTC by caalador

Now it is possible to query
for the element/component that
threw the exception leading
to the ErrorEvent.

Fixes #13044

2023-10-25 10:57 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java
> +                                    new ErrorEvent(e, entry.getStateNode()));
Instead of "leaking" StateNodes outside the state tree, would it be better to look up a potential element or component here?

2023-10-25 11:29 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java
> +                                    new ErrorEvent(e, entry.getStateNode()));
I was trying to keep StateNode from knowing Element and Component. We could ofc do the search directly in the constructor instead of storing the node to the ErrorEvent

2023-10-25 11:55 UTC, mshabarov requested changes

2023-10-25 11:55 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/ErrorEvent.java
> +    public Optional<Component> getComponent() {
Can be simplified as
```java
    public Optional<Component> getComponent() {
        return getElement().flatMap(Element::getComponent);
    }
```
giving less code and no need to test `getElement()` separately.

2023-10-26 06:28 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/ErrorEvent.java
> +    public Optional<Component> getComponent() {
done

2023-10-26 06:35 UTC, mshabarov approved these changes

2023-10-26 06:51 UTC, merged