feat: Add ConditionalOnMissingBean for ServletRegistration
vaadin/flow pull request #17883
Opened 2023-10-23 14:34 UTC by mshabarov

## Description

Adds `ConditionalOnMissingBean` for `ServletRegistration` bean in Spring auto configuration, so it can be customisable and extendable.

Related-to https://github.com/vaadin/flow/issues/17669
Related-to https://github.com/vaadin/flow/pull/17671

Kudos @oliveryasuna for contribution.

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2023-10-23 16:14 UTC, mcollovati requested changes

2023-10-23 16:14 UTC, mcollovati commented on vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringBootAutoConfigurationConditionalTest.java
I think this test can be simplified by using `WebApplicationContextRunner` instead of `ApplicationContextRunner`.
This way we can remove:
* all class level annotations
* the ` WEB_APPLICATION_CONTEXT` ThreadLocal 
* the need for `TestExecutionListener` implementation
* the `vaadin-testbench-unit-shared` dependency in POM file

The test class should look like

```java
public class SpringBootAutoConfigurationConditional2Test {

    @Test
    public void customServletRegistrationBean() {
        new WebApplicationContextRunner()
                .withConfiguration(AutoConfigurations
                        .of(SpringBootAutoConfiguration.class))
                .withUserConfiguration(
                        ServletRegistrationBeanConfiguration.class)
                .run(context -> assertThat(context)
                        .getBean(ServletRegistrationBean.class).isInstanceOf(
                                ServletRegistrationBeanConfiguration.MockServletRegistrationBean.class));
    }

    @Configuration(proxyBeanMethods = false)
    public static class ServletRegistrationBeanConfiguration {

        @Bean
        @Autowired
        public ServletRegistrationBean<SpringServlet> servletRegistrationBean(
                final WebApplicationContext webApplicationContext) {
            return new MockServletRegistrationBean(webApplicationContext);
        }

        public static class MockServletRegistrationBean
                extends ServletRegistrationBean<SpringServlet> {

            public MockServletRegistrationBean(
                    final WebApplicationContext webApplicationContext) {
                super(new SpringServlet(webApplicationContext, false));
            }
        }

    }
}
```

2023-10-24 06:26 UTC, mshabarov commented on vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringBootAutoConfigurationConditionalTest.java
Awesome suggestion @mcollovati ! Works perfectly.

2023-10-24 06:29 UTC, mcollovati commented on vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringBootAutoConfigurationConditionalTest.java
> +        @Autowired
nit: IIRC Autowired annotation should not be required anymore
```suggestion
        @Autowired
```

2023-10-24 06:31 UTC, mshabarov commented on vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringBootAutoConfigurationConditionalTest.java
> +        @Autowired
Removed

2023-10-24 07:16 UTC, mcollovati approved these changes

2023-10-24 07:16 UTC, merged