feat: use devBundle from build folder
vaadin/flow pull request #17977
Opened 2023-11-02 11:01 UTC by caalador

Move devBundle to build folder
and create a single compressed file
for devBundle that can be committed
into the versioning system.

Fixes #16874

2023-11-03 12:54 UTC, mshabarov requested changes

2023-11-03 12:54 UTC, mshabarov commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
> +    private boolean compressBundle;
Turn off compressing for default bundle makes sense, but do you think anyone would want to turn it off in their projects? Maybe we could simplify it at this point and remove config parameter to always have compressing except internal default bundle generation?

2023-11-03 12:54 UTC, mshabarov commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinCleanTask.kt
> +                "${project.projectDir}/${Constants.DEV_BUNDLE_COMPRESSED_FILE_LOCATION}",
Better to clean the whole `bundles` folders, as custom prod bundle will also be cached in this folder soon.

2023-11-03 12:54 UTC, mshabarov commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CleanFrontendMojo.java
> +            if (bundleDir.exists() && bundleDir.listFiles().length == 0) {
I propose to just delete the whole `bundles` folder.

2023-11-03 13:25 UTC, mshabarov commented
Noticed two more things after local testing:
- dev-bundle is re-used correctly when Vaadin builds the bundle once and says no bundle is needed for next runs. But if I do `mvn clean`, and restart my app having still `dev.bundle` in `src/main/bundles` it nevertheless says that the bundle is needed. I expected that it should unzip the bundle before running bundle validation. Seems like it validates against default bundle in this case, not against custom bundle.
- README file should be placed into `src/main/bundles` as well, as it is kind of documentation for developer, wondering what is this weird file.

2023-11-03 14:50 UTC, tltv requested changes

2023-11-06 06:22 UTC, caalador commented
README moved to the bundle folder. 
Fixed check for compressed usage.

2023-11-06 07:55 UTC, mshabarov submitted a review, later dismissed
Re-tested with latest changes, works as expected.
Haven't tested the case, when default bundle is enough, because with snapshots it's problematic.
Looks good to me.

2023-11-06 09:26 UTC, tltv requested changes

2023-11-06 09:26 UTC, tltv commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/DevBundleUtilsTest.java
> +    public void compileDevBundle_uncompileDevBundle_filesHaeSameHash()
```suggestion
    public void compileDevBundle_uncompileDevBundle_filesHasSameHash()
```

2023-11-06 09:34 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/CompressionException.java
> + * @since
since should be filled when released.

2023-11-06 09:38 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/DevBundleUtils.java
> +    public static String findBundleStatsJson(File projectDir,
now added

2023-11-06 09:39 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/CompressionException.java
> + * @since
added version as it is basically certain. We have a updateSinceTags.sh script that I guess is never run even though it should be for when a version is broken out from main.

2023-11-06 09:49 UTC, tltv requested changes

2023-11-06 10:39 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/CompressUtil.java
> +                    "Failed to compress dev bundle files to '"
done

2023-11-06 11:01 UTC, tltv approved these changes

2023-11-06 11:15 UTC, merged