feat: reuse the production bundle if no changes
vaadin/flow pull request #17997
Opened 2023-11-07 08:59 UTC by tltv

Makes a copy of the production bundle in `src/main/bundles/prod.bundle` zip file to make it possible to reuse it without recreating same unchanged bundle again. When `prod.bundle` exists, it will be used as a primary source for `stats.json` file.

Fixes: https://github.com/vaadin/flow/issues/16886

2023-11-08 10:34 UTC, caalador requested changes

2023-11-08 10:34 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
> +    public void noDevFolder_bundleCompressedFileExists_noBuildRequired()
I would perhaps do another test for prod bundle as now the test name says noDevFolder, but also tests production bunlde that doesn't use the devFolder at all for validation.
The use case is a bit different for the 2 cases.

2023-11-08 10:34 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
> +    public void noDevFolderOldDefaultBundle_bundleCompressedFileExists_noBuildRequired()
```suggestion
    public void noFileBundleOrJar_compressedBundleExists_noBuildRequired()
```

2023-11-08 11:30 UTC, tltv commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
> +    public void noDevFolderOldDefaultBundle_bundleCompressedFileExists_noBuildRequired()
Actually this test seems to be wrong, it should mock to return null URL for getResource call or otherwise it would mean that default bundle is indeed found from the jar. However, fixing this won't affect test result as existing custom bundle file prevents the result from changing anyway.

2023-11-08 11:39 UTC, tltv commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
> +    public void noDevFolder_bundleCompressedFileExists_noBuildRequired()
Done

2023-11-08 11:41 UTC, tltv commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +    private static void copyCompressedBundleToProdBundleLocation(
Done

2023-11-09 06:53 UTC, caalador approved these changes

2023-11-09 06:55 UTC, merged