fix: 9376 improve error message when a component is moved from one UI to another.
vaadin/flow pull request #18019
Opened 2023-11-13 09:06 UTC by mvysny

## Description

Improve error message when a component is moved from one UI to another.

Fixes #9376 

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [x] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2023-11-13 09:50 UTC, mcollovati requested changes

2023-11-13 09:50 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
> +                                + "which is not a good idea. This may be caused "
nit: I would maybe replace the "is not a good idea" with "is not recommended"

2023-11-13 09:50 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
> +        // createLocation may be null in production mode. Just return the
```suggestion
        // createLocation is null in production mode. Just return the
```

2023-11-13 09:51 UTC, mcollovati commented
Some minor changes requested, but LGTM. Great job @mvysny

2023-11-13 10:00 UTC, mvysny commented on flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
> +                                + "which is not a good idea. This may be caused "
I agree, fixed.

2023-11-13 10:00 UTC, mvysny commented on flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
> +        // createLocation may be null in production mode. Just return the
Thanks, fixed.

2023-11-13 10:01 UTC, mvysny commented
Thank you @mcollovati , all items should now be resolved.

2023-11-13 10:19 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
>                          "Can't move a node from one state tree to another. "
super small: but it is maybe -I think- a bit more readable and maintainable if the exception message is extracted to a `final static String variable,` and potentially the same variable could be used from the tests to assert if it was the proper error message.

2023-11-13 10:19 UTC, czp13 approved these changes
Looks good to me as well, nice work @mvysny!

2023-11-13 10:41 UTC, mcollovati approved these changes

2023-11-13 10:55 UTC, merged

2023-11-13 10:57 UTC, mvysny commented on flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
>                          "Can't move a node from one state tree to another. "
Ooops, sorry, I merged too hastily and missed your comment. I personally think it's better to have the string constants in-place for better readability, instead of being out-of-place in a String constant, but it's not a very strong opinion. If you'd still like me to extract the message, please reach out to me on Slack and I'll prepare another PR.

2023-11-13 13:09 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
>                          "Can't move a node from one state tree to another. "
No worries, it was a smallish idea/question. Let us not focus on this or block your time or anything :).
And thank you for replying, and taking my comment nicely! 🙇

2024-09-24 12:06 UTC, mvysny commented
More docs on the topic https://mvysny.github.io/cant-move-node/