fix: Do not run NodeTasks in parallel
vaadin/flow pull request #18018
Opened 2023-11-13 07:32 UTC by Artur-

This should prevent issues when a Spring Boot application is restarted almost immediately after startup. Previously roughly this happened:
1. Start app
2. Start npm install
3. Restart app
4. Clean node_modules while npm install is still running
5. Fail

Now it should be
1. Start app
2. Start npm install
3. Restart app
4. Wait for npm install to finish
5. npm install finishes but might log some exception as the app was restarted
6. run node tasks including npm install from the restarted app
7. It should work

2023-11-13 07:53 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +            getLogger().error("Error releasing lock file", e);
Not sure if it makes sense: could we have a retry mechanism here? There might be IOExceptions happening while reading the content of the lock file, and IOExceptions while deleting the lock file for many different reasons...

2023-11-13 08:59 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +        while (lockFile.toFile().exists()) {
The locking does not need to be first come, first served. Also it can be noted that this locking is not 100% reliable as it does not use atomic operations to acquire the lock. It only tries to resolve the case where there are no race conditions but clearly one node tasks instance running and another one starting up in the middle of the first one

2023-11-13 09:33 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +        while (lockFile.toFile().exists()) {
Well, in that case I found the added test a bit off:
```
Assert.assertEquals(List.of("Start 1", "End 1", "Start 2", "End 2"),
                result);
```

2023-11-13 11:31 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +        while (lockFile.toFile().exists()) {
How?

2023-11-13 14:19 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +        while (lockFile.toFile().exists()) {
The test needs the "Start 2" to always happen after "Start 1" and "End 1". 
What you described above about the locking strategy not being First come first served, seems to be accepting the following case: 
```
Start 1 Start 2 End 2 ...
```
Or maybe I'm understanding it in a wrong way.

2023-11-13 14:54 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +        while (lockFile.toFile().exists()) {
With two threads running concurrently the valid results are
* "Start 1 End 1 Start 2 End 2"
* "Start 2 End 2 Start 1 End 1"

Anything else means this PR is broken.
In the test, there is a sleep to force the first case to make the test easier.

If you start the two threads in the test at the same time, then it will fail part of the time. But that is not the real world case.

2023-11-16 09:10 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +                        + getClass().getSimpleName() + " process to finish", e);
Added pid to message

2023-11-16 09:10 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +                    Thread.sleep(500);
Added the process command line to the pid so that we compare that it is the same process that is still running

Also added logging when there is a lock and we start waiting

2023-11-16 10:09 UTC, mcollovati requested changes

2023-11-16 10:09 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +                    Thread.sleep(500);
Great solution!
Only thing that I noticed is that probably `loggedWaiting` should be defined outside the while loop; otherwise the log message is printed every time.

2023-11-16 10:09 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
>              } catch (Exception e) {
Should we handle `InterruptedException` to reset the interrupt flag?

2023-11-16 10:19 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +                    Thread.sleep(500);
Oops

2023-11-16 10:19 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
>              } catch (Exception e) {
You mean something like this?

2023-11-16 10:32 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +            getLogger().error("Error releasing lock file", e);
It could be good to add the lock file path to the message, as we do in the catch block for `writeLockFile()`

2023-11-16 14:33 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +            getLogger().error("Error releasing lock file", e);
Added filename to log messages

2023-11-16 15:02 UTC, mcollovati submitted a review, later dismissed

2023-11-16 15:22 UTC, mcollovati approved these changes

2023-11-16 15:58 UTC, merged