feature: Implement RangeInput component. Fixes #3483
vaadin/flow pull request #18054
Opened 2023-11-16 16:42 UTC by mvysny

## Description

Implement a component for `<input type="range">`.

Fixes #3483 

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2023-11-17 15:06 UTC, tepi commented
Not sure if `RangeInput` should/could extend `com.vaadin.flow.component.html.Input`? At least some methods are duplicated.

2023-11-17 19:03 UTC, mvysny commented
@tepi unfortunately the type of the value of the Input component is fixed to String and can not be changed in overriding class. I thought of having a CustomField, wrapping Input, but that was even more complicated. I believe the current approach to be the most straightforward one.

2023-11-20 15:19 UTC, mcollovati requested changes

2023-11-20 15:19 UTC, mcollovati commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/RangeInput.java
> +     * Returns the minimum value.
nit: Flow team conventions, use "gets" instead of "returns"
```suggestion
     * Gets the minimum value.
```

2023-11-20 15:19 UTC, mcollovati commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/RangeInput.java
> +     * Returns the maximum value.
nit: Flow team conventions, use "gets" instead of "returns"
```suggestion
     * Gets the maximum value.
```

2023-11-20 15:19 UTC, mcollovati commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/RangeInput.java
> +     * Non-standard Attribute.
```suggestion
     * Gets the orientation of the range slider
     * <p>
     * </p>
     * Non-standard Attribute.
```

2023-11-20 15:19 UTC, mcollovati commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/RangeInput.java
> +     * Non-standard Attribute.
```suggestion
     * Sets the orientation of the range slider
     * <p>
     * </p>
     * Non-standard Attribute.
```

2023-11-20 15:19 UTC, mcollovati commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/RangeInput.java
> +        updateEnabled();
What about performing the operation only if the new read-only value is different from the current one?

2023-11-20 15:19 UTC, mcollovati commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/RangeInput.java
> +        updateEnabled();
What about performing the operation only if the new enabled value is different from the current one?

2023-11-20 15:56 UTC, mvysny commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/RangeInput.java
> +            .attributeWithDefault("type", "text");
The default value in this context refers to the default value of the attribute as specified by the HTML spec. According to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input the "text" is the default.

If I would use `attributeWithDefault("type", "range");` and then set the PropertyDescriptor value to "range", it would actually remove the "type" attribute from the DOM, causing the input to be of type "text", which is not what we want.

2023-11-20 16:04 UTC, mvysny commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/RangeInput.java
> +import com.vaadin.flow.component.*;
Oops, thanks! Done.

2023-11-20 16:07 UTC, mvysny commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/RangeInput.java
> +        applyChangeTimeout();
This code is actually copied from the existing `Input` element. Since Input doesn't introduce this kind of optimization, I thought that this kind of optimization doesn't bring much performance benefits.

Yet, please let me know if you would still like me to perform this optimization.

2023-11-20 16:07 UTC, mvysny commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/RangeInput.java
> +        applyChangeTimeout();
This code is actually copied from the existing Input element. Since Input doesn't introduce this kind of optimization, I thought that this kind of optimization doesn't bring much performance benefits.

Yet, please let me know if you would still like me to perform this optimization.

2023-11-20 16:08 UTC, mvysny commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/RangeInput.java
> +     * Returns the maximum value.
Done.

2023-11-20 16:12 UTC, mcollovati commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/RangeInput.java
Got it, and I agree. Let's leave it as a potential future improvement.

2023-11-20 16:14 UTC, mvysny commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/RangeInput.java
> +        updateEnabled();
Not sure about this. `HasValueAndElement.setReadOnly()` doesn't perform this kind of optimization, and this one is the default implementation for all HasValue. I'm not sure whether only this particular component should optimize on this.

2023-11-20 16:15 UTC, mvysny commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/RangeInput.java
> +        updateEnabled();
Same as above: `HasEnabled.setEnabled()` doesn't perform this kind of optimization; I'm not sure whether only this particular component should optimize on this.

2023-11-20 16:16 UTC, mvysny commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/RangeInput.java
> +     * Non-standard Attribute.
Done,  thank you.

2023-11-20 16:28 UTC, mcollovati commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/RangeInput.java
> +        applyChangeTimeout();
Ok, thanks. Let's do it the same way as in Input

2023-11-20 16:31 UTC, mcollovati approved these changes

2023-11-20 16:31 UTC, mcollovati commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/RangeInput.java
> +        applyChangeTimeout();
Ok, thanks. Let's do it the same way as in Input

2023-11-20 16:31 UTC, merged