feat: add react router defaults
vaadin/flow pull request #18058
Opened 2023-11-17 08:27 UTC by caalador

Enabling the reactRouter feature flag will now 
add the necessary package dependencies and
generate the required frontend files
to Frontend/generated/flow

With this one should be able to run a flow project
using react router instead of vaadin-router

2023-11-17 08:29 UTC, knoobie commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react/package.json
> +    "lit": "3.0.2",
``
```suggestion
    "lit": "3.1.0",
```

Artur has updated it to 3.1.0 --> updated that no mismatch happens

2023-11-17 08:46 UTC, caalador commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react/package.json
> +    "lit": "3.0.2",
Need to have a shared/common dependencies so the versions do not differ.

2023-11-20 12:57 UTC, mshabarov requested changes

2023-11-20 12:57 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> + * Generate <code>index.ts</code> if it is missing in frontend folder.
Should list the files actually generated, not `index.ts`.

2023-11-20 12:57 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +                writeFile(routesTsx, getFileContent("routes.tsx"));
Just to clarify: if `routes.tsx` already exists, and Flow won't modify it, does it mean that adding `...serverSideRoutes` to it is a manual action required by developers? 

Can we automate it by adding it always if not there?

2023-11-20 13:33 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +                writeFile(routesTsx, getFileContent("routes.tsx"));
At the moment it means manually adding.
Automatically adding it has the problems of identifying if it is there and I at least do not know the expected setup types for the router that I could generate a good automatic add to the array/object/tree of an existing route setup.

2023-11-20 14:15 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +                writeFile(routesTsx, getFileContent("routes.tsx"));
Ok, fair enough, then we can consider doing this separately, as it needs a smart way of determining a proper place in `routes` to inject server-side routes.

2023-11-20 14:21 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> + * Generate <code>index.ts</code> if it is missing in frontend folder.
```suggestion
 * Generates React related files <code>App.tsx</code> and <code>routes.tsx</code>
 * if they are missing in frontend folder, as well as <code>Flow.tsx</code> file,
 * that contains codes for integrating React router with Flow routes.
```

2023-11-20 14:21 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> + * Generate <code>index.ts</code> if it is missing in frontend folder.
Or something similar.

2023-11-21 04:26 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> + * Generate <code>index.ts</code> if it is missing in frontend folder.
Fixed javaDoc.

2023-11-21 06:59 UTC, mshabarov approved these changes

2023-11-21 08:26 UTC, mshabarov approved these changes
Tested with a case, when I had fresh Hilla+React starter app, added Flow views and run the app.
Then manually I was needed to add `serverSideRoutes` as follows
```javascript
import {serverSideRoutes} from "Frontend/generated/flow/Flow";
...
export const routes = [
  {
    ...
    children: [
      { path: '/', element: <HelloWorldView />, handle: { title: 'Hello World' } },
      { path: '/about', element: <AboutView />, handle: { title: 'About' } },
        ...serverSideRoutes
    ],
  },
] as RouteObject[];
...
```
Then the navigation worked as expected.
We may probably want to add `import {serverSideRoutes} from "Frontend/generated/flow/Flow";` automatically, but this is for further improvements.

2023-11-21 08:27 UTC, merged