fix: consider routes not-public if access control is disabled
vaadin/flow pull request #18072
Opened 2023-11-20 09:20 UTC by mcollovati

When navigation access control is disabled, Flow cannot decide whether a route is public or not.
This change makes the `isAnonymousRoute` method, used as Spring Security request matcher, always return false if the navigation access control is disabled.

2023-11-20 09:28 UTC, knoobie commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/RequestUtil.java
> +                    "Navigation Access Control disable. Cannot determine if {} refers to a public view",
Would it make sense to only print this in development mode and there print it with INFO? If I disable the access control and do a production build, I hopefully know what I've done.. and in development I'm always reminded what I've done 😅

2023-11-20 10:01 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/RequestUtil.java
> +                    "Navigation Access Control disable. Cannot determine if {} refers to a public view",
Using INFO level in development mode could be a good idea, to immediately spot a configuration issue.
However, I'll print the message also in production, at DEBUG level.

2023-11-20 10:14 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/RequestUtil.java
> +                    "Navigation Access Control disable. Cannot determine if {} refers to a public view",
done

2023-11-20 10:27 UTC, knoobie commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/RequestUtil.java
> +                    "Navigation Access Control disable. Cannot determine if {} refers to a public view",
Just something to consider: atLevel comes from slf4j 2.0 which could create problems if people use Vaadin in container that enforce older versions - even tho Vaadin and a lot of other libraries already depend on 2.0, using the "newer" APis could create a risk for those "older" app servers

2023-11-20 11:09 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/RequestUtil.java
> +                    "Navigation Access Control disable. Cannot determine if {} refers to a public view",
Good point! Let's use a good old if statement

2023-11-20 14:14 UTC, czp13 commented on vaadin-spring/src/test/java/com/vaadin/flow/spring/security/RequestUtilTest.java
> +            Assert.assertFalse(requestUtil.isAnonymousRoute(request));
Maybe just for me but `Anonymous` is not the same as public (maybe it is referring to Anonymous being allowed). It would make sense in my eyes to overload this method (as renaming can be challenging for backward compatibility) with `isPublicRoute()` or `isAnonymousAllowedRoute()` (isPublicRoute is better to my eyes) method and deprecate the other.

2023-11-20 14:15 UTC, czp13 submitted a review, later dismissed
I had a nitty comment, but looks good to me. Nice work.

2023-11-21 08:17 UTC, mshabarov requested changes
Message text suggestion, otherwise looks good.

2023-11-21 08:17 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/RequestUtil.java
> +            String message = "Navigation Access Control disable. Cannot determine if {} refers to a public view";
```suggestion
            String message = "Navigation Access Control is disabled. Cannot determine if {} refers to a public view, thus access is denied. Please add an explicit request matcher rule for this URL.";
```

2023-11-21 08:38 UTC, mcollovati commented on vaadin-spring/src/test/java/com/vaadin/flow/spring/security/RequestUtilTest.java
> +            Assert.assertFalse(requestUtil.isAnonymousRoute(request));
I think the name originally related to the `@AnonymousAllowed` annotation put on a view to make it public.
I could make sense to rename it and add a deprecate method with the current name.
@mshabarov what do you think?

2023-11-21 08:52 UTC, mshabarov commented on vaadin-spring/src/test/java/com/vaadin/flow/spring/security/RequestUtilTest.java
> +            Assert.assertFalse(requestUtil.isAnonymousRoute(request));
I don't see any problems with the naming here. One can argue that "anonymous" better reflects the status of user in terms of authentication and this name is better aligned with the annotation. I'd proposed to revisit it if we see any further complains from community.

2023-11-21 10:45 UTC, mshabarov approved these changes

2023-11-21 10:45 UTC, merged