feat: Websocket connection for debugWindow could only work from localhost and could be configurable.
vaadin/flow pull request #18079
Opened 2023-11-20 18:22 UTC by czp13

## Description

Adding a check to DebugWindow to see if it is connected from localhost or not. 
Additionally, it shall be configurable to allow customers to override and still use localhost if they wish.

WIP:
- need to ad some option/method to customize it,
- need to add test,
- need to test it,

Fixes # (issue)
- https://github.com/vaadin/flow/issues/18062

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guide-line.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [x] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2023-11-21 06:59 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
>          resource.suspend(-1);
I don't know but I think we should not suspend the connection if it is not allowed.

2023-11-21 06:59 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
> +                getLogger().info("Unable to resolve remote address {}",
If we are not sure it's localhost, we should probably prevent it and not allow it

2023-11-21 06:59 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
> +                    return;
Isn't this the case that should be allowed, so it should run the init code below?

2023-11-21 15:28 UTC, czp13 commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
>          resource.suspend(-1);
Ok, let's not suspend it. Is there any way or idea how to communicate with the client. 

We have this below when we let the instructions going further and not exit from the method:
```
        resource.getBroadcaster().broadcast("{\"command\": \"hello\"}",
                resource);
               
```
 Maybe we could have something similar saying that other than localhost is not supported or just log out something and do not say anything to clients?

2023-11-21 15:29 UTC, czp13 commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
> +                    return;
Very true :), before writing tests, these kind of problems can happen :D I am fixing it!

2023-11-21 16:23 UTC, czp13 commented
First test validation was flaky as I see, but this one shall be good.
(`BasicViewsITinvalidViewShowsNotFound()` was failing, some context, env was not ready my wild guess).

2023-11-21 17:03 UTC, mcollovati commented
As a side note, `BasicViewsIT` is indeed flaky, but it was not the cause of the build failure. The culprit was `FrontendLiveReloadIT.modifyThemeFile` (an issue already exists)

```
Error:  Failures: 
Error:  com.vaadin.flow.uitest.multimodule.ui.FrontendLiveReloadIT.modifyThemeFile[any_Chrome_]
Error:    Run 1: FrontendLiveReloadIT.modifyThemeFile:129 expected:<rgba([173, 216, 230, 1])> but was:<rgba([0, 0, 0, 0])>
Error:    Run 2: FrontendLiveReloadIT.modifyThemeFile:129 expected:<rgba([173, 216, 230, 1])> but was:<rgba([0, 0, 0, 0])>
Error:    Run 3: FrontendLiveReloadIT.modifyThemeFile:129 expected:<rgba([173, 216, 230, 1])> but was:<rgba([0, 0, 0, 0])>
[INFO] 
[INFO] 
Error:  Tests run: 3, Failures: 1, Errors: 0, Skipped: 0
```

If you check the logs relative to `BasicViewsIT`, you can see that they passed at the second attempt done in the same build

```
Warning:  Flakes: 
Warning:  com.vaadin.flow.servlet.BasicViewsIT.helloViewShown[any_Chrome_]
Error:    Run 1: BasicViewsIT.helloViewShown:37 » NoSuchElement No element with tag <*> found with the attributes [id='view'] using index 0
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.15.0', revision: '1d14b5521b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.2.0-1016-azure', java.version: '17.0.9'
Driver info: driver.version: unknown
[INFO]   Run 2: PASS
[INFO] 
Warning:  com.vaadin.flow.servlet.BasicViewsIT.invalidViewShowsNotFound[any_Chrome_]
Error:    Run 1: BasicViewsIT.invalidViewShowsNotFound:44
[INFO]   Run 2: PASS
[INFO] 
Warning:  com.vaadin.flow.servlet.BasicViewsIT.rootViewShown[any_Chrome_]
Error:    Run 1: BasicViewsIT.rootViewShown:30 » NoSuchElement No element with tag <*> found with the attributes [id='view'] using index 0
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.15.0', revision: '1d14b5521b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.2.0-1016-azure', java.version: '17.0.9'
Driver info: driver.version: unknown
[INFO]   Run 2: PASS
[INFO] 
[INFO] 
Warning:  Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Flakes: 3
```

2023-11-21 21:35 UTC, czp13 commented
@mcollovati Hmm, interesting. Maybe my memory fails me, but I recall seeing a build fail due to the BasicViewsIT class's invalidViewShowsNotFound method. However, my rerun resulted in the validation passing. Perhaps there were multiple failures here due to flaky tests?

Anyway, I believe my added tests and the fixed tests should pass, so nothing related to these code changes on this PR should break the tests. 🙇 (I hope :D 🙏 )

2023-11-22 06:59 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
> +    public void setNonLocalhostEnabled(boolean localhostEnabled) {
I do not understand who could call this and when. What I think we need instead is a system property where you can set the allowed ips, potentially using an asterisk to match many addresses

So by default only the loopback addresses would work but you can set ”192.168.1.2” to allow your other machine (or non docker machine) to connect. Alternatively you set ”192.168.*” to allow your colleagues to use the functionality.

2023-11-22 07:55 UTC, czp13 commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
> +    public void setNonLocalhostEnabled(boolean localhostEnabled) {
:) Okay, we can use a system property or a system environment variable; let's go with a system property.

The requirement I read was about configurability. I did not see a lot of places in the Flow framework where the System variable option is used, so this will be something new. Therefore, I thought an API would be better for this, complete with proper JavaDoc :D, and also an update to the Flow documentation.

2023-11-22 08:08 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
> +    public void setNonLocalhostEnabled(boolean localhostEnabled) {
There are a lot of `vaadin.something` properties, it is not something new

2023-11-22 08:08 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
> +    public void setNonLocalhostEnabled(boolean localhostEnabled) {
They might be disguised as servlet init parameters though

2023-11-22 08:09 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
>          resource.suspend(-1);
If there is no way to deny the connection, then we can just send `{command: 'access-denied'}` or similar and stop the connection in the browser

2023-11-22 08:11 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
> +                getLogger().info("Unable to resolve remote address {}",
We need to take the deny-by-default or deny-unless-we-know-it-is-safe approach to ensure it works as it should

2023-11-23 14:03 UTC, Artur- commented on vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DebugWindowConnectionTest.java
> +    public void onconnect_should_prevent_connection_from_non_localhost() {
I don't think this tests anything anymore

2023-11-23 14:05 UTC, Artur- commented on vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DebugWindowConnectionTest.java
> +    public void onconnect_should_prevent_connection_from_non_localhost() {
Actually this whole test class is kind of redundant. It should be in `IndexHtmlRequestHandlerTest`. There are only two code paths in `DebugWindowConnection` to test:
1. The correct token is present
2. The correct token is not present

2023-11-23 14:21 UTC, czp13 commented on vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DebugWindowConnectionTest.java
> +    public void onconnect_should_prevent_connection_from_non_localhost() {
okey, yap, not all tests are needed, I am happy to rename/delete some of them.

2023-11-23 15:58 UTC, czp13 commented on vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DebugWindowConnectionTest.java
> +    public void onconnect_should_prevent_connection_from_non_localhost() {
Fixed, should be better now:
- correct token
- invalid token
- no token
Just in case testing the last one too.

2023-11-23 16:59 UTC, mcollovati requested changes
Some minor changes for the moment. I'll continue the review tomorrow

2023-11-23 16:59 UTC, mcollovati commented on flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
> +import static org.junit.Assert.*;
nit: please avoid wildcard imports

2023-11-23 16:59 UTC, mcollovati commented on flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
> +    private static final String UUID_REGEX = "\"token\":\"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\"";
This could already be a Pattern instead of a String

2023-11-23 17:06 UTC, czp13 commented on flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
> +import static org.junit.Assert.*;
Thanks, no, it is a fair comment. I remembered I changed my IntelliJ to never use wildcards, but maybe it was a project-specific configuration :(. Anyway Fixed!

2023-11-23 17:06 UTC, czp13 commented on flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
> +    private static final String UUID_REGEX = "\"token\":\"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\"";
Thanks, good point, more performant if does not need to create a Pattern all the time. Fixed.

2023-11-24 06:33 UTC, Artur- commented
It is a bit hqrd to view the changes on a phone but are all tests now missing for the logic in IndexHtmlRequestHandler? Like loopback accepted by default and nothing else + that matching with the property actually accepts and denies correctly- with and without a proxy?

2023-11-24 08:54 UTC, mcollovati requested changes
Another round of comments, but I have not yet tested the feature

2023-11-24 08:54 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
> +    public void handleConnect(AtmosphereResource resource) {
I think there is no need to have this method public

2023-11-24 08:54 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
> +            resource.resume();
Just a thought, but I'm not completely sure: if the connection should be denied, would it make sense to do a `resource.close()` instead of a `resume()`, so the underlying connection will be closed?

2023-11-24 08:54 UTC, mcollovati commented on flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
I may have missed something, but I can't see sensible tests related change introduced in IndexHtmlRequestHandler

2023-11-24 08:54 UTC, mcollovati commented on vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DebugWindowConnectionTest.java
nit: the added tests seem very similar, probably we can refactor them to avoid copy/paste

2023-11-24 08:54 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +        String remoteAddress = request.getRemoteAddr();
API states that `request.getRemoteAddr()` could potentially return `null`, and in this case, `InetAddress.getByName()` would return the address of the loopback interface.
Is this the intended behavior?

2023-11-24 08:54 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +        if (!isAllowedDevToolsHost(remoteAddress, hostsAllowed)) {
Just a note: when documenting the `devmode.hostsAllowed` property, it will be worth it to highlight that if the pattern must also allow the proxy IP, when the server is behind a reverse-proxy

2023-11-24 08:54 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +            String hostsAllowed) {
nit: maybe the method could directly get a Pattern instead of a string.

2023-11-24 08:54 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +    private boolean isAllowedDevToolsHost(AbstractConfiguration configuration,
Minor suggestion: if we make the method static and package protected, it may be easier to test the logic in isolation

2023-11-24 09:09 UTC, czp13 commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
> +    public void handleConnect(AtmosphereResource resource) {
Okey, let's change to private, as we do not write a specific test for this only as well.

2023-11-24 09:11 UTC, czp13 commented on flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
We have smoke tests to see if the tokens were added in correct format or not, but as you and Artur pointed out seems not enough.

2023-11-24 09:12 UTC, czp13 commented on vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DebugWindowConnectionTest.java
Okey, maybe the mocking part could be extracted and then remove some extra lines.

2023-11-24 09:25 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +    private boolean isAllowedDevToolsHost(AbstractConfiguration configuration,
Fair point! 👍

2023-11-24 09:26 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +        String remoteAddress = request.getRemoteAddr();
Added code to deny if remote address is not available

2023-11-24 09:27 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +        if (!isAllowedDevToolsHost(remoteAddress, hostsAllowed)) {
The reason for this is so you cannot just add a header and bypass the restriction

2023-11-24 09:52 UTC, Artur- commented on flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Added tests

2023-11-24 09:52 UTC, Artur- commented
Changed the logic slightly so that localhost is always allowed. Otherwise you end up with the weird scenario with a local proxy that you would need to separately allow the local ip and the remote ip

2023-11-24 09:53 UTC, czp13 commented on vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DebugWindowConnectionTest.java
Fixed, there should be fewer lines, hope you like this one better! 🙇

2023-11-24 09:53 UTC, czp13 commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
> +    public void handleConnect(AtmosphereResource resource) {
Made it private, thanks!

2023-11-24 09:57 UTC, Artur- commented
Changed the property from being a regexp to being a "wildcard match" using `*` and `?` to help people make fewer mistakes

2023-11-24 10:01 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +            String hostsAllowed) {
Not relevant anymore now that it is not a regexp

2023-11-24 10:12 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +            String hostsAllowed) {
We are using the end this `FilenameUtils.wildcardMatch(remoteAddress, hostsAllowed);` 

We could rewrite it to something like this, to not use the `FilenameUtils`
```
        String regex = hostsAllowed.replace("?", ".").replace("*", ".*");
        Pattern pattern = Pattern.compile(regex);

        Matcher matcher = pattern.matcher(remoteAddress);
```

But this seems more complex and not sure if we wanna do this transformation and potentially make it less performant.

So TLDR wildcard and pattern (regexp) match is different, and we are expecting wildcard pattern from users, not sure if we wanna do an intermediate transformation to check with patterns (regexp in the end), or stick to wildcards end2end.

2023-11-24 10:16 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
> +            getLogger().debug(
Could this message be at least at `WARN` level?

2023-11-24 10:23 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
> +            getLogger().debug(
Yes, makes sense now that the client does not blindly try to connect. Changed

2023-11-24 10:26 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +            String hostsAllowed) {
That would require work, implement the matching in an incorrect way (all special regexp chars would have special meaning) and add more code for us to mantain and test. Let's not

2023-11-24 10:54 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
> +    public static final String HOSTS_ALLOWED = "devmode.hostsAllowed";
I would maybe rename it to `DEVTOOLS_HOST_ALLOWED`, as `HOSTS_ALLOWED` seems too generic

2023-11-24 10:57 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +            return FilenameUtils.wildcardMatch(remoteAddress, hostsAllowed);
Match easier than with regexp :+1: 
nit: I wonder if we should consider allowing `hostsAllowed` to provide multiple comma separated patterns

2023-11-24 11:05 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +            String hostsAllowed) {
Yes, agree, let's use wildcards matching from start to end, do not make it more complex.

2023-11-24 11:17 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +            return FilenameUtils.wildcardMatch(remoteAddress, hostsAllowed);
Good idea, but I am not sure. 

And then I guess we need this code:
```suggestion
    String[] allowedHosts = hostsAllowed.split(",");

    for (String allowedHost : allowedHosts) {
        if (FilenameUtils.wildcardMatch(remoteAddress, allowedHost.trim())) {
            return true;
        }
    }
```

And then adding some covering tests... @Artur- I need you once more :D :( Do we wanna support that or wildcard shall be enough?

2023-11-24 11:30 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
> +    public static final String HOSTS_ALLOWED = "devmode.hostsAllowed";
Thanks, good point. Fixed this one to `SERVLET_PARAMETER_DEVMODE_HOSTS_ALLOWED` to keep the naming convention as we discussed as well!

2023-11-24 11:53 UTC, Artur- commented
Added support for many hosts to support the non-local proxy scenario

2023-11-24 12:01 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +            return FilenameUtils.wildcardMatch(remoteAddress, hostsAllowed);
An example from a setup with a reverse-proxy (running on docker) in front of an app, connection from a local and a remote machine

Accessing from local
```
browser URL: http://localhost:9090
remote addr: 172.17.0.3 (IP from docker network)
forwarded-for: 172.17.0.1 (IP from docker network)
```

Accessing from another laptop on the same LAN
```
browser URL: http://192.168.1.99:9090
remote addr: 172.17.0.3 (IP from docker network)
forwarded-for: 192.168.1.23 
```

To make it work, I would need to set the allowed list to something like `172.17.0.*,192.168.1.23`

2023-11-24 12:22 UTC, Artur- commented
Are we done here? 
![image](https://github.com/vaadin/flow/assets/260340/2ddadf8e-1b62-4a77-9e87-c918ed8674a1)

2023-11-24 13:11 UTC, mcollovati submitted a review, later dismissed

2023-11-24 13:24 UTC, czp13 commented on flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
> +     * Whitelisting to specify the allowed hosts, potentially with wildcards,
Thanks fixed as we discussed same time as you did write :)

2023-11-24 14:24 UTC, mcollovati approved these changes

2023-11-24 15:00 UTC, merged