Added border-radius style for elements
vaadin/flow pull request #18089
Opened 2023-11-21 15:28 UTC by Rystars

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes #18063 (https://github.com/vaadin/flow/issues/18063)

## Type of change

- [ ] Bugfix
- [✓] Feature

## Checklist

- [✓] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2023-11-21 15:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=18089) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=18089) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=18089) it.</sub>

2023-11-21 15:41 UTC, mcollovati approved these changes

2023-11-21 15:44 UTC, mcollovati commented
@Rystars thank you for the contribution!
Could you please format the source code as described in [this comment](https://github.com/vaadin/flow/pull/18089#issuecomment-1821175393)?

2023-11-21 22:38 UTC, mcollovati requested changes

2023-11-21 22:38 UTC, mcollovati commented on .github/workflows/maven_formatter.yml
> +# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
Please, remove this file that is not related to this PR

2023-11-22 00:08 UTC, Rystars commented
> @Rystars thank you for the contribution! Could you please format the source code as described in [this comment](https://github.com/vaadin/flow/pull/18089#issuecomment-1821175393)?

Sorry I can only answer because I was asleep yesterday

the error format has been fixed (maybe)

2023-11-22 00:14 UTC, Rystars commented on .github/workflows/maven_formatter.yml
> +# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
It's been deleted but why is it still there?🤔

2023-11-22 06:47 UTC, mcollovati requested changes

2023-11-22 06:47 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/dom/Style.java
> +        return set(STYLE_BORDER_RADIUS,value);
Fixing formatting issue

```suggestion
        return set(STYLE_BORDER_RADIUS, value);
```

2023-11-22 06:50 UTC, mcollovati approved these changes

2023-11-22 06:51 UTC, mcollovati commented
@Rystars there was still a formatting issue, but the PR now looks good. Thank you for the contribution!

2023-11-22 07:03 UTC, Rystars commented
thanks for fixing it

2023-11-22 07:16 UTC, merged