refactor: refactor navigation access control API
vaadin/flow pull request #18110
Opened 2023-11-23 11:06 UTC by mcollovati

Extracts NavigationAccessChecker inner classes to top level
Adds factory method to AccessCheckResult
Improves javadoc

2023-11-23 11:11 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessCheckDecisionResolver.java
> +public interface AccessCheckDecisionResolver extends Serializable {
Should this extend SerializableBiFunction to "enforce" the idea of functional interface?

2023-11-23 11:32 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessCheckDecisionResolver.java
> +public interface AccessCheckDecisionResolver extends Serializable {
In this case, I would prefer to avoid such a strong coupling with a platform interface because it could potentially cause more difficulties if we need/want to change the API in the future.

2023-11-23 12:36 UTC, mshabarov requested changes

2023-11-23 12:36 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessCheckResult.java
> +    public static final AccessCheckResult NEUTRAL = new AccessCheckResult(
Now we have two constants and two factory methods for different results.
Maybe it's better to have only four factory methods and remove constants, so the code would look like

```java
if (hasAccess(context)) {
     return AccessCheckResult.allow();
} else {
     return AccessCheckResult.deny("Access denied");
}
```

2023-11-23 12:36 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessCheckResult.java
> +    public static final AccessCheckResult NEUTRAL = new AccessCheckResult(
Mixing constants and methods looks like incomplete API IMO.

2023-11-23 15:20 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessCheckResult.java
> +    public static final AccessCheckResult NEUTRAL = new AccessCheckResult(
done

2023-11-23 17:09 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessCheckResult.java
> +    public static final AccessCheckResult NEUTRAL = new AccessCheckResult(
Would it make sense to have a method "create()" that takes all params? So the developer isn't forced to create multiple if-else constructs where they either call accept() or reject(), but can just do create(Result, String) in the end of a method after they have checked anything and decided what the outcome is

2023-11-23 17:17 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessCheckResult.java
> +    public static final AccessCheckResult NEUTRAL = new AccessCheckResult(
Another point: the AccessCheckResult is final, making it impossible to have custom implementations with for example more attributes forcing the developer to put all information in the single reason field (technical, human readable messages and so on) 

We often use wrapper classes that hold a message to be printed in the log for DevOps and an readable message for the customer to be shown on the UI as an example. 

Suggestion: AccessCheckResult could be an interface, with a SimpleAccessCheckResult like the infamous Result to allow easier extensibility for the users

(Sorry, the idea just came up.. the other PR was to large for my phone and brain 😬)

2023-11-24 07:21 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessCheckResult.java
> +    public static final AccessCheckResult NEUTRAL = new AccessCheckResult(
This `create` method is a shortcut for `new AccessCheckResult(AccessCheckDecision decision, String reason)`, right?

2023-11-24 07:26 UTC, mshabarov approved these changes

2023-11-24 07:28 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessCheckResult.java
> +    public static final AccessCheckResult NEUTRAL = new AccessCheckResult(
> Suggestion: AccessCheckResult could be an interface, with a SimpleAccessCheckResult like the infamous Result to allow easier extensibility for the users

If you think this can be useful, I believe we change to that.

2023-11-24 07:28 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessCheckResult.java
> +    public static final AccessCheckResult NEUTRAL = new AccessCheckResult(
I was thinking about making this even private and have consistent static builder methods only, like your other shortcuts to have the same API for all types

2023-11-24 07:30 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessCheckResult.java
> +    public static final AccessCheckResult NEUTRAL = new AccessCheckResult(
I'm not sure about making `AccessCheckResult` as this would require additional checks on our code and would somehow block or make it more difficult for us to refactor that class, since we should consider the existence of potential custom implementations.

But we can reason about that if there are good uses cases.

@knoobie, if you could extend or have a custom `AccessCheckResult` with additional information, where would you use it?
I would say that to use them, you will have to also extend other navigation access control components.
So I wonder if it is worth it to make `AccessCheckResult` extensible, or if we can simply improve the existing instance with some additional info.

2023-11-24 07:34 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessCheckResult.java
> +    public static final AccessCheckResult NEUTRAL = new AccessCheckResult(
> Interface change 
I think it's really useful and decreases the burden on you, because it allows for full flexibility for the Developer by allowing sub-classing and using instance of, if the returning result is a standard return type or some of they special type. 

Another spontaneous idea: the developer could want to return a view to delegate to once the access is denied, with a interface and custom class - the developer could just add the redirect route as another param and check if the result is of type "HasRedirect" and doesn't have to do hacks to pass the route throw Session Attributes or other means

2023-11-24 07:49 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessCheckResult.java
> +    public static final AccessCheckResult NEUTRAL = new AccessCheckResult(
> So I wonder if it is worth it to make AccessCheckResult extensible, or if we can simply improve the existing instance with some additional info.

That would also work, e.g. add a map like spring did for they RFC-7807 impl to allow for additional information https://github.com/spring-projects/spring-framework/blob/fb4455b396dd8648f37917a74ab08e9ad373eef7/spring-web/src/main/java/org/springframework/http/ProblemDetail.java#L71

2023-11-24 07:59 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessCheckResult.java
> +    public static final AccessCheckResult NEUTRAL = new AccessCheckResult(
I can see a potential usage for the custom result in a custom decision resolver.
For example, having multiple checkers, based on the result type, you may want to ignore the output or maybe assign different weights to the decision and compute the final result based on that.

Adding a Map of properties could be a good idea, and also easy to implement. Potentially, we could also print the values on debug logs.

Otherwise, we consider how much refactoring the `AccessCheckResult` as an interface impacts current code. For this, I think we will need to introduce several and null consistency checks (e.g. mandatory message for some decisions type) in different places to give better advice than an NPE to the developers who incorrectly implement the interface.

2023-11-24 09:41 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/auth/AccessCheckResult.java
> +    public static final AccessCheckResult NEUTRAL = new AccessCheckResult(
Within this PR I propose to do: add "create" method and remove `final` from `AccessCheckResult` class, so that it can be extendable.

This PR pursues refactoring purposes and I think we can discuss further how we can improve `AccessCheckResult` API. Would be good to make a ticket for it.

2023-11-24 15:57 UTC, mshabarov approved these changes

2023-11-24 16:19 UTC, merged