#18012 feat!: reject AppShells classes which extend Components.
vaadin/flow pull request #18169
Opened 2023-11-30 12:52 UTC by mvysny

## Description

AppShellRegistry now rejects app shell class which extends Component.

Fixes #18012 

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [x] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2023-11-30 15:46 UTC, mcollovati requested changes

2023-11-30 15:46 UTC, mcollovati commented on flow-tests/test-pwa/src/main/java/com/vaadin/flow/pwatest/ui/ParentLayout.java
> +public class ParentLayout implements AppShellConfigurator {
Maybe better rename this class to `AppShell`, since `ParentLayout` does not make sense anymore

2023-11-30 15:46 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
> +            + "App shells are intended for page configuration and are instantiated before the UI is created.%n";
It would be good to add a similar note also on `AppShellConfigurator` javadoc.

2023-11-30 15:46 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
> +            + "App shells are intended for page configuration and are instantiated before the UI is created.%n";
And perhaps also make it explicit in the documentation https://vaadin.com/docs/latest/advanced/modifying-the-bootstrap-page#application-shell-configurator

2023-11-30 15:46 UTC, mcollovati commented on flow-tests/test-frontend/vite-pwa-production/src/main/java/com/vaadin/viteapp/AppShell.java
It looks like that `flow-tests/test-frontend/vite-pwa-production/src/main/java/com/vaadin/viteapp/MainView.java` still has the `layout = AppShell.class` on `@Route` annotation

2023-12-01 06:31 UTC, mvysny commented on flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
> +            + "App shells are intended for page configuration and are instantiated before the UI is created.%n";
Good idea, thanks! Created a PR in docs https://github.com/vaadin/docs/pull/3012 , also added the note to AppShellConfigurator Javadoc.

2023-12-01 06:33 UTC, mvysny commented on flow-tests/test-frontend/vite-pwa-production/src/main/java/com/vaadin/viteapp/AppShell.java
good catch, thanks! fixed.

2023-12-01 08:17 UTC, merged