fix: throw for missing server routes
vaadin/flow pull request #18242
Opened 2023-12-07 10:07 UTC by caalador

If serverSideRoutes is missing
from the routes.tsx then
log error on what to do and
throw exception.

Fixes https://github.com/vaadin/flow/issues/18240

2023-12-07 13:39 UTC, mshabarov requested changes
I'm getting the exception even if I have the import in place:

```
com.vaadin.flow.server.ExecutionFailedException: Faulty configuration of serverSideRoutes
        at com.vaadin.flow.server.frontend.TaskGenerateReactFiles.execute(TaskGenerateReactFiles.java:103) ~[flow-server-24.3-SNAPSHOT.jar:24.3-SNAPSHOT]
        at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:342) ~[flow-server-24.3-SNAPSHOT.jar:24.3-SNAPSHOT]
        at com.vaadin.base.devserver.startup.DevModeInitializer.runNodeTasks(DevModeInitializer.java:354) ~[vaadin-dev-server-24.3-SNAPSHOT.jar:na]
```

My routes file:
```JavaScript
import HelloWorldView from 'Frontend/views/helloworld/HelloWorldView.js';
import MainLayout from 'Frontend/views/MainLayout.js';
import { lazy } from 'react';
import { createBrowserRouter, RouteObject } from 'react-router-dom';
import {serverSideRoutes} from "Frontend/generated/flow/Flow";
import {protectRoutes} from "@hilla/react-auth";
import LoginView from "Frontend/views/LoginView";

const AboutView = lazy(async () => import('Frontend/views/about/AboutView.js'));

export const routes: RouteObject[] = protectRoutes([
  {
    element: <MainLayout />,
    handle: { title: 'Main' },
    children: [
      { path: '/', element: <HelloWorldView />, handle: { title: 'Hello World', rolesAllowed: ['USER'] } },
      { path: '/about', element: <AboutView />, handle: { title: 'About' } },
      ...serverSideRoutes
    ],
  },
  { path: '/login', element: <LoginView />},
]);

export default createBrowserRouter(routes);
```

2023-12-07 13:41 UTC, mshabarov commented
Also, the helper message isn't really visible, because the application keeps throwing `com.vaadin.flow.server.ExecutionFailedException: Faulty configuration of serverSideRoutes` all the time and what is logged at the beginning was lost in the logs.

2023-12-08 05:07 UTC, caalador commented
Changed to use find instead of match.
Put full message into exception.

2023-12-08 10:24 UTC, mshabarov requested changes
Works fine for me.

Have one comment about error message.

As a suggestion: would it be better to insert the import string automatically if it's not there and search for `...serverSideRoutes` entry in the route configuration and throw if not added ?

2023-12-08 10:24 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +            """;
Let's exclude `"` from the suggested import string:

```
    protected static String NO_IMPORT = """
            Faulty configuration of serverSideRoutes.
            The server route definition is missing from the '%1$s' file.

            To have working Flow routes add the following to the '%1$s' file:
- import line 'import {serverSideRoutes} from 'Frontend/generated/flow/Flow';'
- route '...serverSideRoutes' into the routes definition, example:

export const routes = [
  {
    element: <MainLayout />,
    handle: { title: 'Main' },
    children: [
      { path: '/', element: <HelloWorldView />, handle: { title: 'Hello World' } },
      ...serverSideRoutes
    ],
  },
] as RouteObject[];

            """;
```

2023-12-08 10:25 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +            """;
Currently the log message give me string `import "{serverSideRoutes} from \"Frontend/generated/flow/Flow\";`, which produces errors if I copy-paste it.

2023-12-08 10:35 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +            """;
That was left there by mistake as it was earlier on multiple lines. Missed it on refactor

2023-12-08 10:41 UTC, mshabarov approved these changes

2023-12-08 11:02 UTC, merged