fix: Support fragmented messages in debug window
vaadin/flow pull request #18268
Opened 2023-12-09 08:35 UTC by Artur-

2023-12-13 16:30 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/communication/FragmentedMessageHolder.java
> +            AtmosphereRequest request, Reader reader) throws IOException;
Just looking at the interface, it is not clear to me why this method named `getOrCreate...` should return null.
It would be good to clarify that in the Javadoc.
And maybe use `Optional` as return type, if it is not guaranteed that the method will provide an instance.

2023-12-13 16:30 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
> -    protected Reader receiveMessage(Reader reader) throws IOException {
This could potentially be a breaking change. 
I recall at least a custom `AtmospherePushConnection` in Kubernetes KIT, but I need to check if removing the method may impact it in some way.

2023-12-13 16:30 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/communication/FragmentedMessageHolder.java
It looks like the implementation of the two methods uses the `AtmosphereRequest` only to get the `AtmosphereResource`. Could it make sense to directly pass that object instead of the request?

2023-12-13 17:19 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
> -    protected Reader receiveMessage(Reader reader) throws IOException {
It is. It can probably be made compatible also, e.g. when backporting to 24.3 if needed

2023-12-13 17:19 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/communication/FragmentedMessageHolder.java
Seems like that can be done and it makes it simpler, changed

2023-12-13 18:18 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/communication/FragmentedMessageHolder.java
> +            AtmosphereRequest request, Reader reader) throws IOException;
I originally tried to make minimal changes but I now moved message length reading to make this simpler and clearer

2023-12-14 07:27 UTC, mcollovati requested changes

2023-12-14 07:27 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/communication/FragmentedMessageHolder.java
> +     *            the resource to get the partial message forder
Probably a typo: `forder`

2023-12-14 07:27 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
> +        fragmentedMessages.remove(resource);
Can we move the  fragmentedMessages cleanup to the top of the method?
Just to be sure that the map is purged even if the plugin throws an exception

2023-12-14 07:27 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
> +    private final ConcurrentHashMap<AtmosphereResource, FragmentedMessage> fragmentedMessages = new ConcurrentHashMap<>();
Just thinking out loud: could we use `AtmosphereResource.uuid()` as map key, to prevent potential leaks of the `AtmosphereResource`?

2023-12-14 07:42 UTC, mcollovati commented
Is there any chance we could add tests for partial messages? Or do we already have something?

2023-12-14 08:47 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
> +    private final ConcurrentHashMap<AtmosphereResource, FragmentedMessage> fragmentedMessages = new ConcurrentHashMap<>();
We could do that or we could merge this with the `atmosphereResources` tracking above. Which one would be better?

2023-12-14 08:57 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
> +    private final ConcurrentHashMap<AtmosphereResource, FragmentedMessage> fragmentedMessages = new ConcurrentHashMap<>();
So, using a synchronized `WeakHashMap` instead of the  `ConcurrentLinkedQueue`?
Sounds good

2023-12-14 09:19 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
> +        fragmentedMessages.remove(resource);
Not really relevant anymore as it was merged with the existing structure

2023-12-14 09:35 UTC, Artur- commented
> Is there any chance we could add tests for partial messages? Or do we already have something?

Added basic tests for short messages, long messages and messages equal to the limit

2023-12-14 10:05 UTC, mcollovati submitted a review, later dismissed
some minor comments that can be ignored, other than that LGTM

2023-12-14 10:05 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
> +                .filter(resourceRef -> resource.equals(resourceRef.get()))
nit: the check could be `resourceRef.refersTo(resource)`

2023-12-14 11:22 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
> +        resources.put(getRef(resource), new FragmentedMessage());
Added checking

2023-12-14 11:22 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
> +                .filter(resourceRef -> resource.equals(resourceRef.get()))
Updated

2023-12-14 12:08 UTC, mcollovati commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
>                  .removeIf(resourceRef -> resource.equals(resourceRef.get()))) {
nit: could use `refersTo` also here for consistency

```suggestion
                .removeIf(resourceRef -> resourceRef.refersTo(resource))) {
```

2023-12-14 12:12 UTC, mcollovati submitted a review, later dismissed

2023-12-14 12:39 UTC, mcollovati submitted a review, later dismissed

2023-12-14 14:28 UTC, mcollovati approved these changes

2023-12-14 14:33 UTC, mcollovati approved these changes

2023-12-14 15:42 UTC, merged