feat: add getItemIndex to DataView
vaadin/flow pull request #18306
Opened 2023-12-14 13:11 UTC by tltv

New `getItemIndex` method in `DataView` affects `ListDataView` and `LazyDataView` implementations. `LazyDataView` introduces in addition a new method `setItemIndexProvider(ItemIndexProvider)`. With `ListDataView`, `getItemIndex` works out-of-the-box with the in-memory data. With `LazyDataView`, it's required to set item index provider first with `setItemIndexProvider(ItemIndexProvider)`. Otherwise `getItemIndex` will throw `UnsupportedOperationException`. Provider can be implemented to fetch correct item index using item and `Query` parameters. `Query` object is set up to fetch all items with sorting and filter.

Fixes: #18088

2023-12-15 06:23 UTC, tepi commented
Looks good to me. Maybe wait for second opinion since this is new API.

2023-12-15 06:34 UTC, mcollovati commented
Also looks good to me.
I just wonder if we should add a detailed Javadoc on `ItemIndexProvider.apply()` to explain what we expect the method to do (e.g. apply filter and sorting) and to warn about potential pitfalls (e.g. inconsistent index upon data changes)

2023-12-15 08:10 UTC, tepi commented
> Also looks good to me. I just wonder if we should add a detailed Javadoc on `ItemIndexProvider.apply()` to explain what we expect the method to do (e.g. apply filter and sorting) and to warn about potential pitfalls (e.g. inconsistent index upon data changes)

I agree that this should be added. The former is mentioned [here](https://github.com/vaadin/flow/pull/18306/files#diff-3c170f84b70d5e0806b952e5874d04e4f513d54d362039bcef07302d73ff2297R48-R50) but would be good to repeat in `ItemIndexProvider.apply()` javadoc along with potential pitfalls.

2023-12-15 08:22 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +    public ItemIndexProvider<T, ?> getItemIndexProvider() {
I would recommend not to touch DataCommunicator at all and instead place the item index provider directly to `AbstractLazyDataView` class. The reason for it:
1. Let's not leak the API from `DataView` to `DataCommunicator`, it's not really necessary.
2. `DataCommunicator` shouldn't be used by developers at the first place, despite Grid has a direct access to it and for some cases it is need. ComboBox for instance has no getter for it.
If this provider was used somehow in DC, I would maybe agree, but it isn't, so no strong reasons IMO to add it to DC.

2023-12-15 08:25 UTC, mshabarov commented
I support this [comment](https://github.com/vaadin/flow/pull/18306#issuecomment-1857353436) and suggest to add an implementation example code snippet to `ItemIndexProvider`'s javadoc

2023-12-15 08:59 UTC, tltv commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +    public ItemIndexProvider<T, ?> getItemIndexProvider() {
I started first having it in `AbstractLazyDataView`. Then I realized that data view is actually quite stateless. Everything is stored in `DataCommunicator` or component instance itself, and if you call e.g. `Grid#getLazyDataView`, you'll get new instance of data view. To preserve state, only place to put it is in `DataCommunicator`.
So even though I agree that it's not ideal place to store this particular state, it's inline with other states and also only place if we want to preserve it between `getLazyDataView`.

2023-12-15 09:01 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +    public ItemIndexProvider<T, ?> getItemIndexProvider() {
How about storing it in the Component ?

2023-12-15 09:27 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +    public ItemIndexProvider<T, ?> getItemIndexProvider() {
I suggest to use `ComponentUtil` to store the provider in the backed `Component`, like it's done, for example, in `AbstractDataView::addIdentifierProviderChangeListener`.

When data view stores something in DataCommunicator, these stored objects are used by DataCommunicator itself, but this isn't true for our use case.

2023-12-15 09:32 UTC, tltv commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +    public ItemIndexProvider<T, ?> getItemIndexProvider() {
Storing it to `Component` data looks promising. Better than `DataCommunicator`.

2023-12-15 10:52 UTC, mcollovati submitted a review, later dismissed

2023-12-15 11:29 UTC, mshabarov requested changes

2023-12-15 11:29 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/ItemIndexProvider.java
> +    Integer apply(T item, Query<T, F> query);
Needs javadoc

2023-12-15 11:29 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/ItemIndexProvider.java
> +    Integer apply(T item, Query<T, F> query);
Also "Since 24.4" might be helpful

2023-12-15 11:31 UTC, mshabarov commented
@yuriy-fix could you please verify that this new API is appropriate for components to implement scroll to item API ?

2023-12-15 12:05 UTC, tltv commented on flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractLazyDataView.java
> +    private Query getQueryForAllItems() {
`getQueryForAllItems` is not returning same filter that data provider may use. E.g when setup with `DataProvider.withConfigurableFilter()`. its not required to use that filter, but I think it would be misleading to leave it without at least trying to give correct filter.

2023-12-18 11:21 UTC, mshabarov requested changes

2023-12-18 11:21 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractLazyDataView.java
> +                    wrapper.getFilter(baseQuery));
I'd propose to create a ticket for fixing the filtering this way and:
1. Implement it in the next minor release if the issue gets votes (at least 1-2 I think)
2. Implement it in the next major release instead, as this might be a behaviour change for some projects (fetch less items than expected due to the filter in wrapper data provider).

2023-12-18 11:21 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java
> +    Integer getItemIndex(T item);
I propose to return the `Optional<Integer>` instead, this is my personal preference, but we also have `Optional` for item getters, so might be better to align with them.

2023-12-19 09:58 UTC, tltv commented on flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractLazyDataView.java
> +                    wrapper.getFilter(baseQuery));
I just realized after writing almost complete new ticket that I was wrong with `DataProviderWrapper` filter not being used by `getItems`. It is as long as it uses `DataProvider#fetch` method (as it does), filter is added from the data provider properly.

`getItemIndex` is not calling fetch, it calls item index provider with the query, so there it's good to build the filter like this so that developer can use the correct query to fetch the index.

2023-12-19 10:03 UTC, tltv commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java
> +    Integer getItemIndex(T item);
What Item getters do you mean? Nothing like that in the DataView.

2023-12-19 10:05 UTC, tltv commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java
> +    Integer getItemIndex(T item);
Never mind, I see getNextItem/getPrevItem in ListDataView.

2023-12-19 16:20 UTC, mshabarov submitted a review, later dismissed
Have one clarification for javadoc, otherwise looks good to me

2023-12-19 16:20 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/ItemIndexProvider.java
> +     * either side during this call may cause inconsistent index as a result.
```suggestion
     * either side during this call may cause inconsistent index as a result.
     * <p>
     * The query parameter provides a filter object being set with 
     * {@link ConfigurableFilterDataProvider} or provided by a component, 
     * e.g. a string filter in ComboBox.
```

2023-12-20 08:50 UTC, mshabarov approved these changes

2023-12-20 09:05 UTC, merged