#18318 Remove deployment conf field from VaadinSession
vaadin/flow pull request #18319
Opened 2023-12-15 13:25 UTC by tepi

Fixes #18318

2023-12-19 07:23 UTC, mcollovati requested changes
The change looks good and makes sense.
A minor drawback will be that it might break some test configurations on other repositories. In MPR for example, it is used in a couple of tests, and the problem here may be that we use the same MPR codebase against different Flow version.

Potentially also user projects may be affected, since `setConfiguration()` is a public API, even though I suppose `VaadinSession.setConfiguration()` is not widely used.

2023-12-19 07:23 UTC, mcollovati commented on flow-server/src/test/java/com/vaadin/flow/component/InvalidUrlTest.java
> -        session.lock();
If we remove this `session.lock()`, should we also remove the `session.unlock()` at the end of the method?
Or should the `session.lock()` be preserved?

2023-12-19 07:23 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +        if (service != null) {
I wonder if we should throw an exception when service is null.
A VaadinSession without a service reference will not work correctly, and the only moment I can imagine the field to be null is on deserialization, but in that case, the constructor will not be invoked.

2023-12-19 07:33 UTC, tepi commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +        if (service != null) {
You are right, that would make sense. I'll do the change, although it will mean revisiting at least one (quite old) test, which is calling the constructor with null parameter (claiming it as an 'uninitialized' session, whatever that means).

2023-12-19 07:34 UTC, tepi commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +        assert sessionLockCheckStrategy != null;
Will do

2023-12-19 07:34 UTC, tepi commented on flow-server/src/test/java/com/vaadin/flow/component/InvalidUrlTest.java
> -        session.lock();
Good catch. I'll need to check that on other tests as well. Probably the unlock is not needed.

2023-12-19 07:55 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +        if (service != null) {
Could it be a post deserialization simulation? Anyway, I would probably nullify the field through reflection in that case

2023-12-19 07:58 UTC, tepi commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +        if (service != null) {
It's this one: https://github.com/vaadin/flow/blob/main/flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java#L483

2023-12-19 08:12 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +        if (service != null) {
HTTP session unboud is called when the implementing object is removed from the HTTP session, so I think that in that case the VaadinSession should have a not-null reference to VaadinService

2023-12-19 08:15 UTC, tepi commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +        if (service != null) {
Ok, I'll have to check how to fix it then. Initially I just changed the null to a mock VaadinService but that will fail the test.

2023-12-19 08:18 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +        if (service != null) {
Ah, my bad. The `valueUnbound` method Javadoc explains the case.
I propose to have the null-check in the constructor and nullify it with reflection (or serialize/deserialized the VaadinSession object)

2023-12-19 10:08 UTC, tepi commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +        assert sessionLockCheckStrategy != null;
Moved to a new private method

2023-12-19 10:09 UTC, tepi commented on flow-server/src/test/java/com/vaadin/flow/component/InvalidUrlTest.java
> -        session.lock();
Fixed, and found no other instances of this case

2023-12-19 10:09 UTC, tepi commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
> +        if (service != null) {
Fixed

2023-12-19 10:34 UTC, mcollovati commented
Some tests to fix, but other than that LGTM

2023-12-19 12:32 UTC, mcollovati approved these changes

2023-12-19 12:35 UTC, tepi commented
Despite approval, do not merge. This should be postponed until major release of Flow (25), since this changes public API.

2023-12-19 12:38 UTC, mcollovati commented
Would it be better to make it a draft again, to prevent unwanted merge?

2025-07-24 04:43 UTC, tepi commented
Closed in favor of https://github.com/vaadin/flow/pull/21938

2025-07-24 04:43 UTC, closed without merging