fix: consider local npm packages in bundle validation
vaadin/flow pull request #18368
Opened 2023-12-28 09:38 UTC by mcollovati

## Description

If a project package.json contains references to local npm pacakges instead of parsable version, the bundle validation fails. This change update the version check in bundle validation to accept also local packages.
For those packages, a bundle re-creation is triggered only if the reference in package.json does not match the one in the stats.

Fixes #18106

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2023-12-28 09:44 UTC, mcollovati commented
This patch prevents the version parsing exception.
However, currently, the bundle validation might not be able to detect if there are changes in the local package that will require a bundle rebuild.
Rebuild will be triggered if changed components from local packages are imported in fronted source, but not if they are referenced, for example, with `@JsModule` annotation.
This situation should be mitigated once #18365 will be fixed

2024-01-29 11:52 UTC, mshabarov commented
I propose for now to go with the implemented solution.

IMO this is quite a rare case for pure Flow apps when development goes in local npm package (otherwise I beileve the hotdeploy mode should be used).
Upon changes in local package, one can `mvn clean` and delete `dev.bundle` file from `src/main/bundles` and he gets a re-bundling then. 

If we get a request to make this happen automatically, we can consider a more advanced solution.

2024-01-29 11:55 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
> +            return false;
Are these cases covered with the existing logging? 
If not, they need an additional INFO or DEBUG logging telling why re-bundling is happening.

2024-01-29 11:56 UTC, mshabarov requested changes
Small loggin-related question, otherwise looks good.

2024-01-29 12:16 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
> +            return false;
Currently, it will log that the dependency has a wrong version in the bundle.
Adding a DEBUG level log that reports both version make sense to help in troubleshooting

2024-01-29 12:20 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
> +            return false;
added log

2024-01-29 12:25 UTC, mshabarov approved these changes

2024-01-29 12:57 UTC, merged