test: test executable jar with Jetty
vaadin/flow pull request #18502
Opened 2024-01-22 09:05 UTC by tltv

Adds a new module to run ITs for executable jar build for Spring boot with Jetty.

Related-to: #18410

2024-01-22 11:22 UTC, mcollovati requested changes

2024-01-22 11:22 UTC, mcollovati commented on flow-tests/vaadin-spring-tests/test-spring-boot-jar/pom.xml
> +							<executable>java</executable>
What about using a property instead of hard-coding `java`? It might prevent issues with environments where the Java executable is not present on path, or if you have several Java versions and the one on path is not the one you need for the build.

2024-01-22 11:22 UTC, mcollovati commented on flow-tests/vaadin-spring-tests/test-spring-boot-jar/pom.xml
> +							<async>true</async>
Being the execution async, we should probably find a way to stop the process in `post-integration-test` phase.
I think there's nothing out-of-the-box in Maven.
I recall Spring Actuator has a shutdown endpoint, but we can probably do something similar on our own (a custom servlet or filter or maybe using JMX)

2024-01-22 11:22 UTC, mcollovati commented on flow-tests/vaadin-spring-tests/test-spring-boot-jar/pom.xml
> +							<commandlineArgs>-Dgosh.args="--nointeractive -s" -jar vaadin-test-spring-boot-jar-${project.version}.jar</commandlineArgs>
Isn't the `gosh` thing something related only to some OSGi container? It could probably be removed

2024-01-22 11:22 UTC, mcollovati commented on flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/SmokeTestIT.java
> +            waitViewUrl(count - 1);
nit: this will not be a deep stack, but I wonder if it could be better to use a while or for loop, instead of recursion

2024-01-23 09:08 UTC, knoobie commented on flow-tests/vaadin-spring-tests/pom.xml
> +                <module>test-spring-boot-jar</module>
should the module name contain jetty?

2024-01-23 09:21 UTC, mcollovati approved these changes

2024-01-23 09:34 UTC, tltv commented on flow-tests/vaadin-spring-tests/pom.xml
> +                <module>test-spring-boot-jar</module>
I would keep it generic like it's sibling module test-spring-boot for now, which is also jetty module. And get back to renaming when we add same test for e.g. tomcat.

2024-01-23 09:41 UTC, merged