Adds isApplied feature for Binding
vaadin/flow pull request #18540
Opened 2024-01-25 15:28 UTC by tepi

Allows developer to ignore selected bindings via providing a predicate for a binding that is tested before validating the binding, or writing the binding value to bean. Default implementation ignores bindings for which the bound field is not visible.

2024-01-25 17:13 UTC, mcollovati requested changes

2024-01-25 17:13 UTC, mcollovati commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +                .stream().filter(Binding::isApplied).map(b -> b.validate(false))
Probably the `filter` operation here is not needed, since `currentBindings` is already filtered.

2024-01-25 17:13 UTC, mcollovati commented on flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Does it make sense to you to add tests to ensure that the `isApplied`  is evaluated during `writeBean()` and `writeBeanAsDraft()`?

2024-01-25 17:13 UTC, mcollovati commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +                    return ((Component) binding.getField()).isVisible();
nit: could use pattern matching to simplify the cast operation (unless we plan to back-port the feature)
```suggestion
                if (binding.getField() instanceof Component component) {
                    return component.isVisible();
```

2024-01-25 18:34 UTC, tepi commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +                .stream().filter(Binding::isApplied).map(b -> b.validate(false))
True, good catch! Fixed

2024-01-25 18:34 UTC, tepi commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +                    return ((Component) binding.getField()).isVisible();
Fixed

2024-01-25 18:34 UTC, tepi commented on flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Added test for these two cases

2024-01-25 19:42 UTC, knoobie commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +                    || c.isVisible();
nit: the previous version looked way more readable, this feels like brain training :D

2024-01-26 10:22 UTC, mcollovati approved these changes

2025-07-24 10:03 UTC, merged