fix: no serverSideRoutes check if no Routes
vaadin/flow pull request #18546
Opened 2024-01-26 13:25 UTC by caalador

Do not check for the
serverSideRoutes in
routes.tsx in react mode
if no `@Route` annotated
Flow routes found.

2024-01-26 13:26 UTC, mshabarov commented
Is this fixes https://github.com/vaadin/flow/issues/18539  ?

2024-01-26 13:27 UTC, caalador commented
yes

2024-01-26 14:19 UTC, mshabarov requested changes

2024-01-26 14:19 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
>          this.frontendDirectory = options.getFrontendDirectory();
`this.frontendDirectory = options.getFrontendDirectory();` now can be removed as you have class field `options` and can access any parameter.

2024-01-26 14:19 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +                                .getAnnotatedClasses(Route.class).isEmpty()) {
I suggest to simplify this if clause for better readability, e.g.:

```java
if (hasServerRoutes() && missingServerImport()) {
  // existing codes
}

private boolean hasServerRoutes(//params) {
return !options.getClassFinder()
                                .getAnnotatedClasses(Route.class).isEmpty()
}

private boolean missingServerImport(//params) {
return !serverImport.matcher(routesContent).find();
}
```

2024-01-26 14:19 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
> +                Collections.singleton(TaskGenerateReactFilesTest.class));
This also needs a test that checks that Flow doesn't throw if import is missing and no Flow routes.

2024-01-26 14:19 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
> +                Collections.singleton(TaskGenerateReactFilesTest.class));
`TaskGenerateReactFilesTest` is better to replace to e.g. `DummyRoute` private class.

2024-01-29 05:57 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
>          this.frontendDirectory = options.getFrontendDirectory();
Moved

2024-01-29 05:57 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +                                .getAnnotatedClasses(Route.class).isEmpty()) {
methodised

2024-01-29 05:57 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
> +                Collections.singleton(TaskGenerateReactFilesTest.class));
added

2024-01-29 05:57 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
> +                Collections.singleton(TaskGenerateReactFilesTest.class));
done

2024-01-29 06:54 UTC, mshabarov approved these changes

2024-01-29 06:54 UTC, merged