feat: Add method to write only the changed properties to the bean
vaadin/flow pull request #18636
Opened 2024-02-07 10:13 UTC by TatuLund

fixes #18583

2024-02-09 14:46 UTC, mcollovati requested changes

2024-02-09 14:46 UTC, mcollovati commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +        return changedBindings;
I would return an immutable copy of `changedBindings`, to prevent unwanted modifications to the collection.

2024-02-09 14:46 UTC, mcollovati commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +    public void updateBean(BEAN bean) throws ValidationException {
On the linked issue, there was a remark about not adding this method. Ping @mshabarov 

Anyway, as also suggested on the issues, I would change the name to something more explicit like `writeChangedBindingToBean` or `writeChangesToBean`

2024-02-09 14:46 UTC, mcollovati commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +            Collection<Binding<BEAN, ?>> bindingsToWrite)
Since we allow providing a collection of bindings from the outside, I wonder if we should add a sanity check to ensure that the given bindings belong to this Binder

2024-02-09 14:48 UTC, mcollovati commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +            Collection<Binding<BEAN, ?>> bindingsToWrite)
If the collection contains _foreign_ bindings, we could either throw an exception or just log a warnin message and ignore them.

2024-02-09 15:05 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +    public void updateBean(BEAN bean) throws ValidationException {
`writeChangedBindingToBean` sounds self-explanatory, I'd go with this name and keep this method.

2024-02-10 07:34 UTC, TatuLund commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +            Collection<Binding<BEAN, ?>> bindingsToWrite)
I prefer throwing IllegalArgumentException.

2024-02-12 07:33 UTC, mcollovati approved these changes

2024-02-12 11:40 UTC, merged