fix: Use class finder to load package.json templates
vaadin/flow pull request #18658
Opened 2024-02-08 15:04 UTC by mshabarov

Fixes validation errors in https://github.com/vaadin/hilla/pull/2015

2024-02-09 11:18 UTC, mshabarov commented
I have tested this together with https://github.com/vaadin/hilla/pull/2015 and Hilla's `packages/java/tests/spring/react-grid-test` test module. 

No errors and required 4 deps are added into package.json.

2024-02-09 11:59 UTC, caalador requested changes

2024-02-09 11:59 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
>          try {
As NodeUpdater contains Options I would make this non static and get the classFinder from `options.getClassFinder();` instead of sending it around.

2024-02-09 11:59 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +            ClassFinder classFinder) {
Options contains the classFinder so we shouldn't need it as a parameter to be sent in.

Also having this as non static gives us the possibility to use options  without sending it to the method, also makes it possible to drop static from readDependencies

2024-02-09 11:59 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +    static JsonObject readPackageJson(String id, ClassFinder classFinder)
Dropping static and we can use the classFinder in Options

2024-02-09 11:59 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGeneratePackageJson.java
> +        super(classFinder, null, options);
Looking at NodeUpdater there is no reason for it to take in ClassFinder and we could just have the ClassFinder in Options wrap itself with `new ClassFinder.CachedClassFinder(options.getClassFinder());` so that it can be used in every place through the Options class instead of doing the wrapping only in NodeTasks.

2024-02-09 11:59 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
> +        packageCreator = new TaskGeneratePackageJson(options, classFinder);
Should get classFinder from options

2024-02-09 13:04 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
>          try {
Removed and options.classFinder now has a wrapped class finder.

2024-02-09 13:04 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +            ClassFinder classFinder) {
Removed

2024-02-09 13:05 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +    static JsonObject readPackageJson(String id, ClassFinder classFinder)
Done

2024-02-09 13:05 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGeneratePackageJson.java
> +        super(classFinder, null, options);
Done

2024-02-12 05:28 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
>      TaskUpdatePackages(ClassFinder finder,
UpdatePackages is still taking in finder, even though it is not used.

2024-02-12 05:28 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFilesTest.java
> +        Options options = new Options(lookup, npmFolder)
Should we perhaps have a MockOptions that takes in the classFinder.
`MockOptions(ClassFinder classFinder, File npmFolder)` and sets up the lookup mock.
This cold be a update tests ticket.

2024-02-12 07:16 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFilesTest.java
> +        Options options = new Options(lookup, npmFolder)
Yeah, good idea. Let me try to implement it within this PR.

2024-02-12 08:31 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFilesTest.java
> +        Options options = new Options(lookup, npmFolder)
Thanks, done.

2024-02-12 08:31 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
>      TaskUpdatePackages(ClassFinder finder,
Removed

2024-02-12 08:42 UTC, caalador approved these changes

2024-02-12 09:15 UTC, merged