fix: do not run generator without hilla
vaadin/flow pull request #18677
Opened 2024-02-12 11:48 UTC by caalador

Do not add the generators
if not hilla used in project.

Fixes vaadin/platform#5016

2024-02-12 11:51 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +        if (endpointGeneratorTaskFactory != null && FrontendUtils
Could the whole `addEndpointServicesTasks` method be skipped if Hilla is not used?

2024-02-12 12:32 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +        if (endpointGeneratorTaskFactory != null && FrontendUtils
Well there is a comment that it is skipped inside the method. Moved the isUsed check to be first.

2024-02-12 14:07 UTC, mcollovati requested changes
There's a compilation error in one test, but other than that LGTM

2024-02-12 14:07 UTC, mcollovati commented on flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
> +                lookup(EndpointGeneratorTaskFactory.class);
```suggestion
                .lookup(EndpointGeneratorTaskFactory.class);
```

2024-02-13 04:43 UTC, caalador commented on flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
> +                lookup(EndpointGeneratorTaskFactory.class);
Done.

2024-02-13 10:10 UTC, mcollovati approved these changes

2024-02-13 10:38 UTC, merged