chore: upgrade minimum supported Gradle version to 8.4
vaadin/flow pull request #18683
Opened 2024-02-13 08:34 UTC by tarekoraby

Close https://github.com/vaadin/platform/issues/5027.

Related to https://github.com/vaadin/flow/issues/18367.

2024-02-13 08:43 UTC, tarekoraby commented
I keep forgetting what the `+0.0.1` label is supposed to signify. But just to clarify, this change should be in the next Minor (not 24.3)

2024-02-13 10:32 UTC, mcollovati requested changes
`VaadinSmokeTest.pluginShouldFailWithUnsupportedGradleVersion` should be updated as well

2024-02-13 12:11 UTC, tarekoraby commented
There is a failure at https://github.com/vaadin/flow/blob/43aab7c96b56d8fcec73a4774b9854197522449c/flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt#L31. I don't understand what's wrong nor how to fix it.

2024-02-13 12:16 UTC, mcollovati commented
> I don't understand what's wrong nor how to fix it.

The test ensures that gradle plugin works in MPR, in combination with the [com.devsoap.plugin.vaadin](https://github.com/johndevs/gradle-vaadin-plugin) gradle plugin that is for Vaadin 8.
However, the Vaadin 8 compatible plugin is not maintained anymore, and it looks like it cannot run with Gradle 8.

So I think it means that after this upgrade we cannot support gradle anymore in MPR projects

2024-02-14 10:34 UTC, mcollovati approved these changes

2024-02-14 10:48 UTC, merged