NPM SBOM generator fixes
vaadin/flow pull request #18690
Opened 2024-02-13 11:15 UTC by tepi

2024-02-13 11:21 UTC, tepi commented
My review comments copied from previous closed PR:

2024-02-15 07:12 UTC, sosa-vaadin submitted a review, later dismissed

2024-02-16 14:26 UTC, mshabarov commented
> Accept the fact that the add/modify could happen since npm install is run, and document this fact so the developers will know about it.

This seems to me a better approach, at least as a first step towards solving the problem. One may want to audit the installed packages once SBOM is generated and then run `vaadin:clean-frontend` manually afterwards.

2024-02-16 14:31 UTC, mshabarov requested changes

2024-02-16 14:31 UTC, mshabarov commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/GenerateNpmBOMMojo.java
> -@Mojo(name = "generate-npm-sbom", requiresDependencyResolution = ResolutionScope.COMPILE, defaultPhase = LifecyclePhase.PROCESS_RESOURCES)
This was changed recently to PROCESS_RESOURCES. Does it produces some error?

2024-02-16 14:31 UTC, mshabarov commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/GenerateNpmBOMMojo.java
> +                        .withProductionMode(false);
Would it better to add a `productionMode` parameter, so that SBOM can be made for production profile?

2024-02-16 14:31 UTC, mshabarov commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/GenerateNpmBOMMojo.java
> +                new NodeTasks(options).execute();
I propose to add info logging telling that SBOM generation created node_modules and all needed meta-data, if you don't need it, please run `mvn vaadin:clean-frontend` goal.

2024-02-19 12:54 UTC, mshabarov commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/GenerateNpmBOMMojo.java
> -@Mojo(name = "generate-npm-sbom", requiresDependencyResolution = ResolutionScope.COMPILE, defaultPhase = LifecyclePhase.PROCESS_RESOURCES)
@sosa-vaadin what do you think?

2024-02-19 14:21 UTC, sosa-vaadin commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/GenerateNpmBOMMojo.java
> -@Mojo(name = "generate-npm-sbom", requiresDependencyResolution = ResolutionScope.COMPILE, defaultPhase = LifecyclePhase.PROCESS_RESOURCES)
No error is produced. The `prepare-frontend` goal is done in `PROCESS_RESOURCES` and that is why we changed this one as well. But since it can now run the `npm install` task, running `prepare-frontend` beforehand is not strictly necessary.

I can change it back though, don't see why not.

2024-02-19 14:37 UTC, mshabarov commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/GenerateNpmBOMMojo.java
> -@Mojo(name = "generate-npm-sbom", requiresDependencyResolution = ResolutionScope.COMPILE, defaultPhase = LifecyclePhase.PROCESS_RESOURCES)
Thanks for the explanations, got it. Let's keep it as is then.

2024-02-19 15:05 UTC, sosa-vaadin commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/GenerateNpmBOMMojo.java
> +                new NodeTasks(options).execute();
Done.

2024-02-19 15:05 UTC, sosa-vaadin commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/GenerateNpmBOMMojo.java
> +                        .withProductionMode(false);
Done.

2024-02-19 15:06 UTC, sosa-vaadin commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/GenerateNpmBOMMojo.java
> -@Mojo(name = "generate-npm-sbom", requiresDependencyResolution = ResolutionScope.COMPILE, defaultPhase = LifecyclePhase.PROCESS_RESOURCES)
Done.

2024-02-20 18:29 UTC, merged