Add methods for checking roles and authorities
vaadin/flow pull request #18700
Opened 2024-02-14 10:06 UTC by peholmst

This PR adds methods for checking the user's roles and authorities. The purpose is to make the `AuthenticationContext` more in line with the `useAuth` hook in Hilla and reduce the need for implementing a custom "security service". In many cases, it should be enough to inject and use the `AuthenticationContext` directly.

2024-02-14 10:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=18700) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=18700) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=18700) it.</sub>

2024-02-14 10:11 UTC, knoobie commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
> +    private static final String ROLE_PREFIX = "ROLE_";
That value is not really static :) See https://github.com/vaadin/flow/blob/a130d64a9077cdedcbe41fa3eba4d781a0146e35/vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java#L194

2024-02-14 11:32 UTC, knoobie commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
> +        return hasAnyAuthority(roles.map(role -> getRolePrefix() + role));
```suggestion
        var rolePrefix = getRolePrefix();
        return hasAnyAuthority(roles.map(role -> rolePrefix + role));
```

hasAnyRole and hasAllRoles can be quite the hot-path; therefore I would reduce the amount of calculation needed to re-create the role prefix multiple times in the same request/check - especially with hundreds of roles..

While thinking about hot-path: Is the usage of stream here really necessary? (Up for others to decide)

2024-02-14 12:09 UTC, peholmst commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
> +        return hasAnyAuthority(roles.map(role -> getRolePrefix() + role));
That was a good catch, I hadn't noticed it. I've now rewritten the checks to be more efficient.

2024-02-15 15:05 UTC, mcollovati requested changes
Some nits, but other than that, look good to me

2024-02-15 15:05 UTC, mcollovati commented on vaadin-spring/src/test/java/com/vaadin/flow/spring/security/AuthenticationContextTest.java
> +        Assert.assertTrue(authContext.hasAnyRole(List.of("ADMIN")));
What about adding a test with both assigned and not assigned roles?
e.g.
```
Assert.assertTrue(authContext.hasAnyRole(List.of("ADMIN", "SUPERADMIN")));
```

2024-02-15 15:05 UTC, mcollovati commented on vaadin-spring/src/test/java/com/vaadin/flow/spring/security/AuthenticationContextTest.java
> +        Assert.assertTrue(authContext.hasAnyAuthority(List.of("AUTH_WRITE")));
What about adding a test with both assigned and not assigned authorities?
e.g.

```
Assert.assertTrue(authContext.hasAnyAuthority(List.of("AUTH_WRITE", "AUTH_MANAGE")));
```

2024-02-15 15:05 UTC, mcollovati commented on vaadin-spring/src/test/java/com/vaadin/flow/spring/security/AuthenticationContextTest.java
I would add some tests as well for `getGrantedRoles()` and `getGrantedAuthorities()`, since there's some logic involved.
However, they may be already indirectly verified by the other tests.

2024-02-16 06:14 UTC, peholmst commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
> +        }
My first version of this PR used that, but it was questioned by @knoobie . Which one do you want, the one with the loop or the one with the stream?

2024-02-16 06:39 UTC, knoobie commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
> +        }
I think he meant that it is probably unnecessary to use a for-loop after the stream was terminated.. so now we are creating s stream, closing it and afterwards iterating over it. The closing (toSet) and for-loop could theoretically be replaced with anyMatch if I understand Marco's intention correctly

2024-02-16 06:46 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
> +        }
Exactly. @knoobie explained clearly my ambiguous comment :smile:

2024-02-16 06:47 UTC, peholmst commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
> +        }
Roger that.

2024-02-16 07:10 UTC, mcollovati approved these changes
LGTM. Thanks @peholmst for adding this feature!

2024-02-16 07:12 UTC, mcollovati commented
I'll create a ticket on docs repository to add a note about this new utility methods in https://vaadin.com/docs/latest/security/enabling-security#security-utilities

2024-02-16 07:17 UTC, merged