fix: include only react-components in package.json
vaadin/flow pull request #18707
Opened 2024-02-14 15:11 UTC by tltv

When React is enabled, package.json update includes only @vaadin/react-components and excludes all other @vaadin/* web-components pinned by platform versions (core and pro). React components are wrappers for web-components. When React is disabled, only web-components are updated in the package.json.

Fixes: #18684

2024-02-16 12:31 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +                    && pinnedPlatformDependencies.contains(key)) {
the contains(key) is always true here as we are iterating the same set of keys as added to the pinnedPlatformDependencies

2024-02-16 12:31 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +        final JsonObject platformPinnedDependencies = getPlatformPinnedDependencies();
Now that the platformPinnedDependencies already filters out the react-components if they are not needed this place only needs to check if the react-components key  `@vaadin/react-components` is available in the Json.
If yes then ignore old components else do not ignore.

2024-02-16 12:31 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +            }
Trusting the `platformPinnedDependencies` content as `boolean reactComponents = pinnedPlatformDependencies.contains("@vaadin/react-components");` would make this:
```suggestion
            if (reactComponents 
                    && pinnedPlatformDependencies.contains(dep.getKey())) {
                continue;
            }
```

Also is this no here just to not add the `@NpmPackage` annotations from server Component definitions?

2024-02-16 12:33 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +        return key.equals("@vaadin/react-components");
As a string check this sounds a bit easy to fail.
A better way would be to collect all the possibilities in the `versions.json` found under the `react` (perhaps in the future `react-pro`) object which is formatted as:
```
    "react": {
        "react-components": {
            "jsVersion": "24.4.0-alpha13",
            "npmName": "@vaadin/react-components"
        }
    },
```

2024-02-16 13:02 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +            }
Yes, basically so. Without this just having vaadin-core dependency would end up adding all web-components. Or having any dependency with `@NpmPackage` with core components.

2024-02-16 13:11 UTC, caalador reviewed
After removing the unused method it looks fine.

2024-02-16 13:11 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +    private boolean isReactModuleAvailable() {
This is now not needed as it's not used anywhere in the class

2024-02-16 13:14 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +    private boolean isReactModuleAvailable() {
removed

2024-02-19 10:50 UTC, mshabarov requested changes
The case where package.json isn't exist looks working well, but if package.json exists before starting the app and it has WCs, then they aren't removed.

2024-02-19 10:50 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +            }
This looks dangerous and probably not correct, as it skips adding everything from platform's versions json that isn't `@vaadin/react-components`. Besides web-component, versions json has lumo, polymer, bundles, statistics and potentially other "non-component" dependencies that are skipped with this codes.

Also, if I run this patch with the existing package.json containing the web-components, this patch doesn't remove them from, probably because the logic below in this method isn't running, which is incorrect.

But from the other side, how Flow can only extract semantically web-components entries...Should we change the structure of `versions.json` in the platform, so it would store web-components in a separated sub-list?

2024-02-19 12:04 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +            }
It's not removing existing dependency as that's how the package.json update works in general. but if you think, it's safe to remove existing, it could be done too. Just not adding it is probably safer.

2024-02-19 12:18 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +            }
Well, retaining them would require package.json removal during migration to effectively trigger this feature, but this is probably fine. Maybe it's indeed safer to only not adding them.

Having a sub-list is discussible, see the corresponding discussion in Slack.

2024-02-19 12:22 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +            }
My main concern vs merging this change is these messages in the logs:
```
2024-02-19T13:28:30.526+02:00  INFO 10210 --- [onPool-worker-1] c.v.f.server.frontend.TaskUpdateImports  : 

  Failed to find the following imports in the `node_modules` tree:
      - @vaadin/polymer-legacy-adapter/style-modules.js
  If the build fails, check that npm packages are installed.

  To fix the build remove `package-lock.json` and `node_modules` directory to reset modules.
  In addition you may run `npm install` to fix `node_modules` tree structure.

@vaadin/bundles npm package is not found, Vaadin component dependency bundles are disabled.

 Error: The following dependencies are imported but could not be resolved:
2024-02-19T13:28:36.541+02:00  INFO 10210 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 
2024-02-19T13:28:36.541+02:00  INFO 10210 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   @vaadin/polymer-legacy-adapter/style-modules.js
```

These shouldn't be logged at least if we think that there is no impact on applications.

2024-02-19 13:08 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +            }
Let's put on hold this PR until we decide about a solution to add/remove only components.

2024-02-20 09:19 UTC, mshabarov commented
We have to do the following:

1. Add a new parameter/option into entries in `version.json` in platform with values `react` / `lit` / `all` (or empty) and key "mode", e.g.:
```
       "accordion": {
            "javaVersion": "{{version}}",
            "jsVersion": "24.4.0-alpha13",
            "npmName": "@vaadin/accordion",
            "mode": "lit"
        }
```
2. Remove `@NpmPackage` annotations from Flow components importing web-components packages.
3. Extend `TaskUpdatePackages` with a logic that dynamically adds the components depending on the project config (React/Lit).

2024-02-21 14:37 UTC, mshabarov requested changes

2024-02-21 14:37 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
> +            if (!isIncludedByMode(json)) {
Now with this new method the old approach above `(!reactEnabled && isReactObject(key))` isn't needed anymore.
Flow should add or not to add the npm dependency based on this mode value.

2024-02-21 14:37 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
> +    private static final String MODE = "mode";
Better to make it private so platform's codes can reuse it if necessary.

2024-02-21 14:37 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    static boolean isPackageKeyReactComponents(String key) {
Looks like this isn't needed anymore.

2024-02-21 14:37 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
> +            if (!isIncludedByMode(json)) {
Also IMO it would be better to structure it as:
```java
if (isIncludedByMode(json)) {
            if (json.hasKey(NPM_NAME)) {
                addDependency(json);
            } else {
                collectDependencies(json);
            }
}
```

2024-02-21 14:37 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
> +            return MODE_LIT.equalsIgnoreCase(mode);
I propose to add a debug logging to each cases, showing the package name and it's version.

2024-02-21 14:37 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
> +                        "            \"npmName\": \"@vaadin/react-components\"\n" +
this needs a `react` mode ?

2024-02-22 08:35 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
> +            if (!isIncludedByMode(json)) {
Current code does not require "mode: react" for react dependencies. If we change this so that "mode: react" is needed in version.json, then we need to add it in platform versions.json and wait for next snapshot before we merge this PR (this takes more time naturally).
If we keep it as it is, we can merge this/platform independently. Which path should we take?

2024-02-22 08:36 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
> +    private static final String MODE = "mode";
I assume you mean public.

2024-02-22 09:53 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
> +            if (!isIncludedByMode(json)) {
Discussed and decided to add react mode in platform and this means that [platform PR needs to be merged first](https://github.com/vaadin/platform/pull/5076) before this PR can be merged (after related changes). In other words, we will not depend on "react" and "react-pro" keys anymore. We use "mode: react" feature instead.

2024-02-22 09:59 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
> +            return MODE_LIT.equalsIgnoreCase(mode);
done (refactored)

2024-02-22 10:25 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
> +    private static final String MODE = "mode";
Ah yes! Public :)

2024-02-22 10:31 UTC, mshabarov requested changes
LGTM, except that for some reason this PR gets not-related changes from other commits.
Needs a clean-up and rebase.

2024-02-22 10:35 UTC, tltv commented
> LGTM, except that for some reason this PR gets not-related changes from other commits. Needs a clean-up and rebase.

It's just how github shows commits _after_ rebasing. So it's already rebased.

2024-02-22 10:39 UTC, mshabarov commented
I see some other commits in your branch. I propose to revert them and squash all the commits. Then merge latest main.
Also this PR has some conflicts.

2024-02-22 10:52 UTC, mshabarov approved these changes

2024-02-23 07:54 UTC, merged