feat: update gradle plugin clean tasks
vaadin/flow pull request #18756
Opened 2024-02-19 16:16 UTC by tltv

Updates Vaadin Gradle plugin to clean in same way as Maven plugin cleans. Moved  CleanFrontendMojo logic to CleanFrontendUtil in shared flow-plugin-base. Updated VaadinCleanTask and VaadinBuildFrontendTask. Added cleanFrontendFiles property to Gradle plugin.

Fixes: #18556

2024-02-20 16:07 UTC, mcollovati requested changes

2024-02-20 16:07 UTC, mcollovati commented on flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
> +                implementation("com.vaadin.hilla:endpoint:$flowVersion")
This will probably fail because the validation job may change `flowVersion` and also there may not yet exist a Hilla artifact with the same version at them moment of the validation.
I propose to create a local jar with a stub  `com.vaadin.hilla.EndpointController` class and add that as a dependency (it should be something like `implementation files('libs/my-jar.jar')`)

2024-02-21 16:20 UTC, tltv commented on flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
> +                implementation("com.vaadin.hilla:endpoint:$flowVersion")
done

2024-02-21 16:40 UTC, mcollovati submitted a review, later dismissed

2024-02-21 16:40 UTC, mcollovati commented
LGTM, but probably @mshabarov also wants to take a look

2024-02-22 07:43 UTC, mshabarov requested changes

2024-02-22 07:43 UTC, mshabarov commented on flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
> -        val pnpmFileJs = testProject.newFile("pnpmfile.js")
This kind of files may exist in old projects, why do you think it's not needed in test?

2024-02-22 07:43 UTC, mshabarov commented on flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
> -        expect(false) { typesDTs.exists() }
This deleted, but not brought back in the new test codes?

2024-02-22 07:43 UTC, mshabarov commented on flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
> +        testProject.newFile("frontend/index.ts")
I suppose some content is needed to truly force the Hilla detection, or is it done somewhere else?

2024-02-22 07:43 UTC, mshabarov commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinCleanTask.kt
> - * * `types.d.ts` (used by Vaadin 15+)
Why these are deleted?

2024-02-22 07:43 UTC, mshabarov commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinCleanTask.kt
> -                "vite.generated.js, tsconfig.json, types.d.ts, pnpm-lock.yaml, pnpmfile.js, .pnpmfile.cjs and package-lock.json"
Why these are deleted?

2024-02-22 07:43 UTC, mshabarov commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/CleanFrontendUtil.java
> +    public static class Options {
I propose to extract this into a separate class `CleanFrontendOptions` from util class.

2024-02-22 10:24 UTC, tltv commented on flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
> +        testProject.newFile("frontend/index.ts")
EndpointController class is in a hilla-endpoint-stub.jar file that is added in a build file just for a test.

2024-02-22 10:26 UTC, tltv commented on flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
> -        val pnpmFileJs = testProject.newFile("pnpmfile.js")
Same answer as in other comment.

2024-02-22 10:26 UTC, tltv commented on flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
> -        expect(false) { typesDTs.exists() }
Same answer as in other comment.

2024-02-22 11:47 UTC, mshabarov commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinCleanTask.kt
> - * * `types.d.ts` (used by Vaadin 15+)
Ok, let's handle this in a separate discussion. Probably it is so, because these files may have a custom content and thus not deleted.

2024-02-22 11:49 UTC, mshabarov commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/CleanOptions.java
> + *
Needs some javadocs, otherwise LGTM.

2024-02-22 12:42 UTC, mshabarov approved these changes

2024-02-22 13:31 UTC, merged