Publish ServiceInitEvent as Spring event
vaadin/flow pull request #18819
Opened 2024-02-28 09:11 UTC by mstahv

Partial "regression safe" solution to #14086.

Not tested yet in any way. Openin as draft PR to get tests executed.

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2024-03-04 15:25 UTC, tltv requested changes
Change looks good to me. Missing JavaDoc and one integration test for this in `flow-tests/vaadin-spring-tests/test-spring-common` and it's good to go as a first step for the main ticket.

2024-03-04 15:25 UTC, tltv commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java
>      public Stream<VaadinServiceInitListener> getServiceInitListeners() {
Needs some Javadoc with the template from the `Instantiator` interface plus mention EventListener support.

2024-03-04 19:04 UTC, mstahv commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java
>      public Stream<VaadinServiceInitListener> getServiceInitListeners() {
This method? Why would it now start to need it? In general the whole class is an implementation detail 🤔

I think the only sane place to document that ServiceInitListener is now published as a spring event is the reference docs. IIRC the related, existing, CDI feature is documented there as well.

2024-03-04 19:34 UTC, mstahv commented
Added an IT blindly to flow-tests/vaadin-spring-tests/test-spring-common, I have no idea how that project is supposed to be used. mvn verify didn't seem to do anything.

2024-03-05 10:29 UTC, mstahv commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java
>      public Stream<VaadinServiceInitListener> getServiceInitListeners() {
I don't understand why 

* the current behaviour don't need JavaDoc 
* why would somebody find this classess JavaDoc

2024-03-05 10:29 UTC, mstahv commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java
>      public Stream<VaadinServiceInitListener> getServiceInitListeners() {
Without understanding those, I really don't have anything reasonable to write to the javadoc

2024-03-05 10:31 UTC, mstahv commented
Some unit test was failing after I pulled in changes from master but apparently re-initiating them fixed it 🤷‍♂️

2024-03-05 10:49 UTC, tltv commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java
>      public Stream<VaadinServiceInitListener> getServiceInitListeners() {
SpringInstantiator is public class and it's constructed at least in SpringVaadinServletService. But could be used somewhere else too. This is one reason to have proper JavaDoc.

For example something like this would be enough:

```
    /**
     * Gets all service init listeners to use. Registers by default an init
     * listener that publishes ServiceInitEvent to application context.
     *
     * @return stream of service init listeners, not <code>null</code>
     */
```

2024-03-05 11:18 UTC, mstahv commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java
>      public Stream<VaadinServiceInitListener> getServiceInitListeners() {
I still don't get who will ever be reading this or why the original behaviour don't need to be mentioned in the doc, but I guess the cheapest way to get forward to do something that makes a difference is to copy-paste this into the class 🤷‍♂️

2024-03-05 11:46 UTC, tltv commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java
>      public Stream<VaadinServiceInitListener> getServiceInitListeners() {
Repeating whole original just didn't seem necessary, so trimmed it a bit to the point. Who will ever read this? I guess there's possibility that some projects customizes this even outside of the Flow maintenance team.

2024-03-05 12:07 UTC, tltv approved these changes
Looks good.

Tip: To run IT locally:

```
mvn verify -pl :vaadin-test-spring-helpers,:vaadin-test-spring-common,:vaadin-test-spring-boot -Dit.test=ComponentAddedVia*
```

2024-03-05 12:28 UTC, tltv commented
I can add new article for this feature (probably in spring/events page) in docs unless @mstahv you are already on it?

2024-03-05 15:51 UTC, mstahv commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java
>      public Stream<VaadinServiceInitListener> getServiceInitListeners() {
Yeah, and now somebody could claim the interface doc was more informative and now hidden. And it still don't mention the the previous (auto registration of ServiceEventListener beans) feature. But as said, I'm fine with or without JavaDocs, there are dozends of more important places to document, I really hope nobody needs to touch this implementation detail of our Spring  integration...

2024-03-08 08:34 UTC, merged