feat: Add interface for Hilla routes to add public matchers
vaadin/flow pull request #18822
Opened 2024-02-28 10:43 UTC by krissvaa

Adds support for Hilla to use VaadinWebSecurity with file-system routes and to secure them.

Fixes https://github.com/vaadin/hilla/issues/2051

2024-02-28 10:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=18822) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=18822) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=18822) it.</sub>

2024-02-28 10:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=18822) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=18822) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=18822) it.</sub>

2024-03-04 15:10 UTC, mcollovati requested changes
Some minor comments on Javadoc and a proposal to simply the interface.

In addition, we need some tests (could maybe be added to `RequestUtilTest`, or in a new test class if it will simplify maintenance).

I also realized that we are missing tests to verify the usage of `RequestUtil.isAnonymousEndpoint`. It would be good if we could also add these.

2024-03-04 15:23 UTC, mcollovati commented
Additional note: we should also check that the new request matchers work fine with `SpringAccessPathChecker`.
Basically, enabling route path access checker, Hilla view access should be automatically checked as well for Flow navigation (e.g. `UI.navigate("hilla-view")`).

In particular, we need to verify if `RequestUtil.isAnonymousHillaRoute()` needs a check similar to `RequestUtil.isAnonymousRoute()` to prevent endless recursion.

2024-03-08 13:18 UTC, cromoteca commented
Closing for now as we don't need this unless we want to enable the feature by default one day.

2024-03-08 13:18 UTC, closed without merging