feat: default routes.tsx for fs router
vaadin/flow pull request #18904
Opened 2024-03-06 14:46 UTC by tltv

Generate default routes.tsx with a support for File System router. FS router plugin is always installed by default when react is enabled.

Fixes: #18813

2024-03-07 08:38 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +                if (FrontendUtils.isHillaUsed(options.getFrontendDirectory(),
The content should be the same for all cases.
As we move it to `frontend/generated`, it can be generated even for plain Flow app.

2024-03-07 08:39 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +                                      route.children?.push(...serverSideRoutes);
Only `route.children?.push(...serverSideRoutes);` can be used when we add `children` property to route object in Hilla.

2024-03-07 08:40 UTC, mshabarov commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes-fs.tsx
> +export const routes = getDefaultReactRoutes();
This would be better to explicitly configure in this file, because:
1. Import routes from Flow looks semantically incorrect
2. For non standard cases developer would need to remove this method and rewrite anyway.

2024-03-07 12:03 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +    static final String FRONTEND_VIEWS_FOLDER = "views";
This already exists in `FrontendUtils::HILLA_VIEWS_PATH`

2024-03-07 12:04 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateVite.java
> +        if (options.isReactEnabled() && EndpointRequestUtil
Why we need to check for hilla class?

2024-03-07 12:13 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateVite.java
> +        if (options.isReactEnabled() && EndpointRequestUtil
We can't actually. Tests are failing probably due to this. Need to remove it.

2024-03-07 12:21 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateVite.java
> +        if (options.isReactEnabled() && EndpointRequestUtil
Fixed

2024-03-07 12:21 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +    static final String FRONTEND_VIEWS_FOLDER = "views";
Done

2024-03-07 12:22 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +                                      route.children?.push(...serverSideRoutes);
Rewritten for new spec.

2024-03-07 12:22 UTC, tltv commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes-fs.tsx
> +export const routes = getDefaultReactRoutes();
Rewritten for new spec.

2024-03-07 12:22 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +                if (FrontendUtils.isHillaUsed(options.getFrontendDirectory(),
Rewritten for new spec.

2024-03-08 09:17 UTC, caalador commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
> +    "@vaadin/hilla-file-router": "24.4.0-alpha10"
This looks like it will create issues with updating the version. Could we instead have the default views.ts not use the hilla-file-router at all and return a empty object 
 `{ path: "", module: undefined, children: [] }` 
 
 And move the `toReactRouter` from routes.tsx to views.ts that we would always extend with a method?
 e.g. we would in routes.tsx only have `import buildRoutes from 'Frontend/generated/views.js';` with the call `export const routes = buildRoutes(...serverSideRoutes)` which would do all the heavy lifting with imports and return routes.

2024-03-08 09:54 UTC, tltv commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
> +    "@vaadin/hilla-file-router": "24.4.0-alpha10"
Same version update maintenance issue as with already existing dependencies. We need this for the Vite plugin installation. So adding it in case when hilla is not used otherwise, but still using react. To get the views.ts generated.

views.ts exports routes which is `AgnosticRoute` type, so not sure if it's good idea to hide this type completely. Also, hilla generates this same content when views folder exists and doesn't have any views.

Auto-detection of hilla views based on the `const routes = [...serverSideRoutes]` is still in use. If we change this format in the routes.tsx, then auto-detection should also understand the new format. Or as discussed before, we don't necessarily need to check routes.tsx content at all anymore, but somehow we need to know when there are only server side routes when using routes.tsx. So the content based check is still used because it works right now. If we do this suggested change, how do we check this instead?

2024-03-08 10:58 UTC, caalador commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
> +    "@vaadin/hilla-file-router": "24.4.0-alpha10"
It's not quite the same as it should be up to date with the vaadin release version. (this should be fine when having the platform versions.json I think)
Also now we have flow dependency towards hilla functionality that is always there even when hilla is explicitly excluded.

2024-03-08 11:36 UTC, tltv commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
> +    "@vaadin/hilla-file-router": "24.4.0-alpha10"
Actually, after adding this fallback routes.ts in Flow, we can probably revert a bit back to only install plugin when hilla is used. Because why would you now need the plugin to generate that "blank" views.ts file, if we do it anyway in Flow. Original idea was to let Hilla plugin generate views.ts always, but we can generate "blank" just as well in Flow side, imho. And in practice we have to do that as a fallback method, it seems. If views folder doesn't exist at all, hilla plugin doesn't generate anything.

2024-03-08 12:37 UTC, mshabarov requested changes

2024-03-08 12:37 UTC, mshabarov commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +  routes.push(route);
This doesn't work if I simply have `frontend/views/my-view.tsx` without a main layout.
It's because if you have undefined "element", it makes troubles for react router and it cannot navigate to Flow view.
This works for me:
```
if(route.children && route.children.length > 0) {
  route.children.push(...serverSideRoutes);
  routes.pop();
  if (route.element) {
    routes.push(route);
  } else {
    routes.push(...route.children);
  }
}
```
So we have to check if the root element is actually defined.

2024-03-08 12:37 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateVite.java
> +        if (options.isReactEnabled()) {
Vite generated file is now generated even for Flow app with default bundle.
Shouldn't be there.

2024-03-08 12:37 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateVite.java
> +        if (options.isReactEnabled()) {
Probably we miss an additional "is bundle" check.

2024-03-08 12:48 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateVite.java
> +        if (options.isReactEnabled()) {
If we revert this back to the original, then we should be good with bundle too. Check out this thread https://github.com/vaadin/flow/pull/18904#discussion_r1517605620

2024-03-08 13:09 UTC, tltv commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +const route = toReactRouter(views);
If block uses `route`: `if(route.children && route.children.length > 0) {`.

2024-03-08 13:36 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateVite.java
> +        if (options.isReactEnabled()) {
I propose to revert, as now I get confused. With this change:
1. Flow + default bundle - Vite config and empty views are created. Routes.tsx and Flow.tsx aren't created. I believe we shouldn't generate Vite config and views.ts at all in this mode.
2. Flow + custom bundle - Vite config, empty views.ts, routes.tsx and Flow.tsx are generated. I don't know why we need the latter 3 files. I propose to not generate them at all and not add the Vite plugin. Also, application doesn't work with this new change - UI isn't rendered at all.
3. Flow + Hilla views in views folder - Vite config, views.ts, routes.tsx and Flow.tsx have to be generated. But in this case views.ts is generated by Hilla plugin.

All of these give me a clue that Flow shouldn't generate `views.ts` at all. It shouldn't generate routes.tsx and Flow.tsx either for bundles modes as well.

Instead, only generate all of these files when Hilla is used.

2024-03-08 13:45 UTC, tltv commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
> +    "@vaadin/hilla-file-router": "24.4.0-alpha10"
Tests fails now to `import { toReactRouter } from '@vaadin/hilla-file-router/runtime.js';` in routes.tsx after reverting. So that import has to be dynamic, if we don't require the plugin.

2024-03-08 13:46 UTC, mshabarov commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
> +    "@vaadin/hilla-file-router": "24.4.0-alpha10"
Seems like `views.tsx`, as well as `Flow.tsx` and `routes.tsx` are NOT needed for bundle modes.
See my comment below.

2024-03-08 14:06 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateVite.java
> +        if (options.isReactEnabled()) {
Well, this isn't that easy as I described. I missed the fact that `index.tsx` imports routes and default bundle also have index and routes already generated.

2024-03-08 14:29 UTC, mshabarov commented
We don't need to check `serverSideRoutes` for `isHillaUsed`:
```
        var files = List.of(FrontendUtils.INDEX_TS, FrontendUtils.INDEX_TSX,
                FrontendUtils.ROUTES_TS, FrontendUtils.ROUTES_TSX);
        for (String fileName : files) {
          ....
        }
```
Can be removed, as it switched to Vite for custom bundle.

2024-03-08 15:19 UTC, tltv commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
> +    "@vaadin/hilla-file-router": "24.4.0-alpha10"
Latest changes adds more dynamic import for hilla-file-router and new `buildRoute` function in Flow.ts. A bit like Mikael suggested, but not in views.ts. Let's see how it works and let's improve it if needed. Point is to not require hilla-file-router and let Flow.ts handle the import automatically.

2024-03-11 09:23 UTC, tltv commented
> We don't need to check `serverSideRoutes` for `isHillaUsed`:
> 
> ```
>         var files = List.of(FrontendUtils.INDEX_TS, FrontendUtils.INDEX_TSX,
>                 FrontendUtils.ROUTES_TS, FrontendUtils.ROUTES_TSX);
>         for (String fileName : files) {
>           ....
>         }
> ```
> 
> Can be removed, as it switches to Vite for custom bundle with the new content in `routes.tsx`

We still need to check it to also detect the case when routes in `routes.tsx` is build manually without any views in Frontend/views folder.

2024-03-12 07:37 UTC, caalador commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
> +//%buildRouteFunction%
no new line.
Just for usability I would perhaps have here 

```suggestion
export const buildRoute = (views: any): any => {
  //%buildRouteFunction%
}
```
 and the replace would just be `return views;` or `return toReactRouter(views);` to have as little coding in strings as possible. 
 
 Didn't see a need for `// @ts-ignore`

2024-03-12 07:37 UTC, caalador commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +}
I would drop the serverSideRoutes check and move adding of serverSideRoutesTo the buildRoute method so that the default routes.tsx would not import serverSideRoutes nor views, only buildRoute

so it would look like:
```
export const routes = buildRoutes();
```

or  for the manual case
```
let routing = [
    {
        element: <MainLayout />,
        handle: { title: 'Main' },
        children: [
            { path: '/', element: <AboutView />, handle: { title: 'Welcome' } },
            { path: '/hilla', element: <HillaView />, handle: { title: 'Hilla' } }
        ],
    },
] as RouteObject[];

export const routes = buildRoute(routing, routing[0].children);
```


Then the buildRoute method when views is not used would look like:
```

export const buildRoute = (routes?: RouteObject[], serverSidePosition?: RouteObject[]): RouteObject[] => {
    const combinedRoutes = [] as RouteObject[];
    if(!routes) {
        const route: RouteObject = toReactRouter(views);
        if(route.children && route.children.length > 0) {
            serverSidePosition = route.children;
            if (route.element) {
                routes = [route];
            } else {
                routes = route.children;
            }
        }
    }
    if(serverSidePosition) {
        serverSidePosition.push(...serverSideRoutes);
    } else {
        combinedRoutes.push(...serverSideRoutes);
    }
    if(routes) {
        combinedRoutes.push(...routes);
    }
    return combinedRoutes;
};
```
where 
```
    if(!routes) {
        const route: RouteObject = toReactRouter(views);
        if(route.children && route.children.length > 0) {
            serverSidePosition = route.children;
            if (route.element) {
                routes = [route];
            } else {
                routes = route.children;
            }
        }
    }
``` 
would be the fill for `//%buildRouteFunction%` if hilla automatic views is used.

This would also remove the need for the routes export and circular link as we would be generating the routes in Flow.tsx and could just store it in the method call to be used.

2024-03-12 07:37 UTC, caalador commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +}
Also the need for creating the empty views file would go away.

2024-03-12 09:34 UTC, tltv commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +}
Moving logic out from the routes.tsx makes sense. This is what was suggested to be moved in views.ts instead, but for now we could move it to Flow.ts before the final design for default routes.tsx is decided.

Having both views and serverSideRoutes imported in routes.tsx was one point to keep them there as a reference. Now both are hidden behind this buildRoutes function. I assume imports can make a comeback later in some other form.

We still need to generate empty views file for apps using react without Hilla views. Just to get rid of that hilla-file-router import when it's not installed.

Missing serverSideRoutes also means that isHillaUsed check needs to do something else for routes.tsx. Or probably additional check just for routes.tsx based on the usage of buildRoute. This might be the biggest change in this all.

2024-03-12 09:45 UTC, caalador commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +}
Without hilla views we would just need to not have 
```
    if(!routes) {
        const route: RouteObject = toReactRouter(views);
        if(route.children && route.children.length > 0) {
            serverSidePosition = route.children;
            if (route.element) {
                routes = [route];
            } else {
                routes = route.children;
            }
        }
    }
```
in the `buildRoute` method

So ideally it would be written as
```
export const buildRoute = (routes?: RouteObject[], serverSidePosition?: RouteObject[]): RouteObject[] => {
    const combinedRoutes = [] as RouteObject[];
    //%buildRouteFunction%
    if(serverSidePosition) {
        serverSidePosition.push(...serverSideRoutes);
    } else {
        combinedRoutes.push(...serverSideRoutes);
    }
    if(routes) {
        combinedRoutes.push(...routes);
    }
    return combinedRoutes;
};
```
Where the `%buildRouteFunction%` would be replaced with "" if no hilla views are available.

2024-03-12 09:56 UTC, tltv commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +}
I understood that part. But import to views.js is still always there. I wouldn't touch that before we have some final design. It's better this way that you can always import it and Flow generates it if it's not there. But if it will be never used after all, then let's remove it and import dynamically.

2024-03-12 14:24 UTC, tltv commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +}
This is done now except dependency to routes.tsx in Flow.ts is still there. It's tricky to remove so I suggest to do it separately after rest is done.

2024-03-13 06:56 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +            "import[\\s\\S]?\\{[\\s\\S]?buildRoute[\\s\\S]?\\}[\\s\\S]?from[\\s\\S]?(\"|'|`)Frontend\\/generated\\/flow\\/Flow(\\.js)?\\1;");
The regex is a bit bad  in that if you import 2 things from Flow then it will always fail e.g. if you have ` import { serverSideRoutes, buildRoute} from Flow`.
We should at a later point update this so that it is one regex that checks for serverSideRoutes or buildRoute and accepts other imports inside the `{}` block.

2024-03-13 06:56 UTC, caalador commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
> +export const buildRoute = (routes?: RouteObject[], serverSidePosition?: RouteObject[]): RouteObject[] => {
JavaDoc could be useful for the parameters and what they are used for.
e.g. 
- routes are for adding own route definition, giving routes will skip FS routes
- serverSidePosition is the position where server routes should be put. If non given they go to the root of the routes []

2024-03-13 06:58 UTC, caalador commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +}
The idea was to just either add a Flow.tsx parameter the same way we have 
let prevNavigation: string;
let popstateListener: { type: string, listener: EventListener, useCapture: boolean };
( this works fine for the routes as I did test it)
Or then you could store it on the window.Vaadin object as the value we want is the endresult from buildRoute

2024-03-13 10:07 UTC, tltv commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +}
Split to new ticket: https://github.com/vaadin/flow/issues/18955

2024-03-13 10:26 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +                    "import { toReactRouter } from '@vaadin/hilla-file-router/runtime.js';")
Change to import it only if used.

2024-03-13 10:27 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +                    .replace("//%buildRouteFunction%", "");
Done

2024-03-13 10:27 UTC, tltv commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
> +export const buildRoute = (routes?: RouteObject[], serverSidePosition?: RouteObject[]): RouteObject[] => {
Done

2024-03-13 10:33 UTC, tltv commented
I'll add some new tests regarding buildRoute function but in other PR. No need to wait for those as cases are already tested manually with starters.

2024-03-13 11:21 UTC, caalador approved these changes

2024-03-13 12:16 UTC, mshabarov approved these changes
Works perfect for both cases, when I have default generated `routes.tsx` and if I uncomment explicit routing.

https://github.com/vaadin/flow/issues/18954 is a bit annoying indeed if I try to add serverSideRoutes by hand, but thanks to `buildRoutes` function I don't care anymore.

2024-03-13 12:17 UTC, merged