feat: do not require routes import
vaadin/flow pull request #18968
Opened 2024-03-14 12:47 UTC by caalador

Do not import routes from
routes.tsx if not needed.

Fixes tests so that files are not generated into the flow-server folder.

Fixes #18955

2024-03-18 11:52 UTC, tltv requested changes

2024-03-18 11:52 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +            // For frontendHotdeploy we read the routes from file as re-loading
So this condition is needed now to fix reload. I don't understand exactly how reload can't work with having `let routes`. Could routes be stored in sessionStorage or localStorage instead? Those should survive reloads. Or maybe there's method to read routes directly from the React router.

2024-03-19 06:50 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +            // For frontendHotdeploy we read the routes from file as re-loading
Even using sessionStorage doesn't fix the issue. I don't understand why the update reloads Flow.tsx, but not routes.

2024-03-19 09:01 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +            // For frontendHotdeploy we read the routes from file as re-loading
Seems that for Vite the dependency is the key here to make the reload affect also routes.tsx. Maybe we could just keep the dependency there for the reload, but not use it actually, and with a comment telling that.

2024-03-19 09:13 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +            // For frontendHotdeploy we read the routes from file as re-loading
Only having the import did not make it work in the reload tests

2024-03-26 12:08 UTC, closed without merging