Fix: update tsconfig and log message
vaadin/flow pull request #18987
Opened 2024-03-19 10:12 UTC by caalador

Instead of updating and throwing
exception for 'tsconfig.json'.
Generate .bak file,
update file and log info if the
file is updated.

Fixes #18984

2024-03-19 10:17 UTC, mshabarov commented
I'd suggest to also align/unify how back-up file is created and which format is used for `tsconfig.json` and `types.d.ts`.
Also, it would make sense to log/throw only once in the end, giving a bunch of messages to the user.

See my comments here https://github.com/vaadin/flow/issues/18984#issuecomment-2006594242.

2024-03-19 12:24 UTC, mshabarov commented
Collecting the logs can be done separately, as now we have the [issue](https://github.com/vaadin/flow/issues/18986) for it :)

2024-03-19 13:30 UTC, mshabarov submitted a review, later dismissed
Works as expected to me: messages are logged one time, each has backup file, each has the same format of the file and unique ID.

Couple of nits, feel free to merge, if you think they are non-sense.

2024-03-19 13:30 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfig.java
> +
nit: This has one line break before and after, whereas the similar banner for types.d.ts has two line breaks, would it be better to align them so they both have one or two lines each?

2024-03-19 13:30 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitions.java
> +                            log().warn(UPDATE_MESSAGE);
Misses String.format: `log().warn(String.format(UPDATE_MESSAGE));`
Or `TaskGenerateTsConfig` has redundant String.format, hmm

2024-03-20 04:41 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfig.java
> +
Aligned both to have the same single as used normally.

2024-03-20 04:41 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitions.java
> +                            log().warn(UPDATE_MESSAGE);
Removed unneeded string format

2024-03-20 06:15 UTC, mshabarov requested changes

2024-03-20 06:15 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitions.java
> -
This message should contains old "flowBackup" suffix. Should contain the same text, as for tsconfig: "Old configuration is stored as a '.bak' file."

2024-03-20 06:43 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitions.java
> -
done

2024-03-20 06:56 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitions.java
> +            *  as a '.bak' file.. Please verify that the updated 'types.d.ts' file    *
```suggestion
            *  as a '.bak' file. Please verify that the updated 'types.d.ts' file    *
```

2024-03-20 06:56 UTC, mshabarov approved these changes

2024-03-20 07:12 UTC, merged