fix: update JWT cookie at every request
vaadin/flow pull request #18994
Opened 2024-03-19 17:13 UTC by mcollovati

## Description

Fixes stateless authentication, by updating the JWT cookies at every request, preventing the browser to remove the cookie after initial max-age time is expired.

Fixes #18880

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2024-03-19 17:13 UTC, mcollovati commented
Tested the change also with Hilla integration test

2024-03-20 05:57 UTC, mcollovati commented
Removed workaround for https://github.com/spring-projects/spring-security/issues/12579 since it has been fixed.

2024-03-25 11:47 UTC, mshabarov requested changes

2024-03-25 11:47 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/stateless/VaadinStatelessSecurityConfigurer.java
> +    public static void apply(HttpSecurity http,
Needs javadocs

2024-03-25 11:57 UTC, mshabarov commented
Tested the `hilla-auth` example project with this patch and the expiration date of cookie and saved JWT token are changed from request to request as expected.

2024-03-25 12:20 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/stateless/VaadinStatelessSecurityConfigurer.java
> -    public void setSharedObjects(HttpSecurity http) {
Make sense. I'll change it

2024-03-25 14:26 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/security/stateless/VaadinStatelessSecurityConfigurer.java
> +    public static void apply(HttpSecurity http,
added

2024-03-25 14:47 UTC, mshabarov approved these changes

2024-03-25 15:12 UTC, merged