fix: forward/back navigation in hybrid app
vaadin/flow pull request #19017
Opened 2024-03-22 12:03 UTC by caalador

Going back to Hilla view from
Flow view should not override
history so that forward button
also works to get "back" to Flow view.

Fixes #19003

2024-03-25 10:05 UTC, tltv commented
Tested out and Navigation from Flow view to Hilla view via anchor or vaadin button seems to render just blank content.
![flow-to-hilla-nav](https://github.com/vaadin/flow/assets/2182148/df1ffd0b-7742-443d-bae3-6619667809cb)

2024-03-25 10:10 UTC, tltv requested changes

2024-03-25 10:10 UTC, tltv commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
> +            popstateListener.listener(new PopStateEvent('popstate', {state: 'vaadin-router-ignore'}));
This could be culprit to Flow to Hilla button/anchor navigation not working properly. Wouldn't this basically bypass react router from handling the navigation?

2024-03-25 10:29 UTC, caalador commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
> +            popstateListener.listener(new PopStateEvent('popstate', {state: 'vaadin-router-ignore'}));
it specifically calls the popstate of react-router to not generate a navigation which actually overrides the history.

2024-03-25 10:42 UTC, tltv commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
> +            popstateListener.listener(new PopStateEvent('popstate', {state: 'vaadin-router-ignore'}));
I see. Is it also needed when not calling onBeforeLeave, because it looks like flow would not do anything with the history in this case? (not sure if this is actually related to the issue)

2024-03-25 10:48 UTC, caalador commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
> +            popstateListener.listener(new PopStateEvent('popstate', {state: 'vaadin-router-ignore'}));
That should probably not matter. Actually can't come up with a case where we would actually end up there.

2024-03-25 13:16 UTC, tltv submitted a review, later dismissed

2024-03-25 13:22 UTC, tltv commented
Approved after testing manually. IT's for navigation from Flow to Hilla views and vice versa are still needed but those can be added also in separated PR.

2024-03-25 13:30 UTC, caalador commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
> +                    if(event.detail.nav) {
I'll rename it and add some comments. Wanted to see if this is now working as it should.

2024-03-26 07:43 UTC, caalador commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
> +                    if(event.detail.nav) {
Updated name, added comment, fixed context navigation.

2024-03-27 10:44 UTC, tltv approved these changes

2024-03-27 11:25 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/component/UI.java
> +            if (!trimmedRoute.equals(event.route) && !getInternals()
done

2024-03-27 11:25 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +                .getExpression().contains(containsFilter)).count() > 0;
done

2024-03-27 11:43 UTC, tltv approved these changes

2024-03-27 12:07 UTC, merged