feat: Use a new RouterBuilder API for routes.tsx
vaadin/flow pull request #19020
Opened 2024-03-22 14:28 UTC by mshabarov

Removes the `buildRoutes` method and replaces it with a new [RouterBuilder](https://github.com/vaadin/hilla/pull/2250) API that automatically injects server side routes where needed.

Related-to https://github.com/vaadin/hilla/issues/2238

2024-03-25 08:26 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +            export const serverRoute = serverSideRoutes;
Why do we  have this extra file that just exports an import from Flow that could be just imported from Flow?
If it is the name I think we should just change it in Flow.tsx
Same goes for Flow.tsx which can just be renamed instead of hidden.

2024-03-25 08:26 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +            }
Do we still need the routes fallback as I don't see a must link to it anywhere?

2024-03-25 08:26 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
> -    public void routesContainMultipleFlowImports_noExceptionThrown()
This should be left and test that if you need/want multiple imports from Flow (or the other file) that it does pass the requirement of the regex.

2024-03-25 09:00 UTC, tltv commented
`FrontendUtils#isRoutesTsxContentUsingHillaViews()` has regex checks that should be changed now to support new format. Maybe it's enough to check if `.withReactRoutes(...)` is called. 
Also part in `FrontendUtils#isHillaViewsUsed(File)` that check if there are any views in the Frontend/views/ should now check if `.withFileRoutes(...)` is actually called in addition to having views files.

2024-03-25 09:40 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +            export const serverRoute = serverSideRoutes;
This pursues the goal to have similar imports for FS router and server routes, i.e. server routes import name and a file name from where it is imported: `file-routes.js` and `server-routes.js`.
This is just a matter of better naming for objects, publicly exposed in routes.tsx.

@platosha what do you think? Was there anything more complex behind this new import name, rather than just a "unified" name?

2024-03-25 09:43 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +            }
Yes, seems like it's not needed anymore, as Hilla uses internally in RouterBuilder and Flow apps don's use it.
Will remove it.

2024-03-25 09:52 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
> -    public void routesContainMultipleFlowImports_noExceptionThrown()
Well, no, the regexp now checks for exactly one import (serverRoute), multiple imports aren't expected.
Do you think we should allow the regexp to have multiple imports still ?

2024-03-25 10:31 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
> -    public void routesContainMultipleFlowImports_noExceptionThrown()
I think we should as we should not be limiting, but requiring that the expected import is there.

2024-03-25 15:25 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +            export const serverRoute = serverSideRoutes;
Decided to revert back to `import { serverSideRoutes } from 'Frontend/generated/flow/Flow';` to simplify this PR.

`serverSideRoutes` was used with older versions of Hilla, and now I'm confident that it's a good idea to change it.

We can discuss offline and rename it in the separate PR, if needed.

2024-03-25 15:25 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +            }
Removed.

2024-03-25 15:25 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
> -    public void routesContainMultipleFlowImports_noExceptionThrown()
Brought back.

2024-03-25 15:30 UTC, mshabarov commented
> FrontendUtils#isRoutesTsxContentUsingHillaViews() has regex checks that should be changed now to support new format

This now checks that routes.tsx has `withFileRoutes` or `withReactRoutes` method that means Hilla.

2024-03-26 09:07 UTC, mshabarov commented
Tested with different configurations and routes.tsx content is as expected, also triggers an error if manual changes are incorrect.
Ready for review I think and should wait for RouterBuilder.

2024-03-27 08:24 UTC, caalador approved these changes

2024-03-28 04:53 UTC, caalador commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +    .withServerFallback(serverSideRoutes)
Sounds like a strange handling from the builder. So we can't give the server path?
This sounds like it will be a bit more fragile when the path definition is in 2 places and is easily changed.

This also makes routes-flow and this differ considerably and here we should then just import Flow and give <Flow/> to the withServerFallback

2024-03-28 11:31 UTC, mshabarov commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +    .withServerFallback(serverSideRoutes)
[This fix](https://github.com/vaadin/flow/pull/19063) covers the problem with `/*`, thanks @caalador 👍 

About naming, as we discussed offline, it makes sense to have method with a name `withFallbackComponent` that takes a component (not necessarily Flow route) and fallbacks React Router to it, if no client-side route is matched. E.g. this can be a view that shows custom 404 page.

So having two options
- `import Flow from 'Frontend/generated/flow/Flow';` or
- `import { serverSideRoutes } from 'Frontend/generated/flow/Flow';`

might be fine, depending if it's Hilla or Flow.
We need to count this in the routes.tsx content validation.

2024-03-28 11:35 UTC, mshabarov commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> + * - `protect` adds an authentication later to the routes.
Makes sense, will add more explanations.
And, once we'll have online docs available, it makes sense also to put a link.

2024-03-28 11:39 UTC, caalador commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +    .withServerFallback(serverSideRoutes)
So the regex should be something like: `import[\s\S]?(?:{[\s\S]*serverSideRoutes[\s\S]*}|Flow)+[\s\S]?from[\s\S]?("|'|`)Frontend\/generated\/flow\/Flow(\.js)?\1` so that it matches both imports as a either or

2024-03-28 11:42 UTC, mshabarov commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +    .withServerFallback(serverSideRoutes)
I'd make it so that anything that imported from Flow.tsx with a default import, should match what is passed into `.withServerRoutes`. As dev can change it from Flow to something else.

2024-03-28 11:57 UTC, caalador commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +    .withServerFallback(serverSideRoutes)
Sounds like something that should not be done in a single regex

2024-04-02 07:15 UTC, mshabarov commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +    .withServerFallback(serverSideRoutes)
Tested with `import\\s+(\\w+)\\s+from\\s+(\"|'|`)Frontend\\/generated\\/flow\\/Flow(\\.js)?\\2;[\\s\\S]+withFallbackComponent\\(\\s*\\1\\s*\\)")`, seems to do the job.

2024-04-02 08:39 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +        return routesContent.contains("new RouterBuilder(");
Should we just always check both matchers e.g.
```suggestion
        routesContent = StringUtil.removeComments(routesContent);
        return !FALLBACK_COMPONENT_PATTERN.matcher(routesContent).find() && !SERVER_ROUTE_PATTERN.matcher(routesContent).find();
```
Also fallback component pattern checks more than server route as it checks that there is a with method call.
Perhaps SERVER_ROUTE_PATTERN should also check that there is a `...serverSideRoutes` used in the routes file.

2024-04-02 08:39 UTC, caalador commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +    // ])
Should the withReactRoutes samples be one and the same saying that you can define manually and/or add individual routes.

2024-04-02 08:39 UTC, caalador commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +    .protect();
Also protect should probably be marked as optional to have?

2024-04-02 08:47 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
> +        return routesContent.contains("new RouterBuilder(");
Yep, no complaints against this suggestion.

2024-04-02 08:50 UTC, mshabarov commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +    // ])
Yep, I can merge them into one sample, but still believe that these are two different cases - having overall manual config and adding in the individual route.

2024-04-02 08:50 UTC, mshabarov commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +    .protect();
Makes sense.

2024-04-02 08:51 UTC, caalador commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +    // ])
Can you run with multiple withReactRoutes calls and have all the routes get added?

2024-04-02 08:59 UTC, mshabarov commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +    // ])
From the quick implementation check, it seems like I can call this method multiple times, never tested though.

I don't think that in practice you'll need to call them twice. You either have, for instance, full routes config with login path included, or file rotes + single login path.

2024-04-08 10:10 UTC, tltv requested changes

2024-04-08 14:13 UTC, mshabarov commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +export const { router, routes } = new RouterConfigurationBuilder()
Changed to `import { router } ...` in `generated `index.tsx` file.
`Flow.tsx` has already the `import { routes } ...`, that is fine.

2024-04-09 07:29 UTC, mshabarov commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
> +export const { router, routes } = new RouterConfigurationBuilder()
default routes content for Flow was changed to:
```
import { createBrowserRouter, RouteObject } from 'react-router-dom';
import { serverSideRoutes } from 'Frontend/generated/flow/Flow';

function build() {
    const routes = [...serverSideRoutes] as RouteObject[];
    return {
        router: createBrowserRouter(routes),
        routes
    };
}
export const { router, routes } = build()
```

to have the same exports as for Hilla.

2024-04-09 09:45 UTC, tltv commented
I have this error in browser console with `flow-hilla-hybrid-example`, based on your branch `use-routes-builder`. Main page looked ok with one public view listed. Then sign in page gives me this when clicking Log in button:
![image](https://github.com/vaadin/flow/assets/2182148/91ecafed-da81-4d2b-ab56-1d931c3ee596)

2024-04-09 09:51 UTC, mshabarov commented
I don't see this error, when logged in. This looks as something related to the LoginOverlay component.
Could you try in incognito mode or clear browser cache?

2024-04-09 09:58 UTC, tltv commented
> UPD: This might be related to `AuthContext` from `hilla-react-auth`, let me check.

Not a cache issue as I get same error with Edge/Firefox. Yeah AuthContext is not setup for some reason. Maybe I run with old `hilla-react-auth`.

2024-04-09 10:02 UTC, mshabarov commented
Try to clean up the project and re-run. I've just tested with the latest Hilla snapshot.

2024-04-09 10:08 UTC, mshabarov commented
@caalador could you please also test?

2024-04-09 11:06 UTC, tltv commented
> @tltv could you please also double check if you have `AuthProvider` in the index.tsx?
> ...
> This is required.

Ok I didn't use the custom index.tsx. It's not there in the generated index.tsx and somehow I expected it to be correct automatically. After copying default index.tsx and adjusting like that, it works. Shouldn't Flow auto-generate this part too?

2024-04-09 11:25 UTC, mshabarov commented
This is problematic, as `AuthProvider` requires other codes that needs user information. You can check `auth.tsx` in the starter project. So we cannot easily add it to any project, because it is project-specific.

2024-04-09 12:04 UTC, mshabarov commented
Why don't you use `frontend/index.tsx` file by the way? It should be in the https://github.com/vaadin/flow-hilla-hybrid-example/pull/29

2024-04-09 12:04 UTC, mshabarov commented
And even in the v24.4 branch https://github.com/vaadin/flow-hilla-hybrid-example/blob/v24.4/src/main/frontend/index.tsx.

2024-04-09 12:14 UTC, tltv commented
> Why don't you use `frontend/index.tsx` file by the way? It should be in the [vaadin/flow-hilla-hybrid-example#29](https://github.com/vaadin/flow-hilla-hybrid-example/pull/29)

I'm testing that generated files works too.

2024-04-09 14:02 UTC, mshabarov commented
These are good comments and something that we should investigate.
But not in this PR ofc, as this PR is about using the builder API and adapting to it.

2024-04-09 14:03 UTC, merged