fix: Query in path
vaadin/flow pull request #19087
Opened 2024-04-03 09:11 UTC by caalador

Fix mistaken add of query
parameters into the route
breaking route resolution
when navigating thrhough link.

part of #19080

2024-04-03 10:32 UTC, tltv reviewed
Makes sense. Create also new IT for the main issue (can be in separated PR).
Shouldn't this also remove hash from the baseURI?

2024-04-03 10:55 UTC, caalador commented
Actually this might be a problem in the server side route resolver instead of a problem getting the query. I can only see a couple tests that test the href for routerlink, but nothing that would test actually navigating with the query and that is what fails now.

2024-04-03 11:54 UTC, caalador commented
Now it should be ok and there are tests in place for the navigation.

2024-04-03 13:20 UTC, tltv requested changes

2024-04-03 13:20 UTC, tltv commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
> +    let normalizedPathname = href.replace(baseURI, '').replace(search,'').replace(hash, '');
`search` could in some case contain baseURI (e.g. `https://vaadin.com/view?param=https://vaadin.com`), which could leave invalid query part as a result (`/view?param=`). 
Calling `replace(search,'')` before `replace(baseURI, '')` will fix that.

2024-04-03 13:20 UTC, tltv commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
> +        event.detail.href.replace(document.baseURI, '').replace(event.detail.search ,'').replace(event.detail.hash, '') :
Same here.

2024-04-04 04:18 UTC, caalador commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
> +    let normalizedPathname = href.replace(baseURI, '').replace(search,'').replace(hash, '');
This shouldn't be an issue as per the documentation `If pattern is a string, only the first occurrence will be replaced` so to make it replace all then it would need to be a regex with `/ig` ending.
But switched them anyway

2024-04-04 07:22 UTC, tltv approved these changes

2024-04-04 07:22 UTC, merged