Feature/allow intert for dom events
vaadin/flow pull request #19121
Opened 2024-04-05 13:57 UTC by mstahv

Added API to allow bypassing inert check for DOM events.

Fixes #19116

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2024-04-05 14:27 UTC, mstahv commented
There is bit ugly API changes, but luckily only for internal classes (marked properly with documentation). Some code smell, but don't have good ideas how to refactor as I don't understand all the details related to the implementation.

2024-04-05 14:37 UTC, mcollovati commented
A comment after a quick and not in-depth look: do we really need to change `handleNode()` and `fireEvent()` to add the `inert` flag?
I mean, the flag seems to be used only by `ElementListenerMap.fireEvent()` and I wonder if we could get the same information from the event as we do for `isEnabled`  (e.g. `event.getSource().getNode().isInert()`).
This way, we may probably be able to also remove the hard-coded `instanceof  EventRpcHandler` in `AbstractRpcInvocationHandler`; then `EventRpcHandler` should override `allowInert(...)` to return `true` (similar to `PublishedServerEventHandlerRpcHandler`) since the check will be performed later in `fireEvent`.

I apologize in advance if the above statements are incorrect :grin:

2024-04-05 15:14 UTC, knoobie commented
I would follow Marco's suggestion if it works to reduce the possibility of any breaking change 😅

2024-04-07 10:19 UTC, mstahv commented
The "breaking changes" are only in classes marked with "For internal use only. May be renamed or removed in a future release.", so I think those ought to be rather safe. 

I spent quite a while looking into a way to get the right details, but I sure might have missed some opportunity due to the complexity of the code. I have an hour or two in car so I can give it an another look now, but my my true wish is that somebody who actaully understands this code would step in :-) 

@mcollovati is there any kind of "developer docs" for this internals? Like some kind of brief overview or description of what these classes do or even just some class/sequence diagrams? Currently it is very hard to understand how the thing are supposed to work and why it is build in this way...

2024-04-07 10:35 UTC, mstahv commented
If we can assume that this piece in AbstractRpcInvocationHandler: 

```
StateNode node = ui.getInternals().getStateTree()
                .getNodeById(getNodeId(invocationJson));
```

... returns the same instance as `event.getSource().getNode()` in ElementListenerMap, then passing around the inert flag could be omitted as well. I have no idea, don't really even understand the purpose of StateNode 😬

2024-04-07 11:01 UTC, mstahv commented
Refactored, the current state isn't tested in any ways though now...

2024-04-07 11:42 UTC, mstahv commented
There is now a unit test IT will be there throught the resize event improvement. I think this is ready. Annotation support could be added later if needed, I don't need it.

2024-04-08 06:08 UTC, mcollovati commented
> If we can assume that this piece in AbstractRpcInvocationHandler: ...

The node get from UI in `AbstractRpcInvocationHandler` is the same used to create the`Element` object for the `DomEvent`, so `event.getSource().getNode()` returns the exactly same instance.

2024-04-08 06:19 UTC, mcollovati requested changes

2024-04-08 06:19 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementListenerMap.java
> +        private boolean allowIntert;
Typo here: `allowIntert`

2024-04-08 06:19 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementListenerMap.java
> +                                event.getSource().getTag());
I wonder if we can provide some additional information in the message. For example, the event type.

2024-04-08 06:19 UTC, mcollovati commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/BrowserWindowResizeView.java
> +import com.vaadin.flow.component.UI;
unused import
```suggestion
```

2024-04-08 06:19 UTC, mcollovati commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/BrowserWindowResizeView.java
> +import com.vaadin.flow.component.html.NativeButton;
unused import
```suggestion
```

2024-04-08 06:19 UTC, mcollovati commented on flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
> +    public void listenerReceivesEventsWithAllowIntert() {
Typo
```suggestion
    public void listenerReceivesEventsWithAllowInert() {
```

2024-04-08 06:19 UTC, mcollovati commented on flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
> +    public void listenerReceivesEventsWithAllowIntert() {
I would add a similar test to `EventRpcHandlerTest` to prevent regression because of changes in the `allowInert()` override.

2024-04-08 06:37 UTC, mcollovati commented
It looks like this change is breaking navigation on modal components (`InertComponentIT.modalComponentAdded_routerLinkClicked_navigation`).
Probably `ElementListenerMap.fireEvent()` should allow navigation events (`BrowserNavigateEvent.EVENT_NAME` and `BrowserLeaveNavigationEvent.EVENT_NAME`) regardless of the inert node flag, as `AbstractRpcInvocationHandler.isNavigationInvocation()` does.

2024-04-08 07:30 UTC, mcollovati commented
@mstahv if you are busy, I can apply the changes and then continue the discussion

2024-04-08 13:14 UTC, mstahv commented
@mcollovati Go ahead if you have these in IDE already! Otherwise I can open this again at some point when I can't get text out of my brain 😁

2024-04-08 13:38 UTC, mstahv commented
Nah, if you have good ideas @mcollovati, go for it. My idea was to use the new API for those navigation events, but they are some "special cases" and it started to look complicated...

2024-04-09 12:41 UTC, tepi commented on flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
> +            getLogger().info("Ignored RPC for invocation handler '{}' from "
Would not go for `info` level here. Debug or trace should be fine.

2024-04-09 12:45 UTC, tepi requested changes

2024-04-09 12:45 UTC, tepi commented on flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
> +            getLogger().info(
Would not go for `info` level here. Debug or trace should be fine.

2024-04-09 16:49 UTC, mstahv commented on flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
> +            getLogger().info("Ignored RPC for invocation handler '{}' from "
I very much disagree. This is kind of "should not even happen" case (typically browser side/components should block it as well. If it does, it is most likely either somebody trying to do something evil or issue in our components (or in custom addons), and cant be very odd for the developer as the "exception" is eaten. There is a separate bug & PR for that part: https://github.com/vaadin/flow/issues/18940

2024-04-09 19:07 UTC, mstahv commented on flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
> +    public void listenerReceivesEventsWithAllowIntert() {
done

2024-04-10 09:42 UTC, tepi commented on flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
> +            getLogger().info("Ignored RPC for invocation handler '{}' from "
Fair enough. In normal use this should not happen unless there's a bug somewhere. Developers can of course make it happen with their own code, and in that case info level could make sense. So let's go with info level, and fix possible upcoming issues separately (e.g. something causing these in excess and filling the logs).

2024-04-10 09:42 UTC, tepi commented
Looks good to me! @mcollovati did you have any remaining comments about this one?

2024-04-10 10:57 UTC, mcollovati commented
Looks good to me too. There's still a pending discussion about the message log level, but if we want to differentiate between dev and prod, we can do it in another PR

2024-04-10 10:57 UTC, mcollovati approved these changes

2024-04-10 11:25 UTC, tepi approved these changes

2024-04-10 11:25 UTC, merged

2024-04-10 14:34 UTC, mstahv commented
Excellent! I migth even be so bold that I would throw illegal state exception, at least in dev mode.