fix: make property change listener trigger on removeProperty
vaadin/flow pull request #19196
Opened 2024-04-17 17:40 UTC by akhodyko

Removing element property by calling `com.vaadin.flow.internal.nodefeature.AbstractPropertyMap#removeProperty` does not trigger property change listener because of `com.vaadin.flow.internal.nodefeature.ElementPropertyMap#remove` method is skipped due to `AbstractPropertyMap#removeProperty` method calls super:
```
    public void removeProperty(String name) {
        super.remove(name);
    }
```

Fixes #3994

2024-04-17 17:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=19196) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=19196) before we can accept your contribution.<br/><hr/>**Aleksandr Khodyko** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=19196) it.</sub>

2024-04-19 12:52 UTC, mshabarov submitted a review, later dismissed

2024-04-21 19:48 UTC, akhodyko commented
> @akhodyko thanks for you contribution! Looks good to me! May I transfer this pull request to "ready for review" state?

yes, you can, but there are some trouble with `com.vaadin.flow.data.binder.BinderTest.readBean_converterThrows_exceptionHandlerSet_bindingExceptionIsThrown` test yet.

2024-04-22 06:28 UTC, mshabarov commented
> > @akhodyko thanks for you contribution! Looks good to me! May I transfer this pull request to "ready for review" state?
> 
> yes, you can, but there are some trouble with `com.vaadin.flow.data.binder.BinderTest.readBean_converterThrows_exceptionHandlerSet_bindingExceptionIsThrown` test yet.

That seems wrong, if the Binder doesn't throw while the exception happens in the converter. Weird side effect. We will take a look, thanks!

2024-04-22 12:50 UTC, akhodyko commented
@mshabarov 

I think `readBean_converterThrows_exceptionHandlerSet_bindingExceptionIsThrown` test is not fully correct.

I will try to explain:
1. Before this PR, setting `null` value to `com.vaadin.flow.component.AbstractSinglePropertyField` was not triggered property change listener on removing property here `com.vaadin.flow.component.AbstractSinglePropertyField.TypeHandler#createWriter`. 
2. Because of point 1, `com.vaadin.flow.component.internal.AbstractFieldSupport#pendingValueFromPresentation` was not updated to actual value taking into account default value of field. This caused the field value change event to fire. 
3. After that, value change event caused validation at `com.vaadin.flow.data.binder.Binder#handleFieldValueChange` followed with conversion field value to model.

According to that, because of we have in that test `com.vaadin.flow.data.binder.testcomponents.TestTextField` accepting null values with default empty string value, null value must be treated as empty string and should not trigger the change listener and toModel conversion. 

Replacing bean Person to another with non null firstName field fixed the test.

2024-04-26 12:15 UTC, mshabarov requested changes
As the property removal is now considered as non-client originated event, we have to change to `Assert.assertFalse(event.get().isUserOriginated());` in `ElementPropertyMapTest::removeProperty_fireEvent_listenerIsNotNotified`

2024-04-26 12:19 UTC, mshabarov commented
> According to that, because of we have in that test com.vaadin.flow.data.binder.testcomponents.TestTextField accepting null values with default empty string value, null value must be treated as empty string and should not trigger the change listener and toModel conversion.
Replacing bean Person to another with non null firstName field fixed the test.

This makes sense, okay.

2024-04-26 12:21 UTC, mshabarov commented
Requested another review from @caalador , just in case, if I missed something important, the overall fix looks good to me and correct.

2024-04-26 14:20 UTC, akhodyko commented
> As the property removal is now considered as non-client originated event, we have to change to `Assert.assertFalse(event.get().isUserOriginated());` in `ElementPropertyMapTest::removeProperty_fireEvent_listenerIsNotNotified`

done

2024-04-29 04:51 UTC, caalador reviewed
Looks good to me.

2024-04-29 10:21 UTC, mshabarov commented
@akhodyko could you please run `mvn formatter:format` and push? Then we can merge this change.

2024-05-02 08:23 UTC, akhodyko commented
> @akhodyko could you please run `mvn formatter:format` and push? Then we can merge this change.

done

2024-05-02 09:26 UTC, mshabarov approved these changes

2024-05-02 09:27 UTC, merged

2024-05-06 12:56 UTC, mshabarov commented
This has been reverted due to a regression in Vaadin Flow components (to be more precise, in `RadioButtonGroup`) that blocks our releases, see https://github.com/vaadin/flow/pull/19310.

For the record, the failed test is this:
```
[setIdentifierProviderOnId_setItemWithNullId_shouldFailToSelectExistingItemById] java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.component.radiobutton.CustomItem.getId()" because the return value of "com.vaadin.flow.component.radiobutton.RadioButtonGroup.getValue()" is null
	at com.vaadin.flow.component.radiobutton.RadioButtonGroupTest.setIdentifierProviderOnId_setItemWithNullId_shouldFailToSelectExistingItemById(RadioButtonGroupTest.java:441)
```

I.e. the component reset the value to `null`, if `setValue` is called with an item, that is not present in the items list.
We plan to reconsider the logic in RadioButtonGroup regards invalid items and re-apply this patch again.

2024-09-26 20:09 UTC, akhodyko commented
Are there any plans to release this with 24.5.0?

2024-09-27 06:20 UTC, mshabarov commented
@akhodyko no plans unfortunately, this was reverted and we haven't got back to it again afterwards, because of other priorities. This patch opened the can of worms in Flow components, we tried to fix that, but it turned into complicated problem that even more could bring a behaviour change in components, see the description above.