feat: add API for automatic main menu
vaadin/flow pull request #19202
Opened 2024-04-18 07:57 UTC by tltv

Adds API to get and control only accessible routes for automatically build routes based on `Menu` annotated routes. This change is targeting primarily client side menu build with Hilla.

Adds `RouteRegistry#getRegisteredAccessibleMenuRoutes` to get a list of accessible RouteData objects. Method takes in a collection of access control objects which are implementing `BeforeEnterListener`. Supports `NavigationAccessControl` and `ViewAccessChecker`.

Adds `MenuAccessControl` interface to control `getRegisteredAccessibleMenuRoutes` return value. This change adds first part of control by adding API to enable, disable or automate populating client side main menu with the server side routes. Interface has space for future for more advanced control.

Default `MenuAccessControl` implementation can be customized by implementing it as a Spring bean, or by providing the implementation class via 'menu.access.control' property.

Fixes: #19127

2024-04-18 11:32 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +        var populateClientSideMenu = vaadinService.getInstantiator()
If var doesn't look clear enough in one place, we can just keep pointing them out in reviews and fix them where needed. In many places it just makes code easier to read due to shorter/less repeated types in the code.

2024-04-18 11:39 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/RouteData.java
> +        this.menuData = menuData;
Prebuilding is performance wise more optimal as populating MenuData based on Menu annotation can get costly operation because it can be called a lot. Having it build just once takes care of that.

2024-04-18 11:43 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/auth/MenuAccessControl.java
> +     * populate the menu with server side routes, {@code null} - populate the
No word against this. It was Boolean in acceptance criteria, but having a enum instead would be more flexible too.

2024-04-18 11:49 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/router/RouteData.java
> +        this.menuData = menuData;
getRegisteredRoutes() result is not stored anywhere so each call will anyway collect and generate all the data.
Main concern here is the amount of parameters in the constructor. We could just generate the menu data in the constructor instead as all the required data is available there.

2024-04-18 11:50 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/auth/ViewAccessChecker.java
> +                str -> getRolesChecker(vaadinRequest).apply(str), false);
Yeah, `ViewAccessChecker` is deprecated and marked as removal but need to still support it as long as it's there.

2024-04-18 12:06 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/RouteData.java
> +        this.menuData = menuData;
Dynamically build routes would be harder to support menu then. There's no method in RouteRegistry to set route with menu data yet but my thinking was that there eventually would and therefore constructor needs that MenuData so that it can be read from ConfiguredRoutes and set to RouteData.

2024-04-18 12:10 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/router/RouteData.java
> +        this.menuData = menuData;
But dynamic routes can just have the menu annotation on them if they are wanted to a menu.
Dynamic routes can even have the route annotation and have it as register on startup false.

2024-04-18 12:19 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/RouteData.java
> +        this.menuData = menuData;
That wouldn't be so dynamic then regarding the menu info. Imagine that one has to create another class just to get different icon/title configured for a same view implementation. Dynamic to me means non-annotation way to setup menu.

2024-04-18 13:09 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/MenuData.java
> +        this.exclude = exclude;
Absence of the MenuData can be considered as exclude=true, as it in other words means that route doesn't have Menu annotation. Only accessible server routes with MenuData (=has Menu annotation) are returned.

2024-04-18 14:10 UTC, taefi requested changes

2024-04-18 14:10 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +        }
Since the `getRegisteredRoutes()` method doesn't seem to filter the available routes based on any logic, these lines of code seem buggy to me (I might be wrong, ofc).

I suggest to first resolve the easy cases:
- `if (populateClientSideMenu == ALWAYS`)` then `return getRegisteredRoutes()`
- `if (populateClientSideMenu == NEVER || !isClientMenuUsed(vaadinService)` then `return List.empty()` 

and then the rest of the code should go through checking the two remaining conditions out of those 3 conditions (presence of `@Menu`, presence of `@layout`, and checking against the security context) mentioned in the issue.

2024-04-18 14:10 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +            return fileRoutesJson.contains("\"title\":\"Layout\"");
Checking the existence of `@layout.tsx` by `fileRoutesJson.contains("\"title\":\"Layout\"")` can end up with false positives, since it is possible to have no `@layout` exactly under `Frontend/views/` but has `@layout` under the subdirectories of `views` directory. The correct logic should check for the existence of either `@layout.tsx` or `@layout.jsx` right under `Frontend/views/`.

2024-04-18 14:37 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +        }
Currently if populateClientSideMenu is ALWAYS or AUTO without main layout, it falling back to how it worked before returning all registered routes. But maybe it indeed makes sense to return empty list like you suggest.

2024-04-18 14:39 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +            return fileRoutesJson.contains("\"title\":\"Layout\"");
There's no such file(s) in production mode to check, or is there, maybe I'm mistaken?

2024-04-18 15:00 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/MenuData.java
> +        this.exclude = exclude;
You can still have Menu annotated route and exclude can be either true/false and it's currently returned to client if accessible. Meaning that Hilla should still check the `exclude` flag. Would it be better to leave it out already in the server side?

2024-04-18 15:00 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +        var populateClientSideMenu = vaadinService.getInstantiator()
done

2024-04-18 15:00 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/auth/MenuAccessControl.java
> +     * populate the menu with server side routes, {@code null} - populate the
done

2024-04-18 15:00 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/auth/DefaultMenuAccessControl.java
> +    public Optional<Boolean> getPopulateClientSideMenu() {
done

2024-04-18 17:30 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +            return fileRoutesJson.contains("\"title\":\"Layout\"");
Do you mean either of the layouts? If there is a layout present at dev time, it should also be there in the same place in production mode as well. If it isn't, it is a bug.

2024-04-18 17:40 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/router/MenuData.java
> +        this.exclude = exclude;
If it should be excluded, no information regarding its existence should leak to the client, since if it does, it is a security issue IMO. 
Regarding the necessity of having `exclude` in `@Menu`, to me it sounds a bit weird to have it at all, since the presence of `@Menu` means it should be in the menu, and if it should not be in the menu, why add the `@Menu` in the first place, and then add an `exclude = true` for excluding it from the menu. Maybe, there is a benefit for having it that I don't know of :)

2024-04-18 17:59 UTC, taefi requested changes
I added my review again, based on my understanding from the enhancement issue, and the usage of the newly introduced API `getRegisteredAccessibleMenuRoutes` in the vaadin/hilla#2338. Please feel free to discard, if my understanding of the issue is not correct.

2024-04-19 06:39 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/MenuData.java
> +        this.exclude = exclude;
I see it's good to have it just for sake of easy way to exclude menu item without removing code but simply toggle a boolean.
I'll change `exclude` so that if it's `false`, server won't even return it.

2024-04-19 06:45 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/di/Instantiator.java
> +     * Get the MenuAccessControl if one has been defined.
The default method implementation always returns an instance.
Is it intended that implementors can return `null`? Otherwise, I would change the Javadoc to remove the `if one has been defined` part.

2024-04-19 06:45 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/di/DefaultInstantiator.java
> +                        MenuAccessControl.class.getSimpleName());
Looking at the implementation, in this case the `MenuAccessControl` feature is disabled, since the method will return `null`.
I wonder if it would be better to throw an exception, since it is definitely a configuration error.
Otherwise, I would expand the log message to explicitly say that `MenuAccessControl` feature will be disabled.

2024-04-19 06:45 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +        final VaadinService vaadinService = VaadinService.getCurrent();
Could it be taken from `VaadinRequest`?
```suggestion
        final VaadinService vaadinService = vaadinRequest.getService();
```

2024-04-19 06:45 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/di/Instantiator.java
> +     * Get the MenuAccessControl if one has been defined.
I couldn't find null checks on the caller side, so probably an instance is always expected

2024-04-19 06:45 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +        if (VaadinService.getCurrentRequest() == null) {
Could use `vaadinRequest` parameter?

2024-04-19 06:45 UTC, mcollovati commented on flow-tests/vaadin-spring-tests/test-spring-security-flow-routepathaccesschecker/src/main/java/com/vaadin/flow/spring/flowsecurity/views/MenuListView.java
> +        String targetAccessibleMenuRoutes = RouteConfiguration.forSessionScope()
nit: could probably get registry from the event: `event.getSource().getRegistry()`

2024-04-19 06:45 UTC, mcollovati commented on flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/MenuListView.java
> +        String targetAccessibleMenuRoutes = RouteConfiguration.forSessionScope()
nit: could probably get registry from the event: `event.getSource().getRegistry()`

2024-04-19 06:45 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java
> +                        .info("The number of beans implementing '{}' is {}. Cannot use Spring beans for I18N, "
```suggestion
                        .info("The number of beans implementing '{}' is {}. Cannot use Spring beans for Menu Access Control, "
```

2024-04-19 07:16 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +            return fileRoutesJson.contains("\"title\":\"Layout\"");
This is runtime check, so none of the views files exist like views.json does. We can probably add a new flag that flow can set when building frontend bundle, and read it then on demand. Or is it possible to add something in views.json by Hilla already that tells if main menu is used?

2024-04-19 07:31 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/MenuData.java
> +        this.exclude = exclude;
Done

2024-04-19 07:32 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +            return getRegisteredRoutes();
Done

2024-04-19 07:32 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +        }
Done

2024-04-19 07:42 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/di/Instantiator.java
> +     * Get the MenuAccessControl if one has been defined.
It would be expected to always return an instance. I'll change the Javadoc.

2024-04-19 07:52 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +            return fileRoutesJson.contains("\"title\":\"Layout\"");
> This is runtime check, so none of the views files exist like views.json does.

I couldn't understand this. If the convention is to have `@layout.tsx` (or `.jsx`) is at the root of `Frontend/views/` directory, what prevents us to check its existence directly here? Similar to what is done for reading the `file-routes.json`, it is possible check the existence of any `@layout.tsx` (or `.jsx`) at the root of `Frontend/views/`.

2024-04-19 08:06 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/router/MenuData.java
> +        this.exclude = exclude;
> I see it's good to have it just for sake of easy way to exclude menu item without removing code but simply toggle a boolean.

First, I thought of the same thing, as for developers it is actually easier to toggle a boolean when experimenting at dev mode. But, with a similar argument, any annotation should have a boolean switch for disabling it, so that the developer don't have to remove it, in case they don't want the functionality. 

Having an `exclude` implies an extra check everywhere in the code that deals with `@Menu`, since simply checking its existence is not enough. IMO, apart from this extra check making Flow codes unnecessarily cluttered, the extra check is also prone to be forgotten here and there.

Anyway, I have no other strong arguments against this. If you see it's helpful, let's keep it :)

2024-04-19 08:36 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +            return fileRoutesJson.contains("\"title\":\"Layout\"");
When we build a jar/war and run it, all the code under the Frontend folder is compiled, obfuscated and we can't read those files the same way as during the build time.
But we do have stats.json file that contains frontendHashes like "views/@layout.tsx", so we can actually check that existence from there instead.

However, other option would be to use some already existing Hilla Spring bean to get this information, and to also move this check to Hilla side as Flow don't know anything about Hilla beans. That would mean that Flow would return all accessible menu routes when in AUTOMATIC mode, and Hilla would use it's own API to check if client menu is used, and either populate the menu or not populate it. What do you think @taefi? Is there such an bean in Hilla to check it, or would it anyway be better to use the stats.json in Flow side as described above?

2024-04-19 08:52 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/di/DefaultInstantiator.java
> +                        MenuAccessControl.class.getSimpleName());
Let's throw an exception of InvalidIMenuAccessControlException type.

2024-04-19 09:47 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +            return fileRoutesJson.contains("\"title\":\"Layout\"");
@tltv That's correct, I misunderstood the "runtime" term earlier, my bad.

According to the structure of the `file-routes.json`, an entry that has:
* an empty `route`, and 
* a non-undefined `children` (either some children, or even [])
are the signs of the main layout entry. 

Currently, we don't have any beans for this, but may be the same interface from Flow `ClientRoutesProvider` could introduce another method to be implemented by Hilla's `ClientRouteRegistry`. Would this work for Flow?

2024-04-19 10:22 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +            return fileRoutesJson.contains("\"title\":\"Layout\"");
That checking/filtering could be done on Hilla side as well. So the acceptance criteria of the issue changed in a way that Flow is not considering the existence of Hilla main-layout anymore, correct?

2024-04-19 11:30 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +            return fileRoutesJson.contains("\"title\":\"Layout\"");
Yes, that's correct. Let me remove this main-layout check from this PR, and move it to the Hilla PR just to have a working prototype, Hilla team can finalize it then.

2024-04-19 15:25 UTC, deniz-frick commented on flow-server/src/main/java/com/vaadin/flow/router/MenuData.java
> +        this.exclude = exclude;
Currently (24.4.0.alpha22) The automatic menu generation is a complete mess.
I agree with @taefi that `exclude` should be implicit but currently, `@Menu` depends on `vaadin.expose-server-routes-to-client=true`. But then every route gets a menu Entry and not only the ones with `@Menu`. So `exclude=true` is needed on all routes that should not show up in the menu.

To me, it is also very important to support [Hierarchies](https://hilla.dev/docs/react/components/side-nav#hierarchy) in the autogenerated menus (regardless of `@Menu` usage).
The annotation needs a way to specify children and the autogeneration should group routes like `/deployments` and `deployments/new` accordingly.


I also want to mention that this behaviour (the application property and the annotation) should definitely be mentioned [here in the typesrypt code](https://github.com/vaadin/hilla/blob/be9a911be3413770a16b1e2af8314434fd7adb8f/packages/ts/file-router/src/runtime/createMenuItems.ts#L14). I spend hours today trying to figure out why my generated react view had a menu entry but my java view had not and was very happy to find this issue so actively worked on :) .

2024-04-22 07:49 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/MenuData.java
> +        this.exclude = exclude;
After this is merged in Flow, and after Hilla is updated to use the new API, you'll not get all server routes from the server anymore but just what are annotated with the Menu and are accessible and not explicitly excluded. 
Hierarchy support for Menu annotation is however not happening in this PR but it could be added later.

2024-04-22 07:54 UTC, Legioth commented on flow-server/src/main/java/com/vaadin/flow/router/MenuData.java
> +        this.exclude = exclude;
Hilla views need an explicit `exclude` configuration because Hilla views are by default shown in the menu. Flow views won't need an explicit `exclude` because `@Route` classes are only included in the menu if they also have `@Menu`. All Hilla views are passed through the stack in order to configure the client-side router and that's why an explicit `exclude` is needed also in the data. Flow views should on the other hand only be in the list that is potentially sent to the client in case they should be visible in the menu - the browser should not have any way of directly knowing about inaccessible server-side views.

Hierarchy support is out of scope for now. The main purpose of this feature is to help new users so that they don't get into a situation where they add a view and nothing happens. We acknowledge that the functionality that is being built right now is not flexible enough for many real-world use cases. Many applications will eventually "graduate" to a point where they remove those ~5 lines of code related to the automatic menu from their main layout file and instead add something specific to their needs.

2024-04-22 08:10 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/MenuData.java
> +        this.exclude = exclude;
There's now more people against having exclude attribute in the Menu, so I'll just remove it as it's more clear that way.

2024-04-22 12:24 UTC, mshabarov submitted a review, later dismissed
Don't know what was a problem last time I tested, but now, in a second try, it works as expected, so once I have a `AtMenu`, menu item appears in the list, once I remove it - it disappears. 

Approved, so we can merge it to main, if no big objections.

2024-04-23 05:42 UTC, mshabarov submitted a review, later dismissed

2024-04-23 05:44 UTC, mshabarov commented
One comment from my side is that this feature misses a way to change the mode via config param, e.g. `vaadin.menu.access.control=ALWAYS`, one can only create a new bean or give a full class name as a value.
I propose to add it later to not block this feature.

2024-04-23 06:23 UTC, mshabarov approved these changes

2024-04-23 06:39 UTC, merged