feat: API for reloading current route target
vaadin/flow pull request #19331
Opened 2024-05-08 10:34 UTC by tepi

Fixes https://github.com/vaadin/flow/issues/19244

Prepares implementation of https://github.com/vaadin/flow/issues/19262

2024-05-08 11:05 UTC, tepi commented
Draft for now - just wanted to see existing tests pass fine with the change. Still needs tests to be added for the refresh functionality.

2024-05-13 08:14 UTC, tepi commented
Something to consider is `@PreserveOnRefresh` routes - what should we do with them? This PR basically bypasses them, so even if explicit reload API is called, the cached instance will still be used. We could recreate those as well if it seems appropriate.

2024-05-14 06:56 UTC, mcollovati commented
> Something to consider is `@PreserveOnRefresh` routes - what should we do with them? This PR basically bypasses them, so even if explicit reload API is called, the cached instance will still be used. We could recreate those as well if it seems appropriate.

My opinion is that the new API should recreate components even if the route is marked with `@PreserveOnRefresh`. The new method performs an action that is different from a normal page reload or navigation, so if a developer is explicitly calling it, I think it would expect route component(s) to be recreated, even if preserve on refresh is in use.

2024-05-14 07:17 UTC, tepi commented
Logic in this PR recreates the whole layout chain, which might not be wanted in all cases. Working on a change to provide means to control this in the API.

2024-05-15 06:19 UTC, mcollovati requested changes

2024-05-15 06:19 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +        if (locationForRefresh != null) {
What about throwing an exception if `locationForRefresh` is null? Or at least logging a debug message so that the developer can understand why nothing happens when the method is called.

2024-05-15 06:19 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
> +                        typesChain.indexOf(elementType) == typesChain.size()
I wonder if `typesChain.indexOf(elementType)` could get a wrong result if the same class is present multiple times in the chain. This is probably something that will never happen, but, to be sure, what about using and old for loop with index?

2024-05-15 06:19 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
> +                chain);
Nice catch :smile:

2024-05-15 06:19 UTC, mcollovati commented on flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RefreshCurrentRouteIT.java
> +}
nit: new line missing
```suggestion
}

```

2024-05-15 06:19 UTC, mcollovati commented on flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
Do you think we can add some unit tests, for faster feedback?

2024-05-15 06:52 UTC, tepi commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +        if (locationForRefresh != null) {
Added logging

2024-05-15 06:52 UTC, tepi commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
> +                        typesChain.indexOf(elementType) == typesChain.size()
Done

2024-05-15 06:54 UTC, tepi commented on flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
Makes sense, will add unit tests

2024-05-15 07:16 UTC, mcollovati requested changes

2024-05-15 07:16 UTC, mcollovati commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RefreshCurrentRouteView.java
> +import com.vaadin.flow.router.PreserveOnRefresh;
unused import
```suggestion
```

2024-05-15 07:16 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/UI.java
> +     * used.
We can probably remove the `@PreserveOnRefresh` note now.
Or (maybe better) make it explicit that components are re-instantiated even if the target route is annotated with `@PreserveOnRefresh`

2024-05-15 07:18 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +     *
See comment about `@PreserveOnRefresh` note on `UI.refreshCurrentRoute` method

2024-05-15 08:35 UTC, tepi commented on flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
> +     *
Fixed

2024-05-15 08:35 UTC, tepi commented on flow-server/src/main/java/com/vaadin/flow/component/UI.java
> +     * used.
Fixed

2024-05-15 08:35 UTC, tepi commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RefreshCurrentRouteView.java
> +import com.vaadin.flow.router.PreserveOnRefresh;
Removed unused import

2024-05-15 08:35 UTC, tepi commented on flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
Unit tests added for `@PreserveOnRefresh` case and "normal" case.

2024-05-15 09:33 UTC, mcollovati commented on flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
Excellent! Thank you!

2024-05-15 09:34 UTC, mcollovati approved these changes

2024-05-15 10:42 UTC, merged

2025-03-24 18:25 UTC, mwcodeslave commented
in case someone looking for the solution:

`UI.getCurrent().refreshCurrentRoute(false); // refresh AppLayout only`