feat: Filter client routes by authentication and role
vaadin/flow pull request #19389
Opened 2024-05-15 11:59 UTC by caalador

Add filtering of menu client
routes by checking authentication
and roles.

2024-05-20 09:46 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/AbstractRouteNotFoundError.java
> +        return MenuRegistry
Is `MenuRegistry#getClientRoutes` and `FrontendUtils#getClientRoutes` same thing now? I see `MenuRegistry` something needed for the Menu only and `FrontendUtil`'s method is needed to get all client routes. 
It shouldn't do any access checking in the error view, it should list all routes for the developer to be aware of them. Just like with server routes.

Therefore deprecating `ClientRoutesProvider` is not necessary as it is meant for different use case. I think we need to keep both and keep using `FrontendUtil.getClientRoutes()` here.

2024-05-20 10:19 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/router/AbstractRouteNotFoundError.java
> +        return MenuRegistry
This is the unfiltered client routes. 
`MenuRegistry.getClientRoutes(true, config)` would give filtered results.

The issue with ClientRoutesProvider is that it is provided by Hilla only and the routes are read and compiled from the same data as MenuRegistry uses.

We were looking at this and no one had any usecase for having the provider specifically.

2024-05-20 11:30 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/AbstractRouteNotFoundError.java
> +        return MenuRegistry
Ah, it's same then. It's collecting fs-routes but not custom client routes then. And If it's same, then `ClientRoutesProvider` becomes jobless. And I'm still not aware of any new use case for that provider other than adding your custom client routes in the picture by implementing the provider. Not so sure if it's enough to keep the provider, maybe not, as you suggest. 

Calling `MenuRegistry#getClientRoutes(false, config)` is just a bit misleading. I wonder if it could be called from the existing `FrontendUtils.getClientRoutes` where `DeploymentConfiguration` is read from the active VaadinSession.

2024-05-20 12:16 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/router/AbstractRouteNotFoundError.java
> +        return MenuRegistry
changed.

2024-05-20 13:12 UTC, tltv requested changes

2024-05-20 13:12 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/menu/MenuRegistry.java
> +     *            {@code true}if inaccessible client routes should be filtered
Add space between `{@code true}` and `if` or change it to be inline with other methods. Could say "true to filter routes by authentication status" like others.

2024-05-20 13:12 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/menu/MenuRegistry.java
> +     *            {@code true} to filter client views by login information
Not inline with all other methods. All should say same message. Either this or the other option.

2024-05-20 13:12 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/internal/ClientRoutesProvider.java
> + *             {@link com.vaadin.flow.server.menu.MenuRegistry#getClientRoutes(boolean, DeploymentConfiguration)}
Should link to `FrontendUtils#getClientRoutes` instead now.

2024-05-21 08:34 UTC, tltv approved these changes

2024-05-21 08:44 UTC, merged