feat: speedup startup time by excluding jars
vaadin/flow pull request #19395
Opened 2024-05-16 08:28 UTC by tltv

Optimize class scanning of VaadinServletContextInitializer by excluding some commonly used jars and add support for vaadin.blocked-jar boolean property in META-INF/VAADIN/package.properties to exclude whole jar content from the class scanner.

Fixes: #19112

2024-05-20 14:10 UTC, mcollovati requested changes

2024-05-20 14:10 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/io/FilterableResourceResolver.java
> +                if (resourcePath != null && DEFAULT_SCAN_NEVER_JAR.stream()
Testing locally, it seems that `resourcePath` is always `null` for JAR entries (e.g. `"URL [jar:file:/home/user/.m2/repository/com/vaadin/open/8.5.0/open-8.5.0.jar!/]").
Some additional considerations:
* if `resourcePath` matches one of the `DEFAULT_SCAN_NEVER_JAR` entries, shouldn't the resource be removed, by returning `true`?
* Wouldn't it make sense to apply the `DEFAULT_SCAN_NEVER_JAR` check only if `resourcePath` is effectively a JAR URL?
* Couldn't the `contains` filter cause a false positive if the `resourcePath` is an absolute path that accidentally contains one of the tokens in the `DEFAULT_SCAN_NEVER_JAR` list (e.g. `/home/michael-jackson-laptop/.m2/repository/my/org/myjar/1.0/myjar-1.0.jar`). Would it be feasible to try to determina the exact JAR file name and check against it (e.g. `jar:file:/home/user/.m2/repository/com/vaadin/open/8.5.0/open-8.5.0.jar!/` -> `open-8.5.0.jar`)

2024-05-20 14:22 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/io/FilterableResourceResolver.java
> +            "/hilla-parser-jvm-", "/hilla-runtime-plugin-").toList();
We can probably add `jooq` and `jooq-` to the list, since JOOQ is a quite popular library.
And also some additional Vaadin transitive dependency, such as directory-watcher, classgraph, jsoup, throw-if-servlet3, ph-css, ph-commons, gentyref

2024-05-21 12:57 UTC, tltv commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/io/FilterableResourceResolver.java
> +            "/hilla-parser-jvm-", "/hilla-runtime-plugin-").toList();
Pattern is checked with `contains` function. Concern with these patterns is that someone may add custom-hilla-engine-core.jar, which may or may not have Vaadin classes. Starting with slash ensures that we don't accidentally exclude too much. Some of the names are less risky than others. Your suggestions seems safe except jsoup, which could be `/jsoup`.

2024-05-21 14:19 UTC, tltv commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/io/FilterableResourceResolver.java
> +                if (resourcePath != null && DEFAULT_SCAN_NEVER_JAR.stream()
Good catch. Yes, I've noticed `.getURI().toPath()` returning null in some cases. it should check also `.getURI().toString()`.

Yes, it should return true instead. How I missed this... well hard-coded jars I tested only manually in one test application. Need to check if this could be verified better with IT too.

Other points are good points too, I'll improve matching to only match with the jar file-name. It's a bit too wide atm. matching with whole path.

2024-05-22 10:18 UTC, tltv commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/io/FilterableResourceResolver.java
> +            "/hilla-parser-jvm-", "/hilla-runtime-plugin-").toList();
matching to jar file name only will simplify this.

2024-05-22 11:55 UTC, tltv commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/io/FilterableResourceResolver.java
> +            "/hilla-parser-jvm-", "/hilla-runtime-plugin-").toList();
I had to take that back. We still need the slash in the beginning e.g. for vaadin-spring-*.jar which caused issues as it was blocked.

2024-05-22 12:05 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/io/FilterableResourceResolver.java
> +            "/hilla-parser-jvm-", "/hilla-runtime-plugin-").toList();
I see

2024-05-22 13:00 UTC, tltv commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/io/FilterableResourceResolver.java
> +                if (resourcePath != null && DEFAULT_SCAN_NEVER_JAR.stream()
Done

2024-05-22 15:45 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/io/FilterableResourceResolver.java
> +                if (DEFAULT_SCAN_NEVER_JAR.stream()
I wonder if we can avoid this check if the resource is not a JAR and continue with the lambda logic.

2024-05-22 15:45 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/io/FilterableResourceResolver.java
> +            "throw-if-servlet3", "ph-css", "ph-commons", "gentyref.",
What's the reason for the patterns ending with `.`? I noticed that `gentyref` and `jsoup` are not excluded at runtime, since the JAR name is like `jsoup-1.17.2.jar`.

There are other libraries that can probably be skipped, based on running the test: `asm`, `asm-`, `jetty-`, `tomcat-`, `classmate`, `reflections`, `jna-`, `jsr305`, `jcip-annotations`, `activation`, `httpcore5`, `httpclient5`.

2024-05-23 07:32 UTC, tltv commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/io/FilterableResourceResolver.java
> +            "throw-if-servlet3", "ph-css", "ph-commons", "gentyref.",
That was my mistake. Version in the filename breaks it so I'll remove it. These short patterns combined with `contains` are not working so reliably and we can't really add those without changing the check to more specific. regex could be a bit too slow here. But basic startsWith, indexOf and substring would be fast.

Changing `contains` to `startsWith`, and splitting pattern by asterix `*` would let us define `jsoup-*.*.*.jar` pattern that would work better with short filenames. Idea is to use `startsWith` and/or `indexOf` for each part in the splitted array in order, doing substring on the way.  `jsoup-*.*.*.jar` pattern would only match something like `jsoup-XX.YY.ZZ.jar` name.

2024-05-23 13:42 UTC, tltv commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/io/FilterableResourceResolver.java
> +            "throw-if-servlet3", "ph-css", "ph-commons", "gentyref.",
done

2024-05-23 14:15 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/io/FilterableResourceResolver.java
> +                : DEFAULT_SCAN_NEVER_JAR;
Couldn't we always initialize `customBlockedJarsList` in `initCustomBlockedJars` (fallback to `DEFAULT_SCAN_NEVER_JAR`) and simply its value here? Or directly use the field instead of the method?

2024-05-23 14:15 UTC, mcollovati commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/io/FilterableResourceResolver.java
> +    private boolean patternMatch(String jarName, String pattern) {
nit: it would be nice to have a unit test for this method

2024-05-24 07:17 UTC, tltv commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/io/FilterableResourceResolver.java
> +                : DEFAULT_SCAN_NEVER_JAR;
Probably good idea to simplify like that.

2024-05-24 07:20 UTC, tltv commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/io/FilterableResourceResolver.java
> +    private boolean patternMatch(String jarName, String pattern) {
I agree. It turned out into more complex so unit test would make sense.

2024-05-24 08:52 UTC, tltv commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/io/FilterableResourceResolver.java
> +    private boolean patternMatch(String jarName, String pattern) {
Done

2024-05-24 11:36 UTC, mcollovati approved these changes
Looks good. Great job @tltv

2024-05-27 06:41 UTC, merged