fix: support route parameters in menu
vaadin/flow pull request #19406
Opened 2024-05-17 12:21 UTC by tltv

Fixes server menu item url for routes with route parameters. Routes with only required parameters are excluded automatically from the menu. Fixes #19392 for 24.5+.

RelatedTo: #19392

2024-05-17 14:50 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +                .filter(route -> route.getMenuData() != null);
why `.filter(route -> !route.getMenuData().isExclude());` was removed? This looks suspicious as this flag should be still check, shouldn't it?

2024-05-20 05:54 UTC, caalador requested changes

2024-05-20 05:54 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +                        .anyMatch(param -> !param.getTemplate().contains("?"));
```suggestion
                && parameters.values().stream().map(ParameterInfo::new).
                        .anyMatch(param -> !param.isOptional() && !param.isVarargs());
```
Wildcard routes should by definition work with no parameters.
Also we should use the ParameterInfo class instead of a magic char.

2024-05-20 07:03 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
> +                .filter(route -> route.getMenuData() != null);
It's excluded here to let user still navigate to the route with correct parameters. If it's excluded here, Hilla will not add this route in the header script, which breaks the navigation. Hilla hides the excluded menu item.

But now I realize that this would not work for server side menu and we may need another method that excludes the menu item anyway. Or just leave the filtering to the "client" like for Hilla.

In summary, no RouteData means no access at all. `excluded=true` means excluding route from the menu, but route is still accessible via browser's address bar/links.

2024-05-20 08:21 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/menu/MenuRegistry.java
> +                    .stream().filter(param -> param.getTemplate().contains("?"))
This should also probably be for both optional and varargs

Perhaps extending `RouteData` with a method that returns route parameters as List<ParameterInfo> which is never null would make checks simpler as then it would only be a isEmpty check instead of also a null check and the template handling would be cleaner.

Another could be to give RouteParameterData the isOptional and isVarargs methods

2024-05-21 03:43 UTC, caalador approved these changes

2024-05-21 08:48 UTC, caalador approved these changes

2024-05-22 10:03 UTC, mshabarov approved these changes

2024-05-22 10:04 UTC, merged