Issues/19447 navigate
vaadin/flow pull request #19462
Opened 2024-05-27 11:26 UTC by caalador

2024-05-27 12:57 UTC, tltv commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
> +                                mountedContainer?.parentNode?.removeChild(mountedContainer);
This looks like it happens a bit too late causing flicker. How about moving `removeChild` calls to the beginning before `onBeforeLeave`, and add it back with `appendChild` in `prevent()` function if it's called.

2024-05-27 12:59 UTC, tltv commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
> -            if (container.onBeforeEnter) {
Why it's necessary to remove `onBeforeEnter` call here? Could cause some tests fail.

2024-05-28 03:47 UTC, caalador commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
> -            if (container.onBeforeEnter) {
That is because at the current version there is a onNavigateEvent (probably from the mouse click? It seems that the click event is still propagated even as the listener is added during the useEffect.) so that this is actually not executed, but the onBeforeEnter on line 185 is executed 2 times. 
As we can only have one onBeforeEnter callback so the later one overrides the first.

2024-05-28 07:24 UTC, mshabarov requested changes

2024-05-28 07:24 UTC, mshabarov commented on flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
> +                            prevent() {
Postpone feature seems a bit broken: if I have a confirmation dialog like this https://vaadin.com/docs/latest/routing/lifecycle#postpone, I see both Flow and Hilla contents when trying navigate outside of Flow view.

<img width="786" alt="Screenshot 2024-05-28 at 9 44 42" src="https://github.com/vaadin/flow/assets/61410877/e904f3ce-656f-4510-b718-585c52855e42">

2024-05-28 09:00 UTC, closed without merging