feat: add alternative translate methods to I18NProvider
vaadin/flow pull request #19461
Opened 2024-05-27 10:58 UTC by tltv

Adds static `I18NProvider#translate` methods for alternative way to get translation. Compares to calling getTranslation via `VaadinService.getCurrent().getInstantiator().getI18NProvider()`. `translate` methods throws IllegalStateException without active VaadinService.

Fixes: #19333

2024-05-27 13:29 UTC, mcollovati requested changes

2024-05-27 13:29 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/i18n/I18NProvider.java
> +        return translate(LocaleUtil.getLocale(LocaleUtil::getI18NProvider), key,
nit: `LocaleUtil.getLocale(LocaleUtil::getI18NProvider)` looks a bit weird because of `LocaleUtil` used for both getting the locale and the potential provider. To reduce boilerplate, couldn't we add a `LocaleUtil.getLocale()` method, that does not require arguments? 

```java
    public static Locale getLocale() {
        return getLocale(LocaleUtil::getI18NProvider);
    }
```

2024-05-27 13:29 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/i18n/I18NProvider.java
> +                        "No I18NProvider found from the VaadinService"))
This error message could be misleading in some cases. For example, if the method is called outside a Vaadin request, the real problem is that the `VaadinService` is not available, rather than the i18n provider not being found. We can maybe provide a specific error or have a generic message telling all potential culprits for the failure.

2024-05-27 13:29 UTC, mcollovati commented on flow-server/src/test/java/com/vaadin/flow/i18n/DefaultInstantiatorI18NTest.java
> +        VaadinService.setCurrent(service);
It would be good to clear the `VaadinService` thread local in an `@After` method, to prevent potential unexpected issues

2024-05-28 07:55 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/i18n/I18NProvider.java
> +                        "No I18NProvider found from the VaadinService"))
It can't be specific due to getI18NProvider is safe to call. If it returns empty Optional, we just know that VaadinService, initializer or I18NProvider is null. Probably message should say so.

2024-05-28 09:09 UTC, mcollovati approved these changes

2024-05-29 07:54 UTC, merged