feat:Improve Binder change detection
vaadin/flow pull request #19488
Opened 2024-05-31 10:09 UTC by onuridrisoglu

## Description

Fixes #19260

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2024-05-31 10:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=19488) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=19488) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=19488) it.</sub>

2024-05-31 10:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=19488) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=19488) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=19488) it.</sub>

2024-06-10 05:28 UTC, tepi commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +    protected void handleFieldValueChange(Binding<BEAN, ?> binding, ValueChangeEvent<?> event) {
Please avoid changing this method signature since it would be a breaking change and require waiting for the next major. Instead, one option could be to deprecate the current one, and if that is used, just skip the new change detection logic and function as before.

2024-06-10 05:28 UTC, tepi commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +		return Objects.equals(bindingInitialValuesMap.get(binding), newValue);
The logic here relies on `equals` of the value type being implemented properly. That is something the Binder has not required before, so it's potentially a breaking change.

2024-06-10 05:30 UTC, tepi commented
@mshabarov This change will introduce a slight change in behavior of Binder change tracking due to requiring `equals` to be implemented properly by value types. As well as reverting the tracked change if the value is reverted, which is not currently done (that is, the binding is considered as changed anyway). Do you think we'll need an enable/disable switch for this new change tracking?

2024-06-10 08:01 UTC, tepi commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +		return Objects.equals(bindingInitialValuesMap.get(binding), newValue);
Also, it migh make more sense to add Binding-level API for overriding the logic for checking if value is reverted. That way if custom logic is needed, one does not need to extend Binder to do it.

2024-06-17 12:09 UTC, knoobie commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +        public BindingBuilder<BEAN, TARGET> withEqualityPredicate(SerializableBiPredicate<Object, Object> equalityPredicate);
Vote 4 default implementation; otherwise this is a breaking change

2024-06-17 15:31 UTC, onuridrisoglu commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +    protected void handleFieldValueChange(Binding<BEAN, ?> binding, ValueChangeEvent<?> event) {
Added the current `handleFieldValueChange` back as deprecated

2024-06-17 15:34 UTC, onuridrisoglu commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +		return Objects.equals(bindingInitialValuesMap.get(binding), newValue);
introduced an equality predicate (I'm open for naming suggestions) that uses `Objects::equals` as default, but it can be overridden in binding-level

2024-06-17 15:41 UTC, onuridrisoglu commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +        public BindingBuilder<BEAN, TARGET> withEqualityPredicate(SerializableBiPredicate<Object, Object> equalityPredicate);
Done

2024-06-25 13:05 UTC, mshabarov requested changes

2024-06-25 13:05 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +    private Map<Binding<BEAN, ?>, Object> bindingInitialValuesMap = new HashMap<>();
What if the initial values would be a class field in the `BindingImpl` instead and have a getter method in `Binding`? Then you can call newly added method `Binding::getInitialValue`.

2024-06-25 13:08 UTC, mshabarov commented
> @mshabarov This change will introduce a slight change in behavior of Binder change tracking due to requiring `equals` to be implemented properly by value types. As well as reverting the tracked change if the value is reverted, which is not currently done (that is, the binding is considered as changed anyway). Do you think we'll need an enable/disable switch for this new change tracking?

I'd propose to set the equality predicate `null` by default (or some other value that marks it not defined), that means the change detection feature is not enabled by default. Then if this predicate is set by `BindingBuilder::withEqualityPredicate`, then this feature is enabled. In this way this would be backwards compatible.

2024-08-07 09:48 UTC, onuridrisoglu commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +        SerializableBiPredicate<Object, Object> getEqualityPredicate();
done

2024-08-07 09:50 UTC, onuridrisoglu commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +    private Map<Binding<BEAN, ?>, Object> bindingInitialValuesMap = new HashMap<>();
I refactored the changes and removed `bindingInitialValuesMap`. Now the initial value is kept in Binding level which is set during readBean.

2024-08-07 09:52 UTC, onuridrisoglu commented
> > @mshabarov This change will introduce a slight change in behavior of Binder change tracking due to requiring `equals` to be implemented properly by value types. As well as reverting the tracked change if the value is reverted, which is not currently done (that is, the binding is considered as changed anyway). Do you think we'll need an enable/disable switch for this new change tracking?
> 
> I'd propose to set the equality predicate `null` by default (or some other value that marks it not defined), that means the change detection feature is not enabled by default. Then if this predicate is set by `BindingBuilder::withEqualityPredicate`, then this feature is enabled. In this way this would be backwards compatible.

I did the changes, however my only concern is now `withEqualityPredicate ` should be called for each binding in order to activate this feature.

2024-08-23 06:10 UTC, mshabarov approved these changes
Looks good to me, but I haven't tested it.

I agree with the concern about having this API only on a binding level, would be good to allow doing the same for the whole form.

2024-08-23 06:20 UTC, mshabarov commented
Just discussed with @tepi, the Binder-level API could be done in a way:
1. Adding a method on Binder's level that enables/disables usage of these predicates on bindings level.
2. Then, if enabled, Binder will use a configured predicate for a binding, if it exists, otherwise it uses `equals` as a fallback. If disabled, nothing is used (default).

2024-08-23 06:21 UTC, mshabarov requested changes
Setting to request changes

2024-08-23 08:14 UTC, tepi commented
> Just discussed with @tepi, the Binder-level API could be done in a way:
> 
>     1. Adding a method on Binder's level that enables/disables usage of these predicates on bindings level.
> 
>     2. Then, if enabled, Binder will use a configured predicate for a binding, if it exists, otherwise it uses `equals` as a fallback. If disabled, nothing is used (default).

@onuridrisoglu fyi, I'll pick this up and do the changes

2024-08-23 08:58 UTC, mshabarov approved these changes

2024-08-23 09:41 UTC, merged