chore: remove splash messages from dev tools
vaadin/flow pull request #19558
Opened 2024-06-11 07:31 UTC by Artur-

2024-07-10 05:25 UTC, mcollovati commented on vaadin-dev-server/src/main/frontend/vaadin-dev-tools.ts
>      document.body.addEventListener('click', this.disableEventListener);
Should these `addEventListener` calls be removed, since the `disableEventListener` initialization has been deleted? Or maybe can `disableEventListener` be completely removed?

2024-07-10 05:31 UTC, mcollovati requested changes

2024-07-10 05:31 UTC, mcollovati commented on vaadin-dev-server/src/main/frontend/vaadin-dev-tools.ts
> +        class="dev-tools}"
typo
```suggestion
        class="dev-tools"
```

2024-07-10 05:32 UTC, mcollovati commented on vaadin-dev-server/src/main/frontend/vaadin-dev-tools.ts
> +        class="dev-tools}"
This is probably the reason for the test failure

2024-09-13 06:54 UTC, mcollovati commented
@Artur- is this PR still relevant?

2024-09-13 06:57 UTC, Artur- commented on vaadin-dev-server/src/main/frontend/vaadin-dev-tools.ts
>      document.body.addEventListener('click', this.disableEventListener);
Removed, seems like `disableEventListener` is no longer used at all

2024-09-13 06:57 UTC, Artur- commented
Yes, although it is mostly code cleanup

2024-09-16 11:35 UTC, merged