Added support to customizable the `projectFileExtensions`.
vaadin/flow pull request #19550
Opened 2024-06-11 01:11 UTC by oliveryasuna

## Description

Please see the issue.

Fixes https://github.com/vaadin/flow/issues/19527

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended. _NOT APPLICABLE?_
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2024-06-18 04:01 UTC, caalador commented
The dev-bundle-plugin also needs to implement the new `projectFileExtensions()` method
```
Error:  /home/runner/work/flow/flow/flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java:[80,8] com.vaadin.flow.plugin.maven.BuildDevBundleMojo is not abstract and does not override abstract method projectFileExtensions() in com.vaadin.flow.plugin.base.PluginAdapterBase
```

Also it feels like the extensions should be an addition to the existing and not replacing the list of extensions.

2024-06-19 13:56 UTC, mcollovati requested changes
A couple of comments:
* I agree with @caalador that the configurable extensions should be added to the default list and should not replace them.
* it would be better to define the default extensions in a single place instead of having duplication in Maven and Gradle plugin. `FrontendUtils` class could be a good host.
* I know that in the Vite configuration file, the constant is named `projectFileExtensions`, but IMO it doesn't sound like a good name for a plugin setting. What about `frontendFileExtensions`? Could it be a better name?

2024-06-19 13:56 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateVite.java
> +                                .map(ext -> "'" + ext + "'")
Since the values potentially come from the outside, it would be good to escape them

2024-06-19 13:56 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateVite.java
> +                                .reduce((a, b) -> a + ", " + b).orElse(""));
nit: a different option is to use the `joining` collector instead of `reduce().orElse`, e.g. `collect(Collectors.joining(", "))`

Up to you to apply the suggestion or leave the original code as is.

2024-06-19 14:53 UTC, oliveryasuna commented
> A couple of comments:
> 
>     * I agree with @caalador that the configurable extensions should be added to the default list and should not replace them.
> 
>     * it would be better to define the default extensions in a single place instead of having duplication in Maven and Gradle plugin. `FrontendUtils` class could be a good host.
> 
>     * I know that in the Vite configuration file, the constant is named `projectFileExtensions`, but IMO it doesn't sound like a good name for a plugin setting. What about `frontendFileExtensions`? Could it be a better name?

I agree with everything and will make changes later. Thanks for considering this!

2024-07-01 09:23 UTC, mcollovati requested changes
The implementation seems broken because of a missing comma in placeholder replacement. 
I also suggest adding a couple of tests in `TaskUpdateViteTest` like the following one

```java
    @Test
    public void generatedTemplate_extraFrontendExtension_addedToViteConfiguration()
            throws IOException {
        options.withExtraProjectFileExtensions(List.of(".svg", ".ico"));
        TaskUpdateVite task = new TaskUpdateVite(options, null);
        task.execute();

        File configFile = new File(temporaryFolder.getRoot(),
                FrontendUtils.VITE_GENERATED_CONFIG);

        String template = IOUtils.toString(configFile.toURI(),
                StandardCharsets.UTF_8);

        Assert.assertTrue(
                "Extra frontend extensions should be added to vite configuration, but was not.",
                template.contains(
                        "const projectFileExtensions = ['.js', '.js.map', '.ts', '.ts.map', '.tsx', '.tsx.map', '.css', '.css.map', '.svg', '.ico'];"));
    }

```

2024-07-01 09:23 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateVite.java
> +                                        + "'";
It looks like to me that `StringEscapeUtils.escapeJava` does not escape single quotes, that is the only replacement that we need (e.g. `ext.replace("'", "\\'")`).

2024-07-01 09:23 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateVite.java
> +                        }).collect(Collectors.joining(", ")));
The result of this string seems not correct; it will be appended to the existing list without a coma.

```
const projectFileExtensions = ['.js', '.js.map', '.ts', '.ts.map', '.tsx', '.tsx.map', '.css', '.css.map''.svg', '.ico'];
```


An option could be the following, for example
```
        String extraExtension = "";
        if (options.getExtraProjectFileExtensions() != null
                && !options.getExtraProjectFileExtensions().isEmpty()) {
            extraExtension = 
                    Optional.ofNullable(options.getExtraProjectFileExtensions())
                            .orElse(Collections.emptyList()).stream()
                            .map(ext -> ext.replace("'", "\\'"))
                            .collect(Collectors.joining("', '", ", '", "'"));
        }
        template = template.replace("#extraProjectFileExtensions#", extraExtension);
```

2024-07-01 09:23 UTC, mcollovati commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
> +    public abstract val extraProjectFileExtensions: ListProperty<String>
I'm still not convinced by the setting name. It still seems too generic to me.
I mean, the purpose is to add extension for **frontend** files that should be considered, not overall project files.
I propose something like `extraFrontendFileExtensions`.

@mshabarov what do you think?

2024-07-01 09:34 UTC, mcollovati reviewed
Additional note: it would probably make sense that configuration setting does not require the extension to start with a dot. I would prefer a configuration like 

```xml
<extraProjectFileExtensions>
   <extraProjectFileExtension>svg</extraProjectFileExtension>
   <extraProjectFileExtension>ico</extraProjectFileExtension>
</extraProjectFileExtensions>
```
rather than 

```xml
<extraProjectFileExtensions>
   <extraProjectFileExtension>.svg</extraProjectFileExtension>
   <extraProjectFileExtension>.ico</extraProjectFileExtension>
</extraProjectFileExtensions>
```

It would be better if the dot would be automatically added at runtime, if not already defined in configuration.

2024-07-01 09:41 UTC, mcollovati requested changes

2024-07-01 09:41 UTC, mcollovati commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
> +     * @return list of project file extensions
We should add a note on the expected extension format here (e.g. no initial dot) with a simple example list.

2024-07-01 09:41 UTC, mcollovati commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
> +    @Parameter(defaultValue = "${null}")
I would add a `property` attribute named for example `frontend.extraFileExtensions` so that it could be specified also on the command line

2024-07-01 09:41 UTC, mcollovati commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
> +    @Parameter(defaultValue = "${null}")
Also, the field needs Javadoc. IIRC they are used for maven goal documentation

2024-07-01 09:41 UTC, mcollovati commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
> +     */
We should add a note on expected extension format and a simple example list.

2024-07-01 09:41 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
> +     *
We need to provide additional detail on the expected extension format and perhaps  a simple example

2024-07-01 09:51 UTC, mcollovati commented
@oliveryasuna let me know if you need help in setting up the tests or if you have any doubts

2024-09-09 11:45 UTC, mcollovati commented
@oliveryasuna are you still interested in/do you have time to complete this PR?
Otherwise, the Flow team can take care of and mention you as a co-author.

2024-09-09 12:12 UTC, oliveryasuna commented
> @oliveryasuna are you still interested in/do you have time to complete this PR? Otherwise, the Flow team can take care of and mention you as a co-author.

Hey @mcollovati, sorry, it is completely fell off my radar. If the flow team could finish it off, that would be great! This will allow us and many to simplify our build process.

2024-11-05 11:35 UTC, caalador commented
Opened new PR with commits from this one. See vaadin/flow#20397

2024-11-11 12:42 UTC, closed without merging