Add CompletableFuture WebStorage API #19743
vaadin/flow pull request #19747
Opened 2024-08-05 14:44 UTC by Dudeplayz

## Description

Adds CompletableFuture methods for `WebStorage.getItem`.

Fixes #19743

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [x] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2024-08-05 14:51 UTC, Dudeplayz commented
Questions:
- The callback style methods could also use the CompletableFuture one and be called with then?
- CompletableFuture would return an exception in error cases instead of null, how is the behavior intended here?

2024-08-06 05:27 UTC, mcollovati commented
> The callback style methods could also use the CompletableFuture one and be called with then?

I would leave the callback method as is. I think there's no need to create a `CompletableFuture` there.

> CompletableFuture would return an exception in error cases instead of null, how is the behavior intended here?

My opinion is that the `CompletableFuture` version should behave in the same way as the `Callback` one. So, probably the returned `CompletableFuture` should have an `exceptionally(...)` stage that returns null (and maybe logging the error at DEBUG level). It would also be good to mention the behavior on the Javadoc.

2024-08-07 06:04 UTC, mcollovati requested changes

2024-08-07 06:04 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/page/WebStorage.java
> +     *         value was not set
I would use `available` as in the `Callback` javadoc
```suggestion
     *         value was not available.
```

2024-08-07 06:04 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/page/WebStorage.java
> +     *         value was not set
```suggestion
     *         value was not available.
```

2024-08-07 06:04 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/component/page/WebStorage.java
> +     *         value was not set
```suggestion
     *         value was not available.
```

2024-08-07 08:37 UTC, mcollovati approved these changes

2024-08-07 11:50 UTC, merged