feat: Binder record support
vaadin/flow pull request #19806
Opened 2024-08-20 12:39 UTC by tepi

Adds record support for Binder.

https://github.com/vaadin/flow/issues/17947

2024-08-20 12:42 UTC, tepi commented
Comments on how to handle https://github.com/vaadin/flow/pull/19806/files#diff-efd43ee1358647ace8a6ce941aedf4a463aa0db586a75a38fb4c5e4e07b254fbR2577-R2584 are welcome!

2024-08-20 13:30 UTC, knoobie commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +                        .newInstance(convertedValues.toArray()));
This looks really dangerous... can you guarantee that you have the correct order? This requires the binding of fields to be in order of the constructor.. one slight change to the constructor.. everything breaks at runtime :( 

I don't think there is any sensible way for you to always match the correct fields.. except with reflection and such.. so I would probably go away from "magic" and add `Function<Map<FIeld, Object>, BEAN>` that the user has to supply.

2024-08-20 14:15 UTC, tepi commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +                        .newInstance(convertedValues.toArray()));
Good catch! Yeah, this assumes binding order to be same as in record constructor. Luckily there already seems to be a property name to binding mapping in `boundProperties` field.

2024-08-20 14:19 UTC, tepi commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +                        .newInstance(convertedValues.toArray()));
Another slightly related issue I just realized: what to do if the developer does not bind all properties?

2024-08-20 14:45 UTC, knoobie commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +                        .newInstance(convertedValues.toArray()));
Looks like you opened Pandora's box 😬

2024-08-20 14:47 UTC, tepi commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +                        .newInstance(convertedValues.toArray()));
I think for now it's ok to require binding of all properties for records. Otherwise there would have to be some default value provider or such.

2024-08-22 11:32 UTC, mshabarov requested changes
Minor comments, but overall looks good to me.

Tested basic functionality for write/read records, hasChanges, validation and conversion, works as expected.

2024-08-22 11:45 UTC, tepi commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +     *             if record instantiation fails for any reason
IllegalArgumentException was stolen from existing class ReflectTools where it is thrown when instantiation of a certain class fails. I'll consider alternatives

2024-08-22 11:46 UTC, tepi commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +    public BEAN writeRecord() throws ValidationException {
Good point! The bean methods now throw IllegalStateException if used with record type, so I'll use that here as well

2024-08-22 12:15 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +     *             if record instantiation fails for any reason
I see, thanks. From a API user perspective, I think this is a bit confusing to get illegal state exception when having instantiation problems. But if this util method was designed for such a cases, let's keep it.

2024-08-22 14:35 UTC, tepi commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +    public BEAN writeRecord() throws ValidationException {
Added. Also added mentions of the exceptions to relevant javadoc parts.

2024-08-22 14:37 UTC, tepi commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +     *             if record instantiation fails for any reason
I left this as is, since it's already in use in the framework. Also, there's no suitable RuntimeException variant in Java. And I don't see a point of introducing our own exception type that just wraps a bunch of random checked exceptions.

2024-08-23 05:46 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
> +     *             if record instantiation fails for any reason
Yes, makes sense.

2024-08-23 05:47 UTC, mshabarov approved these changes

2024-08-23 05:47 UTC, merged