fix: Validate layout values
vaadin/flow pull request #19873
Opened 2024-09-03 07:37 UTC by caalador

Check Layout annotations
for duplicate values.
If found throw exception.

Fixes #19872

2024-09-03 12:14 UTC, tepi commented
LGTM otherwise, but should the duplicates-not-allowed also be mentioned in `Layout` javadoc? At least I could not see it there.

2024-09-03 14:31 UTC, mcollovati requested changes

2024-09-03 14:31 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
> +                });
nit: can this part be simplified as  `layoutsMap.computeIfAbsent(layoutValue, k -> new ArrayList<>()).add(routeClass);`?

2024-09-03 14:31 UTC, mcollovati commented on flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
> +                .append(AnotherAnnotatedParentLayout.class.getName());
I've got this test failing randomly because of the order of the classes in the error message is not predictable, most likely because of `HashSet`s are used in `RouteRegistryInitializer`

2024-09-03 14:31 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
> +                                .collect(Collectors.joining(" - ")));
nit: a newline could make the message more readable
```suggestion
                                .collect(Collectors.joining("\n - ")));
```

2024-09-04 04:05 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
> +                                .collect(Collectors.joining(" - ")));
This would perhaps work if you expected there to never be more than one pair or one conflicting layout.
When there is multiple I was thinking they should all be on one line so for 2 different conflicting layouts now would give:
```
 - Class1 - Class2 - Class5
 - Class3 - Class4
 ```
Where as with a new line it would become:
``` 
 - Class 1
 - Class 2
 - Class 5
 - Class 3
 - Class 4
```
Perhaps having something noting the different conflicting sets...

2024-09-04 04:06 UTC, caalador commented
> LGTM otherwise, but should the duplicates-not-allowed also be mentioned in `Layout` javadoc? At least I could not see it there.

Yes should be noted in the documentation. Basically you can have duplicates but only one will be then used which would lead to confusion on the layout chosen.

2024-09-04 05:11 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
> +                                .collect(Collectors.joining(" - ")));
Got it. Definitely single line makes more sense

2024-09-04 05:17 UTC, mcollovati approved these changes

2024-09-04 06:11 UTC, merged