fix: prevent Flow navigation for Hilla route
vaadin/flow pull request #19875
Opened 2024-09-03 07:42 UTC by tepi

Tentative fix for https://github.com/vaadin/flow/issues/19831

Prevents Flow navigation actions for cases where a client route exists and is navigated to, but there is also a Flow route with a parameter that could potentially match the target URL.

Need test(s) and some javadoc

2024-09-04 06:22 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/menu/MenuRegistry.java
> +            if (configuration.getFrontendFolder() != null) {
How frontend folder can be null ? Which scenario does this cover ?

2024-09-04 06:27 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/menu/MenuRegistry.java
> +            if (configuration.getFrontendFolder() != null) {
The return value is implicitly not null and all the caller codes in Flow rely on it to be not null. I propose to mock it in the test.

Otherwise the PR looks good to me.

2024-09-04 06:49 UTC, tepi commented on flow-server/src/main/java/com/vaadin/flow/server/menu/MenuRegistry.java
> +            if (configuration.getFrontendFolder() != null) {
Fixed

2024-09-04 06:50 UTC, mshabarov approved these changes

2024-09-04 07:04 UTC, mshabarov requested changes
You need to free the static mocks (e.g. use try-with-resources) for MockStatic, when mocking MenuRegistry.

Without it, we get:

```
Error:  Errors: 
Error:    JavaScriptBootstrapUITest.should_update_pushState_when_navigationHasBeenAlreadyStarted:441 Mockito 
For com.vaadin.flow.server.menu.MenuRegistry, static mocking is already registered in the current thread

To create a new mock, the existing static mock registration must be deregistered
```

2024-09-04 07:10 UTC, mshabarov approved these changes

2024-09-04 07:54 UTC, tepi commented on flow-server/src/main/java/com/vaadin/flow/server/menu/MenuRegistry.java
> +    public static boolean hasClientRoute(String route, boolean excludeLayouts) {
I found no way of testing this since it's a static method that calls other static methods, meaning I would have to mockstatic them all, which at the end does not test anything really. Most of the logic is from the original `hasClientRoute` method which had no unit tests either, probably because of the same reason.

2024-09-04 07:56 UTC, merged

2024-09-04 10:02 UTC, tepi commented
Seems there was no `MenuRegistry` class in 24.4 so CP is not possible.

2024-09-05 11:02 UTC, caalador commented
Also I guess the issue in https://github.com/vaadin/start/issues/3169 is also from this as the "" client route which comes from the `@layout.tsx` (this should be a layout not a route, but as there are not children)  is now seen as a actual client route which cancels the navigation in flow.

2026-10-09 08:39 UTC, mcollovati commented
No backport to 24.4 is needed: this fixes a bug from a 24.5 pre-release (#19831), and the fix uses `MenuRegistry`, which 24.4 does not have.