fix: Propagate Premium Features flag value to configuration
vaadin/flow pull request #19935
Opened 2024-09-11 11:23 UTC by mshabarov

## Description

This adds missing codes into app configuration factory that propagates the PREMIUM_FEATURES flag value from token file to app config. This value can be retrieved from deployment configuration in runtime.

Related-to https://github.com/vaadin/flow/pull/19846

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2024-09-11 12:54 UTC, tltv requested changes

2024-09-11 12:54 UTC, tltv commented on flow-server/src/test/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactoryTest.java
> +    public void create_tokenFileWithPremiumFlag_premiumFlagIsPropagatedToDeploymentConfiguration()
Is this test adding anything that other tests here don't already test? This seems to just test same thing with different constant.

2024-09-11 12:54 UTC, tltv commented on flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
> +import com.vaadin.flow.internal.StringUtil;
```suggestion
```

2024-09-11 12:59 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactoryTest.java
> +    public void create_tokenFileWithPremiumFlag_premiumFlagIsPropagatedToDeploymentConfiguration()
Apparently not, because no test was failing before, though this property wasn't populated :) 

Seems we don't have tests that checks that all possible properties are propagated from token file to config. I'll try to do such a test.

2024-09-11 13:18 UTC, tltv commented on flow-server/src/test/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactoryTest.java
> +    public void create_tokenFileWithPremiumFlag_premiumFlagIsPropagatedToDeploymentConfiguration()
It's a good idea to add such a test. But it will not help with new properties, unless there is for example a list of properties that has to be updated for new properties. It could be in Constants for example.

2024-09-12 06:25 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactoryTest.java
> +    public void create_tokenFileWithPremiumFlag_premiumFlagIsPropagatedToDeploymentConfiguration()
This is problematic, as `AbstractConfigurationFactory` uses a subset of properties that are declared in `Constants` and `InitParameters`, thus, we need to refactor the properties names to group them accordingly, e.g. in separate classes or by marking with comments, if it works. Looks like a bigger work, than just to write one test.

2024-09-12 06:26 UTC, merged