AddWatcher and RemoveWatcher is added to DevTools
vaadin/flow pull request #20054
Opened 2024-09-25 12:19 UTC by abdullahtellioglu

## Description

Sync file watcher should be closed on context shut down so adding watchers to dev tools logical since it handles that 

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [X] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2024-09-25 15:30 UTC, Artur- requested changes

2024-09-25 15:30 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/internal/DevModeHandlerManager.java
> +     * Adds watcher to watcher list.
This javadoc should answer

"Which watcher list?" 
"What happens if I add a watcher to the watcher list?"
"Why would I want to add a watcher to the watcher list?"

Is it even relevant that these are watchers or just resources that will be closed on shutdown? In other words, should it rather be
```
/**
* Registers a command that will be run then the servlet context is shut down. 
*
* @param command the command to run
*/
registerShutdownCommand(Command command)
```

2024-09-25 15:30 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/internal/DevModeHandlerManager.java
> +    /**
If the above is `reigsterShutdownCommand` then this method becomes unnecessary as you would do any checks inside the command instead of removing the command

2024-09-25 15:30 UTC, Artur- commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerManagerImpl.java
> +        this.watchers.add(closeable);
Probably we should update the internal calls to also use this method instead of using `this.watchers` directly

2024-09-25 15:49 UTC, abdullahtellioglu commented on flow-server/src/main/java/com/vaadin/flow/internal/DevModeHandlerManager.java
> +     * Adds watcher to watcher list.
`Command` is not closable,  should it be `Closable`?

2024-09-25 15:57 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/internal/DevModeHandlerManager.java
> +     * Adds watcher to watcher list.
If it is `Command` then it is not something dev mode handler manager closes at shutdown but it is commands it runs at shutdown. The command can close something if it wants to

2024-09-25 18:11 UTC, abdullahtellioglu commented on flow-server/src/main/java/com/vaadin/flow/internal/DevModeHandlerManager.java
> +     * Adds watcher to watcher list.
Updated 👍. I created an internal method to register watchers, and external shutdown commands using `Command` interface as you mentioned.

2024-09-25 18:11 UTC, abdullahtellioglu commented on flow-server/src/main/java/com/vaadin/flow/internal/DevModeHandlerManager.java
> +    /**
Updated 👍

2024-09-25 18:12 UTC, abdullahtellioglu commented on vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerManagerImpl.java
> +        this.watchers.add(closeable);
`registerWatcherShutdownCommand` is created for registering internal Closeables.

2024-09-27 08:49 UTC, mcollovati approved these changes
Only a comment about Javadoc, but not a blocker.

2024-09-27 08:49 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/internal/DevModeHandlerManager.java
> +     * down.
nit: I would remove the `servlet context` part. It could just say the commands run when the `DevModeHandler` is stopped.

2024-09-27 08:49 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/internal/DevModeHandlerManager.java
> +     * down.
BTW, also `initDevModeHandler` method Javadoc mentions servlet context. Probably a leftover, since it takes a generic `VaadinContext`.

2024-09-27 11:23 UTC, abdullahtellioglu commented on flow-server/src/main/java/com/vaadin/flow/internal/DevModeHandlerManager.java
> +     * down.
Updated javadoc 👍

2024-09-27 12:35 UTC, merged