Fix for issue #20092
vaadin/flow pull request #20103
Opened 2024-10-01 22:54 UTC by archiecobbs

## Description

Fix for #20092: `VaadinSessionScope`s for all sessions are destroyed when any single session expires.

* Add new method `VaadinSession.addSessionDestroyListener()` for when you just want one destroy notificatios for a single session, instead of geting notifications for all sessions via `VaadinService.addSessionDestroyListener()`.

* Refactor the Spring scopes to take advantage of the new method to fix an inefficiency.

* Mark `SpringVaadinSession`, which is now empty and useless, for deprecation.

Fixes #20092 (see further discussion there)

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2024-10-03 06:03 UTC, mshabarov commented
@archiecobbs thank you for the contribution!

2024-10-08 08:29 UTC, caalador commented
Seems good apart from the formatting. 
Could you run `mvn formatter:format -pl flow-server,vaadin-spring` and push the formatted sources.

2024-10-08 16:34 UTC, archiecobbs commented
> Could you run `mvn formatter:format -pl flow-server,vaadin-spring` and push the formatted sources.

Done in 7f8ab58271. Thanks.

2024-10-09 05:29 UTC, caalador approved these changes

2024-10-09 06:00 UTC, tepi approved these changes

2024-10-09 06:24 UTC, tepi commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinSession.java
> -
Could you please deprecate these methods instead of removing them? They are public API so could not be removed until a major version. The vaadin-spring module was missing from the api-diff check so this did not stand out earlier.

2024-10-09 06:25 UTC, tepi requested changes
Please see comment about `SpringVaadinSession`

2024-10-09 13:50 UTC, archiecobbs commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinSession.java
> -
> Could you please deprecate these methods instead of removing them? 

Oops, sorry about that - thanks. Should be fixed in d518484fd7.

2024-10-09 13:51 UTC, archiecobbs commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinSession.java
> -
Oops, hang on, I still need to figure out how to deal with `fireSessionDestroy()`...

2024-10-09 14:09 UTC, tepi approved these changes

2024-10-09 15:15 UTC, caalador approved these changes

2024-10-09 15:18 UTC, merged

2024-10-09 15:23 UTC, archiecobbs commented
Thanks!