feat: Add support for customizable projectFileExtensions
vaadin/flow pull request #20397
Opened 2024-11-04 12:31 UTC by caalador

Fixes #19527

2024-11-05 12:37 UTC, tltv requested changes
Should also gradle plugin's `PrepareFrontendInputProperties.kt` be updated for the new property?
Also `GenerateNpmBOMMojo` maven goal could need to use this new property.

2024-11-05 12:37 UTC, tltv commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
>              "cleanFrontendFiles=${cleanFrontendFiles.get()}" +
Missing comma

2024-11-05 12:37 UTC, tltv commented on flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
> +    public static final String FRONTEND_EXTRA_EXTENSIONS = "frontendExtraFileExtensions";
What's the correct naming pattern here, is it like this or "frontend.extra.file.extensions"? We probably should keep them more consistent. I added just new property in other PR with dot format based on majority of properties in InitParameters class.. But if camel case is more correct today, then the other PR should be changed.

2024-11-06 06:55 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateVite.java
> +                "=== '" + options.getFrontendExtraFileExtensions() + "'");
```suggestion
        System.out.println(
                "=== '" + options.getFrontendExtraFileExtensions() + "'");
```

2024-11-06 06:55 UTC, mcollovati commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
> +     * bundle should be generated.
Is it only for prod bundle or also for dev bundle?

2024-11-06 06:55 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateVite.java
> +                    .map(ext -> ext.startsWith(".") ? ext : "." + ext)
Does it make sense to also trim values?
For example, I can imagine configurations like 
`<frontendExtraFileExtensions>.ico, .png</frontendExtraFileExtensions>`

2024-11-06 07:21 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateVite.java
> +                "=== '" + options.getFrontendExtraFileExtensions() + "'");
I forgot to push the removal =P

2024-11-06 07:21 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateVite.java
> +                    .map(ext -> ext.startsWith(".") ? ext : "." + ext)
added trim

2024-11-06 07:21 UTC, caalador commented on flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
> +     * bundle should be generated.
both. Changed to only say new bundle

2024-11-07 04:57 UTC, caalador commented
Added input property for the gradle plugin.

2024-11-07 13:07 UTC, tltv approved these changes
LGTM. After conflicts are resolved.

2024-11-08 09:07 UTC, tltv approved these changes

2024-11-11 12:41 UTC, merged