Fix: move blocking calls outside session lock (#19938)
vaadin/flow pull request #20475
Opened 2024-11-14 14:16 UTC by tepi

2024-11-15 11:52 UTC, mcollovati requested changes

2024-11-15 11:52 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/SynchronizedRequestHandler.java
> +     * should be called.
I would make "Gets if request body should be read before calling synchronizedHandleRequest." as initial documentation, to make immediately clear the effect of the flag.

```suggestion
     * Gets if request body should be read before calling synchronizedHandleRequest.
     *<p></p>
     * Returns {@literal true} if
     * {@link #synchronizedHandleRequest(VaadinSession, VaadinRequest, VaadinResponse, String)}
     * should be called. Returns {@literal false} if
     * {@link #synchronizedHandleRequest(VaadinSession, VaadinRequest, VaadinResponse)}
     * should be called.
```

2024-11-15 11:52 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/SynchronizedRequestHandler.java
> +    public interface ResponseWriter extends Serializable {
This public API needs Javadoc

2024-11-15 11:52 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/SynchronizedRequestHandler.java
> +     * response requestBody has been read before locking the session and is
Could the following be simpler to undertand?
`expect the request body is read before locking the VaadinSession and calling this method.`

2024-11-15 11:52 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/SynchronizedRequestHandler.java
> +     * to unlock the session before writing to the response object.
> Implementations should also take care to unlock the session before writing to the response object.

Could be removed since lock is handled internally.

2024-11-15 11:52 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/SynchronizedRequestHandler.java
> +     *         {@link Optional} is returned.
This sound a bit unclear to me. Would it make sense something like

`@return a ReponseWriter wrapped into an Optional, if this handler will write the response and no further request handlers should be called, otherwise an empty Optional.`

And maybe add to the Javadoc that the ResponseWriter will be executed after VaadinSession is unlocked.

2024-11-15 11:52 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
> +        return responseWriter.isPresent();
Why is needed to override this `synchronizedHandleRequest(...)` method? Isn't this logic already applied in `SynchronizedRequestHandler` if `isReadRequestBodyFirstEnabled()` is true?

2024-11-15 11:52 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/SynchronizedRequestHandler.java
> +                return responseWriter.isPresent();
It looks like we bind the response write stuff with the `isReadRequestBodyFirstEnabled`.
But I wonder if handlers that do no need the request body could benefit from the session unlock before response write feature.
Actually, it should be the default behavior. But unfortunately, this cannot be done without changing the API or providing a `VaadinResponse` wrapper that postpones the actual writing

2024-11-15 13:13 UTC, tepi commented on flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
> +        return responseWriter.isPresent();
Well that comes from `RequestHandler` interface so I must implement something. Would it be better to just throw `UnsupportedOperationException` since this should never be called for this handler?

2024-11-15 13:21 UTC, tepi commented on flow-server/src/main/java/com/vaadin/flow/server/SynchronizedRequestHandler.java
> +                return responseWriter.isPresent();
I think the deadlock issues are all in `UidlRequestHandler`. If some other handlers start to show this issue, we can use the same API to fix them (even if they don't need the request body). Just override `isReadRequestBodyFirstEnabled` to return true and then return a `ResponseWriter`. The request body might be empty but that should not matter.

2024-11-15 13:31 UTC, tepi commented on flow-server/src/main/java/com/vaadin/flow/server/SynchronizedRequestHandler.java
> +                return responseWriter.isPresent();
Or maybe `isReadRequestBodyFirstEnabled` should be called `readAndWriteOutsideSessionLock` or something more general?

2024-11-18 09:05 UTC, mcollovati requested changes

2024-11-18 09:05 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/SynchronizedRequestHandler.java
> +                return responseWriter.isPresent();
I would make the assumption that reading the body beforehand is directly related to writing the response without lock. So, if we do not want two separate flags (unnecessary complexity?)  I'd prefer the `readAndWriteOutsideSessionLock` name that makes the behavior clear.

2024-11-18 09:05 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/server/SynchronizedRequestHandler.java
> +                return responseWriter.isPresent();
And additional though about writing after the lock is released. Is there any chance that unlocking the session causes PUSH to send a message that will reach the client before the current response is committed (e.g. when transport is web socket)?
Probably this situation is handled by the Flow client, putting the unexpected message on hold until the previous one is received, but maybe better double check.

2024-11-18 12:14 UTC, tepi commented on flow-server/src/main/java/com/vaadin/flow/server/SynchronizedRequestHandler.java
> +                return responseWriter.isPresent();
Changed the name. I'll need to check the PUSH case still. Initial guess is it is handled properly since I think some IT should have exploded if it is not.

2024-11-19 07:44 UTC, tepi commented on flow-server/src/main/java/com/vaadin/flow/server/SynchronizedRequestHandler.java
> +                return responseWriter.isPresent();
I ran some manual tests for the push case and it seems to work fine. Whatever is queued for push is sent within the same message as the final response that is written.

2024-11-19 08:50 UTC, mcollovati approved these changes

2024-11-19 09:11 UTC, merged