(feat) Maven plugin improvements
vaadin/flow pull request #20695
Opened 2024-12-13 12:07 UTC by AB-xdev

aka a (bit early) Christmas present from XDEV to Vaadin 🎄

## Description

This PR reworks the Vaadin Maven Plugin to improve performance.
The changes primarily target the ``prepare-`` and ``build-frontend`` goals (all other goals are irrelevant for us) and are based on some experimental changes we have done in internal projects.

Fixes #19596
Fixes #20359

Overview of the changes:
* A core problem of the plugin has always been that it scans/loads all classes of the entire project. This might be ok for a small Vaadin starter but if you have a big project with a few hundred dependencies this takes forever.<br/>If you combine this situation with frequent (re)builds due to e.g. not a good working IDEs, this results in further problems like increased coffee consumption in between builds.<br/>The improvement here is to only scan Vaadin dependencies by default.<br/>The user can further customize and include/exclude certain dependencies if they want.
* A lot of additional optimizations have been introduced, that enable the user to disable additional checks which might not be required.
* Made dependency onto ``org.codehaus.plexus.build.BuildContext`` optional (not everyone uses Eclipse ;) )
* Most things in the plugin can now be replaced/overridden if required

<details><summary>Example configuration</summary>

```xml
<configuration>
	
	<reactEnable>false</reactEnable>
	
	<frontendIgnoreVersionChecks>true</frontendIgnoreVersionChecks>
	
	<hillaAvailable>false</hillaAvailable>
	
	<checkPluginFlowCompatibility>false</checkPluginFlowCompatibility>
	
	<supportDAU>false</supportDAU>
	<fastReflectorIsolation>
		<includeFromTargetDirectory>false</includeFromTargetDirectory>
		<includes>
			<additional>
				<selector>
					<groupId>...</groupId>
					<artifactId>web...*</artifactId>
				</selector>
				
				<selector>
					<groupId>...</groupId>
					<artifactId>logger-...</artifactId>
					<scan>false</scan>
				</selector>
			</additional>
		</includes>
	</fastReflectorIsolation>
	
	
	<performLicenseCheck>false</performLicenseCheck>
	
	<checkRuntimeDependency>false</checkRuntimeDependency>
</configuration>
```

</details>

In a example project (with ~40k LoC and ~150 dependencies) with above configuration we now have the following times:
| | ``prepare-frontend`` | ``build-frontend`` |
| --- | --- | --- |
| Vaadin Default | ~1600ms | ~5100ms |
| with improvements (this PR) | ~900ms (~75% faster) | ~2000ms (~250% faster) |

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.<br/>
_Fixed existing tests so that they work. Feel free to add more tests if you like._
- [x] New and existing tests are passing locally with my change.<br/>
_There seem to be some tests that don't work locally, e.g.:
``[main] ERROR com.vaadin.flow.server.frontend.FrontendToolsLocator - Failed to execute the command '[C:\Program Files\maven\apache-maven-3.9.8\bin\mvn, -v]'
java.io.IOException: Cannot run program "C:\Program Files\maven\apache-maven-3.9.8\bin\mvn": CreateProcess error=193, %1 ist keine zulässige Win32-Anwendung`` or ``DefaultInstantiatorI18NTest.translationFileOnClasspath_instantiateDefaultI18N:122 expected:<[Default lang]> but was:<[deutsch]>``_
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

PS:
* If you see Matti, please give him our best regards
* Would be great if the Formatter & Co is checked into the IntelliJ IDE settings (yes that's possible - have a look at [our repos](https://github.com/xdev-software/java-template/tree/master/.idea)) so you/I don't have to set it up manually or correct it constantly ;)

2024-12-13 12:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=20695) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=20695) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=20695) it.</sub>

2024-12-13 12:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=20695) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=20695) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=20695) it.</sub>

2024-12-13 15:18 UTC, mstahv commented
Awesome @AB-xdev 👏 Does this also fix performance regressions in the development mode 🤔

2024-12-16 07:33 UTC, AB-xdev commented
> Awesome @AB-xdev 👏 Does this also fix performance regressions in the development mode 🤔

@mstahv We only changed the Maven Plugin and nothing noteworthy of the ``flow-server`` or similar.
If you use the plugin during "development mode" to e.g. re-generate the bundle then maybe yes (I'm not quite sure what you guys count to "development mode" and what not).

2024-12-20 09:02 UTC, mcollovati commented
@AB-xdev thank you so much for the contribution. The PR contains many changes, so it will take some time to review it.

A couple of questions and notes:

* what's the reason to make all fields protected?
* why remove the `logTroubleshootingHints` method?
* the original solution included only a subset of provided dependencies; however, with this change, the filter is gone. I need to check the reasons behind the filter and see if they are still valid.
* all public classes and methods required Javadoc

2024-12-20 14:42 UTC, mcollovati requested changes
I did a first review round and added some comments.
I still need to test the changes locally because I currently see several test failures.
I'll continue the review as soon as I get the validation pass locally.

2024-12-20 14:42 UTC, mcollovati commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/Reflector.java
I wonder if we need this interface. I do not expect custom implementations to be provided.
Do you have any good use cases that would need a custom implementation?

2024-12-20 14:42 UTC, mcollovati commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/ReflectorController.java
As for `Reflector`, I wonder if an interface is needed. Wouldn't the default implementation be enough?

2024-12-20 14:42 UTC, mcollovati commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/ReflectorController.java
> +    Reflector of(MavenProject project, MojoExecution mojoExecution);
Javadoc is missing. Also, could we have a better method name?
I would approve `of` if the return type would be `ReflectorController`, but the method instead returns a `Reflector`. Something like `newReflector`, `createReflector` or `buildReflector`.

2024-12-20 14:42 UTC, mcollovati commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/ReflectorController.java
> +public interface ReflectorController {
nit: I wonder if we could come up with a better name. None of the methods make me think of this class as a **controller**. It looks like to me some sort of **provider**. Its responsibility seems to be to provide a new or adapted Reflector instance.

2024-12-20 14:42 UTC, mcollovati commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/ReflectorIsolatedClassLoader.java
Can you explain the reason for introducing this abstract class?

2024-12-20 14:42 UTC, mcollovati commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/Fragment.java
This class seems unused, but being public, we cannot remove it. We have to deprecate it so that removal can happen in the next major.

2024-12-23 09:46 UTC, mcollovati commented
I #20776, rebased on main, to test the changes.
After a first run, it looks like that the change is potentially breaking existing projects, most likely because it filters out too many dependencies by default.

> Error:  Failed to execute goal com.vaadin:flow-maven-plugin:999.99-SNAPSHOT:prepare-frontend (default) on project test-prod-bundle: Execution default of goal com.vaadin:flow-maven-plugin:999.99-SNAPSHOT:prepare-frontend failed: A required class was missing while executing com.vaadin:flow-maven-plugin:999.99-SNAPSHOT:prepare-frontend: org/codehaus/plexus/build/BuildContext


I'll continue the investigation, pushing changes on the linked PR.

2024-12-23 10:19 UTC, mcollovati commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/DefaultReflectorController.java
> +                && "target".equals(artifact.getFile().getParentFile().getName())) {
Output directory can be configured in maven build, so it would be better to avoid hard-coding "target" and get the value from the Maven project.

2024-12-23 11:26 UTC, mcollovati commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
> +import org.codehaus.plexus.build.BuildContext;
This seems to be a wrong import. In `FlowModeAbstractMojo` it was `org.codehaus.plexus.build.BuildContext`

2024-12-23 15:34 UTC, mcollovati commented
Also note that Hilla plugin recently removed the need for executing `configure` goal (vaadin/hilla#2616). That change should also improve the overall performance of `vaadin-maven-plugin`.

2025-01-13 12:27 UTC, AB-xdev commented
Wow, that's a lot of comments. I will try to answer them all.

> what's the reason to make all fields protected?

So it's possible that one can override them without getting having to use reflection or copying code ^^
This also includes methods, classes, etc.

> why remove the logTroubleshootingHints method?

1. The problems are reported [directly by ``DefaultReflectorController``](https://github.com/vaadin/flow/blob/43183dac03f5468d5c0a6eafc20558f7ca2dfc62/flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/DefaultReflectorController.java#L167-L184) this way there is no need to store them as a variable
2. The other messages ("The build process encountered an error: .." and "To diagnose the issue, please re-run Maven with the -X ...") are nearly the same as Maven itself reports when the build fails. There is no need to duplicate them.

> what's the benefit of the supportDAU flag? Is it only to skip the application identifier hashing?

Correct

> the original solution included only a subset of provided dependencies; however, with this change, the filter is gone. I need to check the reasons behind the filter and see if they are still valid.

Yes, the original only contained  ``portlet-api`` and ``javax.servlet-api``.
I removed it because 
* the code looked [very ancient](https://github.com/vaadin/flow/commit/015d6664d5278d406dacec3eb772bd43956cf4f5#diff-04a23c32a5945d5aeec9577577b8184b016651195605ebaa756bd758749ad379R40) 
   * There seems to have been also [a ``VaadinPortlet`` in the past](https://github.com/vaadin/flow/pull/6769).
* there was no documentation why it's still there 
* Vaadin nowadays requires ``jakarta`` (which was not present in the regex)

> all public classes and methods required Javadoc

I didn't know that.

_WIP_

2025-01-13 12:38 UTC, AB-xdev commented on flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java
> -            Class<?>... parameterTypes) throws ExceptionInInitializerError {
> Why is this public method removed?

It was only used in the plugin and is also marked as ``internal`` (in package)

> If it is not used anywhere, we can consider deprecating it, but it cannot be removed.

We can change it back if you like

2025-01-13 12:43 UTC, AB-xdev commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
> -        }
I used an ``Optional`` further down in the ``if``s as I found it more readable and it makes more sense there (the previously created consumer may have never been used in the ``if``s below).

As an alternative one can also do a null check, like:
```java
if(...) {
  if (missingDependencyMessage != null) { // Potential replacement for Optional
    missingDependencyMessage.accept(...);
  }
}
```

2025-01-13 12:46 UTC, AB-xdev commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/DefaultReflector.java
> +public class DefaultReflector implements Reflector {
> Can we make the class final?

What's the advantage of this?
Currently one can override the class if required. If it's ``final`` that's no longer possible.

2025-01-13 12:46 UTC, AB-xdev commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/DefaultReflector.java
> +    public DefaultReflector(final Object copyFromOtherClassLoader) {
> I would make this constructor package-protected, as it looks like to me, it should be used only internally.

Would also keep it public so one can override/instantiate it if required.

2025-01-13 12:49 UTC, AB-xdev commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/DefaultReflector.java
> +        }
+1

Overlooked that, it should probably use the method too like on all other occurrence.

2025-01-14 08:24 UTC, mcollovati commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
> -        }
To be honest, I would prefer the null check in this case, since there is no pipeline built on top of the `Optional`.

2025-01-14 08:24 UTC, mcollovati commented on flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java
> -            Class<?>... parameterTypes) throws ExceptionInInitializerError {
Even if it is `internal`, usually we try not to remove public API in minor or releases.
So, yes, please bring the method back and mark it as `@Deprecated(forRemoval)`. Also, the Javadoc `@deprecation` should state that there will be no replacement.

2025-01-14 08:38 UTC, mcollovati commented
An additional note about the changes in visibility: these changes are significantly increasing the API surface that we would be promising to keep stable between versions. Before committing to something like that, we would want to better understand what potential benefits you expect to get from that.


About the provided scoped dependencies:

> Yes, the original only contained portlet-api and javax.servlet-api.
> I removed it because
>
> the code looked [very ancient](https://github.com/vaadin/flow/commit/015d6664d5278d406dacec3eb772bd43956cf4f5#diff-04a23c32a5945d5aeec9577577b8184b016651195605ebaa756bd758749ad379R40)
> There seems to have been also https://github.com/vaadin/flow/pull/6769.
there was no documentation why it's still there
> Vaadin nowadays requires jakarta (which was not present in the regex)

My concern is that this modification might add more dependencies to the class loader, potentially leading to behavior changes compared to the original code and introducing a breaking change. However, it could make sense to consider also provided dependency. Needs to be investigated.

2025-01-14 12:56 UTC, AB-xdev commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/DefaultReflector.java
> +        }
Fixed

2025-01-14 13:01 UTC, AB-xdev commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/ReflectorController.java
> +public interface ReflectorController {
Done

2025-01-14 14:08 UTC, AB-xdev commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/Fragment.java
Restored and marked as deprecated

2025-01-14 14:08 UTC, AB-xdev commented on flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java
> -            Class<?>... parameterTypes) throws ExceptionInInitializerError {
Restored and marked as deprecated

2025-01-14 14:11 UTC, AB-xdev commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/DefaultReflectorController.java
> +                && "target".equals(artifact.getFile().getParentFile().getName())) {
Done

2025-01-14 14:11 UTC, AB-xdev commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/DefaultReflectorController.java
> +    }
I would keep this here since the Config class is just a data holder which contains no logic.

2025-01-14 14:55 UTC, AB-xdev commented
Thank you for the additional feedback.
I think I responded now to all/most topics.

> An additional note about the changes in visibility: these changes are significantly increasing the API surface that we would be promising to keep stable between versions. Before committing to something like that, we would want to better understand what potential benefits you expect to get from that.

Generally speaking I want to be able to overwrite/customize your code without constantly having to copy it when an update happens because some method is private or something like that.

Since I had this problem now [for the like 50th time, I decided to write a short blog post about it](https://ab-xdev.github.io/blog/blog/2025/01/13/why-java-libraries-should-be-customizable-extensible.html).

> these changes are significantly increasing the API surface that we would be promising to keep stable between versions

I was not aware that you have to keep the plugin "stable" (you know since the average Vaadin user will likely never extend it).

---

> My concern is that this modification might add more dependencies to the class loader, potentially leading to behavior changes compared to the original code and introducing a breaking change. However, it could make sense to consider also provided dependency. Needs to be investigated.

It should make sense to include provided dependencies as the class-loading will otherwise very likely fail (e.g. if a class extends from another one that is inside a provided dependency).
In case of emergency we can also provide an option to exclude / include provided dependencies :)

---

> Currently, the changes in the PR will break projects using ``vaadin-maven-plugin`` because of the removal of static methods used by ``hilla-maven-plugin``.

My opinion here is that the hilla Plugin can implement these itself since only hilla needs them.

>Even re-adding the missing methods, Hilla projects seems not to work out of the box: they require manual configuration of the plugin to include dependencies that are excluded by this change (e.g. swagger, jackson, classgraph).

And now my extensibility effort from above pays off: Hilla can simply use a derivative of ``DefaultReflectorProvider`` where the default excludes/includes are slightly different and work for them.

> Given that existing projects should not require any configuration update if this one gets merged, I would make the dependency filtering an opt-in and not active by default.

The new system is currently designed in a way that it's compatible to the old system and only some - very special - projects might break.
I think if the changes are also ported over into Hilla there should be nothing speaking against this being enabled out of the box.
Additionally a troubleshooting guide can also be provided, which instructs users to disable the ``fastReflector`` on errors.

Anyway I would recommended to bundle these changes only with the next minor/major release and not inside a patch release.

2025-01-16 11:49 UTC, mshabarov commented
> Would be great if the Formatter & Co is checked into the IntelliJ IDE settings

Yes, I agree with this concern. We have this rather old ticket, but still relevant nowadays https://github.com/vaadin/flow/issues/8163. In short, would be nice to include an automatic formatting step into all pull requests automation.

2025-01-29 07:54 UTC, mshabarov commented
@AB-xdev this pull request is quite large and combines several distinct changes, making it challenging to review effectively. To streamline the process and ensure clarity, I propose splitting it into separate pull requests as follows:
1. Remove `gwt-elemental`
This is an isolated change and can be handled in its own pull request for simplicity and a quicker review.
2. Add `frontendIgnoreVersionChecks`
This can also be split into a standalone pull request, as it is independent and has minimal dependencies.
3. Add `fastReflectorIsolation`
This is the most complex part of the pull request and should be further divided into smaller, logical units:
    - Core implementation of `fastReflectorIsolation`.
    - Related configuration or refactoring changes.

**Access Modifiers (Private → Protected)**
The PR makes significant relaxations to access modifiers, which we need to avoid to prevent an overly open API. Here’s why:
The Flow Maven Plugin is extended by the Hilla Maven Plugin, and the Vaadin Maven Plugin is the public, recommended method for building Vaadin applications.
Opening access to extend every single plugin parameter introduces potential risks for plugin compatibility and increases maintenance complexity (e.g., for hybrid Vaadin applications with custom Flow plugins).
Instead of relaxing access, we should:
- Share additional configuration via plugin parameters (e.g., for version check ignoring or granular customisation for reflector/class scanning).
- Avoid extensions of Java Mojo classes for the reasons stated above - we don’t want to courage doing this because of potential problems of compatibility and maintainability.

**License-Related Parameters**
Some parameters proposed in this PR, like `ignoreLicenseChecker` and `ignoreDAU`, are not acceptable, even if they improve performance. We cannot allow Vaadin users to decide when a license is required or not. Instead, we should focus on optimizing the license-checking process to address performance concerns.

**checkRuntimeDependency**
This is a critical part of the license-checking process. This is actually done only for builds with activated Daily Active Users functionality (building with a subscription key).  Allowing it to be disabled could result in broken production artifacts, so we must retain this flag as mandatory.

**hillaAvailable**
We need to investigate whether it is safe and performant to expose this flag.

**checkPluginFlowCompatibility**
This flag disables Flow compatibility checks between the project and the plugin. Since the warnings generated by this check are vital (as the cause may result in runtime issues), we should not allow disabling this check.

**@NpmPackage Inherited Lookup**
Finally, one additional item that deserves its own investigation is the behavior mentioned in point 5:
“Inherited lookup is nearly always performed: When looking up classes with @NpmPackage, all classes extending those with the annotation are also looked up (via ReflectionsClassFinder).”
This should be explored as a separate effort (by Flow team) to determine the impact and feasibility of any changes.

**Proposed Next Steps**
To proceed, I suggest:
- Creating three separate pull requests to extract the above parts from this pull request. (Vaadin Flow team will do it)
- Investigating the @NpmPackage inherited lookup issue independently. (Vaadin Flow team).
- Investigating the license-checking process to address performance concerns. (Vaadin Flow team)
- Investigating the option of adding `hillaAvailable` (Vaadin Flow team).

2025-03-27 15:30 UTC, mshabarov commented
Closed in favour of https://github.com/vaadin/flow/pull/21125.

2025-03-27 15:30 UTC, closed without merging