feat: Add interfaces for CRUD services
vaadin/flow pull request #20743
Opened 2024-12-18 10:04 UTC by Artur-

These were previously in Hilla but are equally useful in Flow applications

2024-12-18 13:06 UTC, peholmst commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/JpaFilterConverter.java
> +    public static <T> Specification<T> toSpec(Filter rawFilter, Class<T> entity) {
You could also make the class itself final, and add a private constructor.

2024-12-18 18:02 UTC, peholmst commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/ListService.java
> +    @NonNull
Are the `@NonNull` annotations here because of Hilla's code generator? I guess Hilla does not understand `@NonNullApi` / `@NullMarked` on a parent interface?

2024-12-18 18:04 UTC, peholmst commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/filter/Filter.java
> +public class Filter implements Serializable {
Are the Filter classes meant to mainly be created by Jackson, or is there a situation where a developer may want to create them in Java as well? Also why are the Filter classes mutable and not immutable?

2024-12-18 18:07 UTC, peholmst commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/filter/package-info.java
> +@org.springframework.lang.NonNullApi
Consider adding `@NullMarked` here.

2024-12-18 18:08 UTC, peholmst commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/CrudRepositoryService.java
> +        getRepository().saveAll(values).forEach(saved::add);
Maybe use `List.copyOf(..)` instead here?

2024-12-18 18:11 UTC, peholmst commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/PropertyStringFilterSpecification.java
> +public class PropertyStringFilterSpecification<T> implements Specification<T> {
Could this be package private, or is there any situation where you would want to manually instantiate it or extend it?

2024-12-19 10:52 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/package-info.java
> +package com.vaadin.flow.spring.data.jpa;
Why would we need both?

2024-12-19 10:55 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/PropertyStringFilterSpecification.java
> +public class PropertyStringFilterSpecification<T> implements Specification<T> {
Wouldn't you want to extend this if the default one does not support a data type you are using or similar?

2024-12-19 10:56 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/CrudRepositoryService.java
> +        getRepository().saveAll(values).forEach(saved::add);
List.copyOf requires a Collection, saveAll returns Iterable

2024-12-19 10:56 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/FormService.java
> +    T save(T value);
Updated javadoc as to be in sync with `CrudRepository.save`

2024-12-19 10:57 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/filter/Filter.java
> +public class Filter implements Serializable {
I need to create some examples to show usage before this is merged. I think they should be public and ok to create by hand but they don't need to be mutable

2024-12-19 10:58 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/ListService.java
> +    @NonNull
They should not be needed, removed. Hilla uses `@NonNullApi`

2024-12-19 10:58 UTC, peholmst commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/package-info.java
> +package com.vaadin.flow.spring.data.jpa;
If removing `@NonNullApi` does not break anything, then by all means remove it.

2024-12-19 10:59 UTC, peholmst commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/CrudRepositoryService.java
> +        getRepository().saveAll(values).forEach(saved::add);
Ah. Good point.

2024-12-19 11:02 UTC, peholmst commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/FormService.java
> +    T save(T value);
Then you should also remove `@Nullable` from the method. 🙂

2024-12-19 11:04 UTC, peholmst commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/PropertyStringFilterSpecification.java
> +public class PropertyStringFilterSpecification<T> implements Specification<T> {
Or introduce another protected method that you can override that already gets the `value`, `javaType`, and `propertyType` so that you don't have to compute them again.

2024-12-19 13:07 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/package-info.java
> +package com.vaadin.flow.spring.data.jpa;
On the contrary, Hilla only supports `@NonNullApi`

2024-12-20 14:00 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/PropertyStringFilterSpecification.java
> +public class PropertyStringFilterSpecification<T> implements Specification<T> {
Better now?

2024-12-20 15:57 UTC, peholmst commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/PropertyStringFilterSpecification.java
> +public class PropertyStringFilterSpecification<T> implements Specification<T> {
Yes! This is good.

2025-01-10 10:30 UTC, mshabarov requested changes

2025-01-10 10:30 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/CrudService.java
> +public interface CrudService<T, ID> extends ListService<T>, FormService<T, ID> {
nit: Here and in other service/repository classes the javadoc misses generic types description.

2025-01-10 10:32 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/ListRepositoryService.java
> +    private R repository;
Ah, maybe not, as it has protected method for setting this object?

2025-01-10 10:41 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/JpaFilterConverter.java
> +public final class JpaFilterConverter {
Or other way around - add a new overload that uses `Filter` and something Vaadin own, e.g. `Query`? To add a consistent abstraction layer between Vaadin and Spring Persistance.

2025-01-10 13:46 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/filter/PropertyStringFilter.java
> +    public void setFilterValue(String filterValue) {
Would it make sense to set "" as filterValue in the default CTOR?

2025-01-10 13:48 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/ListRepositoryService.java
> +    public long count(@Nullable Filter filter) {
Can we have shorthand `count()` method ?

2025-01-10 14:32 UTC, peholmst commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/filter/PropertyStringFilter.java
> +public class PropertyStringFilter extends Filter {
I'm using the Hilla-versions of these classes in a unit test right now. The expression "greeting contains Alice OR greeting contains Eve" requires the following amount of Java code:

```java       
var aliceFilter = new PropertyStringFilter();
aliceFilter.setPropertyId("greeting");
aliceFilter.setFilterValue("Alice");
aliceFilter.setMatcher(PropertyStringFilter.Matcher.CONTAINS);

var eveFilter = new PropertyStringFilter();
eveFilter.setPropertyId("greeting");
eveFilter.setFilterValue("Eve");
eveFilter.setMatcher(PropertyStringFilter.Matcher.CONTAINS);

var filter = new OrFilter();
filter.setChildren(List.of(aliceFilter, eveFilter));
```

I think the Java API could be significantly improved, maybe to something like this:

```java
var filter = new OrFilter(new PropertyStringFilter("greeting", Matcher.CONTAINS, "Alice"), new PropertyStringFilter("greeting", Matcher.CONTAINS, "Eve"));
```

2025-01-10 14:34 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/filter/PropertyStringFilter.java
> +public class PropertyStringFilter extends Filter {
Yes, this is the simplification I had in mind.

2025-01-10 15:20 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/JpaFilterConverter.java
> +public final class JpaFilterConverter {
Well, using `Filter` is much easier for at least common CRUD cases than the criteria API, see my very quick example https://github.com/vaadin/flow-crm-tutorial/compare/crud-services...without-crud-services.

But nevertheless the ListRepositoryService could have a shorthand list method that takes Pageable and Specification.

2025-01-10 15:25 UTC, mshabarov commented
Made a quick example of how a CRUD service may look like with/without these classes https://github.com/vaadin/flow-crm-tutorial/compare/crud-services...without-crud-services. 
A big benefit for me is obviously a simpler filtering: no need to make my own query/criteria code for it.

2025-01-13 09:01 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/filter/PropertyStringFilter.java
> +public class PropertyStringFilter extends Filter {
Added convenience constructors to `PropertyStringFilter`, `OrFilter` and `AndFilter`

2025-01-13 09:05 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/ListRepositoryService.java
> +    public long count(@Nullable Filter filter) {
We could. Should we? :D

2025-01-13 09:06 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/CrudService.java
> +public interface CrudService<T, ID> extends ListService<T>, FormService<T, ID> {
Updated

2025-01-13 09:12 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/filter/PropertyStringFilter.java
> +public class PropertyStringFilter extends Filter {
"needs" is a strong word but maybe it would be convenient that two filters with the same operands equal each other

2025-01-13 09:12 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/FormService.java
> + * A service that can create, update, and delete a given type of object.
Fixed

2025-01-13 09:14 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/CountService.java
> + * A service that can count the given type of objects with a given filter.
Fixed

2025-01-13 09:14 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/CountService.java
> +     * @return
Fixed

2025-01-13 09:36 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/ListRepositoryService.java
> +    public long count(@Nullable Filter filter) {
I think we should, minor thing but IMO makes the code reading a bit clearer when count has no `null` in the project.

2025-01-13 09:51 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/JpaFilterConverter.java
> +public final class JpaFilterConverter {
Excellent explanations! Thanks.
For future we could consider using some abstraction interface over Spring's `Pageable` in these CRUD services, if we would want to do the same for non-Spring containers. I'm fine with the proposed API for now as it seems cover most use cases.

2025-01-13 10:03 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/filter/PropertyStringFilter.java
> +public class PropertyStringFilter extends Filter {
Do you mean Matcher under "operands" ? I think all the fields matter, i.e. propertyId, filterValue, matcher.
On the other hand, how the filters objects are compared probably doesn't matter.

2025-01-13 10:04 UTC, mshabarov submitted a review, later dismissed
Overall looks good and has many benefits of beings available in Flow.
LGTM.

2025-01-13 10:34 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/ListRepositoryService.java
> +    public long count(@Nullable Filter filter) {
Added

2025-01-13 10:34 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/filter/Filter.java
> +public class Filter implements Serializable {
Added convenience constructors. Some usage examples in https://github.com/Artur-/flow-crud-demo/tree/main/src/main/java/com/example/demo

2025-01-13 10:40 UTC, mshabarov submitted a review, later dismissed

2025-01-13 10:51 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/ListRepositoryService.java
> +    public long count(@Nullable Filter filter) {
However, now count and list works differently. 
Also, it is impossible to do something like
```
        grid.setItemsPageable(pageable -> productService.list(pageable, filter),
                pageable -> productService.count(filter));
```

2025-01-13 10:53 UTC, Artur- commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/ListRepositoryService.java
> +    public long count(@Nullable Filter filter) {
Reverted `count()` again. Let's start without it and see?

2025-01-13 10:56 UTC, mshabarov commented on vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/ListRepositoryService.java
> +    public long count(@Nullable Filter filter) {
Yes, okay 👍

2025-01-13 10:57 UTC, mshabarov approved these changes

2025-01-13 11:03 UTC, mshabarov commented
Fixes https://github.com/vaadin/flow/issues/20834.

2025-01-13 11:22 UTC, mshabarov approved these changes

2025-01-13 12:00 UTC, merged