Dp/ccdm/support inline bodysize viewport annotations
vaadin/flow pull request #7168
Opened 2019-12-15 21:19 UTC by ptdatkhtn

allow using @viewport annotation in Appshell class
add test case to count the amount of meta tag when using or not using @viewport annotation

2019-12-15 21:20 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=7168) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=7168) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=7168) it.</sub>

2019-12-15 21:20 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=7168) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=7168) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=7168) it.</sub>

2019-12-16 08:24 UTC, manolo requested changes
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/7168)* status: 2 unresolved discussions, 0 of 1 LGTMs obtained (waiting on @ptdatkhtn)

___
*[flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellRegistry.java, line 182 at r1](https://reviewable.io/reviews/vaadin/flow/7168#-LwCmq3A9CmTnH1lRYSO:-LwCmq3A9CmTnH1lRYSP:bh0jbed) ([raw file](https://github.com/vaadin/flow/blob/8a86b859b495e7be091b22aa9c5161bf9c0c2a25/flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellRegistry.java#L182)):*
> ```Java
>         });
> 
>         getAnnotations(Viewport.class).forEach(viewport -> {
> ```

Viewport only should happen once, although compiler would fail when adding multiple annotations I don't know what happens if class is annotated, but also super class
___
*[flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/AppShell.java, line 10 at r1](https://reviewable.io/reviews/vaadin/flow/7168#-LwCmLBn512Iqm3WgxfG:-LwCmLBo3SeghkonJwr_:bhugkj) ([raw file](https://github.com/vaadin/flow/blob/8a86b859b495e7be091b22aa9c5161bf9c0c2a25/flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/AppShell.java#L10)):*
> ```Java
> @Meta(name = "foo", content = "bar")
> @PWA(name = "My App", shortName = "app")
> @Viewport(Viewport.DEVICE_DIMENSIONS)
> ```

If you add this  you need some assertions in the test class for checking that it happens.
See `IndexHtmlRequestHandlerIT.indexHtmlRequestListener_openRootURL_shouldDynamicMetaContent`


<!-- Sent from Reviewable.io -->

2019-12-16 11:43 UTC, ptdatkhtn commented
___
*[flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/AppShell.java, line 10 at r1](https://reviewable.io/reviews/vaadin/flow/7168#-LwCmLBn512Iqm3WgxfG:-LwDWMFcB1IzI--DBBov:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/8a86b859b495e7be091b22aa9c5161bf9c0c2a25/flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/AppShell.java#L10)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

If you add this  you need some assertions in the test class for checking that it happens.
See `IndexHtmlRequestHandlerIT.indexHtmlRequestListener_openRootURL_shouldDynamicMetaContent`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-12-16 11:43 UTC, ptdatkhtn commented
___
*[flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellRegistry.java, line 182 at r1](https://reviewable.io/reviews/vaadin/flow/7168#-LwCmq3A9CmTnH1lRYSO:-LwDWNDX0RWiUbKMMayl:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/8a86b859b495e7be091b22aa9c5161bf9c0c2a25/flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellRegistry.java#L182)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Viewport only should happen once, although compiler would fail when adding multiple annotations I don't know what happens if class is annotated, but also super class
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-12-16 16:13 UTC, ptdatkhtn commented
___
*[flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellRegistry.java, line 188 at r2](https://reviewable.io/reviews/vaadin/flow/7168#-LwAQTP5hdbKrqqtEkmi-r2-188:-LwEU6S7BVW_uin2zwsV:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f1275449d1daa5264ce548d44a86f5a7101522fe/flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellRegistry.java#L188)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Use isEmpty() to check whether the collection is empty or not. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS1155)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-12-17 08:06 UTC, manolo approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 5 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/7168#-:-LwHt60s3QYmltQL80s8:bnfp4nl)* status: 1 unresolved discussion, 1 of 1 LGTMs obtained (waiting on @vaadin-bot)



<!-- Sent from Reviewable.io -->

2019-12-17 10:07 UTC, manolo approved these changes
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/7168)* status: 1 unresolved discussion, 1 of 1 LGTMs obtained (waiting on @vaadin-bot)



<!-- Sent from Reviewable.io -->

2019-12-17 10:08 UTC, manolo approved these changes
> Dismissed @vaadin-bot from a discussion.
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/7168)* status: :shipit: complete! all discussions resolved, 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-12-17 10:09 UTC, merged