Dp/ccdm/bodysize annotation
vaadin/flow pull request #7179
Opened 2019-12-16 19:13 UTC by ptdatkhtn

- allow using `@BodySize` annotation in AppShell class
- add some test case to check style element that contains body style exist
- add test case to use dynamic content for `@BodySize` annotation

2019-12-16 19:13 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=7179) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=7179) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=7179) it.</sub>

2019-12-16 19:13 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=7179) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=7179) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=7179) it.</sub>

2019-12-17 08:19 UTC, manolo requested changes
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/7179)* status: 1 unresolved discussion, 0 of 1 LGTMs obtained (waiting on @ptdatkhtn)

___
*[flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellRegistry.java, line 176 at r2](https://reviewable.io/reviews/vaadin/flow/7179#-LwHw5EIBDrfGoDc1oHZ:-LwHw5EIBDrfGoDc1oH_:b-l6mwxj) ([raw file](https://github.com/vaadin/flow/blob/c8a0b3b640a7957c5101b2512ef4992b3f14084d/flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellRegistry.java#L176)):*
> ```Java
>      * Modifies the `index.html` document based on the {@link VaadinAppShell}
>      * annotations.
>      *g
> ```

remove


<!-- Sent from Reviewable.io -->

2019-12-17 09:38 UTC, ptdatkhtn commented
___
*[flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellRegistry.java, line 176 at r2](https://reviewable.io/reviews/vaadin/flow/7179#-LwHw5EIBDrfGoDc1oHZ:-LwIDItSB7mkI7It7Gtu:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/c8a0b3b640a7957c5101b2512ef4992b3f14084d/flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellRegistry.java#L176)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-12-17 11:34 UTC, platosha approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/7179#-:-LwIcjixAojeu85ZfoTq:bnfp4nl)* status: 1 unresolved discussion, 1 of 1 LGTMs obtained (waiting on @manolo)



<!-- Sent from Reviewable.io -->

2019-12-17 18:14 UTC, manolo approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/7179#-:-LwK3TYFEDcBdBgoMlgU:bnfp4nl)* status: :shipit: complete! all discussions resolved, 2 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-12-17 18:16 UTC, merged

2026-02-07 11:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=7179) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=7179) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=7179) it.</sub>