Add target constants for Anchor to use with alternate setTarget method (#8346)
vaadin/flow pull request #8397
Opened 2020-05-20 17:42 UTC by jhult

Implements #8346. See the issue for further discussion.

2020-06-27 22:43 UTC, jhult commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
> +        setHref(href);
This problem existed before this PR. I can fix it if so desired.

2020-06-27 22:43 UTC, jhult commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
> +        setText(text);
This problem existed before this PR. I can fix it if so desired.

2020-06-27 22:45 UTC, jhult commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
> +        setTargetEnum(target);
Depending on how we set `href` and `text` (see other `vaadin-bot` issues), I can use the same technique to set the `target`.

2020-06-27 23:03 UTC, jhult commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
> +    public Anchor(String href, String text, AnchorTarget target) {
Fixed.

2020-06-27 23:05 UTC, jhult commented
Requesting a review by @joelpop (since he opened the original issue #8346) and @pleku (since he commented).

2020-06-29 12:49 UTC, joelpop submitted a review, later dismissed
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/8397)* status: 3 unresolved discussions, 0 of 1 LGTMs obtained (waiting on @vaadin-bot)



<!-- Sent from Reviewable.io -->

2020-10-05 05:57 UTC, pleku requested changes
Hi and thanks for the contribution. Sorry that this has been left unnoticed after the vacations.

Only couple of small changes to make. If you're busy to do those, we can handle those too.

2020-10-05 05:57 UTC, pleku commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
> +    public void setTargetEnum(AnchorTarget target) {
I would rename this API to `setTarget` and have it as overloaded method name. This is what we have done in other places too. The getter can then have the more specific name.

2020-10-05 05:57 UTC, pleku commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/AnchorTarget.java
> + * @since 3.2
Since tags should be kept empty, we'll fix those once we know what release the enhancement lands into first.

2020-10-06 16:47 UTC, jhult commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
> +    public void setTargetEnum(AnchorTarget target) {
@pleku,

If I use `setTarget` and keep `getTargetEnum`, I get this error (from `HtmlComponentSmokeTest`):

```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.259 s <<< FAILURE! - in com.vaadin.flow.component.html.HtmlComponentSmokeTest
[ERROR] testAllHtmlComponents(com.vaadin.flow.component.html.HtmlComponentSmokeTest)  Time elapsed: 0.226 s  <<< FAILURE!
java.lang.AssertionError: public void com.vaadin.flow.component.html.Anchor.setTarget(com.vaadin.flow.component.html.AnchorTarget) should have the same type as its getter expected:<class com.vaadin.flow.component.html.AnchorTarget> but was:<class java.lang.String>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at com.vaadin.flow.component.html.HtmlComponentSmokeTest.testSetter(HtmlComponentSmokeTest.java:200)
	at com.vaadin.flow.component.html.HtmlComponentSmokeTest.lambda$testSetters$3(HtmlComponentSmokeTest.java:145)
	at com.vaadin.flow.component.html.HtmlComponentSmokeTest$$Lambda$150/000000002006F0E0.accept(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.vaadin.flow.component.html.HtmlComponentSmokeTest.testSetters(HtmlComponentSmokeTest.java:145)
	at com.vaadin.flow.component.html.HtmlComponentSmokeTest.smokeTestComponent(HtmlComponentSmokeTest.java:107)
	at com.vaadin.flow.component.html.HtmlComponentSmokeTest$$Lambda$71/0000000020029460.accept(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.vaadin.flow.component.html.HtmlComponentSmokeTest.testAllHtmlComponents(HtmlComponentSmokeTest.java:87)
```

Any suggestions on how to rectify?

2020-10-06 16:49 UTC, jhult commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/AnchorTarget.java
> + * @since 3.2
Rebased on `master` and emptied `@since`.

2020-10-09 10:32 UTC, pleku commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
> +    public void setTargetEnum(AnchorTarget target) {
I think it just about adding an exception to the check, as a property `ignoredMethodNames` or such which would have this included and then ignored in the test

2020-11-10 07:39 UTC, pleku requested changes
The changes for the getter name have not been done

2020-11-25 01:47 UTC, jhult commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
> +    public void setTargetEnum(AnchorTarget target) {
I didn't see the exact way to ignore this. So, I followed the example for `Label.setFor`.

2020-11-25 02:08 UTC, jhult commented
@pleku, can you review again now that the `HtmlComponentSmokeTest` tests are passing?

2020-11-25 10:51 UTC, pleku reviewed
One question

2020-11-25 10:51 UTC, pleku commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
> +    public Optional<AnchorTarget> getTargetEnum() {
Should this just return `AnchorTarget.DEFAULT` when the actual string value is `null` instead of an optional ? I understood from the javadocs that it is semantically the same thing ?

2020-11-27 20:32 UTC, jhult commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
> +    public Optional<AnchorTarget> getTargetEnum() {
This now returns `AnchorTarget.DEFAULT` if no target has been set.

2020-11-27 20:34 UTC, jhult commented
@pleku, ready for your review/approval.

2020-11-30 07:32 UTC, pleku reviewed
Continuing on the discussion

2020-11-30 07:32 UTC, pleku commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
> +    public Optional<AnchorTarget> getTargetEnum() {
Sorry, not done, reopening the discussion as I'm not sure if I was clear enough - I meant that instead of returning an empty optional, it would return `AnchorTarget.DEFAULT` so the return type would **not** be `Optional` for `getTargetEnum()`. Is there any other issue for this than if they user uses `setTarget("foobar")` which cannot be parsed to the enum ? I'm not sure if returning `null` would be just fine then, as wrapping the enum in Optional just feels unnecessary complication.

Now that I'm thinking this, it might make sense to even deprecate the String version of `setTarget(String)` and recommend using the enum one instead to avoid errors.

2020-11-30 17:25 UTC, joelpop commented
"target" can also be the *name* of an iframe. Per https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a:

**target**
Where to display the linked URL, as the name for a browsing context (a tab, window, or <iframe>). The following keywords have special meanings for where to load the URL:

- _self: the current browsing context. (Default)
- _blank: usually a new tab, but users can configure browsers to open a new window instead.
- _parent: the parent browsing context of the current one. If no parent, behaves as _self.
- _top: the topmost browsing context (the "highest" context that’s an ancestor of the current one). If no ancestors, behaves as _self.

2020-11-30 17:32 UTC, joelpop commented
In hindsight, maybe a better API would have been to have an additional enum constant `AnchorTarget.IFRAME` and methods something like:

- public AnchorTarget getTarget()
- public void setTarget(AnchorTarget target) // also clears anchor target iframe name if not AnchorTarget.IFRAME (which is a no-op)
- public String getTargetIframeName()
- public void getTargetIframeName(String name) // also sets anchor target to AnchorTarget.IFRAME

2020-12-04 11:48 UTC, pleku commented
I think the suggestion from https://github.com/vaadin/flow/pull/8397#issuecomment-735931255 is OK, with keeping the backwards compatibility by having the getter as
```java
public AnchorTarget getTargetEnum()
```
instead. Also it is a good question that what should happen with `anchor.setTarget(AnchorTarget.IFRAME);` ? Maybe it would be OK to throw an `IllegalArgumentException` and instead point to use `setTargetIframeName` instead.

2021-01-18 07:11 UTC, pleku commented
@jhult are you still interested in continuing with this contribution (based on the comments above) or should we handle it ?

2021-05-04 10:13 UTC, denis-anisimov commented
I'm supposed to make changes in this PR according to the comments but I cannot do this apparently because I disagree with the latest comments.

I'm absolutely against of this suggestion: https://github.com/vaadin/flow/pull/8397#issuecomment-735931255
It introduces two accessors for _one_ state. 
It's always extremely confusing to have two accessors for the same state: one setter should affect one getter (corresponding). With two accessors: one setter affects two getters.
(another observation : `setTarget(AnchorTarget.IFRAME)`  is useless without `setTargetIframeName` )

Now the enumeration can't be used for `target` : an iframe name can be used as a `target`  value so we may not deprecate `setTarget(String)` and use only `getTargetEnum/setTargetEnum` .
`Optional<AnchorTarget> getTargetEnum` looks much better for me then `AnchorTarget getTargetEnum()` which returns `AnchorTarget#DEFAULT` if it's not able to map a `target`  value to the enum (but it should be an empty optional of course).

So I'm not sure what to do with this, @pleku ....

2021-05-04 16:11 UTC, joelpop commented
We're having trouble coming to an agreement on how to implement our API because the API for HTML's anchor tag was poorly designed, and now we're stuck with it. I've always been irritated by how they "overloaded" the target attribute. That's the same thing we're running into as we work to provide our users an easy way to use it from Flow.

Perhaps the best compromise solution now would be to ditch the AnchorTarget enum and the new methods that use them, and funnel everything through the existing String methods. However, to give the users a little help, we could then create some convenience constants in the Anchor class like these:

```
    /**
     * Opens the link in a new unnamed context.
     */
    public static final String TARGET_BLANK = "_blank";
    /**
     * Opens the link in the parent context,
     * or the current context if there is no parent context.
     */
    public static final String TARGET_PARENT = "_parent";
    /**
     * Opens the link in the current context. (The default if nothing is specified for target.)
     */
    public static final String TARGET_SELF = "_self";
    /**
     * Opens the link in the top most grandparent context,
     * or the current context if there is no parent context.
     */
    public static final String TARGET_TOP = "_top";
```

That way our API does not change at all, but our users can access "target's" special String values and documentation a little easier.

Your thoughts?

2021-05-05 13:50 UTC, pleku reviewed
One suggestion for javadocs in case someone doesn't get the intent for iframes

2021-05-05 13:50 UTC, pleku commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/AnchorTargetValue.java
> +        return new AnchorTargetValue() {
Non-blocking: I wonder why this is an anonymous class instead of private class here but I don't think it makes any difference

2021-05-05 13:50 UTC, pleku commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
> +     *
```suggestion
     * For targeting an {@code <iframe>}, browser window or tab by its name, use
     * {@link #setTarget(String)} instead.
     *
```

2021-05-06 05:46 UTC, pleku approved these changes

2021-05-06 05:47 UTC, merged

2021-05-07 07:39 UTC, pleku commented
Cherry-picked manually in https://github.com/vaadin/flow/pull/10940