Decode path in Location before producing segments.
vaadin/flow pull request #8815
Opened 2020-08-05 04:42 UTC by denis-anisimov

Fixes #7454

2020-09-08 15:44 UTC, joheriks requested changes

2020-09-08 15:44 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/router/Location.java
> +                    StandardCharsets.UTF_8.name());
Unclear if routes containing `%` character has ever been or should be supported, but this change seems to causes a regression for these. For instance:
```
@Route("percent%man")
public class SpaceMan extends VerticalLayout {
    ...
}
``` 

At this point in the code, the `%` is for some reason not encoded (as `%25`), causing the call to `URLDecoder.decode` to throw.

2020-09-17 08:51 UTC, bogdanudrescu commented on flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java
> +    public void locaitonWithSpacesInPath_segmentIsDecoded() {
typo in`locaiton`, should be `location`

2020-09-21 08:07 UTC, bogdanudrescu commented on flow-server/src/main/java/com/vaadin/flow/router/Location.java
>      private static List<String> parsePath(String path) {
Shouldn't we decode also the parameters in `parseParams`

2020-09-21 08:32 UTC, bogdanudrescu commented on flow-server/src/main/java/com/vaadin/flow/router/Location.java
> +                    StandardCharsets.UTF_8.name());
In case of `percent%man` route, without the fix in this PR, the behaviour I get is that the page is populated with the view but the address bar url doesn't change.

2020-09-21 08:33 UTC, bogdanudrescu requested changes

2020-09-21 08:33 UTC, bogdanudrescu commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RouteTargetWithSpaceView.java
> +    @Route("route with space")
We should also add a tests with a route url as in https://github.com/vaadin/flow/issues/3462 which is a duplicate of the current issue.

2020-10-01 08:16 UTC, denis-anisimov commented on flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RouteTargetWithSpaceView.java
> +    @Route("route with space")
#3462 is not a duplicate of this ticket since this ticket is about spaces in path and #3462 is about parameters.
The code for this two cases is different even though it's quite related and it's in the same class.
This is just for academical accuracy.

2020-10-01 10:04 UTC, closed without merging