Live reload on frontend changes
vaadin/flow pull request #8875
Opened 2020-08-20 22:00 UTC by joheriks

Addresses tickets #8852, #8721, #5617, #607 (and maybe others).

2020-08-24 08:12 UTC, caalador requested changes

2020-08-24 08:12 UTC, caalador commented on flow-tests/test-live-reload/frontend/styles.css
> +/* A CSS file */
Could have the comment as `unstyled css file for on the fly styling` or other more descriptive use of the file.

2020-08-24 08:43 UTC, caalador approved these changes

2020-08-24 09:39 UTC, caalador approved these changes

2020-08-24 10:33 UTC, merged

2020-08-25 08:24 UTC, joheriks commented
When/if backporting to 2.3, check compatibility with ES5 transpilation (e.g. `findIndex` fix https://github.com/vaadin/flow/pull/8788 needs to be reapplied)