Fix typo in variable DEAULT_FLOW_RESOURCES_FOLDER
vaadin/flow pull request #8897
Opened 2020-08-26 05:09 UTC by Haprog

Replace DEAULT_FLOW_RESOURCES_FOLDER with DEFAULT_FLOW_RESOURCES_FOLDER, but keep the old variable as deprecated.

2020-08-26 05:12 UTC, Haprog commented on flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
> -import static com.vaadin.flow.server.frontend.FrontendUtils.DEAULT_FLOW_RESOURCES_FOLDER;
This was an unused import.

2020-09-08 12:06 UTC, joheriks requested changes

2020-09-08 12:06 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
>              + "flow-frontend";
Any particular reason for duplicating the value of the constant? Would be less redundancy to have the new `DEFAULT_FLOW_RESOURCES_FOLDER` introduced first with value and then the deprecated name backreferencing it:
```java
    @Deprecated
    public static final String DEAULT_FLOW_RESOURCES_FOLDER = DEFAULT_FLOW_RESOURCES_FOLDER;

```

2020-09-08 13:20 UTC, Haprog commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
>              + "flow-frontend";
Good point. I can change it (maybe later today when I'm back at my computer, or tomorrow)

2020-09-09 12:14 UTC, Haprog commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
>              + "flow-frontend";
Done.

2020-09-09 19:41 UTC, joheriks approved these changes

2020-09-09 19:42 UTC, merged