Add HasHelper interface
vaadin/flow pull request #8922
Opened 2020-08-31 09:35 UTC by DiegoCardoso

On this PR:

- Add HasHelper interface to be used for field components that have a "helper" feature (such as TextField)
- The interface contains getters and setters with default implementation for text and component APIs
- Tests for the methods

Fix #8871

2020-08-31 12:48 UTC, pleku requested changes

2020-08-31 12:48 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/component/HasHelper.java
> +      .collect(Collectors.toList())
Unnecessary collecting to a list since it seems like there can only ever be one child with the slot=helper, so could go with `findAny().ifPresent(...)` instead

2020-08-31 12:48 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/component/HasHelper.java
> +    if (element.isPresent()) {
I don't think this is necessary for readability as it adds more lines, could just use mapping to the Stream with `map(Element::get)` before `findFirst()` and then `return component.orElse(null);`.

2020-08-31 12:48 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/component/HasHelperTest.java
> +
Slightly nit-picking, but could validate the default values too so that those are not accidentally changed

2020-09-01 13:51 UTC, DiegoCardoso commented on flow-server/src/main/java/com/vaadin/flow/component/HasHelper.java
> +      .collect(Collectors.toList())
Changed.

2020-09-01 13:51 UTC, DiegoCardoso commented on flow-server/src/main/java/com/vaadin/flow/component/HasHelper.java
> +    if (element.isPresent()) {
I changed as suggested, but then `findFirst()` returns an `Optional<Optional<Component>>` object, so I had to add a `.orElse(Optional.empty())`.

2020-09-01 13:51 UTC, DiegoCardoso commented on flow-server/src/test/java/com/vaadin/flow/component/HasHelperTest.java
> +
Added.

2020-09-01 13:51 UTC, DiegoCardoso commented on flow-server/src/main/java/com/vaadin/flow/component/HasHelper.java
> +   * String used for the helper text.
Added text describing the feature more for both setters.

2020-09-02 05:35 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/component/HasHelper.java
> + * @author Vaadin Ltd
That is why we prefer to just add the tags as empty `@since` - those can be then later on fixed at any point

2020-09-02 05:38 UTC, pleku approved these changes

2020-09-02 05:48 UTC, merged

2020-09-02 05:52 UTC, pleku commented
PR to master (5.0) open too.