Cherry picks for starting web pack dev server and (p)npm install command in the separate thread
vaadin/flow pull request #8925
Opened 2020-08-31 11:33 UTC by denis-anisimov

Fixes #8859

2020-09-02 09:19 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
> +            getLogger().warn("'{}' doesn't exist. Did you run `npm install`?",
Should this be somehow reformulated to include pnpm as it's the default now? 

`(p)npm install` or `pnpm/npm install` or just check it from the configuration and give the correct one expected to be used. As running the wrong one will create slowness and possibly even mess up the node_modules folder.

2020-09-02 09:19 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendToolsLocator.java
>          try {
Unrelated formatting changes in File.

2020-09-02 13:57 UTC, pleku requested changes
Couple of comments / questions

2020-09-02 13:57 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
> +        long start = System.nanoTime();
Just a note that now the start time is recorded during a different phase, it used to be just before the `processbuilder.command(command);`.

Is this change intentional and why ? I know it hardly matters for the execution itself, just curious as there is some additional things now done after that compared to before.

2020-09-02 13:57 UTC, pleku commented on flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
> +    protected void waitForDevServer() {
I'm sure this has been discussed earlier too, but I'm going still ask: why do we need to explicitly wait for it in tests instead of just fixing TB or Flow's wait for Vaadin to handle it automatically when devserver is being run ?

2020-09-02 13:57 UTC, pleku commented on flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
> +            getDriver().navigate().refresh();
Maybe might be a good clarifying comment to the test that this is not really part of the test, but instead just for waiting for the devserver to be done

2020-09-02 13:57 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerStopTest.java
This test class is ignored for flakiness for Java 11 and PR validation (?).

It could instead be configured for the surefire plugin to be included/excluded in certain JDK version activated profile. Now it seems to me we are never running this test even though it might pass.

But I suppose this is a non-blocking comment...

2020-09-03 05:58 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
> +        long start = System.nanoTime();
Right....
It's consistent with the `master`  branch now:

https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java#L540

But yes, it was in another place.
OK, I will move it there.

2020-09-03 06:00 UTC, denis-anisimov commented on flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
> +    protected void waitForDevServer() {
TB is a different product.
I've asked to fix that in TB and explained how.
But nobody cares.
The original PR couldn't pass the validation without this fix.
So it was necessary. And it's still necessary to make validation passing at the moment.
TB may be fixed separately and then this can be removed.

2020-09-03 06:08 UTC, pleku commented on flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
> +    protected void waitForDevServer() {
As a reminder, to the users there is one product: Vaadin. And if users tests get broken because we're are making changes in the ways things are working, we are (in my opinion) responsible for that.

We should be probably in the best position to contribute it to https://github.com/vaadin/testbench/blob/23efeafc771448876886233123bc12dcc4cdd45e/vaadin-testbench-core/src/main/java/com/vaadin/testbench/DriverInvocationHandler.java#L64
At least then we could remove this debt from our testing code. Can you create a ticket about this or is there one already ? If there is, then it should be mentioned here.

2020-09-03 06:14 UTC, pleku requested changes

2020-09-03 06:14 UTC, pleku commented on flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
> +        // https://github.com/vaadin/flow/issues/7596
But this issue is for 15+ so why is it picked for 14 ??? It should not be here. 14 should have 5500

2020-09-03 06:16 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerStopTest.java
Github.

There are no changes in this method: it's not removed or ignored.
It's here : https://github.com/vaadin/flow/blob/2729a22dd4f0c916e3251240b17f0646f70a71b7/flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerStopTest.java

2020-09-03 06:19 UTC, denis-anisimov commented on flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
> +        // https://github.com/vaadin/flow/issues/7596
Right.......

And I'm very curious how that has been cherry-picked if this is commit is not a part of cherry-picks.
`git` never works for me as it should.

2020-09-03 06:25 UTC, denis-anisimov commented on flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
> +    protected void waitForDevServer() {
There is a ticket : https://github.com/vaadin/testbench/issues/1244

2020-09-03 06:27 UTC, denis-anisimov commented on flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
> +    protected void waitForDevServer() {
This is a cherry-pick.
So technically this should have been done (or not) in the `master`  branch.
Now we desync the branches.

2020-09-03 06:30 UTC, pleku approved these changes

2020-09-03 06:31 UTC, pleku commented on flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
> +        // https://github.com/vaadin/flow/issues/7596
Not sure what could cause it. Maybe there is some difference between _merge strategies_.

2020-09-03 07:17 UTC, merged