Remove progress plugin from web-pack config
vaadin/flow pull request #8935
Opened 2020-09-02 11:31 UTC by denis-anisimov

Fixes #8933

2020-09-02 12:57 UTC, joheriks approved these changes

2020-09-02 13:01 UTC, joheriks requested changes

2020-09-02 13:01 UTC, joheriks commented on flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
> +                        : 1000;
5500 ms was used for V14, any reason to assume it will be faster with V15 bootstrap?

2020-09-03 06:31 UTC, denis-anisimov commented on flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
> +                        : 1000;
Ah, hm.
I thought progress plugin is for any version.
But OK, I will revert that.

Just a note: this code never worked since:
- `Boolean.getBoolean("vaadin.useDeprecatedV14Bootstrapping")` always returns `false`.
- there is no any configuration which allow to run this test  using V14 bootsrtaping.

2020-09-03 08:24 UTC, joheriks approved these changes

2020-09-03 08:43 UTC, merged