Fixes from backporting frontend live-reload into master
vaadin/flow pull request #8937
Opened 2020-09-03 08:57 UTC by joheriks

Getting fixes for some issues that surfaced in the review of the cherry-pick #8930 of #8875 into master:
* Better ES5 compatibility in VaadinDevmodeGizmo (while not strictly necessary for V17+, including these also here makes backporting future changes to VaadinDevmodeGizmo simpler)
* Made BootstrapHandlerHelper a utility class (private ctor and final)
* Set encoding explicitly on webpack <-> server socket

2020-09-03 09:15 UTC, denis-anisimov requested changes

2020-09-03 09:15 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/DevServerWatchDog.java
> +            BufferedReader in = new BufferedReader(new InputStreamReader(
I'm not sure at which point this functionality was added to the watchdog but it looks absolutely alien for it.

Watchdog has only one purpose: notify webpack server to stop when JVM is stopped.
Anything else here is just illogical.

Any other functionality added here is absolutely unexpected and may not be located here.
Otherwise the code is going to become unmantainable.

This code has to be refactored so that watchdog does only its function and other functionality does its own function.

I didn't dig into this deeply but the simplest way could be rename `DevServerWatchDog`  to another class and register/add some handlers so that they are called generically via common interface. One handler could be watchdog, another : this code.

Though may be this code should be just completely removed from here and somehow implemented in another place.

I totally disagree with having it here. It makes a mess.

2020-09-03 09:25 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/DevServerWatchDog.java
> +            BufferedReader in = new BufferedReader(new InputStreamReader(
The feature needs to connect the webpack recompile hook to the live reload trigger, and this existing connection is useful for the purpose ("the watchdog got another task"). A refactoring/renaming to better capture the extended responsibility of the class sounds like a good idea.

2020-09-03 09:52 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/DevServerWatchDog.java
> +            BufferedReader in = new BufferedReader(new InputStreamReader(
I'm not sure whether this is should be done as another task or not since this PR is going to solve another issue.

But this code definitely needs refactoring: pure watchdog doesn't know anything about anything , especially about Live reload.
They should be absolutely decoupled.
Some abstraction layer should be introduced to avoid one functionality knowing about another unrelated functionality.

I may unblock this to fix addressed issue but the code required refactoring for sure.

2020-09-07 14:23 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/DevServerWatchDog.java
> +            BufferedReader in = new BufferedReader(new InputStreamReader(
Ticket for internal refactoring:
https://github.com/vaadin/flow/issues/8960

2020-09-08 06:42 UTC, denis-anisimov approved these changes

2020-09-08 06:42 UTC, merged