Move service worker generation to webpack config
vaadin/flow pull request #8940
Opened 2020-09-03 10:41 UTC by Haprog

WIP related to #8911.

TODO:
- service worker should be registered and work both in dev and production mode (after `mvn clean` and removal of webpack.generated.js).
  - Currently webpack generates it to `../resources/sw.js` which results in it being served at root but it only works after running `build-frontend` task. It can be changed to `build/sw.js` so that it also seems to be served in dev mode too but that results in it being served from `VAADIN/build/sw.js` and that causes a scope issue when registering the service worker (unless extra HTTP header `Service-Worker-Allowed` is added to the `sw.js` response). So we need some way to make sure the webpack generated `sw.js` is served from root, and also works in dev mode without extra steps.
- following things should be somehow added to workbox precache manifest (with hash/revision):
  - offline.html (currently runtime generated)
  - manifest.webmanifest (currently runtime generated)
  - pwa/app icons (currently runtime generated), only webmanifest icons?
  - can we precache these dynamically at runtime (when service worker has just been registered) without knowing the content/hash at build time? Or do we need to make sure these are also available at build time?

2020-09-03 12:19 UTC, Haprog commented
I think we can use this kind of approach to caching the offline page (default behaviour for now): https://developers.google.com/web/tools/workbox/guides/advanced-recipes#offline_page_only

2020-09-25 07:30 UTC, Haprog commented
This PR closes #8911 and #8982. Tests still need to be fixed.

2020-09-28 10:06 UTC, Haprog commented on flow-server/src/main/resources/webpack.generated.js
> +const rootUrl = String.fromCharCode(47); // equivalent of '/'
I don't like this. Obfuscation for the sake of passing some test(s) makes no sense to me.

2020-09-28 10:08 UTC, Haprog commented on flow-server/src/main/resources/webpack.generated.js
> +const rootUrl = String.fromCharCode(47); // equivalent of '/'
Which test was this related to?

2020-09-28 14:44 UTC, platosha commented on flow-server/src/main/resources/webpack.generated.js
> +const rootUrl = String.fromCharCode(47); // equivalent of '/'
See `com.vaadin.flow.server.frontend.TaskUpdateWebpackTest#verifyNoAbsolutePathsPresent`

2020-09-29 10:06 UTC, Haprog commented on flow-server/src/main/resources/webpack.generated.js
> +const rootUrl = String.fromCharCode(47); // equivalent of '/'
The test already seems to have an exception for `publicPath`. I think it would be better to keep the code clean and add a similar exception in the test. But also the `publicPath` is not used anymore (it was previously used in the webpack output options) so that could be replaced with an exception for this `rootUrl`.

So something like (note that all whitespaces have been removed at this point):
```java
.filter(line -> !line.startsWith("constrootUrl="))
```

Instead of the current:
```java
.filter(line -> !line.startsWith("publicPath:"))
```

2020-09-29 11:50 UTC, platosha commented on flow-server/src/main/resources/webpack.generated.js
> +const rootUrl = String.fromCharCode(47); // equivalent of '/'
👍  good idea, done

2020-09-30 07:49 UTC, haijian-vaadin requested changes

2020-09-30 10:22 UTC, Haprog commented on flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
> +                // Skip "index.html", as it should go through
Yeah looking at this commit https://github.com/vaadin/flow/commit/b0725798b8f2e7d0853863a71825e07a91c08fe9 it looks like a copy paste mistake to me? The comment is added to two places but filter only in one of them.

2020-09-30 10:23 UTC, Haprog reviewed
I can't mark this as approved as I'm the original author, but I looked through the new changes (by Anton) and those look ok to me (though note Haijian's comments above).

2020-09-30 10:48 UTC, platosha commented on flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
> +        // TODO: make sure target directories are aligned with build config
Created: https://github.com/vaadin/flow/issues/9082

Should I mention the link in TODO also?

2020-09-30 11:45 UTC, haijian-vaadin approved these changes

2020-09-30 12:03 UTC, merged