Do not force installation of compatible pnpm version when system property `vaadin.ignoreVersionChecks` is set
vaadin/flow pull request #8971
Opened 2020-09-08 11:41 UTC by joheriks

Fixes #8889.

2020-09-08 12:47 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +                    if (FrontendUtils.skippingVersionCheck()) {
Done

2020-09-08 12:47 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +                                String.join(" ", pnpmCommand));
Done

2020-09-09 08:16 UTC, denis-anisimov requested changes

2020-09-09 08:16 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +                if (FrontendUtils.skippingVersionCheck()) {
Two issues here:  
- skip version check is done after version check. Version check may throw an exception and skip will not skip.
- `FrontendTools` has been created to avoid static things like  `FrontendUtils.skippingVersionCheck`.

`skip version check` flag should be passed to the `FrontendTools`  CTOR.
`FrontendUtils`  as a helper class should contain only helper generic methods.
Everything else should be a state of `FrontendTools` otherwise it goes to the same direction as  `FrontendTools`

2020-09-09 08:16 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
> +        String originalPropertyValue = System
Making flag a parameter in the CTOR will allow to test `FrontendTools`  properly: without any system properties.

Every code which sets system property is not thread safe at least: the same property may be modified outside of this test at any time.

2020-09-09 15:51 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +                if (FrontendUtils.skippingVersionCheck()) {
Good point! Now uses the found `pnpm` even if the version check failed (i.e., threw `UnknownVersionException`). Also removed the static method `FrontendUtils::skippingVersionCheck`, added ctor parameter, and moved the logic to `FrontendTools`.

2020-09-09 15:51 UTC, joheriks commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
> +        String originalPropertyValue = System
Done.

2020-09-10 05:30 UTC, denis-anisimov approved these changes

2020-09-10 05:30 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +            if (!ignoreVersionChecks) {
I would avoid version check via `getVersion`  at all if it should be ignored anyway: it takes additional time
and it may throw an exception whose catching is always more expensive than just check a condition.

Not blocking though.

The only benefit from the current code is logging about failed version check but this is something we failed internally: the `node` of course has some version and we just not able to detect it. So it's an internal issue which will be ignored anyway. So I don't see why spend significant time on checking something which won't be used anyway.

2020-09-10 05:30 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +        if (ignoreVersionChecks) {
Same here: check is done after attempt to get a version and check whether it's good enough.
Why just don't return immediately without any checks in case  `ignoreVersionChecks`?

2020-09-10 06:40 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +            if (!ignoreVersionChecks) {
After more consideration, I agree. My initial line of thinking was that the log about incompatible pnpm would be good anyway. And it's "ignore" version checks rather than "skip" version checks. However, if one is setting this flag one probably knows what one is doing.

2020-09-10 06:40 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +        if (ignoreVersionChecks) {
Done.

2020-09-10 07:24 UTC, denis-anisimov approved these changes

2020-09-10 08:18 UTC, merged