Implement lit template parser for limited template formats which extends LitTemplate element
vaadin/flow pull request #8979
Opened 2020-09-09 05:12 UTC by denis-anisimov

Fixes #8966

2020-09-10 10:53 UTC, joheriks requested changes

2020-09-10 10:53 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateParserImpl.java
> +    }
Could looping through the dependencies somehow be factored out as this method is quite complex.

2020-09-10 10:53 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateParserImpl.java
> +    private final ReentrantLock lock = new ReentrantLock();
Some more descriptive name on this field would be good.

2020-09-10 11:01 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateDataAnalyzer.java
> +                    templateClass);
`warn` is good when it happens rarely and unexpected.
In fact this is absolutely expected situation.
`templateData`  is not null _only_ for Designer template which extends `LitTemplate` directly and has to provide `render` method.
Generally `render`  method doesn't have to be in the template.
So this parser works only for very specific cases and generally it won't work. So `info` looks more suitable for me here.

2020-09-10 11:08 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateParserImpl.java
> +    private final ReentrantLock lock = new ReentrantLock();
Oh my god !
:(
This is copy paste of the existing code from `NpmTemplateParser`  and it's absolutely broken.......

2020-09-10 11:25 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateParserImpl.java
> +    }
Unfortunately I failed any attempt to refactor it.

There are too many local variables which are used across the code.
Extracting methods will require very cumbersome return types.

2020-09-10 11:26 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateParserImpl.java
> +    private final ReentrantLock lock = new ReentrantLock();
The code is corrected.

2020-09-10 16:39 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateDataAnalyzer.java
> +                    templateClass);
Ok

2020-09-10 16:39 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
> +            "render\\(\\)[\\s]*\\{[\\s]*return[\\s]*html([\\`\\'\\\"])([\\s\\S]*)\\1;[\\s]*\\}");
For discussion: `LIT_TEMPLATE_PATTERN` is sent as parameter to `Matcher::find` which matches greedily. It means that if there is an additional block of the form ``xxx`...`;} `` following the end of the ``html`...`;}`` block, it will also be consumed by the regex. This could happen for instance if a `styles` function  was placed after `render`:

```javascript
export class LitTest extends LitElement {
  render() { return html`<button/>`; }
  static get styles() { return css`:host { background-color: pink }`; }
}
```

Putting this throught the parser results in the following `templateDocument`:

```html
<html>
 <head></head>
 <body>
  <button></button>`; } static get styles() { return css`:host { background-color: pink }
 </body>
</html>
```

Maybe we can rely on templates from designer to never have such an issue. But it would feel safer to match the content between the delimiters as ``[^`]|\\` ``, though I'm not sure how to make that work with the backreference `\\1` (is it at all possible to use `html"..."` or `html'...'`? I get syntax errors when I try them, both in JS and TS).

2020-09-11 05:52 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
> +            "render\\(\\)[\\s]*\\{[\\s]*return[\\s]*html([\\`\\'\\\"])([\\s\\S]*)\\1;[\\s]*\\}");
I don't know how to solve this via regexps.
Solved via truncating the matched group in the code.

`css` example is quite artificial here since it may not contain DOM elements (the content is parsed) and will be just a text node.
But anyway I've added the unit test for this with invalid css containing HTML element.

2020-09-11 06:33 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
> +            "render\\(\\)[\\s]*\\{[\\s]*return[\\s]*html([\\`\\'\\\"])([\\s\\S]*)\\1;[\\s]*\\}");
Could that match too early if there is an escaped backtick? For instance:
```javascript
export class LitTest extends LitElement {
  render() { return html`<span>Backtick in html: \` </span>`; }
}

```

2020-09-11 06:40 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
> +            "render\\(\\)[\\s]*\\{[\\s]*return[\\s]*html([\\`\\'\\\"])([\\s\\S]*)\\1;[\\s]*\\}");
Yes, it can .
And this is the consequence of not being greedy: it's either greedy or not.
Greedy has issues , not greedy has issues.
This way of parsing doesn't support every case.
Designer is not supposed to use this or we will need to rewrite it (and since designer doesn't support LitTemplate at all it has no sense to guess what is supported and what's not).

2020-09-11 06:46 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
> +            "render\\(\\)[\\s]*\\{[\\s]*return[\\s]*html([\\`\\'\\\"])([\\s\\S]*)\\1;[\\s]*\\}");
I believe that it will be possible to write backticks in any field in designer. And the parser will not work then, so it will be  clear bug. Handling escaped backticks should be doable with regex.

2020-09-11 06:55 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
> +            "render\\(\\)[\\s]*\\{[\\s]*return[\\s]*html([\\`\\'\\\"])([\\s\\S]*)\\1;[\\s]*\\}");
The problem is : I don't know what we are trying to solve here.

First of all: this is already a bug in Polymer template. Exactly the same issue is for it and this "bug" already exists.
The tick doesn't have to be escaped.
This is correct template content:
```
html`
  ${this.myBool?
    html`<p>Render some HTML if myBool is true</p>`:
    html`<p>Render some other HTML if myBool is false</p>`}
`;
```

And finally : please just let me know how may I solve this : should be "\\\\\\\`" considered as a possible inside the content ? pattern for excluding "\\\`" is most likely not a sloution

2020-09-11 07:08 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
> +            "render\\(\\)[\\s]*\\{[\\s]*return[\\s]*html([\\`\\'\\\"])([\\s\\S]*)\\1;[\\s]*\\}");
Yes, I think the easiest way would be to change the pattern to accept `` `\` `` also in the content.
I don't think we should need to handle any unescapes `${...}` back to JS, as that would theoretically require a regex handling all possible JS syntax. AFAIK Designer will not generate such, at least not containing a nested escape block.

2020-09-11 07:19 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
> +            "render\\(\\)[\\s]*\\{[\\s]*return[\\s]*html([\\`\\'\\\"])([\\s\\S]*)\\1;[\\s]*\\}");
My point is :
"\\\\'" is decoded two symbols "\\" and "\`", so it has nothing to do with escaped  "\`"
"\\'" is decoded as  "\`".

So the question is : should "\\\\'" be also allowed in the content ?

As a result : show may I distinguish "_some_number_of_\\\`"  from "_another_number_of_\ \\`"

2020-09-11 08:00 UTC, joheriks commented on flow-server/src/test/resources/META-INF/VAADIN/config/stats.json
> +                "source": "// Import an element\nimport { LitElement, html } from 'lit-element';\n\n// Define an element class\n export class MyGreedyLitElement extends LitElement {\n\n  // Define th
I believe there's a missing `}` after the ``return html`...` `` and just before the `static get styles`(column 515).

2020-09-11 08:07 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
> +            "render\\(\\)[\\s]*\\{[\\s]*return[\\s]*html([\\`\\'\\\"])([\\s\\S]*)\\1;[\\s]*\\}");
I really don't think it's useful to solve one very specific unclear usecase ignoring unknown number of other generic cases 
and I don't know how to solve this with regexps.

Since the exact usecase is not clear for me I've fixed something via the code.

2020-09-11 08:11 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
> +            "render\\(\\)[\\s]*\\{[\\s]*return[\\s]*html([\\`\\'\\\"])([\\s\\S]*)\\1;[\\s]*\\}");
Would this pattern work?
```java
private static final Pattern LIT_TEMPLATE_PATTERN = Pattern.compile(
    "render\\(\\)[\\s]*\\{[\\s]*return[\\s]*html`(([^`]|\\.)*)`;[\\s]*\\}");

So anything escaped with `\` would be accepted. Except this doesn't accept `'` or `"` as delimiters but I still don't understand why that is needed. 

(BTW, to be able to write `` ` `` in GH MD one can use double backticks around the whole block)

2020-09-11 08:17 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
> +            "render\\(\\)[\\s]*\\{[\\s]*return[\\s]*html([\\`\\'\\\"])([\\s\\S]*)\\1;[\\s]*\\}");
In my opinion the fix in the [last commit](https://github.com/vaadin/flow/pull/8979/commits/904285e32c8f159a87a7a4d3f2ae169054e892e3) would be a regression, since it will break the case where somebody is entering a backtick in component field in designer. I would either fix the regex to accept escape sequences or revert that commit.

2020-09-11 08:32 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
> +            "render\\(\\)[\\s]*\\{[\\s]*return[\\s]*html([\\`\\'\\\"])([\\s\\S]*)\\1;[\\s]*\\}");
This pattern doesn't match the template content in the latest test.

2020-09-11 08:47 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
> +            "render\\(\\)[\\s]*\\{[\\s]*return[\\s]*html([\\`\\'\\\"])([\\s\\S]*)\\1;[\\s]*\\}");
Sorry. I had forgot the Java escaping also for `\`:
```java
    private static final Pattern LIT_TEMPLATE_PATTERN = Pattern.compile(
            "render\\(\\)[\\s]*\\{[\\s]*return[\\s]*html`(([^`]|\\\\.)*)`;[\\s]*\\}");
```
Also there was a missing `}` in that latest test case.

2020-09-11 08:53 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
> +            "render\\(\\)[\\s]*\\{[\\s]*return[\\s]*html([\\`\\'\\\"])([\\s\\S]*)\\1;[\\s]*\\}");
This pattern doesn't match the template content in the latest test (from the latest commit)
whose content is:

"source": "// Import an element\nimport { LitElement, html } from 'lit-element';\n\n// Define an element class\n export class MyGreedyLitElement extends LitElement {\n\n  // Define the element's template\n  render() {\n    return html`\n      <style>\n        :host{ \n          margin: 5px; \n        }\n      \n        .response { margin-top: 10px; } \n      </style>\n   <div>\\`Tag name doesn't match the JS module name<div>inner</div></div>   <div id='test'  class='response'>greedy</div>\n    `;\n static get styles() { return css`:host { background-color: pink } <span>incorrect content</span>`; }} }\n}\n\n// Register the element with the browser\ncustomElements.define('my-greedy-element', MyGreedyLitElement);"

2020-09-11 09:00 UTC, joheriks commented on flow-server/src/test/resources/META-INF/VAADIN/config/stats.json
> +                "source": "// Import an element\nimport { LitElement, html } from 'lit-element';\n\n// Define an element class\n export class MyGreedyLitElement extends LitElement {\n\n  // Define th
There is a missing `}` at column 505.

2020-09-11 09:04 UTC, denis-anisimov commented on flow-server/src/test/resources/META-INF/VAADIN/config/stats.json
> +                "source": "// Import an element\nimport { LitElement, html } from 'lit-element';\n\n// Define an element class\n export class MyGreedyLitElement extends LitElement {\n\n  // Define th
Right, thanks.

Does it change parsing anyhow ?

2020-09-11 09:06 UTC, joheriks commented on flow-server/src/test/resources/META-INF/VAADIN/config/stats.json
> +                "source": "// Import an element\nimport { LitElement, html } from 'lit-element';\n\n// Define an element class\n export class MyGreedyLitElement extends LitElement {\n\n  // Define th
Well, the pattern suggested in the other thread will now match this test case.

2020-09-11 09:07 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
> +            "render\\(\\)[\\s]*\\{[\\s]*return[\\s]*html([\\`\\'\\\"])([\\s\\S]*)\\1;[\\s]*\\}");
I believe that would be the correct behavior, since the `render` method was missing a closing brace.

2020-09-11 09:21 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
> +
I find this more messy than having the same logic in a regex, to be honest.

2020-09-11 09:24 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
> +            "render\\(\\)[\\s]*\\{[\\s]*return[\\s]*html([\\`\\'\\\"])([\\s\\S]*)\\1;[\\s]*\\}");
done

2020-09-11 09:25 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
> +
The main messy thing is : absence of any specification how it should work/what's supported/what's not.

In fact: I don't know the result of this code, I'm just tired from it.

2020-09-11 10:01 UTC, joheriks approved these changes

2020-09-11 10:17 UTC, denis-anisimov commented
Implement lit template parser for limited template formats which extends LitTemplate element

Fixes #8966

2020-09-11 10:17 UTC, merged