Read template attributes as properties
vaadin/flow pull request #8988
Opened 2020-09-09 11:34 UTC by denis-anisimov

Fixes #8974

2020-09-11 13:28 UTC, joheriks requested changes

2020-09-11 13:28 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/component/template/internal/InjectableElementInitializer.java
> +        if (value.contains("{{") && value.contains("}}")) {
I got an NPE here when using the attribute-without-value syntax in my template. For example `autofocus`:
```html
<vaadin-text-field id="textField" autofocus></vaadin-text-field>
```

Also, how about about `${...}` in the attribute? For example:

```html
<vaadin-text-field id="textField" label="${this.dynamicLabel}"></vaadin-text-field>
```
Should it then also not be read to the server side?

2020-09-11 16:21 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/template/internal/InjectableElementInitializer.java
> +    private void initialize(Element element, String name, String value) {
Good point.

2020-09-11 16:27 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/template/internal/InjectableElementInitializer.java
> +        if (value.contains("{{") && value.contains("}}")) {
`label="${this.dynamicLabel}"` should not be read as it's dynamic.
But now again : how may I detect a dynamic values ?
Is `label="foo ${this.dynamicLabel}"` a correct declaration ?
Is check for `${` presence good enough ?

I considered only bindings as dynamic value and missed that .

2020-09-11 16:29 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/template/internal/InjectableElementInitializer.java
> +        if (value.contains("{{") && value.contains("}}")) {
There is an IT test for `hidden` attribute .

So stacktrace is required.

2020-09-13 13:22 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/component/template/internal/InjectableElementInitializer.java
> +        if (value.contains("{{") && value.contains("}}")) {
Probably attributes should only be parsed to server if they're string, int, float, etc. literals. So value containing `${` would need to be excluded.

With the following template in my app:
```javascript
class PolymerComponent extends PolymerElement {
  static get template() {
    return html`
        <vaadin-text-field id="textField" autofocus></vaadin-text-field>
    `;
  }

  static get is() {
    return 'polymer-component'
  }
}
```

I got the following exception when adding the component:

```
java.lang.IllegalArgumentException: Unable to create an instance of 'org.vaadin.example.MainView'. The constructor threw an exception.
	at com.vaadin.flow.internal.ReflectTools.createProxyInstance(ReflectTools.java:512)
	at com.vaadin.flow.internal.ReflectTools.createInstance(ReflectTools.java:449)
	at com.vaadin.flow.di.DefaultInstantiator.create(DefaultInstantiator.java:137)
	at com.vaadin.flow.di.DefaultInstantiator.getOrCreate(DefaultInstantiator.java:66)
	at com.vaadin.flow.di.Instantiator.createRouteTarget(Instantiator.java:190)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.lambda$getRouteTarget$1(AbstractNavigationStateRenderer.java:133)
	at java.base/java.util.Optional.orElseGet(Optional.java:362)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.getRouteTarget(AbstractNavigationStateRenderer.java:132)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.sendBeforeEnterEventAndPopulateChain(AbstractNavigationStateRenderer.java:485)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.createChainIfEmptyAndExecuteBeforeEnterNavigation(AbstractNavigationStateRenderer.java:466)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:204)
	at com.vaadin.flow.component.internal.JavaScriptNavigationStateRenderer.handle(JavaScriptNavigationStateRenderer.java:75)
	at com.vaadin.flow.component.internal.JavaScriptBootstrapUI.handleNavigation(JavaScriptBootstrapUI.java:289)
	at com.vaadin.flow.component.internal.JavaScriptBootstrapUI.renderViewForRoute(JavaScriptBootstrapUI.java:253)
	at com.vaadin.flow.component.internal.JavaScriptBootstrapUI.connectClient(JavaScriptBootstrapUI.java:127)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:200)
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:177)
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:137)
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.handleNode(PublishedServerEventHandlerRpcHandler.java:125)
	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:64)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:409)
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$1(ServerRpcHandler.java:390)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:390)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:317)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:114)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1539)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1363)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1278)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at com.vaadin.flow.internal.ReflectTools.createProxyInstance(ReflectTools.java:481)
	... 70 more
Caused by: java.lang.NullPo [...]

2020-09-14 06:03 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/template/internal/InjectableElementInitializer.java
> +        if (value.contains("{{") && value.contains("}}")) {
Values with `${` are excluded.

Will check the exception, thanks.

2020-09-14 06:31 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/template/internal/InjectableElementInitializer.java
> +        if (value.contains("{{") && value.contains("}}")) {
I'm not able to get any exception with the correct template: 

```
import {PolymerElement} from '@polymer/polymer/polymer-element.js';
import {html} from '@polymer/polymer/lib/utils/html-tag.js';

class PolymerComponent extends PolymerElement {
  static get template() {
    return html`
        <vaadin-text-field id="textField" autofocus></vaadin-text-field>
    `;
  }
  
  static get is() {
    return 'polymer-component';
  }
}
customElements.define('polymer-component', PolymerComponent);
```

Though `textField.isAutofocus()` returns `false` which is unexpected but this is a different issue.
I will try to see what can be done with this.

2020-09-14 06:37 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/template/internal/InjectableElementInitializer.java
> +        if (value.contains("{{") && value.contains("}}")) {
On the other hand , apparently the NPE is caused by the `null`  attribute value after Jsoup parsing which is never `null` for me.
I may assume it's related to Jsoup version.
But anyway the fix should be easy: just check `null`  value.

2020-09-14 06:44 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/component/template/internal/InjectableElementInitializer.java
> +        if (value.contains("{{") && value.contains("}}")) {
This template looks essentially the same as the one I posted above (I omitted the imports). I get the NPE also with this template I when I add the polymer component to a server-side component.

2020-09-14 07:23 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/template/internal/InjectableElementInitializer.java
> +        if (value.contains("{{") && value.contains("}}")) {
Both issues should be fixed now.

2020-09-14 07:38 UTC, joheriks approved these changes

2020-09-14 08:17 UTC, merged