--wip-- [skip ci] feat(offline): read @PWA to configure webpack build
vaadin/flow pull request #8993
Opened 2020-09-09 18:47 UTC by platosha

Fixes #8983

2020-09-11 10:53 UTC, fluorumlabs commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java
> +    private static Map<String, Map<String, Object>> annotationDefaults = new HashMap<>();
This is not thread-safe collection.
Also field could be made `final`

2020-09-11 10:53 UTC, fluorumlabs commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java
> +                            if (data.indexOf(info) < 0) {
Can be replaced with `!data.contains(info)`

2020-09-11 10:53 UTC, fluorumlabs commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java
> +     * @throws IOException
```suggestion
     * @throws UncheckedIOException
```

2020-09-11 10:53 UTC, fluorumlabs commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java
> +                public AnnotationVisitor visitArray(String name) {
All those anonymous visitors should be extracted into static inner classes

2020-09-11 10:53 UTC, fluorumlabs commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java
> +        return LoggerFactory.getLogger(this.getClass());
```suggestion
        return LoggerFactory.getLogger(FrontendAnnotatedClassVisitor.class);
```

2020-09-11 10:53 UTC, fluorumlabs commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
> +                offlineResources.toArray(new String[offlineResources.size()]));
Replace with an empty String[] array constant: preallocation is not needed since Java 6

2020-09-11 10:53 UTC, fluorumlabs commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
> +            return new PwaConfiguration(true, name, shortName, description,
`shortName` might be `null` here, `PwaConfiguration` constructor will throw NPE in that case

2020-09-11 11:21 UTC, fluorumlabs commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java
> +    private static Map<String, Map<String, Object>> annotationDefaults = new HashMap<>();
I have doubts about this static collection: SpringBoot dev tools can do a hot restart of Spring Application in certain cases (method signature changes, for example); in this case the collection contents will be retained.

2020-09-16 15:44 UTC, platosha commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java
> +    private static Map<String, Map<String, Object>> annotationDefaults = new HashMap<>();
Changed to `final` instance member. Thus it re-reads defaults upon every parent build task execution.

AFAIK this is a build step rather then runtime code. I wonder if thread-safety critical here. At least this change does not make it worse, since this is only used in `FrontendDependencies.java`, which has a bunch of HashMaps anyway.

Also, this only concerns framework-provided `@PWA` annotation default values. Would not expect those to change between hot reloads. Or am I wrong?

2020-09-16 15:56 UTC, platosha commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
> +            return new PwaConfiguration(true, name, shortName, description,
I don’t see how that’s possible in practice. `@PWA` annotation is found at this point, and seems like it must have `shortName` by definition. I’ve tried declaring `@PWA` with `shortName` null and absent, it does not compile.

Added an assert just in case to make dev tools happy though.

2020-09-17 06:07 UTC, fluorumlabs commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
> +            return new PwaConfiguration(true, name, shortName, description,
You are correct, `com.vaadin.flow.server.frontend.scanner.FullDependenciesScanner#getAnnotationValueAsString` confused me

2020-09-17 06:18 UTC, fluorumlabs commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java
> +    private static Map<String, Map<String, Object>> annotationDefaults = new HashMap<>();
In `FrontendDependencies` hashMaps are instance variables, so that's ok. 

I had a second look at the code, and realized that you can just use https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/Method.html#getDefaultValue() intead of invoking ASM :)

2020-09-17 10:58 UTC, fluorumlabs requested changes

2020-09-17 10:58 UTC, fluorumlabs commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java
> +    private Map<String, Object> readAnnotationDefaultValues(
Consider using `java.lang.reflect.Method#getDefaultValue` instead of ASM to collect default annotation values.

2020-09-18 12:36 UTC, Haprog requested changes
Looks mostly good to me, but found few minor issues.

2020-09-18 12:36 UTC, Haprog commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
> +                                ERROR_CAN_ONLY_HAVE_ONE_PWA_ANNOTATION);
The name of the error message constant `ERROR_CAN_ONLY_HAVE_ONE_PWA_ANNOTATION` seems counter intuitive in this case, though the actual value does mention both cases (`"There can only be one @PWA annotation and it must be set on the " + AppShellConfigurator.class.getSimpleName() + " implementor."`).

I'd consider renaming the constant as now it seems like it's only about the other case below.

My suggestion for a name: `ERROR_INVALID_PWA_ANNOTATION`.

(Not a blocker though)

2020-09-18 12:36 UTC, Haprog commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
> +import static com.vaadin.flow.server.frontend.FrontendUtils.DEAULT_FLOW_RESOURCES_FOLDER;
`DEAULT_FLOW_RESOURCES_FOLDER` (with typo) is now deprecated (since last rebase). Please use the corrected one:  
`DEFAULT_FLOW_RESOURCES_FOLDER` instead.

2020-09-18 12:36 UTC, Haprog commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
> +                        new File(userDir, DEAULT_FLOW_RESOURCES_FOLDER))
`DEAULT_FLOW_RESOURCES_FOLDER` (with typo) is now deprecated. Please use the corrected one:  
`DEFAULT_FLOW_RESOURCES_FOLDER` instead.

2020-09-21 20:20 UTC, haijian-vaadin approved these changes

2020-09-23 06:46 UTC, Haprog approved these changes

2020-09-23 11:33 UTC, merged