Deprecate Polymer Template related classes
vaadin/flow pull request #9025
Opened 2020-09-17 11:20 UTC by denis-anisimov

Fixes #8955

2020-09-18 09:42 UTC, pleku requested changes
For every deprecation message which is on a "public facing API" class, the part about 
"This will be removed in an upcoming version." should be removed.

Instead the deprecation message should say:
```
Polymer template support is deprecated - we recommend you to use {@link LitTemplate} instead. Read more details from <a href="https://vaadin.com/blog/future-of-html-templates-in-vaadin">the Vaadin blog.</a>" (edited)
```
The replacement message should probably be either before or after this, depending on the case ...

2020-09-18 09:42 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java
> + *             instead, polymer templates are deprecated. This will be removed
This message should instead be:

```java
Polymer template support is deprecated - we recommend you to use {@link LitTemplate} instead. Read more details from <a href="https://vaadin.com/blog/future-of-html-templates-in-vaadin">the Vaadin blog.</a>"
```

2020-09-18 10:32 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
>      private static Element tryParsePolymer2(Document templateDocument,
I believe it's not Polymer 2 but some polymer2 style which can be used for Polymer 3.
I don't remember exactly but anyway, this is not a part of this PR.

2020-09-21 06:32 UTC, pleku approved these changes
Good enough

2020-09-21 06:37 UTC, merged