Set `display:none` in addition to `hidden` attribute when hiding elements inside a shadow root
vaadin/flow pull request #9026
Opened 2020-09-17 20:42 UTC by joheriks

Fixes #8256.

2020-09-18 09:10 UTC, denis-anisimov requested changes
There are some GWT unit tests for visibility.

Please review them whether they need to be extended.
Some tests are for the visibility feature (bind/unbind) mostly.

But other tests are for hidden attribute behavior.

E.g. 
`testBindHiddenElement_stateNodeIsVisible_elementStaysHidden`
`testBindHiddenElement_stateNodeChangesVisibility_elementStaysHidden`,
`testBindNotHiddenElement_stateNodeChangesVisibility_elementIsNotHidden`, ....

2020-09-18 09:10 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeProperties.java
> +     * property to be able to restore when making a hidden element visible
Since there is a code which checks for shadow root would be good to mention it also here.

2020-09-18 09:10 UTC, denis-anisimov commented on flow-tests/test-root-context/frontend/lit/lit-template-inner.js
> +customElements.define('lit-template-inner', TemplateInner);
new line

2020-09-18 10:10 UTC, bogdanudrescu commented on flow-client/src/main/java/com/vaadin/client/PolymerUtils.java
> +     * Returns true iff the element has a shadow root ancestor.
double `f` type

2020-09-18 13:01 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeProperties.java
> +     * property to be able to restore when making a hidden element visible
Done.

2020-09-18 13:01 UTC, joheriks commented on flow-tests/test-root-context/frontend/lit/lit-template-inner.js
> +customElements.define('lit-template-inner', TemplateInner);
Done.

2020-09-18 13:01 UTC, joheriks commented on flow-client/src/main/java/com/vaadin/client/PolymerUtils.java
> +     * Returns true iff the element has a shadow root ancestor.
Spelled out.

2020-09-18 13:04 UTC, joheriks commented
> There are some GWT unit tests for visibility.
> 
> Please review them whether they need to be extended.
> Some tests are for the visibility feature (bind/unbind) mostly.
> 
> But other tests are for hidden attribute behavior.
> 
> E.g.
> `testBindHiddenElement_stateNodeIsVisible_elementStaysHidden`
> `testBindHiddenElement_stateNodeChangesVisibility_elementStaysHidden`,
> `testBindNotHiddenElement_stateNodeChangesVisibility_elementIsNotHidden`, ....

I added an additional assertion that `style={display:none}` is not added in existing tests checking attribute `hidden`. This  protects against regressions where it would be added unncessarily (for elements not in shadow root). Not sure how to set up a GWT test for the shadow root case.

2020-09-21 08:06 UTC, denis-anisimov requested changes

2020-09-21 08:06 UTC, denis-anisimov commented on flow-client/src/main/java/com/vaadin/client/PolymerUtils.java
> +    public static native boolean isInShadowRoot(Element element)
>I added an additional assertion that style={display:none} is not added in existing tests checking attribute hidden. This protects against regressions where it would be added unncessarily (for elements not in shadow root). Not sure how to set up a GWT test for the shadow root case.

I think we need more GWT tests for this.
It's possible to emulate code with shadow root with this code or change one.
You may create Elements hierarchy so that one element in the hierarchy returns '[object ShadowRoot]'.
Just fake it: create a fake `toString`  method and return this string from it.

Another way could be reimplement this method a bit so that it doesn't use `toString` but check whether an element has a parent whose `shadowRoot`  property is set to the element.
Then it's also possible to fake `shadowRoot`.

We have quite many tests like that which fakes elements.
See e.g. `GwtBasicElementBinderTest`: `initPolymer` , `addShadowRootElement`, etc.

With mocking/faking it should be possible to write the same tests for `display` style as we already have for `hidden`.

2020-09-21 12:08 UTC, joheriks commented on flow-client/src/main/java/com/vaadin/client/PolymerUtils.java
> +    public static native boolean isInShadowRoot(Element element)
Ok, thanks for the hints. Added two unit tests.

2020-09-22 07:57 UTC, denis-anisimov approved these changes

2020-09-22 07:57 UTC, merged