Force size re-estimate when requested range end equals assumed size
vaadin/flow pull request #9033
Opened 2020-09-18 12:42 UTC by mshabarov

Since the `Range` is exclusive at the end, it may happen that the range end is the same as the assumed size. It that case the `flush()` would not be invoked, although it should. Requested range strategy generally speaking depends on web component and there may be the case when the component requests, for example [5700...5800] and the assumed size is already 5800. This situation reflects the case when the user scroll to the end and then he jumps to undefined size. Then it should force the size re-estimation. And thus this code change occurred.

2020-09-21 09:09 UTC, pleku requested changes

2020-09-21 09:09 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +            if (requestedRange.contains(assumedSize - 1)) {
Good catch but where is the unit test ?

2020-09-22 06:07 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +            if (requestedRange.contains(assumedSize - 1)) {
Unit test added

2020-09-22 08:49 UTC, pleku requested changes

2020-09-22 08:49 UTC, pleku commented on flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
> +        dataCommunicator.setDataProvider(createDataProvider(), null);
Could have been nice to add a comment here that states that `// the size will be 100` so it makes it very clear how this test works

2020-09-22 08:49 UTC, pleku commented on flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
> +        Mockito.verify(stateNode).runWhenAttached(Mockito.anyObject());
Like (most?) other tests here, shouldn't this very that the (estimated) count is increased properly too (which is the desired outcome in terms of internal DC logic) instead of just relying that call to flush has been done ?

2020-09-23 14:53 UTC, mshabarov commented on flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
> +        dataCommunicator.setDataProvider(createDataProvider(), null);
Done

2020-09-23 14:53 UTC, mshabarov commented on flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
> +        Mockito.verify(stateNode).runWhenAttached(Mockito.anyObject());
Done

2020-09-24 05:39 UTC, pleku approved these changes

2020-09-24 05:40 UTC, merged