Clear routes.
vaadin/flow pull request #9050
Opened 2020-09-22 09:23 UTC by bogdanudrescu

Fixes https://github.com/vaadin/flow/issues/8433

2020-09-22 10:42 UTC, caalador requested changes

2020-09-22 10:42 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/router/internal/ConfigureRoutesTest.java
> +            Assert.fail("Route is already registered");
Failing should be due to route not registered yet as the exception is thrown for non unique route registration.

Also what does this actually test as the assert routes check that the route has been registered?
I would remove this part as it doesn't bring anything that is expected.

2020-09-22 10:42 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/router/internal/ConfigureRoutesTest.java
> +            Assert.fail("Route is already registered");
Also remove this set as it doesn't bring anything that is not tested in assertSetRoutes.

2020-09-23 06:53 UTC, bogdanudrescu commented on flow-server/src/test/java/com/vaadin/flow/router/internal/ConfigureRoutesTest.java
> +            Assert.fail("Route is already registered");
We can remove this of course. I'd like though to keep it because that exception was somehow causing the bug itself, and the purpose of having it in the test is to make sure that the exception is raised for a duplicate route while after `clear` it doesn't. I can put this details in the code.

2020-09-23 06:53 UTC, bogdanudrescu commented on flow-server/src/test/java/com/vaadin/flow/router/internal/ConfigureRoutesTest.java
> +            Assert.fail("Route is already registered");
Same as above.

2020-09-23 06:59 UTC, bogdanudrescu commented on flow-server/src/test/java/com/vaadin/flow/router/internal/ConfigureRoutesTest.java
> +            Assert.fail("Route is already registered");
I've added the details in the code. Let me know please if you agree with this.

2020-09-23 07:06 UTC, caalador requested changes

2020-09-23 07:06 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/router/internal/ConfigureRoutesTest.java
> +            Assert.fail("Route is already registered");
I would rather have these as their own tests e.g. duplicateRootPathRegistration_throwsException and duplicateParameterPathRegistration_throwsException. as then it's clear what is the expected outcome and having a test fail makes it clear. now it would seem that clearing routed doesn't work even if this wouldn't be the case.

2020-09-23 07:22 UTC, bogdanudrescu commented on flow-server/src/test/java/com/vaadin/flow/router/internal/ConfigureRoutesTest.java
> +            Assert.fail("Route is already registered");
Done. Thank you!

2020-09-23 07:31 UTC, caalador requested changes

2020-09-23 07:31 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/router/internal/ConfigureRoutesTest.java
> +            mutable.setRoute(":param", ParamTarget.class);
Instead of the try catch you a better choice would be to add as a common parameter
```
    @Rule
    public ExpectedException exception = ExpectedException.none();
```
and in the tests expecting exception have:
```
        exceptionRule.expect(InvalidRouteConfigurationException.class);
        exceptionRule.reportMissingExceptionWithMessage("Duplicate routes shouldn't be accepted.");
```

2020-09-23 07:40 UTC, bogdanudrescu commented on flow-server/src/test/java/com/vaadin/flow/router/internal/ConfigureRoutesTest.java
> +            mutable.setRoute(":param", ParamTarget.class);
But if doing this, how can we test on what line it was thrown from? Isn't this an expectation over the whole method just like `@Test(expected = InvalidRouteConfigurationException.class)`?

2020-09-23 07:52 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/router/internal/ConfigureRoutesTest.java
> +            mutable.setRoute(":param", ParamTarget.class);
exceptionRule gives more possibilities than the expected, for instance the message that should be found
 `exceptionRule.expectMessage("Navigation targets must have unique routes, found navigation targets 'ParamTarget' and 'ParamTarget' with the same route.");` which would be good to check perhaps to see it fails for the correct version.


Also the cause can be checked with `exceptionRule.expectCause(CoreMatchers.isA(TheCauseClassWeWouldExpect.class))`

Also shouldn't the correct exception be `AmbiguousRouteConfigurationException` and not `InvalidRouteConfiguratioException`?

2020-09-23 08:09 UTC, bogdanudrescu commented on flow-server/src/test/java/com/vaadin/flow/router/internal/ConfigureRoutesTest.java
> +            mutable.setRoute(":param", ParamTarget.class);
Thank you. Please see if it's OK.

2020-09-23 08:13 UTC, caalador approved these changes

2020-09-23 09:17 UTC, joheriks approved these changes

2020-09-23 09:32 UTC, merged