Skip data provider verification in AbstractDataView if default one is used
vaadin/flow pull request #9052
Opened 2020-09-23 08:53 UTC by mshabarov

Fixes #8583

2020-09-23 09:48 UTC, pleku requested changes
Small nits

2020-09-23 09:48 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +    static final class EmptyDataProvider<T1> extends ListDataProvider<T1> {
This should be before instance variables, and any static variables too

2020-09-23 09:48 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +     * for instance), even if no backend data provider set by user.
NIT: it feels like this is documented now in two places, abstract data view and here, IMO this is a bit excessive and one would have sufficed with a comment `// see xyz` for the other place

2020-09-23 09:48 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
> +         * provider has been set.
This documentation (and the other duplicate in the empty data provider) is missing the part that in-memory data view API is supported without explicitly setting the data provider. Since you're documenting the usage, might add that too

2020-09-24 09:54 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +    static final class EmptyDataProvider<T1> extends ListDataProvider<T1> {
I would better place it just before `SizeVerifier` declaration and after the instance variables, because IMO inner class declaration on the top of outer class decrease the readability, and I couldn't find the recommendations to place inner classes on the top (before variables declaration).

2020-09-24 10:35 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +     * for instance), even if no backend data provider set by user.
Done

2020-09-24 10:44 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
> +         * provider has been set.
Done

2020-09-29 04:49 UTC, mshabarov commented
I've changed the EmptyDataProvider access modifier to public so that it can be used in components.

2020-09-29 10:46 UTC, pleku approved these changes

2020-09-29 10:50 UTC, merged