Update javadoc of rerouteTo()/forwardTo()
vaadin/flow pull request #9060
Opened 2020-09-24 06:36 UTC by mvysny

Update javadoc of rerouteTo()/forwardTo() to clear out the difference between the two

2020-09-24 06:37 UTC, mvysny commented
Also see https://github.com/vaadin/flow-and-components-documentation/issues/1355

2020-09-25 06:53 UTC, bogdanudrescu requested changes
This is a nice update, thank you!

2020-09-25 06:53 UTC, bogdanudrescu commented on flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
>       *            reroute target location string
It would be good to replace word `reroute` to `forward` for consistency.

2020-09-25 06:53 UTC, bogdanudrescu commented on flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
>       *            reroute target location string
Same here `reroute` can be changed to `forward`.

2020-09-30 07:20 UTC, bogdanudrescu approved these changes

2020-09-30 07:20 UTC, merged