Add data communicator API for disabling data provider interactions
vaadin/flow pull request #9070
Opened 2020-09-28 18:12 UTC by mshabarov

2020-09-29 06:41 UTC, pleku requested changes
I think the implementation is done in a way that it will leak to the users (when using e.g. data view API) and causes errors that can confuse them. It should be basically about the component to be able to "delay" the first fetch to a certain point, but not cause errors for users.

2020-09-29 06:41 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +            this.skipCountIncreaseUntilReset = false;
Unrelated unnecessary changes

2020-09-29 06:41 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +        this.definedSize = false;
Unrelated unnecessary change (yes the `this.` for countCallback is unnecessary too)

2020-09-29 06:41 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +            if (fetchDisabled) {
Why should this be blocked ??? Since this API is not directly exposed to users, like it should not, it feels weird to me that for some components I can do
```java
Component listing = createListing();
listing.setItems(query -> getStuff(query));
listing.getItem(0);
```
but not for all. So for Grid this would work and not for combobox (I guess) ??? That is confusing.

2020-09-29 06:41 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +        if (fetchDisabled) {
Again, it would be weird for a data view API user that the same things work for another component, but not for another.

2020-09-29 13:28 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +            this.skipCountIncreaseUntilReset = false;
Reverted

2020-09-29 13:28 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +        this.definedSize = false;
Reverted

2020-09-29 13:29 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +            if (fetchDisabled) {
Excluded

2020-09-29 13:29 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
> +        if (fetchDisabled) {
Excluded

2020-09-29 13:34 UTC, mshabarov commented
> I think the implementation is done in a way that it will leak to the users (when using e.g. data view API) and causes errors that can confuse them. It should be basically about the component to be able to "delay" the first fetch to a certain point, but not cause errors for users.

I was thinking whether it's better to use the data communicator as a listener for 'switch to normal mode', but I think it is a over-complication and basically limited to 1 component so far, so I simply left it as it is (CTOR arg + getter and setter). Curious users could of course try them randomly, but I have no elegant protection for that.

2020-09-29 18:22 UTC, pleku requested changes
It seems to me this PR has more unnecessary white space changes than the actual changes. I will not review it as such as it wastes my time

2020-09-29 18:24 UTC, pleku commented
https://www.jetbrains.com/help/idea/reformat-file-dialog.html

2020-09-30 07:40 UTC, pleku approved these changes

2020-09-30 07:44 UTC, merged