fix: fail access check when no csrf token in session
vaadin/flow pull request #9072
Opened 2020-09-28 23:05 UTC by haijian-vaadin

2020-09-29 12:52 UTC, platosha requested changes

2020-09-29 12:52 UTC, platosha commented on flow-server/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
> +            return csrfTokenInHeader != null;
This fails requests with a token header when there is no session. Any reasons behind it?

IMO it would read more logical if in case of empty session we return early before checking the header:

```java
HttpSession session = request.getSession(false);
if (session == null) {
  return false;
}

String csrfToken = (String) request.getSession();
return csrfToken == null || !csrfToken.equals(request.getHeader("X-CSRF-Token"));
```

2020-09-29 13:00 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
> +            return csrfTokenInHeader != null;
> This fails requests with a token header when there is no session. Any reasons behind it?
Isn't this exactly the case that the session has expired, and a cached request is being submitted (with an outdated csrf token)?

it could be fine when there is no csrf token in the request header, e.g. using curl.

2020-09-30 07:11 UTC, platosha commented on flow-server/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
> +            return csrfTokenInHeader != null;
If the session has expired, it should fail elsewhere in `isLoggedIn` kind of check.

2020-09-30 13:04 UTC, platosha approved these changes

2020-09-30 13:51 UTC, merged