Fix router link with shadow dom.
vaadin/flow pull request #9080
Opened 2020-09-30 08:26 UTC by bogdanudrescu

Fixes https://github.com/vaadin/flow/issues/3697

2020-09-30 08:27 UTC, bogdanudrescu commented
@pleku I'm not sure about `target/1.0` label, but I think that's where the bug was reported.

2020-09-30 09:12 UTC, caalador requested changes

2020-09-30 09:12 UTC, caalador commented on flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterLinkIT.java
> +        testInsideServlet(findElement(By.id("router-link-with-shadow-green")),
How does this not fail? At the step before we navigate away from the test view and the view should now be Shadow where we do not have other elements apart from the `<h1>shadow</h1>` .

This should be in it's own test case `customElementWithShadowRoot_clickLightDomSlottedElement_navigatedToShadowRoute` or the like.

2020-09-30 09:20 UTC, bogdanudrescu commented on flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterLinkIT.java
> +        testInsideServlet(findElement(By.id("router-link-with-shadow-green")),
I don't know how it's not failing, I didn't investigated that, but it doesn't, it behaves like all the other router links in the test. The text, without `<h1>` is embedded in the `<div id="location">`.

When testing without the change, a browser navigation will be triggered when clicking on the red div inside the shadow and it does navigate to another page, but still not from the green one.

2020-09-30 10:32 UTC, caalador commented on flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterLinkIT.java
> +        testInsideServlet(findElement(By.id("router-link-with-shadow-green")),
Really? At least not when actually running in the browser and clicking the links. 
That would explain why the test works with the second validation, but it could still be its own test case.

This is again one of the stranger tests.

2020-10-26 09:34 UTC, caalador submitted a review, later dismissed

2021-05-03 11:11 UTC, pleku commented
Apparently this is not even a problem in e.g. https://labs.vaadin.com/business/payments and as the changeset is cannot be accepted as is, closing the PR.

2021-05-03 11:11 UTC, closed without merging