chore: Fix tests for windows execution
vaadin/flow pull request #9129
Opened 2020-10-07 11:12 UTC by caalador

Fix tests so they work also on windows.
Remove Polymer dependency form the test
root and only have it in packages actually
utilizing Polymer.

2020-10-08 11:54 UTC, pleku requested changes

2020-10-08 11:54 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +        if(frontendDir.endsWith("/")) {
To be honest, I don't even get how this helps - is it not going through the file system ? Maybe a clarifying comment so someone doesn't "fix this" again

2020-10-09 05:21 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +        if(frontendDir.endsWith("/")) {
I actually fixed this now in the test expectation.
The problem is ofc that for instance the deafult frontendDir is `./frontend/`
which will not match the windows file separator and thus is will become `./frontend/\index.html`
This looks strange, but as it's only an exception the work to handle the path correctly would be wasted.

2020-10-09 10:10 UTC, pleku approved these changes

2020-10-09 10:11 UTC, merged