fix: store app shell title into UI instead of AppShellRegistry
vaadin/flow pull request #9133
Opened 2020-10-07 19:53 UTC by haijian-vaadin

The app shell title is currently stored in `AppShellRegistry` which makes it a singleton. The fix is to store it into `UI` instead.

- Normally the app shell title is passed from client to server via`flowRoot.$server.connectClient(this.container.localName, this.container.id, this.getFlowRoute(ctx), document.title);` in `Flow.ts`
- When `eagerServerLoad` is set, the app shell title is passed via `IndexHtmlHandler`, since the UI is already available then.

2020-10-08 08:01 UTC, platosha approved these changes

2020-10-08 08:04 UTC, platosha requested changes

2020-10-08 08:04 UTC, platosha commented on flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
> -    public String getTitle() {
Note: this is technically a breaking change now that `AppShellRegistry#getTitle()` is removed.

Should we deprecate it instead for now?

2020-10-08 09:56 UTC, Haprog commented on flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
> -    public String getTitle() {
I'm not sure. If we deprecate it, do we also need to keep/add logic so it returns what it used to?

I guess it would be good to have deprecation before removal, but I'm not sure if it's ok to just remove in this case.

2020-10-08 10:02 UTC, Haprog commented on flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
> -    public String getTitle() {
For backporting the fix we probably should not remove it though.

2020-10-08 11:11 UTC, Artur- commented
Isn't UI the wrong scope for this, just as AppShellRegistry? I page title is tied to a browser tab or a view. A UI instance is shared among many browser tabs. Also if you have a TS only app, you should not have any UI instance at all

2020-10-08 11:30 UTC, haijian-vaadin commented
> If you have a TS only app, you should not have any UI instance at all
The purpose of storing this app title into UI is that when navigating to a server-side view that doesn't have a title, then the app title could be used as a fallback one.
If you have a TS only app, then the title is not stored/used.

2020-10-08 11:52 UTC, Artur- commented
What is an "app title"? What is the "app title" if you navigate from a server side view to a server side view without a title? What is the "app title" if you directly navigate to a server side view without a title?

2020-10-08 12:32 UTC, pleku commented
> What is an "app title"?

"App title" is what is referred to here as the title set via the `AppShell` or `AppShellConfigurator`.

> What is the "app title" if you navigate from a server side view to a server side view without a title?

The title will be either the "app title" or if there is none set, the title is cleared to leave the browser to decide what is shown.
So if the previous server side view had a specific title like "Login", that would always change when the user navigates away from it. Either to 1) new specific view title 2) app title 3) cleared completely.

That is how it is intended to work, though there is no design for this (?) in any older issue. Not at least in the one that introduced the current issue.

2020-10-08 12:36 UTC, haijian-vaadin commented
> What is an "app title"? What is the "app title" if you navigate from a server side view to a server side view without a title? What is the "app title" if you directly navigate to a server side view without a title?
"app title" means the value of the <title> tag in the bootstrap page. However you navigate to a server-side view without a title, the <title> tag in the bootstrap page would be used.

2020-10-08 12:36 UTC, pleku requested changes

2020-10-08 12:36 UTC, pleku commented on flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
> +          .connectClient(this.container.localName, this.container.id, this.getFlowRoute(ctx), document.title);
Isn't this too late ? If a client side view sets another title instead of the one provided by the `AppShell` from Java, then that title would be set as the "app title" instead ? So basically the `document.title` should be captured somewhere after the initial index page with the appshell provided title comes (like I said yesterday in the call). Or what am I missing ?

2020-10-08 18:53 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
> -    public String getTitle() {
Yep, good point, marked it as `@Deprecated` now

2020-10-08 18:55 UTC, haijian-vaadin commented on flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
> +          .connectClient(this.container.localName, this.container.id, this.getFlowRoute(ctx), document.title);
very good catch, sorry that I forgot about it while implementing.

2020-10-09 09:03 UTC, pleku requested changes

2020-10-09 09:03 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +        if(UI.getCurrent()!=null){
a) Isn't this always `null` unless the legacy bootstrapping is used ? If the code calling this method cannot be moved inside the if-else that checks that checks the bootstrapping mode, a comment could point here that "this is only for the legacy bootstrapping"
b) IMO `UI.getCurrent().ifPresent(ui -> ...` would be cleaner code
c) this code is not formatted

2020-10-09 09:03 UTC, pleku commented on flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
> +    this.appShellTitle = document.title;
This code / feature is not tested anyway, so it can be accidentally removed and nobody will notice the regression before a user reports it. So an IT should be IMO added

2020-10-09 10:18 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
> -    public String getTitle() {
This PR should be cherry-picked to 4.0, so I think maybe we keep it as Deprecated in this PR, so we can cherry-pick as is to 4.0, then make another PR in master to remove it.
I will update the PR to throw an exception instead.

2020-10-09 10:19 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
> +        if(UI.getCurrent()!=null){
It's also won't be null when [eagerServerLoad](https://github.com/vaadin/flow/blob/2fa75ddc88cdb719daaceb8ef21478b9acb43c37/flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java#L372) is configured.

I will update the code for other suggestions.

2020-10-09 10:19 UTC, haijian-vaadin commented on flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
> +    this.appShellTitle = document.title;
Good point, will add one

2020-10-09 11:27 UTC, pleku approved these changes

2020-10-09 11:31 UTC, pleku commented on flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/NavigateToServerSideViewWithoutTitleIT.java
> +        findElement(By.id("updatePageTitle")).click();
Slightly nit picking and thus not blocking: could verify that the title has been changed here in the middle, since if it for some reason would not be changed from the initial, then this test would not add anything extra to the previous test

2020-10-09 13:27 UTC, pleku approved these changes

2020-10-09 15:31 UTC, platosha approved these changes

2020-10-09 15:32 UTC, merged