Rename “Connect” to “Fusion”
vaadin/flow pull request #9151
Opened 2020-10-09 06:51 UTC by jouni

Didn’t touch the package names, as I have no idea of all the places where those should be changed. Just updated the strings that I believe are more visible for users.

2020-10-09 07:06 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiSpecGenerator.java
> +    public static final String DEFAULT_APPLICATION_TITLE = "Vaadin Fusion Application";
This should be "Vaadin Application"

2020-10-09 07:06 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiSpecGenerator.java
> +    public static final String DEFAULT_SERVER_DESCRIPTION = "Vaadin Fusion backend";
Not sure where this is used but why point out "Fusion" at all?

2020-10-09 07:07 UTC, Artur- commented on flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiSpecGenerator.java
> +                log.info("There are no Fusion endpoints to generate.");
Same here, why use "Fusion endpoints" instead of "endpoints"?

2020-10-09 07:15 UTC, jouni commented on flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiSpecGenerator.java
> +    public static final String DEFAULT_APPLICATION_TITLE = "Vaadin Fusion Application";
Sure, no argument from me. I hope someone else makes that decision. I mainly opened this PR to trigger this type of discussion, and so that we don’t forget to update these.

2020-11-23 10:38 UTC, joheriks requested changes
These mentions of "Vaadin Connect" could also be changed:
```
$ grep -r -w "Connect" flow-server/src/main/java 
<irrelevant hits removed>
flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectClientGenerator.java: * Generates the Vaadin Connect Client file, based on the application
flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java:     * Prepends the Connect prefix URL from the Vaadin Connect properties to
flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java:     * @return a new mapping with the Connect prefix URL prepended to the
```

2020-11-23 11:32 UTC, haijian-vaadin commented
> These mentions of "Connect" could also be changed:
> 
> ```
> $ grep -r -w "Connect" flow-server/src/main/java 
> <irrelevant hits removed>
> flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectClientGenerator.java: * Generates the Vaadin Connect Client file, based on the application
> flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java:     * Prepends the Connect prefix URL from the Vaadin Connect properties to
> flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java:     * @return a new mapping with the Connect prefix URL prepended to the
> ```

Good catch, done. Have to use connect-client for the first one, since the file name is still like that.

2020-11-23 13:32 UTC, joheriks approved these changes

2020-11-23 16:59 UTC, merged