feat: add support for Range header to StaticFileServer
vaadin/flow pull request #9154
Opened 2020-10-09 14:02 UTC by joheriks

A Range header can specify either a single byte range, e.g. `Range: bytes=0-100`, or multiple ranges,
e.g. `Range: bytes=0-99, 200-299`. The ranges do not need to be sequential and can have overlap;
e.g. `Range: bytes=200-299, 0-99` is valid; such requests will open a new stream reading from the
beginning of the file for each out-of-order range. The motivation for this feature is to support video
playback on Safari.

Fixes #9083

2020-10-12 08:54 UTC, caalador requested changes

2020-10-12 08:54 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
> +                dataStream.skip(start);
Could have an assert on the skipped bytes that we skipped the expected amount.

2020-10-12 08:54 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
> +        // multipart range: use chunked transfer mode because calculating
I would like for this to be in its own method `writeMultipartRangeContent`
Also would like a Javadoc header explaining what the specification used for the chunked mode is so that it can bee looked up when/if needed.

2020-10-12 08:54 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
> +                        String.format("\r\n--%s\r\n", boundary).getBytes());
`chunkBoundary` would give a bit more information on what the `boundary` is about.

2020-10-12 11:40 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
> +        // multipart range: use chunked transfer mode because calculating
Done.

2020-10-12 11:43 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
> +                        String.format("\r\n--%s\r\n", boundary).getBytes());
Renamed to `partBoundary` as I believe technically these boundary-separated things are "parts", whereas "chunks" are a byte-level feature which is handled transparently by the servlet container.

2020-10-12 11:43 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
> +                dataStream.skip(start);
Done.

2020-10-12 11:43 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
> +    private void closeStreamAndLogFailure(Closeable stream) {
Done.

2020-10-12 11:48 UTC, caalador approved these changes

2020-10-12 13:58 UTC, merged

2020-11-10 08:54 UTC, kPlock commented
Hello, 
Chromium is not as stringent as Safari in the range specifications.
You could also include the "full"-Ranges in the RANGE_HEADER_PATTERN pattern.
**Range: bytes=0-
Range: bytes=-99**
are also  valid range specifications.

2020-11-10 14:26 UTC, TGit911iger commented
Please look at comment from user kplock. I have got the same problem. Videos are working in Safari. Videos are not working withe Chrome, Firefox and Edge Chromium.

2020-11-10 17:17 UTC, joheriks commented
Fixed by #9368.