fix: only register endpoint request handler when endpoint presents
vaadin/flow pull request #9172
Opened 2020-10-14 06:53 UTC by haijian-vaadin

Fixes https://github.com/vaadin/flow/issues/9005

2020-10-14 11:38 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
> +@ConditionalOnProperty(value = VAADIN_ENDPINT_ENABLED, havingValue = "true")
Just a question; would it be better to use Custom Conditional to only activate the controller if the `@Endpoint` annotation is used? Or is this over-engineered because you guys think about removing spring? https://reflectoring.io/spring-boot-conditionals/#custom-conditions

2020-10-14 11:59 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
> +@ConditionalOnProperty(value = VAADIN_ENDPINT_ENABLED, havingValue = "true")
Hi @knoobie, thanks for the comment. I was also thinking about using a Custom Condition in the beginning, but then realized that we are already scanning the Endpoints at build time, so we can just reuse that instead of having another check in a custom condition.

Also for an extreme case, if there is only one class that has `@Endpoint` annotation, but without any public methods, then the annotation scanning-based custom condition would still active the Vaadin controller while the solution in this PR won't.

Another big reason is what you mentioned, we might remove the spring dependency in the future, so the check won't be necessary, thus like to have a minimal effort solution.

2020-10-16 11:03 UTC, joheriks requested changes

2020-10-16 11:03 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/Constants.java
> +    public static final String VAADIN_ENDPINT_ENABLED = "endpoint.enabled";
```suggestion
    public static final String VAADIN_ENDPOINT_ENABLED = "endpoint.enabled";
```
There's a typo in the constant. BTW, should it be a public constant (from API maintenance point of view this means it can't easily be removed or renamed later) or could it be put inside `com.vaadin.flow.server.connect` (e.g., within an `internal` package)?

2020-10-16 11:21 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/Constants.java
> +    public static final String VAADIN_ENDPINT_ENABLED = "endpoint.enabled";
Very good point, instead of create a new internal package inside `connect`, I reused a flow internal package and added a new InternalConstants, please help to take another look

2020-10-16 11:59 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/Constants.java
> +    public static final String VAADIN_ENDPINT_ENABLED = "endpoint.enabled";
👍. Looks like the imports may need updating.

2020-10-16 12:03 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/Constants.java
> +    public static final String VAADIN_ENDPINT_ENABLED = "endpoint.enabled";
Good spot, thanks. Thought VS Code would have done that automatically for me.

2020-10-16 12:28 UTC, joheriks approved these changes

2020-10-16 13:23 UTC, joheriks approved these changes

2020-10-16 16:44 UTC, merged