--wip-- fix(offline): support offlinePath from PWA annotation [skip ci]
vaadin/flow pull request #9181
Opened 2020-10-15 07:28 UTC by platosha

Fixes #8856

2020-10-21 20:17 UTC, haijian-vaadin requested changes
Few findings:
1. the second point of DoD in the ticket seems is not taken into consideration. i.e. 

> same as above, but instead of using a custom offlinePath property, the app has customized content in the default offline.html file path -> the presence of the offline.html resource is detected and when the app is offline, the content of offline.html is rendered instead the app shell

2. in a v17 Spring app, the `offlinePath` is relative to `src/main/resources/META-INF/resources`, in our offline branch, it's relative to `src/main/webapp`, but maybe this is in the scope of #8996.

2020-10-27 13:46 UTC, haijian-vaadin submitted a review, later dismissed
Let's merge this one, have a new ticket regarding `customized content in the default offline.html file path`

2020-10-27 20:07 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/PWA.java
> +     * offline.
Is that actually correct? I tested `@PWA(offlinePath="notexisting.html)` where `notexisting.html` is not served by the app and the browser replied `This site can’t be reached` rather than falling back to the appshell.

2020-10-28 10:08 UTC, Haprog approved these changes
Looks good.

2020-10-28 10:50 UTC, merged