Read token file and stats.json file as bundle resources instead of Classpath resources
vaadin/flow pull request #9187
Opened 2020-10-15 09:41 UTC by denis-anisimov

Fixes #9146

2020-10-15 10:06 UTC, caalador requested changes

2020-10-15 10:06 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
> -    private static boolean isProductionMode(Properties initParameters) {
Why is the method removed?

2020-10-15 10:06 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +            return streamToString(getStatsFromWebpack());
We don't want the stats.json form webpack we just want to know the asset chunks. This shouldn't be reverted as it's 4-8 lines of text against 4-18 megabytes of text. Also the returned content is not what is expected from the method.

2020-10-15 10:08 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
> -    private static boolean isProductionMode(Properties initParameters) {
It's not used from anywhere.

2020-10-15 10:09 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
> +            }
Is it dropped ?
There was no any intention to drop anything.
The code should just first try to get resource from OSGi and if it's there then nothing else should be executed.
Otherwise the logic should be the same.
I will check...

2020-10-15 10:10 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +            return streamToString(getStatsFromWebpack());
Ah, my bad.
I thought the code is identical. Didn't notice that the resource path is different.
I will correct this , thanks.

2020-10-15 10:13 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
> +            }
The code looks the same....
Am I missing something ?

Should I mention that in OSGi `Collections.list(DeploymentConfiguration.class.getClassLoader().getResources(tokenResource))` will never return anything ? This code just has no sense.

2020-10-15 10:38 UTC, caalador approved these changes
Should the compatibility mode override be dropped as we are adding stats and token support?

2020-10-15 10:38 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
> +            }
No  it's not missing anything now that I squint and ignore the red green dance on the screen. it does use the resource if found. 
The offset between changes makes this really hard to read.

2020-10-15 10:38 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
> -    private static boolean isProductionMode(Properties initParameters) {
All un-used methods should perhaps be removed in one PR where every one of those would be gone through. Github comparison doesn't handle this changeset too well and the extra removed method makes this a bit complicated to read.

2020-10-15 10:38 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> -    private static String getNonNull(String... valueArray) {
Same as with isProductionMode. This makes one take 2 and search for where the usage was removed as it's not applicable to the change set.

2020-10-15 12:18 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> -    private static String getNonNull(String... valueArray) {
Generally I agree that this is out of scope of the PR but in practice this would have never been removed
and this is a feature branch.
I'm not sure whether this PR should be even merged : should the branch be used to proceed OSGi feature development.

So I won't merge this for now. The PR gives me a way to verify the code.

2020-10-16 08:43 UTC, pleku reviewed
One question.

Also it seems that having osgi-related code in `FrontendUtils` and `DeploymentConfigurationFactory` (very little in latter) is a bit of an code smell. No need to do anything for now, but I think overall it would be great if we structure the OSGi code somehow as something that is just plugged in as an "alternative implementation" when OSGi is used, instead that it is spread all over the code to handle certain things in an OSGi way. It is just something to think about

2020-10-16 08:43 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +            return getOSGiUrl(servlet.getClass(), path);
Stupid question as I'm probably missing something, but:
How is this supposed to work when here the `VaadinServlet.class` is passed here and then on lines 590-591 both `getBundle` calls get the bundle for `VaadinServlet.class`, and which should result in the same bundle and then throw ISE next ? Or is the `getClass()` returning here something else ?

2020-10-16 08:50 UTC, denis-anisimov commented
> One question.
> 
> Also it seems that having osgi-related code in `FrontendUtils` and `DeploymentConfigurationFactory` (very little in latter) is a bit of a code smell. No need to do anything for now, but I think overall it would be great if we structure the OSGi code somehow as something that is just plugged in as an "alternative implementation" when OSGi is used, instead that it is spread all over the code to handle certain things in an OSGi way. It is just something to think about

I totally agree.
Already thought about this and created a ticket : https://github.com/vaadin/flow/issues/9185 as a first step.
Then we should have our internal service interface to get resources with two impl: for plain WAR and for OSGi

2020-10-16 08:55 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +            return getOSGiUrl(servlet.getClass(), path);
This code is exactly to catch `VaadinServlet` case which is currently never used in OSGi directly (and in fact is not supposed to be used).
There will be an issue which needs to be resolved once we implement servlet auto registration.
I'm pretty sure there will be an OSGi specific servlet (not `VaadinServlet` but something extending it).
I can't answer to the question how we are going to pass the WAB bundle as a context here.
This can be solved in various ways: using the specific OSGi capable servlet which has to be instantiated with a Bundle provided (so then it may be fetched from the servlet instance) or via passing parameter via `Dictionary` at the servlet registration phase.
Not sure which way is better and may be there will be a third way.
But anyway: this is something for the future, for the automatic servlet registration issue.

2020-11-02 14:20 UTC, pleku requested changes

2020-11-02 14:20 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/startup/ClassLoaderAwareServletContainerInitializer.java
> +            synchronized (context) {
Should this be synchronized for `context` or for `vaadinContext` ?
Why is this synchronized ? `vaadinContext.getAttribute(...)` does synchronization so couldn't this be actually simplified by just delegating to that by only having instead of the if-attribute-is-null-check like:
```java
 DeferredServletContextInitializers initializers = vaadinContext
                            .getAttribute(DeferredServletContextInitializers.class,
                                    () -> new DeferredServletContextInitializers());
```

2020-11-02 14:20 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/startup/ClassLoaderAwareServletContainerInitializer.java
> +        DeferredServletContextInitializers.Initializer deferredInitializer = ctx -> {
I would introduce a comment here on why is this deferred, maybe just // see DeferredServletContextIntializers

2020-11-02 14:20 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/startup/DeferredServletContextInitializers.java
> + * {@link LookupInitializer} completed.
Why are these needed (answer in javadocs)

2020-11-02 14:20 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/startup/DeferredServletContextInitializers.java
> +    interface Initializer {
Missing javadocs

2020-11-02 14:20 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/osgi/OSGiAccess.java
> +                    .getServiceReference(serviceClass);
Why is the referenced bundle here `OSGiAccess` but below in `lookupAll` it is `LookupInitializer.class` instead ? Shouldn't it be changed to `OSGiAccess` too  ?

2020-11-03 05:52 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/di/Lookup.java
> +     * Lookup for a service by the provided {@code serviceClass}.
Will be tricky journey since I have to fix the things in the separate PR for this branch....

2020-11-03 05:56 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/di/Lookup.java
> + * singleton services.
I think I don't understand this.

Is it about how you may provide a service impl which will be available in the lookup ?

2020-11-03 06:15 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/ClassLoaderAwareServletContainerInitializer.java
> +            synchronized (context) {
Synchronization on `vaadinContext` has no any sense since it's just a facade. There may be many `VaadinContext` instances which delegates to the same `ServletContext` instance.
This will work only if other code also synchronizes on the same monitor. And now I've found an issue in the `VaadinServletContext` impl where sync is done against the instance and not against the underlying context.
Fixed.

The logic has semantic:
- if there is no `Lookup`  in the attribute then set `DeferredServletContextInitializers.class` attribute.

You are suggesting setting the attribute `DeferredServletContextInitializers.class` unconditionally.
This is not the same at all.
And for the semantic which I need the synchronization is required since it guarantees atomic execution. Without it any check in multithreaded code has no sense.

2020-11-03 06:18 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/DeferredServletContextInitializers.java
> + * {@link LookupInitializer} completed.
The current javadocs exactly says why it's needed........

Do you suggest to reword the same thing somehow ? Not sure how.

2020-11-03 06:19 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/DeferredServletContextInitializers.java
> +    interface Initializer {
It's not missing.
Most likely it's not in the commit which you revired.

2020-11-03 06:24 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/osgi/OSGiAccess.java
> +                    .getServiceReference(serviceClass);
Good point though it's doesn't matter.
Don't know why the classes are different.
Fixed.

2020-11-03 06:27 UTC, denis-anisimov commented
Fixes for the current review round : https://github.com/vaadin/flow/pull/9289

2020-11-03 06:30 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/LookupInitializer.java
> +                List<T> services = new ArrayList<>();
Done

2020-11-03 07:13 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/di/Lookup.java
> + * singleton services.
Yes, but it is easy to discover the usage with an IDE, so my note was a bit silly.

2020-11-03 07:24 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/di/Lookup.java
> + * singleton services.
Well............
The issue is: depending on the way of running the app it differs (and that's the exact reason why this abstraction layer is introduced).
In WAR case it works in one way.
In OSGi case it works in another way.
In some third container it may work in one more way.
There is no point to describe all the cases of course in the abstraction layer.

I may add a note that services are registered in a different way depending on the servlet container where the app is running....
But I'm not sure whether this is a worth note.

2020-11-03 07:42 UTC, pleku requested changes

2020-11-03 07:42 UTC, pleku commented on flow-tests/test-root-context/pom-npm.xml
> +                            <goal>test-jar</goal>
Maybe add a comment here that why is this produced so that someone doesn't just remove it

2020-11-03 07:49 UTC, denis-anisimov commented on flow-tests/test-root-context/pom-npm.xml
> +                            <goal>test-jar</goal>
Done ( in the PR `osgi` branch).

2020-11-03 11:48 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinServletContext.java
> +        ensureServletContext();
@denis-anisimov you have marked this as resolved but no response here nor do I see any changes in the PR you mentioned. The `ensureServletContext()` is only run when in
```java
Lookup.class.equals(type) && doGetAttribute(type) != null
```
the former check is true.

2020-11-03 11:54 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinServletContext.java
> +        ensureServletContext();
I've missed it, sorry.

May be you are looking to some not final commit.

`ensureServletContext` is executed now every time when :
- `getAttribute` is called.
- `getContextParameterNames` is called
- `checkType`   is called.

But `checkType`  has a wrong order of checks: if `Lookup.class.equals(type)` is `false`  then `doGetAttribute`  will be never called.

Will fix it, thanks.

2020-11-03 11:56 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinServletContext.java
> +        ensureServletContext();
Yeah I went through commit by commit to understand what belongs together. You can see all the open comments through the Conversation tab in github

2020-11-03 13:51 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinServletContext.java
> +                checkType(clazz);
`setAttribute` may be called from anywhere.
E.g. it may be called from one servlet during the request dispatch and at the same time it may be called from another servlet during another request dispatch.

For this reason accessor get/setAttribute of `ServletContext`  has to be synchronized _already_ in the implementation (`ServletContext` is an interface so the methods are not synced there but should be in any impl).

As always synchronized accessors is not enough because normally the app logic do something more than just storing/reading the attribute value: e.g. in many cases it needs to check the attribute value and then store it if it doesn't exist.
This is exactly what `getAttribute(Class<T> type, Supplier<T> defaultValueSupplier)` does: such operation has to be executed atomically. Without any lock the check if `context.getAttribute() == null` may pas but it will be already `false` when `context.setAttribute` is executed. So this code has to be protected by some lock.
Doesn't matter whether this is related to `Lookup` or not.

2020-11-03 13:56 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/di/Lookup.java
> +     * interface.
I'm not sure what this should do in fact.
It's an impl detail: it may decide to choose some of the service if there are many or throw.
Currently the WAR impl throws but is this the proper behavior?

I may add but...

2020-11-03 14:07 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/LookupInitializer.java
> +                    .getServiceReference(serviceClass);
I'm not sure what do add and where.....

OSGi lookup which is now in the `OSGiAccess` is a totally different impl and it doesn't know anything about `LookupImpl` for WAR . The same is for :`LookupImpl` : it doesn't know anything about `OsgiLookupImpl`.
It's two totally different implementations which doesn't know anything each other.
So it's weird for me to add a comment in one impl about another totally unrelated impl.

Instead I may be would reconsider the implementation of `LookupImpl::lookup`: may be it should not throw if there are many services but just select one.....

2020-11-03 14:09 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/di/Lookup.java
> +     * interface.
I reverted the comment since it's invalid in case of OSGi.
`LookupImpl` is just an one impl which throws and may be it should not throw : I don't know what's better.
Since I don't see to select one service over another I would keep throwing as is: it's not possible to select the service deterministically .

2020-11-03 14:16 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/LookupInitializer.java
> +                        "Unexpected exception which is not expected to be thrown",
I don't know any details. They are provided in the exception `e`  which is passed as an argument.
I may reformulate but this should never happen, so is it worth ?

2020-11-03 14:20 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/LookupInitializer.java
> +                assert false : "Serveice filter is null so this may not happen";
I really have no any idea what to write here.
This is one useless sentence against another useless sentence.
This should never happen. If it happens then I don't know what's wrong and I may not provide any details: they are in the exception which is logged above.

2020-11-03 14:27 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/LookupInitializer.java
> +    private static class ResourceProviderImpl implements ResourceProvider {
I prefer to keep all implementation details hidden as private classes.

`LookupInitializer` is implemented in the way to search for all implementations of `ResourceProvider`.
Extracting the nested class in its own file allows `LookupInitializer` to collect this class as well if it's `public` which is wrong because this disallow to have a custom `ResourceProvider` impl since there will be two `ResourceProvider` services.

Keeping `ResourceProviderImpl`   as non `public` is fragile : someone may decide to make it `public`.
And I don't really see a point to have it in its own file.

2020-11-03 14:31 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/LookupInitializer.java
> +                    return new CachedStreamData(null, e);
Not sure what to answer: how may I throw something which doesn't exist over and over again?
Either something is used from the cache or cache is not used and the value is reread every time and then exception may be thrown......
I will try to figure out some comments but not sure .

2020-11-03 14:39 UTC, denis-anisimov commented on flow-server/pom.xml
> +        <dependency>
OK, but .....
Should every dependency have such comment ?
Not sure why this specific dependency should be commented

2020-11-03 14:41 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/osgi/VaadinBundleTracker.java
> +    private static class PushResourceServlet extends HttpServlet {
This is already changed in one of the PRs. The servlet is reused for `flow-client` as well.
So it's not for push anymore.
Made a generic comment.

2020-11-03 16:02 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/startup/LookupInitializer.java
> +                assert false : "Serveice filter is null so this may not happen";
Ok

2020-11-03 16:02 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/startup/LookupInitializer.java
> +                    .getServiceReference(serviceClass);
Ok, I think this is fine for now.

2020-11-03 16:05 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/startup/LookupInitializer.java
> +                    return new CachedStreamData(null, e);
My bad sorry - I first misread the code below. It is thrown already

2020-11-03 16:07 UTC, pleku commented on flow-server/pom.xml
> +        <dependency>
To help with maintenance and faster understanding for why is that dependency in flow-server. Thanks to the comment, it seems more intentional than introduced or forgotten after due to a mistake

2020-11-03 16:09 UTC, pleku reviewed
Reviewed up till 12th commit. (not approving since we don't know if this will land to 2.5 or not)

2020-11-04 05:38 UTC, denis-anisimov commented on flow-server/pom.xml
> +        <dependency>
Actually that was the result of transfer of the code from `flow-push`  to `flow-server` .
But now the resource is registered programmatically in `flow-server` instead of declaratively in `flow-push`. 
So it's not needed anymore. I will make a PR which removes it.

2020-11-04 06:47 UTC, pleku commented on flow-server/pom.xml
> +        <dependency>
Ok, great. So yeah, _I always question_ if new dependencies are added without clear explanation on _why_. And old dependencies need questioning often too.

2020-12-16 10:40 UTC, mg-dev-fis commented
I'm also waiting for fix as we are using OSGi bridged servlet.

2020-12-16 10:43 UTC, denis-anisimov commented
> I'm also waiting for fix as we are using OSGi bridged servlet.

This is already done in the `master` branch ( V19 Platform , 6.0 Flow).
The status of this change is quite unknown for `2.5`.

2020-12-16 10:46 UTC, mg-dev-fis commented
I'm doing migration from V8 to V14 and hoped that updating flow to 2.5 will fix the issue.

2021-03-04 08:43 UTC, pleku commented
Closing for now as OSGi support will likely not be backported to v14 at all, or not like it was done here anyway as this is slightly different from how it works since v19.

2021-03-04 08:43 UTC, closed without merging