prepare testEnv, simplify Tracker Component
vaadin/flow pull request #9193
Opened 2020-10-17 08:11 UTC by stbischof

- Simplify Tracker Component
- update bnd version to 5.2.0
- prepare testEnviroment - Tests inside an OSGi Framework
- initial test

2020-10-17 08:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=9193) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=9193) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=9193) it.</sub>

2020-11-02 06:09 UTC, denis-anisimov reviewed
Thank you for your contribution.
I'm not sure what to do with `VaadinResourceTrackerComponent`  in fact: we don't need anymore internally `OsgiVaadinStaticResource` and `OsgiVaadinContributor` for NPM.
Though they are still needed in compatibility mode.

So in the end we may just decide to drop `VaadinResourceTrackerComponent`  completely (at least in the latest version).
But I've got the idea behind the changes and the testing infrastructure is also valuable.
I will discuss how we are going to proceed with this PR: may be I will make again my PR based on this one.

2020-11-02 08:19 UTC, denis-anisimov commented on flow-osgi/pom.xml
> +        <dependency>
Are all these deps needed ?
Looks like there are too many of them

2020-11-02 10:01 UTC, stbischof commented on flow-osgi/pom.xml
> +        <dependency>
just a better Manifest-Declaration
https://github.com/apache/felix-dev/blob/0245baa922ca68718f5b75fc4cd0c23b519d7767/http/servlet-api/pom.xml#L41-L62

2020-11-02 10:02 UTC, stbischof commented on flow-osgi/pom.xml
> +        <dependency>
its just for the test

2020-11-02 10:04 UTC, stbischof commented on flow-osgi/pom.xml
> +        <dependency>
will remove 

```
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>3.4.6</version>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
            <version>3.4.6</version>
        </dependency>
```

2020-11-02 10:38 UTC, denis-anisimov commented
Could you please also rebase it on top of `feature/osgi` and resolve conflicts ?

I believe in fact the PR should not contain any changes in `DeploymentConfigurationFactory`, `FrontendUtils`, `OSGiAccess`.

2020-11-03 09:24 UTC, denis-anisimov requested changes

2020-11-03 09:24 UTC, denis-anisimov commented on flow-osgi/src/test/java/com/vaadin/flow/osgi/support/test/Test.java
> +public class Test {
Please rename the file with  some meaningful name, e.g. `VaadinResourceTrackerComponentTest`.

2020-11-03 09:24 UTC, denis-anisimov commented on flow-osgi/src/test/java/com/vaadin/flow/osgi/support/test/Test.java
> +    static OsgiVaadinStaticResource vsr(String path) {
Please make the method name more desceriptive.

2020-11-03 09:24 UTC, denis-anisimov commented on flow-osgi/src/test/java/com/vaadin/flow/osgi/support/test/Test.java
> + * @author stbischof
The test doesn't have to have any author.
Please just remove it.

2020-11-03 09:24 UTC, denis-anisimov commented on flow-osgi/src/test/java/com/vaadin/flow/osgi/support/test/Test.java
> +/**
Please remove an empty header or insert a standard Vaadin copyright header.

2020-11-03 09:24 UTC, denis-anisimov commented on flow-osgi/src/test/java/com/vaadin/flow/osgi/support/test/Test.java
> +
Could you please remove an empty line ?

2020-11-03 09:24 UTC, denis-anisimov commented on flow-osgi/src/test/java/com/vaadin/flow/osgi/support/test/Test.java
> +    void test1() throws Exception {
Please change the method name to some meaningful statement.
We normally use the format `a_b_c`, where :
- `a` is what's tested (e.g. `registerService`).
- `b` is precondition
- `c` is the expected result.

2020-11-03 09:24 UTC, denis-anisimov commented on flow-osgi/src/test/java/com/vaadin/flow/osgi/support/test/Test.java
> +        // printServletContexts();
please remove the comment.

2020-11-03 09:24 UTC, denis-anisimov commented on flow-osgi/src/test/java/com/vaadin/flow/osgi/support/test/Test.java
> +        // printServletContexts();
Please remove the comment

2020-11-03 09:24 UTC, denis-anisimov commented on flow-osgi/src/test/java/com/vaadin/flow/osgi/support/test/Test.java
> +        RequestInfoDTO riDto = httpServiceRuntime
Would be good to have some more meaningful name than just `riDto`.

2020-11-03 09:24 UTC, denis-anisimov commented on flow-osgi/src/test/java/com/vaadin/flow/osgi/support/test/Test.java
> +    void test2() throws Exception {
Please change the test name

2020-11-03 09:24 UTC, denis-anisimov commented on flow-osgi/src/test/java/com/vaadin/flow/osgi/support/test/Test.java
> +        // printServletContexts();
extra comment

2020-11-03 09:24 UTC, denis-anisimov commented on flow-osgi/src/test/java/com/vaadin/flow/osgi/support/test/Test.java
> +
an empty line

2020-11-03 09:24 UTC, denis-anisimov commented on flow-osgi/src/test/java/com/vaadin/flow/osgi/support/test/Test.java
> +        // printServletContexts();
extra comment

2020-11-03 09:24 UTC, denis-anisimov commented on flow-osgi/src/test/java/com/vaadin/flow/osgi/support/test/Test.java
> +    private void printServletContexts() {
The method is not used from anywhere. Please just remove it.

2020-11-03 09:24 UTC, denis-anisimov commented on flow-osgi/src/test/java/com/vaadin/flow/osgi/support/test/Test.java
> +    static HttpURLConnection connect(String sUrl) throws IOException {
The method is not used from anywhere, please just remove it.

2020-11-03 09:25 UTC, denis-anisimov commented
I hope you are aware of the fact that the build validation fails:
```
org.junit.platform.commons.JUnitException: BundleEngine must run inside an OSGi framework
	at aQute.tester.bundle.engine.BundleEngine.discover(BundleEngine.java:59)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:103)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:85)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:92)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:113)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
```

2020-11-03 09:35 UTC, stbischof commented
@denis-anisimov will not have time this week to change it.

2020-11-03 10:33 UTC, denis-anisimov commented
> @denis-anisimov will not have time this week to change it. if you need tomething earlyer. take what you need from this PR

that's fine, no worries

2020-11-05 17:04 UTC, stbischof commented on flow-osgi/bnd.bnd
> -Bundle-SymbolicName: ${project.groupId}.flow.osgi
the main reason is that i had the problem that the itest bnd extends from the bnd.bnd file. because of this it failed.

there a 3 Ways to declare bnd files.
- bnd.bnd file
- inline bnd file
-   [bnd](https://bnd.bndtools.org/chapters/230-manifest-annotations.html) and [osgi](https://docs.osgi.org/javadoc/osgi.annotation/7.0.0/org/osgi/annotation/bundle/package-summary.html) annotations

they are not just osgi specific:
for ServiceLoader
```
@ServiceConsumer - Generates requirements in support of the consumer side of the Service Loader Mediator specification.
@ServiceProvider - Generates requirements and capabilities in support of the provider side of the Service Loader Mediator specification. Also generates META-INF/service descriptors.
```
for JPMS
https://bnd.bndtools.org/chapters/330-jpms.html

maybe this could help you more

2020-11-05 17:23 UTC, stbischof commented on flow-osgi/logback.xml
> +<configuration>
will remove it.

2020-11-05 17:28 UTC, stbischof commented on flow-osgi/pom.xml
> +        <dependency>
would you test against both major frameworks? or just the reference implementation felix

2020-11-05 17:50 UTC, stbischof commented on flow-osgi/src/main/java/com/vaadin/flow/osgi/support/VaadinResourceTrackerComponent.java
> +        registration.init(httpService);
// init method has no any sense anymore. The service may be and should be provided in the constructor.

After your decition to use OSGi R7 we cann use the Constructor. but then scr will creat a new instance every time the http service is gone.

will add some more tests, that helps me to understand better what you mean.

2020-11-05 18:20 UTC, stbischof commented on flow-osgi/src/main/java/com/vaadin/flow/osgi/support/VaadinResourceTrackerComponent.java
> +    void unbindResource(OsgiVaadinStaticResource resource) {
no magic just osgi ds.

addX bindX setX
undbindX unsetX 
is what bnd is looking for. and writes the name of the method into the meta-inf/services

if you want so specify it more use `@Reference(bind = "bindResource",unbind = "unbindResource"`

[spec](https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.component.html#org.osgi.service.component.annotations.Reference.unbind--)

If you disable the service or deactivate a bundle with a service  or unregister a Service

this method will be called.

2020-11-05 18:20 UTC, stbischof commented on flow-osgi/src/main/java/com/vaadin/flow/osgi/support/VaadinResourceTrackerComponent.java
> +    void unbindContributor(OsgiVaadinContributor contributor) {
it is. via OSGi SCR

2020-11-05 18:21 UTC, stbischof commented on flow-osgi/src/main/java/com/vaadin/flow/osgi/support/VaadinResourceTrackerComponent.java
> +    void unbindHttpService(HttpService service) {
OSGi SCR will do

2020-11-05 18:24 UTC, stbischof commented on flow-osgi/src/test/java/com/vaadin/flow/osgi/support/test/Test.java
> +/**
done

2020-11-05 18:24 UTC, stbischof commented on flow-osgi/src/test/java/com/vaadin/flow/osgi/support/test/Test.java
> + * @author stbischof
done

2020-11-05 18:25 UTC, stbischof commented on flow-osgi/src/test/java/com/vaadin/flow/osgi/support/test/Test.java
> +    static OsgiVaadinStaticResource vsr(String path) {
thx

2020-11-05 18:26 UTC, stbischof commented on flow-osgi/src/test/java/com/vaadin/flow/osgi/support/test/Test.java
> +
thx

2020-11-05 23:42 UTC, stbischof commented
please try not to run vaadin with felix.http.jetty 4.1.0 & 4.1.2 
https://issues.apache.org/jira/browse/FELIX-6357

2020-11-06 01:02 UTC, stbischof commented on flow-osgi/src/main/java/com/vaadin/flow/osgi/support/VaadinResourceTrackerComponent.java
> +        registration.init(httpService);
I cleaned it a bit more... Just to show how it could look. If you know what all could be dropped. We can renove it .

2020-11-06 01:03 UTC, stbischof commented on flow-osgi/src/test/java/com/vaadin/flow/osgi/support/test/Test.java
> +public class Test {
Done

2020-11-06 01:03 UTC, stbischof commented on flow-osgi/src/test/java/com/vaadin/flow/osgi/support/test/Test.java
> +        // printServletContexts();
Removed

2020-11-06 01:03 UTC, stbischof commented on flow-osgi/src/test/java/com/vaadin/flow/osgi/support/test/Test.java
> +    private void printServletContexts() {
Removed

2020-11-06 01:04 UTC, stbischof commented on flow-osgi/src/test/java/com/vaadin/flow/osgi/support/test/Test.java
> +    static HttpURLConnection connect(String sUrl) throws IOException {
✅

2020-11-06 06:06 UTC, denis-anisimov commented on flow-osgi/bnd.bnd
> -Bundle-SymbolicName: ${project.groupId}.flow.osgi
Alright.
Yeah, I see the issue with `itest`.
OK.

2020-11-06 06:15 UTC, denis-anisimov commented
```
DEBUG ROOT - bundle org.apache.felix.scr:2.1.24 (26) bundle biz.aQute.tester.junit-platform:5.2.0.202010142003 (34) : Starting extension synchronously
[01:02:55] :	 [Step 5/11] 01:02:55.386 [main] INFO Events.Service.org.eclipse.osgi - ServiceEvent REGISTERED
[01:02:55] :	 [Step 5/11] TEST [10] jakarta.activation-api;1.2.2 <<< ERROR: Could not resolve module: jakarta.activation-api [10]
[01:02:55] :	 [Step 5/11]   Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=9.0))"
[01:02:55] :	 [Step 5/11] 
[01:02:55] :	 [Step 5/11] org.osgi.framework.BundleException: Could not resolve module: jakarta.activation-api [10]
[01:02:55] :	 [Step 5/11]   Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=9.0))"
[01:02:55] :	 [Step 5/11] 
[01:02:55] :	 [Step 5/11] 	at org.eclipse.osgi.container.Module.start(Module.java:463)
[01:02:55] :	 [Step 5/11] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:439)
[01:02:55] :	 [Step 5/11] 	at aQute.tester.bundle.engine.discovery.BundleSelectorResolver.lambda$resolve$14(BundleSelectorResolver.java:234)
[01:02:55] :	 [Step 5/11] 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[01:02:55] :	 [Step 5/11] 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[01:02:55] :	 [Step 5/11] 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[01:02:55] :	 [Step 5/11] 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[01:02:55] :	 [Step 5/11] 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[01:02:55] :	 [Step 5/11] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
[01:02:55] :	 [Step 5/11] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[01:02:55] :	 [Step 5/11] 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[01:02:55] :	 [Step 5/11] 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[01:02:55] :	 [Step 5/11] 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[01:02:55] :	 [Step 5/11] 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[01:02:55] :	 [Step 5/11] 	at aQute.tester.bundle.engine.discovery.BundleSelectorResolver.resolve(BundleSelectorResolver.java:228)
[01:02:55] :	 [Step 5/11] 	at aQute.tester.bundle.engine.discovery.BundleSelectorResolver.resolve(BundleSelectorResolver.java:103)
[01:02:55] :	 [Step 5/11] 	at aQute.tester.bundle.engine.BundleEngine.discover(BundleEngine.java:63)
[01:02:55] :	 [Step 5/11] 	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:103)
[01:02:55] :	 [Step 5/11] 	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:85)
[01:02:55] :	 [Step 5/11] 	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:92)
[01:02:55] :	 [Step 5/11] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
[01:02:55] :	 [Step 5/11] 	at aQute.tester.junit.platform.Activator.test(Activator.java:438)
[01:02:55] :	 [Step 5/11] 	at aQute.tester.junit.platform.Activator.automatic(Activator.java:344)
[01:02:55] :	 [Step 5/11] 	at aQute.tester.junit.platform.Activator.run(Activator.java:216)
[01:02:55] :	 [Step 5/11] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[01:02:55] :	 [Step 5/11] 	at aQute.launcher.Launcher.launch(Launcher.java:452)
[01:02:55] :	 [Step 5/11] 	at aQute.launcher.Launcher.run(Launcher.java:181)
[01:02:55] :	 [Step 5/11] 	at aQute.launcher.Launcher.main(Launcher.java:157)
[01:02:55] :	 [Step 5/11] 	at aQute.launcher.pre.EmbeddedLauncher.executeWithRunPath(EmbeddedLauncher.java:170)
[01:02:55] :	 [Step 5/11] 	at aQute.launcher.pre.EmbeddedLauncher.findAndExecute(EmbeddedLauncher.java:135)
[01:02:55] :	 [Step 5/11] 	at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:52)
```

2020-11-06 06:15 UTC, denis-anisimov requested changes

2020-11-06 06:15 UTC, denis-anisimov commented on flow-osgi/pom.xml
> +        <dependency>
In case of test the `test`  scope should be used.

If it's only for test with `test`  scope then it's fine to have this dependency.
Not sure whether it has sense to have _unit_ tests for many frameworks. 
In the future we may have IT tests for various frameworks but for unit tests it's enough to use some framework.

2020-11-06 06:24 UTC, denis-anisimov commented on flow-osgi/src/main/java/com/vaadin/flow/osgi/support/VaadinResourceTrackerComponent.java
> +        registration.init(httpService);
`Delegate` is an internal class and I'm not sure how OSGi R7 relates here.

What I meant is:

- in the previous impl a `Delegate` instance might have been created before `HttpService` instance is available. 
- this is not the case anymore: there is already an `HttpService` instance when a `Delegate` is created.
- It means that `init` method is not needed.
- moreover : `HttpService`  is not needed at all for a `Delegate`. Only `HttpContext` is needed. An `HttpContext` instance may be created before instantiating a `Delegate`  and the instance may be passed as an argument to the constructor. And since it's immutable there is no any need to declare it as `AtomicReference`,  it should be just `final HttpContext`.

2020-11-06 06:51 UTC, stbischof commented
You are running your tests with java8?

These tests are both. Unit and integration tests. Because we start a full Framework.

2020-11-06 06:57 UTC, denis-anisimov commented
> You are running your tests with java8?

Validation build is using Java 8, yes.
> 
> These tests are both. Unit and integration tests. Because we start a full Framework.

Well, kind of...
They are ITs in the sense that it requires a full framework. But this is just because there is no other way to run them.
But their nature is unit test: they tests only one small piece of the code (not even functionality).

IT usually test no the code itself but a user scenario ( the code is a black box and there is only a user interface).

So by the nature these are unit tests.
We have a lot of ITs with various user scenarios.

2020-11-06 07:39 UTC, stbischof commented
Sorry, i didnt realised the `Log in as guest` option of your teamcity. Didnts know that i can see what went wrong....

2020-11-06 07:44 UTC, denis-anisimov commented
> Sorry, i didnt realised the `Log in as guest` option of your teamcity. Didnts know that i can see what went wrong....

Ah, that's fine.
But it's good that you now may see the error messages.

2020-11-06 12:29 UTC, stbischof commented
I saw in the commit https://github.com/vaadin/flow/pull/9321/commits/e641cf127642e7b07a8952231cffca4563ea3a69 that you removed flow-osgi.pom.xml
what does that mean for this PR?

2020-11-09 06:19 UTC, denis-anisimov commented
> I saw in the commit [e641cf1](https://github.com/vaadin/flow/commit/e641cf127642e7b07a8952231cffca4563ea3a69) that you removed flow-osgi.pom.xml
> what does that mean for this PR?

It's for the `master` branch.
For this specific PR it doesn't mean anything.
We will need to decide whether we want to forwardport this PR into the latest version.
`flow-osgi` is not completely removed: it's moved into its own repo https://github.com/vaadin/osgi.
But there is a question: do we need functionality provided by `VaadinResourceTrackerComponent` at all.
See my initial comments above: 
>I'm not sure what to do with VaadinResourceTrackerComponent in fact: we don't need anymore internally OsgiVaadinStaticResource and OsgiVaadinContributor for NPM.
>Though they are still needed in compatibility mode.

At the moment I don't see a reason to have `VaadinResourceTrackerComponent` for the `master`. So I'm not going to forwardport this. But may be later on there will be a need for this.

`2.5` still supports compatibility mode so it's still needed here.

2020-11-09 07:13 UTC, denis-anisimov commented on flow-osgi/pom.xml
> +            <scope>compile</scope>
Not sure about `compile` scope here.........
`compile`  scope means that the dependency should be deployed along with the bundle.
But OSGi container should contain this bundle already (otherwise nothing just will work as I understand).

It's kind of the same situation as with Servlet API Jar for WAR: we depend on Servlet API but we should not deploy it as a part of a WAR because it's already available in the servlet container.

It doesn't have to be present in the OSGi container though. So we include it as a `compile` dependency here but 
OSGi core should be already in the OSGi container.

I think `provided`  scope is more correct semantically.
Though it doesn't matter in reality most likely.

2020-11-09 09:24 UTC, stbischof commented on flow-osgi/pom.xml
> +            <scope>compile</scope>
youre right! Sorry!

i also checked how felix use this:

https://github.com/apache/felix-dev/blob/a6c986ffc8f6f08f71fc435909a7f1061eeb961a/scr/pom.xml#L73-L89

2020-11-09 23:22 UTC, stbischof commented
@denis-anisimov  maybe some of the last changes should also be in #9321 Forwardporting OSGi feature branch to the master

2020-11-10 06:03 UTC, denis-anisimov approved these changes

2020-11-10 06:03 UTC, denis-anisimov commented
The build failed, see https://teamcity.vaadin.com/viewLog.html?buildId=68828&buildTypeId=Flow_FlowTests.
I guess because of some dependency/version updates.

Also there are conflicts in `VaadinBundleTracker`. Could you please reabase your changes on top of the `master`?

2020-11-10 06:04 UTC, denis-anisimov commented
> @denis-anisimov maybe some of the last changes should also be in #9321 Forwardporting OSGi feature branch to the master

Yeah, makes sense.

2020-11-10 06:40 UTC, denis-anisimov requested changes

2020-11-10 06:40 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/osgi/ServletContainerInitializerExtender.java
> -        registration = context.registerService(ResourceProvider.class,
This code is removed and has no any equivalent now as I understand.

2020-11-10 06:50 UTC, stbischof commented on flow-server/src/main/java/com/vaadin/flow/server/osgi/ServletContainerInitializerExtender.java
> -        registration = context.registerService(ResourceProvider.class,
The component annotation atbthe constructors of the oagi resource provider

2020-11-10 06:52 UTC, stbischof commented on flow-server/src/main/java/com/vaadin/flow/server/osgi/ServletContainerInitializerExtender.java
> -        registration = context.registerService(ResourceProvider.class,
https://github.com/vaadin/flow/blob/31577503f03923a5a043e1aba4eed9863088b8b8/flow-server/src/main/java/com/vaadin/flow/server/osgi/OSGiResourceProvider.java#L39

2020-11-10 09:46 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/osgi/ServletContainerInitializerExtender.java
> -        registration = context.registerService(ResourceProvider.class,
Ah.
It has been registered programmatically to remove dependency on OSGi compendium artifact because that we the only need in it.
But now it's also used in the tracker. 
OK, let's use it this way.

2020-11-10 12:10 UTC, denis-anisimov commented
> > @denis-anisimov maybe some of the last changes should also be in #9321 Forwardporting OSGi feature branch to the master
> 
> Yeah, makes sense.

Reverted in the `master` branch since the latter changes breaks everything without a clear reason.
Don't know which change exactly but these changes are extra here and can be done later on.

2020-12-10 13:10 UTC, pleku commented
Is this PR still valid for 2.5 ? @denis-anisimov @stbischof

2020-12-10 13:15 UTC, denis-anisimov commented
yes, it's valid.

2021-02-03 12:50 UTC, pleku commented
As this PR is not going anywhere for now and we don't like leaving PRs open forever, I'm closing this PR.

That said, once we move focus into OSGi support in Flow 2.x we can consider these changes. It is still an open question if we will do it based on the the current feature branch `feature/osgi` or if we'll do the same as we did for Flow 6.0 and move OSGi support to its own repository (even just partly).

2021-02-03 12:50 UTC, closed without merging