feat: offline stub for server-side views
vaadin/flow pull request #9200
Opened 2020-10-19 17:10 UTC by joheriks

An information page, similar in style and content to the default `offline.html`, is rendered in 
when navigating to a server-side view in offline mode.
Fixes #9103

2020-10-19 20:01 UTC, joheriks commented
Note: this PR duplicates some CSS from `default-offline-page.html` in `OfflineStub.ts`. However, this should not be an issue as it seems that as of #8856 `default-offline-page.html` should be removed.

2020-10-20 18:52 UTC, haijian-vaadin commented
Found some weird UI behavior when offline, but I think it's out of scope for this ticket, made a separate [ticket](https://github.com/vaadin/flow/issues/9207)

2020-10-20 18:53 UTC, haijian-vaadin approved these changes

2020-10-21 04:40 UTC, haijian-vaadin requested changes

2020-10-21 04:40 UTC, haijian-vaadin commented on flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
> +      if (navigator.onLine) {
Maybe we should also check if a custom `offlinePath` is defined. Otherwise, Anton's [PR](https://github.com/vaadin/flow/pull/9181) won't work.

2020-10-23 13:23 UTC, platosha approved these changes

2020-10-23 14:42 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
> +        await this.flowInit();
Good idea, updated to show the offline stub also in the failed connection case. Only unit test for this one though, as setting up the scenario in IT gets unncessarily complicated.

2020-10-26 07:46 UTC, haijian-vaadin commented on flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
> +        await this.flowInit();
Should it also check what kind of error it is? simply catching all the errors might lead to a confusing situation, e.g. when the server throws some exception and the user suddenly sees an offline page.

2020-10-26 12:47 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
> +        await this.flowInit();
The logic of ´flowInitUI` wraps a `XMLHttpRequest` with a promise that is rejected only `onerror`. This [SO thread ](https://stackoverflow.com/questions/10584318/when-should-xmlhttprequests-onerror-handler-fire) concludes that `onerror` only triggers for network-level errors (e.g., no internet, DNS lookup failure, same-origin violation, etc.). It does not trigger for irregular HTTP response code such as 404, 501, etc. I added a specific exception raised there so that offline stub is not shown for other exceptions raised within `´flowInitUI` (instead the user will see the infinitely blinking loading indicator as before).

2020-10-26 18:55 UTC, haijian-vaadin commented on flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
> +        await this.flowInit();
Looks good!
Just found one small improvement that can be made. I think we could also hide the loading indicator (the `hideLoading()` method), otherwise when the server is not reachable, it shows the loading indicator indefinitely.
![2020-10-26 20-51-43 2020-10-26 20_52_25](https://user-images.githubusercontent.com/30408303/97215740-85798400-17cd-11eb-8561-644a86159432.gif)

2020-10-26 19:41 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
> +        await this.flowInit();
Done.

2020-10-26 19:47 UTC, haijian-vaadin submitted a review, later dismissed

2020-10-28 13:31 UTC, platosha submitted a review, later dismissed

2020-10-28 15:47 UTC, joheriks commented
Rebased. Now uses `com.vaadin.flow.testutil.ChromeDeviceTest` to go offline.

2020-10-29 07:54 UTC, haijian-vaadin approved these changes

2020-10-29 08:01 UTC, merged