feat: defer deferrable endpoint calls on network failure
vaadin/flow pull request #9244
Opened 2020-10-27 11:42 UTC by haijian-vaadin

Fixes #9231

2020-10-28 11:07 UTC, platosha requested changes

2020-10-28 11:07 UTC, platosha commented on flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
> +        if (error.message === 'Failed to fetch') {
In Firefox the error message is different: `NetworkError when attempting to fetch resource.`

This tells me that checking a message string is unreliable.

I’d suggest to check against the errors we throw ourselves instead:
```
if ((error instanceof EndpointResponseError) || (error instanceof EndpointError)) {
  // Error thrown in the client, carry to the user
  throw error;
} else {
  // Network error
  return this.cacheEndpointRequest({endpoint, methods, params});
}
```

This is safer: if it’s not the error we throw ourselves, then it’s a `fetch` error, which is only thrown for the network reasons.

2020-10-28 11:23 UTC, haijian-vaadin commented on flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
> +        if (error.message === 'Failed to fetch') {
very good point, done

2020-10-29 14:57 UTC, platosha approved these changes

2020-10-29 18:51 UTC, merged