fix(offline): resolve offlineResources at runtime
vaadin/flow pull request #9258
Opened 2020-10-28 15:09 UTC by joheriks

Depending on servlet container type and configuration, offline resources
may be served from multiple different file system locations, which cannot
be predicted. Revert to runtime resolution.

Fixes #8996.

2020-10-28 15:56 UTC, joheriks commented on flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
> +
Note. I have replaced the previous version of `exists` which checked for existence by connecting directly to the server with one that goes via the browser. This makes the test more end-to-end, and allows testing the caching of resources in offline mode.

2020-10-29 09:00 UTC, Haprog requested changes

2020-10-29 09:00 UTC, Haprog commented on flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
> +    }
What does this (and the above `@NotThreadSafe`) actually do?

2020-10-29 09:03 UTC, Haprog commented on flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
> +    }
Or is this about making the tests run in sequence instead of parallel?

2020-10-29 09:04 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
> +        }
Done, this was a mistake, should use `isOfflinePathEnabled` instead.

2020-10-29 09:12 UTC, joheriks commented on flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
> +    }
Forcing the tests to run in sequence. I will remove these once it's clear whether the tests can run in parallel or not. If they need to be sequenced, `@NotThreadSafe` should be enough anyway (the annotation is recognized by `maven-failsafe-plugin`, https://maven.apache.org/surefire/maven-failsafe-plugin/examples/fork-options-and-parallel-execution.html)

2020-10-29 09:16 UTC, joheriks commented on flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
> +    private void checkResources(String... resources) {
That sounds like a good idea. ´Content-Length` is a bit iffy because resources can be served in `chunked` mode in which case the header is missing. What do you think about checking `Content-Type` and correlating it with the expected file (e.g. icon should be `image/png`). I guess a typical bug that would now go unnoticed is where we incorrectly serve a fallback `text/html` for a resource).

2020-10-29 09:54 UTC, Haprog commented on flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
> +    private void checkResources(String... resources) {
`Content-Type` sounds like a good enough generic check when we're expecting something else than HTML. It would be a good improvement to these tests here I think.

2020-10-29 09:55 UTC, Haprog commented on flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
> +    }
Ok, thanks for the explanation.

2020-10-29 09:58 UTC, Haprog commented
Code looks ok so far. Just need to make the new tests work reliably.

2020-10-29 11:03 UTC, joheriks commented on flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
> +    private void checkResources(String... resources) {
Done. Now checks `Content-Type` of the atual served file if `URLConnection#guessContentTypeFromName` returns non-`null` for the resource (currently `null` only for `manifest.webmanifest`).

2020-10-29 11:08 UTC, joheriks commented on flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
> +    }
Seems parallelism may have been a red herring, as the test was failing because of the service worker not installing due to the (now corrected) error I had in `PWARegistry` (when checking whether to precache `offlinePath`). Removed the forced sequencing to see if the tests pass. The race between SW installation and going offline (addressed in #9261) is also likely to be an issue here.

2020-10-29 12:32 UTC, Haprog approved these changes

2020-10-30 10:40 UTC, Haprog approved these changes

2020-10-30 11:08 UTC, merged