fix: Sync expanded state of HierarchicalDataCommunicator with client side
vaadin/flow pull request #9275
Opened 2020-11-02 07:39 UTC by taefi

Fixes: #9175

2020-11-02 09:40 UTC, mshabarov requested changes

2020-11-02 09:40 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapper.java
> +     * {@code IdentifierProvider} to the items.
For the current implementation they are the result of `DataProvider::getId()`, aren't they? `IdentifierProvider` is not used currently in `HierarchyMapper`, so maybe better to refer to `getId` method?

2020-11-02 09:40 UTC, mshabarov commented on flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapperWithDataTest.java
> +        System.out.println(hierarchyMapper.getExpandedItems());
Is this `sout` a leftover after debugging? Let's remove it

2020-11-02 09:40 UTC, mshabarov commented on flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapperWithDataTest.java
> +        Map<Object, TreeNode> expandedItems = hierarchyMapper.getExpandedItems();
Good to add a `Assert.assertNotNull(expandedItems);` right away

2020-11-02 09:40 UTC, mshabarov commented on flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapperWithDataTest.java
> +    public void expandingItems_getExpandedItems_shouldReturnCorrectExpandedItems() {
Should the test name be like `getExpandedItems_expandSomeItems_returnsCorrectExpandedItems`

2020-11-02 09:40 UTC, mshabarov commented on flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapperWithDataTest.java
> +        HierarchicalDataProvider<TreeNode, Void> dataProvider =
Since this data provider is used more than once, is it better to extract it to an inner class and reuse?

2020-11-02 09:40 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
> +            update.enqueue("$connector.expandItems",
Does it make sense to add one more unit test to verify that the `update` contains the proper bunch of `JsonObject` for expanded items after `reset()`?

2020-11-02 10:22 UTC, mshabarov requested changes

2020-11-02 10:22 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapper.java
> +    public Map<Object, T> getExpandedItems() {
I believe that it's better to return the collection of items, not a whole mapping. From a client code perspective, it's not that necessary to have a mapping (someone can recalculate the object ids if needed), but to know which items are expanded. So I would suggest to limit this method to return `Collection<T>`

2020-11-02 20:17 UTC, taefi commented on flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapper.java
> +     * {@code IdentifierProvider} to the items.
Done.

2020-11-02 20:17 UTC, taefi commented on flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapperWithDataTest.java
> +        System.out.println(hierarchyMapper.getExpandedItems());
How did I miss that?! 
Done.

2020-11-02 20:17 UTC, taefi commented on flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapperWithDataTest.java
> +        Map<Object, TreeNode> expandedItems = hierarchyMapper.getExpandedItems();
Done.

2020-11-02 20:17 UTC, taefi commented on flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapperWithDataTest.java
> +    public void expandingItems_getExpandedItems_shouldReturnCorrectExpandedItems() {
Done.

2020-11-02 20:17 UTC, taefi commented on flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapperWithDataTest.java
> +        HierarchicalDataProvider<TreeNode, Void> dataProvider =
Done.

2020-11-02 20:17 UTC, taefi commented on flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
> +            update.enqueue("$connector.expandItems",
Done. 
Created a test in `HierarchicalCommunicatorTest.java` to verify it.

2020-11-02 20:17 UTC, taefi commented on flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapper.java
> +    public Map<Object, T> getExpandedItems() {
Nice one! 
Done.

2020-11-03 07:29 UTC, mshabarov approved these changes

2020-11-03 07:37 UTC, merged