Make VaadinService.dependencyFilters unmodifiable
vaadin/flow pull request #9292
Opened 2020-11-03 08:57 UTC by fluorumlabs

### Warning: Exposed mutable collection ([CERT](https://wiki.sei.cmu.edu/confluence/display/java/OBJ05-J.+Do+not+return+references+to+private+mutable+class+members))

Returning references to internal mutable members of a class can compromise an application's security, both by breaking encapsulation and by providing the opportunity to corrupt the internal state of the class (whether accidentally or maliciously). As a result, programs must not return references to private mutable classes.

Class: **`com.vaadin.flow.server.VaadinService`**
Scope: **singleton**
Field: **`private Iterable<DependencyFilter> VaadinService.dependencyFilters`**
Value: `(ArrayList<E>) []`
Value is read:
- **`public Iterable<DependencyFilter> VaadinService.getDependencyFilters()`**
Value is written:
- **`private void VaadinService.lambda$init$1(ServiceInitEvent, List<E>)`**
Value is returned:
- **`public Iterable<DependencyFilter> VaadinService.getDependencyFilters()`**

2020-12-04 10:27 UTC, pleku requested changes
Only one import formatting change please

2020-12-04 10:27 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
> +import java.util.*;
No `*` imports according to the coding conventions (just noticed that the conventions are not up to date so we need to fix that immediately)

2020-12-04 15:48 UTC, fluorumlabs commented on flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
> +import java.util.*;
Fixed

2020-12-07 07:14 UTC, pleku submitted a review, later dismissed

2020-12-07 08:19 UTC, pleku approved these changes

2020-12-07 09:59 UTC, merged

2021-01-26 15:45 UTC, mshabarov commented
Cherry picked to `2.5`