feat: Create Flow plugins for webpack
vaadin/flow pull request #9295
Opened 2020-11-03 09:41 UTC by caalador

Moved stats file handling to a custom plugin.
Added feature for copying custom Flow plugins
for use with webpack.

Fixes #9283

2020-11-04 12:43 UTC, pleku requested changes

2020-11-04 12:43 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPlugins.java
> +        final String pluginFolder = "plugins/" + pluginName + "/";
Just noting that I was a bit confused with the code for a moment since the variable names are both `folder` but other is `String` and other is a `File`

2020-11-04 12:43 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPlugins.java
> +    private URL getUrlResource(String resource) {
nitpicking, but shouldn't this be `getResourceUrl` instead ?

2020-11-04 12:43 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPlugins.java
> +        final JsonObject json = getJsonFile(pluginFolder + PACKAGE_JSON);
nitpicking: `packageJson`  would be clearer name

2020-11-04 12:43 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPlugins.java
> +        File pluginPackageJson = new File(urlResource.getFile());
Wrong variable name left after refactoring this method to be reused ? Should probably just be ` jsonFile`

2020-11-04 12:43 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
> +    public void runNpmInstall_dirContainsOnlyFlowNpmPackage_npmInstallIsExecuted()
wat - it is now executed but no changes to the actual test ? 😅

2020-11-04 12:50 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
> +    public void runNpmInstall_dirContainsOnlyFlowNpmPackage_npmInstallIsExecuted()
The assertion at the end of the test checks that npm is executed. the test name was wrong as the assertion for not executing npn install would be
```
        ArgumentCaptor<String> captor = ArgumentCaptor.forClass(String.class);
        Mockito.verify(logger).info(captor.capture(),
                Mockito.matches(getToolName()),
                Mockito.matches(nodeModules.getAbsolutePath().replaceAll("\\\\", "\\\\\\\\")), Mockito.any(),
                Mockito.matches(Constants.PACKAGE_JSON));
        Assert.assertEquals(
                "Skipping `{} install` because the frontend packages are already installed in the folder '{}' and the hash in the file '{}' is the same as in '{}'",
                captor.getValue());
```

2020-11-04 13:04 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPlugins.java
> +            log().error("Couldn't locate files for plugin '{}'", pluginName);
done

2020-11-04 13:04 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPlugins.java
> +        File pluginPackageJson = new File(urlResource.getFile());
done

2020-11-04 13:04 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPlugins.java
> +    private URL getUrlResource(String resource) {
done

2020-11-04 13:04 UTC, caalador commented on flow-server/src/main/resources/plugins/webpack-plugins.json
> +    "stats-plugin"
It would simplify the plugins to just an array or list of String, but this makes it easier to add/remove plugins when you don't have to find the Java class and update it.

We can revert to java class strings if wanted.

2020-11-04 13:31 UTC, pleku approved these changes

2020-11-04 13:31 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPlugins.java
> +    protected List<String> getPlugins() {
But it is needed as protected ?

2020-11-04 13:31 UTC, pleku commented on flow-server/src/main/resources/plugins/webpack-plugins.json
> +    "stats-plugin"
Ok. I don't think it is significant enough to warrant the change

2020-11-05 04:46 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPlugins.java
> +    protected List<String> getPlugins() {
Only for tests, so package protected would also be fine.
Constructor could also be made package protected as no one should ever have the need to create this task on the outside.

2020-11-05 13:18 UTC, mshabarov approved these changes

2020-11-05 13:34 UTC, merged