generate sw.ts to frontend folder when pwa enabled
vaadin/flow pull request #9309
Opened 2020-11-04 10:47 UTC by haijian-vaadin

Fixes #9143

- generate `sw.ts` to frontend folder instead of the project root folder
- generate `sw.ts` only when PWA is enabled

2020-11-05 08:39 UTC, joheriks requested changes
From the ticket (#9143) I understood the intention is to generate `sw.ts` to the `target` folder:

> Per discussion: We align the sw.ts the same as index.ts and index.html. Generate in the target folder unless the user has a sw.ts in the frontend folder. There should be a log message, the same as index.ts. index.html

and only use `frontend/sw.ts` if they user has created it themselves.

2020-11-05 08:42 UTC, joheriks commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
> +        createWebpackUpdater();
`createWebpackUpdater` is run by `setup` so not needed to run explicitly unless creating a new `PwaConfiguration` in the test.

2020-11-05 08:42 UTC, joheriks commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
> +        createWebpackUpdater();
`createWebpackUpdater` is run by `setup` so not needed to run explicitly unless creating a new `PwaConfiguration` in the test.

2020-11-10 07:48 UTC, joheriks requested changes
´TaskGenerateServiceWorker` needs an exclusion in `com.vaadin.flow.testutil.ClassesSerializableTest` to pass the validation.

2020-11-10 07:48 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +        }
Would perhaps make sense to extract this duplicate logic into a private method, e.g. `addServiceWorkerTask(Builder bilder, FrontendDependencies frontendDependencies)`.

2020-11-10 08:19 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +        }
Removed the other code block which should've been deleted.

2020-11-10 08:29 UTC, joheriks approved these changes

2020-11-10 19:44 UTC, merged