chore: create profile deepClean
vaadin/flow pull request #9311
Opened 2020-11-04 11:39 UTC by caalador

Using the deepClean profile one can
clean up all the generated files and
node_modules folders from all test modules.

2020-12-10 13:52 UTC, taefi requested changes

2020-12-10 13:52 UTC, taefi commented on flow-tests/pom.xml
> +                                            <include>pmpm-lock.yaml</include>
Shouldn't this be `pnpm-...` instead of `pmpm-...`?

2020-12-11 06:03 UTC, caalador commented on flow-tests/pom.xml
> +                                            <include>pmpm-lock.yaml</include>
yes. updated.
Also I don't see a main.js anymore anywhere.

2020-12-11 21:40 UTC, taefi approved these changes

2020-12-15 07:24 UTC, merged