feat: Theme annotation should be only on AppShellConfigurator
vaadin/flow pull request #9313
Opened 2020-11-04 12:46 UTC by caalador

If an AppShellConfigurator is available the `@Theme` annotation 
should be only defined there.

Fixes #9092

2020-11-04 13:06 UTC, pleku requested changes
1) Theme annotation javadocs need updating.

2) I think we should throw a meaningful error for people who migrate to flow 6 / v19 and have the theme annotation in the wrong place, even after they change their code after we've broken it elsewise. The error should state that the Theme annotation should go to the appshellconfigurator.

2020-11-04 13:19 UTC, caalador commented
I felt there isn't much more information to add than the default:
```
Found app shell configuration annotations in non `AppShellConfigurator` classes.
Please create a custom class implementing `AppShellConfigurator` and move the following annotations to it:
 - Theme from [nonAppShellClass]
```

2020-11-09 08:20 UTC, pleku approved these changes

2020-11-09 08:21 UTC, merged

2020-11-12 09:15 UTC, mshabarov commented
Cherry picked to `5.0`