fix: Store in-memory filtering and sorting in component
vaadin/flow pull request #9315
Opened 2020-11-04 13:32 UTC by mshabarov

In-memory filtering and sorting are now stored directly in component, which gives an opportunity to change it through the data view API for a certain component separately from other components bound to the same data provider.

Fixes: https://github.com/vaadin/flow/issues/8655

2020-11-09 09:33 UTC, pleku requested changes

2020-11-09 09:33 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/ComponentInMemoryFilter.java
> +public class ComponentInMemoryFilter<T> implements Serializable {
Why is this class needed ? For storing the filter with certain key to component data ?
Is it necessary that it is public ?

2020-11-09 09:33 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/ComponentSorting.java
> +public class ComponentSorting<T> implements Serializable {
Why is this class needed ? For storing the comparator in component data ?
Is it necessary that it is public ?

2020-11-09 09:33 UTC, pleku commented on flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
> +
Should there be a test that checks case that setting a list data provider filter is applied correctly (doesn't discard data view filter) and that it is combined with the data view one ? Probably for sorting too ?

2020-11-09 09:33 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
> +                new ComponentDataChangeEvent<>(component));
So how is this working when none of the components react to this event ? Why not fire the `DataChangeEvent` instead ?

2020-11-09 11:01 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
> +    private Query getQuery(boolean filteringOnly) {
Yes, `withSorting ` much more clear.

2020-11-09 12:46 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/ComponentInMemoryFilter.java
> +public class ComponentInMemoryFilter<T> implements Serializable {
Yes, this is for storing in the component. I was considering to use a string key like this 

`ComponentUtil.setData(component, ListDataView.IN_MEMORY_FILTER_KEY,  filter);`

but adding a public string to `ListDataView` seems even worse maybe, because it is still public and it modifies the public interface. This key should be visible in both `AbstractListDataView` and in the `Component` (Component needs to restore this object internally in some places), so I am not able to find out the better approach than to make it just public.

2020-11-09 12:47 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/ComponentSorting.java
> +public class ComponentSorting<T> implements Serializable {
The same comment as for filter.

2020-11-09 12:48 UTC, mshabarov commented on flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
> +
Yeah, good point! I will add such a test!

2020-11-09 12:53 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/ComponentInMemoryFilter.java
> +public class ComponentInMemoryFilter<T> implements Serializable {
If it were hidden to a protected method for the abstract data view, then it would be possible to access it in a component that creates the data view. If it was package protected, then the data communicator could access it. So package-protected static method in the AbstractListDataView ? I would not expose two new public classes just as markers for storing data.

2020-11-09 13:10 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
> +                new ComponentDataChangeEvent<>(component));
> So how is this working when none of the components react to this event ?
I assumed that the components have to add a listener by themselves and to restore the filter/sorting by themselves. I avoided using a callback for notifying the components because it would be a breaking change for list data view abstract class. 

> Why not fire the DataChangeEvent instead ?
There are tow obstacles to do that:
1. `DataChangeEvent ` does not have a 'component' field, nor any other information to distinguish the target component. Adding such a filed means the breaking change in this class.
2. If we fire this event via data provider listener handler, then it would require the certain component mention in the public method -> breaking change. We're also not able to fire it via `ComponentUtil.fireEvent` because this event class does not extend `ComponentEvent`.

2020-11-09 13:29 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
> +                new ComponentDataChangeEvent<>(component));
> Adding such a filed means the breaking change in this class.

I see, this doesn't matter, but I don't see how it is necessarily a breaking change with another constructor and exposing a new getter which might return `null`. There is new API added here anyway which makes it impossible to backport anyway. I don't know if it is really worth it to introduce dubious new API just for avoiding breaking something that we introduced in version 4.0 and can now change for 5.0.

But as to an alternative, I don't know either how the data provider could even distinguish the correct component to fire the data change event on. But it feels somehow bad API design to me as a component developer that if I have to _know and remember to do something extra_ when using `AbstractListDataView` instead of being required to do it implicitly in the constructor. Basically I could easily miss adding the listener to this event ^ and then my component would not work when filters & sorting changes.

So either
1) make the data provider fire the event for all components with the optional meta data of `Component getDataChangeComponent()` (better name would be nice) and then our components & data communicator (?) can ignore the events where the component is something different than itself.
2) force components using abstractlistdataview to always pass a callback for reacting to filter/sorting change

2020-11-09 13:30 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/ComponentInMemoryFilter.java
> +public class ComponentInMemoryFilter<T> implements Serializable {
Yeah, good idea! So I will add `protected static final String ...KEY = "...key";` to `AbstractListDataView` and then override it in component-specific data views, for instance, in `ComboBoxListDataView`, with a `public` modifier, and then just use in in `ComboBox` - `ComboBoxListDataView.KEY` and in data communicator - `AbstractListDataView.KEY`.

Sound good!

2020-11-09 13:34 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/ComponentInMemoryFilter.java
> +public class ComponentInMemoryFilter<T> implements Serializable {
> Yeah, good idea! So I will add `protected static final String ...KEY = "...key";` to `AbstractListDataView` and then override it in component-specific data views, for instance, in `ComboBoxListDataView`, with a `public` modifier, and then just use in in `ComboBox` - `ComboBoxListDataView.KEY` and in data communicator - `AbstractListDataView.KEY`.
> 
> Sound good!

Sorry, I'm not sure I understand this. Why do you need to expose or override keys ? If you just create package protected static getter & setter method in  `AbstractListDataView` that takes in component and optionally the filter OR sorting. Why would a component specific key be needed ????

2020-11-09 13:52 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/ComponentInMemoryFilter.java
> +public class ComponentInMemoryFilter<T> implements Serializable {
Right, the component and data communicator will just use those static setter and getter. And the string key will be hidden in the `AbstractListDataView`. Sorry for confusing.

2020-11-09 14:02 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
> +                new ComponentDataChangeEvent<>(component));
> But it feels somehow bad API design to me as a component developer that if I have to know and remember to do something extra when using AbstractListDataView instead of being required to do it implicitly in the constructor.

Agree! I would go with option 2 then, because it guarantee that the custom component won't forget to handle these filtering/sorting events.

2020-11-09 14:07 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
> +                new ComponentDataChangeEvent<>(component));
>it guarantee that the custom component won't forget to handle these filtering/sorting events.

I don't think it guarantees it per se, as existing components often can forget to add those listener into their data providers.. but is maybe a better pattern. I wonder now why we didn't just expose an API in the `HasItems` or `HasDataProvider`  that would have been called by the data provider and even optionally the users to just tell the component to _refresh the data for itself_... I don't know what sense it made to require acquiring the data provider to refresh things. Probably just wrong design principles with too much emphasis on the data providers.

2020-11-11 13:11 UTC, pleku requested changes

2020-11-11 13:11 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
> +     * A filter bound to the component. Any other component using the same
> A filter bound to the component.

This is a bit odd way of continuing the javadocs at this point... maybe

> This filter is bound to the component.

would make it more natural.

2020-11-11 13:11 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
> +     * A filter bound to the component. Any other component using the same
The same as above

2020-11-11 13:11 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
> +     * A comparator bound to the component. Any other component using the same
The same as above, seem off. Maybe

> This comparator is bound to the component. Thus any other...

would be better

2020-11-11 13:11 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
> +     * A comparator bound to the component. Any other component using the same
Same as above

2020-11-12 07:33 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
> +    private void fireDataChangeEvent(SerializablePredicate<T> filter,
Done

2020-11-12 07:33 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
> +     * A filter bound to the component. Any other component using the same
Done

2020-11-12 07:33 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
> +     * A filter bound to the component. Any other component using the same
Done

2020-11-12 07:33 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
> +     * A comparator bound to the component. Any other component using the same
Done

2020-11-12 07:33 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
> +     * A comparator bound to the component. Any other component using the same
Done

2020-11-12 07:59 UTC, pleku approved these changes

2020-11-12 08:01 UTC, merged