Forwardporting OSGi feature branch to the master
vaadin/flow pull request #9321
Opened 2020-11-05 09:25 UTC by denis-anisimov

Part of #9248

2020-11-05 09:27 UTC, denis-anisimov reviewed
This should not be merged yet. There are still things that needs to be done: e.g. move `flow-osgi` along with OSGi ITs into a separate repo.

But I would like to see validation errors now since there are a lot changes in various places: the OSGi feature branch adaptation to the `master` requires significant efforts.

2020-11-06 12:06 UTC, denis-anisimov commented
> This should not be merged yet. There are still things that needs to be done: e.g. move `flow-osgi` along with OSGi ITs into a separate repo.
> 
> But I would like to see validation errors now since there are a lot changes in various places: the OSGi feature branch adaptation to the `master` requires significant efforts.

Ready for review.

2020-11-06 12:48 UTC, stbischof commented on flow-lit-template/bnd.bnd
> +Import-Package: *
I know that you use this in most `bnd.bnd` files. But not sure why -  its the default

> The Import-Package header lists the packages that are required by the contained packages. The default for this header is *, resulting in importing all referred packages. 

[from bnd docs](https://bnd.bndtools.org/heads/import_package.html)

2020-11-06 12:52 UTC, stbischof commented on flow-polymer-template/pom.xml
> +            <scope>provided</scope>
i think the scope is compile.

2020-11-06 12:55 UTC, stbischof commented on flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/rpc/OSGiPolymerPublishedEventHandlerRegistration.java
> +    void activate() {
You could a BundleContext as Parameter in the method. The ServiceComponentRuntime will inject it.

2020-11-09 05:56 UTC, denis-anisimov commented on flow-lit-template/bnd.bnd
> +Import-Package: *
Thank you.
Didn't know that this is the default.

2020-11-09 06:02 UTC, denis-anisimov commented on flow-polymer-template/pom.xml
> +            <scope>provided</scope>
Not really.
Or may be it would be better to set this dependency as optional....

The idea here is : this Jar should be used without any OSGi.
And that's exactly the reason why I've introduced `OSGiPolymerPublishedEventHandlerRegistration` class instead of declaring `PolymerPublishedEventRpcHandler` directly as a service impl.
It allows to use `PolymerPublishedEventRpcHandler` as is so that it doesn't depend on OSGi at all (no any references to OSGi annotations).
And `OSGiPolymerPublishedEventHandlerRegistration`  will be used only in OSGi, otherwise this class will be completely ignored.

I think I prefer `provided`  vs `optional`.

2020-11-09 06:03 UTC, denis-anisimov commented on flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/rpc/OSGiPolymerPublishedEventHandlerRegistration.java
> +    void activate() {
Thank you.
I assumed that it should work this way but was too lazy to check that in the spec.

2020-11-09 17:44 UTC, stbischof commented on flow-server/bnd.bnd
> +    io.swagger*;resolution:=optional;,javax.annotation;version=1.3.2,\
maybe just only  io.swagger.codegen an optional. oll the other are afaik theother io.swagger jars are osgi bundles

2020-11-09 20:02 UTC, stbischof commented
would be good to update the bnd version.

2020-11-10 05:57 UTC, denis-anisimov commented on flow-server/bnd.bnd
> +    io.swagger*;resolution:=optional;,javax.annotation;version=1.3.2,\
Well, there are many packages.
And the reason is semantical here: all `io.swagger` packages are used by `vaadin-connect` functionality which is 
executed either via Maven goal or via `DevModeInitializer`  which is explicitly excluded in OSGi.

So in the end : the whole Flow functionality which requires `io.swagger`  doesn't work in OSGi and there is just no sense to keep some dependencies non optional.

At some point all these deps will be excluded from `flow-server`  along with this functionality which is not supposed to work in OSGi at all.

2020-11-10 06:07 UTC, denis-anisimov commented
> would be good to update the bnd version.

done

2020-11-10 06:47 UTC, stbischof commented
The bnd update needs this lines in the tests pom


https://github.com/vaadin/flow/blob/014de584c5f44dae8b91fca80a5e072419426e6c/flow-tests/pom.xml#L75

2020-11-10 09:49 UTC, denis-anisimov commented
> The bnd update needs this lines in the tests pom
> 
> https://github.com/vaadin/flow/blob/014de584c5f44dae8b91fca80a5e072419426e6c/flow-tests/pom.xml#L75

OK, thanks.

2020-11-10 11:01 UTC, stbischof commented on flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/rpc/OSGiPolymerPublishedEventHandlerRegistration.java
> +                new PolymerPublishedEventRpcHandler(), null);
you could remove this class if you declare PolymerPublishedEventRpcHandler als component 
```
@Component(immidiate=true,service=PolymerPublishedEventRpcHandler.class)
public class PolymerPublishedEventRpcHandler
```

2020-11-10 12:05 UTC, denis-anisimov commented
> > The bnd update needs this lines in the tests pom
> > https://github.com/vaadin/flow/blob/014de584c5f44dae8b91fca80a5e072419426e6c/flow-tests/pom.xml#L75
> 
> OK, thanks.

Reverted since the latter changes breaks everything without a clear reason.
Don't know which change exactly but these changes are extra here and can be done later on.

2020-11-10 12:05 UTC, denis-anisimov commented
> > would be good to update the bnd version.
> 
> done


Reverted since the latter changes breaks everything without a clear reason.
Don't know which change exactly but these changes are extra here and can be done later on.

2020-11-10 12:06 UTC, denis-anisimov commented on flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/rpc/OSGiPolymerPublishedEventHandlerRegistration.java
> +                new PolymerPublishedEventRpcHandler(), null);
Already explained here: 
https://github.com/vaadin/flow/pull/9321/files#r519569258

2020-11-10 12:07 UTC, denis-anisimov commented on flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/rpc/OSGiPolymerPublishedEventHandlerRegistration.java
> +                new PolymerPublishedEventRpcHandler(), null);
Already explained here: https://github.com/vaadin/flow/pull/9321/files#r519569258

2020-11-10 12:24 UTC, stbischof commented
i will add the commits on top of this and have a look what breaks it

2020-11-12 09:38 UTC, caalador requested changes

2020-11-12 09:38 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
> +        File tmpFile = temporaryFolder.newFile();
Is the temp file necesary? We could just mock the URL and return an expected path.

2020-11-12 09:38 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
> +    public final TemporaryFolder tmpDir = new TemporaryFolder();
Drop un-used rule and imports

2020-11-12 09:38 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
> +            File tmpFile = tmpDir.newFile();
This should also be mockable to not need to have the temporary file by returning a mock url that for `openStream()` returns the stream.

2020-11-12 11:42 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandler.java
> +                        .isPresent() : "Rpc handler may not be called for a component that is not attached";
This code is designed to work only with `StateNode`  which are attached to the `StateTree`: RPC may not be executed for a Node which is not in the tree.

So I would say `assertion` should be enough since it just checks that the assumption correct.
Exception should be thrown on a user mistake. Our internal mistake (or incorrect assumption) should be checked with assertions.
But I don't see a reason to have a strong position here on my side.
Let's make it throwing.

2020-11-12 11:47 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +                    .lookup(ResourceProvider.class);
`BootstrapContext` is quite hidden internal class.
And `ResourceProvider` is used only once in the code.
So any specific reason to declare a shorthand ?

2020-11-12 11:54 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +                    .lookup(ResourceProvider.class);
Readability is the main issue.

2020-11-12 12:03 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
>                  .findFirst().orElse(null);
Doesn't work.
Because it fixes only `URL resource =` line.

But then below there is a check for `resources.isEmpty()` which may not be done with the same stream.
It might be this can be simplified but it's out of scope of this PR.

2020-11-12 12:04 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
> +     *             >>>>>>> 81a7e2d15a... Fix OSGi Lookup related issues
Good point.

2020-11-12 12:12 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
>                  .findFirst().orElse(null);
But the stream of an empty list is a "empty stream" (e.g. no-op) so it makes streams of the 2 lists (that are never null) and gets the same end result as the if with the isEmpty checks and new list creation.

2020-11-12 12:23 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/LookupInitializer.java
> +    private static class LookupImpl implements Lookup {
Similar question has been already answered in the original review of this code for `2.5` branch.

`LookupImpl` : I may extract this class to its own file. But why ?
This class is instantiated here directly and there is no any single reason to override it because overridden class won't be ever instantiated.

Implementation is done private explicitly. And this obviously says that this may not be overriden /changed.
Just because it's impossible.
And that's the reason why it's done `private` and nested.
The code is self-explanatory . 

Lookup is an entry point for "everything". It exactly allows to override any service (if it's done properly).
And this is the only thing which may not be overridden: because it give the way to override other things.

Other classes are made private for same reasons and e.g. `ResourceProviderImpl` may not be done `public` because otherwise it will be collected by the `LookupInitializer` and there will be no any way to override it.

Shortly : this functionality is explicitly made non-overridable because it gives the way to override everything.

2020-11-12 12:24 UTC, denis-anisimov reviewed
-

2020-11-12 12:26 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/startup/LookupInitializer.java
> +    private static class LookupImpl implements Lookup {
So please add a javadoc with the information for both internal impl classes.

2020-11-12 12:28 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
> +        File tmpFile = tmpDir.newFile();
Can we mock `final` classes?
I thought we can't.

I will check.

2020-11-12 12:30 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
> +        File tmpFile = tmpDir.newFile();
`final` class may not be mocked.

2020-11-12 12:31 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
> +        File tmpFile = temporaryFolder.newFile();
final class may not be mocked.

2020-11-12 12:31 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
> +            File tmpFile = tmpDir.newFile();
final class may not be mocked.

2020-11-12 12:38 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
> +        File tmpFile = tmpDir.newFile();
Right so the other possibility would be to either have a WrapperUrl that is mocked or   mock(URLConnection.class);
e.g. something like:
```
final URLConnection mockUrlCon = mock(URLConnection.class);

ByteArrayInputStream is = new ByteArrayInputStream(
        "<myList></myList>".getBytes("UTF-8"));
doReturn(is).when(mockUrlCon).getInputStream();

URLStreamHandler stubUrlHandler = new URLStreamHandler() {
    @Override
     protected URLConnection openConnection(URL u) throws IOException {
        return mockUrlCon;
     }            
};
URL url = new URL("foo", "bar", 99, "/foobar", stubUrlHandler);
```

Which is in many ways worse... Lets go with the temp file.

2020-11-12 12:41 UTC, pleku requested changes
I noticed that your changes are touching imports and breaking the agreed ordering. Please fix this for everything

2020-11-12 12:41 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +import javax.servlet.http.HttpServletResponse;
This is also broken, javax. should be at the top

2020-11-12 12:41 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +import static java.nio.charset.StandardCharsets.UTF_8;
Your import ordering is broken ?
Static imports should be last https://sites.google.com/a/vaadin.com/fw-flow-team-s-wiki/contributing-code/code-style/e

2020-11-12 13:53 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java
> +                deploymentConfiguration);
`servlet.init` is almost not needed in the tests.
That's why I've removed it.

But `VaadinService::init` is needed everywhere.
So yes, good point.

2020-11-12 13:55 UTC, denis-anisimov commented on flow-polymer-template/src/test/java/com/vaadin/flow/component/PolymerClassesSerializableTest.java
> +                "com\\.vaadin\\.flow\\.component\\.polymertemplate\\.rpc\\.OSGiPolymerPublishedEventHandlerRegistration"),
This class has been removed at some point.
So now it's not needed.
Just a leftover, thanks.

2020-11-12 13:59 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +import javax.servlet.http.HttpServletResponse;
I had no `flow.importorder`  imported in my Eclipse apparently.
Done.

2020-11-12 14:02 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +                    .lookup(ResourceProvider.class);
Ah, you mean just private method.
I thought `public` or `protected`  method for reuse.

OK.

2020-11-12 14:08 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
>                  .findFirst().orElse(null);
I think I don't understand you.

One stream instance may be used once. Stream is not interchangeable with List anyhow.
`resourceStream.filter....` closes the stream in the end.
Which means that `isEmpty`  or in fact `stream.count()` may not be called anymore: stream is closed.
That's why the list is used : it's possible to call `isEmpty` regardless of any other list operations.

Please provide the whole code snippet for the method instead of change for the snippet above if you still see how this can be imprioved.

2020-11-12 14:10 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/LookupInitializer.java
> +    private static class LookupImpl implements Lookup {
Which kind of information?

I don't understand . These are impl classes.
The contract (interfaces) are described in details in javadocs of interface.
Impl classes just impl classes (one of impl).

2020-11-13 05:15 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
>                  .findFirst().orElse(null);
Right didn't see the reuse of the thing later on in the class. then I would just have it as
`Collection<URL> resources = Stream.of(classResources, contextResources).flatMap(Collection::stream).collect(Collectors.toList());`

2020-11-13 05:36 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
>                  .findFirst().orElse(null);
Done without `flatMap`.

2020-11-13 06:09 UTC, caalador requested changes

2020-11-13 06:09 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
>  package com.vaadin.flow.server;
This still doesn't have the fixed imports after Pekkas comment

2020-11-13 06:09 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
> -        mockServlet = new TestServlet();
The private static class TestServlet can be removed as it's not used anymore.

2020-11-13 06:09 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/communication/StreamReceiverHandlerTest.java
Imports

2020-11-13 06:09 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/communication/StreamRequestHandlerTest.java
> +import static com.vaadin.flow.server.communication.StreamRequestHandler.DYN_RES_PREFIX;
import position

2020-11-13 06:09 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
> +import static org.mockito.Matchers.eq;
import position

2020-11-13 06:09 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
> +import static org.junit.Assert.assertTrue;
import position

2020-11-13 06:18 UTC, caalador approved these changes

2020-11-16 09:50 UTC, pleku requested changes
Please fix the introduced unnecessary import ordering change for all test files, not just the ones that I had the strength to check and comment on

2020-11-16 09:50 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java
> +    public static ApplicationRouteRegistry getInstance(ServletContext context) {
Again, adding back deprecated code is not that nice ... but OK for now if we address it soon anyway

2020-11-16 09:50 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/startup/ClassLoaderAwareServletContainerInitializer.java
> +import javax.servlet.ServletException;
Wrong import order

2020-11-16 09:50 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/startup/LookupInitializer.java
> +    private static class LookupImpl implements Lookup {
> Which kind of information?

Answer review questions in code.

> Shortly : this functionality is explicitly made non-overridable because it gives the way to override everything.

Yes this is obvious to you as you've done this. It was not obvious for me or Mikael so we asked to document it.
Unless you do that, it will not be obvious to anyone else outside this conversation either. So spending a little time on documenting the code with comments to save time in the future.

2020-11-16 09:50 UTC, pleku commented on flow-tests/test-root-context/pom.xml
> -    </properties>
Uh, shouldn't this still be applied for the module not to be released/deployed with Flow ?
I understand that it is needed for snapshots due to being reused in tests, but probably not for named releases ? And thus this configuration should be still done for a release profile ?

2020-11-16 09:50 UTC, pleku commented on flow-tests/pom.xml
> +                <module>test-root-context</module>
I don't think we should release these modules other than for snapshots. Is it so ?

2020-11-16 09:50 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
> +import javax.servlet.http.HttpServletRequest;
Wrong import ordering

2020-11-16 09:50 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/startup/ServletDeployerTest.java
> +import static org.junit.Assert.assertTrue;
Wrong import ordering

2020-11-16 09:50 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/component/UITest.java
> +
Wrong import ordering

2020-11-16 09:50 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerDependenciesTest.java
> +import static org.mockito.Mockito.mock;
Wrong import ordering

2020-11-16 09:50 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerPushConfigurationTest.java
> +import static org.mockito.Mockito.mock;
Wrong import ordering

2020-11-16 09:50 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
> +import static org.junit.Assert.assertTrue;
Wrong import ordering

2020-11-16 09:50 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
> +import static org.junit.Assert.assertTrue;
Wrong import ordering

2020-11-16 09:50 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/I18NProviderTest.java
> +
Wrong import ordering

2020-11-16 15:29 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java
> +    public static ApplicationRouteRegistry getInstance(ServletContext context) {
This is actually done my accident.
Code is reintroduced from `2.5`  but now this method is not used internally and indeed should be removed.

2020-11-17 05:39 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +                if (instantiator != null && instantiator.init(this)) {
I hope you understand that it means my intention is failed: it should have been done for `2.5` and now this change should be back-ported after forwardporting. This is exactly what I've been trying to avoid.

This should be done by factory.
But the method exists. And if it's implemented we should use it I suppose.
Though I'm not sure: and as result I consider the comment absolutely useless since both approaches makes sense and the code is written using one or another way.
But sure, let's add more comments which nobody reads.

2020-11-17 05:41 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/osgi/VaadinBundleTracker.java
> +            URL resource = bundle.getResource(resourceDirPath + pathInfo);
And again this code has been already reviewed in `2.5`.

This is done only for two bundles: `flow-client`  and `flow-push`.
`flow-push` contains only two resources (and nothing else) and both of them should be exposed.
`flow-client` contains client engine compiled files + `ts` files and `map` files. Do you see any reason why we should not allow to access any resource in this bundle ?

Do you suggest add a check for the `pathInfo` to avoid navigation to parent folders ?

I would not touch this for now because this should be rewritten via HTTP whiteboard resource registration which should take care about this in a separate PR.

2020-11-17 05:41 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/osgi/VaadinBundleTracker.java
> +                .trace("Couldn't load class '{}'", className, throwable);
Perhaps, you mean by total duplication  that `trace` method is totally the same as `warn`  method.
But I think I disagree.
And this code here is for ages : https://github.com/vaadin/flow/blob/2.4/flow-server/src/main/java/com/vaadin/flow/server/osgi/VaadinBundleTracker.java#L137
https://github.com/vaadin/flow/blob/2.4/flow-server/src/main/java/com/vaadin/flow/server/osgi/VaadinBundleTracker.java#L143
This is reintroduced code.
So you are again reviewing the code in Nth time.

2020-11-17 05:42 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java
> +                        .removeRoute(data.getUrl(), data.getNavigationTarget()),
This is reintroduced code.
I would suggest to avoid (re-)reviewing the code which is not new but has been removed and then added back overall.

This is exactly the reason why I've not done any change : to keep the code the same as in `2.5`.

But one more reason do not touch this: it will be completely removed once OSGi code moved to `osgi` repo.

2020-11-17 05:42 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java
> +    public static ApplicationRouteRegistry getInstance(ServletContext context) {
This is actually done by accident.
Code is reintroduced from 2.5 but now this method is not used internally and indeed should be removed.

2020-11-17 05:55 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/LookupInitializer.java
> +    private static class LookupImpl implements Lookup {
There is a reason why we are writing the code using Java.
It allows to write the code in typesafe way, clear contract and hide things which should not be exposed.
All these things may be done so that compiler may check this.
Without this JS may be used to write the code: it doesn't provide any safety.

It's possible to use 4 visibilities : `public`, `protected` , package local and `private`.
If something is defined as `private` then this is intentionally made non-extendable and intentionally hidden from everyone. And this is enforced by the compiler.
Looks quite obvious. And the same obvious things are requested to be added as comment. That's why 
I really don't understand why.
We don't add any comment for a private field why it's `private` : it's obvious why it's private.
Here the internal impl class implements interface which defines a contract and since it's private: it's an implementation details which explicitly is not exposed.
So it's absolutely obvious for me why the nested class is private and what it means.
But apparently I'm the only one for whom this is obvious.
So OK, let's add comment which nobody reads.

2020-11-17 06:04 UTC, denis-anisimov commented on flow-tests/test-root-context/pom.xml
> -    </properties>
It's hard to answer to the questions which are not related to the code at all without testing this.
And I'm not able to test this because this PR is under review for several weeks.

Yes, the module should be deployed as a snapshot. And yes, it should not be deployed for a regular release.
I'be been trying to prevent deploying it for the regular release via config options in the build jobs.
But looks like it was wrong. At least it turns out the `SNAPSHOT` doesn't even use `release` profile.

I made one more profile `snapshot` and the module `test-root-context` is not anymore in `release` profile which should prevent releasing it.

2020-11-17 06:07 UTC, denis-anisimov commented on flow-tests/pom.xml
> +                <module>test-root-context</module>
Moved to a dedicated profile.

2020-11-17 10:29 UTC, pleku requested changes
Just one odd change

2020-11-17 10:29 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
> +    public void testFireSessionDestroy()
Why was this test removed ?

2020-11-17 11:48 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
> +    public void testFireSessionDestroy()
Good question.
No idea. Perhaps merge conflict consequence.
Returned back.

2020-11-17 13:35 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
> -
How is it that your imports are again going to the wrong location and causing unnecessary changes ?

2020-11-17 15:27 UTC, pleku approved these changes

2020-11-18 05:41 UTC, merged