feat: Theme can be defined as string or class
vaadin/flow pull request #9349
Opened 2020-11-09 12:31 UTC by caalador

Add a string definition for theme that
matches the application theme in the theme folder.
Change old version to use themeClass for theme
selection.

Fixes #9281

2020-11-10 11:51 UTC, pleku requested changes
Submitting review for Java things while JS parts are still WIP

2020-11-10 11:51 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
>          themeLayoutVisitor = new RepeatedAnnotationVisitor() {
The comment above is outdated, should this even exist as we're not interested in theme in routes either than to fail graciously ?

2020-11-10 11:51 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
>              @Override
The comment above is outdated, should this even exist as we're not interested in theme in routes either than to fail graciously ?

2020-11-10 11:51 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
> +                visitClass(endPoint.getTheme().getThemeClass(), endPoint, true);
First I was confused with _why are we visiting end points..._ but then looked it up in code.
Should the javadocs of this method be somehow changed as we're not supposed to search for theme information from "end points" anymore ? I mean that first we check for the theme annotation from the `AppShellConfiguration` and then if that is not found, we can search the "end points" and then make it fail if it is discovered there ?

2020-11-10 11:51 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
> +                        data.getTheme().getThemeName() != null
Based on the code here, I think the error is thrown only if the theme is discovered `>1` times on any of the following things that are collected as `EndPoint`:
- `Route`
- `WebComponentExporter` or `WebComponentExporterFactory`
- `UIInitListener`
- `VaadinServiceInitListener`
- `HasErrorParameter`

And I don't think the theme should be on any of those classes anymore (?) even 1 time, so this code seems off now.

2020-11-10 11:51 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
> +            replacements.put("ApplyTheme","");
Doesn't this go into adding app theme support for exported web component ?
Not sure it is OK for now or we should just have TODOs in place until we have tests that validate things...
Or if we add the support at the same time we should then at least draft the issues for web component support accordingly and make sure this PRs commit message acknowledges all the additions.

2020-11-10 11:51 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/theme/Theme.java
>      /**
I think the class javadocs need to be updated as they now don't refer to the application theme and its folder in any way, which is the recommended way to go.

2020-11-10 11:51 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/theme/Theme.java
> +     * The name of the application theme to use
What is an application theme ? (+ missing a dot)

2020-11-10 11:51 UTC, pleku commented on flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/NpmThemedComponentView.java
> +@Theme(value ="app-theme", themeClass = MyTheme.class)
At one point at least it was discussed that this should be impossible and I think I've written it to the technical design doc - I mean basically as the application theme is always based on Lumo (that is stated in feature design doc too).

This code ^ should be not allowed as otherwise someone could try to use `@Theme(value="my-theme", themeClass=Material.class)` and that is not supported for now (?) Or I'm a bit confused now, could that be made to work with this from our end ? What would it mean ? And anyway, if the parent theme is not lumo, it should be done in `theme.json` instead since one should not be able to switch the "base theme" for an application theme with the java annotation...

Even if we could make this possible (not like this from Java code), we would then have to support this and add tests...

2020-11-10 11:52 UTC, pleku commented on flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/NpmThemedComponentView.java
> +@Theme(value ="app-theme", themeClass = MyTheme.class)
But it might be OK to slice this (catching the usage the same time and throwing a meaningful error) to its own issue

2020-11-10 12:40 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +        defaults.put("construct-style-sheets-polyfill", "2.4.2");
It's for `Constructable Stylesheet Objects` specification for handling style sheets across shadow boundaries and only implemented for chrome 73+, but is not needed yet at this step, removed.

2020-11-10 12:40 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendWebComponentGenerator.java
> +            ThemeDefinition theme) {
done

2020-11-10 12:40 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
> +            if (themeDef!= null && !themeDef.getName().equals("")) {
done

2020-11-10 12:40 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +                    + theme.getName() + ".js';\nexport const applyTheme = _applyTheme;\n",
done

2020-11-10 12:40 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
>              @Override
This fork is from before the change for AppShell so on this instance in time it's correct.

2020-11-10 12:40 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
> +                visitClass(endPoint.getTheme().getThemeClass(), endPoint, true);
This branch doesn't have the appShell changes as of yet.

2020-11-10 12:40 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/theme/ThemeDefinition.java
> +            String variant, String name) {
done

2020-11-10 12:40 UTC, caalador commented on flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/NpmThemedComponentView.java
> +@Theme(value ="app-theme", themeClass = MyTheme.class)
Well at the moment we only add support for global.css for which the base theme doesn't matter as long as you don't use lumo specific things.

2020-11-10 12:40 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
> +            replacements.put("ApplyTheme","");
We can take it out.

2020-11-10 19:21 UTC, pleku requested changes

2020-11-10 19:21 UTC, pleku commented on flow-server/src/main/resources/webpack.generated.js
> +// FIXME This is missing some entries
??? Fixed now or ticket ?

2020-11-10 19:21 UTC, pleku commented on flow-server/src/main/resources/webpack.generated.js
> +      //   use: ['lit-css-loader', 'extract-loader']
Commented out code ???

2020-11-10 19:21 UTC, pleku commented on flow-server/src/main/resources/webpack.generated.js
> +                // If the import happens from within a node_modules file, we must resolve and inline. Otherwise resources will not be found at runtime as node_modules is not deployed
This is related to supporting resources from `node_modules` ?
Again a bit unclear why added now as part of another issue and then with no tests

2020-11-10 19:21 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
> +            if (themeDef != null && !themeDef.getName().equals("")) {
The bot is right

2020-11-10 19:21 UTC, pleku commented on flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/AppShell.java
> +// `src/` in component above should be replaced by `legacyTheme/my-theme`
This comment is out of place now ?

2020-11-10 19:21 UTC, pleku commented on flow-tests/test-misc/pom.xml
> +                <configuration>
Maybe drop a comment on what this refers to or why

2020-11-10 19:21 UTC, pleku commented on flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/AppShell.java
> +// `src/` in component above should be replaced by `legacyTheme/my-theme`
This comment seems out of place

2020-11-10 19:21 UTC, pleku commented on flow-tests/test-themes/pom.xml
> +                <configuration>
Not sure why this is here, maybe add a comment to help

2020-11-10 19:21 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +        themeImportFile.getParentFile().mkdirs();
Not sure when this could occur, maybe due to some access rights issue, but could be handled

2020-11-11 07:00 UTC, pleku commented on flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/NpmThemedComponentView.java
> +@Theme(value ="app-theme", themeClass = MyTheme.class)
https://github.com/vaadin/flow/issues/9370

2020-11-11 08:33 UTC, caalador commented on flow-server/src/main/resources/webpack.generated.js
> +                // If the import happens from within a node_modules file, we must resolve and inline. Otherwise resources will not be found at runtime as node_modules is not deployed
the url loading needs to not resolve the urls for local theme files.
Updated the loader options.

2020-11-11 08:33 UTC, caalador commented on flow-server/src/main/resources/webpack.generated.js
> +      //   use: ['lit-css-loader', 'extract-loader']
removed.

2020-11-11 08:33 UTC, caalador commented on flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/AppShell.java
> +// `src/` in component above should be replaced by `legacyTheme/my-theme`
done

2020-11-11 08:33 UTC, caalador commented on flow-tests/test-themes/pom.xml
> +                <configuration>
added info.

2020-11-11 08:33 UTC, caalador commented on flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/AppShell.java
> +// `src/` in component above should be replaced by `legacyTheme/my-theme`
done

2020-11-11 08:33 UTC, caalador commented on flow-tests/test-misc/pom.xml
> +                <configuration>
added info

2020-11-11 08:33 UTC, caalador commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
> +  const themeFileApply = `export const applyTheme = (target) => {
applyTheme is not for fusion, but the theme-generated.js is calling it to actually apply the theme.

2020-11-11 08:33 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/theme/Theme.java
>      /**
What should we recommend here?

2020-11-11 09:19 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
>              @Override
Made a ticket about this case https://github.com/vaadin/flow/issues/9379 as changing it here would make backporting problematic.

2020-11-11 12:10 UTC, pleku requested changes

2020-11-11 12:10 UTC, pleku commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> + */
Maybe a TODO with a new ticket that will only use the currently active theme

2020-11-11 12:47 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/theme/Theme.java
>      /**
changed.

2020-11-11 12:47 UTC, caalador commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> + */
MAde ticket bout this #9383

2020-11-11 12:52 UTC, pleku approved these changes

2020-11-12 07:42 UTC, merged