fix: support Range requests with either start or end byte index omitted
vaadin/flow pull request #9368
Opened 2020-11-10 17:10 UTC by joheriks

Supports headers of the type `Range: -123` and `Range: 123-`. This
format was accidentally omittted in the previous implementation and 
Firefox and Chromium now use it.

2020-11-11 07:10 UTC, denis-anisimov requested changes

2020-11-11 07:10 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
> +                response.setStatus(416); // Range Not Satisfiable
Seems this code branch is not tested ?

2020-11-11 07:20 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
> +                response.setStatus(416); // Range Not Satisfiable
Done.

2020-11-11 07:24 UTC, denis-anisimov approved these changes

2020-11-12 08:30 UTC, merged

2020-11-12 09:38 UTC, mshabarov commented
Cherry picked to `5.0`

2020-11-12 12:28 UTC, taefi commented
Cherry-picked to `4.0`