feat: initial sketch of connection state store
vaadin/flow pull request #9377
Opened 2020-11-11 08:17 UTC by joheriks

2020-11-11 17:26 UTC, platosha commented on flow-client/src/main/resources/META-INF/resources/frontend/ConnectionState.ts
> +  private stateChangeListeners: ConnectionStateChangeListener[] = [];
BTW: Using `Set` instead of array for storage works better for this use case, in particular, `addStateChangeListener` and `removeStateChangeListener` methods would map directly to `stateChangeListeners.add` and `stateChangeListeners.remove`.

Iterating a `Set` could be done with `for...of`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

2020-11-11 17:26 UTC, platosha commented on flow-client/src/main/resources/META-INF/resources/frontend/ConnectionState.ts
> +  getState(): ConnectionState {
Should we do `get state()` `set state()` instead of `getState()`/`setState()` maybe?

2020-11-11 17:26 UTC, platosha commented on flow-client/src/main/resources/META-INF/resources/frontend/ConnectionState.ts
> +  isOnline(): boolean {
Maybe `get online(): boolean` should be preferred

2020-11-11 17:26 UTC, platosha commented on flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
> +      connectionState.setState(ConnectionState.CONNECTED);
Placing these handlers in `Flow.ts` makes them inactive before the first server-side view is requested, right? Was that intentional?

2020-11-12 07:41 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
> +      connectionState.setState(ConnectionState.CONNECTED);
This code is invoked from the constructor of `Flow`, and this object is always created (in `index.ts`) even when starting from a client-side view AFAIK.

2020-11-12 07:41 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/ConnectionState.ts
> +  isOnline(): boolean {
Done.

2020-11-12 07:41 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/ConnectionState.ts
> +  getState(): ConnectionState {
Agreed, done.

2020-11-12 07:41 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/ConnectionState.ts
> +  private stateChangeListeners: ConnectionStateChangeListener[] = [];
Done.

2020-11-12 13:42 UTC, joheriks commented
Currently, the global connection state store (`window.Vaadin.Flow.connectionState`) is imported and instantiated via `generated-flow-imports.js` rather than from `Flow.ts`. The sole reason for this is to load it also in V14 bootstrapping mode, where `Flow.ts` is not loaded.

2020-11-16 13:53 UTC, haijian-vaadin requested changes

2020-11-16 13:53 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/component/UI.java
> +@JsModule("@vaadin/flow-frontend/LoadingIndicator.js")
Do we really need this? Isn't the `LoadingIndicator` imported in `Flow.ts`?

2020-11-16 13:59 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/component/UI.java
> +@JsModule("@vaadin/flow-frontend/LoadingIndicator.js")
`Flow.ts` is not loaded in legacy bootstrapping mode. Agree it's not very nice to have a `JsModule` annotation here, open to suggestions for other ways of solving the backwards compatibility issue.

2020-11-17 11:15 UTC, haijian-vaadin approved these changes

2020-11-17 13:35 UTC, merged