feat: Do not allow themeClass and themeName in same annotation
vaadin/flow pull request #9389
Opened 2020-11-12 12:30 UTC by caalador

Theme Class and Theme Name is not supported in
the same Theme annotation as theme name builds
on the Lumo theme.

test-themes is now for testing the Application theme only.
Old theme test was moved into test-misc.

Fixes #9370

2020-11-14 15:57 UTC, mshabarov requested changes

2020-11-14 15:57 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
> +    public void noDefaultThemeAvailable_throwsException()
There should be also a test checking the `theme = getDefaultTheme();` line has been executed and `theme` defaults to LUMO, when the `themeClass` is `null`, but probably this test already exists, where is it then?

2020-11-14 15:57 UTC, mshabarov commented on flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/MiscelaneousView.java
> +}
add a new line

2020-11-16 07:45 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
> +                    theme = getDefaultTheme();
The application theme always bases on lumo and lumo will be set for it.

2020-11-16 07:45 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
>          // theme could be null when lumo is not found or when a NoTheme found
If nothing is defined then everything should work the same as before so not having a theme definition and no lumo on classpath should result in no theme. 
If theme name is defined we will throw that lumo needs to be on the classpath.

2020-11-16 07:45 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
> +            exception.getMessage().startsWith(
done.

2020-11-16 07:45 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
> +    public void noDefaultThemeAvailable_throwsException()
Added a test.

2020-11-16 07:45 UTC, caalador commented on flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/MiscelaneousView.java
> +}
added

2020-11-16 08:34 UTC, mshabarov requested changes

2020-11-16 08:34 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
> +        FrontendDependencies dependencies = new FrontendDependencies(classFinder, false);;
```suggestion
        FrontendDependencies dependencies = new FrontendDependencies(classFinder, false);
```

2020-11-16 08:38 UTC, mshabarov approved these changes

2020-11-16 10:23 UTC, merged