fix!: Store in-memory filtering and sorting in component
vaadin/flow pull request #9391
Opened 2020-11-12 14:57 UTC by mshabarov

In-memory filtering and sorting are now stored directly in component, which gives an opportunity to change it through the data view API for a certain component separately from other components bound to the same data provider.

Related-to: #8655

2020-11-12 17:08 UTC, pleku requested changes
Two copy paste errors (?) as pointed out by sonarqube. I think we could manage even without the methods.

2020-11-12 17:08 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataViewUtils.java
> +     *            component's in-memory sort comparator
apparently this could be null to remove it ?

2020-11-12 17:08 UTC, pleku commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataViewUtils.java
> +            SerializablePredicate<T> filter) {
apparently this could be null to remove it ?

2020-11-12 19:32 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataViewUtils.java
> +     *            component's in-memory sort comparator
Yeah, added the explanations about it

2020-11-12 19:32 UTC, mshabarov commented on flow-data/src/main/java/com/vaadin/flow/data/provider/DataViewUtils.java
> +            SerializablePredicate<T> filter) {
Yeah, added the explanations about it

2020-11-12 19:34 UTC, mshabarov commented
Methods for removing both filter and sorting, and query getter have been extracted to utils as well, so as to remove more boilerplate code from components.

2020-11-13 08:44 UTC, pleku approved these changes

2020-11-16 08:52 UTC, pleku approved these changes

2020-11-16 12:35 UTC, merged