fix: check if Url path is safe in Dev Mode
vaadin/flow pull request #9392
Opened 2020-11-12 19:59 UTC by mshabarov

Checks double encoding in Dev Mode requests paths, and if the given path contains unsafe double encoding, it then doesn't serve the request.

2020-11-13 12:20 UTC, denis-anisimov requested changes

2020-11-13 12:20 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
> +        if (HandlerHelper.isPathUnsafe(requestFilename)) {
Two questions here:

- `serveDevModeRequest`  looks too late for checking.
I think this may be preserved _BUT_ this could be just double check.
- why it sets `HttpServletResponse.SC_NOT_MODIFIED` ? 

Clarification: 
`isDevModeRequest` should be called before `serveDevModeRequest` (if I understand correctly).
The method should return just `false`  and then some other handler will be used to handle a request or some status (404 most likely , but this doesn't matter) will be set.
Double check here can be done but then the code should just throw: since `isDevModeRequest` should be checked first by design and `serveDevModeRequest` shouldn't be ever called.
If it's called then our imp is broken and we should just throw.

2020-11-13 12:20 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +    public static boolean isPathUnsafe(String path) {
If I remember correctly @caalador mentioned that we already has similar code somewhere.
If it's true then the code should be reused (may be extracted as an utility method but then some existing code should be modified as well since it already contains it).

2020-11-13 12:20 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
> +    public static boolean isPathUnsafe(String path) {
Ah, sorry, I just realized that this is exactly done.

Just ignore this.

2020-11-13 12:20 UTC, denis-anisimov commented
Please add a reference to the ticket in the commit message: I can't see which ticket the PR fixes.

2020-11-13 14:10 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
> +        if (HandlerHelper.isPathUnsafe(requestFilename)) {
>The method should return just false and then some other handler will be used to handle a request or some status

I agree to make a path check more early, in `isDevModeRequest`, but if we just return `false` and delegate to another handler, then the path check occurs twice. Is that correct and why not just terminate the request handling?

>why it sets HttpServletResponse.SC_NOT_MODIFIED ?

Good question and I also thinking about that. The response code should reflect the semantics of rejecting the request, some maybe `403 Forbidden` is better here.

>Double check here can be done but then the code should just throw: since isDevModeRequest should be checked first by design and serveDevModeRequest shouldn't be ever called.
If it's called then our imp is broken and we should just throw.

Agree!  `serveDevModeRequest` potentially could be called directly, because it's public, so let double check and throw if needed.

2020-11-16 07:03 UTC, denis-anisimov requested changes

2020-11-16 07:03 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
> +    public static Collection<String> pathsWithDirectoryChange() {
I would rename the method to have different name than `pathsWithDirectoryChange`: they have quite different nature (at least the types are different) event though they are connected.

Another thing : I'm pretty sure that `DevModeHandlerTest` should not be made parameterized .
As I understand when you parameterize the class its instance is created per every parameter _AND_ for every test method.
So if you have `N` parameters and `M` test methods then there will be `N*M` executed tests.
Since this class contains tests which don't need any parameters this is very excessive and will increase the time of execution dramatically.

So: either the method should accept parameter and there should be just one test method per parameter (hardcoded) or the class should be refactored to contain only test methods which really requires parameters.

2020-11-16 07:03 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
> +    public static Collection<String> paths() {
Same thing here: check whether this class should be refactored

2020-11-17 16:10 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
> +    public static Collection<String> paths() {
done

2020-11-17 16:10 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
> +    public static Collection<String> pathsWithDirectoryChange() {
done

2020-11-18 05:45 UTC, denis-anisimov requested changes

2020-11-18 05:45 UTC, denis-anisimov commented on flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/UrlValidationIT.java
> +public class UrlValidationIT extends ChromeBrowserTest {
`test-root-context`  doesn't use dev mode.
it compiles the resources and web pack dev server is not started.

It should not be changed because these tests are used for OSGi which is not able to run webpack dev server at all.
So the IT which relies on webpack dev server will fail there.

There are a bunch of modules which are executed in dev mode. E.g. `test-dev-mode`  which is explicitly made for dev mode. Please use another module for the test.

2020-11-18 08:46 UTC, mshabarov commented on flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/UrlValidationIT.java
> +public class UrlValidationIT extends ChromeBrowserTest {
Moved to test-dev-mode, thanks!

2020-11-18 10:48 UTC, denis-anisimov approved these changes

2020-11-18 10:59 UTC, merged