WIP: feat(offline): add connection indicator element
vaadin/flow pull request #9396
Opened 2020-11-13 18:06 UTC by platosha

Fixes #9322

2020-11-17 07:55 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/ConnectionIndicator.ts
> +  private loadingThird: boolean = false;
Would it be better to have a single property of a type that restricts the possible states (such as `0|1|2|3` or enum)?

2020-11-18 10:57 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/ConnectionIndicator.ts
> +    }`, document.head);
Is this safe? The doc for `render` states `The entire contents are either replaced, or efficiently updated if the same result type was previous rendered there`. I got some weird broken styles when trying this with basic starter.

2020-11-18 11:15 UTC, platosha commented on flow-client/src/main/resources/META-INF/resources/frontend/ConnectionIndicator.ts
> +    }`, document.head);
Right, changing this to just adding the styles to head.

2020-11-18 13:03 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
> +    $wnd.Vaadin.loadingIndicator = document.createElement('vaadin-connection-indicator');
For consistency, maybe we could rename `window.Vaadin.loadingIndicator` now also to `window.Vaadin.connectionIndicator`.

2020-11-18 13:31 UTC, platosha commented on flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
> +    $wnd.Vaadin.loadingIndicator = document.createElement('vaadin-connection-indicator');
Done.

2020-11-18 13:57 UTC, joheriks commented
It seems to show the temporary "Online" banner when loading the app in the browser the first time and when refreshing, maybe not the best UX.

2020-11-18 15:00 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/ConnectionIndicator.ts
> +      this.offline = state === ConnectionState.CONNECTION_LOST
Perhaps `state === ConnectionState.CONNECTION_LOST || state === ConnectionState.RECONNECTING` alternatively `this.connectionStateStore.offline`? Else it will show "Online" text for reconnecting state.

2020-11-18 16:26 UTC, platosha commented on flow-client/src/main/resources/META-INF/resources/frontend/ConnectionIndicator.ts
> +      this.offline = state === ConnectionState.CONNECTION_LOST
I realised it’s cleaner to fix `renderMessage` instead, so done that way.

2020-11-18 16:26 UTC, platosha commented
> It seems to show the temporarily expanded "Online" banner when loading the app in the browser the first time and when refreshing, maybe not the best UX. Analogously, when browser is offline and reloading maybe the "Connection lost" banner would not need to be expanded.

Fixed.

2020-11-18 21:12 UTC, joheriks requested changes

2020-11-18 21:16 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/ConnectionIndicator.ts
> +  offlineText: string = 'Connection lost'
Maybe terminate by `,` for consistency.

2020-11-18 21:29 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/ConnectionIndicator.ts
> +    this.offline = state === ConnectionState.CONNECTION_LOST
Maybe terminate by `;` for consistency.

2020-11-18 21:31 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/ConnectionIndicator.ts
> +        : this.onlineText
Maybe terminate by `;` for consistency. 
Not blocking, but is this more readable than an `if-else` statement?

2020-11-20 12:37 UTC, joheriks approved these changes

2020-11-23 13:23 UTC, joheriks approved these changes

2020-11-23 13:27 UTC, joheriks approved these changes

2020-11-23 15:08 UTC, merged