feat: Only handle annotated theme
vaadin/flow pull request #9406
Opened 2020-11-16 08:29 UTC by caalador

Now we only handle the theme with
the name inside the Theme annotation.

Fixes #9383

2020-11-16 13:32 UTC, pleku requested changes

2020-11-16 13:32 UTC, pleku commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +
So now when _theme-name_ is discovered from both inside a `.jar` and inside the `/theme/` folder in the project both will be loaded. While I cannot figure out at the moment why it would be a bad thing yet, the _spec_ says that when you have something inside a `.jar`, it should be used from there. If you have something inside  the `/theme/` folder in the project, it should be used there. But not both. If the in-project theme defines a parent theme, that should be loaded before the in-project theme.

So we should probably decide (and document) how it goes when you have this situation that the theme is present both in-project and inside a .jar.

2020-11-16 13:32 UTC, pleku commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +
Probably throwing and instructing the in-project theme to use the parent theme inside theme.json is the thing to do.

In context of this ticket, maybe it would be fine to just first check the in-project location and if it is not there, then the `.jar`. Or even now the `.jar` could be commented out until we re-enable it with parent theme support ...

2020-11-17 09:55 UTC, caalador commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +
Only handling frontend theme and trowing if found also from "jar"

2020-11-17 09:55 UTC, caalador commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +        logger.log("No '", generatedThemeFile, "' found. Skipping application theme handling.");
Changed log level and added extra trace with more information.

2020-11-17 11:08 UTC, pleku requested changes

2020-11-17 11:08 UTC, pleku commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +              "If extending the jar theme the 'parent' theme feature should be used");
> "If extending the jar theme the 'parent' theme feature should be used")

I'm not sure if this is enough for anyone who doesn't know about the it already. Maybe
"Extending another theme is possible by adding `{ "parent": "my-parent-theme" }`  entry to the theme.json file inside your theme's folder." would be explicit

2020-11-17 11:15 UTC, caalador commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +              "If extending the jar theme the 'parent' theme feature should be used");
👍

2020-11-17 13:28 UTC, pleku approved these changes

2020-11-17 13:31 UTC, merged