feat: TypeScript API for connection indicator configuration
vaadin/flow pull request #9427
Opened 2020-11-17 15:42 UTC by joheriks

Needs rebasing and update to align with #9396.

Fixes #9402.

2020-11-19 08:31 UTC, haijian-vaadin requested changes

2020-11-19 08:31 UTC, haijian-vaadin commented on flow-client/src/main/resources/META-INF/resources/frontend/AppShell.ts
> +/* tslint:disable: max-classes-per-file */
Maybe it's better to put this at the top of the file

2020-11-19 08:31 UTC, haijian-vaadin commented on flow-client/src/main/resources/META-INF/resources/frontend/index.ts
> +export * from './ConnectionIndicator';
Could also add Appshell.ts here?

2020-11-19 09:16 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/AppShell.ts
> +/* tslint:disable: max-classes-per-file */
Done.

2020-11-19 09:16 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/index.ts
> +export * from './ConnectionIndicator';
Done.

2020-11-19 12:09 UTC, haijian-vaadin requested changes

2020-11-19 12:09 UTC, haijian-vaadin commented on flow-client/src/main/resources/META-INF/resources/frontend/AppShell.ts
> +class ConnectionIndicatorConfigurationImpl implements ConnectionIndicatorConfiguration {
Maybe DefaultConnectionIndicatorConfiguration would be better than ConnectionIndicatorConfigurationImpl?

2020-11-19 12:09 UTC, haijian-vaadin commented on flow-client/src/main/resources/META-INF/resources/frontend/AppShell.ts
> +  onlineText?: string;
Could we have some inline doc for the class and the properties?

2020-11-23 16:19 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/AppShell.ts
> +class ConnectionIndicatorConfigurationImpl implements ConnectionIndicatorConfiguration {
Renamed to `ConcreteConnectionIndicatorConfiguration` instead (to avoid potentialconfusion with default configuration values, which are defined in the `ConnectionIndicator` component). There is now duplication of properties here---maybe we should consider whether we really need this intermediate configuration DTO, or if we instead could consider the `ConnectionIndicator` the public configuration interface instead.

2020-11-23 16:20 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/AppShell.ts
> +  onlineText?: string;
Done. However, there is now duplication of properties and documentation here. Maybe we should consider whether we really need this intermediate configuration DTO, or if we instead could consider the `ConnectionIndicator` the public configuration interface instead.

2020-11-24 09:36 UTC, haijian-vaadin submitted a review, later dismissed
Cool, really works nicely now

2020-11-24 09:36 UTC, haijian-vaadin commented on flow-client/src/main/resources/META-INF/resources/frontend/ConnectionIndicator.ts
> +      active: this.reconnecting,
indentations missing?

2020-11-24 10:05 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/ConnectionIndicator.ts
> +      active: this.reconnecting,
Done (apparently this was too difficult for my IDE to auto-indent properly).

2020-11-24 18:50 UTC, haijian-vaadin approved these changes

2020-11-25 08:00 UTC, merged