feat: Serve theme static files from VAADIN/static
vaadin/flow pull request #9451
Opened 2020-11-20 09:58 UTC by caalador

Static files in META-INF/VAADIN/static will now be served
on request to VAADIN/static.
Added new webpack loader that changes app theme
css urls targeting ./ to be VAADIN/static/ instead.

Fixes #9405

2020-11-20 10:18 UTC, knoobie commented on flow-tests/test-themes/frontend/theme/app-theme/global.css
> +    background-image: url("./img/bg.jpg");
Isn't that exactly the opposite of https://github.com/vaadin/flow/issues/9430?  @pleku

2020-11-20 10:34 UTC, caalador commented on flow-tests/test-themes/frontend/theme/app-theme/global.css
> +    background-image: url("./img/bg.jpg");
hmm... but now it's a direct reference from the css file so IDEA can for instance auto complete and validate the reference file.

2020-11-20 10:50 UTC, knoobie commented on flow-tests/test-themes/frontend/theme/app-theme/global.css
> +    background-image: url("./img/bg.jpg");
That's a convenient for developer for "small" projects but can be a huge burden for dev or ops teams in bigger projects when you have requirements to load images from something outside of app. 

At least this "magic" should be configurable(opt-out) if that's something you need to have for vaadin's DX.

2020-11-20 12:09 UTC, caalador commented on flow-tests/test-themes/frontend/theme/app-theme/global.css
> +    background-image: url("./img/bg.jpg");
Updated so that we only change the url if the file actually exists relative to the css being handled.

2020-11-20 12:30 UTC, knoobie commented on flow-tests/test-themes/frontend/theme/app-theme/global.css
> +    background-image: url("./img/bg.jpg");
Interesting idea! 

Just a test case to verify: Project setup: Vaadin + Spring Boot 

`resources/public/img/first.png`
`resources/META-INF/VAADIN/static/img/second.jpg`
`resources/VAADIN/themes/my-theme/global.css`

global.css:
```css
body {
 background-image: url("./img/my-image.png");
}
main {
 background-image: url("./img/second.jpg");
}
```

Spring boot would serve the image `my-image.png` because it is inside the `public` folder. Now your change would not change the background-image of the css because `my-image.png` isn't reachable for webpack. And the background-image of main would be rewritten and of course served successfully. Correct?

2020-11-20 12:44 UTC, caalador commented on flow-tests/test-themes/frontend/theme/app-theme/global.css
> +    background-image: url("./img/bg.jpg");
The theme-loader will now actually check that the file exists relative to the css file handled so: if it can find the file resources/VAADIN/themes/my-theme/img/second.jpg it will be rewritten with VAADIN/static else it's seen as "external" and supplied by someone else.

2020-11-20 12:50 UTC, knoobie commented on flow-tests/test-themes/frontend/theme/app-theme/global.css
> +    background-image: url("./img/bg.jpg");
That was the missing piece, thanks!

2020-11-20 13:15 UTC, pleku requested changes

2020-11-20 13:15 UTC, pleku commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
> + * copy theme files  to static assets folder.
maybe clarify what theme files will be copied

2020-11-20 13:15 UTC, pleku commented on flow-server/src/main/resources/plugins/theme-loader/theme-loader.js
> +    // for some reason this matcher can not be reused as a constant
I think to be reused you would have to make a `new Regexp(...)`

2020-11-20 13:15 UTC, pleku commented on flow-tests/test-themes/frontend/theme/app-theme/global.css
> +    background-image: url("./img/bg.jpg");
Lets add another test which verifies that `url("../icons/icon.png"); or similar works

2020-11-23 05:53 UTC, caalador commented on flow-tests/test-themes/frontend/theme/app-theme/global.css
> +    background-image: url("./img/bg.jpg");
Here we have a small problem in that we won't accept static serving for anything that contains `../`
What we could do would be to accept navigation inside the theme folder and rewrite those to be absolute to the file target so we wouldn't have ../ e.g. `../icons/icon.png`  would fail from `/app-theme/global.css`, but would be rewritten to `icons/icon.png` in `app-theme/sub/extras.css`

2020-11-23 08:50 UTC, pleku commented on flow-tests/test-themes/frontend/theme/app-theme/global.css
> +    background-image: url("./img/bg.jpg");
Another option could be to use a magic URL thingy there like `theme://` but not sure if it should resolve to 
1) to the `theme/` folder
2) to the currently active theme
Usually it should resolve to 2) but in some cases when you're creating a reusable theme it should refer to the parent theme and not the currently active theme ... so probably this is just unnecessary complication and thus a bad idea.

I think using e.g. `../icons/icon.png` is common so if we can just automatically handle it, lets go with that.
For Java code, we'll expect people to anyway use the full path `"frontend/theme/my-theme/icons/icon.png"`.

One thing to note, even though it is not directly part of this issue, that the npm-based imports it is supposed to work with:
`"foobar/images/image.png"` when the package has been declared to be imported in `theme.json`. These URLs should not be touched even though they are not "external".

2020-11-23 10:47 UTC, caalador commented on flow-server/src/main/resources/plugins/theme-loader/theme-loader.js
> +    // for some reason this matcher can not be reused as a constant
In the end the main matcher was updated so that we get the url part directly from there.

2020-11-23 10:55 UTC, caalador commented on flow-tests/test-themes/frontend/theme/app-theme/global.css
> +    background-image: url("./img/bg.jpg");
in the format `"foobar/images/image.png"` they won't be touched. Only `./`is handled.

2020-11-23 12:45 UTC, pleku requested changes

2020-11-23 12:45 UTC, pleku commented on flow-tests/test-themes/frontend/theme/app-theme/sub-css/sub.css
> +    background: url('./../icons/archive.png') left top;
As looking at `url(...)` examples from MDN, it has
```css
list-style-image: url('../images/bullet.jpg');
```
so I think we should be able to have the same, `../` is less things to type than `./../`.

2020-11-23 12:45 UTC, pleku commented on flow-server/src/main/resources/plugins/theme-loader/theme-loader.js
> +const urlMatcher = /(url\()(\'|\")?(\.\/)(\S*)(\2\))/g;
So this IMO should handle `../` too and not just `./`

2020-11-23 13:08 UTC, caalador commented on flow-server/src/main/resources/plugins/theme-loader/theme-loader.js
> +const urlMatcher = /(url\()(\'|\")?(\.\/)(\S*)(\2\))/g;
Added now with more \ and /

2020-11-23 13:08 UTC, caalador commented on flow-tests/test-themes/frontend/theme/app-theme/sub-css/sub.css
> +    background: url('./../icons/archive.png') left top;
done

2020-11-23 13:13 UTC, pleku approved these changes

2020-11-24 06:09 UTC, merged