Dropping logging level from warn to debug
vaadin/flow pull request #9473
Opened 2020-11-23 16:55 UTC by TatuLund

We have encountered real-life scenario, where these warnings pollutes logs in excessive manner. As it is normal conditions harmless note, it does not warrant warn level, I am proposing to change to debug level.

"Currently in our server production log, 80% is filled with this and we will have hard time monitoring our application."

Fixes: https://github.com/vaadin/flow/issues/8848

2020-11-23 16:57 UTC, Legioth commented
If dropping the logging level, then maybe only one step to `info` instead? Those warnings can be highly relevant especially for someone debugging cases when their own component isn't updating the server as expected.

2020-11-24 08:14 UTC, pleku requested changes
Agreed, `info` is better than debug.
If someone is looking to cut down the amount of logs, info level is already too noisy for that.
And as this is still kind of a sign of some "extra communication" between client->server that is not necessary, one should be able to take note about it without setting the level to debug.

2020-11-25 10:12 UTC, pleku approved these changes

2020-12-07 14:39 UTC, pleku commented
So after some investigation it would seem that the best thing to do would be to address any warnings that result from disabled Vaadin components individually - thus the warning level should stay there as it is not as intended. There is at least one case for TextField, NumberField, DataPicker, TimePicker BigDecimalField ... where it is just not working right and producing the warning because it is not working properly - and this should be fixed instead. Working on that at the moment and closing this PR.

2020-12-07 14:39 UTC, closed without merging