fix: optimize handling of requests containing Range header
vaadin/flow pull request #9484
Opened 2020-11-24 17:10 UTC by joheriks

More efficient parsing of the Range: header value. Also, range count is capped at 16
(additional will be ignored) and overlapping ranges at 2 (request will be denied
if above).

2020-11-25 05:54 UTC, denis-anisimov requested changes

2020-11-25 05:54 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
> +            "^bytes=(([0-9]*-[0-9]*\\s*,\\s*)*[0-9]*-[0-9]*\\s*)$");
`[0-9]` is `\d`.
The expression will become shorter.

2020-11-25 05:54 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
> +            for (Pair<Long, Long> accepted : ranges) {
unnecessary `for` inside `while` : please refactor

2020-11-25 05:54 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
> +        while (rangeMatcher.find() && ranges.size() < MAX_RANGE_COUNT) {
What happens if `ranges.size() >= MAX_RANGE_COUNT`?
There is no mistake set. The processing goes in happy path.
This is not the same as check for `overlappingRangeCount` which fails the request processing.

2020-11-25 05:54 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
> +        while (rangeMatcher.find() && ranges.size() < MAX_RANGE_COUNT) {
Ah, is it covered by the case that `end < start`?

I would may be refactor this a bit and log an error message depending on what happened (instead of one big `if`).
That will also help to avoid comments: log messages will be self documented.

2020-11-25 09:38 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
> +        while (rangeMatcher.find() && ranges.size() < MAX_RANGE_COUNT) {
According to the [RFC](https://tools.ietf.org/html/rfc7233#section-6.1), it is acceptable for the server to either drop some ranges or outright reject a request when ranges are out-of-order or overlapping. My implementation was inconsistent in the handling of too many ranges compared to too many overlapping range. In the case of a benevolent client (that happened to asks too many ranges or too many overlapping ranges), it is probably better to serve the maximum amount rather than outright deny the request. I have amended the implementation to serve only the ranges processed so far when hitting more than 2 overlapping ranges. Also added logging.

2020-11-25 09:39 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
> +            for (Pair<Long, Long> accepted : ranges) {
Done. Moved the limit checks to a separate method.

2020-11-25 09:40 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
> +            "^bytes=(([0-9]*-[0-9]*\\s*,\\s*)*[0-9]*-[0-9]*\\s*)$");
Done.

2020-11-25 11:54 UTC, denis-anisimov approved these changes

2020-11-25 11:54 UTC, merged

2021-01-26 14:50 UTC, mshabarov commented
Cherry picked to `2.5`