chore: move fusion code to fusion-server module
vaadin/flow pull request #9499
Opened 2020-11-25 20:34 UTC by haijian-vaadin

move fusion code to a separate fusion-server module, so that the fusion dependencies which are not OSGi compatible can be removed from the flow-server module.

2020-11-26 09:06 UTC, denis-anisimov requested changes

2020-11-26 09:06 UTC, denis-anisimov commented on fusion-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/collectionendpoint/expected-model-collectionendpoint.CollectionEndpoint.Collection.ts
> +}
new line OR is it generated ?

2020-11-27 11:07 UTC, haijian-vaadin commented on fusion-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/collectionendpoint/expected-model-collectionendpoint.CollectionEndpoint.Collection.ts
> +}
generated, the same as in flow-server, I think one of them could be removed in the end

2020-11-27 11:07 UTC, haijian-vaadin commented on flow-server/pom.xml
>          <dependency>
updated, does it look good now?

2020-12-01 07:28 UTC, denis-anisimov requested changes

2020-12-01 07:28 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateEndpointBase.java
> +public interface TaskGenerateEndpointBase extends FallibleCommand {
Not sure the final usage of this interface but it seems the methods with the return type should return the class and not its superclass.

So may be it should be 
```
TaskGenerateEndpointBase<T extends TaskGenerateEndpointBase> extends FallibleCommand{

T withApplicationProperties(File applicationProperties);
}
```

2020-12-01 07:28 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateEndpointBase.java
> +public interface TaskGenerateEndpointBase extends FallibleCommand {
Another thing which I would recommend: methods `withXXX` are good for builders.
These are commands, not builders.

I would  make factories instead which produces the command. 
Factory should accept paramer(s) and produces the command instance.

The only issue which I see here: there should be only one method. It means the fixed amount of parameters.
So factories extending has no sense.
Instead I would may be make builder (which may extends one each other) and the builder may produce an immutable instance of configuration which will be passed to a factory.

2020-12-01 07:28 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateOpenApi.java
> +public interface TaskGenerateOpenApi extends TaskGenerateEndpointBase {
same comments as above for `TaskGenerateEndpointBase`.

2020-12-01 07:28 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
> +                new File(baseDir), lookup, new File(generatedDir),
This code and code below assumes that connect will be available and configured.
(see `withConnectApplicationProperties`, etc...).

The proper logic should check whether a service is available and the configure it only if it's available.

2020-12-01 07:31 UTC, denis-anisimov commented on flow-server/pom.xml
>          <dependency>
Looks good now

2020-12-01 08:04 UTC, haijian-vaadin commented on flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
> -    public void mavenGoal_generateOpenApiJson_when_itIsInClientSideMode()
It's moved to `BuildFrontendMojoEndpointTest.java`, the `BuildFrontendMojoEndpointTest.java` is currently ignored though, need some work to make it pass.

2020-12-02 07:25 UTC, haijian-vaadin commented on flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
> +            Lookup lookup= new LookupImpl(classFinder);
Done, but couldn't make a non-args, since it depends on a private filed
(`private MavenProject project; `) to get the class finder.

2020-12-02 07:25 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +        public Builder(ClassFinder classFinder, File npmFolder, Lookup lookup) {
done

2020-12-02 07:26 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateEndpointBase.java
> +public interface TaskGenerateEndpointBase extends FallibleCommand {
I removed this unnecessary interface.

2020-12-02 07:27 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateEndpointBase.java
> +public interface TaskGenerateEndpointBase extends FallibleCommand {
Good point, I removed those `withXXX` methods, use a `init()` method instead, in this way, we also don't need the factory.

2020-12-02 07:27 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateOpenApi.java
> +public interface TaskGenerateOpenApi extends TaskGenerateEndpointBase {
done

2020-12-02 07:36 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
> +                new File(baseDir), lookup, new File(generatedDir),
Add logic to check if endpoint services are available before running endpoint related logic

2020-12-02 07:50 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateEndpointBase.java
> +public interface TaskGenerateEndpointBase extends FallibleCommand {
`init` method may be better than `withXxx` but it's also an evil.

`init` method is a weak API: `public` method means that the method may be called by _anyone_ at _any time_.
So your intention with `init` method is to define a contract which says: this method should be called once.
But you don't define such contract via Java : as I said the method is `public` and can be called many times by anyone who has an access to the instance.

May be in this case since the instance is "private" it's not an issue.
But I'm pretty sure that you may replace easily `init` with a factory `create`(or whatever), it's almost the same with one significant difference: `init` may be called any number of times , CTOR may be called _only once_.
So it's always better to create some new instance via CTOR with arguments instead of `init` method with same arguments.
The only difference is : to be able to call CTOR you will need a factory (which can be created with a default CTOR) and then create a required instance via a factory method which instantiate an instance via CTOR instead of calling `init` on the required instance right away.

So it's better to use factories instead of ugly `init` method: it defines good clear contract via Java without any additional assumption.

2020-12-04 09:21 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateEndpointBase.java
> +public interface TaskGenerateEndpointBase extends FallibleCommand {
done

2020-12-04 10:57 UTC, denis-anisimov requested changes
There are still things which may be improved.
Though things are done properly considering the required architecture decision (and current limitations with ugly `Builder` class).

Only some things related to the implementation.

I've not reviewed unit tests since they are related to the Fusion fincitonality.
These should be reviewed by the Fusion team.
But some introduced API usage looks untested (in DevModeInitializer) : this is an architectural issue.

2020-12-04 10:57 UTC, denis-anisimov commented on flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
> +        new NodeTasks.Builder(lookup, classFinder,
I would may be avoid passing `ClassFinder`  as a separate parameter here and everywhere.

Lookup may be created so that it may return the `ClassFinder` by `ClassFinder.class`.
You may implement this by yourself here or wait for https://github.com/vaadin/flow/pull/9572 where I introduced two static methods into Lookup which allows to extend it.

But this is not very important.

2020-12-04 10:57 UTC, denis-anisimov commented on flow-maven-plugin/src/main/java/com/vaadin/flow/utils/LookupImpl.java
> +        return lookupAll(serviceClass).stream().findFirst().orElse(null);
Here you may add directly a special case for `ClassFinder.class`.

2020-12-04 10:57 UTC, denis-anisimov commented on flow-server/pom.xml
> +            <groupId>com.fasterxml.jackson.core</groupId>
Have you checked that these deps don't break OSGi ?
Do they have proper OSGi manifest ?

2020-12-04 10:57 UTC, denis-anisimov commented on flow-server/pom.xml
> +            <groupId>com.fasterxml.jackson.core</groupId>
By the way : why they are needed ?

2020-12-04 10:57 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java
> +     * Check if a class can be instantiated as a service or not.
Would be good to improve javadoc.
It should explain what the service is: this is a static check whether a class may be instantiated via its default CTOR via reflection. static check means that the CTOR may throw an exception and this is not checked but only possibility to instantiate the class based on type data

2020-12-04 10:57 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +        public Builder(Lookup lookup, ClassFinder classFinder, File npmFolder) {
I suggest to skip `ClassFinder`  passing as a parameter here (and everywhere).

2020-12-04 10:57 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/EndpointGeneratorTaskFactory.java
> +     * @return an endpoint tasks for generating TypeScript files for endpoints.
`create` implies that the return value won't be `null`  but anyway please add to the `@return` that it's never `null`

2020-12-04 10:57 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
> +        if (lookup == null) {
This is technically extra check.
The lookup is never `null` here.

2020-12-04 10:57 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
> -    public void should_generateOpenApi_when_EndpointPresents()
Should these test be really removed ?
Are they moved somewhere else ?
Should there be some replacement ?

E.g. now there is no need to check the functionality (integration: something is generated and so on).
But you may check that some methods of classes that are in the lookup are called: e.g. factory is called.
And also objects produced by the factory are called somehow (doesn't matter what they do but they are called).

2020-12-04 10:57 UTC, denis-anisimov commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/frontend/fusion/EndpointGeneratorTaskFactoryImpl.java
> +    public TaskGenerateConnect createTaskGenerateConnect(File applicationProperties, File openApi,
Up to you , but I would may be add checks that arguments are not `null` (if they should not be `null` ).
And javadocs should be extended so it mentions which arguments are allowed to be `null` and which not.

2020-12-04 10:57 UTC, denis-anisimov commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/frontend/fusion/TaskGenerateConnectImpl.java
> +    private File outputFolder;
I think all (or most) fields may be set `final`.

2020-12-04 10:57 UTC, denis-anisimov commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/frontend/fusion/TaskGenerateOpenApiImpl.java
> +    private File javaSourceFolder;
All fields are most likely `final`.

2020-12-04 10:57 UTC, denis-anisimov commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/frontend/fusion/TaskGenerateOpenApiImpl.java
> +    private transient ClassLoader classLoader;
Do you need this class to be `Serializable`?
Does this class even implements `Serializable`.

I think the class should not be `Serializable` : it's not stored anywhere.

So if the class is serializable then you should care about `transient` fields: they won't be restored after deseriallization.
If class should not be serialzable then `transient` is not needed here.

2020-12-04 10:59 UTC, denis-anisimov commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/frontend/fusion/EndpointGeneratorTaskFactoryImpl.java
> +    public TaskGenerateConnect createTaskGenerateConnect(File applicationProperties, File openApi,
I see you have some checks for parameters in the CTOR.
But : is it enough?
And anyway the javadocs doesn't say anything about that.

2020-12-04 12:22 UTC, haijian-vaadin commented on flow-server/pom.xml
> +            <groupId>com.fasterxml.jackson.core</groupId>
They are used in the [JsonUtils](https://github.com/vaadin/flow/blame/feature/offline/flow-server/src/main/java/com/vaadin/flow/internal/JsonUtils.java#L34), there will be compile errors without them.

How do I check the OSGi manifest?

2020-12-04 12:24 UTC, haijian-vaadin commented on flow-server/pom.xml
> +            <groupId>com.fasterxml.jackson.core</groupId>
I tried to run the testing project, looks like it works fine

2020-12-04 12:49 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
> -    public void should_generateOpenApi_when_EndpointPresents()
The tests were moved to [DevModeInitializerEndpointTest](https://github.com/vaadin/flow/blob/haijian/fusion-server-module/fusion-endpoint/src/test/java/com/vaadin/flow/server/startup/fusion/DevModeInitializerEndpointTest.java)

2020-12-04 12:55 UTC, haijian-vaadin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/frontend/fusion/TaskGenerateOpenApiImpl.java
> +    private transient ClassLoader classLoader;
Done, it was inherited from the existing code, now removed.

2020-12-04 12:55 UTC, haijian-vaadin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/frontend/fusion/TaskGenerateOpenApiImpl.java
> +    private File javaSourceFolder;
done

2020-12-04 12:55 UTC, haijian-vaadin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/frontend/fusion/TaskGenerateConnectImpl.java
> +    private File outputFolder;
done

2020-12-04 12:58 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
> -    public void should_generateOpenApi_when_EndpointPresents()
True, good point, I will add tests to verify that certain methods get called

2020-12-04 13:35 UTC, haijian-vaadin commented on flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
> -    public void should_generateOpenApi_when_EndpointPresents()
Done

2020-12-04 17:09 UTC, platosha requested changes

2020-12-07 06:23 UTC, denis-anisimov commented on flow-server/pom.xml
> +            <groupId>com.fasterxml.jackson.core</groupId>
The manifest should have a number of entries like 
`Bundle-SymbolicName: com.vaadin.flow.server`
`Export-Package: com.vaadin.flow.component`,
....

But if everything works in OSGi container it means that manifest is correct.

2020-12-07 06:28 UTC, denis-anisimov commented on flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
> +            Lookup lookup= new LookupImpl(classFinder);
I thought the classes have( or could have) a common superclasess where the field may be used (may be as a protected field even though I don't like protected). And then it will be possible.
But that's minor.

2020-12-08 06:55 UTC, haijian-vaadin commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/frontend/fusion/EndpointGeneratorTaskFactoryImpl.java
> +    public TaskGenerateConnect createTaskGenerateConnect(File applicationProperties, File openApi,
done, added null check

2020-12-08 06:57 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +        public Builder(Lookup lookup, ClassFinder classFinder, File npmFolder) {
Removed the ClassFinder parameter, use Lookup to look for ClassFinder

2020-12-08 06:57 UTC, haijian-vaadin commented on flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java
> +     * Check if a class can be instantiated as a service or not.
updated the java doc

2020-12-08 06:58 UTC, haijian-vaadin commented on flow-maven-plugin/src/main/java/com/vaadin/flow/utils/LookupImpl.java
> +        return lookupAll(serviceClass).stream().findFirst().orElse(null);
didn't make it a special case, but instead using Lookup.compose() when creating the Lookup

2020-12-08 06:58 UTC, haijian-vaadin commented on flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
> +        new NodeTasks.Builder(lookup, classFinder,
done

2020-12-08 10:11 UTC, denis-anisimov reviewed
I'm fine with the code now.

As mentioned : the business logic should be reviewed by the Fusion team (and the approval should go from there).

From the architectural point of view it's OK for me.

2020-12-08 10:21 UTC, platosha approved these changes

2020-12-08 11:04 UTC, merged