feat: Enable importing CSS from node_modules
vaadin/flow pull request #9543
Opened 2020-11-30 17:18 UTC by tanbt

Allow importing CSS files as global styles from installed node_modules by adding the `importCss` to theme/my-theme/theme.json.

Fixes #9410

2020-12-01 06:20 UTC, caalador commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
>   * @param {string} themeName name of the handled theme
No added param documentation for themeProperties.

2020-12-01 06:20 UTC, caalador commented on flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
> -            driver.getPageSource().contains("HTTP ERROR 404 Not Found"));
Lots of unrelated formatting changes in the test file.
Could you check the TeamWiki Code style section. indentation at least seems different

2020-12-01 06:28 UTC, caalador commented
webpack.generated.js might need to have in css-loader also the part:
```

              import: (url, media, resourcePath) => {
                // resourcePath - path to css file
                // If the import happens from within a node_modules file, we must resolve and inline. Otherwise resources will not be found at runtime as node_modules is not deployed
                return resourcePath.includes('/node_modules/');
              }
```

2020-12-01 07:49 UTC, tanbt commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
>   * @param {string} themeName name of the handled theme
Added.

2020-12-01 07:50 UTC, tanbt commented on flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
> -            driver.getPageSource().contains("HTTP ERROR 404 Not Found"));
Reverted. My formatter setting was disappear somehow.

2020-12-01 09:16 UTC, caalador commented
Perhaps it needs the rule:
```
      {
        // File-loader only copies files used as imports in .js files
        test: /\.(png|gif|jpg|svg|eot|woff|woff2|ttf)$/,
        use: [ {
          loader: 'file-loader',
          options: {
            outputPath: '../resources/VAADIN/static/',
            name: '[name].[ext]'
          }
        }],
      },
```

2020-12-01 10:05 UTC, caalador commented
You are missing the file-loader from NodeUpdater getDefaultDevDependencies
Guess it can be "file-loader", "6.1.0"

2020-12-01 10:48 UTC, caalador commented
It would be good to run the tests locally to see that all pass as now there is " in the actual string gotten from the browser which was not expected by the test. 
For the second failure you should set the webpack logging to have debug and see that the subcss is handled by the theme-loader

2020-12-01 11:17 UTC, tanbt commented
Is it possible to test only the `test-themes` module?
I used
```
cd flow-tests/test-themes
mvn test
```
but looks like no test is executed.

2020-12-02 06:33 UTC, caalador commented on flow-server/src/main/resources/webpack.generated.js
> +                    || resourcePath.includes('/frontend/theme/');
This has the problem that "external" url's are not filtered out making it fail as the files can not be found.

2020-12-02 06:33 UTC, caalador commented on flow-server/src/main/resources/webpack.generated.js
> +            outputPath: '../resources/VAADIN/static/',
This was my mistake, but the output path should be `outputPath: 'static/',` also I can't get this to actually copy anything.

2020-12-02 07:57 UTC, tanbt commented on flow-server/src/main/resources/webpack.generated.js
> +                    || resourcePath.includes('/frontend/theme/');
Added a check to skip external URL.

2020-12-02 07:57 UTC, tanbt commented on flow-server/src/main/resources/webpack.generated.js
> +            outputPath: '../resources/VAADIN/static/',
Fixed.
I can still see files are copied to `target\classes\META-INF\VAADIN\static` when using `outputPath: '../resources/VAADIN/static/'`.

2020-12-02 08:41 UTC, caalador commented on flow-server/src/main/resources/webpack.generated.js
> +            outputPath: '../resources/VAADIN/static/',
that's because it's not file-loader that is doing the copying.

2020-12-02 08:52 UTC, caalador commented on flow-server/src/main/resources/webpack.generated.js
> +                    || resourcePath.includes('/frontend/theme/');
Only `http://` doesn't mean external also `./served/by/server` or `/absolute` is external from the view of the theme see test module octopuss and monarch-butterfly

2020-12-02 09:22 UTC, caalador commented
As I look at this it might be that the feature was fine at commit d8474de and that it's the test that is wrong as the font icons style sheet probably needs to be in the head and not where it lands with this PR.

2020-12-03 07:28 UTC, tanbt commented on flow-server/src/main/resources/webpack.generated.js
> +                    || resourcePath.includes('/frontend/theme/');
Will update with https://github.com/vaadin/flow/pull/9558.

2020-12-03 07:31 UTC, tanbt commented
> style sheet probably needs to be in the head

Do you mean the stylesheet should be in a `<link rel="stylesheet" ...>` and placed at `target.head`? 
I tried locally but a link like `<link rel="stylesheet" src="@fortawesome/fontawesome-free/css/all.css">` can't be resolved.

2020-12-03 07:35 UTC, caalador commented on flow-server/src/main/resources/webpack.generated.js
> +                    || resourcePath.includes('/frontend/theme/');
Let's take in 9558 and you can rebase the fix on that.

2020-12-03 07:54 UTC, caalador commented
see #9559 for a working fontawesome test

2020-12-07 04:55 UTC, caalador commented on flow-tests/test-themes/frontend/theme/app-theme/global.css
> +    background-image: url("/path/test/path/monarch-butterfly.jpg");
As this should stay unchanged the path should get path from the application as it should be requested with the application context. There is a test that `./` should match `RootUrl+/path` when executed in browser context.

2020-12-07 06:41 UTC, caalador requested changes

2020-12-07 06:41 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +        defaults.put("file-loader", "6.1.0");
Remove the extra file-loader as it was added from the merge in master. see 3 lines down

2020-12-07 06:41 UTC, caalador commented on flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
> +                        .getCssValue("font-family"));
Should this check for something more. Are we certain the resource is available just because the css has been applied and no exceptions are on the console?

Should we also check the resource e.g.
```
        getDriver().get(getRootURL() + "/path/VAADIN/static/[THE_RESOURCE_THAT_IS_EXPECTED]");
        Assert.assertFalse("Font resource should be available",
            driver.getPageSource().contains("HTTP ERROR 404 Not Found"));
```

2020-12-07 06:41 UTC, caalador commented on flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/ThemeView.java
> +        faText.setClassName("fab");
Does this give something visible or should we add a icon class name also?

2020-12-07 07:45 UTC, caalador requested changes
Update the version number of the application-theme package.json with +0.0.1

2020-12-07 18:09 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
> +        defaults.put("file-loader", "6.1.0");
Done.

2020-12-07 18:13 UTC, taefi commented on flow-tests/test-themes/frontend/theme/app-theme/global.css
> +    background-image: url("/path/test/path/monarch-butterfly.jpg");
I'm not sure about this, since the `monarch-butterfly.jpg` is a non-theme resource under `src/webapp` and that leading `/path` is actually a folder under `webapp`.

2020-12-08 04:54 UTC, caalador commented on flow-tests/test-themes/frontend/theme/app-theme/global.css
> +    background-image: url("/path/test/path/monarch-butterfly.jpg");
But the point is that the url is relative to the application and /path/ is from the application servlet path.

2020-12-08 10:38 UTC, caalador commented on flow-tests/test-themes/frontend/theme/app-theme/global.css
> +    background-image: url("/path/test/path/monarch-butterfly.jpg");
Also this feature shouldn't touch the external url tests as this shouldn't change them in any way.

2020-12-08 12:46 UTC, taefi commented on flow-tests/test-themes/frontend/theme/app-theme/global.css
> +    background-image: url("/path/test/path/monarch-butterfly.jpg");
> /path/ is from the application servlet path
The project structure is like this:
```
project-root
|_ src
    |_ webapp
        |_ path
            |_ test
                |_ path
                    |_ monarch-butterfly.jpg
```
So I think I got confused because `@WebServlet("/path/*")` was the URL-pattern and not the context-path. So I removed the `/path` and changed it back to `./` as it was before.

2020-12-08 12:49 UTC, caalador commented on flow-tests/test-themes/frontend/theme/app-theme/global.css
> +    background-image: url("/path/test/path/monarch-butterfly.jpg");
I agree it's a bit confusing and should perhaps have a better comment on top.

2020-12-08 15:04 UTC, taefi commented on flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/ThemeView.java
> +        faText.setClassName("fab");
Added an Icon. Done.

2020-12-08 15:04 UTC, taefi commented on flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
> +                        .getCssValue("font-family"));
Done.

2020-12-09 06:41 UTC, caalador approved these changes

2020-12-09 08:00 UTC, merged