feat: Resource handling to not need plugin copying
vaadin/flow pull request #9558
Opened 2020-12-02 19:55 UTC by caalador

Fixed the url handling so that theme resources
get prepended with theme/[themeName] while
having the correct absolute path. With this we can handle
these url resources with the css-loader which in turn
leads to file-loader gettign the files for copying.

External url are still not touched in any way.

Only negative is now we loose any folder the resources
were located at.

2020-12-03 10:03 UTC, pleku requested changes
So
>Only negative is now we loose any folder the resources
were located at.

means that while resources can be referenced with e.g. `theme/mytheme/img/myfunnymeme.png` via Java or `./img/myfunnymeme.png` in css, in the end the resources is not available inside an `img` folder but instead at the root level of `VAADIN/static` ?

2020-12-03 10:03 UTC, pleku commented on flow-server/src/main/resources/webpack.generated.js
>                importLoaders: 1
If I understood correctly, the comments for the theme-loader below are not valid anymore as it is not aboud `VAADIN/static` but the ` theme/[themeFolder]`

2020-12-03 11:04 UTC, caalador reviewed
Got file-loader updated to generate the correct folder structure also.

2020-12-03 12:21 UTC, pleku commented on flow-server/src/main/resources/webpack.generated.js
> +                const themResource = resourcePath.match(/(\\|\/)theme\1[\s\S]*?\1/) && url.match(/theme\/[\s\S]*?\//);
typo

2020-12-03 12:21 UTC, pleku commented on flow-server/src/main/resources/webpack.generated.js
> +              if(urlResource.match(/(\\|\/)theme\1[\s\S]*?\1/)){
Should this regex be somewhere so that it is named and shared for both usage (this & css-loader) ?

2020-12-03 12:21 UTC, pleku commented on flow-server/src/main/resources/webpack.generated.js
> +              if(urlResource.match(/(\\|\/)theme\1[\s\S]*?\1/)){
Just to make sure, the `frontendFolder` will never end with `/` or `\` ?

2020-12-03 12:21 UTC, pleku commented on flow-server/src/main/resources/webpack.generated.js
> +                return /[\s\S]*(\\|\/)theme\1[\s\S]*?\1(.*)/.exec(resourcePath)[2];
Would it make sense to either use the output from the match above so there is only one regex operation ?

2020-12-03 12:21 UTC, pleku commented on flow-server/src/main/resources/webpack.generated.js
> +                return /[\s\S]*(\\|\/)theme\1[\s\S]*?\1(.*)/.exec(resourcePath)[2];
Will this code be only executed for the currently active theme's resources as the theme name is not checked here ? I think so but just checking

2020-12-03 12:54 UTC, caalador commented on flow-server/src/main/resources/webpack.generated.js
> +                const themResource = resourcePath.match(/(\\|\/)theme\1[\s\S]*?\1/) && url.match(/theme\/[\s\S]*?\//);
fixed

2020-12-03 12:54 UTC, caalador commented on flow-server/src/main/resources/webpack.generated.js
> +              if(urlResource.match(/(\\|\/)theme\1[\s\S]*?\1/)){
path.resolve never ends in a path separator. From the documentation `The resulting path is normalized and trailing slashes are removed unless the path is resolved to the root directory.`

2020-12-03 12:54 UTC, caalador commented on flow-server/src/main/resources/webpack.generated.js
> +              if(urlResource.match(/(\\|\/)theme\1[\s\S]*?\1/)){
done.

2020-12-03 12:54 UTC, caalador commented on flow-server/src/main/resources/webpack.generated.js
> +                return /[\s\S]*(\\|\/)theme\1[\s\S]*?\1(.*)/.exec(resourcePath)[2];
The match above doesn't collect the file name at all just checks that the theme part is there. 

In the first case we match for the css file not for the resource file so then they need to differ in usage.

2020-12-03 12:54 UTC, caalador commented on flow-server/src/main/resources/webpack.generated.js
> +                return /[\s\S]*(\\|\/)theme\1[\s\S]*?\1(.*)/.exec(resourcePath)[2];
No other themes are pointed to so that webpack would find them so this will only handle the active theme.

2020-12-03 13:26 UTC, pleku approved these changes

2020-12-04 06:49 UTC, pleku approved these changes

2020-12-04 07:07 UTC, merged