feat: add entry for @Deferrable to Vaadin usage statistics
vaadin/flow pull request #9577
Opened 2020-12-04 14:50 UTC by joheriks

Fixes #9540.

2020-12-04 16:33 UTC, platosha requested changes

2020-12-04 16:33 UTC, platosha commented on flow-client/src/main/resources/META-INF/resources/frontend/DeferrableEndpoint.ts
> +    version: /* updated-by-script */ '6.0-SNAPSHOT'
In addition, `scripts/version.js` should be updated to make it actually updated by script.

2020-12-07 07:43 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/DeferrableEndpoint.ts
> +    version: /* updated-by-script */ '6.0-SNAPSHOT'
Missed it. Now updates.

2020-12-07 09:42 UTC, haijian-vaadin requested changes

2020-12-07 09:42 UTC, haijian-vaadin commented on flow-client/src/main/resources/META-INF/resources/frontend/DeferrableEndpoint.ts
> +    version: /* updated-by-script */ '6.0-SNAPSHOT'
Got TS compile erros when trying out the PR.
```
ERROR in [at-loader] ./node_modules/@vaadin/flow-frontend/DeferrableEndpoint.ts:1:7 
    TS2451: Cannot redeclare block-scoped variable '$wnd'.

ERROR in [at-loader] ./target/flow-frontend/DeferrableEndpoint.ts:1:7 
    TS2451: Cannot redeclare block-scoped variable '$wnd'.
```

2020-12-07 09:54 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/DeferrableEndpoint.ts
> +    version: /* updated-by-script */ '6.0-SNAPSHOT'
Good catch, I had somehow dropped the empty export from the commit and it was working randomly when testing it. Now fixed.

2020-12-07 11:18 UTC, haijian-vaadin approved these changes

2020-12-07 11:50 UTC, platosha approved these changes

2020-12-07 12:52 UTC, merged