fix: encode attribute value during transfer from embedded web app
vaadin/flow pull request #9583
Opened 2020-12-07 10:29 UTC by denis-anisimov

2020-12-07 14:59 UTC, fluorumlabs requested changes

2020-12-07 14:59 UTC, fluorumlabs commented on flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
> +        return URLEncoder.encode(str, StandardCharsets.UTF_8.name());
Hm. `URLEncoder.encode` is for encoding parameters for using in `application/x-www-form-urlencoded` data, it changes forward slash (perfectly valid in path part of URL) to `%2f`.

2020-12-07 14:59 UTC, fluorumlabs commented on flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
> +        script.attr("src", "foo'bar %27?baz%22");
Would be nice to see the test with a real URL (with protocol, path parameters etc.)

2020-12-07 15:25 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
> +        return URLEncoder.encode(str, StandardCharsets.UTF_8.name());
The forward slash is not a problem : encoded slash is recognized correctly in the URI.
Encoded `?` is an issue.

But if not `URLEncoder.encode`  then which way do you suggest to escape/encode here ?

2020-12-07 15:30 UTC, fluorumlabs commented on flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
> +        return URLEncoder.encode(str, StandardCharsets.UTF_8.name());
One particular problem is whitespace character: in path it should be encoded as `%20` whereas `URLEncoder.encode` encodes it as `+`. The real solution is to either escape single quote to avoid injection, or, possibly, use double quotes in JS (double quote is not allowed in URL AFAIR)

2020-12-08 06:39 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
> +        return URLEncoder.encode(str, StandardCharsets.UTF_8.name());
Why it is a problem ?

Single quote is not always a single quote.
The problem is : you have to detect whether the symbol `'` is a single quote or not.
E.g. `\'` is not a single quote.
And `%27` is also a single quote.

Please provide a code which escape single quote.
>or, possibly, use double quotes in JS (double quote is not allowed in URL

double quote is not allowed. But I don't understand the sentence.

2020-12-08 06:51 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
> +        return URLEncoder.encode(str, StandardCharsets.UTF_8.name());
>or, possibly, use double quotes in JS (double quote is not allowed in URL

It's really hard to decrypt what you mean sometimes.

Do you suggest to use double quotes in the code which creates JS content inside `transferAttribute`?

Then yes, looks like it's a good suggestion.

2020-12-08 07:06 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
> +        script.attr("src", "foo'bar %27?baz%22");
Double quotes are use so there is no encoding done anymore.

2020-12-08 08:02 UTC, fluorumlabs requested changes

2020-12-08 08:02 UTC, fluorumlabs commented on flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
> +    private String checkURL(String url) {
Since this method doesn't returns argument as is, it should probably return `boolean` instead and called `isUrlUnsafe` to align with `com.vaadin.flow.server.HandlerHelper#isPathUnsafe`. The `IllegalArgumentException` should be thrown in `modifyPath` then.

2020-12-08 08:06 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
> +                .not(CoreMatchers.containsString("foo'bar %27?baz%22")));
Don't understand this .
Please decrypt.

2020-12-08 08:12 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
> +    private String checkURL(String url) {
This is an internal `private` method and it's name and how it's called is a  matter of taste .
The method returns the provided argument as is without any change and it throws the exception if something wrong with the argument.
It works quite similar to the `Objects::requireNonNull`.

2020-12-08 08:46 UTC, fluorumlabs commented on flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
> +                .not(CoreMatchers.containsString("foo'bar %27?baz%22")));
IMO the assertion should be `MatchAssert.assertThat(resultScript, CoreMatchers.containsString(...))`. If you disagree, could you explain what exactly this test is testing?

2020-12-08 08:48 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
> +                .not(CoreMatchers.containsString("foo'bar %27?baz%22")));
Now I've got it: `CoreMatchers.not` was a mistake in copy paste.
The intention was to have only `CoreMatchers.containsString`.
Thanks,

2020-12-08 10:07 UTC, fluorumlabs approved these changes

2020-12-08 10:08 UTC, merged

2021-01-26 14:49 UTC, mshabarov commented
Cherry picked to `2.5`