Fix: theme files can now be referenced as theme/theme-name
vaadin/flow pull request #9590
Opened 2020-12-07 13:09 UTC by caalador

Theme files are now copied undet theme/[theme-name]
and can be refernced by theme/them-name/path/file.ff
even though they are located at VAADIN/static

Fixes #9405 and #9535

2020-12-09 13:29 UTC, mshabarov requested changes

2020-12-09 13:29 UTC, mshabarov commented on flow-server/src/main/resources/webpack.generated.js
> +              if (resourcePath.match(/(\\|\/)node_modules\1/)) {
Why did you exclude `if(urlResource.match(themePartRegex)){ ... }`? I presume that excluding the `frontend/` is not needed anymore, but the `resourcePath` can still have no `node_modules` inside, right?

2020-12-09 13:29 UTC, mshabarov commented on flow-server/src/main/resources/webpack.generated.js
> +                return /(\\|\/)node_modules\1(?!.*node_modules)([\S]*)/.exec(resourcePath)[2].replace(/\\/g, "/");
Same question as above: shall it be `[\S]+`, not `[\S]*`?

2020-12-09 13:34 UTC, mshabarov commented
Another comment is that the dev mode now has this fix also, so it's desirable to cover the debug mode. `flow-test-themes-npm` has a production mode explicitly set up, so maybe another module will be required. However, let's get this PR in, and create a separate issue for covering the dev mode. WDYT, @caalador ?

2020-12-10 05:49 UTC, caalador reviewed
For the dev mode I guess we should make another module. Or a double pom-file at some point.

2020-12-10 05:49 UTC, caalador commented on flow-server/src/main/resources/webpack.generated.js
> +              if (resourcePath.match(/(\\|\/)node_modules\1/)) {
As we want to have the resource in theme/theme-name we get it from the `[path][name].[ext]` but for node modules we don't want it to be in `node_modules\.pnpm\registry.npmjs.org\@fortawesome\fontawesome-free\5.15.1\node_modules\@fortawesome\fontawesome-free\webfonts\fa-regular-400.eot` but rather `@fortawesome\fontawesome-free\webfonts\fa-regular-400.eot` 

Also using urlResource for checking node was wrong as it made the string `ules\.pnpm\registry.npmjs.org\@fortawesome\fontawesome-free\5.15.1\node_modules\@fortawesome\fontawesome-free\webfonts\fa-brands-400.eot` as the node_modules folder is not below frontend.

2020-12-10 05:49 UTC, caalador commented on flow-server/src/main/resources/webpack.generated.js
> +                return /(\\|\/)node_modules\1(?!.*node_modules)([\S]*)/.exec(resourcePath)[2].replace(/\\/g, "/");
Doesn't matter in this instance as we always should target a file for node_modules. but I can change it

2020-12-10 05:49 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
> +        return filenameWithPath.startsWith("/" + VAADIN_BUILD_FILES_PATH) || filenameWithPath.startsWith("/" + VAADIN_STATIC_FILES_PATH)
Formatted

2020-12-10 05:49 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
> +        if (themeFolder.matcher(requestFilename).find() || requestFilename.startsWith("/" + VAADIN_STATIC_FILES_PATH)
formatted

2020-12-10 05:49 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
> +    protected static final Pattern themeFolder = Pattern.compile("^\\/theme\\/[\\s\\S]*?\\/");
done

2020-12-10 05:49 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
> +    protected static final Pattern themeFolder = Pattern.compile("^\\/theme\\/[\\s\\S]*?\\/");
Named APP_THEME_PATTERN as its not for theme folder per say.

2020-12-10 07:46 UTC, mshabarov approved these changes

2020-12-10 07:49 UTC, merged

2020-12-10 08:52 UTC, mshabarov commented
Ticket for tests in Dev Mode https://github.com/vaadin/flow/issues/9628