Allow endpoints to work on non-public classes.
vaadin/flow pull request #9592
Opened 2020-12-07 20:20 UTC by tdq

Fix sets accessible all public methods of endpoint which allows to call them even if class is not public.
Checked with Oracle documentation that fix supports java 12 (there was a doubt that it's not)
https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/reflect/AccessibleObject.html

Fixes #8168

2020-12-07 20:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow?pullRequest=9592) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow?pullRequest=9592) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow?pullRequest=9592) it.</sub>

2020-12-10 15:17 UTC, joheriks requested changes

2020-12-10 15:17 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
> +        AccessibleObject.setAccessible(endpointPublicMethods, true);
This does set the accessible override flag on all public methods in the class, including those inherited from `Object` (`wait`, `toString`, ...) even though these are from being exposed as endpoints later on. Seems it would be safer to flag only the methods that can actually be called as endpoints.

2020-12-10 16:31 UTC, tdq commented on flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
> +        AccessibleObject.setAccessible(endpointPublicMethods, true);
setAccessible is not changing method itself, it's changing only instance of that Method (it's not singleton). The rest of security checks is done in com.vaadin.flow.server.connect.auth.VaadinConnectAccessChecker which is not changed in this PR.

2020-12-10 16:50 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
> +        AccessibleObject.setAccessible(endpointPublicMethods, true);
Right. I missed that `getMethods` returns copies so the override has only local impact. This looks fine then.

2020-12-10 16:51 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
> +        AccessibleObject.setAccessible(endpointPublicMethods, true);
Looks good to me after conflict resolution then.

2020-12-10 21:53 UTC, joheriks submitted a review, later dismissed

2020-12-11 08:37 UTC, haijian-vaadin submitted a review, later dismissed
Also looks good to me, ready to be merged once the conflicts are resolved.

2020-12-16 18:07 UTC, haijian-vaadin approved these changes

2020-12-16 18:07 UTC, merged