fix: loading indicator visible and isActive true while endpoint fetch
vaadin/flow pull request #9593
Opened 2020-12-07 21:03 UTC by joheriks

2020-12-08 20:36 UTC, haijian-vaadin requested changes

2020-12-08 20:36 UTC, haijian-vaadin commented on flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
> +      if (show || hide) {
The code here is not easy to understand.
`action && this.isActiveCount === 0;` 
`!action && this.isActiveCount === 1`
`Math.max(0, this.isActiveCount + (action ? 1 : -1));`
could these expression be extracted  as more meaningful functions?

`if (show || hide)`
Is it possible that it could be neither `show` nor `hide`?

2020-12-09 07:38 UTC, joheriks commented on flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
> +      if (show || hide) {
I clarified the code a bit and added comments. `show` and `hide` would both be false when there are multiple requests being handled at the same time. I added a unit test.

2020-12-09 20:30 UTC, haijian-vaadin approved these changes

2020-12-09 20:31 UTC, merged