WIP: fix(TypeScript): binder should allow typing decimal numbers
vaadin/flow pull request #9604
Opened 2020-12-08 11:10 UTC by platosha

Fixes #9521
Fixes #9522

2020-12-10 09:43 UTC, haijian-vaadin requested changes
Also, could we have a test for the fix?

2020-12-10 09:43 UTC, haijian-vaadin commented on flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts
> +function _asValidatorAttributes(attrs: ValueNumberAttributes | number | string | PatternAttributes | string | RegExp) {
redundant `string`?

2020-12-11 10:33 UTC, platosha commented
@haijian-vaadin added tests, there is one ensuring that the value is not reset from the binder while typing.

2020-12-14 08:03 UTC, haijian-vaadin commented
It looks good now, just found another issue. If I type `12,5` or `12,kjsdf` into the field, I don't get a validation error, the data is saved as 12. Could this be fixed in this PR, so should it be in another ticket?

2020-12-14 13:10 UTC, platosha commented
@haijian-vaadin thanks for pointing out, fixed here also

2020-12-14 13:24 UTC, haijian-vaadin commented
There are some lint errors for Models.ts file

2020-12-14 15:37 UTC, platosha commented
@haijian-vaadin oh, I always forget those, fixed 😅

2020-12-14 19:33 UTC, haijian-vaadin requested changes
It works! Good job! Found some minors things that could be improved.

2020-12-14 19:33 UTC, haijian-vaadin commented on flow-client/src/test/frontend/form/FieldTests.ts
> +            debugger;
remove debugger?

2020-12-14 19:33 UTC, haijian-vaadin commented on flow-client/src/test/frontend/form/ValidatorsTests.ts
> +    assert.isTrue(validator.validate(1.2));
Maybe we could add validations for `1,2`, `1,abc`, `abc` etc?

2020-12-14 19:33 UTC, haijian-vaadin commented on flow-client/src/test/frontend/form/FieldTests.ts
> +            debugger;
remove debugger?

2020-12-15 10:34 UTC, platosha commented on flow-client/src/test/frontend/form/ValidatorsTests.ts
> +    assert.isTrue(validator.validate(1.2));
This validator cannot check those cases — it only works on the `number` data type, which is the only type `NumberModel` works with.

2020-12-15 10:35 UTC, platosha commented on flow-client/src/test/frontend/form/FieldTests.ts
> +            debugger;
done

2020-12-15 11:34 UTC, haijian-vaadin approved these changes

2020-12-16 10:44 UTC, merged