Add IT test for CSS loading order
vaadin/flow pull request #9613
Opened 2020-12-09 06:37 UTC by tanbt

Resolves https://github.com/vaadin/flow/issues/9529

2020-12-11 07:27 UTC, caalador requested changes
This seems to be missing application theme position in the loading order and what it overrides (should probably override everything)

2020-12-11 07:27 UTC, caalador commented on flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/CssLoadingIT.java
> +    public void lumoStyleIsOverridden() {
The test name doesn't give a clear insight to what it actually tests.

2020-12-14 06:58 UTC, tanbt commented
I don't see any mention about testing application theme CSS loading order.
The issue says:
```
Lumo styles
(2. Parent theme)
Current theme
(4. App-specific bundled css added via @CssImport)
(5. App-specific unbundled css added via @Stylesheet
(6. Page.addStylesheet)
```
Should app theme be included in this PR?

2020-12-14 07:11 UTC, caalador commented
Current theme should equal application theme shouldn't it. As this is about getting a test that tests what comes when in the application theme documentation

2020-12-14 07:20 UTC, tanbt commented on flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/CssLoadingIT.java
> +    public void lumoStyleIsOverridden() {
I actually have no idea how to test Lumo styles in a more specific way.

2020-12-14 07:27 UTC, tanbt commented on flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/CssLoadingIT.java
> +    public void lumoStyleIsOverridden() {
Should I create separate views to test the priority of each pair of sources: a view to test `@CssImport` vs `@StyleSheet`, another view for  `@StyleSheet` vs `page.addStylesheet`, and so on?
There could be many combinations if doing so.

2020-12-14 07:38 UTC, caalador commented on flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/CssLoadingIT.java
> +    public void lumoStyleIsOverridden() {
Perhaps you could ask Rolf or Jouni about lumo tests, also Rolf might have a vision on the expected ordering. 
Having overriding tests would be perhaps better as a bunch where each step has 2 values where one is overridden or something.

2020-12-18 11:14 UTC, caalador submitted a review, later dismissed

2020-12-18 11:14 UTC, caalador commented on flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/CssLoadingIT.java
> +    }
Should these 3 tests just be merged to one `multipleDefinitions_correctOverrides` as opening a new browser for single asserts is quite heavy and they could just mention in the assertion fail message which part failed for which exception.

2020-12-18 11:33 UTC, tanbt commented on flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/CssLoadingIT.java
> +    }
Done.

2020-12-21 09:39 UTC, mshabarov requested changes

2020-12-21 09:39 UTC, mshabarov commented on flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/CssLoadingIT.java
> +        assertStylesOverride("p1", GREEN_RGBA, "16px", "1px");
Is it better to split out these 3 assertions into 3 separate tests and name them accordingly for better readability/maintainability?

2020-12-21 09:40 UTC, mshabarov commented on flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/CssLoadingIT.java
> +        assertStylesOverride("p1", GREEN_RGBA, "16px", "1px");
Sorry, just saw Mikael's comment about it. Ignore my comment.

2020-12-21 09:40 UTC, mshabarov approved these changes

2020-12-21 09:42 UTC, merged