chore: fix flaky tests that depends on mock count
vaadin/flow pull request #9631
Opened 2020-12-10 21:55 UTC by haijian-vaadin

2020-12-11 07:20 UTC, joheriks submitted a review, later dismissed

2020-12-11 10:04 UTC, joheriks commented
In addition, to deflake the tests, I think the following should be done:
1) Update `should_generateTs_files` and `should_generateOpenApi_when_EndpointPresents` to create a temporary folder (using e.g. `Files.createTempDirectory`) instead of `getClass().getClassLoader().getResource("com")`
2) Wrap each test that sets a system property with:
```java
        String originalPropertyValue = null;
        try {
            originalPropertyValue = System.getProperty("tested.property");
            System.setProperty("tested.property", baseDir);
           
            // actual test code

        } finally {
            if (originalUserDirValue != null) {
                System.setProperty("tested.property", originalUserDirValue);
            } else {
                System.clearProperty("tested.property");
            }
        }
```

2020-12-11 12:21 UTC, platosha submitted a review, later dismissed

2020-12-11 12:25 UTC, joheriks requested changes
`DevModeInitializerTest.should_notGenerateOpenApi_when_EndpointIsNotUsed` is still flaky, see second most recent validation build.

2020-12-14 07:36 UTC, joheriks approved these changes

2020-12-14 08:01 UTC, merged