refactor: extract common config functionality and introduce add config
vaadin/flow pull request #9635
Opened 2020-12-11 12:25 UTC by denis-anisimov

part of #9417

2020-12-11 12:27 UTC, denis-anisimov commented
Please note that it's not clear at the moment in this PR why the refactoring is needed.
So please review considering the fact that it's needed.
The changes are extracted from the existing set of changes where the refactoring is applied to simplify review and reduce a number if change.

This is only refactoring which should not break any logic: extraction some common code and moving code between classes.
Also it introduced API/SPI which is not currently used.

2020-12-11 14:53 UTC, pleku submitted a review, later dismissed

2020-12-11 14:53 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
> +        extends AbstractConfiguration, Serializable {
Is it intentional that some of the methods have now 1-1 implementation in this interface and the introduced `AbstractConfiguration`, and thus the implementation here is unnecessary ? I see still at least devserver and pnpm methods are the same

2020-12-11 14:53 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/AbstractPropertyConfiguration.java
> + *
Javadocs missing

2020-12-11 14:53 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/AbstractPropertyConfiguration.java
> +
```suggestion
/**
 * Constructs property based configuration based on the given properties map.
 * @param properties a map of the properties
 */
```
Missing javadocs

2020-12-11 14:53 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
> +            ApplicationConfiguration parentConfig,
This parameter is not added to the javadocs

2020-12-11 14:53 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
> +        initialParameters = initParameters;
Is `initParameters` a bad name for the variable ? Should it be also renamed for the constructor parameter to make it clear that it is not "init parameters" but "initial parameters" ?

2020-12-11 14:53 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractConfigurationFactory.java
> + *
Javadocs missing

2020-12-11 14:53 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactory.java
> +            // For no non jar build info, in production mode check for
Maybe not related to this PR, but I have a hard time understanding "For no non jar build info", my guess would be it tries to imply that "When no token file is found from a jar and running in production mode, then check..." but not sure

2020-12-11 14:54 UTC, pleku commented
Compile error
```
[14:49:12][WARNING] The requested profile "npm" could not be activated because it does not exist.
[14:49:12][ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project flow-server: Compilation failure: Compilation failure: 
[14:49:12][ERROR] /opt/agent/work/a69251da2b2bb9e9/flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java:[127,16] constructor PropertyDeploymentConfiguration in class com.vaadin.flow.server.PropertyDeploymentConfiguration cannot be applied to given types;
[14:49:12][ERROR]   required: com.vaadin.flow.server.startup.ApplicationConfiguration,java.lang.Class<?>,java.util.Properties
[14:49:12][ERROR]   found: java.lang.Class<capture#1 of ?>,java.util.Properties
[14:49:12][ERROR]   reason: actual and formal argument lists differ in length
[14:49:12][ERROR] /opt/agent/work/a69251da2b2bb9e9/flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java:[133,9] constructor PropertyDeploymentConfiguration in class com.vaadin.flow.server.PropertyDeploymentConfiguration cannot be applied to given types;
[14:49:12][ERROR]   required: com.vaadin.flow.server.startup.ApplicationConfiguration,java.lang.Class<?>,java.util.Properties
[14:49:12][ERROR]   found: java.lang.Class<capture#2 of ?>,java.util.Properties
[14:49:12][ERROR]   reason: actual and formal argument lists differ in length
```

2020-12-14 06:32 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
> +        extends AbstractConfiguration, Serializable {
No, not intentional.
I thought I've removed them from the `DeploymentConfiguration`.
Most likely cherry-pick issue.

2020-12-14 06:33 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/AbstractPropertyConfiguration.java
> + *
Done

2020-12-14 06:34 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/AbstractPropertyConfiguration.java
> +
Done.

2020-12-14 06:34 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
> +            ApplicationConfiguration parentConfig,
Removed.

2020-12-14 06:41 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
> +        initialParameters = initParameters;
I think `initParameters` is not a bad name.
`init parameters` is something which comes from servlet (or servlet context) init parameters.
At least `ServletContext` has method `getInitParameter` so it's consistent.

`initialParameters` is an internal field with intentional name to distinguish the coming properties which has type `Hashtable<Object,Object>` from the string properties which are passed to the super CTOR.

So contract-wise `initProperties` are still init properties.

2020-12-14 06:42 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractConfigurationFactory.java
> + *
Done.

2020-12-14 06:44 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactory.java
> +            // For no non jar build info, in production mode check for
Unfortunately I don't know the exact details of this code.
This is direct copy/paste of existing code in the `DeploymentConfigurationFactory` without any change.

2020-12-15 12:36 UTC, caalador requested changes

2020-12-15 12:36 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactory.java
> +            // For no non jar build info, in production mode check for
It could say `when token not found outside jar...` also the whole comment should be removed as the javadoc for getPossibleJarResource is more accurate as we don't even check for production mode.

2020-12-15 16:55 UTC, denis-anisimov commented on flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
> +                "com\\.vaadin\\.flow\\.server\\.startup\\.ApplicationConfigurationFactory",
Sorry, I didn't get.
`ApplicationConfigurationFactory` is an interface.
It doesn't extend `Serializable`.
`DefaultApplicationConfigurationFactory` is a class, it implements Serializable just because its superclass implements it.
But the main its interface doesn't extend Serializable.

2020-12-15 17:01 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactory.java
> +            // For no non jar build info, in production mode check for
Removed

2020-12-15 17:02 UTC, denis-anisimov commented on flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
> +                "com\\.vaadin\\.flow\\.server\\.startup\\.ApplicationConfigurationFactory",
Ah, I guess yo meant `AbstractConfigurationFactory`.
AbstractConfigurationFactory != ApplicationConfigurationFactory

2020-12-16 05:06 UTC, caalador requested changes

2020-12-16 05:06 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactory.java
> +    protected String getTokenFileFromClassloader(VaadinContext context)
Is it intentional that the same function is still also available in `DeploymentConfigurationFactory.java`?

2020-12-16 05:06 UTC, caalador commented on flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
> +                "com\\.vaadin\\.flow\\.server\\.startup\\.ApplicationConfigurationFactory",
Reading comprehension is not strong at the moment it seems.

2020-12-16 05:47 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactory.java
> +    protected String getTokenFileFromClassloader(VaadinContext context)
Technically `DefaultApplicationConfigurationFactory` should not be in this PR.
It's not yet used from anywhere.
The main work is the configuration refactoring but I've included also `DefaultApplicationConfigurationFactory`  for some reasons which I don't even remember anymore.

You are right that the intention is to have the method in `DefaultApplicationConfigurationFactory` only.
But that will require complete PR with all things reimplemented and that will be too big.
This change is the next: it's even already done. I'm writing and correcting unit tests.

WIP: https://github.com/vaadin/flow/pull/9642

2020-12-16 06:09 UTC, caalador approved these changes

2020-12-16 06:21 UTC, merged