Feat: enable having a parent theme
vaadin/flow pull request #9648
Opened 2020-12-14 13:37 UTC by caalador

It is now possible to extend a parent application
theme. This means adding the key "parent" with
the value of the target theme and then this will
be used with the current theme.

Fixes #9587

2020-12-14 14:05 UTC, knoobie commented on flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
> +
How about a third test that css from the parent theme can be overwritten by the child? (e.g. having Lumo as parent and customizing a specific color)

2020-12-15 06:06 UTC, caalador commented on flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
> +
Yes I noted also that I forgot to change the message. But this will wait for the reusable theme test to be done first and I will need to move the functionality test to another module at that point.

2020-12-18 10:45 UTC, pleku requested changes
After the reusable-theme PR is merged, needs an IT for the common case when the parent theme is inside a `.jar`. And I'm not sure what / where is the code that makes sure that the parent theme ends up being copied also in that case - or is it so that in the reusable theme PR the part that searches and copies all `META-INF/resources/themes/` folder makes this magic happen ?

2020-12-18 10:45 UTC, pleku commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
>   * Copies static resources for theme and generates/writes the [theme-name].js for webpack to handle.
As this will now recursively also do things for all parent themes, maybe that could be clarified here

2020-12-18 10:45 UTC, pleku commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
> +    themeFile += `import {applyTheme as applyBaseTheme} from 'themes/${themeProperties.parent}/${themeProperties.parent}.generated.js';`;
Non-blocking: Just a thought that it would probably be a good idea to have an util method that "gets the generated file for a given theme name" that is reused in all places, but that refactoring can be done later if needed

2020-12-22 08:47 UTC, pleku approved these changes

2020-12-22 09:21 UTC, pleku requested changes

2020-12-22 09:21 UTC, pleku commented on flow-tests/test-application-theme/test-reusable-as-parent/src/test/java/com/vaadin/flow/uitest/ui/theme/ParentThemeIT.java
> +        Assert.assertEquals("Polymer text field should have red background",
Nit: this is not background ...

2020-12-22 09:21 UTC, pleku commented on flow-tests/test-themes/frontend/themes/parent-theme/parent.css
> +    color: aqua;
Non-blocking: I think it is not nice to have different css value here than in the tests that verify using the `rgb` value, makes it more cumbersome to follow things

2020-12-22 09:21 UTC, pleku commented on flow-tests/test-application-theme/test-reusable-as-parent/src/test/java/com/vaadin/flow/uitest/ui/theme/ParentThemeIT.java
> +public class ParentThemeIT extends ChromeBrowserTest {
Is this really `ParentThemeIT` as it is mostly testing overriding parent theme things ? At least individual test names appear so... maybe the parts that check that something from the parent theme is still applied could be moved inside one test, I think there is not many checks for that, maybe two ?

2020-12-22 09:21 UTC, pleku commented on flow-tests/test-application-theme/test-reusable-as-parent/src/test/java/com/vaadin/flow/uitest/ui/theme/ParentThemeIT.java
> +        // Note themes/reusable-theme gets VAADIN/static from the file-loader
Is this actually valid comment ? As the path is for `child-theme`

2020-12-22 09:21 UTC, pleku commented on flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
> +        Assert.assertEquals("Polymer text field should get parent border radius",
This has nothing to do with border radius

2020-12-22 09:58 UTC, caalador commented on flow-tests/test-application-theme/test-reusable-as-parent/src/test/java/com/vaadin/flow/uitest/ui/theme/ParentThemeIT.java
> +        // Note themes/reusable-theme gets VAADIN/static from the file-loader
Unecessay note. removed

2020-12-22 09:58 UTC, caalador commented on flow-tests/test-application-theme/test-reusable-as-parent/src/test/java/com/vaadin/flow/uitest/ui/theme/ParentThemeIT.java
> +        Assert.assertEquals("Polymer text field should have red background",
CopyPaste do something else problem. fixed

2020-12-22 09:58 UTC, caalador commented on flow-tests/test-themes/frontend/themes/parent-theme/parent.css
> +    color: aqua;
Updated.

2020-12-22 09:58 UTC, caalador commented on flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
> +        Assert.assertEquals("Polymer text field should get parent border radius",
CP. fixed

2020-12-22 09:58 UTC, caalador commented on flow-tests/test-application-theme/test-reusable-as-parent/src/test/java/com/vaadin/flow/uitest/ui/theme/ParentThemeIT.java
> +public class ParentThemeIT extends ChromeBrowserTest {
Well as this is for testing the reusable theme as parent most parent theme specifics are already tested there. This is testing the reusable theme as parent so I feel the important is here to be able to override parent parts as the reusable is fully tested in another module.

2020-12-22 11:16 UTC, pleku approved these changes

2020-12-22 11:17 UTC, pleku commented on flow-tests/test-application-theme/test-reusable-as-parent/src/test/java/com/vaadin/flow/uitest/ui/theme/ParentThemeIT.java
> +public class ParentThemeIT extends ChromeBrowserTest {
Yeah, but my point was that to me this is mostly about "Overriding Parent Theme".

2020-12-22 11:19 UTC, caalador commented on flow-tests/test-application-theme/test-reusable-as-parent/src/test/java/com/vaadin/flow/uitest/ui/theme/ParentThemeIT.java
> +public class ParentThemeIT extends ChromeBrowserTest {
CustomiseParentThemeIT?

2020-12-22 11:19 UTC, merged