WIP: Support reusable application theme
vaadin/flow pull request #9650
Opened 2020-12-14 16:03 UTC by tanbt

Resolves https://github.com/vaadin/flow/issues/9585

2020-12-17 07:28 UTC, caalador requested changes

2020-12-17 07:28 UTC, caalador commented on flow-server/src/main/resources/webpack.generated.js
>        // The following matches target/flow-frontend/theme/theme-generated.js and not frontend/themes
Comment is wrong now. Should be updated to say it for the theme-generated and for the jar theme

2020-12-17 08:43 UTC, tanbt commented on flow-server/src/main/resources/webpack.generated.js
>        // The following matches target/flow-frontend/theme/theme-generated.js and not frontend/themes
Updated.

2020-12-17 10:45 UTC, tanbt commented on flow-tests/test-resources/src/main/java/com.vaadin.apptheme.reusabletheme/Dependency.java
> +package org.vaadin.apptheme.reusabletheme;
Moved to reusable module.

2020-12-17 10:45 UTC, tanbt commented on flow-tests/test-resources/src/main/resources/META-INF/resources/themes/reusable-theme/README.md
> +This theme is cloned from frontend/themes/app-theme.
Moved to reusable module.

2020-12-17 10:53 UTC, caalador requested changes

2020-12-17 10:53 UTC, caalador commented on pom.xml
> +        <module>flow-tests/test-application-theme/reusable-theme</module>
This is fine to build only in test-application-theme when it is built. it shouldn't be used outside of the module.

2020-12-17 10:53 UTC, caalador commented on flow-tests/test-application-theme/reusable-theme/pom.xml
> +
I expect that you will need some flow dependencies to get the imports to compile as at least flow-tests only depend on lumo and not much else.

2020-12-17 11:30 UTC, tanbt commented on pom.xml
> +        <module>flow-tests/test-application-theme/reusable-theme</module>
Removed.

2020-12-17 11:30 UTC, tanbt commented on flow-tests/test-application-theme/reusable-theme/pom.xml
> +
Some flow dependencies are already in the parent (or grandparent) of this module already. Is that enough?

2020-12-17 11:36 UTC, caalador commented on flow-tests/test-application-theme/reusable-theme/pom.xml
> +
Should be fine if it compiles.

2020-12-17 13:16 UTC, caalador requested changes

2020-12-17 13:16 UTC, caalador commented on flow-tests/test-application-theme/reusable-theme/src/main/resources/META-INF/resources/themes/reusable-theme/global.css
> +}
Not certain we would want the external urls in the reusable theme as then the one reusing should somehow have them served.

2020-12-17 15:43 UTC, tanbt commented on flow-tests/test-application-theme/reusable-theme/src/main/resources/META-INF/resources/themes/reusable-theme/global.css
> +}
Yeah, make sense.
It's not a good practice to to call an external resources inside an independent theme pack (JAR file).
Should we remove this test?

2020-12-18 08:44 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/Constants.java
> +    public static final String APPLICATION_THEME_ROOT = "themes";
@taefi  is running for this to be in FrontendUtils.
> Of course, agree to define it once, but I have a feeling that it is better to define it here since many other 
> default/hardcoded path and folder constants defined in this file, e.g. NODE_MODULES, FRONTEND, 
> DEFAULT_NODE_DIR, DEFAULT_FRONTEND_DIR, etc. I propose to keep it here but rename it to 
> APPLICATION_THEME_ROOT as Tan defined.

2020-12-18 09:51 UTC, tanbt commented on flow-server/src/main/java/com/vaadin/flow/server/Constants.java
> +    public static final String APPLICATION_THEME_ROOT = "themes";
So should I move this constant to `FrontendUtils`? Or @taefi  will do that in his PR?

2020-12-18 10:09 UTC, pleku approved these changes

2020-12-18 10:09 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/Constants.java
> +    public static final String APPLICATION_THEME_ROOT = "themes";
Please resolve this kind of trivial issues as fast as possible by e.g. just agreeing over Slack

2020-12-18 10:12 UTC, caalador approved these changes

2020-12-18 10:27 UTC, merged

2020-12-18 10:29 UTC, tanbt commented
I guess @taefi  can continue from `master`, i.e. moving `APPLICATION_THEME_ROOT` to FrontendUtils
and update the comment `// If we define a theme name we need to import theme/theme-generated.js` to `.... themes/theme-generated.js`