Use ArrayList instead of HashSet to make CompositeDataGenerator deter…
vaadin/flow pull request #9657
Opened 2020-12-15 10:04 UTC by TatuLund

…ministic

Fixes https://github.com/vaadin/flow/issues/9656

2020-12-15 12:37 UTC, joheriks commented on flow-data/src/main/java/com/vaadin/flow/data/provider/CompositeDataGenerator.java
> +    private final List<DataGenerator<T>> dataGenerators = new ArrayList<>();
Does this change API slightly in that `addDataGenerator` is no longer idempotent? Would perhaps be safer to use `LinkedHashSet `, which has set semantics but preserves order.

2020-12-15 12:47 UTC, TatuLund commented on flow-data/src/main/java/com/vaadin/flow/data/provider/CompositeDataGenerator.java
> +    private final List<DataGenerator<T>> dataGenerators = new ArrayList<>();
True

2020-12-15 13:50 UTC, Artur- commented
I am not saying tests are mandatory but if you leave them out, it means you are fine if somebody reverts the patch tomorrow. It should not be difficult to add a test that the order is preserved

2020-12-15 14:46 UTC, joheriks commented
> Ok, did that, which required to make dataGenerators package protected.

It can be tested without the visibility modificiation, with just slightly blacker-box test. E.g. public method `destroyAllData` calls the `dataGenerators` in order. The test could register e.g. three `DataGenerator` instances which have side effect on a local mutable, e.g., appending `this` to a local list. Then the list can be asserted to be in order of registration.

2020-12-15 15:10 UTC, joheriks requested changes

2020-12-15 15:10 UTC, joheriks commented on flow-data/src/test/java/com/vaadin/flow/data/provider/CompositeDataGeneratorTest.java
> +        List<DataGenerator<String>> expected = Arrays.asList(dg1,dg2);
`Arrays` may need import.

2020-12-15 15:10 UTC, joheriks commented on flow-data/src/test/java/com/vaadin/flow/data/provider/CompositeDataGeneratorTest.java
> +        assertEquals(expected,new ArrayList<>(cdg.dataGenerators));
`Assert.assertEquals` or import.

2020-12-15 17:11 UTC, TatuLund commented
> It can be tested without the visibility modificiation

The both approaches have their pros and cons, it is really hard to judge which is better.

2020-12-15 19:32 UTC, joheriks approved these changes

2020-12-15 19:33 UTC, joheriks commented
> The both approaches have their pros and cons, it is really hard to judge which is better.

True, I'm fine with package-private. Just wanted to highlight the alternative.

2020-12-16 11:49 UTC, mshabarov approved these changes
Small nits

2020-12-16 11:49 UTC, mshabarov commented on flow-data/src/test/java/com/vaadin/flow/data/provider/CompositeDataGeneratorTest.java
> +    public void orderIsPreserved() {
```suggestion
    public void addDataGenerator_orderIsPreserved() {
```

2020-12-16 11:49 UTC, mshabarov commented on flow-data/src/test/java/com/vaadin/flow/data/provider/CompositeDataGeneratorTest.java
> +        assertEquals(expected,new ArrayList<>(cdg.dataGenerators));
```suggestion
        assertEquals(expected, new ArrayList<>(cdg.dataGenerators));
```

2020-12-16 11:49 UTC, mshabarov commented on flow-data/src/test/java/com/vaadin/flow/data/provider/CompositeDataGeneratorTest.java
> +        List<DataGenerator<String>> expected = Arrays.asList(dg1,dg2);
```suggestion
        List<DataGenerator<String>> expected = Arrays.asList(dg1, dg2);
```

2020-12-16 11:59 UTC, mshabarov requested changes
> > It can be tested without the visibility modificiation

> The both approaches have their pros and cons, it is really hard to judge which is better.

I would go with Johannes's approach (use `callOrder`) and keep the modifier `private`, because the package consists of a lot of classes with heavy data handling logic, and the risk of accidentally modify the internal state is high.

2020-12-17 11:00 UTC, mshabarov approved these changes

2020-12-17 11:04 UTC, merged

2021-01-22 13:12 UTC, mshabarov commented
Cherry picked to `2.4`