fix: verify theme folder existence based on app-theme name in @Theme
vaadin/flow pull request #9676
Opened 2020-12-16 16:41 UTC by taefi

Fixes #9610

2020-12-18 05:46 UTC, caalador requested changes

2020-12-18 05:46 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    public static final String APP_THEMES_FOLDER_NAME = "themes";
Tan is addin to Constants 
```
    /**
     * The name of the application theme root folder.
     */
    public static final String APPLICATION_THEME_ROOT = "themes";
```
And I feel we should define it only in one place.

2020-12-18 05:46 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +    private void verifyThemeDirectoryExistence() throws ExecutionFailedException {
Nit: you could just have the method take in `String themeName` to not have `theme.getName()` in so many places

2020-12-18 05:46 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +        File themesDir = new File (frontendDirectory, APP_THEMES_FOLDER_NAME);
Again this is not the only place we support so we should also check 
- `src/main/resources/META-INF/resources`
- `src/main/resources/static`
- `${flowFrontend}` (where the generated is written to, will also get the jar contents)

2020-12-18 05:46 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +                    "typo in the theme or folder name \"%s\".";
```suggestion
            String errorMessage = "Discovered @Theme annotation with theme name '%s', " +
                    "but could not find the theme directory in the " +
                    "project or available as a jar dependency." +
                    "Check if you forgot to create the folder in '%s' or have " +
                    "mistyped the theme or folder name for '%s'.";
```

2020-12-18 05:46 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +                    APP_THEMES_FOLDER_NAME, theme.getName(), theme.getName()));
```suggestion
            throw new ExecutionFailedException(String.format(errorMessage,
                    theme.getName(), themesDir, theme.getName()));
```

2020-12-18 05:46 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +        File themesDir = new File (frontendDirectory, APP_THEMES_FOLDER_NAME);
We can ofc suggest creating to the frontend folder, but we should still check all the possibilities. 
Also this doesn't check for jar contents at the moment. This is possible to check in the flowFrontend directory as the files will have been copied out from the jar before we process this step.

2020-12-18 08:34 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +    public static final String APP_THEMES_FOLDER_NAME = "themes";
Of course, agree to define it once, but I have a feeling that it is better to define it here since many other default/hardcoded path and folder constants defined in this file, e.g. NODE_MODULES, FRONTEND, DEFAULT_NODE_DIR, DEFAULT_FRONTEND_DIR, etc. I propose to keep it here but rename it to `APPLICATION_THEME_ROOT` as Tan defined.

2020-12-21 07:11 UTC, caalador requested changes

2020-12-21 07:11 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +
I would just have this method return a list (stream?) of strings concatenate as `String.join("/", APPLICATION_META_INF_RESOURCES, APPLICATION_THEME_ROOT, themeName)` Also I would not call this other folders as it should just be the full set of folders.

2020-12-21 07:11 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +                String errorMessage = "Discovered Theme folder for theme " +
This exception is sort of wrong if you have the same themeName in frontend and a jar.
In that case the exception should be more like `"Theme '" + themeName + "'should not exist inside a jar and in the project at the same time\n Extending another theme is possible by adding { \"parent\": \"my-parent-theme\" } entry to the theme.json file inside your theme folder."`
But this case is checked in the webpack plugin.

2020-12-21 07:11 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/Constants.java
> +    public static final String APPLICATION_STATIC_RESOURCES = "src/main/resources/static";
Will anyone else have need of these paths? I would have them in the task only.

2020-12-21 07:25 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +
And the stream/list would be used as `Stream.filter(path -> new File(npmFolder, path).exists()).count()`

2020-12-21 10:19 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +                                               File frontendDirectory)
I'm trying to maintain integrity for the input parameters, so either the method to be totally dependent on fields or totally act as independent as possible. In this case, I would remove `theme name` also from the input args and would create a local variable as `String themeName = theme.getName()`, since feels the same for me to pass `theme.getName()` to it while the `theme` is available as a field.

2020-12-21 10:22 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +                                                    File frontendDirectory) {
Same as https://github.com/vaadin/flow/pull/9676/files#r546623022

2020-12-21 10:31 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +                                               File frontendDirectory)
We shouldn't pass instance variables around internal private methods. Even though theme is available the name is as such not, but it's fine to have getName everywhere it is needed..

2020-12-21 10:32 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +        File projectRootDir = frontendDirectory.getParentFile();
Yeah, right, totally understand this since I was struggling with the same issue in my mind while I was taking the look at available runtime parameters from `builder` in `NodeTask.java` and didn't find any proper parameter which holds the `project-root`. Should I assume that `npmFolder` is the project-root? Since I wasn't sure that it is not gonna be optimized by the users.

2020-12-21 10:44 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +        File projectRootDir = frontendDirectory.getParentFile();
It's where everything else is calculated from also so it should be fine to assume it's the project root. it bsically needs to be the place where pom.xml exists.

2020-12-21 11:03 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +                String errorMessage = "Discovered Theme folder for theme " +
I'm validating this to cover such situations that user wrongly copies the same `/themes/some-theme` structure in more than one place, for instance having it in both `[project-root]/frontend/themes/some-theme` and `[project-root]/src/main/resources/static/themes/some-theme`. As far as I understood, webpack is only checking the duplicity in jar and project files, not between to places in project files. Please correct me if I'm wrong.

2020-12-21 11:06 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +                String errorMessage = "Discovered Theme folder for theme " +
yes, but as this is done earlier and the check does even check for jar resource theme it should handle the fronten+jar scenario and inform that the jar should be marked as a parent theme and the other should get a new name.

2020-12-22 07:15 UTC, caalador requested changes

2020-12-22 07:15 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +    }
```suggestion
    private List<String> getAppThemePossiblePaths(String themePath) {
        String frontendTheme = String.join("/",
            npmFolder.toPath().relativize(frontendDirectory.toPath())
                .toString(), themePath);
                
        String themePathInMetaInfResources = String.join("/",
                APPLICATION_META_INF_RESOURCES, themePath);

        String themePathInStaticResources = String.join("/",
                APPLICATION_STATIC_RESOURCES, themePath);

        String themePathInClassPathResources = String
            .join("", FrontendUtils.NODE_MODULES,
                FrontendUtils.FLOW_NPM_PACKAGE_NAME, themePath);

        return Arrays.asList(frontendTheme, themePathInMetaInfResources,
            themePathInStaticResources, themePathInClassPathResources);
    }
```

2020-12-22 07:15 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +        }
```suggestion
        
        if (existingAppThemeDirectories.isEmpty()) {
            String errorMessage = "Discovered @Theme annotation with theme "
                + "name '%s', but could not find the theme directory "
                + "in the project or available as a jar dependency. "
                + "Check if you forgot to create the folder under '%s' "
                + "or have mistyped the theme or folder name for '%s'.";
            throw new ExecutionFailedException(String
                .format(errorMessage, themeName,
                    new File(frontendDirectory, APPLICATION_THEME_ROOT)
                        .getPath(), themeName));
        }
        if (existingAppThemeDirectories.size() >= 2) {

            boolean appThemeFoundInClassPath = existingAppThemeDirectories
                .stream().map(File::getPath)
                .anyMatch(path -> path.contains(FrontendUtils.FLOW_NPM_PACKAGE_NAME));

            if (appThemeFoundInClassPath) {
                String errorMessage = "Theme '%s' should not exist inside a "
                    + "jar and in the project at the same time.%n"
                    + "Extending another theme is possible by adding "
                    + "{ \"parent\": \"your-parent-theme\" } entry to the "
                    + "'theme.json' file inside your theme folder.";
                throw new ExecutionFailedException(
                    String.format(errorMessage, themeName));
            } else {
                String errorMessage = "Discovered Theme folder for theme '%s' "
                    + "in more than one place in the project. Please "
                    + "make sure there is only one theme folder with name '%s' "
                    + "exists in the your project. "
                    + "The recommended place to put the theme folder inside "
                    + "the project is '%s'";
                throw new ExecutionFailedException(String
                    .format(errorMessage, themeName, themeName,
                        new File(frontendDirectory, APPLICATION_THEME_ROOT)
                            .getPath()));
            }
        }
```

2020-12-22 07:15 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +        File mainCustomThemeDir = new File(frontendDirectory, themePath);
```suggestion
```

2020-12-22 09:13 UTC, caalador approved these changes

2020-12-22 09:13 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +            if (appThemeFoundInClassPath) {
Minor nit. Now that I read this like this appThemeFoundInClasPath is not perhaps the most explanatory name. Could be `jarThemeFound` as that's what it checks, also it's basically not on the classpath what we check.

2020-12-22 10:21 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +            if (appThemeFoundInClassPath) {
Agree, renamed it `themeFoundInJar` to be read as a natural sentence in `if`

2020-12-22 11:13 UTC, caalador approved these changes

2020-12-22 14:28 UTC, merged