chore: improve stability of two tests
vaadin/flow pull request #9697
Opened 2020-12-18 17:46 UTC by joheriks

Contains two stabilising fixes:
- A [rare fluke](https://bender.vaadin.com/viewLog.html?buildId=204930&buildTypeId=Flow_Flow60_Flow60Snapshot&tab=buildLog&_focus=15958) (also in master) occurs in `FlowTests` when the `setTimeout` calls intended to simulate asynchronous server response in `stubServerRemoteFunction` complete after the unit test, when `afterEach` has already deleted `window.Vaadin`. This causing `Flow.loadingFinished` ran by `Flow.serverConnected` to crash between the tests. The fix cancels all timers between in `afterEach`.
- With the right heartbeat timing, the browser console in`LogoutIT` can [contain a session expiration message](https://bender.vaadin.com/viewLog.html?buildId=205169&buildTypeId=Flow_Misc_FlakyItInvestigationTestByJohannes&tab=buildLog&branch_Flow_Misc=merge-offline-to-master&_focus=37588). The fix relaxes the acceptable console errors in the IT.

2020-12-18 18:04 UTC, haijian-vaadin requested changes

2020-12-18 18:04 UTC, haijian-vaadin commented on flow-client/src/test/frontend/FlowTests.ts
> +        //await new Promise(resolve => setTimeout(resolve, 500));
Is this commented line needed?

2020-12-18 18:06 UTC, joheriks commented on flow-client/src/test/frontend/FlowTests.ts
> +        //await new Promise(resolve => setTimeout(resolve, 500));
Good catch! Neither this comment nor the above await should be in the test, they are remnants from inserting waits to provoke the race condition. Removed.

2020-12-18 18:19 UTC, haijian-vaadin commented on flow-client/src/test/frontend/FlowTests.ts
> +        //await new Promise(resolve => setTimeout(resolve, 500));
thanks, now it looks good

2020-12-18 18:19 UTC, haijian-vaadin submitted a review, later dismissed

2020-12-21 08:11 UTC, haijian-vaadin approved these changes

2020-12-21 08:38 UTC, merged