use superclass of VadinServlet/Request if possible
vaadin/flow pull request #9699
Opened 2020-12-20 21:28 UTC by stbischof

Signed-off-by: Stefan Bischof <stbischof@bipolis.org>

2021-02-04 07:09 UTC, pleku requested changes
Thanks for the contribution and sorry for the long delay with the review, but this PR basically shows how reluctant people are to comment on PRs that don't explain _why_ changes are proposed. There is no issue open that would explain why this is needed so you need to start with that.

Secondly many of the changes seem like invalid and, sorry for being direct but, a waste of time. Please help me understand why this would be valuable. If not, I think we'll just have to say no thanks this time - I hope you understand.

2021-02-04 07:09 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
> +    private VaadinService servletService;
Since this is _VaadinServlet_ it means that there should be a servlet. I don't see a point in doing any changes for this class for "no servlet present". Why are there changes done here ?

2021-02-04 07:09 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinServletRequest.java
> +    private final VaadinService vaadinService;
This is a _servlet_ request, so why shouldn't it have access to servlet service ?

2021-02-04 07:09 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
> +        String servletPath = ((HttpServletRequest) request).getServletPath();
Again, servlet based class and these changes seem like a waste of time, or why would these be needed ?

2021-02-04 07:09 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
> +        if (request instanceof HttpServletRequest) {
When would it be a case here that `VaadinServletRequest` is not applicable here ??

2021-02-04 07:09 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
> +                                .wrap((HttpServletRequest) request),
When would it be a case here that `VaadinServletRequest` is not applicable here ??

2021-02-04 07:09 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
> +                                .wrap((HttpServletResponse) response));
When would it be a case here that `VaadinServletRequest` is not applicable here ??

2021-02-04 07:09 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
> +                    "Only HttpServletRequest are supported");
When would it be a case here that `VaadinServletRequest` is not applicable here ??

2021-02-04 07:09 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/communication/StreamResourceHandler.java
> +            ServletContext context = ((ServletRequest) request)
When would it be a case here that `VaadinServletRequest` is not applicable here ??

2021-02-04 07:09 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
> +        return ((HttpServletRequest) request).getRequestURL().toString();
When would it be a case here that `VaadinServletRequest` is not applicable here ??

2021-02-04 07:09 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
> +            url = ((HttpServletRequestWrapper) request).getRequestURL().toString();
When would it be a case here that `VaadinServletRequest` is not applicable here ??

2021-02-04 08:16 UTC, stbischof commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
> +    private VaadinService servletService;
I do not use the `VaadinServletService` i am using my own `VaadinServic`.If I want to use your `VaadinServlet.class` i have no way to do this because it must be your `VaadinServletService`.

But you are not using any methods of VaadinServletService because VaadinService is enough.

2021-02-04 08:18 UTC, stbischof commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinServletRequest.java
> +    private final VaadinService vaadinService;
because then you cant use it with other VasdinService Implementations then yours

2021-02-04 08:46 UTC, stbischof commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
> +        String servletPath = ((HttpServletRequest) request).getServletPath();
I fixed the description.

2021-02-04 08:46 UTC, stbischof commented on flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
> +        if (request instanceof HttpServletRequest) {
I fixed the description.

2021-02-04 08:46 UTC, stbischof commented on flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
> +                                .wrap((HttpServletResponse) response));
I fixed the description.

2021-02-04 08:46 UTC, stbischof commented on flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
> +                    "Only HttpServletRequest are supported");
I fixed the description.

2021-02-04 08:46 UTC, stbischof commented on flow-server/src/main/java/com/vaadin/flow/server/communication/StreamResourceHandler.java
> +            ServletContext context = ((ServletRequest) request)
I fixed the description.

2021-02-04 08:46 UTC, stbischof commented on flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
> +        return ((HttpServletRequest) request).getRequestURL().toString();
I fixed the description.

2021-02-04 08:49 UTC, stbischof commented on flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
> +            url = ((HttpServletRequestWrapper) request).getRequestURL().toString();
here it is just a cleanup because you do not need a `VaadinServletRequest`. The `HttpServletRequestWrapper` is enough to `.getRequestURL()`. And others that do not use the `VaadinServletRequest`will not end with a ClassCastException

2021-02-04 08:52 UTC, stbischof commented on flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
> +                                .wrap((HttpServletRequest) request),
when it is a HttpServletRequest but not a VaadinServletRequest

2021-02-09 12:04 UTC, pleku reviewed
If we we're to _allow having your own `VaadinService`_ then it would be good if there was some sort of test in the project that would make it so that this feature is not accidentally broken.

Now that the reasoning behind the PR is clear, the next question would be about the added value and use case - why do you want to use your own VaadinService ?

(edit: this type of discussions would be better to have in an issue before starting the implementation)

2021-02-09 12:45 UTC, stbischof commented
Because of your OSGi approach is not the way how I would expect to handle OSGi and Vaadin. It is kind of "Works with OSGi" and will fit most of people. But really working with `Services` is in a deep way would look other.

And your OSGi bundles also have the wrong license.

2021-02-09 12:51 UTC, stbischof commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
> +    private VaadinContext initializeContext() {
sure. will change this back.

2021-02-10 07:01 UTC, pleku commented
> Because of your OSGi approach is not the way how I would expect to handle OSGi and Vaadin. It is kind of "Works with OSGi" and will fit most of people. But really working with Services is in a deep way would look other.

I take it you mean with this that _there would be a better way for this to work by utilizing declarative services in OSGi_. I think this is a direction that we would want to take too and would gladly accept those contributions, but this direction should be taken by first discussing and agreeing on the steps in issues before jumping into implementation - it will be more smooth that way as then we know what is incoming and are more likely to help you get it in instead of need to start by questioning that "why is this code needed". From our perspective, we have to start that way as we're promising to maintain the code for 15 years to users who need that.

> And your OSGi bundles also have the wrong license.

Just to be sure - do you mean the commercial license in vaadin/osgi or something else ?

> If you allow others to having an own VaadinService i will add test that force and check ClassCastExceptions.

I don't have any objections to this now that I understand the goal. Though, I would rather work together to improve our OSGi support for all instead of enabling people to build their own support. We're gladly willing to give out licenses to those who contribute to it.

2021-02-10 07:37 UTC, stbischof commented
I broken all my contribution in the moment where i had seen that you moved the osgi part to commercial license in vaadin/osgi.
Also parts that had been under the normal license. 

Because this was just an private interest a commercial license would not be an option for me.

2021-02-17 12:26 UTC, pleku commented
To clarify to myself for later times, this is still waiting for a test to be added that would prevent breaking the "feature" that easily.

2021-02-18 11:17 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +                    && (response instanceof HttpServletResponse)) {
Overall I like the idea behind this PR, I just have a problem with the explicit downcast from `VaadinServletResponse` to `HttpServletResponse` with the upcoming jakarta namespace change in mind. Totally out of scope, just my 2 cents.

2021-02-18 11:24 UTC, stbischof commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
> +                    && (response instanceof HttpServletResponse)) {
New interfaces that extends response and provides the Methods may be a way to solve this

2021-02-18 11:49 UTC, stbischof commented
i added the wished tests: `OtherImplementationsTest.java`

2021-02-18 14:43 UTC, pleku commented
The build failed due to unrelated build agent issues, I'll retrigger it tomorrow and take a look at the test.

2021-02-24 18:00 UTC, stbischof commented
Could you please retrigger it?

2021-02-24 18:25 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
> +            if (request instanceof HttpServletRequest&&((HttpServletRequest)request).getRequestedSessionId() == null) {
```suggestion
            if (request instanceof HttpServletRequest && ((HttpServletRequest) request).getRequestedSessionId() == null) {
```

@stbischof This could help with your rebuild as well ;) and makes the code a little bit easier to read.

2021-02-25 08:03 UTC, stbischof commented
forced push to trigger rerun of tests, (last one also did not finished

2021-03-02 08:08 UTC, pleku requested changes
Sorry for the long delay, I was on winter vacation last week ⛷️ 

Only couple of small comments and then this would be 🟢

2021-03-02 08:08 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/OtherImplementationsTest.java
> +    public void StaticFileServer_Constructor_uses_VadinService()
non-blocking nit: typoed Vaadin here and c/p the error to other method names too ...

2021-03-02 08:08 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/OtherImplementationsTest.java
> +public class OtherImplementationsTest {
I get the test, but at a glance probably most developers will not. Please change the name to `CustomVaadinServiceImplementationTest` and maybe add a comment line "Makes sure that a custom vaadin service that is not vaadin servlet service can be used in when desired".

2021-03-02 15:07 UTC, stbischof commented on flow-server/src/test/java/com/vaadin/flow/server/OtherImplementationsTest.java
> +public class OtherImplementationsTest {
Done, Thx

2021-03-02 15:07 UTC, stbischof commented on flow-server/src/test/java/com/vaadin/flow/server/OtherImplementationsTest.java
> +    public void StaticFileServer_Constructor_uses_VadinService()
changed into Vaadin

2021-03-04 08:06 UTC, pleku approved these changes

2021-03-04 08:55 UTC, merged

2021-04-14 07:56 UTC, Legioth commented
This change causes massive backwards binary compatibility issues with e.g. add-ons compiled against older versions of Vaadin. This happens because method invocations in bytecode are tied to the method return type and not only the method name and parameter types.

I would suggest reverting to avoid those issues.

Furthermore,  I don't even understand the whole point of making this change. If you want to use a custom service implementation together with `VaadinServlet`, then why wouldn't you extend `VaadinServletService` instead of the generic `VaadinService` class?

2021-04-15 15:51 UTC, Legioth commented
To further elaborate on my previous message, the point is that `VaadinServlet` and `VaadinServletService` should really be seen as a single unit that just happens to be split up into two separate classes because Java doesn't offer multiple inheritance.

They're not supposed to be separated from each other. A proper separation would require more thorough architectural considerations rather than only tweaking some return types that happened to get in the way when trying to do something that you're not supposed to even try.

2021-04-26 14:45 UTC, pleku commented
I don't know why the bot has added the label `Released with Platform 19.0.0` as it is not true - @ZheSun88 ?

2021-04-26 15:31 UTC, ZheSun88 commented
@pleku somehow the bot caught flow 7.0.0.alpha1 release note for platform 19.0.0 release. i will check other tickets in that release.