fix: recompile Webpack when adding a new CSS file to app theme
vaadin/flow pull request #9708
Opened 2020-12-21 12:32 UTC by mshabarov

Adding a new file to `frontend/themes/my-theme` now triggers the `webpack` recompilation and updates the application.

Fixes: https://github.com/vaadin/flow/issues/9594

2020-12-21 13:18 UTC, caalador requested changes

2020-12-21 13:18 UTC, caalador commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +    compiler.plugin("after-compile", function (compilation, callback) {
This plugin should only be set in devMode

2020-12-21 13:18 UTC, caalador commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +    compiler.plugin("watch-run", (compilation, callback) => {
Also this plugin should only run in dev mode.

2020-12-21 13:18 UTC, caalador commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +  return JSON.parse(themePropertyFileAsString);
Strange that it doesn't parse empty string.
A cleaner solution is `JSON.parse(fs.readFileSync(themePropertyFile)||'{}')`

2020-12-21 13:22 UTC, mshabarov commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +        const nameRegex = /themes\/(.*)\/\1.generated.js/g;
Because `nameRegex.exec` return `null` on a second run, so I need to reset it. https://stackoverflow.com/questions/4724701/regexp-exec-returns-null-sporadically

2020-12-21 13:33 UTC, mshabarov commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +  return JSON.parse(themePropertyFileAsString);
Yep, this looks more clean, but the "truthy" value check of `fs.readFileSync(themePropertyFile)` does not work for some reason. It still gives: 
```javascript
return JSON.parse(fs.readFileSync(themePropertyFile)||'{}');
              ^
SyntaxError: Unexpected end of JSON input
```

2020-12-22 04:53 UTC, caalador commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +        const nameRegex = /themes\/(.*)\/\1.generated.js/g;
That's because of the global status just remove the `g` from the end.

2020-12-22 08:12 UTC, caalador commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +    compiler.plugin("after-compile", function (compilation, callback) {
For this there also exists npmjs.com/package/extra-watch-webpack-plugin

2020-12-22 08:12 UTC, caalador commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +    const handleThemesHook = () => {
Perhaps even move this out to its own file so it's easier to reuse.

2020-12-22 10:01 UTC, caalador commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +        compilation.contextDependencies.add('frontend/themes/' + themeName);
This might be wrong as the folder might also be under `src/...` though editing anything there would restart the server due to changes in classpath.

2020-12-23 06:28 UTC, caalador requested changes

2020-12-23 06:28 UTC, caalador commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +    generateThemeCallback = (logger) => generateTheme(this.options, logger);
These can and probably should be called on request so that `getThemeName` calls `extractThemeName` and `getThemeCallback` just creates the lambda when requested perhaps even using the callers logger instead of the appThemeLogger.

2020-12-23 06:28 UTC, caalador commented on flow-server/src/main/resources/plugins/theme-live-reload-plugin/theme-live-reload-plugin.js
> +module.exports = ThemeLiveReloadPlugin;
Missing new line.

2020-12-23 06:28 UTC, caalador commented on flow-server/src/main/resources/plugins/theme-live-reload-plugin/theme-live-reload-plugin.js
> +        logger = compiler.getInfrastructureLogger("ThemeLiveReloadPlugin");
insignificant: As the logger is not used outside of the watchRun hook then it doesn't need to be stored outside.

2020-12-23 06:28 UTC, caalador commented on flow-server/src/main/resources/plugins/theme-live-reload-plugin/theme-live-reload-plugin.js
> +      compiler.plugin("watch-run", (compilation, callback) => {
```suggestion
      compiler.hooks.watchRun.tapAsync("ThemeLiveReloadPlugin", (compilation, callback) => {
```

2020-12-23 07:51 UTC, mshabarov commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +    const handleThemesHook = () => {
Moved to it's own file

2020-12-23 07:51 UTC, mshabarov commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +        const nameRegex = /themes\/(.*)\/\1.generated.js/g;
Done

2020-12-23 07:52 UTC, mshabarov commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
>      });
Done, moved to its own plugin

2020-12-23 07:54 UTC, mshabarov commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +                "Extending another theme is possible by adding { \"parent\": \"my-parent-theme\" } entry to the theme.json file inside your theme folder.");
Seems there are still some wrong indentation after moving to separate file. Will double check and fix

2020-12-23 07:54 UTC, mshabarov commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +    compiler.plugin("after-compile", function (compilation, callback) {
extra-watch-webpack-plugin is now used

2020-12-23 07:55 UTC, mshabarov commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +    compiler.plugin("watch-run", (compilation, callback) => {
done

2020-12-23 08:02 UTC, mshabarov commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +        compilation.contextDependencies.add('frontend/themes/' + themeName);
Do you mean these folders `src/main/resources/static` and `src/main/resources/META-INF/resources/themes` whose can contains theme resources either? Well, if the live reload agent (or jetty, or webpack) has already them to be watched, then no need to add them. I will double check with starter project, if restart happens upon adding a new files there

2020-12-23 08:10 UTC, caalador commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +        compilation.contextDependencies.add('frontend/themes/' + themeName);
Those yes, but I don't know if we need to support those with this.

2020-12-23 08:13 UTC, caalador commented on flow-server/src/main/resources/webpack.generated.js
> +    devMode && new ThemeLiveReloadPlugin(getThemeName, getGenerateThemeCallback),
One issue is that if we don't have a themeName then these shouldn't be added at all either.

2020-12-23 08:42 UTC, mshabarov commented on flow-server/src/main/resources/webpack.generated.js
> +    devMode && new ThemeLiveReloadPlugin(getThemeName, getGenerateThemeCallback),
Yep, assuming that the `getThemeName` should extract the theme name on request, I can create a `themeName` variable somewhere before these plugins array and just use it for extra watch and live reload plugins.

2020-12-23 08:44 UTC, caalador commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +    themeName = extractThemeName(generatedThemeFile);
The build fails here as you do not check that the file exists in the first place.

```
[17:46:28]	[Step 5/11] Error: ENOENT: no such file or directory, open '/tmp/junit8056780026882223291/target/flow-frontend/themes/theme-generated.js'
[17:46:28]	[Step 5/11]     at Object.openSync (fs.js:448:3)
[17:46:28]	[Step 5/11]     at Object.readFileSync (fs.js:348:35)
[17:46:28]	[Step 5/11]     at extractThemeName (/tmp/junit8056780026882223291/node_modules/@vaadin/application-theme-plugin/theme-handle.js:130:28)
[17:46:28]	[Step 5/11]     at new ApplicationThemePlugin (/tmp/junit8056780026882223291/node_modules/@vaadin/application-theme-plugin/application-theme-plugin.js:47:17)
[17:46:28]	[Step 5/11]     at Object.<anonymous> (/tmp/junit8056780026882223291/webpack.generated.js:234:5)
```
```

2020-12-23 08:45 UTC, caalador commented on flow-server/src/main/resources/webpack.generated.js
> +    devMode && new ThemeLiveReloadPlugin(getThemeName, getGenerateThemeCallback),
When we run webpack if the file will be created it will be available so it's fine to check and trust the result.

2020-12-23 08:52 UTC, mshabarov commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +    themeName = extractThemeName(generatedThemeFile);
Oh, thanks! I apparently didn't clean my `target` folder and it passes for my. So, you were 💯  right when requesting to make `getThemeName` to be on demand :)

2020-12-23 13:44 UTC, mshabarov commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +    themeName = extractThemeName(generatedThemeFile);
Sorry, I've just got the meaning of this. Dev server (web pack) normally starts when the node tasks (including `theme-generated.js` creating) complete. Thus, the `theme-generated.js` should exist when the web pack starts (=> when the webpack.config.js is being processed), but not yet copied to `target/flow-frontend/themes`, right? Could I extract the theme name directly from `${project.root.dir}/node_modules/@vaadin/flow-frontend/themes`?

2020-12-23 15:24 UTC, mshabarov commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> +    themeName = extractThemeName(generatedThemeFile);
`theme-generated.js` already exists before webpack starts. Found the mistake in my code.

2020-12-23 20:32 UTC, pleku reviewed
Only some comments. Probably @tanbt can finish the review once the build gets green as me and @caalador are away.

2020-12-23 20:32 UTC, pleku commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
> +    throw new Error('Theme resource folder cannot be empty');
So what happens if the user removes the `@Theme` annotation and deletes the `/themes/` folder ?

I'm not sure if this code is run in that case, but as I think that case will be probably for anyone adopting a existing project (any starter) they might want to delete the existing `/themes/` folder completely and go "vanilla style" instead without any theme.

2020-12-23 20:32 UTC, pleku commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
> +    throw new Error('Theme resource folder cannot be empty');
And should the variable name be `themesFolder` or such ? Or actually I'm a bit confused that "what is theme resource folder" as the name is not IMO obvious

2020-12-23 20:32 UTC, pleku commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
> +    throw new Error('Theme resource folder cannot be empty');
Or meh, maybe it is fine that we require them to restart the server at that point, but I think people will not know what does the error "Theme resource folder cannot be empty" mean and what to do after that ?

2020-12-23 20:32 UTC, pleku commented on flow-server/src/main/resources/plugins/theme-live-reload-plugin/theme-live-reload-plugin.js
> +        throw new Error("Missing theme generate callback or incorrect type");
Non-blocking: When could this error occur and is this error message supposed to be helpful ? If a user sees it, they have no idea what it means

2020-12-23 20:32 UTC, pleku commented on flow-server/src/main/resources/webpack.generated.js
> +const { ApplicationThemePlugin, generateTheme, extractThemeName } = require('@vaadin/application-theme-plugin');
Non-blocking: Seeing it here, I wonder if the `generateTheme` is a good name. How does it "generate the theme" ? The jsdocs say
```
 * Looks up for a theme resources in a current project and in jar dependencies,
 * copies the found resources and generates/updates meta data for webpack
 * compilation.
 ```
 so probably more suitable names would be `themeResourcesLookup` or `themeResourcesProcessor` or something like that, and same for the callback in the other file.

2020-12-27 19:50 UTC, mshabarov commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
> +    throw new Error('Theme resource folder cannot be empty');
> So what happens if the user removes the @Theme annotation and deletes the /themes/ folder ?
No, this code won't be executed in this case. 
Webpack won't trigger recompilation after delete of `/themes/`, no app reload, but the app keeps running with theme styles until you delete the `@Theme` annotation and triggers live reload. 
Then, the app theme will be deleted.
If you delete `/themes/` and then changes something else than `@Theme` and trigger live reload, then you get `Discovered @Theme annotation with theme name 'app-theme', but could not find the theme directory...` error message.

2020-12-27 20:04 UTC, mshabarov commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
> +    throw new Error('Theme resource folder cannot be empty');
> Or meh, maybe it is fine that we require them to restart the server at that point, but I think people will not know what does the error "Theme resource folder cannot be empty" mean and what to do after that ?

`themeResourceFolder` refers to the folder where the `theme-generated.js` is generated. Basically, it's value is autogenerated in `webpack.generated.js` and if it's empty, then it's a bug in the flow. But since the `extractThemeName` can be potentially be reused, then it's good to change the message reflect the problem - could not extract theme name, because the path to folder with the autogenerated file `theme-generated.js` is not set, please set this path as a `application-theme-plugin` constructor parameter.

2020-12-28 07:23 UTC, mshabarov commented on flow-server/src/main/resources/webpack.generated.js
> +const { ApplicationThemePlugin, generateTheme, extractThemeName } = require('@vaadin/application-theme-plugin');
Changed to `processThemeResources`

2020-12-28 07:24 UTC, mshabarov commented on flow-server/src/main/resources/plugins/theme-live-reload-plugin/theme-live-reload-plugin.js
> +        throw new Error("Missing theme generate callback or incorrect type");
Replaced by more meaningful message.

2020-12-29 12:18 UTC, tanbt approved these changes

2020-12-29 13:07 UTC, merged

2020-12-29 13:53 UTC, joheriks commented
When/if adding more ITs in the module in the future, it should be remembered to add `@net.jcip.annotations.NotThreadSafe` or other sequencing mechanism since the tests modify server state and are run in parallel by default and on the CI.

2020-12-29 14:05 UTC, mshabarov commented
Thanks, @joheriks ! Here is the fix https://github.com/vaadin/flow/pull/9728