Process Iterable same way as Collection type
vaadin/flow pull request #9709
Opened 2020-12-21 21:46 UTC by tdq

Extend SchemaResolver in the way to process Iterable type as Collection.
Fixes #9256

2020-12-21 22:06 UTC, haijian-vaadin requested changes
Since TypeScript has type Iterable<>, would it better if can generate a TypeScript Iterable for Java Iterable?

2020-12-22 22:06 UTC, fluorumlabs requested changes

2020-12-22 22:06 UTC, fluorumlabs commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/SchemaResolver.java
> +        return !type.isPrimitive() && (isTypeOf(type, Collection.class) || isTypeOf(type, Iterable.class));
`Collection` already extends `Iterable`

2020-12-22 22:06 UTC, fluorumlabs commented on fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
> +import com.vaadin.flow.server.connect.generator.endpoints.collectionendpoint.IterableEndpoint;
Looks like you forgot to commit `IterableEndpoint`

2021-01-04 08:41 UTC, tdq commented on fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/SchemaResolver.java
> +        return !type.isPrimitive() && (isTypeOf(type, Collection.class) || isTypeOf(type, Iterable.class));
Sure, so you think we can keep only Iterable here to allow such usage?
{code}
@Endpoint
@AnonymousAllowed
public class VaadinEndpoint {

    public static class Foo {
        public String bar = "bar";
    }

    public Iterable<Foo> getFoos() {
        return Arrays.asList(new Foo(), new Foo());
    }
}
{code}

2021-01-13 17:01 UTC, platosha commented
> Since TypeScript has type Iterable<>, would it better if can generate a TypeScript Iterable for Java Iterable?

For a regular (sync) Iterable means supporting sync `for...of` loop in TypeScript. That requires that the (async) result of the endpoint call would have all the items on the client side. In practice this means using an array under-the-hood anyway. Arrays are Iterable themselves, btw. I don’t think it’s worth to declare `Iterable` on what is in fact a regular array, it would make using that array harder for no benefit.

But, something potentially useful here is `AsyncIterable`. When used with `for await...of` iterators, as every iteration is async, this could enable requesting additional items from the endpoint on demand from the iterator, instead of everything at once. 

BTW Unlike `Collection<>`, `Iterable<>` does not contain a defined size, which means to me that for a given iterator there is no guarantee that it ever reaches an end. I wonder if it is fair that Fusion server tries to serialise all the items from a given iterable into a single JSON array response in Java. Would it rather be expected that items are requested from the iterator one-by-one upon iterating on the caller side, the client?

2021-01-27 08:59 UTC, haijian-vaadin approved these changes
Turns out using `Iterable` for TypeScript is not necessary.

2021-02-23 09:15 UTC, fluorumlabs approved these changes

2021-02-24 09:33 UTC, merged