fix: AppTheme is not applied in client-side Fusion
vaadin/flow pull request #9725
Opened 2020-12-25 09:46 UTC by tanbt

Fixes https://github.com/vaadin/flow/issues/9684

2020-12-31 14:42 UTC, tanbt commented
The script that applies AppTheme `.... applyTheme(document);` is generated in `target/frontend/generated-flow-imports` which is imported for server-side views only by the index.ts file
```
export const { serverSideRoutes } = new Flow({
  imports: () => import('../target/frontend/generated-flow-imports'),
});
```

[The solution](https://vaadin.slack.com/archives/CDNTYMS9H/p1608641893104400?thread_ts=1608219489.062900&cid=CDNTYMS9H) is to generate a bootstrap file i.e `frontend/generated/vaadin.ts` that includes  the script for loading AppTheme and [also imports index.ts](https://vaadin.slack.com/archives/CDNTYMS9H/p1609144801187600).

2021-01-04 11:59 UTC, tanbt commented
Since `vaadin.ts` is always loaded, I wonder if the script for loading AppTheme in `generated-flow-import.js` file is now redundant?

2021-01-04 12:07 UTC, mshabarov commented
> Since vaadin.ts is always loaded, I wonder if the script for loading AppTheme in generated-flow-import.js file is now redundant?

Good point. I believe now it's redundant, and maybe even dangerous.

2021-01-04 12:21 UTC, mshabarov requested changes

2021-01-04 12:21 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +            commands.add(new TaskGenerateBootstrap(frontendDependencies, builder.frontendDirectory));
Do I understand right, that this fix won't work for old (deprecated) bootstrapping? Although, it might be completely fine, because TS views theming is not even needed with deprecated V14 bootstrap, is it?

2021-01-04 12:21 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
> +            lines.add("applyTheme(document);");
`WebComponentGenerator` class still contains `applyTheme` code injection for shadow root. Do we need to point it to the `vaadin.ts` within this PR, or is it another feature/fix?

2021-01-04 12:21 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
> + * A task for generate a TS file which is always executed in a Vaadin app.
Not clear from this javadoc what's the file (name), when and where is it being executed, as well as it's goal.

2021-01-04 13:11 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
> +                .getUnixRelativePath(connectClientTsApiFolder.toPath(), path);
Could you please give a comment here that the `relativePath` is a relative path of a file given by `path` to the path `frontend/generated`? It's really hard to get the meaning of this line of code without any certain example.

2021-01-04 13:46 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
> +        return frontDeps != null && connectClientTsApiFolder != null;
Also, don't we check here the result of `shouldApplyAppTheme()` ? So that if no theme definition => no file generate?

2021-01-04 13:46 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
> +                : Paths.get(frontendDirectory.getParentFile().getPath(), TARGET,
Oh, this was taken from `TaskUpdateWebpack`. Skip my comment.

2021-01-04 13:46 UTC, mshabarov commented on flow-tests/test-ccdm/package.json
> +{
Was this file committed intentionally? Usually it is ignored for `flow-tests`

2021-01-04 13:47 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
> +                : Paths.get(frontendDirectory.getParentFile().getPath(), TARGET,
Oh, this was taken from TaskUpdateWebpack. Skip my comment.

2021-01-04 13:50 UTC, mshabarov commented
Verified with TS starter from `start.vaadin.com` and the theme was applied as expected. Great job!

2021-01-05 11:09 UTC, tanbt commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
> +            lines.add("applyTheme(document);");
Does `WebComponentGenerator` work in TS client-side views?
`WebComponentGenerator` is new to me, and I didn't consider it during this PR.

2021-01-05 11:18 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +            commands.add(new TaskGenerateBootstrap(frontendDependencies, builder.frontendDirectory));
Yes, Viktor confirmed TS views do not work in old bootstrapping.

2021-01-05 12:08 UTC, mshabarov approved these changes

2021-01-05 13:54 UTC, mshabarov submitted a review, later dismissed

2021-01-07 06:57 UTC, mshabarov approved these changes

2021-01-07 07:01 UTC, mshabarov commented
LGTM, but this issue marked as a critical:

`CRITICAL First sentence of Javadoc is incomplete (period is missing) or not present. rule`

So maybe good to add a dot here before merging.

2021-01-07 07:02 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
> +     * frontend folder
```suggestion
     * frontend folder.
```

2021-01-07 07:51 UTC, mshabarov approved these changes

2021-01-07 08:17 UTC, merged