Refactor Lookup initialization for Servlet 3.0 containers
vaadin/flow pull request #9727
Opened 2020-12-29 08:41 UTC by denis-anisimov

Provides SPI for Lookup SPI

fixes #9717

2021-01-04 10:30 UTC, caalador requested changes

2021-01-04 17:09 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/di/LookupInitializer.java
> + * {@link VaadinContext#getAttribute(Class)}.
Done

2021-01-04 17:12 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/di/LookupIntializerTest.java
> +    public void createLookup_instantiatorsAreProvidedAsScannedClasses_lookupThrows()
Done

2021-01-05 04:40 UTC, caalador approved these changes

2021-01-05 12:21 UTC, merged