feat: implement NativeDetails as html component
vaadin/flow pull request #9735
Opened 2021-01-02 16:37 UTC by knoobie

Reasoning: Currently `<details>` is missing from the list of html components. This PR fixes this. 

`NativeDetails`  is based on `vaadin-details` except that the html property is called `open` instead of `opened` and the event is called `Toggle` like the html dom event. 

To reduce the API noise `NativeDetails` extends `HtmlComponent` instead of `HtmlContainer`. `HasText` and `HasComponents` would interfere with the already set `<summary>` inside the `<details>`.

2021-01-13 13:49 UTC, pleku requested changes

2021-01-13 13:49 UTC, pleku commented on flow-html-components-testbench/src/test/java/com/vaadin/flow/component/html/testbench/NativeDetailsElementIT.java
> +
Missing an IT where the details is opened via server side (by executing code in a click listener)

2021-01-13 13:49 UTC, pleku commented on flow-html-components-testbench/src/test/java/com/vaadin/flow/component/html/testbench/NativeDetailsElementIT.java
> +}
Missing an IT where the details has been opened through server side state when the component is rendered

(I usually do it by using a query/view parameter and reading that in the view to determine it should be opened when present, e.g. `details?opened` or `details/opened`)

2021-01-13 13:49 UTC, pleku commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/NativeDetails.java
> +    public Registration addOpenChangedListener(
This is against our naming conventions - since the event name is `ToggleEvent`, the corresponding listener API should thus be `addToggleListener`.

I understand the intention to go with same event name as in browser, but then I think this API should match it.
This current API, `addOpenChangedListener` would IMO in this case have to match the `open`-property and it being changed.

2021-01-13 13:49 UTC, pleku commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/NativeDetails.java
> +      .propertyWithDefault("open", false);
One problem with the `open` property on server side is that it is not synchronized with the client side value. And I don't know if this is intentional or not because there is no javadocs mention on this - so I would expect it to be synchronized. Otherwise things will get unsync. So the options are:
a) fix the property synchronization to happen automatically on the `toggle` event. I don't know how much details you need to make this happen - the element API has `addPropertyChangeListener(String propertyName, String domEventName, PropertyChangeListener listener)` which can be used - but to do it properly you should have one property listener for each component and then have that one trigger the component level `ToggleEvent` on server side after updating the property value (in case there are listeners on server side). You can utilize the `ComponentEventBus` for firing the events on the component level.
b) Remove the `open` property and change the API to be `open()` & `close()` instead - then it doesn't match the DOM API though
c) Remove the `open` property and make it be `toggle(boolean open)` instead without getter ?

I would go with a), WDYT Christian ?

2021-01-13 13:49 UTC, pleku commented on flow-html-components-testbench/src/test/java/com/vaadin/flow/component/html/testbench/NativeDetailsElementIT.java
> +    }
Maybe: Missing an IT where the detais summary is focused and then opened/closed with space key ?

2021-01-13 13:49 UTC, pleku commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/NativeDetails.java
> +public class NativeDetails extends HtmlComponent implements ClickNotifier<NativeDetails> {
Non-blocking: As focus+space should open the details, I wonder if this should implement `Focusable` ...
maybe not needed for now (or ever)

2021-01-13 13:49 UTC, pleku commented on flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/NativeDetailsElement.java
> +
Should there be `toggle()` / `click()` API which simulates user clicking the element summary to open/close it

2021-01-13 13:52 UTC, pleku commented
Also one overall note - the import order does not match the conventions https://github.com/vaadin/flow/blob/master/CONTRIBUTING.md#project-setup

2021-01-13 14:40 UTC, knoobie commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/NativeDetails.java
> +public class NativeDetails extends HtmlComponent implements ClickNotifier<NativeDetails> {
While implementing, I asked myself the same and played with `Focusable`. The problem or let's say the technical detail is, that the `<detail>` isn't focused. Instead the `<summary>` gets focused and is used by the browser for keyboard handling to open/close the details. 

Instead of implementing `Focusable` in both components and delegating every call to the `<summary>`, I did not implement it to reduce complexity.

See WhatWG HTML Spec:

> This ability to request that additional information be shown or hidden may simply be the activation behavior of the appropriate summary element

Source: https://html.spec.whatwg.org/multipage/interactive-elements.html#htmldetailselement

This note was extremely interesting while testing the feature with "fast" clicking:

> When the open attribute is toggled several times in succession, these steps essentially get coalesced so that only one event is fired.

2021-01-13 14:52 UTC, knoobie commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/NativeDetails.java
> +      .propertyWithDefault("open", false);
Option A sounds like the most reasonable. I'm gonna take a look at it. 

I would probably try the `@Synchronize` approach first, which is used in the [flow component details](https://github.com/vaadin/vaadin-flow-components/blob/master/vaadin-details-flow-parent/vaadin-details-flow/src/main/java/com/vaadin/flow/component/details/Details.java). 

I'm wondering why I didn't used it, while creating the component.. I think I wanted to use the same API (PropertyDescriptor) as every other html component in the package.

2021-01-13 14:53 UTC, knoobie commented
I've read your other comments and try to fix them all on the next update. Probably in 1-2 days or at the weekend. Thanks for the thought out review!

2021-01-13 21:13 UTC, knoobie commented on flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/NativeDetailsElement.java
> +
Added a `toggle()` method and tested the method within `NativeDetailsElementIT#toggleNativeDetailsWithTestBenchElement`.

2021-01-13 21:16 UTC, knoobie commented on flow-html-components-testbench/src/test/java/com/vaadin/flow/component/html/testbench/NativeDetailsElementIT.java
> +    }
Personally, I don't like to test browser default behavior on native elements, but I can create a test if you want ;)

2021-01-13 21:17 UTC, knoobie commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/NativeDetails.java
> +    public Registration addOpenChangedListener(
Done. Renamed the method to `addToogleListener`.

2021-01-13 21:18 UTC, knoobie commented on flow-html-components-testbench/src/test/java/com/vaadin/flow/component/html/testbench/NativeDetailsElementIT.java
> +}
Done  within `NativeDetailsElementIT#openAndCloseDetailsFromOtherServerSideComponent`.

2021-01-13 21:18 UTC, knoobie commented on flow-html-components-testbench/src/test/java/com/vaadin/flow/component/html/testbench/NativeDetailsElementIT.java
> +
Done  within `NativeDetailsElementIT#openAndCloseDetailsFromOtherServerSideComponent`.

2021-01-13 21:19 UTC, knoobie commented on flow-html-components-testbench/src/test/java/com/vaadin/flow/component/html/testbench/NativeDetailsView.java
> +            log.setText("Toggle event is '" + e.isOpened() + "'");
Done. Every test case was updated to include the current event count.

2021-01-13 21:36 UTC, knoobie commented
> Also one overall note - the import order does not match the conventions https://github.com/vaadin/flow/blob/master/CONTRIBUTING.md#project-setup

I've tried my luck with the intellij setup. Resulting in weird formatting behavior for me. 

![image](https://user-images.githubusercontent.com/3968629/104511893-ac39a080-55ed-11eb-8cbc-32d6b52b516d.png)

I changed the obvious formatting for the imports by hand to match the contributing guideline and used `mvn formatter:format` for other stuff. 

FYI: `mvn formatter:format` resulted in this:

![image](https://user-images.githubusercontent.com/3968629/104513095-641b7d80-55ef-11eb-8d7e-80deb853dd50.png)

I think everything is done now :)

2021-01-14 09:17 UTC, pleku commented on flow-html-components-testbench/src/test/java/com/vaadin/flow/component/html/testbench/NativeDetailsElementIT.java
> +    }
I agree, it is not necessary. Hence the _maybe_

2021-01-14 09:50 UTC, pleku requested changes

2021-01-14 09:50 UTC, pleku commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/NativeDetails.java
> +            return getSource().isOpen();
My first impression was that I would have kept the "cached" value in the event and instead used that one for all the events. But after thinking it through, I thought about that since that is how it works (for good reasons) for `ValueChangeEvent`. Now this is not semantically exactly the same as that.

I can't say which one is more expected or better for usage, but I think the method javadocs need to be updated to explicitly mention that _is this the captured value_ or just delegating to the actual details component itself.

2021-01-14 09:50 UTC, pleku commented on flow-html-components-testbench/src/test/java/com/vaadin/flow/component/html/testbench/NativeDetailsElementIT.java
> +        Assert.assertEquals("Toggle event number '1' is 'true'", log.getText());
I'm wondering, is this event triggered by the server side or the client side ? (I understood it is latter)
When it happens on the client side after the component has been rendered, it will require another roundtrip to just fire the event (the property value has not changed). So basically for the `ToggleEvent` (always) reports that `isFromClient` is `true` event though the `setOpen` was actually called from the server side to trigger the toggle.

While this is a trivial component itself, it is not that trivial to integrate due to this event-property synchronization. I don't know how big (if any) problem it is that the programmatic toggle event would cause an extra roundtrip and not reveal if it actually occurred by server/client. But I do know that the intention should be documented (in event or adding listener method and `setOpen`) and preferably also confirmed in a test so that it is considered "intended behavior" instead of just an oversight.

Since the `Toggle` event semantics are not the same as would be with `OpenChangedEvent`, I would just document this behavior. Anyone who needs to know if the open changed by server/client, they would use `details.getElement.addPropertyChangeListener("open"....` to distinct that.

2021-01-14 10:19 UTC, knoobie commented on flow-html-components-testbench/src/test/java/com/vaadin/flow/component/html/testbench/NativeDetailsElementIT.java
> +        Assert.assertEquals("Toggle event number '1' is 'true'", log.getText());
While developing, I had the same problem in mind. Looking at e.g. other roundtrip / client based actions like `focus` I was like "okay, that's how it is." Same as you said here: https://github.com/vaadin/flow/issues/9768

I'm not sure how I can tackle this to force the "server side" change without any hacks. I would probably go with a javadoc notice like with your comment above.

2021-01-14 11:23 UTC, knoobie commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/NativeDetails.java
> +            return getSource().isOpen();
Done. Javadoc updated.

2021-01-14 11:23 UTC, knoobie commented on flow-html-components-testbench/src/test/java/com/vaadin/flow/component/html/testbench/NativeDetailsElementIT.java
> +        Assert.assertEquals("Toggle event number '1' is 'true'", log.getText());
Done. Javadoc updated.

2021-01-14 12:11 UTC, pleku approved these changes

2021-01-14 12:11 UTC, pleku commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/NativeDetails.java
> +         * Resulting in {@code fromClient} to be always {@code true}.
Non-blocking: this note would have belonged to overridden `isFromClient()` to be discoverable (not blocking since it is in the add listener method)

2021-01-14 12:23 UTC, knoobie commented on flow-html-components/src/main/java/com/vaadin/flow/component/html/NativeDetails.java
> +         * Resulting in {@code fromClient} to be always {@code true}.
My first draft (non-commited) had this change. I decide against this, because I had to overwrite the method "just to clarify" the javadoc while additionally fighting with myself if I wanna return `true` or `super.isFromClient()`.

2021-01-14 13:13 UTC, merged

2021-01-14 13:14 UTC, pleku commented
Thanks for this contribution too @knoobie !

2021-01-26 14:43 UTC, mshabarov commented
Cherry picked to `2.5`