TEST:  Extract plugin code to a separate module
vaadin/flow pull request #9752
Opened 2021-01-06 17:13 UTC by stbischof

fixes #9685

2021-01-08 15:52 UTC, stbischof commented
Need some help because i could not see why and where this fails.

2021-01-08 15:57 UTC, stbischof commented
@ mvysny ,@pleku
I need some help because i could not see why and where this fails.

2021-01-12 00:42 UTC, stbischof commented
@mvysny cold you have a look an this?

2021-01-12 10:59 UTC, stbischof commented on flow-plugin/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +  public static ClassFinder getClassFinder(List<String> classpathElements) {
there is a doc.
  /**
   * creates a {@link ClassFinder} from a List of classpathElements.
   *
   * @param classpathElements
   * @return the {@link ClassFinder} that uses the classpathElements
   */

2021-01-12 12:18 UTC, mvysny reviewed
Thank you, looks good, but there are couple of things that will cause problems. Also added @caalador as a reviewer since he knows who own the plugin code and who would be the best to perform the review.

2021-01-12 12:18 UTC, mvysny commented on flow-plugin/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +        .inheritIO();
We need to avoid inheritIO() because of https://github.com/vaadin/flow/issues/8947 . Even better is to use the zeroturnaround's exec library and create a static `exec()` function which runs given command properly as it is done with the Gradle plugin: https://github.com/vaadin/vaadin-gradle-plugin/blob/master/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt#L98

2021-01-12 12:18 UTC, mvysny commented on pom.xml
> -        <module>flow-maven-plugin</module>
This is dangerous: flow-maven-plugin is used in MPR-based projects; renaming this is an incompatible change.

2021-01-13 22:18 UTC, stbischof commented on pom.xml
> -        <module>flow-maven-plugin</module>
This is not a renaming. This is a move into a sub module

2021-01-15 07:32 UTC, mvysny commented on flow-plugin/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +        .directory(adapter.projectBaseDirectory().toFile());
Perfect! I'd use also `.readOutput(true).destroyOnExit()`, to make sure that the stdout/stderr is read properly and the process is properly killed afterwards.

2021-01-15 07:32 UTC, mvysny commented on flow-plugin/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +    } catch (InvalidExitValueException e) {
You need to call `exitValues(0)` in order for the `InvalidExitValueException` to be thrown.

2021-01-15 07:32 UTC, mvysny commented on flow-plugin/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +          "Failed to read webpack process stderr. Webpack process exited with non-zero exit code.%nStderr: '%s'",
Please remove the "Failed to read webpack process stderr." since it's always possible to read the stderr :+1:

2021-01-15 07:37 UTC, stbischof commented on flow-plugin/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +        .directory(adapter.projectBaseDirectory().toFile());
@mvysny  your reaction is quick. i just pushed it to test it;-) Will add all your comments

2021-01-15 08:15 UTC, stbischof commented on flow-plugin/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +    } catch (InvalidExitValueException e) {
sure `exitValueNormal()` should be more readable

2021-01-19 13:55 UTC, stbischof commented on flow-plugin/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +          "Failed to read webpack process stderr. Webpack process exited with non-zero exit code.%nStderr: '%s'",
done

2021-01-20 12:04 UTC, stbischof commented
@mvysny This comment https://github.com/vaadin/flow/pull/9752#discussion_r555222035 is wrong! Is there a Way that @vaadin-bot rerun this check?

2021-01-20 12:57 UTC, mvysny commented
@stbischof no worries, the personal review of the code is way more important than the SonarQube results. Let's hope @caalador will find some time to review this.

2021-01-27 12:14 UTC, stbischof commented
@caalador @mvysny Is there any opportunity get information about the estimated date of review? It would help a lot to plan my time.

2021-01-27 12:40 UTC, mvysny commented
@mstahv any estimate please?

2021-01-27 13:37 UTC, mstahv commented on flow-plugin/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +   * @param classpathElements
```suggestion
   * @param classpathElements the list of classpath elements
```

2021-01-27 13:37 UTC, mstahv commented on flow-plugin/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +  public static ClassFinder getClassFinder(List<String> classpathElements) {
But there is no description for the parameter. Fixed by the suggestion I added above. Probably not too helpful, but at least the javadoc compiler won't nag.

2021-01-27 13:39 UTC, mstahv commented
@mvysny You also have some non-closed discussions from your review. Looks good to me, but somebody from the team should still look into this.

2021-01-27 13:42 UTC, mstahv commented
There also seem to be conflicts with the master. Didn't check what those are, but if @stbischof can rebase the changes, that would speed up to get the changes in.

2021-01-27 14:43 UTC, stbischof commented on flow-plugin/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +   * @param classpathElements
thx

2021-01-27 15:06 UTC, mvysny approved these changes
looks good to me

2021-01-27 21:17 UTC, stbischof commented
> There also seem to be conflicts with the master. Didn't check what those are, but if @stbischof can rebase the changes, that would speed up to get the changes in.

@mstahv is rebased

2021-02-02 15:10 UTC, stbischof commented
Tell me if you really want to merge this. Then I will rebase this again. 

Its not nice the to ask me to resolve Conflicting again and again but then no review happened and new conflicts will come up.

2021-02-02 15:12 UTC, mvysny commented
@stbischof I'm so sorry but unfortunately I have no authority over this. All I can do is to kick and scream loudly... :(

2021-02-02 15:12 UTC, mstahv submitted a review, later dismissed

2021-02-02 15:15 UTC, mstahv commented
@caalador or @pleku Check these changes through. They look very helpful for Gradle plugin and potentionally other build solutions too. We want to get this in. I just don't know how these might affect e.g. platform build, so I don't dare to land the changes myself.

2021-02-02 15:31 UTC, stbischof commented
It ia just to be able to schedule m Time. It is okay when it takes weeks, when i know.

I am just surprised about that because the gradle plugin is still broke since weeks.

2021-02-03 15:57 UTC, mstahv commented
@stbischof Don't worry about rebase, the reviewer can also do it before landing it. It just helps a bit. This will be taken in next week by latest and then we'll proceed to refactor Gradle plugin to use the new module ASAP. I hope we could do the integration within Vaadin 20 timeframe.

2021-02-04 07:00 UTC, caalador reviewed
`flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven`
Still contains the files:
`BuildFrontendMojo.java`
`FlowModeAbstractMojo.java`
`PrepareFrontendMojo.java`

This makes it harder to see the changes done to those files.

2021-02-04 09:49 UTC, stbischof commented
@caalador 
* rebased
* formatted
* squashed

2021-02-04 11:06 UTC, caalador requested changes

2021-02-04 11:06 UTC, caalador commented on flow-plugin/flow-plugin-base/pom.xml
> +</project>
```suggestion
</project>

```
Missing new line

2021-02-04 13:17 UTC, stbischof commented on pom.xml
> +        <module>flow-plugin</module>
we should!

2021-02-04 13:29 UTC, stbischof commented on flow-plugin/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
> +        implements DefaultPluginAdapterBase {
not all DefaultPluginAdapterBase provides
```
    @Override
    default Path projectBuildDirectory() {

        return projectBaseDirectory().resolve(buildPathSegment());
    }

    @Override
    default Path projectBuildOutputDirectory() {

        return projectBaseDirectory().resolve(buildOutputPathSegment());
    }

    @Override
    default Path projectBuildResourcesDirectory() {

        return projectBaseDirectory().resolve(buildResourcesPathSegment());
    }
```

2021-02-04 13:31 UTC, stbischof commented on flow-plugin/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
> +        implements DefaultPluginAdapterBuild {
ok

2021-02-04 13:41 UTC, stbischof commented on flow-plugin/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/DefaultPluginAdapterBase.java
> +public interface DefaultPluginAdapterBase extends PluginAdapterBase {
i removed all DefaultPluginAdapters

2021-02-04 13:54 UTC, stbischof commented on flow-plugin/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
> +    String nodeDownloadRoot();
return URI

2021-02-04 14:01 UTC, stbischof commented on flow-plugin/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +        if (adapter.getJarFiles() != null) {
added isJarProject() to PluginAdapterBase

2021-02-04 14:03 UTC, stbischof commented on flow-plugin/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +    public static String readFullyAndClose(String readErrorMessage,
removed

2021-02-04 14:07 UTC, stbischof commented on flow-plugin/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +    .execute();
formatted

2021-02-04 14:07 UTC, stbischof commented on flow-plugin/flow-plugin-base/pom.xml
> +</project>
ok

2021-02-05 06:53 UTC, caalador requested changes
Seems fine except for the isJarProject method check that checks wrong.

Also as git review doesn't play that great with you have reviewed and force push could you 
in the future just push changes on top if the branch as it will be squashed anyway on merge thanks.

@pleku will you have a quick look also.

2021-02-05 06:53 UTC, caalador commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
> +        return getJarFiles() != null;
```suggestion
        return "jar".equals(project.getPackaging());
```

2021-02-05 06:53 UTC, caalador commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +        }
This should just throw as prepareFrontend does. Or then all 3 places should throw a ExecutionFailedException instead

2021-02-05 06:53 UTC, caalador commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +        }
Should be the same as prepareFrontend and runNodeUpdater

2021-02-05 06:55 UTC, caalador commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
> +     * @throws Exception
This needs to be updated as it fails the build with a JavaDoc error
```
[14:24:20]	[Step 5/11] /opt/agent/work/a69251da2b2bb9e9/flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java:194: error: exception not thrown: java.lang.Exception
[14:24:20]	[Step 5/11]      * @throws Exception  
```

2021-02-05 09:27 UTC, stbischof commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
> +     * @throws Exception
updated JavaDoc

2021-02-05 09:28 UTC, stbischof commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +        }
throws URISyntaxException as in the other cases

2021-02-05 09:28 UTC, stbischof commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
> +        return getJarFiles() != null;
updated

2021-02-05 09:28 UTC, stbischof commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +        }
throws URISyntaxException as in the other cases

2021-02-05 09:31 UTC, caalador submitted a review, later dismissed

2021-02-05 09:31 UTC, caalador commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
> +     * @throws Exception - Could not build an URI from nodeDownloadRoot().
```suggestion
     * @throws URISyntaxException- Could not build an URI from nodeDownloadRoot().
```

2021-02-05 09:31 UTC, caalador commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
> +     * @throws Exception - Could not build an URI from nodeDownloadRoot().
This will probably fail the build as it throws URISyntaxException not Exception

2021-02-05 09:33 UTC, stbischof commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
> +     * @throws Exception - Could not build an URI from nodeDownloadRoot().
that was fast!!

2021-02-05 09:36 UTC, caalador commented
Looks fine as long as it builds. This will probably be merged after 6.0 has been branched and we start building 7.0 from master for V20

2021-02-05 12:00 UTC, mstahv commented
When you said it, it of course don't 😁  

> [09:48:49][Step 5/11] [WARNING] The requested profile "npm" could not be activated because it does not exist.
> [09:48:49][Step 5/11] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project flow-maven-plugin: Compilation failure: Compilation failure: 
> [09:48:49][Step 5/11] [ERROR] /opt/agent/work/a69251da2b2bb9e9/flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java:[119,45] unreported exception java.net.URISyntaxException; must be caught or declared to be thrown
> [09:48:49][Step 5/11] [ERROR] /opt/agent/work/a69251da2b2bb9e9/flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java:[127,45] unreported exception java.net.URISyntaxException; must be caught or declared to be thrown
> [09:48:49][Step 5/11] [ERROR] -> [Help 1]

Anyways, great to see this getting closer 💪 Probably one of our most complex community contributions so far.

2021-02-05 12:17 UTC, caalador commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
> +        } catch (ExecutionFailedException exception) {
```suggestion
        } catch (ExecutionFailedException | URISyntaxException exception) {
```

2021-02-05 12:17 UTC, caalador commented on flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
> +            throws RuntimeException, IOException, InterruptedException,
```suggestion
            throws IOException, InterruptedException,
```

2021-02-05 12:17 UTC, caalador commented on flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
> +            } catch (RuntimeException | IOException | InterruptedException
```suggestion
            } catch (URISyntaxException | IOException | InterruptedException
```

2021-02-09 16:34 UTC, stbischof commented
I forces push some changes 30 min ago but could nit see them here.

https://github.com/bipolis/flow/tree/plugin

2021-02-10 06:59 UTC, caalador commented
Interesting as the merge conflict is a non issue as we just should update the plugin versions to 7.0-SNAPSHOT from 6.0-SNAPSHOT and mark the `flow-maven-plugin/pom.xml` as removed.

2021-02-11 07:31 UTC, pleku requested changes
I don't understand how/why, but there are at least 4 files shown as deleted and new files, instead of renamed + with changes. This breaks the history for those files and makes review take a lot longer, so can you please fix that ? Breaking the history is the bigger problem

2021-02-11 08:09 UTC, mstahv commented
Shouldn't Git figure out the moved files automatically? Maybe there is some formatting that should be done in a single change, maybe squash and see if that helps, even though it doesn't help reviewing🤔

2021-02-11 10:10 UTC, stbischof commented
I also tryed it with an git mv.. I did not found any way to get this work.
If you have it it would be interesting for me how to fix this.

2021-02-18 20:47 UTC, mstahv commented
I did following for this test PR: https://github.com/vaadin/flow/pull/10090 

 * Downloaded zip from @stbischof:s branch
 * dropped flow-plugins to fresh master branch
 * deleted abandoned flow-maven-plugin directory
 * updated pom.xml manualla
 * committed everything
 
The result is basically the same. Some of the files have just changed so radically when the "beef" of the file has been moved to the plugin base module that git don't consider it a rename anymore but a deletion and addition of two new files. I think there is no sane way to maintain the history better than this case.

If people need the history, they will see this commit and find the old files from there if needed. Or they can use blame in older branches.

So lets now fix the build errors and conflicts and get this in to the master branch

2021-02-18 21:34 UTC, mstahv commented
Eh, sorry, did it to stbischof/flow first, now also to bipolis/flow.

2021-02-19 06:03 UTC, mstahv commented
The last build failure seems to be an issue on the build cluster:

      (No space left on device)

2021-02-19 07:04 UTC, mcollovati commented
> If people need the history, they will see this commit and find the old files from there if needed. Or they can use blame in older branches.

I don't know if it can be of any help or if you already tried it, but in a similar situation rebase option *strategy-option=rename-threshold* helped me to preserve history.

`git rebase --strategy-option=rename-threshold=10 develop`

2021-02-19 07:41 UTC, mstahv requested changes

2021-02-19 07:41 UTC, mstahv commented on flow-plugins/pom.xml
> +		<version>6.0-SNAPSHOT</version>
```suggestion
		<version>7.0-SNAPSHOT</version>
```

2021-02-19 07:42 UTC, mstahv commented
@stbischof Was that latest force push a trial with the suggestion by @mcollovati or just rebase on top of master? In both cases we still need to update the version in the module to 7.0-SNAPSHOT

2021-02-19 07:43 UTC, mstahv requested changes

2021-02-19 07:43 UTC, mstahv commented on flow-plugins/flow-maven-plugin/pom.xml
> +        <version>6.0-SNAPSHOT</version>
```suggestion
        <version>7.0-SNAPSHOT</version>
```

2021-02-19 07:43 UTC, mstahv commented on flow-plugins/flow-plugin-base/pom.xml
> +        <version>6.0-SNAPSHOT</version>
```suggestion
        <version>7.0-SNAPSHOT</version>
```

2021-02-19 07:47 UTC, mstahv commented on flow-plugins/flow-maven-plugin/pom.xml
> +        <artifactId>flow-plugin</artifactId>
```suggestion
        <artifactId>flow-plugins</artifactId>
```

2021-02-19 11:31 UTC, stbischof commented
this force push was to 
- squash (worked)
- rebase on master
- try git rebase --strategy-option=rename-threshold=10 develop (NOT WORKED)

maybe i have the wrong git version(?)

2021-02-22 13:39 UTC, mstahv commented
I don't believe there is anything wrong with the git version you are using. It is just that preserving more history than currently would require extra work that probably never pays off. We have wasted already hours on playing with that, but we should focus on more essential things.

@stbischof Did you try the OSGi bundle code functionality in your own project? We don't have any reason from the official features to keep that part as functional OSGi bundle, so I'm bit afraid it will be working perfectly in the future if there are some bigger changes. If it is ok for you that it might break at some point, I think we could leave it like this. If that is critical, maybe we should add some integration/smoke test that loads the bundle 🤔

2021-02-22 13:51 UTC, mstahv approved these changes

2021-02-22 13:54 UTC, stbischof commented
I would have it as a osgi-bundle for a plugin that uses the bnd-generator-plugin.
I do not think that any one else would use this. And if, he would be able to add a pr. This bnd file is really short. It is mostly to get it an name and allow others to have access to the Exported-Packeges.
If this Plugin is ready maybe i will add it here.

2021-02-22 14:01 UTC, mstahv commented
Yup, I think we'll anyway declare that as "interrnal module", so that we don't tie our hands with all backwards compatibility constraints we have with other APIs. If that's ok for you, I think it is fine to leave out ITs as well.

2021-02-24 06:43 UTC, merged