fix: Generate TS definition for theme-generated.js
vaadin/flow pull request #9753
Opened 2021-01-07 07:19 UTC by tanbt

Fixes #9678

2021-01-07 12:47 UTC, caalador requested changes

2021-01-07 12:47 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
> +                    "import { applyTheme } from '@vaadin/flow-frontend/themes/theme-generated';");
Shouldn't this work as `themes/theme-generated` as `target/flow-frontend` should be in the modules definition making it available to webpack.

2021-01-08 07:21 UTC, tanbt commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
> +                    "import { applyTheme } from '@vaadin/flow-frontend/themes/theme-generated';");
Fixed.

2021-01-08 08:38 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
> +                    "import { applyTheme } from '@vaadin/flow-frontend/themes/theme-generated';");
Forgot to push?

2021-01-08 08:38 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
> +            "import { applyTheme } from '@vaadin/flow-frontend/themes/theme-generated';\n" +
this should then also be updated to expect `themes/theme-generated`

2021-01-08 08:58 UTC, tanbt commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
> +                    "import { applyTheme } from '@vaadin/flow-frontend/themes/theme-generated';");
Then I got it wrong. I thought `import { applyTheme } from '@vaadin/flow-frontend/themes/theme-generated';"` is the fixed.
I've tried `import { applyTheme } from 'themes/theme-generated';` but the module isn't found.

2021-01-08 09:49 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
> +                    "import { applyTheme } from '@vaadin/flow-frontend/themes/theme-generated';");
is it something to do with is being TS as it works fine on for instance embedded that only uses the shortened one.

2021-01-08 09:50 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
> +                    "import { applyTheme } from '@vaadin/flow-frontend/themes/theme-generated';");
I would perhaps also update `WebComponentGenerator` to use the same notation.

2021-01-08 11:13 UTC, tanbt commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
> +                    "import { applyTheme } from '@vaadin/flow-frontend/themes/theme-generated';");
I don't really get your ideas.

> is it something to do with is being TS

Having a TS definition file will allow importing by module name. i.e `@vaadin/flow-frontend/themes/theme-generated` which looks like a proper import in the TS file `vaadin.ts` (?).

>  instance embedded that only uses the shortened one

Has the shortened one `themes/theme-generated` (?) been used somewhere already? Is it correct when it doesn't work when I use `import { applyTheme } from 'themes/theme-generated';` ?

2021-01-08 11:17 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
> +                    "import { applyTheme } from '@vaadin/flow-frontend/themes/theme-generated';");
WebComponentGenerator uses the import as `import {applyTheme} from 'themes/theme-generated.js';` and that works fine, so I don't know why the TS file doesn't find the import on compilation except that it is searching somehow different as it's ts not js.
But we should keep the targets the same so that we don't confuse ourselves on those.

2021-01-08 15:03 UTC, tanbt commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
> +                    "import { applyTheme } from '@vaadin/flow-frontend/themes/theme-generated';");
I don't know where `import {applyTheme} from 'themes/theme-generated.js';` statement will be generated by `WebComponentGenerator`. If it is generated inside `target/some/folder/some-file`, then it can be resolved.

But from client-side, that statement should be resolved by path or `@vaadin/...` module name (?).
Is there any docs or example about `WebComponentGenerator`? Javadocs doesn't clarify its use-cases. There's also no IT test for it.

2021-01-11 05:09 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
> +                    "import { applyTheme } from '@vaadin/flow-frontend/themes/theme-generated';");
`flow-teests/test-embedding/test-embedding-application-theme` contains app theme tests for embedded components and `WebComponentGeneratorTest` contains junit test for generated embedded js

2021-01-11 07:33 UTC, caalador approved these changes

2021-01-11 10:24 UTC, tanbt commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
> +                    "import { applyTheme } from '@vaadin/flow-frontend/themes/theme-generated';");
So so the two-line applyTheme scripts in `WebComponentGenerator` are generated in `target\frontend\themed-component.js`.

I guess JS/TS scripts generated inside `target/....` can resolve `import { applyTheme } from 'themes/theme-generated';`  (because of some magical mechanisms that resolve the import path to `target/frontend` or `target/flow-frontend` folders) but not for scripts inside `frontend/...`. 
Scripts inside `project-root/frontend/...` can only resolve proper [JS Module Import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#syntax).

Did I got it correctly?

That's why the two import statements are different. So, `themed-component.js` works with both:
1.  `themes/theme-generated.js` which is short and magical, IDE can't resolve it (by ctrl + click), only flow-server can.
2.  `@vaadin/flow-frontend/themes/theme-generated` the proper import that can be used everywhere. I would keep this, even it's a bit longer.

2021-01-11 10:31 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
> +                    "import { applyTheme } from '@vaadin/flow-frontend/themes/theme-generated';");
webpack is the one that resolves 1. and that's because a the webpack definition contains `resolve{module{..., 'target/flow-frontend', ...} }`

2021-01-11 10:37 UTC, caalador approved these changes

2021-01-11 12:13 UTC, merged