Bump Node.js version as it's getting EOF
vaadin/flow pull request #9760
Opened 2021-01-07 09:43 UTC by mshabarov

2021-01-07 14:09 UTC, pleku requested changes
The commit message should probably be `chore!` or such as this should be highlighted in release notes

2021-01-07 14:09 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
>      private static final int SUPPORTED_NODE_MINOR_VERSION = 0;
Is 12.0 supported ?

2021-01-07 14:18 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
>      private static final int SUPPORTED_NODE_MINOR_VERSION = 0;
Change to 12.20 as it's a latest minor version. Will double check if 12.20 is indeed supported by flow.

2021-01-07 14:35 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
>      private static final int SUPPORTED_NODE_MINOR_VERSION = 0;
Tested with application theme demo. It works as expected. IT tests should also show if it's supported.

2021-01-07 19:34 UTC, manolo submitted a review, later dismissed

2021-01-07 19:34 UTC, manolo commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +    public static final String INSTALL_NODE_LOCALLY = "%n  $ mvn com.github.eirslett:frontend-maven-plugin:1.10.0:install-node-and-npm -DnodeVersion=\"v14.15.4\" ";
I would use DEFAULT_NODE_VERSION here to avoid maintaining the  value twice in the code

2021-01-07 19:34 UTC, manolo commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
> +        String nodeExecutable = tools.installNode("v14.15.4", null);
Why not use the static DEFAULT_NODE_VERSION  in tests for the installation and assertions, having to change tests every time we bump node is cumbersome and error prone

2021-01-08 07:26 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +    public static final String INSTALL_NODE_LOCALLY = "%n  $ mvn com.github.eirslett:frontend-maven-plugin:1.10.0:install-node-and-npm -DnodeVersion=\"v14.15.4\" ";
Done

2021-01-08 07:26 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
> +        String nodeExecutable = tools.installNode("v14.15.4", null);
Done

2021-01-08 16:38 UTC, pleku requested changes
Up to @manolo to say if we would include this to v19 and what would be the minimum version. I think the previous default version of 12.18.3 could be a good choice, even though it will require some updates to be made.

2021-01-08 16:38 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +    private static final int SUPPORTED_NODE_MINOR_VERSION = 20;
Would there be some reason why we would not support node 12.13 where the LTS starts for node 12 ? 
This change would require a lot of users with Node versions 12.13-12.19 to update.

2021-01-08 16:38 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
>      private static final int SUPPORTED_NPM_MINOR_VERSION = 6;
I think npm versions should be also updated to match the version that comes with the supported node version above, see https://nodejs.org/en/download/releases/

2021-01-08 16:38 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +    private static final int SUPPORTED_NODE_MINOR_VERSION = 20;
Or by minimum we could require the previous default version 12.18.3 but I would not require newer without a good reason

2021-01-11 08:47 UTC, Artur- commented
Why are you mixing two things in the same PR? 
- Bump the default installed Node to latest LTS - non breaking, can and should be merged for V19
- Change the supported Node versions. Breaking change that cannot just be merged based on that "ITs pass"

2021-01-11 10:30 UTC, pleku commented
> Why are you mixing two things in the same PR?

True, bumping the default installed version could be merged immediately and the supported version can stay pending open for a decision on when to do it. Nobody has said anywhere that this (bumping the minimum supported version) would be merged "just because ITs pass".

On the _why_, there was no need to rush into this, but @mshabarov felt eager to get it going forward and opened this PR so here we are.

2021-01-11 13:39 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +    private static final int SUPPORTED_NODE_MINOR_VERSION = 20;
Good point, I didn't take into account the fact 12.20 will require many updates on users side. Not certain about what is better - 12.13 or 12.18. I would go with 12.18 as it newer.

2021-01-11 13:45 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
>      private static final int SUPPORTED_NPM_MINOR_VERSION = 6;
Sure! Thanks!

2021-01-11 13:47 UTC, mshabarov commented
> Why are you mixing two things in the same PR?
> 
> * Bump the default installed Node to latest LTS - non breaking, can and should be merged for V19
> * Change the supported Node versions. Breaking change that cannot just be merged based on that "ITs pass"

Good comment! Will split these changes into two PRs

2021-02-04 07:14 UTC, pleku commented
So I think we won't merge this for 6.0 / v19. I don't know when we're going to update the versions and who decides it, so maybe @mshabarov you should convert this to a draft or just close it but leave the branch in tact.

2021-04-30 11:09 UTC, Artur- commented
Before doing this, we would need an auto installation of Node if the existing one is too old (#9864)

2021-06-07 09:57 UTC, manolo commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +    private static final int SUPPORTED_NODE_MINOR_VERSION = 20;
I think 12.18 is a good choice

2021-06-07 09:58 UTC, manolo commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +    private static final int SUPPORTED_NODE_MINOR_VERSION = 20;
regarding porting this to v19, I think it's not needed since we have v20 already

2021-10-01 07:21 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +    private static final int SUPPORTED_NODE_MINOR_VERSION = 18;
```suggestion
    private static final int SUPPORTED_NODE_MINOR_VERSION = 22;
```

2021-10-01 07:26 UTC, mshabarov commented
#9864 is not done and merged, so we can revisit this Node version upgrade again.

2021-10-01 07:28 UTC, mshabarov commented
I've changed the title to not be a breaking change.

2021-10-04 05:56 UTC, pleku approved these changes

2021-10-04 11:02 UTC, mshabarov commented
@manolo could you please review this PR.

2021-10-04 14:14 UTC, manolo approved these changes
LGTM

2021-10-04 19:15 UTC, merged