test: Fix random failures of ThemeLiveReloadIT
vaadin/flow pull request #9764
Opened 2021-01-07 13:56 UTC by mshabarov

Fixes: https://github.com/vaadin/flow/issues/9746

2021-01-07 14:55 UTC, joheriks commented
Merge commit 87afca55f5e26cb2d950cf6c45ddc1cc48ef3411, which fixes the two failing `AppThemeTestIT` tests.

2021-01-13 15:16 UTC, mshabarov commented
For some reason `require('mkdirp')(staticAssetsThemeFolder);` has started to fail when used by copying the theme static resources.
Replaced with `fs.mkdirSync(staticAssetsThemeFolder, {recursive: true});`
Maybe related to a Node.js default version upgrade.

2021-01-15 06:09 UTC, caalador reviewed
Seems fine, runnable would make it cleaner.
If you take the change use the add suggestion to batch.

2021-01-15 06:09 UTC, caalador commented on flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
> +import java.util.function.Consumer;
```suggestion
```

2021-01-15 08:34 UTC, mshabarov commented
Thanks a lot, @caalador ! Yep, it's much more cleaner now with `Runnable`.

2021-01-15 08:37 UTC, caalador requested changes

2021-01-15 08:37 UTC, caalador commented on flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
> +        deleteFile(stylesCSSFile));
Minor nit. Formatting is off and this should be indented like on line 100 same for line 84-85 (or the other way around)

2021-01-15 08:45 UTC, mshabarov commented on flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
> +        deleteFile(stylesCSSFile));
Yep, fixed. Well, now these two lines are fit into one line.

2021-01-15 09:01 UTC, caalador approved these changes

2021-01-15 09:55 UTC, merged