Refactor startup initializers to use VaadinContext
vaadin/flow pull request #9777
Opened 2021-01-08 15:57 UTC by jhult

This is the successor to [this pull request](https://github.com/vaadin/flow/pull/8469) (which ran long and had too many updates).

Most Vaadin startup initializers don't actually need `ServletContext`. Thus, their methods should use VaaddinContext instead. This pull request attempts to fix. This allows non-servlet implementing HTTP frameworks (such as [VertxVaadin](https://github.com/mcollovati/vertx-vaadin)) to directly call the main initialization logic via `VaadinContextStartupInitializer#initialize(Set, VaadinConntext)}` instead of needing to create fake `ServletContext`s.

I also standardized parameter names of overriden methods and also deprecated (where it made sense) public methods that used `ServletContext` in favor of a new method which uses `VaadinContext`.

I believe this fixes #5735 and also fixes #2775. In addition, this provides a good step towards allowing external libraries to reduce the dependency on servlet-api (#4613).

2021-01-11 08:48 UTC, denis-anisimov commented
>This allows non-servlet implementing HTTP frameworks 

This is the main question which I would like to get the answer to.
I'm not familiar with ` VertxVaadin` .
Could you please describe shortly how and when VaadinContextStartupInitializer are (going to be ?) called.

My original question about initial PR was exactly about the need of this refactoring: `ServletContainerInitializer`  in this PR is used _as is_.
And Servlet 3.0 specification calls `ServletContainerInitializer` directly .
So when Vaadin app works inside a Servlet container the `VaadinContextStartupInitializer` abstraction is not used anyhow.
So I would like to understand the usecase for `VaadinContextStartupInitializer` .
In which way `VaadinContextStartupInitializer`s are supposed to be called : how they will be collected from the application and who will trigger their execution?

2021-01-11 15:58 UTC, jhult commented
@denis-anisimov 

External, non-servlet frameworks (such as VertxVaadin) should be able to manually call these classes:

`AnnotationValidator`
`DevModeInitializer`
`ErrorNavigationTargetInitializer`
`RouteRegistryInitializer`
`VaadinAppShellInitializer`
`WebComponentConfigurationRegistryInitializer`
`WebComponentExporterAwareValidator`

It is up to the external, non-servlet framework to manually find the above classes. One method would be to search for any class (not interface) which implements `VaadinContextStartupInitializer`. Then the `initialize` method could be called to do all the necessary startup logic.

The external, non-servlet framework would also need to manually locate the required `Set` of classes which the initializer needs.

However, right now (in the `master` branch), if an external, non-servlet framework tries to call `RouteRegistryInitializer`, it has to use this method `onStartup(Set<Class<?>> classSet, ServletContext servletContext)`. That is troublesome for frameworks which don't have/need a `ServletContext`.

[Here](https://github.com/mcollovati/vertx-vaadin/blob/78bcdd4f26feb0d131b04ead355b08198d18ad18/vertx-vaadin-flow-parent/vertx-vaadin-flow/src/main/java/com/github/mcollovati/vertx/vaadin/VaadinVerticle.java#L305) is how VertxVaadin does it. VertxVaadin has to create a fake `ServletContext` when in reality `ServletContext` is unnecessary unnecessary for the above classes.

The external, non-servlet framework would need to implement `VaadinContext` (e.g. `MyFrameworkCustomVaadinContext`). Implementing the required code for `VaadinContext` is much simpler than doing so for `ServletContext`. Then, with this PR, external, non-servlet frameworks could call this:
```
MyFrameworkCustomVaadinContext context = new MyFrameworkCustomVaadinContext();
RouteRegistryInitializer routeRegistryInitializer = new RouteRegistryInitializer();
routeRegistryInitializer.initialize(classSet, context);
```

2021-01-13 06:02 UTC, denis-anisimov commented
OK, thank you. Now it starts to look reasonable.

2021-01-13 06:46 UTC, denis-anisimov requested changes

2021-01-13 06:46 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/DeferredServletContextInitializers.java
> +import com.vaadin.flow.di.LookupInitializer;
This is the only change in this class.
Is it necessary.
I think it's just extra.

2021-01-13 06:46 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
> +    private static final class DEV_MODE_HANDLER_ALREADY_STARTED_ATTRIBUTE implements Serializable { }
The name of the class should not be in upper case.
It should be in camel case.
The constant (an object of the type) should be upper case.

2021-01-13 06:46 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinContextStartupInitializer.java
> + * A functional interface which performs the required startup logic for a
`A functional interface` doesn't add anything to the javadocs.
Java type allows to see that this is an interface and it's functional. 
This sentence start just repeats the fact which is forced by Java.

We cleaned up (I hope everywhere) such extra words in javadocs. Could you please reformulate the sentence so that it doesn't contain extra words?

2021-01-13 06:46 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinContextStartupInitializer.java
> + * Vaadin initializer (those classes implemented by
What's the Vaadin initializer ?

2021-01-13 06:46 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinContextStartupInitializer.java
> + * {@link VaadinServletContextStartupInitializer}).
`VaadinServletContextStartupInitializer` should not be mentioned here in that way I think.
Because it's just a subinterface and the whole point of this PR to get rid of Servlet dependency.

It can be mentioned but only as a possible subinterface/example.

2021-01-13 06:46 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinContextStartupInitializer.java
> + * This functional interface is intended to be called either:
`functional interface` is extra.

s/`This functional interface is intended`/`It is intended`/

2021-01-13 06:46 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinContextStartupInitializer.java
> + *
A couple of `@see`  tags could be added here: to 
- `ClassLoaderAwareServletContainerInitializer` (or `ServletContainerInitializer` instead or in addition to)
- `VaadinServletContextStartupInitializer`.

2021-01-13 06:46 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinContextStartupInitializer.java
> +     * Performs the required startup logic for this initializer
I would may be use something like `applies this initializer to the given context`.
The current sentence doesn't say anything at all to me.
The suggested sentence is not that meaningful as well but at least it doesn't contain "startup logic" (because it's confusing: which start up logic ?)

2021-01-13 06:46 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinContextStartupInitializer.java
> +     * @param classSet
This javadoc should be completely rewritten somehow.
That's the main challenge when you make an abstraction layer.
Since `VaadinContextStartupInitializer` doesn't know anything (and not based anymore) about `ServletContainerInitializer`  then it may not mention `HandlesTypes`. The latter annotation is an implementation detail of `ServletContainerInitializer`  and it's a servlet based.
So this mention should be removed completely.
The set of classes explanation should be rewritten as well: you are referring here to the implementation/realization detail of the  `ServletContainerInitializer` .
It should be just a set of classes which initializer needs to do its job.
There should not be any mention about specifics of this classes : extend, implement, etc...

2021-01-13 06:46 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinInitializerException.java
> + * Exception indicating an issue during Vaadin initialization.
`Exception` is an extra word which repeats the Java declaration

2021-01-13 06:46 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinServletContextStartupInitializer.java
> + * Interface which allows a library/runtime to be notified of a web
`Interface` is an extra word.

2021-01-13 06:46 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinServletContextStartupInitializer.java
> + * <li>{@link AnnotationValidator}</li>
I would avoid mentioning all the implemented classes here.
This list has to be updated on every change in such classes :if some new class is added that will require change this list.
It's quite easy to find the list via introspecting hierarchy.

2021-01-13 06:46 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinServletContextStartupInitializer.java
> + * @see ClassLoaderAwareServletContainerInitializer
This is the only interface which I would keep here.

2021-01-13 06:46 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinServletContextStartupInitializer.java
> +     * By default, this simply delegates to {@link #initialize(Set, VaadinContext)}
Are you sure that this javadoc is needed ?

Several issues here:
- you have completely overridden the javdocs from the original `process`
- the original javadocs are not mentioned here anyhow (via `inheritdoc`)
- the delegation note is extremely easy to see from the implementation since the impl is quite easy.
- it's quite obvious that any initializer may override this method and it's up to the initializer to do it: superclass should not mentioned subclass specifics.

2021-01-13 06:46 UTC, denis-anisimov commented on flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
> +                "com\\.vaadin\\.flow\\.server\\.startup\\.VaadinServletContextStartupInitializer",
I have doubts for this change: our `ServletContainerInitiaizer`s  were `Serializable`.
Should the new abstraction layer also be `Serializable` ?

I'm not sure in fact because quite many implementations of `ServletContainerInitiaizer` weren't `Serializable` in fact.....

2021-01-13 13:11 UTC, jhult commented on flow-server/src/main/java/com/vaadin/flow/server/startup/DeferredServletContextInitializers.java
> +import com.vaadin.flow.di.LookupInitializer;
This import was added by my IDE because `LookupInitializer` is mentioned in the Javadoc. `VaadinContext` is also imported strictly for a Javadoc (not used anywhere in the class). I can either leave the import or make both fully qualified in the Javadoc. Which would you prefer?

2021-01-13 13:20 UTC, jhult commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinServletContextStartupInitializer.java
> + * Interface which allows a library/runtime to be notified of a web
I will remove this. However, I did pattern it off [ServletContainerInitializer]( https://github.com/eclipse-ee4j/servlet-api/blob/master/api/src/main/java/jakarta/servlet/ServletContainerInitializer.java#L23) which starts the Javadoc with `Interface`.

2021-01-13 13:21 UTC, jhult commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinServletContextStartupInitializer.java
> + * <li>{@link AnnotationValidator}</li>
This has been removed.

2021-01-13 13:21 UTC, jhult commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinServletContextStartupInitializer.java
> + * @see ClassLoaderAwareServletContainerInitializer
The others have been removed.

2021-01-13 13:21 UTC, jhult commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinServletContextStartupInitializer.java
> +     * By default, this simply delegates to {@link #initialize(Set, VaadinContext)}
I removed this Javadoc.

2021-01-13 13:21 UTC, jhult commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinInitializerException.java
> + * Exception indicating an issue during Vaadin initialization.
Fixed.

2021-01-13 13:27 UTC, jhult commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinContextStartupInitializer.java
> + * A functional interface which performs the required startup logic for a
Removed `A functional interface which`.

2021-01-13 13:28 UTC, jhult commented on flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
> +    private static final class DEV_MODE_HANDLER_ALREADY_STARTED_ATTRIBUTE implements Serializable { }
Fixed.

2021-01-13 13:28 UTC, jhult commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinContextStartupInitializer.java
> + * This functional interface is intended to be called either:
Updated.

2021-01-13 13:29 UTC, jhult commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinContextStartupInitializer.java
> + *
I added these:

- `ClassLoaderAwareServletContainerInitializer`
- `VaadinServletContextStartupInitializer`

2021-01-13 13:47 UTC, jhult commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinContextStartupInitializer.java
> +     * @param classSet
I will rework this.

FYI, the verbiage of `classes that extend, implement, or have been annotated` is patterned off [ServletContainerInitializer](https://github.com/eclipse-ee4j/servlet-api/blob/master/api/src/main/java/jakarta/servlet/ServletContainerInitializer.java#L68).

2021-01-13 17:14 UTC, jhult commented on flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
> +                "com\\.vaadin\\.flow\\.server\\.startup\\.VaadinServletContextStartupInitializer",
I'm not sure whether this should be `Serializable` or not. If I don't include it, this error is thrown for the test:

```
[INFO] Running com.vaadin.tests.server.component.FlowClassesSerializableTest
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.017 s <<< FAILURE! - in com.vaadin.tests.server.component.FlowClassesSerializableTest
[ERROR] classesSerializable(com.vaadin.tests.server.component.FlowClassesSerializableTest)  Time elapsed: 0.735 s  <<< FAILURE!
java.lang.AssertionError: 
Serializable not implemented by the following classes and interfaces: ,
com.vaadin.flow.server.startup.VaadinContextStartupInitializer,
com.vaadin.flow.server.startup.VaadinServletContextStartupInitializer
	at org.junit.Assert.fail(Assert.java:89)
	at com.vaadin.flow.testutil.ClassesSerializableTest.failSerializableClasses(ClassesSerializableTest.java:433)
	at com.vaadin.flow.testutil.ClassesSerializableTest.classesSerializable(ClassesSerializableTest.java:337)
```

2021-01-13 18:37 UTC, jhult commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinContextStartupInitializer.java
> + * {@link VaadinServletContextStartupInitializer}).
Removed the mention of `VaadinServletContextStartupInitializer`.

2021-01-13 18:39 UTC, jhult commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinContextStartupInitializer.java
> + * Vaadin initializer (those classes implemented by
Updated Javadoc to remove reference to "Vaadin initializer".

2021-01-13 18:40 UTC, jhult commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinContextStartupInitializer.java
> +     * Performs the required startup logic for this initializer
Updated Javadoc.

2021-01-14 06:31 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/DeferredServletContextInitializers.java
> +import com.vaadin.flow.di.LookupInitializer;
OK, no problems.
The only thing which is weird: there are no other changes. It means that javadocs were broken before this change.

2021-01-14 06:44 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinContextStartupInitializer.java
> +     * @param classSet
>FYI, the verbiage of classes that extend, implement, or have been annotated is patterned off

It's totally fine for `ServletContainerInitializer`  to use the words and everything because this is how it works: it's part of Servlet 3.0 specification.

`VaadinContextStartupInitializer` is an abstraction layer and it's not specified by anyone what classes are passed to the method.
`HandlesTypes` is not used anymore in this abstraction layer (or do you still expect that it's used ?) and as a consequence its semantic with `classes that extend, implement, or have been annotated` can't be used here.
You may write whatever you want/require here but this should be something which anyone may understand.
It's not clear anymore where those classes comes from now (strongly related to  my point with the whole refactoring) and what's their meaning.

If you still want to rely the `VaadinContextStartupInitializer` implementation on `HandlesTypes` then please describe it properly here and then you may use `classes that extend, implement, or have been annotated`.

But the question : is `HandlesTypes` still applicable for `VaadinContextStartupInitializer`  ? ( I think no, but it's not my spedcification ).

2021-01-14 06:56 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinContextStartupInitializer.java
> +     * @param classSet
I'm kind of fine with the current javadocs.
So this can be kept as is.
If you think you may improve it then please go ahead.

The javadocs in fact are quite confusing since they don't define the exact contract: any class may be passed to the `VaadinContextStartupInitializer`  in the set. 
As I mentioned already `ServletContainerInitializer` works with `HandlesTypes` : so the Servlet container passes the classes based on `HandlesTypes`  annotation.
It's completely unclear  which classes are passed to `VaadinContextStartupInitializer` : as I mentioned `HandlesTypes` is not anymore related to this abstraction (and in fact it can't be related since this class in a servlet specific).
So in fact the NON Servlet container has to define the semantic based on every `VaadinContextStartupInitializer` implementation instead of defining the clear contract for the abstraction layer (this is exactly done in Vertx : every initializer impl class is used directly and classes are passed to it per its nature).

Technically you should invent something like  `HandlesTypes`  for `VaadinContextStartupInitializer` here and this is strongly connected to the my initial question about this refactoring.

2021-01-14 07:32 UTC, denis-anisimov commented on flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
> +                "com\\.vaadin\\.flow\\.server\\.startup\\.VaadinServletContextStartupInitializer",
The test fails because the interfaces don't extend `Serializable`.
To avoid the test failure you should either make the classes `Serializable`  or add them to the exclusion list.
The latter is not always the correct solution.

But it's up to the every implementation class to decide whether it should be `Serializable` or not : `ServletContainerInitializer` doesn't extend `Serializable`  so no need to require that from `VaadinContextStartupInitializer`.

2021-01-14 07:36 UTC, denis-anisimov approved these changes

2021-01-14 07:36 UTC, merged

2021-01-14 15:29 UTC, jhult commented on flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinContextStartupInitializer.java
> +     * @param classSet
I'm fine with the current Javadocs.

To answer your question, for [VertxVaadin](https://github.com/mcollovati/vertx-vaadin), `HandlesTypes` is still used as a means to find the necessary classes (since most classes come from core Vaadin which uses `HandlesTypes` or addons which also use `HandlesTypes`.

2021-01-14 15:33 UTC, jhult commented
Thanks @denis-anisimov for all your comments and effort reviewing. I'm glad we were able to get this merged.