test: Use portable line separators in TaskGeneratedBootstrapTest
vaadin/flow pull request #9790
Opened 2021-01-11 16:29 UTC by mshabarov

Fixes: https://github.com/vaadin/flow/issues/9773

2021-01-12 12:43 UTC, caalador requested changes

2021-01-12 12:43 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
> +                "import '../../target/index';" + System.lineSeparator()));
In this test the line separator is not all that important. It would be enough to check that it has the code.

2021-01-12 12:43 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
> +                System.lineSeparator()));
This is not the same as it was except more complicated to read.
```
By using %n in your format string, you tell Java to use the value returned by System. getProperty("line. separator")
```

2021-01-12 12:43 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
> +                .contains("import '../index';" + System.lineSeparator()));
Also here the line separator is extra.

2021-01-12 12:43 UTC, caalador commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
> +        //@formatter:on
This could also be update to check just that the expected lines exist see `TsFormTest::should_generate_FormModels` for inspiration.
This will also help in figuring out what is wrong instead of just getting a expected true was false.
Also we don't need to care about lineSeparators.

2021-01-12 14:49 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
> +                "import '../../target/index';" + System.lineSeparator()));
Yep, not needed.

2021-01-12 14:50 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
> +                System.lineSeparator()));
Right! Reverted

2021-01-12 14:50 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
> +                .contains("import '../index';" + System.lineSeparator()));
Removed

2021-01-12 14:53 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
> +        //@formatter:on
Right! Replaced by the expected lines check.
I was thinking about extracting the file content check code from `should_generate_FormModels` to a common place, but haven't found an appropriate way for it.

2021-01-13 04:58 UTC, caalador approved these changes

2021-01-13 04:59 UTC, merged