refactor: Move theme-generated.js to frontend/generated
vaadin/flow pull request #9820
Opened 2021-01-15 12:14 UTC by mshabarov

Renames `theme-generated.js` to `theme.js` and moves it to `frontend/generated` folder.

Fixes: https://github.com/vaadin/flow/issues/9687

2021-01-18 07:48 UTC, caalador requested changes

2021-01-18 07:48 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +                new File(frontendDirectory, FrontendUtils.GENERATED),
These should probably target `generatedTsFolder` (or `connect.generated` property) to be in the correct folder.

Asking fusion team about why it's there but only used for one instance.

2021-01-18 07:48 UTC, caalador commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
> +function extractThemeName(frontendFolder) {
This should be `generatedTsFolder` that is actually definable so we shouldn't make expectations and only check the given folder for `theme.js`
```
    /**
     * The folder where flow will put TS API files for client projects.
     */
    @Parameter(defaultValue = "${project.basedir}/" + FRONTEND + "/generated")
    protected File generatedTsFolder;
```

2021-01-18 07:48 UTC, caalador commented on flow-server/src/main/resources/webpack.generated.js
> +  projectFrontendFolder: frontendFolder
This should be the generated folder and probably should be the configurable target folder.

2021-01-18 07:48 UTC, caalador commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> + *  files are placed
Should be only the generated folder.

2021-01-18 10:51 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +                new File(frontendDirectory, FrontendUtils.GENERATED),
Yeah, It does make sense. And then, `connectTsFolder` property should be available always (not only if TS endpoints are available).

2021-01-18 14:00 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
> +                new File(frontendDirectory, FrontendUtils.GENERATED),
Done. 
`connect.generated` is now used as a target folder for `theme.js`.
`connect.generated` is proposed to be renamed `frontend.generated` as it used not only for connect.
Will create a separate PR for it.

2021-01-18 14:03 UTC, mshabarov commented on flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
> +function extractThemeName(frontendFolder) {
Done. Definable generated path is used.

2021-01-18 14:03 UTC, mshabarov commented on flow-server/src/main/resources/webpack.generated.js
> +  projectFrontendFolder: frontendFolder
Done. Definable generated path is used.

2021-01-18 14:03 UTC, mshabarov commented on flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
> + *  files are placed
Done. Definable generated path is used.

2021-01-19 06:52 UTC, caalador submitted a review, later dismissed
This will be a breaking change until #9832 is fixed as the theme is not removed with `mvn clean` and might break the project unexpectedly when the file is left, but the theme is removed.

2021-01-19 07:34 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +                frontendDependencies.getThemeDefinition(), // NOSONAR
This is actually valid that it might not be initialized. I have made a note into the parking lot about this issue with NodeTasks

2021-01-19 07:36 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +                frontendDependencies.getThemeDefinition(), // NOSONAR
Why? if `builder.enableImportsUpdate` is `true` then the `frontendDependencies ` is being initialised via `new FrontendDependenciesScanner.FrontendDependenciesScannerFactory().createScanner`

2021-01-19 07:43 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +                frontendDependencies.getThemeDefinition(), // NOSONAR
Beacuse you can (well should be able) to run without webpackTemplate and then if you don't have packages or imports enabled then you will npe.

2021-01-19 08:23 UTC, caalador approved these changes

2021-01-19 08:24 UTC, merged

2021-01-19 08:32 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
> +                frontendDependencies.getThemeDefinition(), // NOSONAR
Yeah, if `builder.enablePackagesUpdate || builder.enableImportsUpdate || enableWebpackConfigUpdate` is false meaning that no webpack template, no packages and no import then `frontendDependencies` will be `null` ofc.

But for this particular case the sonar complains we have `if (builder.enableImportsUpdate) {...}`, so the code execution should have gone inside `builder.enablePackagesUpdate || builder.enableImportsUpdate || enableWebpackConfigUpdate` block => initialise `frontendDependencies`.

For other cases/code blocks where nothing among those three flags are checked, there are already a NPE checks inside methods/tasks, like this `protected boolean shouldGenerate() { return frontDeps != null; }`.

So, okay let's look into it more deeply in another ticket.