fix: Also load default JAR resources for DevModeInitializer
vaadin/flow pull request #9823
Opened 2021-01-16 22:44 UTC by tanbt

Fixes https://github.com/vaadin/flow/issues/9802

2021-01-16 22:50 UTC, tanbt commented on flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
> +import com.vaadin.flow.server.VaadinServletContext;
I think my IntelliJ reordering import works correctly in this case.

2021-01-16 22:50 UTC, tanbt commented on flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
> +            Constants.RESOURCES_JAR_DEFAULT));
It could be more specific to load `META-INF/resources/themes` instead of just `META-INF/resources/`.

But `META-INF/resources/` works just fine and could help covering more cases in the future.

2021-01-19 07:04 UTC, caalador requested changes

2021-01-19 07:04 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
> +            Constants.RESOURCES_JAR_DEFAULT));
I would target themes as the compatibility resources is actually at `META-INF/resources/frontend` so now they overlap and we would want to do as little as possible.

2021-01-19 11:57 UTC, tanbt commented on flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
> +            Constants.RESOURCES_JAR_DEFAULT));
Fixed.

2021-01-19 12:36 UTC, caalador reviewed
What do the new tests with loadingJars_allFilesExist actually test?
I couldn't figure it out by looking at the full test class.

2021-01-19 18:00 UTC, tanbt commented
Fixed.

2021-01-20 06:49 UTC, caalador approved these changes

2021-01-20 10:06 UTC, merged