feat: improve HasSize
vaadin/flow pull request #9824
Opened 2021-01-17 22:12 UTC by knoobie

Improves the addition to `HasSize` for `Unit`. 

* adds `getWidthUnit` and `getHeightUnit` for better discoverability
  * Open Questions:
    * Optional<Unit> vs. null vs. Unit.PIXELS as default?
    *  Adding those APIs for Min/Max as well? This would increase the amount of methods quite a lot with less gain
* improve performance of `Unit`
  * change streaming to simple for-each 
  * change ordering of enum values, most used (% > px > others) 
  * Open Questions:
    * Should I replace the streaming API in `getSize` as well?

2021-01-26 16:33 UTC, knoobie commented on flow-server/src/test/java/com/vaadin/flow/component/HasSizeTest.java
> +        Assert.assertEquals(Unit.PERCENTAGE, component.getHeightUnit().get());
Same for both comments: I can understand your concern and I would never do this in production code. I only used it in tests to make the test short and readable. Depending on the question above, this has to be changed anyway. Gonna wait for that before I tackle this.

2021-01-26 16:37 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/component/Unit.java
> +        if (cssSize == null || cssSize.isEmpty()) {
`trim` is rarely used within the whole code base - I can easily add it, if that's something to improve the code and serve a purpose, but I can't really see a use case where this method is called with a blank string or possibility.

2021-01-26 16:42 UTC, knoobie commented on flow-server/src/test/java/com/vaadin/flow/component/UnitTest.java
> + * Copyright 2000-2020 Vaadin Ltd.
Thanks for the header! I copied another test class in the package.. and got the only one without a copyright header. Damn it :)  

See: https://github.com/vaadin/flow/blob/master/flow-server/src/test/java/com/vaadin/flow/component/HasThemeTest.java

2021-01-26 16:46 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/component/UnitTest.java
> + * Copyright 2000-2020 Vaadin Ltd.
Thanks for the note about the missing license header in that Test class. I'll fix it.

2021-01-26 16:56 UTC, taefi commented
Hi and thanks for the contribution. 

My opinion about some of the questions:

> Optional vs. null vs. Unit.PIXELS as default?
- I would avoid `Unit.PIXELS` as default since IMO it creates more confusion. Between, `null` and `Optional.empty` I vote for the current implementation. 

> Adding those APIs for Min/Max as well? This would increase the amount of methods quite a lot with less gain
- To be honest, the already added APIs fills like double edge sword! It feels right to get `Unit` of the `size` from the same API that we can get the size itself. One the other hand, these methods are also seems like on-liner utility methods that we can define a lot of them. Since this is a base interface, we need to be cautious about adding so many methods to it.

2021-01-26 17:30 UTC, knoobie commented
@taefi Thanks for your opinion! 

> I would avoid Unit.PIXELS...

The idea was based on the default implementation of V8 where PIXELS was the default instead of null. Personally I'm not a huge fan of Optional (until java 9) but I used it because it's often used in flow for optional values. 

> To be honest, the already added APIs fills like double edge sword...

The whole addition was based on the comment of Ben in https://github.com/vaadin/flow/pull/8533#issuecomment-755279268 - meaning having a "official" API inside the interface is easier to find for the developer and probably working ;) 

Additionally, the HasSize interface is probably going to be cleaned up in the future once #5854 is done.

2021-01-27 08:19 UTC, taefi commented on flow-server/src/main/java/com/vaadin/flow/component/Unit.java
> +        if (cssSize == null || cssSize.isEmpty()) {
Fair point!

2021-02-17 07:52 UTC, pleku requested changes
Sorry that it has taken a while. Only two clarifications for the javadocs would be required

2021-02-17 07:52 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/component/HasSize.java
> +     * Gets the height unit defined for the component.
Or what ? This javadoc doesn't tell me when the optional might be empty

2021-02-17 07:52 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/component/HasSize.java
> +     * Gets the width unit defined for the component.
Or what ? This javadoc doesn't tell me when the optional might be empty

2021-02-17 08:07 UTC, knoobie commented on flow-server/src/main/java/com/vaadin/flow/component/HasSize.java
> +     * Gets the height unit defined for the component.
Updated both javadocs based on other `Optional<?>` methods like `Element::getShadowRoot`

2021-02-17 08:16 UTC, pleku submitted a review, later dismissed

2021-02-17 08:33 UTC, taefi approved these changes

2021-02-17 09:19 UTC, pleku commented
Sigh, test failure should not be related in any way, restarted the build.

2021-02-17 09:22 UTC, knoobie commented
@pleku  I'm not sure about the target/2.5 and target/2.6 label because the original PR for this isn't backported or? (https://github.com/vaadin/flow/pull/9824)

2021-02-17 11:44 UTC, pleku commented
> @pleku I'm not sure about the target/2.5 and target/2.6 label because the original PR for this isn't backported or? (#8533)

It is now as the manual cherry-pick PRs will be merged before this, then the bot will backport this too.

But @knoobie can you please rebase this on top of the `master` as it now failed for the silly Chrome version test.

2021-02-17 12:11 UTC, knoobie commented
@pleku thanks! Rebased and waiting for the build process to do it's job :)

2021-02-18 07:55 UTC, fluorumlabs commented
Unit `ch` is missing from the unit list. While rarely used, I believe it's more popular than, let's say, centimeters :)

2021-02-18 08:02 UTC, knoobie commented
@fluorumlabs Thanks! Found a reason to trigger a build restart :)

2021-02-18 08:31 UTC, pleku approved these changes

2021-02-18 08:32 UTC, pleku approved these changes

2021-02-18 14:24 UTC, merged