Inject Lumo CSS into shadow roots
vaadin/flow pull request #9842
Opened 2021-01-19 12:47 UTC by Artur-

Fixes #9767

2021-01-21 11:03 UTC, caalador requested changes
I noted that in the package.json you forced polymer to 3.4.1, but as things should work out of the box by building the project I made the fix #9859 
I guess the issue comes from vaadin-text-field that has the dependencies
    "@polymer/iron-component-page": "^4.0.0",
    "@polymer/iron-form": "^3.0.0",
    "@polymer/iron-test-helpers": "^3.0.0",
That bring in polymer 3.4.1.
On the other hand if there is no issues then we should probably update our polymer version to the latest.

package.json files should be removed

2021-01-21 11:03 UTC, caalador commented on flow-tests/test-application-theme/test-theme-reusable/src/main/java/com/vaadin/flow/uitest/ui/theme/TSView.java
> +}
Missing new line.

2021-01-21 14:14 UTC, Artur- commented
Rebased on top of #9859 and removed package.json files

2021-01-22 11:59 UTC, caalador commented
Looks good, I'll fix it in with the package fix asap.

2021-01-22 14:44 UTC, Artur- commented
Rebased on master

2021-01-22 15:11 UTC, caalador approved these changes

2021-01-22 16:01 UTC, merged