feat:support current pnpm versions
vaadin/flow pull request #9848
Opened 2021-01-20 08:49 UTC by joheriks

Remove pnpm-lock.yaml when package.json dependencies 
are updated to work around pnpm/pnpm#2587 (previously
handled by forcing pnpm 4.5.0).

Fixes #9719

2021-01-25 11:07 UTC, haijian-vaadin submitted a review, later dismissed
The change looks good to me. 
I also tried to verify with the pr snapshot build, it works great!
Would be good to have some input from Flowers.

2021-01-26 08:15 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +        assert "npm".equals(toolName) || "npx".equals(toolName);
As tool name can/should only be npm or npx could we just have an `enum Tool` from where we take the accepted tool. Then we wouldn't typo it in mistake either.

In any case the assert should have a message on what was wrong.

2021-01-26 09:28 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +        assert "npm".equals(toolName) || "npx".equals(toolName);
Done.

2021-01-26 10:39 UTC, pleku requested changes
Comments ready and testing next with windows and an svc project.

Let me know if you want to discuss comment directly via voice/slack to speedup things

2021-01-26 10:39 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +                    "unable to locate pnpm of supported version");
I don't think this comment is in any way helpful if I have installed a pnpm version that used to work in my project folder - _what should I do (ignore version or install new) and what version should I use_ ?

2021-01-26 10:39 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +                    "pnpm@" + DEFAULT_PNPM_VERSION);
Why ? How does passing a default version to the _version check_ make a difference here ?
I've understood that this code is executed in case an old version was detected or no version was detected, but I can't figure out how this makes a difference, please elaborate (preferably in code)

2021-01-26 10:39 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +    private boolean checkPnpmVersion(List<String> pnpmCommand) {
The method name could be clearer as my first thought was - _check pnpm version is what_? The return value has the answer `versionNewEnough`.

2021-01-26 10:39 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +                        .warn("pnpm at '{}' is version {} which is not supported (expected >={})",
I'm not sure if this warning is needed in case there is another check with the _default version_ and then everything will be OK ?

2021-01-26 10:39 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +            getLogger().warn("error checking pnpm version", e);
Not sure if we could give more details to the user on what to do next if running into this.

2021-01-26 10:39 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +                    deletePnpmLockFile();
According to https://github.com/pnpm/benchmarks-of-javascript-package-managers#lots-of-files there is a significant difference in the benchmarks when the lockfile is still present. I presume that being able to use a newer pnpm version however makes things faster ?
Are there any other alternative ideas on what to do instead of deleting the lockfile or an issue open describing further improvements for this ? Or will 9719 be updated and kept open ?

2021-01-26 10:39 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
> +        Assert.assertEquals("expected pnpm version 4.5.0 rejected",
So the previously installed default version will start failing starting from this version ?
Yet there is no mention of this in the linked issue or PR. Probably should be highlighted somehow.

My expectation would be that 
- if pnpm was installed by Vaadin, it would just update it for me
- if I have installed pnpm myself, things would fail and tell me to update to a new version or let Vaadin install it (and how to)

2021-01-26 10:47 UTC, mshabarov requested changes

2021-01-26 10:47 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +                    "unable to locate pnpm of supported version");
Can we suggest any actions the dev should do to fix that, when he see this message? Delete the too old version from node_modules, for instance. Or maybe restart the application. 
Also would be good to explicitly mention the supported version here in the message.

2021-01-26 10:47 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +            // Otherwise look for regular `npm`/`npx`
So what will be returned in this case? 
I expect `getNpmCliToolExecutable` return `npm-cli` always, but this block of code looks for `npm` and return it.
I'm sure this does work, but could you briefly explain how? :)

2021-01-26 10:56 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
> +        tools = new FrontendTools(baseDir, () -> vaadinHomeDir, "v14.15.4",
Use DEFAULT_NODE_VERSION constant instead.

2021-01-26 12:08 UTC, pleku commented
When running a locally built version of this with a v19 SVC project, I get the following logs:
- no `target`, `pnpm-lock` & `package.json` & `node_modules`
- old pnpm 4.5.0 installation in `/.vaadin`
- windows 10
```
...
2021-01-26 13:59:18.079  INFO 10480 --- [         task-1] c.v.f.s.frontend.TaskUpdatePackages      : writing file C:\Users\Pekka\workspaces\flow2\svc-test\package.json.
2021-01-26 13:59:18.088  INFO 10480 --- [         task-1] c.v.f.s.frontend.TaskUpdatePackages      : Running `pnpm install` to resolve and optionally download frontend dependencies. This may take a moment, please stand by...
2021-01-26 13:59:18.097  INFO 10480 --- [         task-1] c.v.f.s.frontend.TaskUpdatePackages      : Generated pnpmfile hook file: 'C:\Users\Pekka\workspaces\flow2\svc-test\pnpmfile.js'
2
...
2021-01-26 13:59:28.900  INFO 10480 --- [         task-1] c.v.flow.server.frontend.FrontendTools   : using 'C:\Users\Pekka\.vaadin\node\node.exe C:\Users\Pekka\.vaadin\node\node_modules\npm\bin\npx-cli.js --yes --quiet pnpm' for frontend package installation
2021-01-26 14:00:25.862  INFO 10480 --- [  restartedMain] c.e.a.data.generator.DataGenerator       : Generated demo data
```
This seems a bit off to me - the first doesn't seem to do anything (?) and the latter is not descriptive as it takes quite long.

2021-01-26 12:27 UTC, mshabarov commented
Tested on `Mac` with a fresh `Java+Html` project downloaded from SVC.
`pnpm` version already installed in `~/.vaadin` is `4.5.0`.

I changed `chokidar: "^3.5.0"` to `3.5.1` in `package.json` and restarted the app.
`pnpm-lock.yaml` has been deleted and re-generated as expected.

Application works fine.

2021-01-26 13:18 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
> +        Assert.assertEquals("expected pnpm version 4.5.0 rejected",
Right, so after testing and then reading further the linked issue comments it seems that:
When I have an existing pnpm 4.5.0 installed to `.vaadin`, it is logged that it would be used but it is actually not as it is determined to be too old, instead `npx` is installing and running the default version instead but I didn't see any logs for this. 

The side effect of this is that I don't really know which version of pnpm is used, but maybe that is not so important. But the false log of "using pnpm from .vaadin" could be removed ?

2021-01-26 13:57 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +        if (!ignoreVersionChecks && !checkPnpmVersion(pnpmCommand)) {
Rewrote the whole method in functional style, which also made it shorter. Slightly changed the behavior so that even if `ignoreVersionChecks` is true it runs `npx pnpm .... --version` (but ignores the reported version) so that it at least fails fast also in this case if the pnpm command can't be run at all (should only happen if something is seriously broken).

2021-01-26 13:58 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +                    "pnpm@" + DEFAULT_PNPM_VERSION);
The statement mutated `pnpmCommand` which was not only passed to the version check but returned from the method and to be used for the actual pnpm command. However, using the array like this was maybe bad style; now rewritten using only immutables.

2021-01-26 13:59 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +    private boolean checkPnpmVersion(List<String> pnpmCommand) {
Changed to `validatePnpmVersion`. Also the `ignoreVersionChecks` flag is now checked in this method instead.

2021-01-26 13:59 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +                        .warn("pnpm at '{}' is version {} which is not supported (expected >={})",
`warn` -> `info`

2021-01-26 13:59 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +            getLogger().warn("error checking pnpm version", e);
Added the full command to log so that user can test run it manually in console.

2021-01-26 14:00 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
> +                    deletePnpmLockFile();
Deletion should happen only when `package.json` is updated due to platform updates, so quite rarely. Test both suggestions given here https://github.com/pnpm/pnpm/issues/2587#issuecomment-636169750 and deleting the lockfile followed by `install` was not perceived slower than the alternative `update --depth Infinity`.

2021-01-26 14:00 UTC, joheriks commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
> +        Assert.assertEquals("expected pnpm version 4.5.0 rejected",
It shouldn't start failing. Node.JS and npm/npx scripts auto-installed by Vaadin go into `~/.vaadin/node` (scripts in `~/.vaadin/node/node_modules`), while `pnpm` installed by Vaadin currently goes into `~/.vaadin/node_modules/pnpm`. So the `npx pnpm` command (`~/.vaadin/node/node ~/.vaadin/node/node_modules/npm/bin/npx-cli.js pnpm` if the user has relied on Vaadin-installed Node.js) will run a `pnpm` version independent of old Vaadin-installed `pnpm`. It will fetch the latest version and cache it in `~/.npm`. So for the first bullet point, there is no need to do anything. For the second, the user (globally) installed version will be too old so it will try to get a supported version (5.15.1) instead.

2021-01-26 14:03 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +    public static final int SUPPORTED_PNPM_MINOR_VERSION = 0;
Done.

2021-01-26 14:03 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
>          if (!pnpmCommand.isEmpty()) {
It would have propagated the empty command and higher in the call chain. However, this could not happen as `ensurePnpm` will now always either throw an exception or return a non-empty list. Added an `assert` here to clarify this.

2021-01-26 14:03 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +                    "unable to locate pnpm of supported version");
Done.

2021-01-26 14:04 UTC, joheriks commented on flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
> +            // Otherwise look for regular `npm`/`npx`
Added some comments to describe the search logic. Note that it may need to be changed at some point (see #9863).

2021-01-26 14:04 UTC, joheriks commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
> +        tools = new FrontendTools(baseDir, () -> vaadinHomeDir, "v14.15.4",
Done.

2021-01-26 14:33 UTC, mshabarov approved these changes

2021-01-26 14:43 UTC, joheriks commented on flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
> +        Assert.assertEquals("expected pnpm version 4.5.0 rejected",
It is true that the `pnpm` version that it chooses to use is a bit non-deterministic due to how `npx pnpm` selects the version (on the other hand, this also held true to some degree when we defaulted to global `pnpm` in command search path; in most cases this would be the latest version of `pnpm` at the time the user installed it). 

The thing to perhaps decide is what should be the supported way of using a specific `pnpm` version if the user has this requirement, and document it. One way that will already work after this PR is to install global Node.js and then do e.g. `npm i -g pnpm@5.15.2`. Then this version will be invoked when doing `npx pnpm install`.

Followup question is whether it should also be supported to fiddle with project-local installations into `project/node_modules` and/or `project/node/node_modules` (with `frontend-maven-plugin`). This is where it gets hairy, with a package manager installing itself into the managed packages...

2021-01-26 15:20 UTC, platosha submitted a review, later dismissed

2021-01-27 08:26 UTC, pleku approved these changes

2021-01-27 09:23 UTC, merged