Backport lit support.
vaadin/flow pull request #9878
Opened 2021-01-26 13:17 UTC by caalador

Fixes #8862

2021-01-27 06:12 UTC, denis-anisimov requested changes
There is a polymer module created in the PR.
It's not clear whether this should be done at all or in this PR.
At the same time polymer related classes are in both modules: polymer and flow-server.

If polymer needs to be extracted then everything should go into polymer module.
If not then moved classes should stay in flow-server

2021-01-27 06:12 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
> +    private static final Pattern LIT_TEMPLATE_PATTERN = Pattern.compile(
Is it the same as in the `master` ?
Looks quite weird that polymer template module contains Lit template methods.

2021-01-27 06:12 UTC, denis-anisimov commented on flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/rpc/PublishedServerEventHandlerRpcHandler.java
> +public class PublishedServerEventHandlerRpcHandler implements Serializable {
This is a breaking change though the class is internal

2021-01-27 06:12 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/IdCollector.java
> +import com.vaadin.flow.component.Component;
This class is not moved to the polymer template module though it's in the polymer package.

2021-01-27 06:12 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/IdMapper.java
> +    private Component template;
The package of this class is polymer template but it's in the flow-server.

2021-01-27 06:12 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java
> +import com.vaadin.flow.component.dependency.JsModule;
This class is not moved to the polymer template module

2021-01-27 06:12 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateParser.java
> +     * Template parser factory.
Polymer template class is in the flow-server module

2021-01-27 07:28 UTC, caalador commented on flow-bom/pom.xml
> +                <artifactId>flow-polymer-template</artifactId>
I was expecting not to and keep Polymer in the server module.

2021-01-29 09:43 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
> +    private static final Pattern LIT_TEMPLATE_PATTERN = Pattern.compile(
It's not there in master, but it was changed in a deprecate polymer commit which is not applicable here.

2021-01-30 06:29 UTC, denis-anisimov requested changes

2021-01-30 06:29 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/Id.java
> + * public class Details extends LitTemplate {
I think _this_ `Id`  annotation should be deprecated and not changed.
And additional `Id` in the package outside of `polymertemplate` should be introduced in the same was is it has been done in the `master`.
This is not a breaking change since you still may use the old `Id`  with polymer templates.
But in Lit template one has to use the new `Id` .
The open question should new `Id` also work in polymer templates ? 
I think yes to avoid confusions with imports.
That will require to add logic into the polymer template id collector to recognize both `Id`  (which already in the `master`).

But it's quite weird to use `Id` in Lit template with `Id`  being in the polymer template package.

2021-01-30 06:29 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/InjectablePolymerElementInitializer.java
> +public class InjectablePolymerElementInitializer
That functionality introduces attributes/properties initialization for PolymerTemplate (from the template content into Java).
Should we backport it at all?
Should we backport it in this PR ?

Also I believe the same functionality is for LitTemplate. 
Should it also be backported along with LitTemplates ?
LitTemplate is a new functionality overall so i think yes, we should backport it along with LitTemplates.
But for PolymerTemplate it may cause unexpected changes in the existing applications.

2021-01-30 06:29 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/InjectablePolymerElementInitializerTest.java
> +public class InjectablePolymerElementInitializerTest {
This test is for Polymer template functionality which sets attribute from the template file content to the Java object.
So should this bebackported
(and the same question is for all the related classes to this functionality)?

2021-02-01 11:24 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/InjectablePolymerElementInitializer.java
> +public class InjectablePolymerElementInitializer
It is considered a new improvement for the existing polymer templates. This has been communicated clearly last year and I just checked that the feedback has only been about "how this makes an existing add-on useless".

So this is intended.

2021-02-01 11:25 UTC, pleku commented on flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/InjectablePolymerElementInitializerTest.java
> +public class InjectablePolymerElementInitializerTest {
This is like intended

2021-02-01 11:38 UTC, pleku commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/Id.java
> + * public class Details extends LitTemplate {
The idea is that
1) Nothing related to polymer templates should be deprecated in 14 as it is not going away and we don't want to push people to get worried they have to do something. We have announced however the direction and are now giving them the possibility to migrate gradually within the 14-series and then have easier moving to nextLTS where polymer is deprecated but not removed.
2) NO changes should be needed when going from 14.4 to 14.5 when you have existing polymer templates
3) NO changes should be needed when going from 14.5 with lit templates to 19+, or with polymer templates from 14.5 to 19+

Is there something that cannot be done according to 1-3 with the backporting ?

2021-02-01 12:24 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/Id.java
> + * public class Details extends LitTemplate {
Will keep polymer as is, but add the new Id for Lit usage so then there should be no changes needed for current or when updating to 18+

2021-02-01 12:56 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/InjectablePolymerElementInitializer.java
> +public class InjectablePolymerElementInitializer
It's not clear for me why this is a part of _lit templates_  backport ?

I don't have a strong objection but it's not really correct to put changes which are not related to the main topic of this backport regardless of confirmed improvement.

2021-02-01 12:58 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/Id.java
> + * public class Details extends LitTemplate {
It will be confusing If you can't use new `Id` with Polymer templates (didn't get the exact intention from the last comment).

2021-02-01 13:00 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/Id.java
> + * public class Details extends LitTemplate {
Polymer template still uses the polymertemplate.Id where as list should use template.Id

2021-02-01 13:00 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/Id.java
> + * public class Details extends LitTemplate {
OK I see from the impl that both Ids can be used in the polymer templates.

2021-02-01 13:05 UTC, caalador commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/InjectablePolymerElementInitializer.java
> +public class InjectablePolymerElementInitializer
8988 introduced the feature to lit and polymer at the same time.

2021-02-01 13:59 UTC, denis-anisimov commented on flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/InjectablePolymerElementInitializer.java
> +public class InjectablePolymerElementInitializer
Should 8988 be backported separately then ?

Again : up to you.

2021-02-01 13:59 UTC, denis-anisimov submitted a review, later dismissed

2021-02-02 07:09 UTC, caalador commented
Rebased on branch to get browser fix.

2021-02-02 08:40 UTC, pleku approved these changes

2021-02-02 09:01 UTC, merged