feat: Backport url parameter template support
vaadin/flow pull request #9895
Opened 2021-01-27 13:23 UTC by mshabarov

Fixes: https://github.com/vaadin/flow/issues/9850

2021-02-03 14:55 UTC, taefi requested changes

2021-02-03 14:55 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
> +import org.mockito.Mockito;
These imports belongs to the import block above `com.vaadin.*` imports.

2021-02-03 14:55 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/router/RoutingTestBase.java
> +import org.mockito.Mockito;
Please reorder these imports in the correct format.

2021-02-03 14:55 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/router/internal/AbstractRouteRegistryTest.java
> +import com.vaadin.flow.server.InvalidRouteConfigurationException;
Please reorder imports.

2021-02-03 14:55 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/router/internal/AbstractRouteRegistryTest.java
> +import org.junit.rules.ExpectedException;
Please move up this import.

2021-02-03 14:55 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/router/internal/ConfigureRoutesTest.java
> +import org.junit.rules.ExpectedException;
Please reorder these imports.

2021-02-03 14:55 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/router/internal/RouteModelTest.java
> +import org.junit.Test;
Please move up these imports,

2021-02-03 14:55 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/SessionRouteRegistryTest.java
> +import com.vaadin.flow.router.internal.HasUrlParameterFormat;
Please add a new line after this import.

2021-02-03 14:55 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
> +import com.vaadin.tests.util.MockUI;
Please move these imports down.

2021-02-03 14:55 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
> +import org.mockito.Mockito;
Please move up these imports.

2021-02-03 14:55 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/theme/ThemeUtilTest.java
> +
I could not locate this change in non of the PRs addressed by this PR. Please verify this change was intentional and not ported here through auto merging.

2021-02-03 14:59 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/theme/ThemeUtilTest.java
> +
This change caused by deprecation of `UI.getRouter()`. Since now the `UI.getInternals().getRouter()` is used, this tests needs more mocking for `UIInternals`.

2021-02-03 15:05 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +        initializeUIWithRouter(request, ui);
`initializeUIWithRouter` apparently has been introduced somewhen in the middle between 2.5 and 6 of flow. Basically the method `initializeUIWithRouter` contains exactly the same code which has been deleted, but with `ui.getInternals().getRouter()`.

2021-02-03 15:07 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
> +    }
Same as above. `initializeUIWithRouter ` just wraps the removed code and uses ui internals.

2021-02-03 15:22 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/component/UITest.java
> +    }
This change has been made even before the Url template feature.
It is from this commit https://github.com/vaadin/flow/commit/70fc1c5edd2d40c5a7af5db0a32031859c1cf02b.
I believe it's safe to leave it here, but I need to add an addition unit test from this commit.

2021-02-03 15:26 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/component/UI.java
>  import org.slf4j.LoggerFactory;
done

2021-02-03 15:27 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentUI.java
> +import org.slf4j.LoggerFactory;
done

2021-02-03 15:28 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/router/BeforeEnterEvent.java
> +        super(router, trigger, location, navigationTarget, parameters, ui, layouts);
done

2021-02-03 15:28 UTC, mshabarov commented on flow-server/src/main/java/com/vaadin/flow/router/internal/DefaultRouteResolver.java
> +import org.slf4j.LoggerFactory;
done

2021-02-03 15:33 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/component/InvalidUrlTest.java
>  import org.junit.After;
done

2021-02-03 15:35 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/component/UITest.java
> +import org.mockito.Mockito;
done

2021-02-03 15:39 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/router/RouteConfigurationTest.java
> +import com.vaadin.flow.router.internal.HasUrlParameterFormat;
done

2021-02-03 15:39 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/router/RouterConfigurationUrlResolvingTest.java
> +import com.vaadin.flow.router.internal.HasUrlParameterFormat;
done

2021-02-03 15:42 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
> +import org.mockito.Mockito;
done

2021-02-03 15:42 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/router/RoutingTestBase.java
> +import org.mockito.Mockito;
done

2021-02-03 15:42 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/router/internal/AbstractRouteRegistryTest.java
> +import com.vaadin.flow.server.InvalidRouteConfigurationException;
done

2021-02-03 15:43 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/router/internal/AbstractRouteRegistryTest.java
> +import org.junit.rules.ExpectedException;
done

2021-02-03 15:43 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/router/internal/ConfigureRoutesTest.java
> +import org.junit.rules.ExpectedException;
done

2021-02-03 15:43 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/router/internal/RouteModelTest.java
> +import org.junit.Test;
done

2021-02-03 15:44 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/SessionRouteRegistryTest.java
> +import com.vaadin.flow.router.internal.HasUrlParameterFormat;
done

2021-02-03 15:45 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
> +import com.vaadin.tests.util.MockUI;
done

2021-02-03 15:45 UTC, mshabarov commented on flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
> +import org.mockito.Mockito;
done

2021-02-04 08:55 UTC, taefi requested changes

2021-02-04 08:55 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/component/InvalidUrlTest.java
> +import static org.junit.Assert.assertEquals;
I think this import misplaced up here.

2021-02-04 08:55 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/component/UITest.java
> +import static org.junit.Assert.assertTrue;
Are these imports misplaced here?

2021-02-04 08:55 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/router/RouteConfigurationTest.java
> +import javax.servlet.ServletContext;
This should be up there above `java.*` imports.

2021-02-04 08:55 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/router/RouteConfigurationTest.java
> +import net.jcip.annotations.NotThreadSafe;
And this one belongs to _all other imports_ block.

2021-02-04 08:55 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/router/RouterConfigurationUrlResolvingTest.java
> +import net.jcip.annotations.NotThreadSafe;
And this one belongs to _all other imports_ block.

2021-02-04 08:55 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
> +import javax.servlet.http.HttpServletResponse;
This should be up there above `java.*` imports.

2021-02-04 08:55 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
> +import static org.junit.Assert.assertThat;
These are belong to the lowest imports block.

2021-02-04 08:55 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
> +import net.jcip.annotations.NotThreadSafe;
And this one belongs to _all other imports_ block.

2021-02-04 08:55 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/SessionRouteRegistryTest.java
> +import javax.servlet.ServletContext;
And this one belongs to above `java.*` imports block.

2021-02-04 08:55 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
> +import javax.servlet.http.HttpSessionBindingEvent;
These are belong to the above of `java.*` imports block.

2021-02-04 08:55 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
> +import net.jcip.annotations.NotThreadSafe;
And this one belongs to _all other imports_ block.

2021-02-04 08:55 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
> +import javax.servlet.ServletException;
These to belong to the above of `java.*` imports block.

2021-02-04 09:40 UTC, taefi requested changes

2021-02-04 09:40 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
>  import java.io.ByteArrayInputStream;
```suggestion
import javax.servlet.ServletConfig;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import javax.servlet.http.HttpSessionBindingEvent;

import java.io.ByteArrayInputStream;
```

2021-02-04 09:40 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
> +import javax.servlet.http.HttpSessionBindingEvent;
```suggestion
```

2021-02-04 09:40 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
> +import net.jcip.annotations.NotThreadSafe;
```suggestion
```

2021-02-04 09:40 UTC, taefi commented on flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
> +
```suggestion

import net.jcip.annotations.NotThreadSafe;
```

2021-02-04 09:50 UTC, taefi approved these changes

2021-02-04 11:07 UTC, merged