build: enable reuse of forks during unit tests
vaadin/flow pull request #9943
Opened 2021-02-02 07:21 UTC by miguelatvaadin

Several changes which enable reusing forks during the surefire (unit tests) phase. As a result, a new jvm is not started for each unit test class and a 5 minute build time gain is experienced for the full build.

Fixes: #9885

2021-02-02 13:37 UTC, denis-anisimov requested changes

2021-02-02 13:37 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
> +    public static void beforeClass() {
It's executed once for this test class.
What does this solve ?
I would expect this call in `@Before` instead `@BeforeClass` so it's not clear what does this do.

2021-02-02 13:37 UTC, denis-anisimov commented on pom.xml
> +                        <!--
Comments should either have explanation or removed.

2021-02-02 14:23 UTC, miguelatvaadin commented on pom.xml
> +                        <!--
no problem. I will definitely remove it. Thanks!

2021-02-02 15:12 UTC, miguelatvaadin commented on flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
> +    public static void beforeClass() {
This call solves an issue which arises when reusing forks. For some reason some trash is left there by a previous test from another class and, as a result, one of these tests fails so some clearance must be done. It was not a problem when a new jvm was instantiated for each test class, but now it is made visible.

`CurrentInstance.clearAll();` only needs to be called once for the whole class, before all these tests run. That's why I placed it in the `@BeforeClass`.

2021-02-03 12:03 UTC, denis-anisimov commented on flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
> +    public static void beforeClass() {
Alright, thanks for explanation.

2021-02-03 12:03 UTC, denis-anisimov approved these changes

2021-02-03 12:04 UTC, merged